getsolus/packages

- packages/c/claws-mail/abi_symbols
- packages/c/claws-mail/abi_used_symbols
- packages/c/claws-mail/files/org.claws_mail.Claws-Mail.appdata.xml
- packages/c/claws-mail/package.yml
- packages/c/claws-mail/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://www.claws-mail.org/news.php).
**Test Plan**
- Installed and setup an account.
**Checklist**
- Appstream metadata added from flathub.
> claws-mail: update to 4.3.0

- packages/e/eza/package.yml
- packages/e/eza/pspec_x86_64.xml
**Summary**
- Use NaiveDateTime::from_timestamp_opt instead of panicky From impl
**Test Plan**
List files in a directory.
**Checklist**
> eza: Update to 0.18.22

- common/Scripts/worklog.py
**Summary**
This is a simple fix for a linter error which was causing failures in unrelated PRs.
**Test Plan**
1. Test out `worklog.py`. See that it works perfectly.
2. Run `flake8` against `worklog.py`. See that it fails.
3. Check out this PR.
4. Run `flake8` against `worklog.py` again. See that it passes. 
5. Try `worklog.py` again and see that it functions in the same way.
**Checklist**
> common/Scripts/worklog.py: Fix missing whitespace

- packages/f/fzf/package.yml
- packages/f/fzf/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://github.com/junegunn/fzf/releases/tag/v0.54.0).
**Test Plan**
- Installed did some fuzzy finding and checked the version.
**Checklist**
-  [X] Package was built and tested against unstable
> fzf: update to 0.54.0

- packages/h/hyphen-de/package.yml
- packages/h/hyphen-de/pspec_x86_64.xml
**Summary**
- No upstream changelog
- Switch to git source, no tarball available
- Add homepage` key to `package.yml` (Part of getsolus/packages#411)
- Resolves getsolus/packages#2640
**Test Plan**
Need german speaker to actually test it
**Checklist**
> hyphen-de: Update to 2022.09.23

- packages/l/lightdm-gtk-greeter-settings/monitoring.yml
- packages/l/lightdm-gtk-greeter-settings/package.yml
- packages/l/lightdm-gtk-greeter-settings/pspec_x86_64.xml
**Summary**
- [changelog](https://github.com/Xubuntu/lightdm-gtk-greeter-settings/releases/tag/lightdm-gtk-greeter-settings-1.2.3)
- add homepage
**Test Plan**
change settings in vm
**Checklist**
> lightdm-gtk-greeter-settings:  Update to 1.2.3

- packages/l/labwc/package.yml
- packages/l/labwc/pspec_x86_64.xml
**Summary**
Minor update, crash related to pipemenus
Full release note: [0.7.4](https://github.com/labwc/labwc/releases/tag/0.7.4)
**Test Plan**
It was updated, and it loads the previous configuration with zero issues
**Checklist**
> labwc: update to 0.7.4

- packages/a/antidote/package.yml
- packages/a/antidote/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://github.com/mattmc3/antidote/releases/tag/v1.9.7).
**Test Plan**
- Checked plugins.
**Checklist**
> antidote: update to 1.9.7

- packages/f/fb2converter/package.yml
- packages/f/fb2converter/pspec_x86_64.xml
**Summary**
- [changelog](https://github.com/rupor-github/fb2converter/compare/v1.75.1...v1.75.2)
**Test Plan**
- fb2c convert --to epub file.fb2
**Checklist**
> fb2converter: Update to 1.75.2

- packages/s/sof-firmware/package.yml
- packages/s/sof-firmware/pspec_x86_64.xml
**Summary**
For v2.10 series, the following new topology files have been added since v2.9:
v2.10.x/sof-ipc4-tplg-v2.10
├── sof-lnl-rt1318-l12-rt714-l0.tplg
├── sof-lnl-rt711-4ch.tplg
├── sof-lnl-rt711-l0-rt1316-l23-rt714-l1.tplg
├── sof-lnl-rt712-l2-rt1712-l3.tplg
├── sof-lnl-rt722-l0.tplg
├── sof-mtl-max98357a-rt5682-google-aec.tplg
├── sof-mtl-max98357a-rt5682-ssp2-ssp0-2ch-pdm1-google-aec.tplg ├── sof-mtl-max98357a-rt5682-ssp2-ssp0-google-aec.tplg ├── sof-mtl-rt5650-dts-google-aec.tplg
├── sof-mtl-rt5650.tplg
├── sof-mtl-rt711-l0-rt1316-l3-2ch.tplg
├── sof-mtl-rt711-l0-rt1316-l3-4ch.tplg
├── sof-mtl-rt711-l0-rt1316-l3.tplg
├── sof-mtl-rt712-l0.tplg
├── sof-mtl-rt712-vb-l0.tplg
├── sof-mtl-rt713-l0-rt1318-l12-rt1713-l3.tplg
├── sof-mtl-rt713-l0-rt1318-l1-rt1713-l3.tplg
Full release …
> sof-firmware: update to 2.10

- packages/b/bottom/abi_used_symbols
- packages/b/bottom/monitoring.yml
- packages/b/bottom/package.yml
- packages/b/bottom/pspec_x86_64.xml
**Summary**
- Fix building with Rust 1.80.0
**Test Plan**
Run `btm` and see that all graphs worked as expected.
**Checklist**
> bottom: Update to 0.9.7

- packages/l/libheif/abi_symbols
- packages/l/libheif/abi_used_symbols
- packages/l/libheif/package.yml
- packages/l/libheif/pspec_x86_64.xml
**Summary**
This releases fixes the syntax of the `vvcC` box and a few build issues
**Test Plan**
Encoded, decoded and viewed a couple of HEIF images
**Checklist**
> libheif: Update to 1.18.1

- packages/s/starship/abi_used_libs
- packages/s/starship/abi_used_symbols
- packages/s/starship/package.yml
- packages/s/starship/pspec_x86_64.xml
**Summary**
- color: add prev_fg and prev_bg as color specifiers based on the previous foreground/background colors respectively
- color: add prevfg,prevbg as color specifiers based on the previous foreground/background colors respectively
- gcloud: Disabled gcloud module when active config hasn't been set
- purescript: add support for spago-next configuration files
- custom: escape characters in command output by default
- direnv: replace nonexistent "orange" color with "bright-yellow"
- dotnet: Remove duplicate v in dotnet version
- k8s: don't trigger if scan config is set but env vars are not
- preset: fix typo in Open Policy Agent module format string
- k8s: Improve performance of kubeconfig module
**Security**
- CVE-2024-41815 …
> starship: Update to 1.20.0

- packages/f/fb2converter/package.yml
- packages/f/fb2converter/pspec_x86_64.xml
**Summary**
- Handle "hanging" images within floating notes.
- [changelog](https://github.com/rupor-github/fb2converter/compare/v1.75.2...v1.75.3)
**Test Plan**
- fb2c convert --to epub in.fb2
**Checklist**
> fb2converter: Update to 1.75.3

- packages/g/gpxsee/abi_used_symbols
- packages/g/gpxsee/package.yml
- packages/g/gpxsee/pspec_x86_64.xml
**Summary**
- Improved ENC maps rendering.
- Various minor fixes.
**Test Plan**
- zoom in and out a map
**Checklist**
> gpxsee: Update to 13.23

- packages/m/mu/abi_used_symbols
- packages/m/mu/package.yml
- packages/m/mu/pspec_x86_64.xml
**Summary**
- improved documentation
- fix mu4e-compose-pre-hook
- fix bookmark support
- [changelog](https://github.com/djcb/mu/releases/tag/v1.12.6)
**Test Plan**
- search for and view message
**Checklist**
> mu: Update to 1.12.6

- packages/l/libwpe/abi_symbols
- packages/l/libwpe/monitoring.yml
- packages/l/libwpe/package.yml
- packages/l/libwpe/pspec_x86_64.xml
**Summary**
- added homepage
- remove dependency on x11
- full changelog [here](https://github.com/WebPlatformForEmbedded/libwpe/blob/1.16.0/NEWS)
**Checklist**
> libwpe: Update to 1.16.0

- packages/l/lz4/package.yml
- packages/l/lz4/pspec_x86_64.xml
**Summary**
- update lz4 from 1.9.4 to 1.10.0
- add homepage to package.yml
- Full lz4 [(changelog](https://github.com/lz4/lz4/releases/tag/v1.10.0))
**Test Plan**
Build and install lz4.  Compress various files and file types.  Extract / decompress those files back to their original state.
Confirm homepage is in package.yml file.
The build procedure for lz4 includes many internal tests - all are successful.
**Checklist**
> lz4: Update to 1.10.0

- packages/t/thunar/abi_used_symbols
- packages/t/thunar/monitoring.yml
- packages/t/thunar/package.yml
- packages/t/thunar/pspec_x86_64.xml
**Summary**
- Use parent windows for undo/redo dialog
- Fix for `misc_open_new_windows_in_split_view`
- Don't add directories to `recent:///`
- Focus split view pane on DnD events
- Don't reload folder when `draw_frames` is set
- Allow submenu UCAs in toolbar
- Fix shortcuts for ucas in subfolders
- Don't show 'open location' on recent icon
- Fix for image preview visibility
- Prevent focus stealing of file transfer dialog
- Don't update `last-view` when searching
**Test Plan**
Open Thunar and browse to different directories.
**Checklist**
> thunar: Update to 4.18.11

- packages/f/flatpak/files/flatpak-enable-flathub.service
- packages/f/flatpak/package.yml
- packages/f/flatpak/pspec_x86_64.xml
**Summary**
Enable flathub by default
**Test Plan**
- Install, reboot
- `flatpak remotes`
- Verify flathub is added
**Checklist**
> flatpak: Enable flathub by default

- packages/py/python-google-auth-httplib2/package.yml
- packages/py/python-google-auth-httplib2/pspec_x86_64.xml
**Summary**
Adds homepage to `python-google-auth-httplib2`
**Test Plan**
**Checklist**
> python-google-auth-httplib2: add homepage

- packages/py/python-html2text/package.yml
- packages/py/python-html2text/pspec_x86_64.xml
**Summary**
- Updates `python-html2text` to 2024.2.26 and adds homepage
- Full changelog [here](https://github.com/Alir3z4/html2text/blob/master/ChangeLog.rst#2024226)
**Test Plan**
- Run simple example from the readme file
**Checklist**
> python-html2text: update to 2024.2.26

- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
**Summary**
Full commit log available [here](https://github.com/notofonts/notofonts.github.io/compare/noto-monthly-release-24.7.1...noto-monthly-release-24.8.1)
**Test Plan**
- Checked everything looked alright in my DE where Noto Sans is set as system font
- Wrote some text with Noto Sans and Noto Serif in LibreOffice Writer 
**Checklist**
> noto-sans-ttf: Update to 24.8.1

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Remove redundant whitespace
- Update documentation for `gh api PATCH`
- Clarify usage of template flags for PR and issue creation
- Expose json databaseId field for release commands
- Expose `fullDatabaseId` for PR json export
- Handle `--bare` clone targets
- Slightly clarify when CLI exits with code 4
- Exit with 1 on authentication issues
- Add `--remove-milestone` option to `issue edit` and `pr edit`
**Test Plan**
Run `gh status`, `gh pr list`, and open this Pull Request.
**Checklist**
> github-cli: Update to 2.54.0

- packages/b/bottom/abi_used_symbols
- packages/b/bottom/package.yml
- packages/b/bottom/pspec_x86_64.xml
**Summary**
Changelog available [here](https://github.com/ClementTsang/bottom/blob/0.10.1/CHANGELOG.md#0101---2024-08-01).
**Test Plan**
Run `btm` and see that the graphs display as expected.
**Checklist**
> bottom: Update to 0.10.1

- packages/r/rawtherapee/abi_used_symbols
- packages/r/rawtherapee/files/0001-jpeg-turbo.patch
- packages/r/rawtherapee/package.yml
- packages/r/rawtherapee/pspec_x86_64.xml
**Summary**
- Backport patch for libjpeg-turbo
Fixes https://github.com/getsolus/packages/issues/3485
**Test Plan**
Launch RawTherapee and see that it doesn't crash on start.
**Checklist**
> rawtherapee: Backport patch for libjpeg-turbo

- packages/py/python-pkginfo/package.yml
- packages/py/python-pkginfo/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> python-pkginfo: Add homepage

- packages/p/perl-extutils-helpers/monitoring.yml
- packages/p/perl-extutils-helpers/package.yml
- packages/p/perl-extutils-helpers/pspec_x86_64.xml
**Summary**
Revert "Make split_like_shell always unixy"
**Test Plan**
Rebuild `perl-module-build-tiny` and `perl-readonly`
**Checklist**
> perl-extutils-helpers: Update to 0.027

- packages/e/eza/package.yml
- packages/e/eza/pspec_x86_64.xml
**Summary**
- **[breaking]** Implement `EZA_GRID_ROWS` grid details view minimum rows threshold
Before this change, the `EZA_GRID_ROWS` variable was ignored, despite documentation existing. Users relying on `EZA_GRID_ROW` not doing anything will find their output changed.
**Test Plan**
Run `eza` and `eza -l` in a directory.
**Checklist**
> eza: Update to 0.19.0

- packages/b/bottom/package.yml
- packages/b/bottom/pspec_x86_64.xml
**Summary**
- Add option to move the AVG CPU bar to another row in basic mode
- Fix the `--default_cpu_entry` argument not being checked
**Test Plan**
Run `btm` and see that the charts are displaying as expected.
**Checklist**
> bottom: Update to 0.10.2

- packages/l/libheif/abi_used_symbols
- packages/l/libheif/package.yml
- packages/l/libheif/pspec_x86_64.xml
**Summary**
Changes:
- Fix regression that Exif orientation was not correctly reset when converting rotated HEIF (`heif-dec`)
- Swap Exif width/height when rotating image by 90 degrees
- Fix memory leak in OpenJPEG decoding plugin
- Pay attention to `DESTDIR` variable when installing `heif-convert` symlink
**Test Plan**
- Encode and decode a couple of heif images
- View heif images in my image viewer (`eog`)
**Checklist**
> libheif: Update to 1.18.2

- packages/l/libytnef/abi_used_symbols
- packages/l/libytnef/package.yml
- packages/l/libytnef/pspec_x86_64.xml
**Summary**
- Update from version 2.0 to 2.1.2 
- changelog [2.1.2](https://github.com/Yeraze/ytnef/releases/tag/v2.1.2) 
- changelog [2.1.1](https://github.com/Yeraze/ytnef/releases/tag/v2.1.1) 
- changelog [2.1.0](https://github.com/Yeraze/ytnef/releases/tag/v2.1)
**Test Plan**
**Checklist**
> libytnef: update to 2.1.2

- packages/l/libva-vdpau-driver/abi_symbols
- packages/l/libva-vdpau-driver/abi_symbols32
- packages/l/libva-vdpau-driver/package.yml
- packages/l/libva-vdpau-driver/pspec_x86_64.xml
**Summary**
- Added homepage
- Following most recent commit
**Test Plan**
Ensure homepage key was added to pspec
**Checklist**
> libva-vdpau-driver: Update to 0.7.4 bump

- packages/py/python-pyrate-limiter/package.yml
- packages/py/python-pyrate-limiter/pspec_x86_64.xml
**Summary**
Changes:
- Address issue with SQLite backend
- Fix small bug in binary-search algo
- Update document on sync/async support
**Test Plan**
- Tested some examples from the project's README
- Confirmed `python-moddb` still works correctly
**Checklist**
> python-pyrate-limiter: Update to 3.6.2

- packages/p/perl-io-utf8-strict/abi_used_symbols
- packages/p/perl-io-utf8-strict/monitoring.yml
- packages/p/perl-io-utf8-strict/package.yml
- packages/p/perl-io-utf8-strict/pspec_x86_64.xml
**Summary**
Full changelog can be read [here](https://fastapi.metacpan.org/source/LEONT/PerlIO-utf8_strict-0.010/Changes)
**Test Plan**
Rebuild and run `biber`
**Checklist**
> perl-io-utf8-strict: Update to 0.010

- packages/l/libvips/abi_used_symbols
- packages/l/libvips/package.yml
- packages/l/libvips/pspec_x86_64.xml
**Summary**
Changes:
- fix dzsave of >8-bit images to JPEG
- jpegsave: fix chrominance subsampling mode with jpegli
- pngload: disable ADLER32/CRC checking in non-fail mode
- improve target_clones support check
- fix pipe read limit
- conva: fix a crash with {u,}{short,int} images
- fix vips_image_get_string
- heifsave: fix lossless mode
- composite: fix dest-atop blend mode
- fix vips_source_map for zero-length sources
**Test Plan**
Edited a few images using `vips`
**Checklist**
> libvips: Update to 8.15.3

- packages/py/python-pyrate-limiter/package.yml
- packages/py/python-pyrate-limiter/pspec_x86_64.xml
**Summary**
Changes:
- Add method to remove bucket
**Test Plan**
- Ran some examples from the project README
- Confirmed `python-moddb` still works
**Checklist**
> python-pyrate-limiter: Update to 3.7.0

- packages/d/doflicky/package.yml
- packages/d/doflicky/pspec_x86_64.xml
**Summary**
It's actually `GPL-2.0-or-later` according to the license headers
See e.g. https://github.com/Staudey/doflicky/blob/master/doflicky-ui#L6-L11
**Test Plan**
Confirmed the correct license was shown in Software Center
**Checklist**
> doflicky: Fix license

- packages/p/perl-extutils-installpaths/monitoring.yml
- packages/p/perl-extutils-installpaths/package.yml
- packages/p/perl-extutils-installpaths/pspec_x86_64.xml
**Summary**
Try to install any installable paths
**Test Plan**
Rebuild  `perl-extutils-config`, `perl-module-build-tiny` and `perl-readonly`
**Checklist**
> perl-extutils-installpaths: Update to 0.013

- common/Hooks/prepare-commit-msg.py
**Summary**
- If the version has been changed in the package.yml as part of the commit then prefill that information in the commit header. e.g. nano: Update to 1.2.3
**Test Plan**
Update some pkgs, verify commit info gets prefilled.
**Checklist**
> common/hooks: Prefill update info in commit msg

- packages/a/appstream-data/package.yml
- packages/a/appstream-data/pspec_x86_64.xml
**Summary**
Update Appstream Metainfo to v46
**Test Plan**
Build appstream-data from this PR. See that software centers like Discover still work.
**Checklist**
> appstream-data: Update to v46

- packages/c/curl/files/init-sigpipe.patch
- packages/c/curl/package.yml
- packages/c/curl/pspec_x86_64.xml
**Summary**
`transmission` started crashing during download after curl update 8.9.1 due to [this curl issue](https://github.com/curl/curl/issues/14344)
This backports the patch fixing the crash.
**Test Plan**
Successfully downloaded a torrent that would previously crash consistently
**Checklist**
> curl: Backport patch to fix transmission crash

- packages/w/weechat/abi_symbols
- packages/w/weechat/abi_used_symbols
- packages/w/weechat/package.yml
- packages/w/weechat/pspec_x86_64.xml
**Summary**
- **breaking:** relay/api: flatten JSON event object sent to clients, always set "body_type" and "body" (null if there is no body) in websocket frame, add body types buffers and lines (array), add field "request_id" in websocket frame (request and response)
- **breaking:** core, plugins: force "short_name" in buffers to non-empty value (name by default), remove buffer property "short_name_is_set"
- **breaking:** alias: display an error with `/alias add` or `/alias addcompletion` when the alias already exists, add options `addreplace` and `addreplacecompletion` in command `/alias`
- **breaking:** irc: rename parameter `-re` to `-raw` in command `/list`
- **breaking:** api: add constants for IPv6 and allow force of IPv6 in function hook_connect
- **breaking:** irc: convert …
> weechat: Update to 4.4.0

- packages/e/engrampa/abi_used_symbols
- packages/e/engrampa/package.yml
- packages/e/engrampa/pspec_x86_64.xml
**Summary**
- Fix extract of encrypted archives
- Fix volume split button in "Compress" window
- src/file-utils.c: Fix "error: implicit declaration of function ‘strcasecmp’..."
- fr-process.c: Setting error status
- Resolves https://github.com/getsolus/packages/issues/3595
**Test Plan**
- Installed checked version.
**Checklist**
> engrampa: Update to 1.28.2

- packages/p/picard/package.yml
- packages/p/picard/pspec_x86_64.xml
**Summary**
Update MusicBrainz Picard to the latest release.
Bugfixes:
- PICARD-2914 - macOS: Crash when opening options with Spanish UI
- PICARD-2939 - Crash when loading release with genre filters resulting in empty genre list
- PICARD-2940 - Possible bug with locking in Metadata.__iter__
- PICARD-2946 - Fix display length value in AppStream metadata
Release notes [here](https://github.com/metabrainz/picard/releases/tag/release-2.12.1)
Full changelog [here](https://github.com/metabrainz/picard/compare/release-2.11...release-2.12.1)
**Test Plan**
Launch picard and add Music folder. Let it identify and correct music metadata, then update files when complete.
**Checklist**
> picard: Update to 2.12.1

- packages/v/vgrep/package.yml
- packages/v/vgrep/pspec_x86_64.xml
**Summary**
- handle *grep errors
- add GitHub workflows
- build(deps): bump golang.org/x/term from 0.19.0 to 0.20.0
- update golangci-lint to v1.57.2
- build(deps): bump golang.org/x/term from 0.18.0 to 0.19.0
- build(deps): bump golang.org/x/term from 0.17.0 to 0.18.0
- update copyright date to 2024
- bump go.mod to 1.21
- update github.com/rivo/uniseg
- build(deps): bump golang.org/x/term from 0.16.0 to 0.17.0
- bump golangci-lint to 1.55.2
- build(deps): bump golang.org/x/term from 0.15.0 to 0.16.0
- build(deps): bump golang.org/x/term from 0.14.0 to 0.15.0
- build(deps): bump golang.org/x/term from 0.13.0 to 0.14.0
**Test Plan**
- Ran example commands from github.
**Checklist**
> vgrep: Update to 2.8.0

- packages/t/tailscale/package.yml
- packages/t/tailscale/pspec_x86_64.xml
**Summary**
- Captive portal detection is now supported.
- The tailscale cert command now contains the --min-validity flag
- The tailscale lock command now supports passing keys as files
- A warning is now raised if unable to forward DNS queries
- Mitigate low throughput over high latency networks
- [changelog](https://tailscale.com/changelog#2024-08-19)
**Test Plan**
**Checklist**
> tailscale: Update to 1.72.0

- packages/l/lime3ds/abi_used_libs
- packages/l/lime3ds/abi_used_symbols
- packages/l/lime3ds/package.yml
- packages/l/lime3ds/pspec_x86_64.xml
**Summary**
Bugfixes:
- Fix a known crash in 2 games caused by invalid cubemap face IDs
- Fix interface language sometimes being detected incorrectly
- All hotkeys now work correctly when using 2-window layout
Improvements:
- The "report compatibility" button now links to the Lime3DS compatibility repo
- Frame advancing is now possible while emulation is paused.
Release notes for 2117 [here](https://github.com/Lime3DS/Lime3DS/releases/tag/2117) (note that 2117.1 has no user-facing changes vs. 2117)
Full changelog [here](https://github.com/Lime3DS/Lime3DS/compare/2116...2117.1)
**Test Plan**
Launch a few titles and make sure things look and sound alright
**Checklist**
> lime3ds: Update to 2117.1

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Update `gh variable get` to use repo host
- Improve Unix compliance in `gh repo set-default`
- Document that `gh run download` downloads the latest artifact by default
- Improve `gh release create --notes-from-tag` behavior with multiline tag annotation
- Add `pr create --editor`
- Improve documentation for pr checks and exit codes
- Fix behavior for `gh issue develop -b does-not-exist-on-remote`
- Update `--project <number>` flags in `gh search` to `owner/number`
**Test Plan**
**Checklist**
> github-cli: Update to 2.55.0

- packages/p/perl-image-exiftool/package.yml
- packages/p/perl-image-exiftool/pspec_x86_64.xml
**Summary**
- Properly implement patch of 12.45 to avoid duplicating raw data when writing Sony ARW images where the raw data is double-referenced as both strips and tiles
- Improved handling of bad offsets in HtmlDump output
- Resolves https://github.com/getsolus/packages/issues/3647
**Test Plan**
- Checked in Digikam that this new version was loaded.
**Checklist**
- Did not update to the requested version as that is not a production release. 12.76 is the latest for production.
> perl-image-exiftool: Update to 12.76

- packages/o/obs-vkcapture/package.yml
- packages/o/obs-vkcapture/pspec_x86_64.xml
**Summary**
Changes:
- Fixed build issues with latest OBS
**Test Plan**
Recorded footage from a Vulkan game
**Checklist**
> obs-vkcapture: Update to 1.5.1

- packages/e/egl-wayland/package.yml
- packages/e/egl-wayland/pspec_x86_64.xml
**Summary**
Changes:
- Fix a crash due to an assertion firing during surface destruction, which affected Qt6 webengine
- Add an explicit dependency on the EGL headers
**Test Plan**
- Test akregator and confirm it no longer segfaults
(still seems to crash intermittently without `__NV_DISABLE_EXPLICIT_SYNC` though)
**Checklist**
> egl-wayland: Update to 1.1.16

- packages/f/fb2converter/package.yml
- packages/f/fb2converter/pspec_x86_64.xml
**Summary**
- [changelog](https://github.com/rupor-github/fb2converter/compare/v1.75.2...v1.75.4)
**Test Plan**
- fb2c convert --to epub in.fb2
**Checklist**
> fb2converter: Update to 1.75.4

- packages/p/protontricks/files/vdf-29-support.patch
- packages/p/protontricks/package.yml
- packages/p/protontricks/pspec_x86_64.xml
- packages/py/python-vdf/files/new-format-compat.patch
- packages/py/python-vdf/package.yml
- packages/py/python-vdf/pspec_x86_64.xml
**Summary**
This updates `python-vdf` and `protontricks` so they are compatible with the new vdf format in the current Steam beta
**Test Plan**
Used `protontricks` to install components into a game's proton prefix.
**Checklist**
> Update python-vdf and protontricks for new Steam vdf format

- packages/s/scrcpy/abi_used_symbols
- packages/s/scrcpy/package.yml
- packages/s/scrcpy/pspec_x86_64.xml
**Summary**
- Control-only option
- Pause/unpause display
- Mouse hover
- Mouse bindings
- Audio mirroring
- Secondary mouse bindings
- [2.5](https://github.com/Genymobile/scrcpy/releases/tag/v2.5)
- [2.6](https://github.com/Genymobile/scrcpy/releases/tag/v2.6)
- [2.6.1](https://github.com/Genymobile/scrcpy/releases/tag/v2.6.1)
**Test Plan**
Succesfully mirrored my phone's screen
(Note: can't currently test mouse control of device due to a Xiaomi bug)
**Checklist**
> scrcpy: Update to 2.6.1

- packages/n/nano-syntax-highlighting/files/0001-Fix-git-commit-colours-for-dark-terminals.patch
- packages/n/nano-syntax-highlighting/package.yml
- packages/n/nano-syntax-highlighting/pspec_x86_64.xml
- packages/n/nano/package.yml
- packages/n/nano/pspec_x86_64.xml
- packages/n/nanorc/package.yml
- packages/n/nanorc/pspec_x86_64.xml
**Summary**
- Initial inclusion at version 2022.11.02
- Resolves https://github.com/getsolus/packages/issues/2615
**Test Plan**
- Checked some highlighting.
**Checklist**
Nano depends on nanorc which conflicts with nano-syntax-highlighting. So this wont build without the conflicts tag. After this is pushed then nanorc can be deprecated at whole.
> nano-syntax-highlighting: add at 2022.11.02

- packages/f/flask-cors/package.yml
- packages/f/flask-cors/pspec_x86_64.xml
**Summary**
Changes:
- Backwards Compatible Fix for CVE-2024-6221
- Add unit tests for Private-Network
**Security**
- CVE-2024-6221
**Test Plan**
Executed some example from the project's README
**Checklist**
> flask-cors: Update to 4.0.2

- packages/m/mbedtls/files/0001-Fix-calloc-argument-order.patch
- packages/m/mbedtls/package.yml
- packages/m/mbedtls/pspec_x86_64.xml
**Summary**
Changes:
- CTR_DRBG prioritized over HMAC_DRBG as the PSA DRBG
- Fix the build in some configurations when check_config.h is not included
- Fix issue of redefinition warning messages for _GNU_SOURCE in entropy_poll.c and sha_256.c
- Fix error handling when creating a key in a dynamic secure element
- Fix a memory leak that could occur when failing to process an RSA key through some PSA functions due to low memory conditions
- Document and enforce the limitation of mbedtls_psa_register_se_key() to persistent keys
Full release notes available [here](https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-2.28.9)
**Security**
- CVE-2024-45157
**Test Plan**
Rebuilt and used `dolphin-emu` with this version
**Checklist**
> mbedtls: Update to 2.28.9

- packages/a/acpica-unix/abi_used_symbols
- packages/a/acpica-unix/package.yml
- packages/a/acpica-unix/pspec_x86_64.xml
**Summary**
- Changelog available [here](https://github.com/acpica/acpica/blob/master/documents/changes.txt)
**Test Plan**
- Hex-dump a random executable
**Checklist**
> acpica-unix: Update to 20240827

- packages/t/tickrs/package.yml
- packages/t/tickrs/pspec_x86_64.xml
**Summary**
- Part of https://github.com/getsolus/packages/issues/3111
- Resolves https://github.com/getsolus/packages/issues/3320
**Test Plan**
- Look at stocks
**Checklist**
> tickrs: Switch to rust macros

- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
**Summary**
Full commit log available [here](https://github.com/notofonts/notofonts.github.io/compare/noto-monthly-release-24.8.1...noto-monthly-release-24.9.1)
**Test Plan**
- Confirmed my system UI looks correct with Noto system fonts
- Wrote some text with Noto Sans/Serif in LibreOffice
**Checklist**
> noto-sans-ttf: Update to 24.9.1

- packages/p/pueue/abi_used_symbols
- packages/p/pueue/package.yml
- packages/p/pueue/pspec_x86_64.xml
**Summary**
- Changelog [here](https://github.com/Nukesor/pueue/releases/tag/v3.4.1)
**Packaging**
- Switch to cargo macros
- Part of https://github.com/getsolus/packages/issues/3111
**Test Plan**
- Start pueue and queue a command
**Checklist**
> pueue: Update to 3.4.1, switch to cargo macros

- packages/u/ufw/package.yml
- packages/u/ufw/pspec_x86_64.xml
**Summary**
Fix apparent packaging error.
Resolves getsolus/packages#3738
**Test Plan**
- Make sure users can not enable / disable ufw or modify firewall rules without sudo.
- Sanity check other distributions permissions for ufw.
- Confirm bash completions now work with ufw.
**Checklist**
> ufw: Fix permissions

- packages/d/dcfldd/abi_used_symbols
- packages/d/dcfldd/monitoring.yml
- packages/d/dcfldd/package.yml
- packages/d/dcfldd/pspec_x86_64.xml
**Summary**
- Contributors to the old SourceForge source are inactive, other distros have moved to this fork
- Post-fork changelog available [here](https://github.com/resurrecting-open-source-projects/dcfldd/blob/master/ChangeLog)
**Test Plan**
- Copy a small partition, generate hash
**Checklist**
> dcfldd: Change source, Update to 1.9.1

- packages/py/pybind11/monitoring.yml
- packages/py/pybind11/package.yml
- packages/py/pybind11/pspec_x86_64.xml
- packages/py/python-pikepdf/abi_used_libs
- packages/py/python-pikepdf/abi_used_symbols
- packages/py/python-pikepdf/package.yml
- packages/py/python-pikepdf/pspec_x86_64.xml
**Summary**
- pybind11 v2.13.5 [changelog](https://pybind11.readthedocs.io/en/stable/changelog.html#version-2-13-5-august-22-2024)
- python-pikepdf v9 [changelog](https://pikepdf.readthedocs.io/en/latest/releasenotes/version9.html#v9-2-1)
- python-pikepdf v8 [changelog](https://pikepdf.readthedocs.io/en/latest/releasenotes/version8.html#v8-15-1)
**Test Plan**
Run `pdfarranger` and modify some PDF Files.
**Checklist**
> python-pikepdf: Update to v9

- packages/g/gpxsee/abi_used_symbols
- packages/g/gpxsee/package.yml
- packages/g/gpxsee/pspec_x86_64.xml
**Summary**
**Test Plan**
- render map
**Checklist**
> gpxsee: Update to 13.24

- packages/p/picard/package.yml
- packages/p/picard/pspec_x86_64.xml
**Summary**
Bugfixes:
- Fix translation in tooltip for unmatched files
- Fix an issue related to directory separators in file naming patterns
Full changelog [here](https://github.com/metabrainz/picard/compare/release-2.12.1...release-2.12.3)
**Test Plan**
Open picard. Import music and let it do its thing. Make sure things check out
**Checklist**
> picard: Update to 2.12.3

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
Changelog available [here](https://github.com/cli/cli/releases/tag/v2.56.0).
**Test Plan**
Run `gh status`, `gh pr list`, and create this PR.
**Checklist**
> github-cli: Update to 2.56.0

- packages/b/bash/files/profile/50-history.sh
- packages/b/bash/package.yml
- packages/b/bash/pspec_x86_64.xml
**Summary**
- Enable hist append by default: Append to history instead of overwriting with multiple terminals.
- Enable ignoreddups: the same line executed consecutively will not be written to the history.
- Enable erasedups: when saving to the history if previous saved entries of the line exist, they be be removed.
**Test Plan**
Verify options work as expected
**Checklist**
> bash: Tweak default history options

- packages/l/linux-driver-management/abi_libs
- packages/l/linux-driver-management/abi_symbols
- packages/l/linux-driver-management/abi_used_symbols
- packages/l/linux-driver-management/files/allow-newer-libusb.patch
- packages/l/linux-driver-management/monitoring.yml
- packages/l/linux-driver-management/package.yml
- packages/l/linux-driver-management/pspec_x86_64.xml
**Summary**
- Update source to the getsol organization
- Add homepage
- Add `monitoring.yml`
Part of https://github.com/getsolus/packages/issues/3554
**Test Plan**
Installed LDM with the LightDM integration package, rebooted the PC, nothing exploded.
That said, I only have an all-AMD machine, so this definitely needs to be tested by Intel and NVIDIA users.
**Checklist**
> linux-driver-management: Housekeeping

- packages/u/usysconf-epoch/files/usr-merge.sh
- packages/u/usysconf-epoch/package.yml
- packages/u/usysconf-epoch/pspec_x86_64.xml
**Summary**
Update the chance that a system is usr-merged to 100%.
Depending on how the week goes we will either reduce it to 10% or keep it as is before sync to stable.
**Test Plan**
Run on a system:
```
$ sudo /usr/lib/usysconf/usr-merge.sh
```
~~(output will differ for machines with a machine ID ending in 00-1A, see `hostnamectl`)~~
**Checklist**
> usysconf-epoch: Increase the usr-merge chance to 100%

- packages/s/scrcpy/abi_used_symbols
- packages/s/scrcpy/package.yml
- packages/s/scrcpy/pspec_x86_64.xml
**Summary**
Highlighed changes:
- Add gamepad support
- Fix workarounds for ONYX devices
- Accept float values for --max-fps
- Various technical fixes
Full release notes available [here](https://github.com/Genymobile/scrcpy/releases/tag/v2.7)
**Test Plan**
Mirrored my phone's screen and controlled a game with my gamepad
**Checklist**
> scrcpy: Update to 2.7

- packages/l/libtcod/abi_used_symbols
- packages/l/libtcod/package.yml
- packages/l/libtcod/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libtcod: include homepage

- packages/m/micro/package.yml
- packages/m/micro/pspec_x86_64.xml
**Summary**
Add the .desktop file that ships with micro. This allows micro to open supported file types from GUI e.g. file browsers. 
Also add the metainfo.xml shipped with micro.
**Test Plan**
Open nautilus (or your preferred file browser) and navigate to a folder containing a .typ file. Right click -> Open With -> select micro. Make sure the file opens in micro. Check that micro appears in the application menu.
**Checklist**
> micro: Bump to add .desktop and .metainfo.xml

- packages/o/obs-cmd/abi_used_symbols
- packages/o/obs-cmd/files/fix-version.patch
- packages/o/obs-cmd/package.yml
- packages/o/obs-cmd/pspec_x86_64.xml
**Summary**
Enhancements:
- Add streaming status command
- [0.17.8](https://github.com/grigio/obs-cmd/releases/tag/v0.17.8)
**Test Plan**
* Built.
* Ran few manual commands.
* Ran few scripted commands (via deckmaster).
**Checklist**
> obs-cmd: Update to 0.17.8

- packages/g/glib2/package.yml
- packages/g/glib2/pspec_x86_64.xml
- packages/py/python-packaging/package.yml
- packages/py/python-packaging/pspec_x86_64.xml
**Summary**
- Move more development related bits to the glib2-devel subpackage in order to drop python-packaging from the system.base group
**Test Plan**
Used system as normal, ensured nothing gnomey blew up
**Checklist**
> Drop python-packaging from system.base by splitting glib2 better

- packages/d/delta/abi_used_symbols
- packages/d/delta/package.yml
- packages/d/delta/pspec_x86_64.xml
**Summary**
Changelog:
- [0.18.2](https://github.com/dandavison/delta/releases/tag/0.18.2)
**Test Plan**
All following scenarios should output neatly formatted and highlighted
diffs:
- Use `delta` as replacement for `diff`:
```console
$ delta /usr/share/defaults/etc/profile /usr/share/defaults/etc/xprofile
```
- Use `delta` in git repository:
```console
$ GIT_PAGER=delta git diff HEAD~1
```
- Use `delta` with side-by-side mode in git repository:
```console
$ GIT_PAGER=delta DELTA_FEATURES='+side-by-side' git diff HEAD~1
```
**Checklist**
> delta: Update to 0.18.2

- packages/g/gleam/abi_used_symbols
- packages/g/gleam/package.yml
- packages/g/gleam/pspec_x86_64.xml
**Summary**
See blog post: https://gleam.run/news/convenient-code-actions/
**Test Plan**
* Tried out some of the new features, e.g. context aware exhaustiveness error.
**Checklist**
> gleam: Update to 1.5.0

- packages/l/light/abi_used_symbols
- packages/l/light/monitoring.yml
- packages/l/light/package.yml
- packages/l/light/pspec_x86_64.xml
**Summary**
- Original GitHub repository is gone, switch to this GitLab archived mirror, used by other distros.
Resolves https://github.com/getsolus/packages/issues/3845
**Test Plan**
- List available backlight controllers
**Checklist**
> light: Change upstreams

- packages/g/gpxsee/package.yml
- packages/g/gpxsee/pspec_x86_64.xml
**Summary**
**Test Plan**
- zoom in and out
**Checklist**
> gpxsee: Update to 13.25

- packages/b/budgie-desktop-branding/package.yml
- packages/b/budgie-desktop-branding/pspec_x86_64.xml
- packages/x/xfce4-desktop-branding/package.yml
- packages/x/xfce4-desktop-branding/pspec_x86_64.xml
**Summary**
- **budgie-desktop-branding: Sync with git**
- **xfce4-desktop-branding: Sync with git**
**Test Plan**
Install packages and `cat /usr/share/applications/budgie-mimeapps.list` (and `xfce4-mimeapps.list`) and see that the compression formats are set to use Engrampa.
**Checklist**
> update budgie xfce branding

- packages/g/gpxsee/package.yml
- packages/g/gpxsee/pspec_x86_64.xml
**Summary**
**Test Plan**
- zoom in and out
**Checklist**
> gpxsee: Update to 13.26

- Taskfile.yml
**Summary**
This should make `go-task clean-local` more ergonomic to use.
Note that `go-task list-local` now also lists files in descending date, which has the effect of showing you if you have added an .eopkg which is not yet in the index.
**Test Plan**
`go-task clean-local`
Example output:
```
ermo@solbox:~/repos/getsolus/monorepo [smarter-clean-local-task* +8 ~1 -0 !]
$ gt clean-local
task: [list-local] ls -AFcghlot /var/lib/solbuild/local/
total 8,1M
-rw-rwSr-- 1   40 Sep 23 13:33 eopkg-index.xml.sha1sum
-rw-rwSr-- 1 1,4K Sep 23 13:33 eopkg-index.xml.xz
-rw-rwSr-- 1   40 Sep 23 13:33 eopkg-index.xml.xz.sha1sum
-rw-rwSr-- 1  12K Sep 23 13:33 eopkg-index.xml
-rw-r--r-- 1  96K Sep 23 13:24 libjson-glib-32bit-1.8.0-27-1-x86_64.eopkg
-rw-r--r-- 1 1,7K Sep 23 13:24 …
```
> Taskfile: Make the clean-local target list .eopkgs

- packages/p/physfs/abi_symbols
- packages/p/physfs/package.yml
- packages/p/physfs/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://github.com/icculus/physfs/releases/tag/release-3.2.0).
**Test Plan**
- Installed Neverball which is dependent on this and played a game.
**Checklist**
> physfs: Update to 3.2.0

- packages/o/onedrive-gui/files/0001-make-project-buildable.patch
- packages/o/onedrive-gui/files/0002-create-package-directory.patch
- packages/o/onedrive-gui/monitoring.yml
- packages/o/onedrive-gui/package.yml
- packages/o/onedrive-gui/pspec_x86_64.xml
**Summary**
**Important:** If you are using sync_business_shared_folders in config of OneDrive v2.4, you will need to manually remove it from the config file.
OneDrive Client for Linux v2.5.0 introduces significant changes and is not backwards compatible with v2.4.x. Please ensure that you do not use both v2.5.0 and v2.4.x clients with the same Microsoft OneDrive account simultaneously - whether on the same or different systems. If you upgrade to v2.5.0, all your clients must be updated to this version. However, you can revert to v2.4.x at any time if necessary, but do not run different versions at the same time on any system.
Changes:
- Provides compatibility with new features introduced in OneDrive client v2.5.0
- Added support for multi-threaded upload/download progress monitoring
- …
> onedrive-gui: Update to 1.1.0 and add monitoring.yml

- packages/e/eza/package.yml
- packages/e/eza/pspec_x86_64.xml
**Summary**
- Remove `non_alpha` from percent encoding to fix hyprlinks
- Convert empty space to `%20` when render hyperlinks
**Test Plan**
List files and directories inside a directory.
**Checklist**
> eza: Update to 0.19.4

- packages/f/frog-protocols/MAINTAINERS.md
- packages/f/frog-protocols/monitoring.yml
- packages/f/frog-protocols/package.yml
- packages/f/frog-protocols/pspec_x86_64.xml
**Summary**
- Initial inclusion of `frog-protocols`
Fixes https://github.com/getsolus/packages/issues/3898
**Test Plan**
n/a (Package only contains XML definitions of the protocols)
**Checklist**
> frog-protocols: Add at 0.01

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Added tenancy aware attestation commands
- Added `--active flag` to the `gh auth status` command
- `gh attestation verify` test for custom OIDC issuers
- Update `gh attestation verify` bundle parsing and validation errors
- Suppress `attestation verify` output when no TTY present
- Use api subdomains for tenant hosts
**Test Plan**
**Checklist**
> github-cli: Update to 2.57.0

- packages/py/python-maturin/abi_used_symbols
- packages/py/python-maturin/package.yml
- packages/py/python-maturin/pspec_x86_64.xml
**Summary**
Changes:
- Cross building fixes
- Normalize `REPOSITORY_URL`
- UniFFI: supports bindings generated from multiple crates
- Enable `--all-features` when building source distribution
- Replace "." with "/" in module_name
**Test Plan**
**Checklist**
> python-maturin: Update to 1.7.2

- packages/py/python-maturin/package.yml
- packages/py/python-maturin/pspec_x86_64.xml
**Summary**
Changes:
- Fix pypi/testpypi upload
- Fix musllinux rpath for non-cffi bindings
- Add GitHub Actions attestation support to generate-ci
**Test Plan**
Successfully build `python-orjson`
**Checklist**
> python-maturin: Update to 1.7.4

- packages/p/picocom/abi_used_symbols
- packages/p/picocom/package.yml
- packages/p/picocom/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://gitlab.com/wsakernel/picocom/-/releases/2024-07).
- Resolves https://github.com/getsolus/packages/issues/3875
**Test Plan**
- Installed, checked help. Read the manual.
**Checklist**
> picocom: Update to 2024.07

- packages/m/magpie/abi_symbols
- packages/m/magpie/abi_used_symbols
- packages/m/magpie/package.yml
- packages/m/magpie/pspec_x86_64.xml
**Summary**
- Add API replacing gsd-power's use of libgnome-rr.
Resolves backlight crashes due to new GSD api requirement.
- Resolve GNOME 47 Scaling issues due to GSD api new requirement
**Test Plan**
Install updated package, reboot and login successfully, change scaling to 200% and back to 100%.
**Checklist**
> magpie: Update to 0.9.4

- packages/b/bash/files/skel/.bashrc
- packages/b/bash/files/skel/.profile
- packages/b/bash/package.yml
- packages/b/bash/pspec_x86_64.xml
**Summary**
Add /etc/skel files so new users have sane defaults.
Resolves getsolus/packages#3795
**Test Plan**
Generate ISO with this package. See shell colours in ISO and in fresh install:
**Checklist**
> bash: Add /etc/skel files

- packages/n/newsboat/abi_used_symbols
- packages/n/newsboat/package.yml
- packages/n/newsboat/pspec_x86_64.xml
**Summary**
Changelog can be read [here](https://raw.githubusercontent.com/newsboat/newsboat/refs/tags/r2.37/CHANGELOG.md)
**Test Plan**
Open rss feed
**Checklist**
> newsboat: Update to 2.37

- packages/n/neochat/files/0001-allow-system-tray-on-gnome.patch
- packages/n/neochat/package.yml
- packages/n/neochat/pspec_x86_64.xml
**Summary**
- We use https://github.com/ubuntu/gnome-shell-extension-appindicator OOTB so let us use the damn tray
**Test Plan**
- System tray setting is no longer hidden, system tray works
**Checklist**
> neochat: Allow system tray support in GNOME

- packages/m/mpv/abi_used_symbols
- packages/m/mpv/package.yml
- packages/m/mpv/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://github.com/mpv-player/mpv/releases/tag/v0.39.0).
- Resolves https://github.com/getsolus/packages/issues/3972
**Test Plan**
- Installed, ran some commands.
**Checklist**
-  [X] Package was built and tested against unstable
> mpv: Update to 0.39.0

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Better messaging for `attestation verify` custom issuer mismatch error
- Enhance `gh repo create` docs, fix random cmd link
- Add HasActiveToken method to AuthConfig to refactor auth check for `attestation trusted-root` command
- Improve the suggested command for creating an issue when an extension doesn't have a binary for your platform
- Disable auth check for `attestation trusted-root` command
- Fix tenant-awareness for `trusted-root` command
- Replace "GitHub Enterprise Server" option with "other" in gh auth login prompting
**Test Plan**
**Checklist**
> github-cli: Update to 2.58.0

- packages/m/mate-notification-daemon/abi_symbols
- packages/m/mate-notification-daemon/package.yml
- packages/m/mate-notification-daemon/pspec_x86_64.xml
**Summary**
Changes:
- daemon: Properly update the set of monitors when it changes
**Test Plan**
Confirmed notifications in a MATE sessions worked and looked correctly
**Checklist**
> mate-notification-daemon: Update to 1.28.1

- packages/c/calamares/files/install/modules/shellprocess_removeliveos.conf
- packages/c/calamares/files/install/modules/users.conf
- packages/c/calamares/package.yml
- packages/c/calamares/pspec_x86_64.xml
**Summary**
Remove additional files created for/by the installer in `/etc/pam.d` and `/etc/sudoers.d`. Both directories should generally not exist in a clean install.
**Test Plan**
1. Install Solus using an ISO with this version of Calamares included.
2. Verify that `/etc/pam.d` and `/etc/sudoers.d` do not exist.
**Checklist**
> calamares: Remove leftover files in /etc

- packages/a/aa-lsm-hook/package.yml
- packages/a/aa-lsm-hook/pspec_x86_64.xml
- packages/a/apparmor/abi_used_symbols
- packages/a/apparmor/package.yml
- packages/a/apparmor/pspec_x86_64.xml
**Summary**
Move `aa-lsm-hook` out of system.base.
Resolves getsolus/packages#3934.
**Test Plan**
- Install and check component.
- Remove and verify errors are gone.
**Checklist**
> Allow apparmor removal

- packages/py/python-toolz/monitoring.yml
- packages/py/python-toolz/package.yml
- packages/py/python-toolz/pspec_x86_64.xml
**Summary**
Changes:
- Test fixes for changes in recent upstream Python
- Drop Python 3.7
- Test against Python 3.13
**Test Plan**
- Ran some examples from the project's documentation
**Checklist**
> python-toolz: Update to 1.0.0, add monitoring, enable tests

- packages/g/godot/abi_used_symbols
- packages/g/godot/package.yml
- packages/g/godot/pspec_x86_64.xml
**Summary**
- 2D physics interpolation
- 2D hierarchical culling
- Tighter shadow culling
- Mesh merging
- Discrete level of detail
- ORM materials
- Vertex cache optimization
- Light probes and directional shadows performance improvements
- View selected mesh stats
- SceneTree dock’s filter improvements
- Text-to-Speech support
- In-editor documentation for Editor Settings
- Update supported versions for Android, iOS, and macOS
Full release notes available [here](https://godotengine.org/article/godot-3-6-finally-released/)
**Test Plan**
Opened, edited and ran a small example project in both -classic and -mono
**Checklist**
> godot: Update to 3.6

- packages/d/dolphin-emu/package.yml
- packages/h/haxe/package.yml
- packages/l/librist/package.yml
- packages/n/neko/package.yml
- packages/o/obs-studio/package.yml
- packages/o/openrgb/package.yml
- packages/r/retroarch/package.yml
**Summary**
Replaces mbedtls-devel build dependencies with the new-ish pkgconfig
**Test Plan**
Built Godot using the pkgconfig in build deps (that's a separate PR though)
**Checklist**
> [NFC] repo-wide: Replace mbedtls-devel with pkgconfig(mbedtls)

- packages/y/yaru-theme/package.yml
- packages/y/yaru-theme/pspec_x86_64.xml
**Summary**
Changes:
- Update gnome-system-monitor symbolics
- Update gnome-calendar symbolics
- Update gnome-control-center symbolics
- Update gnome-software symbolics
- gnome-shell: Use button style for auth dialog list items
- icons: Update rendered icons and symlinks
- gnome-shell: Sync dock theming with upstream
- gnome-shell/dock: Use the same style for the notification badges in overview
- gnome-shell/dock: Move the progress bar at the bottom of the icon
- gnome-shell/slider: Drop yaru customization as border is not supported
- gnome-shell/slider: Use lighter color for the handler on light themes
**Test Plan**
Set system style to Yaru gtk and icon theme and confirmed everything looks alright
**Checklist**
> yaru-theme: Update to 24.10.4

- packages/b/brave/package.yml
- packages/b/brave/pspec_x86_64.xml
**Summary**
- Fixed issue where unchecking the “Show on startup” checkbox of the profile picker was not being retained.
- Fixed toggling on “Enable AdGuard” under brave://settings/extensions/v2 was installing the MV3 version of the AdGuard Blocker extension.
- Upgraded Chromium to 129.0.6668.100.
**Test Plan**
Browse some websites, youtube, getsolus, github.
**Checklist**
> brave: Update to 1.70.126

- packages/a/appstream-data/package.yml
- packages/a/appstream-data/pspec_x86_64.xml
**Summary**
Update Appstream Metainfo to v49
**Test Plan**
1. Build appstream-data from this PR.
2. Install the updated package.
3. Check that one of KDE Discover or GNOME Software works and has sane content.
4. Check that Solus SC works and has sane content.
**Checklist**
> appstream-data: Update to 49

- packages/n/numix-icon-theme-circle/package.yml
- packages/n/numix-icon-theme-circle/pspec_x86_64.xml
- packages/n/numix-icon-theme-square/package.yml
- packages/n/numix-icon-theme-square/pspec_x86_64.xml
**Summary**
- New icons:
- Update numix-icon-theme-square to 24.10.13
- Update numix-icon-theme-circle to 24.10.13
**Test Plan**
Change system icon theme and check the icons
**Checklist**
> Numix icons: Update to 24.10.13

- packages/o/obs-cmd/files/fix-version.patch
- packages/o/obs-cmd/package.yml
- packages/o/obs-cmd/pspec_x86_64.xml
**Summary**
* Expose `recording toggle-pause` command.
Full changelog: https://github.com/grigio/obs-cmd/releases/tag/v0.17.9
**Test Plan**
* Ran new `obs-cmd recording toggle-pause` while recording in OBS.
**Checklist**
> obs-cmd: Update to v0.17.9

- packages/d/doublecmd/package.yml
- packages/d/doublecmd/pspec_x86_64.xml
- packages/g/goverlay/package.yml
- packages/g/goverlay/pspec_x86_64.xml
- packages/l/lazarus/package.yml
- packages/l/lazarus/pspec_x86_64.xml
- packages/q/qt6pas/package.yml
- packages/q/qt6pas/pspec_x86_64.xml
- packages/t/transgui/package.yml
- packages/t/transgui/pspec_x86_64.xml
**Summary**
Update Lazarus to latest version. v3.6.0
**Test Plan**
Rebuild and run: `transgui` `winff` `goverlay` and `doublecmd`
**Checklist**
> lazarus: Update to 3.6.0

- packages/e/eqonomize/abi_used_symbols
- packages/e/eqonomize/package.yml
- packages/e/eqonomize/pspec_x86_64.xml
**Summary**
- Add option to group accounts by type, bank, or currency
- Allowing collapsing of Assets, Liabilities, Incomes, and Expenses in Accounts & Categories using double-click
- Option to edit assets group name (using "Edit..." menu item)
- Ask if user want to save changes before opening file from command line or file manager
- Set allowed range for ledger print time period date fields (fixes ledger print error not shown when to date is before date of first transaction)
- Disable close account menu item for debts
- Place cash, current, and credit card accounts first in account selection list when appropriate
- Fix segfault and duplicating character when tag contains ampersand
- Fix initial group in new account dialog
**Test Plan**
Load an account, add incomes and expenses. Show …
> eqonomize: Update to 1.5.8

- packages/q/qutebrowser/package.yml
- packages/q/qutebrowser/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://github.com/qutebrowser/qutebrowser/blob/main/doc/changelog.asciidoc#v330-2024-10-12) for 3.3.0.
- 3.3.1 updated the workaround for Google sign-in issues.
**Test Plan**
- Installed and surfed the web.
**Checklist**
> qutebrowser: Update to 3.3.1

- packages/s/signal-desktop/abi_used_symbols
- packages/s/signal-desktop/package.yml
- packages/s/signal-desktop/pspec_x86_64.xml
**Summary**
- This update improves startup speed by around 5%, so feel free to slow down a little bit in other areas of your life.
- We fixed a bug that prevented stickers from working correctly in the media editor, and now the picker no longer gets stuck when you're trying to stick a sticker on a picture.
**Test Plan**
- Open app and chat.
**Checklist**
> signal-desktop: Update to 7.29.0

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Allow community submitted design work
- Print the login URL even when opening a browser
- Handle errors when parsing hostname in auth flow
- Add `repo license list`/`view` and `repo gitignore list`/`view`
- Support `GH_ACCEPTANCE_SCRIPT` env var to target a single script
- Ensure Acceptance defer failures are debuggable
- Supporting filtering on `gist list`
**Test Plan**
**Checklist**
> github-cli: Update to 2.59.0

- packages/e/eza/abi_used_symbols
- packages/e/eza/package.yml
- packages/e/eza/pspec_x86_64.xml
**Summary**
- Fix git cliff docs issue
- Reuse filetype from DirEntry
This yields approximately a ~24% speedup for most common operations.
**Test Plan**
**Checklist**
> eza: Update to 0.20.3

- packages/s/starship/abi_used_symbols
- packages/s/starship/package.yml
- packages/s/starship/pspec_x86_64.xml
**Summary**
- deno: add `deno.lock` file to default `detect_files` list
- hostname: add option to replace hostnames with aliases
- mojo: add module for Mojo language
- package: support alternative gradle module version syntax
- python: Add detect env vars option
- python: detect pixi and ipynb files
- bash: fix variable leak in Bash integration
- cmd_duration: Make render_time format more consistent
- docker_context: Ignore Docker Desktop "desktop-linux" context
- fish: add missing arguments for fish transient prompt functions
- fish: improve fish transient prompt
- fish: use correct input function in transient execute
- Fixed "Click to download TOML" links
- git_status: read proper name for core.fsmonitor flag
- python: improve parsing of `pyvenv.cfg` files
- Use `whoami` for …
> starship: Update to 1.21.0

- packages/py/python-gphoto2/monitoring.yml
- packages/py/python-gphoto2/package.yml
- packages/py/python-gphoto2/pspec_x86_64.xml
**Summary**
- Add Python 3.12 & 3.13 binary wheels.
- Add `__version_tuple__` for easy runtime version checking.
**Test Plan**
- Download new photos from my phone using `rapid-photo-downloader`
- Connect my phone via USB and run commands:
```
$ cd /usr/lib/python3.11/site-packages/gphoto2/examples
$ python3 camera-summary.py
$ python3 list-cameras.py
$ python3 gphoto2_version.py
```
**Checklist**
> python-gphoto2: Update to 2.5.1

- packages/w/wine/abi_symbols
- packages/w/wine/abi_symbols32
- packages/w/wine/package.yml
- packages/w/wine/pspec_x86_64.xml
**Summary**
- Bundled Capstone library for disassembly in WineDbg
- More formats supported in D3DX9
- More support for network sessions in DirectPlay
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.20)
**Test Plan**
- Ran `winefile`, `winemine`, `winecfg`, `wineconsole`
**Checklist**
> wine: Update to 9.20

- packages/p/pentobi/abi_used_symbols
- packages/p/pentobi/package.yml
- packages/p/pentobi/pspec_x86_64.xml
**Summary**
- Don't ask for continuing computer move anymore if computer is to play in current position after program startup.
- Workaround for QTBUG-119198 (Disabled menu item indistinguishable from enabled one).
- Fixed formatting of written game files.
- Improved visibility of analysis graph lines in theme System.
- Minor fixes.
**Test Plan**
- Play a game.
**Checklist**
> pentopi: Update to 25.1

- packages/a/adw-gtk3-theme/package.yml
- packages/a/adw-gtk3-theme/pspec_x86_64.xml
**Summary**
- Fix black selection in GTK4 apps
**Test Plan**
Switch to the theme on Budgie Desktop.
**Checklist**
> adw-gtk3-theme: Update to 5.5

- packages/py/python-orjson/abi_libs
- packages/py/python-orjson/abi_symbols
- packages/py/python-orjson/abi_used_symbols
- packages/py/python-orjson/package.yml
- packages/py/python-orjson/pspec_x86_64.xml
**Summary**
Changes:
- `int` serialization no longer chains `OverflowError` to the the `__cause__` attribute of `orjson.JSONEncodeError` when range exceeded
- Compatibility with CPython 3.14 alpha 1
**Test Plan**
- Ran some examples from the project's README
- Built and used `anki`
**Checklist**
> python-orjson: Update to 3.10.9

- common/Scripts/yauto.py
**Summary**
This slightly changes the `yauto` logic so after it discovers a file with "configure" in the name, it will first check if it's a plain text file before further scanning it. This avoids issues with it trying to analyze e.g. image files.
Error example without this patch:
```
C-_4.13.1/resources/icons/png/configure.png for use of g-ir-scanner
Traceback (most recent call last):
File "/home/thomas/Projects/SolusPackaging/common/Scripts/yauto.py", line 410, in <module>
p.examine_source()
File "/home/thomas/Projects/SolusPackaging/common/Scripts/yauto.py", line 153, in examine_source
if self.check_is_gnomey(f_path):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/thomas/Projects/SolusPackaging/common/Scripts/yauto.py", line 394, in check_is_gnomey
lines = makefile.read()
^^^^^^^^^^^^^^^ …
```
> yauto: Only scan "configure" files if they're text/plain

- common/Hooks/prepare-commit-msg.py
**Summary**
- Add at for initial package inclusion
- Non functional change when the package isn't rebuilt
**Test Plan**
- Only NFC tested
**Checklist**
> common/Hooks: Add support for 'Add at' and '[NFC]' commits

- common/CI/config.yaml
- common/CI/package_checks.py
**Summary**
Add a check that fails when static libraries are included.
Packages or paths that should contain static libraries can be allow-listed in the CI configuration.
Depends on #2038.
**Test Plan**
```
./common/CI/package_checks.py **/pspec_x86_64.xml
```
**Checklist**
> ci/package_checks: Add check for included static libraries

- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
**Summary**
Enables Unicode 16 emoji support
For more details see [here](https://blog.emojipedia.org/whats-new-in-unicode-16-0/)
**Test Plan**
Entered the new emojis in my text editor of choice (`gedit`)
**Checklist**
> noto-sans-ttf: Update emoji font to 2.047

- packages/j/juliaup/abi_used_symbols
- packages/j/juliaup/package.yml
- packages/j/juliaup/pspec_x86_64.xml
**Summary**
- Updated juliaup to 1.17.9
- Release notes can be found [here](https://github.com/JuliaLang/juliaup/releases/tag/v1.17.9)
- Part of getsolus/packages#3111
**Test Plan**
installed julia
**Checklist**
> juliaup: Update to 1.17.9

- packages/r/ripgrep/abi_used_symbols
- packages/r/ripgrep/package.yml
- packages/r/ripgrep/pspec_x86_64.xml
**Summary**
Use the new `%cargo_test` macro for `ripgrep`
**Test Plan**
Successfully built package with tests enabled
**Checklist**
> ripgrep: Switch to `%cargo_test` macro

- packages/y/yt-dlp/package.yml
- packages/y/yt-dlp/pspec_x86_64.xml
**Summary**
- Updated yt-dlp to 2024.10.22
- Changelog available [here](https://github.com/yt-dlp/yt-dlp/blob/2024.10.22/Changelog.md)
**Test Plan**
Download an watch a video.
**Checklist**
> yt-dlp: Update to 2024.10.22

- packages/b/budgie-control-center/files/fix-FTBFS-with-incompatible-pointer-types.patch
- packages/b/budgie-control-center/package.yml
- packages/b/budgie-control-center/pspec_x86_64.xml
**Summary**
_Actually_ add a patch from upstream, which fixes a FTBFS issue.
Fixes https://github.com/getsolus/packages/issues/4136
**Test Plan**
Check that budgie-control-center still builds and that the newly added patch file is part of the changeset.
**Checklist**
> budgie-control-center: 2nd rebuild for samba-4.19.8

- packages/s/sof-firmware/package.yml
- packages/s/sof-firmware/pspec_x86_64.xml
**Summary**
For v2.11 series (Meteor Lake and newer), the following new topology files have been added since v2.10:
v2.11.x/sof-ipc4-tplg-v2.11  
├── sof-adl-cs42l43-l0-cs35l56-l23.tplg  
├── sof-arl-cs42l43-l0-cs35l56-l23.tplg  
├── sof-arl-cs42l43-l0-cs35l56-l2.tplg  
├── sof-arl-cs42l43-l0.tplg  
├── sof-arl-cs42l43-l2-cs35l56-l3.tplg  
├── sof-arl-cs42l43-l2.tplg  
├── sof-hda-generic-ace1-idisp-2ch.tplg  
├── sof-hda-generic-ace1-idisp-4ch.tplg  
├── sof-hda-generic-cavs25-idisp-2ch.tplg  
├── sof-hda-generic-cavs25-idisp-4ch.tplg  
├── sof-hda-generic-idisp-2ch.tplg  
├── sof-hda-generic-idisp-4ch.tplg  
├── sof-lnl-cs42l43-l0-cs35l56-l23.tplg  
├── sof-lnl-cs42l43-l0-cs35l56-l3.tplg  
├── sof-lnl-cs42l43-l0.tplg  
├── sof-mtl-cs42l43-l0.tplg  
├── sof-mtl-rt712-l0-2ch.tplg  
├── …
> sof-firmware: update to 2.11.1

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Add ArchivedAt field
- Include startedAt, completedAt in run steps data
- Adjust environment help for host and tokens
- Add handling of empty titles for Issues and PRs
- `LiveSigstoreVerifier.Verify` should error if no attestations are present
- `gh at verify` retries fetching attestations if it receives a 5xx
- Prevent local extension installations with invalid names and conflicts with core commands and other extensions
- Use new GitHub previews terminology in attestation commands' help docs
**Test Plan**
**Checklist**
> github-cli: Update to v2.60.0

- .github/ISSUE_TEMPLATE/report-packaging-problems.yml
The report-packaging-problems.yml template has a syntax error. This may fix it.
> Potential fix for options label in report-packaging-problems.yml

- packages/b/baselayout/package.yml
- packages/b/baselayout/pspec_x86_64.xml
**Summary**
Update baselayout to be fully compatible with usr merged systems. This makes it safe to install on merged systems, but dangerous to install on non-merged systems.
⚠️ Do not publish this PR after merging, it will break upgrades from non-merged systems! ⚠️
**Test Plan**
```console
$ sudo eopkg.bin it baselayout-1.9.0-82-1-x86_64.eopkg
<snip>
$ sudo /usr/lib64/usysconf/usr-merge.sh
Skipping usr-merge: already done!
$ ls -l /bin /sbin /lib64 /lib32 /lib
lrwxrwxrwx 1 root root 7 22 okt 12:58 /bin -> usr/bin/
lrwxrwxrwx 1 root root 7 22 okt 12:58 /lib -> usr/lib/
lrwxrwxrwx 1 root root 9 22 okt 12:58 /lib32 -> usr/lib32/
lrwxrwxrwx 1 root root 9 22 okt 12:58 /lib64 -> usr/lib64/
lrwxrwxrwx 1 root root 8 22 okt 12:58 /sbin -> usr/sbin/
```
**Checklist**
> baselayout: Make compatible with usr merged systems

- common/CI/package_checks.py
**Summary**
Add a check that errors when `monitoring.yml` does not exist. This makes the existence of `monitoring.yml` mandatory for all packages.
Related to https://github.com/getsolus/packages/issues/4121
**Test Plan**
Run manually against a known bad package:
```console
$ common/CI/package_checks.py packages/g/glog/package.yml 
Checking files: packages/g/glog/package.yml
Found 4 result(s), 1 warnings and 2 error(s)
INF packages/g/glog/package.yml:1: This package is included in the ISO. Consider validating the functionality in a newly built ISO.
ERR packages/g/glog/package.yml:1: `homepage` is not set
ERR packages/g/glog/package.yml:1: `monitoring.yml` is missing
WRN packages/g/glog/package.yml:1: Package release is not incremented by 1
```
Run manually against a known good package: …
> ci/package_checks: Add check for monitoring.yml

- packages/q/quickemu/monitoring.yml
- packages/q/quickemu/package.yml
- packages/q/quickemu/pspec_x86_64.xml
**Summary**
Initial addition of Quickemu, a tool for quickly spinning up disposable VMs.
Resolves getsolus/packages#3487
**Test Plan**
Download and start an Alpine VM:
```
quickget alpine v3.20
quickemu --vm alpine-v3.20.conf --viewer spicy --width 1920 --height 1080
```
Remove it after starting:
```
quickemu --vm alpine-v3.20.conf --kill --delete-vm
```
**Checklist**
> quickemu: Add at v4.9.6

- packages/h/heroic-games-launcher/package.yml
- packages/h/heroic-games-launcher/pspec_x86_64.xml
Resolves #4025 
**Summary**
Bugfixes:
- Fixed Amazon Games library synchronization failure
- Fixed issues with CYGNI: All Guns Blazing and Black Myth: Wukong from Epic Games
- Fixed GOG cloud saves issues, when files were removed using utility on GOG's website
Full changelog available [here](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/compare/v2.15.1...v2.15.2)
**Test Plan**
Launch Heroic and navigate through stores, download manager, settings, etc. Make sure things look and function normally. Launch a game and make sure it runs as expected.
**Checklist**
> heroic-games-launcher: Update to 2.15.2

- packages/t/typst/abi_used_symbols
- packages/t/typst/package.yml
- packages/t/typst/pspec_x86_64.xml
**Summary**
Enhancements:
- Added support for multi-column floating placement and figures
- Added support for automatic line numbering
- Typst's layout engine is now multithreaded. Typical speedups are 2-3x for larger documents.
- Paragraph justification was optimized with a new two-pass algorithm. Speedups are larger for shorter paragraphs and go up to 6x.
- Highly reduced PDF file sizes due to better font subsetting
- Emoji are now exported properly in PDF
- Added initial support for PDF/A
- Added various options for configuring the CLI's environment (fonts, package paths, etc.)
- Text show rules now match across multiple text elements
- Block-level equations can now optionally break over multiple pages
Bugfixes:
- Fixed a bug where some fonts would not print correctly on professional …
> typst: Update to 0.12.0

- packages/s/svtplay-dl/package.yml
- packages/s/svtplay-dl/pspec_x86_64.xml
**Summary**
- tv4play: fixed a crash using -A
- tv4play: improved DRM message a bit.
- tv4play: improved detection on what videos we can download in -A
- dr.dk: fixed so its working again
- hls: fixed some videos got the wrong alt stremas.
- aftonbladet: fixed so we can download premium videos via a token
- svtplay: fixed a crash in some specific videos
- Avoid overwrite config for merge subtitle
**Test Plan**
- Downloaded a video.
**Checklist**
> svtplay-dl: Update to v4.101

- packages/f/filemanager-actions/abi_used_symbols
- packages/f/filemanager-actions/package.yml
- packages/f/filemanager-actions/pspec_x86_64.xml
**Summary**
- Fix dependencies
- Part of https://github.com/getsolus/packages/issues/4143
**Test Plan**
**Checklist**
> filemanager-actions: fix dependencies

- packages/f/fb2converter/files/0002_nerf_colors
- packages/f/fb2converter/package.yml
- packages/f/fb2converter/pspec_x86_64.xml
**Summary**
- Latest go toolchain: go1.23.2
- Regenerating all dependencies
- Cleaning up taskfile
- Re-formatting and linting all sources using up to date tools
- [changelog](https://github.com/rupor-github/fb2converter/releases/tag/v1.76.0)
**Test Plan**
- fb2c convert --to epub in.fb2
**Checklist**
> fb2converter: Update to 1.76.0

- packages/k/kitty/abi_used_symbols
- packages/k/kitty/package.yml
- packages/k/kitty/pspec_x86_64.xml
**Summary**
- A new optional text cursor movement animation that shows a “trail” following the movement of the cursor making it easy to follow large cursor jumps
- Custom kittens: Add a framework for easily and securely using remote control from within a kitten’s main() function
- kitten icat: Fix the kitty +kitten icat --no-trailing-newline not working when using unicode placeholders
- tab_title_template allow using the 256 terminal colors for formatting
- Fix resizing window when alternate screen is active does not preserve trailing blank output line in the main screen
- Wayland: Fix background_opacity less than one causing flicker on startup when the Wayland compositor supports single pixel buffers
- Fix background image flashing when closing a tab
- When running a kitten that modifies …
> kitty: Update to 0.37.0

- packages/l/libarchive/package.yml
- packages/l/libarchive/pspec_x86_64.xml
**Summary**
- Fix dependencies
- Part of https://github.com/getsolus/packages/issues/4143
**Test Plan**
**Checklist**
> libarchive: fix dependencies

- packages/e/eza/package.yml
- packages/e/eza/pspec_x86_64.xml
**Summary**
- Fix typo `--get-repos-no-status` to `--git-repos-no-status`
**Test Plan**
**Checklist**
> eza: Update to v0.20.6

- packages/w/weston/package.yml
- packages/w/weston/pspec_x86_64.xml
**Summary**
Fix runtime dependency name.
**Test Plan**
Run a full system upgrade successfully.
**Checklist**
> weston: Fix runtime dependency name

- packages/c/chocolate-doom/package.yml
- packages/c/chocolate-doom/pspec_x86_64.xml
**Summary**
Fixes getsolus/packages#78
**Test Plan**
Install packages and look whether they are showing up correctly in the menu.
Setup programs are starting, the game itself does not start because [you need *wad* files](https://www.chocolate-doom.org/wiki/index.php/FAQ#How_do_I_set_up_Chocolate_Doom_on_my_computer.3F) for that. 
**Checklist**
> chocolate-doom: Split into separate sub-packages

- packages/py/python-orjson/abi_libs
- packages/py/python-orjson/abi_symbols
- packages/py/python-orjson/package.yml
- packages/py/python-orjson/pspec_x86_64.xml
**Summary**
Release notes:
- [3.10.11](https://github.com/ijl/orjson/releases/tag/3.10.11)
- [3.10.10](https://github.com/ijl/orjson/releases/tag/3.10.10)
**Test Plan**
**Checklist**
> python-orjson: Update to v3.10.11

- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
**Summary**
Full commit log available [here](https://github.com/notofonts/notofonts.github.io/compare/noto-monthly-release-24.9.1...noto-monthly-release-2024.11.01)
**Test Plan**
- Typed some text in Noto Sans and Noto Serif
- Confirmed my system UI looked alright with Noto Sans set as system font
**Checklist**
> noto-sans-ttf: Update to v2024.11.01

- packages/n/nvidia-vaapi-driver/abi_used_symbols
- packages/n/nvidia-vaapi-driver/package.yml
- packages/n/nvidia-vaapi-driver/pspec_x86_64.xml
**Summary**
This release is mainly just to fix the issue with newer versions of FFmpeg passing a single surface rather than the actual amount
Changes:
- Fix memory issues
- vabackend: Treat surfaceCount == 1 the same as surfaceCount == 0
- Unbreak build on FreeBSD < 14
**Test Plan**
Played a couple videos in firefox and confirmed acceleration was active
**Checklist**
> nvidia-vaapi-driver: Update to v0.0.13

- packages/z/zellij/abi_used_symbols
- packages/z/zellij/package.yml
- packages/z/zellij/pspec_x86_64.xml
**Summary**
- A "non-colliding" keybinding preset: This is a UX change to allow users to opt-in to a different keybinding setup and default_mode.
- A new Configuration screen: Allowing users to switch between the default and non-colliding keybinding presets (temporarily per session or permanently by updating the configuration file), as well as change the Ctrl and Alt leader keys. Accessible by default with Ctrl o + c.
- A first run Setup Wizard: When Zellij runs for the first time, a special version of the Configuration screen will run, titled "First Time Setup Wizard Step 1/1", inviting the user to choose the default keybindings or the new "non-colliding" keybindings.
- Support for the Kitty Keyboard Protocol
- Configuration live reloading
- A new WebAssembly/WASI runtime
- A new Plugin …
> zellij: Update to v0.41.1

- packages/m/mousepad/abi_libs
- packages/m/mousepad/abi_symbols
- packages/m/mousepad/abi_used_libs
- packages/m/mousepad/abi_used_symbols
- packages/m/mousepad/package.yml
- packages/m/mousepad/pspec_x86_64.xml
**Summary**
Changelog available [here](https://www.mail-archive.com/xfce-announce@xfce.org/msg00974.html).
Note that while this is an XFCE app, it is not a part of 4.20.
**Test Plan**
Open the `package.yml` for `mousepad`, enable the spellchecker plugin.
**Checklist**
> mousepad: Update to v0.6.3

- packages/e/eopkg/package.yml
- packages/e/eopkg/pspec_x86_64.xml
- packages/p/pisi/pspec.xml
- packages/y/ypkg/package.yml
- packages/y/ypkg/pspec_x86_64.xml
**Summary**
- `eopkg.py2` now writes versioned (v3), gdbm format FilesDB shelves, and versioned LazyDB caches; both using Pickle Protocol Version 2.
- `eopkg.py3/bin` now writes versioned (v4), gdbm format FilesDB shelves, and versioned LazyDB caches; both using Pickle Protocol Version 2.
- FilesDB and LazyDBs are autoupgraded on version mismatch.
- The output of `sudo eopkg.py2/py3/bin rdb` operations has been cleaned up significantly.
- Taskfile now uses `eopkg.bin` for indexing operations due to the improved output it provides.
- ypkg-install-deps supports an optional -e/--eopkg-cmd argument, which defaults to `eopkg.py3`
(look at https://github.com/getsolus/solbuild/pull/117 for how this will be leveraged in solbuild).
This is intended to help make the transition between using …
> pisi/eopkg: Add versioned FilesDB and LazyDB instances

- packages/s/solbuild/package.yml
- packages/s/solbuild/pspec_x86_64.xml
**Summary**
Adds the new solbuild with no-fakeroot functionality.
Important note: Landing this PR to -unstable needs to be followed up by updating the solbuild image, otherwise we will get some really annoying failures related to libglib-json moving certain files to a -devel subpackage IIUC.
Depends on https://github.com/getsolus/packages/pull/4063 and should be landed after it.
**Test Plan**
- Complete the Test Plan for https://github.com/getsolus/packages/pull/4063 first
- Check out the branch associated with the present PR
- Build solbuild with `go-task localcp` and install it
- Run `solbuild version` and check that it shows 1.7.0
- Check out the branch from https://github.com/getsolus/packages/pull/4063 again
- Demonstrate to yourself that the two PRs taken together are self-hosting: …
> solbuild: Drop fakeroot use, use eopkg.bin

- packages/r/rxvt-unicode/abi_used_symbols
- packages/r/rxvt-unicode/package.yml
- packages/r/rxvt-unicode/pspec_x86_64.xml
**Summary**
**Test Plan**
Make sure homepage is relevant and get added to pspec_*.xml
**Checklist**
> rxvt-unicode: Add homepage

- packages/f/font-firacode/files/firacode.metainfo.xml
- packages/f/font-firacode/monitoring.yml
- packages/f/font-firacode/package.yml
- packages/f/font-firacode/pspec_x86_64.xml
**Summary**
- Add appstream metainfo (Part of getsolus/packages#449)
**Test Plan**
Run `appstream-builder --packages-dir=. --include-failed -v` 
**Checklist**
> font-firacode: Housekeeping

- packages/h/hicolor-icon-theme/package.yml
- packages/h/hicolor-icon-theme/pspec_x86_64.xml
**Summary**
[Changelog](https://gitlab.freedesktop.org/xdg/default-icon-theme/-/raw/v0.18/NEWS?ref_type=tags)
**Test Plan**
- install use system as normal
**Checklist**
> hicolor-icon-theme: Update to v0.18

- packages/l/lime3ds/abi_used_libs
- packages/l/lime3ds/abi_used_symbols
- packages/l/lime3ds/package.yml
- packages/l/lime3ds/pspec_x86_64.xml
**Summary**
- Added a "Small Screen Position" feature which can be used with the Large Screen layout
- Diagonal inputs for the circlepad and c-stick can now be bound from the Controls menu
- Added new command line options for the `lime3ds` executable which mirror those that were available with the `-cli` executable
- Fixed the labels in the Texture Filter dropdown menu being mismatched
- Full release note can read [here](https://github.com/Lime3DS/Lime3DS/releases/tag/2119)
**Test Plan**
Play Fire Emblem: Shadow of Valentia
**Checklist**
> lime3ds: Update to v2119

- packages/f/font-weather-icons/files/weather_icons.metainfo.xml
- packages/f/font-weather-icons/monitoring.yml
- packages/f/font-weather-icons/package.yml
- packages/f/font-weather-icons/pspec_x86_64.xml
**Summary**
- Only ship .otf files
- Add appstream metainfo (Part of getsolus/packages#449)
**Test Plan**
Run `appstream-builder --packages-dir=. --include-failed -v `
**Checklist**
> font-weather-icons: Housekeeping

- repo_data/distribution.xml
- repo_data/distribution.xml.in
**Summary**
- Undeprecate font-firago
- Undeprecate font-weather-icons
- Deprecate :
- font-firago-otf
- font-firago-ttf
- font-weather-icons-otf
- font-weather-icons-ttf
Only land this PR after https://github.com/getsolus/packages/pull/4263 and https://github.com/getsolus/packages/pull/4264 get merged.
> Undeprecate and Deprecate fonts

- packages/x/xfce4-weather-plugin/abi_used_symbols
- packages/x/xfce4-weather-plugin/package.yml
- packages/x/xfce4-weather-plugin/pspec_x86_64.xml
**Summary**
- Use subdomain for api.met.no
- Avoid calling libsoup callbacks when dialogs are destroyed
- weather-config: Fix memory leak on GtkBuilder
- icon: Apply translate logic to get_symbol_name
- weather-config: Fix memory management of source
**Test Plan**
Add the plugin to the panel, configure my location, see the current weather. Tis a bit warm, for this time of year.
**Checklist**
> xfce4-weather-plugin: Update to v0.11.3

- packages/g/gnome-online-accounts-gtk/package.yml
- packages/g/gnome-online-accounts-gtk/pspec_x86_64.xml
**Summary**
- Fix build with newer GTK4
**Test Plan**
Add my Google account.
**Checklist**
> gnome-online-accounts-gtk: Update to v3.50.4

- packages/b/blueprint-compiler/package.yml
- packages/b/blueprint-compiler/pspec_x86_64.xml
**Summary**
Release notes available [here](https://gitlab.gnome.org/jwestman/blueprint-compiler/-/releases/v0.14.0)
**Test Plan**
Built and used Gradience
**Checklist**
> blueprint-compiler: Update to v0.14.0

- packages/g/gpxsee/abi_used_symbols
- packages/g/gpxsee/monitoring.yml
- packages/g/gpxsee/package.yml
- packages/g/gpxsee/pspec_x86_64.xml
**Summary**
- Multiple vector maps rendering improvements/fixes.
- package incl. monitoring.yml
**Test Plan**
- open map, zoom, pan etc.
**Checklist**
> gpxsee: Update to 13.27

- packages/m/mdbook/abi_used_symbols
- packages/m/mdbook/package.yml
- packages/m/mdbook/pspec_x86_64.xml
**Summary**
- Added preliminary support for Rust 2024 edition.
- Added a full example of the remove-emphasis preprocessor.
- Adjusted styling of clipboard/play icons.
- Updated to handlebars v6.
- Attr and section rules now have specific code highlighting.
- The sidebar is now loaded from a common file, significantly reducing the book size when there are many chapters.
**Test Plan**
- Built a test site locally
**Checklist**
> mdbook: Update to 0.4.41

- packages/a/apr/abi_used_symbols
- packages/a/apr/monitoring.yml
- packages/a/apr/package.yml
- packages/a/apr/pspec_x86_64.xml
**Summary**
- Unix: Implement apr_shm_perms_set() for the "POSIX shm_open()" and "classic mmap" shared memory implementations.
- Fix missing ';' for XML/HTML hex entities from apr_escape_entity().
- Fix crash in apr_pool_create() with --enable-pool-debug=all|owner.
- Improve platform detection by updating config.guess and config.sub.
- Full release notes [here](https://dlcdn.apache.org//apr/CHANGES-APR-1.7)
**Security**
- CVE-2023-49582
**Test Plan**
- Try running a few revdeps: kdevelop, svn
**Checklist**
> apr: Update to v1.7.5

- packages/w/warzone2100/abi_used_symbols
- packages/w/warzone2100/monitoring.yml
- packages/w/warzone2100/package.yml
- packages/w/warzone2100/pspec_x86_64.xml
**Summary**
- Add: In-game options button
- Fix: Transporter timer capacity label area should be clickable
- Fix: Do not remove vision from transporters when loading saves
- Fix: Various potential crashes
- Change: Improve high-quality terrain water
- Fix: Loading high-quality terrain water diffuse textures
- Add: Initial support for admins changing settings via UI
- Add: Host auto-kick on sustained desync
- Fix: Refactor socket operations error code return
- Fix: Add campaign HQs to MP stats
- Fix: Display and log connection state on joining screen timeout
- Fix: Only play "Player is exiting" audio when player slot drops, ignore spectators
- Add: Research field for Stats object
- Change: Plasmite Flamer boost
**Packaging**
- Switch to GitHub source, project homepage does not mention …
> warzone2100: Update to v4.5.4

- packages/z/zsh/files/006-52383-Avoid-incompatible-pointer-types-in-terminfo-g.patch
- packages/z/zsh/files/010-gcc14.patch
- packages/z/zsh/files/series
- packages/z/zsh/files/zprofile
- packages/z/zsh/package.yml
- packages/z/zsh/pspec_x86_64.xml
**Summary**
Remove sourcing of /etc/profile for zsh
Fix errors from sourcing bash scripts that are incompatible with zsh
Add patches to correct make error
**Test Plan**
After reboot
- Log into TTY, verify there are no errors, ran htop
- Launch Konsole, verify there are no errors. Verify I can call commands from `solus-monorepo-helpers.zsh`
- Verified `onefetch` and `mpv`, which rely on zsh functions, work as expected
- Verify `which snap` returns the binary location for snap
- Verify `/var/lib/snapd/desktop` is in $XDG_DATA_DIRS once and only once
- Installed the Spotify snap via command line. Verify it is shown in the app menu and that it launches.
- Verify flatpaks are seen in the app menu and can be launched from there.
- Verified $XDG_DATA_DIRS was correct
``` …
```
> zsh: fix - do not source bash files and fix build

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- `gh repo edit` command has been enhanced to inform users about consequences of changing visibility and ensure users are intentional before making irreversible changes
1. Interactive `gh repo edit` visibility change requires confirmation when changing from `public`, `private`, or `internal`
2. Non-interactive `gh repo edit --visibility` change requires new `--accept-visibility-change-consequences` flag to confirm
3. New content to inform users of consequences
- `gh attestation verify` should only verify provenance attestations by default
- Fix verbiage for deleting workflow runs
- Simplify Sigstore verification result handling in `gh attestation verify`
- Print empty array for `gh cache list` when `--json` is provided
- Create the automatic key when specified with `-i`
- fix: …
> github-cli: Update to v2.61.0

- packages/w/wine/abi_symbols
- packages/w/wine/abi_symbols32
- packages/w/wine/abi_used_symbols
- packages/w/wine/abi_used_symbols32
- packages/w/wine/package.yml
- packages/w/wine/pspec_x86_64.xml
**Summary**
- More support for network sessions in DirectPlay
- Header fixes for C++ compilation
- I/O completion fixes
- More formats supported in D3DX9
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.21)
**Test Plan**
- Used `winemine`, `winecfg`, `wineconsole`, `winefile`
**Checklist**
> wine: Update to v9.21

- packages/z/zsh/files/zprofile
**Summary**
Fix the sourcing of 10-xdh.sh to have the full path Without this zsh was failing to load the file
**Test Plan**
Verified the file is at the location now in the zprofile file
> [NFC] zsh: fix sourcing of 10-xdg.sh

- packages/l/libheif/package.yml
- packages/l/libheif/pspec_x86_64.xml
**Summary**
Changes:
- fix running the unit tests from the build directory when building with plugins
- switch to catch2 testing framework
- fixes a race condition that may lead to some image tiles not being included in the output image
- fix a potential crash when querying overlay image information
**Test Plan**
Encoded and decoded a bunch of image files
**Checklist**
> libheif: Update to v1.19.3

- packages/a/acpica-unix/monitoring.yml
- packages/a/acpica-unix/package.yml
- packages/a/acpica-unix/pspec_x86_64.xml
**Summary**
- Fix the acpixf.h file which caused issues for the last release (before this) 20240827
- Fix the pointer offset for the SLIC table
- Verify the local environment and GitHub commits are all in sync which was a problem with the second from last release (before this)20240322 (aka 20240323 date issue)
**Test Plan**
- Run some `acpi*` commands
**Checklist**
> acpica-unix: Update to v20240927

- packages/d/doctl/monitoring.yml
- packages/d/doctl/package.yml
- packages/d/doctl/pspec_x86_64.xml
**Summary**
- [1.117.0](https://github.com/digitalocean/doctl/releases/tag/v1.117.0)
- [1.116.0](https://github.com/digitalocean/doctl/releases/tag/v1.116.0)
- [1.115.0](https://github.com/digitalocean/doctl/releases/tag/v1.115.0)
- [1.114.0](https://github.com/digitalocean/doctl/releases/tag/v1.114.0)
**Test Plan**
- Authorize doctl with a test API token
**Checklist**
> doctl: Update to v1.17.0

- packages/t/tmux/monitoring.yml
- packages/t/tmux/package.yml
- packages/t/tmux/pspec_x86_64.xml
**Summary**
- Do not translate BSpace as Unicode with extended keys.
- Fix so that keys with Shift are represented correctly with extended keys.
- Revert to using /bin/sh for #() and run-shell and if-shell; the change to use default-shell only applies now to popups.
- Fix grey colour without a number suffix in styles.
**Test Plan**
- Use a new tmux session for a bit
**Checklist**
> tmux: Update to v3.5a

- packages/p/pcsx2/abi_used_symbols
- packages/p/pcsx2/monitoring.yml
- packages/p/pcsx2/package.yml
- packages/p/pcsx2/pspec_x86_64.xml
**Summary**
- Remove png++ as dependency.
- Part of https://github.com/getsolus/packages/issues/3885
**Test Plan**
- Checked it still build and started up as expected.
**Checklist**
> pcsx2: remove png++ as dependency

- packages/u/usysconf-epoch/files/usr-merge.sh
- packages/u/usysconf-epoch/package.yml
- packages/u/usysconf-epoch/pspec_x86_64.xml
**Summary**
Instead of skipping the usr-merge when it was performed (once), do it when it is needed. This means that anything that causes the system to not be merged (like reinstalling baselayout) is recovered from on the next boot.
Resolves #4118
**Test Plan**
```console
$ sudo /usr/lib64/usysconf/usr-merge.sh
Skipping usr-merge: already done!
$ sudo eopkg.bin it --reinstall baselayout
<snip>
$ ls -l /bin /sbin /lib64 /lib32 /lib
lrwxrwxrwx 1 root root 7 Oct 22 12:10 /bin -> usr/bin
lrwxrwxrwx 1 root root 5 Oct 22 12:24 /lib -> lib64
lrwxrwxrwx 1 root root 9 Oct 22 12:10 /lib32 -> usr/lib32
lrwxrwxrwx 1 root root 8 Oct 22 12:10 /sbin -> usr/sbin
/lib64:
total 0
$ sudo /usr/lib64/usysconf/usr-merge.sh
Starting merge:
[/bin]: is a symlink to usr/bin
[/bin]: is the correct symlink
[/sbin]: …
```
> usysconf-epoch: Only skip if properly merged

- packages/y/yadm/monitoring.yml
- packages/y/yajl/monitoring.yml
- packages/y/yakuake/monitoring.yml
- packages/y/yaml-cpp/monitoring.yml
- packages/y/yaml/monitoring.yml
- packages/y/yapf/monitoring.yml
- packages/y/yasm/monitoring.yml
- packages/y/yodl/monitoring.yml
- packages/y/yosys/monitoring.yml
- packages/y/youtube-viewer/monitoring.yml
- packages/y/ypkg/monitoring.yml
- packages/y/yubico-pam/monitoring.yml
- packages/y/yubico-piv-tool/monitoring.yml
- packages/y/yubikey-manager/monitoring.yml
- packages/y/yubikey-personalization-gui/monitoring.yml
- packages/y/yubikey-personalization/monitoring.yml
**Summary**
Add monitoring.yml (Part of getsolus/packages#4121)
**Checklist**
- [n/a ] Package was built and tested against unstable
> [NFC] repo-wide: Add monitoring.yml

- packages/y/yubico-authenticator/files/com.yubico.yubioath.appdata.xml
- packages/y/yubico-authenticator/package.yml
- packages/y/yubico-authenticator/pspec_x86_64.xml
**Summary**
**Test Plan**
Run `appstream-builder --packages-dir=. --include-failed -v`
**Checklist**
> yubico-authenticator: Add appstream metainfo

- packages/py/python-waitress/package.yml
- packages/py/python-waitress/pspec_x86_64.xml
**Summary**
Changes:
When using Waitress to process trusted proxy headers, Waitress will now update the headers to drop any untrusted values, thereby making sure that WSGI apps only get trusted and validated values that Waitress itself used to update the environ
Full release notes available [here](https://github.com/Pylons/waitress/releases/tag/v3.0.2)
**Test Plan**
- Shared a file with `onionshare-cli`
- Used `anki` online functionalities (though I'm unsure what part exactly uses the waitress)
**Checklist**
> python-waitress: Update to v3.0.2

- packages/o/onefetch/MAINTAINERS.md
- packages/o/onefetch/abi_used_symbols
- packages/o/onefetch/package.yml
- packages/o/onefetch/pspec_x86_64.xml
**Summary**
- Add support for nerd font glyphs in languages info
- Add nerdfont iconts to the preview
- Show future commit dates without panicking
- Full changelog [here](https://github.com/o2sh/onefetch/releases/tag/2.22.0)
**Test Plan**
- Run `onefetch` on the packages repository, learn we are a python project
**Checklist**
> onefetch: Update to v2.22.0

- packages/t/tealdeer/monitoring.yml
- packages/t/tealdeer/package.yml
- packages/t/tealdeer/pspec_x86_64.xml
**Summary**
- This patch release updates the yansi dependency to version 1, so that the previous versions of yansi can be removed from the package sets of Linux distributions. This change should not impact the behavior of tealdeer.
**Test Plan**
- Use tldr to look up a random command
**Checklist**
> tealdeer: Update to v1.7.1

- packages/w/watchexec/abi_used_symbols
- packages/w/watchexec/package.yml
- packages/w/watchexec/pspec_x86_64.xml
**Summary**
Changelog: https://github.com/watchexec/watchexec/releases/tag/v2.2.0
**Test Plan**
* Ran within a few projects to run tests.
**Checklist**
> watchexec: Update to v2.2.0

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Update monotonic verification logic and testing
- Check extension for latest version when executed
- Shorten extension release checking from 3s to 1s
- Mention GitHub CLI team on discussion issues
**Security**
- CVE-2024-52308
**Test Plan**
**Checklist**
> github-cli: Update to v2.62.0

- packages/l/libheif/package.yml
- packages/l/libheif/pspec_x86_64.xml
**Summary**
Changes:
- fix crash when encoding tiled `unci` images
- fix crash in `heif_context_encode_grid()`
- fix querying the preferred colorspace for monochrome AVIF files
- error when using a chroma format or bit depth that is not supported by the Kvazaar plugin
- output proper error message when memory allocation failed and use user-defined security limits
- heif-dec: do not show progress when option `--quiet` it given
- fix `heif_image_handle_is_premultiplied_alpha()`
**Test Plan**
Encode and decode a bunch of image files
**Checklist**
> libheif: Update to v1.19.5

- packages/o/obs-cmd/files/fix-version.patch
- packages/o/obs-cmd/package.yml
- packages/o/obs-cmd/pspec_x86_64.xml
**Summary**
Changelog: https://github.com/grigio/obs-cmd/releases/tag/v0.18.0
* Checked version reported correctly.
**Checklist**
> obs-cmd: Update to v0.18.0

- packages/s/shotcut/abi_used_symbols
- packages/s/shotcut/package.yml
- packages/s/shotcut/pspec_x86_64.xml
**Summary**
- Fixed Convert stopped converting variable frame rate to constant (broke in v24.10).
- Fixed filter in and out points when you resize transition by moving a clip (broke in v24.10).
- Fixed Reframe loses its keyframes in Export (broke in v24.10).
- Fixed moving a clip immediately after a transition beyond another clip stopped working (broke in v24.10).
- Fixed Settings > Time Format > Timecode (Non-Drop Frame) for other non-integer frame rates such as 23.98 fps.
- Fixed using Export > From > Marker with subtitles creates a bad output (broke in v24.08).
- Fixed a video transition between sources with alpha channel is more translucent than expected.
- Fixed a crash adding MLT XML As a Clip to a Timeline with a higher frame rate.
- Fixed View > Resources > Convert negatively …
> shotcut: Update to v24.11.17

- packages/f/font-ubuntu-sans-ttf/files/ubuntu-sans.metainfo.xml
- packages/f/font-ubuntu-sans-ttf/monitoring.yml
- packages/f/font-ubuntu-sans-ttf/package.yml
- packages/f/font-ubuntu-sans-ttf/pspec_x86_64.xml
**Summary**
- Add ubuntu-sans font
- resolves https://github.com/getsolus/packages/issues/4360
**Test Plan**
Install font, and view in kde font manager.
**Checklist**
> font-ubuntu-sans-ttf: Add at 1.006

- Taskfile.yml
**Summary**
Use `~` instead of `null` for the default null values in the monitoring.yml template
Also add a head comment about removing all comments before submitting
Part of https://github.com/getsolus/packages/issues/4425
Old template:
```yaml
releases:
id: null # Check https://release-monitoring.org/
rss: null # For example https://github.com/PyO3/maturin/releases.atom
security:
cpe: ~
```
New template:
```yaml
releases:
id: ~ # Check https://release-monitoring.org/
rss: ~ # For example https://github.com/PyO3/maturin/releases.atom
security:
cpe: ~
```
> Taskfile: Use `~` for null in monitoring template

- packages/w/wine/abi_symbols
- packages/w/wine/abi_symbols32
- packages/w/wine/abi_used_symbols
- packages/w/wine/abi_used_symbols32
- packages/w/wine/package.yml
- packages/w/wine/pspec_x86_64.xml
**Summary**
- Support for display mode virtualization
- Locale data updated to Unicode CLDR 46
- More support for network sessions in DirectPlay
- Wayland driver enabled in default configuration
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.22)
**Test Plan**
**Checklist**
> wine: Update to v9.22

- packages/g/gpxsee/abi_used_symbols
- packages/g/gpxsee/package.yml
- packages/g/gpxsee/pspec_x86_64.xml
**Summary**
- Improved Mapsforge maps rendering performance.
- Improved Mapsforge map render theme.
- Improved Mapsforge maps render engine.
- [changelog](https://build.opensuse.org/package/view_file/home:tumic:GPXSee/gpxsee/gpxsee.changes)
**Test Plan**
- open map, zoom, pan, etc
**Checklist**
> gpxsee: Update to 13.31

- packages/l/libgtksourceview5/abi_used_symbols
- packages/l/libgtksourceview5/package.yml
- packages/l/libgtksourceview5/pspec_x86_64.xml
**Summary**
* Ignore various libxml2 deprecations
* Fix some incorrect GI annotations
* Fix extraneous dismissal of hover providers in some cases
* Add missing 5_14 version macros
**Test Plan**
- Checked it build correctly.
**Checklist**
> libgtksourceview5: Update to v5.14.2

- packages/c/cemu/abi_used_symbols
- packages/c/cemu/monitoring.yml
- packages/c/cemu/package.yml
- packages/c/cemu/pspec_x86_64.xml
**Summary**
Update to 2.4, the latest release. Improvements include reduced input latency, proper proxy server handling, and lots of bugfixes.
Enhancements:
- Vulkan: Reduced input latency
- SpotPass now respects proxy_server option in settings.xml
- More accurate error dialog emulation
Bugfixes:
- Fix corruption bug when reading .app, .wud, and .wux files
- Fix unskippable error dialogs in some games
- Fix a race condition which could cause polygon corruption
- Amiibo now work in MK8
- Various crash fixes
**Test Plan**
Launch a title and make sure things generally look ok. Test out some graphics packs. Save and load a few times.
**Checklist**
> cemu: Update to 2.4

- packages/s/scrcpy/abi_used_symbols
- packages/s/scrcpy/package.yml
- packages/s/scrcpy/pspec_x86_64.xml
**Summary**
- Virtual display
- On-device OpenGL filters
- Screen off timeout
Full release notes available [here](https://github.com/Genymobile/scrcpy/releases/tag/v3.0)
**Test Plan**
- Mirrored my phone's display and controlled it using mouse and keyboard
- Tried the new virtual display functionality
**Checklist**
> scrcpy: Update to v3.0

- packages/m/mdbook/package.yml
- packages/m/mdbook/pspec_x86_64.xml
**Summary**
- Fixed setting the title in mdbook init when no git user is configured
- The Rust 2024 edition no longer needs -Zunstable-options
**Test Plan**
- `init` and `serve` a local test site
**Checklist**
> mdbook: Update to v0.4.43

- packages/py/python-maturin/package.yml
- packages/py/python-maturin/pspec_x86_64.xml
**Summary**
Changes:
- Auto detect Python 3.13
- Feat: add skip attestation option to maturin ci github
- generate-ci: use macos-13 runner for x86_64 build job
- Improve wheel reproducibility by sorting libs
- Fix inverted workspace inclusions
- Don't resolve python interpreter when building sdist only
- Include timestamps in the suggested log format
- Add support for GNU/Hurd
- Fix `__init__` exports when using multiple UniFFI bindings
- Add free-threaded Python support
**Test Plan**
**Checklist**
> python-maturin: Update to v1.7.5

- packages/z/zsh-autosuggestions/package.yml
- packages/z/zsh-autosuggestions/pspec_x86_64.xml
**Summary**
Changes:
- Clear POSTDISPLAY instead of unsetting
- Always reset async file descriptor after consuming it
- Always use builtin `exec`
- Add `history-beginning-search-*-end` widgets to clear widget list
**Test Plan**
Used `zsh` with autosuggestions while packaging some stuff
**Checklist**
> zsh-autosuggestions: Update to v0.7.1

- packages/k/keepass/package.yml
- packages/k/keepass/pspec_x86_64.xml
**Summary**
Release notes available [here](https://keepass.info/news/n240601_2.57.html#v1)
**Test Plan**
Opened my password database, added an entry, let it perform Auto-Type
**Checklist**
> keepass: Update to v2.57.1

- packages/r/rinutils/monitoring.yml
- packages/r/rinutils/package.yml
- packages/r/rinutils/pspec_x86_64.xml
**Summary**
Changes:
- Fix absolute pkg-config libdir
- Exclude .ninja files from trailing space check
- Refactoring and minor build-fixes
**Test Plan**
Built `freecell-solver`, `black-hole-solver`, `fortune-mod`
**Checklist**
> rinutils: Update to v0.10.3 and add monitoring.yml

- packages/b/bdwgc/abi_used_symbols
- packages/b/bdwgc/abi_used_symbols32
- packages/b/bdwgc/monitoring.yml
- packages/b/bdwgc/package.yml
- packages/b/bdwgc/pspec_x86_64.xml
**Summary**
Release notes:
- [8.2.8](https://github.com/ivmai/bdwgc/releases/tag/v8.2.8)
- [8.2.6](https://github.com/ivmai/bdwgc/releases/tag/v8.2.6)
**Test Plan**
- Built and used `crystal`
- Used `inkscape`
**Checklist**
> bdwgc: Update to v8.2.8 and add monitoring.yml

- packages/f/font-firacode-nerd/monitoring.yml
- packages/f/font-firacode-nerd/package.yml
- packages/f/font-firacode-nerd/pspec_x86_64.xml
**Summary**
Release notes:
- [3.3.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.3.0)
- [3.2.1](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.2.1)
- [3.2.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.2.0)
- [3.1.1](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.1.1)
- [3.1.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.1.0)
**Test Plan**
Used "Fira Code Nerd Font" as my terminal font
**Checklist**
> font-firacode-nerd: Update to v3.3.0 and add monitoring.yml

- packages/py/python-maturin/package.yml
- packages/py/python-maturin/pspec_x86_64.xml
**Summary**
Changes:
- Allow `-i 3.13t`
- Propagate abiflags to wheel name on Windows
- Add free-threaded wheel build to generate-ci by default
- Bump metadata version to 2.4 to fix license bug
**Test Plan**
Built `python-orjson`
**Checklist**
> python-maturin: Update to v1.7.6

- packages/z/zotero/package.yml
- packages/z/zotero/pspec_x86_64.xml
**Summary**
- Import Calibre and KOReader EPUB annotations
- Import notes from Mendeley “Notebook” feature
- Wrap all long fields in the Info pane
- Increased width of search bar
- Added option to prevent note, text, and image annotation tools from automatically turning off after reader use
- Added basic image zoom feature for EPUBs to the reader
- Select next duplicate set when using up/down-arrow in Duplicate Items view
- Added File, Edit, and Window menus to note editor window
- Improved detection of creators in some Atom feeds
- Updated ISBN detection to handle new ISBN ranges
- Make side navigation bar (including Locate menu) keyboard accessible
- Bugfixes
- [changelog](https://www.zotero.org/support/changelog#changes_in_7010_november_26_2024)
**Test Plan** …
> zotero: Update to 7.0.10

- packages/g/gpxsee/package.yml
- packages/g/gpxsee/pspec_x86_64.xml
**Summary**
- Improved Mapsforge maps rendering performance.
- Improved Mapsforge map render theme.
**Test Plan**
- open map, zoom and pan
**Checklist**
> gpxsee: Update to 13.32

- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
**Summary**
Fix color emojis by also including COLRv1 font variant.
Resolves https://github.com/getsolus/packages/issues/4181
Full commit log available [here](https://github.com/notofonts/notofonts.github.io/compare/noto-monthly-release-2024.11.01...noto-monthly-release-2024.12.01)
**Test Plan**
- Confirmed system looks okay with Noto system font
- Posted coloured emojis in Steam chat window
**Checklist**
> noto-sans-ttf: Update to v2024.12.01 and fix color emojis

- common/CI/config.yaml
**Summary**
Adds qt6-base and qt6-declarative to the list of packages allowed to contain static libs.
**Test Plan**
N/A
**Checklist**
> CI/config: Add qt6-base and qt6-declarative to allowlist

- packages/g/gleam/package.yml
- packages/g/gleam/pspec_x86_64.xml
**Summary**
* Bug fix to exhaustiveness checking
Changelog: https://github.com/gleam-lang/gleam/releases/tag/v1.6.2
**Test Plan**
**Checklist**
> gleam: Update to v1.6.2

- packages/py/python-maturin/package.yml
- packages/py/python-maturin/pspec_x86_64.xml
**Summary**
Changes:
- Fix: remove extra indent in generated CI
- Upgrade cargo-xwin to unify rustls versions
- Normalize python source directory path
- Use different binding dirs for different uniffi modules
- Update minimal Python minor version for pyo3 0.23
- Limit minimal PyPy version based on bindings crate version
- Remove hard coded `pip show` in `fix_direct_url`
**Test Plan**
Rebuilt `python-orjson`
**Checklist**
> python-maturin: Update to v1.7.7

- packages/l/light/monitoring.yml
- packages/l/lzip/monitoring.yml
- packages/w/wireless-regdb/monitoring.yml
Updated yml files, replacing "rss: null" with "rss: ~"
Resolves https://github.com/getsolus/packages/issues/4425
> repo-wide: Fix monitoring.yml files

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Support bare repo creation
- Refactor the `getAttestations` functions
- Added a section on manual verification of the releases
- Adding option to return `baseRefOid` in `pr view`
- Update verification results printing
- Fix some multiline command documentation to use `heredoc` strings
- Print friendly error when `release create` fails due to missing `workflow` OAuth scope
**Test Plan**
**Checklist**
> github-cli: Update to v2.63.0

- packages/w/weechat/package.yml
- packages/w/weechat/pspec_x86_64.xml
**Summary**
- script: fix crash on /script buffer when a filter is set
- core: fix too many sorts of hotlist when buffers are moved
- relay, xfer: fix letters with actions displayed on top of buffer
- perl: fix crash when unloading Perl scripts with Perl 5.38
**Test Plan**
**Checklist**
> weechat: Update to v4.4.4

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Fix formatting in git/client_test.go comments for linter
- Bump github.com/gabriel-vasile/mimetype from 1.4.6 to 1.4.7
- Clarify which commands correspond to which DNF version under Linux install instructions
- When renaming an existing remote as part of remote creation in gh repo fork, log the change
- Fix PR checkout panic when base repo is not in remotes
**Security**
- [CVE-2024-54132](https://github.com/cli/cli/security/advisories/GHSA-2m9h-r57g-45pj)
**Test Plan**
- Build `github-cli` from this PR and install it
- Execute a few `gh` commands and make sure it doesn't blow up
**Checklist**
> github-cli: Update to v2.63.1

- packages/py/python-hatchling/package.yml
- packages/py/python-hatchling/pspec_x86_64.xml
- packages/py/python-packaging/package.yml
- packages/py/python-packaging/pspec_x86_64.xml
- packages/py/python-trove-classifiers/package.yml
- packages/py/python-trove-classifiers/pspec_x86_64.xml
- packages/py/python3-pylast/monitoring.yml
- packages/py/python3-pylast/package.yml
- packages/py/python3-pylast/pspec_x86_64.xml
- packages/y/yt-dlp/package.yml
- packages/y/yt-dlp/pspec_x86_64.xml
**Summary**
Update the `python3-pylast` build stack, down from `python-packaging`, to fix an issue with `python-trove-classifiers` that also affected `yt-dlp`. This also introduces Python 3.13 support.
Update `python3-pylast` to 5.3.0.
Remove the workaround from `yt-dlp`.
**Test Plan**
- Successfully built all the packages in the stack without workaround
- Played some last.fm songs in `lollypop`
**Checklist**
> Update python3-pylast stack, and fix python-trove-classifiers issue

- packages/s/scrcpy/package.yml
- packages/s/scrcpy/pspec_x86_64.xml
**Summary**
Changes:
- Set main display power for virtual display
- Rollback to old --turn-screen-off method for Android 15
- Do not reset TCP/IP connections
- Fix NullPointerException on certain devices
- Fix camera capture failure without retry
- Accept control events without display
- [3.0.1](https://github.com/Genymobile/scrcpy/releases/tag/v3.0.1)
- [3.0.2](https://github.com/Genymobile/scrcpy/releases/tag/v3.0.2)
**Test Plan**
Mirrored my phone display and controlled it using mouse and keyboard
**Checklist**
> scrcpy: Update to v3.0.2

- packages/k/kvirc/abi_used_symbols
- packages/k/kvirc/files/0001-Force-app_id-to-be-set-in-more-places.patch
- packages/k/kvirc/package.yml
- packages/k/kvirc/pspec_x86_64.xml
**Summary**
- A few bugs were fixed, including potential app crashes.
- Updated sound effects to use newer Qt library, cleaned up older audio backends (ESD, aRts), made Qt be preferred over Phonon, which is also becoming outdated.
- Full release notes can read [here](https://github.com/kvirc/KVIrc/releases/tag/5.2.6)
**Test Plan**
Launch the app and join a room
**Checklist**
> kvirc: Update to v5.2.6

- packages/g/glibc/package.yml
- packages/g/glibc/pspec_x86_64.xml
**Summary**
- Updated to latest 2.40 stable
- Cleaned up recipe a bit
- Bumped kernel baseline to v5.15
For post-sync
> glibc: Update to latest and bump kernel baseline

- packages/w/wine/abi_libs
- packages/w/wine/abi_libs32
- packages/w/wine/abi_symbols
- packages/w/wine/abi_symbols32
- packages/w/wine/abi_used_symbols
- packages/w/wine/abi_used_symbols32
- packages/w/wine/package.yml
- packages/w/wine/pspec_x86_64.xml
**Summary**
- Bundled vkd3d upgraded to version 1.14
- Mono engine updated to version 9.4.0
- Initial version of a Bluetooth driver
- UTF-8 support in the C runtime functions
- Support for split debug info using build ids
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-10.0-rc1)
Packaging note: Add netapi build dep to enable Samba NetAPI support
**Test Plan**
- Played Age of Empires I demo
**Checklist**
> wine: Update to v10.0-rc1

- packages/a/adw-gtk3-theme/monitoring.yml
- packages/a/adw-gtk3-theme/package.yml
- packages/a/adw-gtk3-theme/pspec_x86_64.xml
**Summary**
- Remove legacy stuff
- Add link to accent-color-change shell script
- Add `monitoring.yml` (Part of https://github.com/getsolus/packages/issues/4121)
**Test Plan**
Switch to the `adw-gtk3` theme in XFCE.
**Checklist**
> adw-gtk3-theme: Update to v5.6

- packages/h/hyprland/package.yml
- packages/h/hyprland/pspec_x86_64.xml
**Summary**
Bugfixes:
- internal: fix changeWindowZOrder reordering incorrectly
- xdg-shell: don't report invalid min/max sizes on unset
- [0.45.2](https://github.com/hyprwm/Hyprland/releases/tag/v0.45.2)
by gNick
**Summary**
package file updated
**Test Plan**
tested on a VM and on my laptop
**Checklist**
> hyprland: Update to 0.45.2

- packages/l/libsoup3/abi_symbols
- packages/l/libsoup3/abi_symbols32
- packages/l/libsoup3/abi_used_symbols
- packages/l/libsoup3/abi_used_symbols32
- packages/l/libsoup3/package.yml
- packages/l/libsoup3/pspec_x86_64.xml
**Summary**
* Fix `soup_uri_copy()` reading port as a long instead of an int
* Fix possible NULL deref in `soup_uri_decode_data_uri()`
* Fix possible overflow in `SoupContentSniffer`
* Fix assertion in `soup_uri_decode_data_uri()` on URLs with a path starting with `//`
* headers: Be more robust against invalid input when parsing params
* websocket: Fix possibility of being stuck in a read loop
**Test Plan**
- Installed, loaded homebank that is dependent on this.
**Checklist**
> libsoup3: Update to v3.6.1

- packages/s/scrcpy/package.yml
- packages/s/scrcpy/pspec_x86_64.xml
**Summary**
- Keep virtual display content on close
- Improved gamepad support
- Fix unclickable elements
- Fix "turn screen off" on some devices
- AV1 decoder
Full release notes available [here](https://github.com/Genymobile/scrcpy/releases/tag/v3.1)
**Test Plan**
Mirrored my phone's display and controlled it with mouse and keyboard
**Checklist**
> scrcpy: Update to v3.1

- common/CI/config.yaml
**Summary**
Add ispc, ldc and llvm-bolt to the list of packages allowed to contain static libs.
**Test Plan**
N/A
**Checklist**
> CI/config: Add ispc, ldc and llvm-bolt to allowlist

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Use consistent slice ordering in run download tests
- Fix bug when fetching bundles from OCI registry
- Use safepaths for run download
- Error for mutually exclusive json and watch flags
**Test Plan**
**Checklist**
> github-cli: Update to v2.63.2

- packages/a/audacity/abi_symbols
- packages/a/audacity/package.yml
- packages/a/audacity/pspec_x86_64.xml
**Summary**
- Effects can be applied to time-stretched clips.
- Moving or renaming the installation directory no longer re-enables disabled modules.
- Opening the "Adjust Playback Speed" dialog doesn't crash Audacity anymore.
**Test Plan**
- Installed and checked settings.
**Checklist**
> audacity: Update to 3.7.1

- packages/a/appstream-data/monitoring.yml
- packages/f/ffmpeg-chromium-opera/monitoring.yml
- packages/f/ffmpeg-chromium-vivaldi-stable/monitoring.yml
- packages/f/ffmpeg-chromium/monitoring.yml
**Summary**
Add monitoring.yml to
- appstream-data
- ffmpeg-chromium
- ffmpeg-chromium-opera
- ffmpeg-chromium-vivaldi-stable
Note these fields are intentionally blank see issue:
Resolves https://github.com/getsolus/packages/issues/4533
**Test Plan**
N/A
**Checklist**
N/A
> [NFC] repo-wide: Add monitoring.yml to packages

- packages/t/tailscale/package.yml
- packages/t/tailscale/pspec_x86_64.xml
**Summary**
- [changelog](https://tailscale.com/changelog#2024-12-13-client)
**Test Plan**
**Checklist**
> tailscale: Update to 1.78.3

- packages/t/tlp/monitoring.yml
- packages/t/tlp/package.yml
- packages/t/tlp/pspec_x86_64.xml
**Summary**
- Add charge threshold support for Apple Silicon Macbooks (M*), MSI laptops
- Improve support for LG Gram laptops, ThinkPads with coreboot
- Laptop screen power saving with adaptive backlight modulation (ABM) for AMD Vega or newer GPUs
- Highlight (colorize) error, warning, notice and success messages
- Add option --version to all TLP commands
- Add Fish shell command completion
- Avoid error popups from NetworkManager when switching wifi/wwan
Resolves https://github.com/getsolus/packages/issues/4539
**Test Plan**
- enable tlp, look at `tlp-stat`
**Checklist**
> tlp: Update to v1.7.0

- packages/v/vkd3d/abi_symbols
- packages/v/vkd3d/abi_symbols32
- packages/v/vkd3d/abi_used_libs
- packages/v/vkd3d/abi_used_symbols
- packages/v/vkd3d/abi_used_symbols32
- packages/v/vkd3d/monitoring.yml
- packages/v/vkd3d/package.yml
- packages/v/vkd3d/pspec_x86_64.xml
**Summary**
- [1.14](https://gitlab.winehq.org/wine/vkd3d/-/releases/vkd3d-1.14)
- [1.13](https://gitlab.winehq.org/wine/vkd3d/-/releases/vkd3d-1.13)
- [1.12](https://gitlab.winehq.org/wine/vkd3d/-/releases/vkd3d-1.12)
Part of https://github.com/getsolus/packages/issues/4143
**Test Plan**
- Rebuilt wine without issue
**Checklist**
> vkd3d: Update to v1.14

- packages/s/sysstat/abi_used_symbols
- packages/s/sysstat/monitoring.yml
- packages/s/sysstat/package.yml
- packages/s/sysstat/pspec_x86_64.xml
**Summary**
- Too many changes from 12.6.1 to 12.7.6 to list here
- Refer to full changelog [here](https://github.com/sysstat/sysstat/blob/master/CHANGES)
**Security**
- CVE-2023-33204
**Test Plan**
- Try a few commands `sar` `iostat`
**Checklist**
> sysstat: Update to v12.7.6

- packages/w/wine/package.yml
- packages/w/wine/pspec_x86_64.xml
**Summary**
Bugfix update
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-10.0-rc2)
**Test Plan**
**Checklist**
> wine: Update to v10.0-rc2

- packages/b/binutils/abi_used_libs
- packages/b/binutils/abi_used_symbols
- packages/b/binutils/files/0001-Proper-stateless.patch
- packages/b/binutils/files/0001-Use-BLAKE3-for-build-id-hashing.patch
- packages/b/binutils/files/series
- packages/b/binutils/package.yml
- packages/b/binutils/pspec_x86_64.xml
- packages/b/blake3/package.yml
- packages/b/blake3/pspec_x86_64.xml
- packages/b/bpftrace/package.yml
- packages/g/gammaray/package.yml
- packages/l/linux-tools/package.yml
Changes:
- Link against jansson to enable ELF_PACKAGE_METADATA
- Default to compressing debug symbols and set default compression algorithm to zstd
- Use BLAKE3 for hashing when using the --build-id=md5 or --build-id=sha1 flags
- Switch to RUNPATH over RPATH
- Add `--with-zstd` flag so the build fails if somehow it can't use zstd (really important now)
- Fix gprofng stateless
- Move gprofng shared libs back into main binutils package
- Split out the devel files to -devel
> binutils: Update to latest and update configs

- packages/q/qutebrowser/package.yml
- packages/q/qutebrowser/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://github.com/qutebrowser/qutebrowser/blob/main/doc/changelog.asciidoc#v340-2024-12-14).
**Test Plan**
- Read the change notes in the browser.
**Checklist**
> qutebrowser: Update to v3.4.0

- packages/a/amdgpu_top/MAINTAINERS.md
- packages/a/amdgpu_top/package.yml
- packages/a/amdgpu_top/pspec_x86_64.xml
**Summary**
- Update `libdrm_amdgpu_sys`
- Fix `CHIP_CLASS` check for GFX12
- Include `CHIP_GFX1103_R1X` (Hawk Point1) in `has_npu` condition
- Add description of `--xdna` option
- Full changelog can be found [here](https://github.com/Umio-Yasuno/amdgpu_top/releases/tag/v0.10.1)
**Test Plan**
Run the TUI and GUI app
**Checklist**
> amdgpu_top: Update to v0.10.1

- packages/b/budgie-backgrounds/package.yml
- packages/b/budgie-backgrounds/pspec_x86_64.xml
**Summary**
We have removed about half of the backgrounds in the set to keep things lightweight. The following have been removed:
- accelerated-green
- apollo-11-earth
- dragonfly-on-lavender
- geo-forest
- kitten-on-lawn
- motherboard-circuits
- orange-hallway
- solaris-grapes
- ufo-galaxy
- valley-coral
- waves-slate Additionally, ocean-waves has been cropped to the standard 3840x2160.
Additionally, ocean-waves has been cropped to the standard 3840x2160.
**Test Plan**
Install package and verify removed background is gone
**Checklist**
> budgie-backgrounds: Update to v3.0

- packages/d/diffoscope/package.yml
- packages/d/diffoscope/pspec_x86_64.xml
**Summary**
Full changelog can be found [here](https://salsa.debian.org/reproducible-builds/diffoscope/-/raw/284/debian/changelog?ref_type=tags)
**Test Plan**
Compare two version  `qtractor-*.eopkg` files
**Checklist**
> diffoscope: Update to v284

- packages/c/calibre/abi_used_symbols
- packages/c/calibre/package.yml
- packages/c/calibre/pspec_x86_64.xml
**Summary**
- We can only include one appstream metainfo per package,  remove the other files
- There is not much justification deleting additional desktop files, restore them
Resolves getsolus/packages#1364
**Test Plan**
- Verify the appstream generation with `appstream-builder --packages-dir=. --include-failed -v`
- Test the package in Plasma VM
**Checklist**
> calibre: Remove unused appstream files & restore desktop files

- packages/q/qtractor/MAINTAINERS.md
- packages/q/qtractor/abi_used_symbols
- packages/q/qtractor/package.yml
- packages/q/qtractor/pspec_x86_64.xml
**Summary**
- Clip/Cross Fade may now apply to all (multiple) selected clips.
- Fixed the status-bar session and MIDI clip length BBT format, when in presence of multiple tempo or time-signature changes.
- Introducing MIDI clip editor (aka. piano-roll) new Transport/Step /Note/Backward and Forward menu actions, to move the play-head to previous and next note events, respectively.
- MIDI clip editor (aka. piano-roll) menu Edit/Select Mode/Edit On, Off and Draw actions are now self-toggled when triggered.
- Plug-in presets menu: now sorted alphabetically.
- When summoned from the menu, the View/Tempo Map-Markers... dialog positions itself to the current play-head location, instead of the absolute beginning of the timeline.
- Introducing new application custom theming option: View/Options... …
> qtractor: Update to v1.5.0

- packages/l/lenovo-legion-linux/MAINTAINERS.md
- packages/l/lenovo-legion-linux/package.yml
- packages/l/lenovo-legion-linux/pspec_x86_64.xml
- packages/l/linux-current/REBUILDS.md
- packages/l/linux-current/autopush.yml
- packages/l/linux-lts/autopush.yml
Fixes #2590.
**Summary**
Added `lenovo-legion-linux`, providing drivers and tools to control hardware features for Lenovo Legion laptops such as power profile modes, fan speed, battery conservation/quick charge mode, and more.
**Test Plan**
Ran both the CLI and GUI. Verified switching power mode in Power Profiles Daemon works.
**Checklist**
> lenovo-legion-linux: Add at v0.0.18

- packages/b/budgie-desktop/files/libxfce4windowing-4.19.7.patch
- packages/b/budgie-desktop/package.yml
- packages/b/budgie-desktop/pspec_x86_64.xml
**Summary**
- Backport patch for newer `libxfce4windowing`
**Test Plan**
Install all updated packages in a VM and reboot. Observe that everything appears to work as expected.
**Checklist**
> budgie-desktop: Backport patch for newer libxfce4windowing

- packages/l/libmikmod/abi_symbols
- packages/l/libmikmod/abi_used_libs
- packages/l/libmikmod/abi_used_symbols
- packages/l/libmikmod/files/man.patch
- packages/l/libmikmod/monitoring.yml
- packages/l/libmikmod/package.yml
- packages/l/libmikmod/pspec_x86_64.xml
- packages/p/pingus/MAINTAINERS.md
- packages/p/pingus/abi_used_symbols
- packages/p/pingus/monitoring.yml
- packages/p/pingus/package.yml
- packages/p/pingus/pspec_x86_64.xml
- packages/s/sdl1-mixer/abi_used_symbols
- packages/s/sdl1-mixer/abi_used_symbols32
- packages/s/sdl1-mixer/monitoring.yml
- packages/s/sdl1-mixer/package.yml
- packages/s/sdl1-mixer/pspec_x86_64.xml
**Summary**
- Use cmake build with libmikmod
- Use bugfix branch for sdl1-mixer and build with explicit mikmod support
- Add a direct rundep onto libmikmod from pingus
Pingus' music finally playing again after several years. Enjoy playing Pingus, now with music!
Closes getsolus/packages#1712
**Checklist**
> pingus: Fix music

- packages/f/freetype2/monitoring.yml
- packages/f/freetype2/package.yml
- packages/f/freetype2/pspec_x86_64.xml
**Summary**
Changes:
- Some fields in the `FT_Outline` structure have been changed from signed  to unsigned type
- Rare double-free crashes in the cache subsystem have been fixed
- Excessive stack allocation in the autohinter has been fixed
- The B/W rasterizer has received a major upkeep that results in large performance improvements
- If the new configuration option `TT_CONFIG_OPTION_GPOS_KERNING` is defined, `FT_Get_Kerning` understands rudimentary GPOS kerning
- The internal structures `PS_DesignMap` and `PS_Blend` related to parsing of old Multiple Masters fonts have been removed
Full release notes available [here](https://sourceforge.net/projects/freetype/files/freetype2/2.13.3/)
**Test Plan**
- Rebooted
- Confirmed fonts looked okay Firefox, LibreOffice, gnome-terminal, Element, …
> freetype2: Update to v2.13.3 and add monitoring.yml

- packages/x/xfce4-taskmanager/abi_used_libs
- packages/x/xfce4-taskmanager/abi_used_symbols
- packages/x/xfce4-taskmanager/files/org.xfce.taskmanager.metainfo.xml
- packages/x/xfce4-taskmanager/package.yml
- packages/x/xfce4-taskmanager/pspec_x86_64.xml
**Summary**
- Changes:
- Update copyright year
- build: Fix `-Wcast-align` warning from clang
- Fix UBSan errors
- settings-dialog: Fix `XtmRefreshRate` memory leak
- Dark mode for process-statusbar
- Dark mode for process-monitor
- Allow multiple instances via command line option.
- Fix blurry app icons when UI scale > 1
- Use symbolic window picker icon in toolbar
- Fix broken "show-legend" setting sync
- Translation Updates: Catalan, Croatian, Estonian, Greek, Hebrew, Italian, Occitan (post  1500), Polish, Spanish, Swedish, Turkish
**Test Plan**
Install and launch it in the XFCE VM
**Checklist**
> xfce4-taskmanager: Update to v1.5.7

- packages/p/putty/abi_used_symbols
- packages/p/putty/package.yml
- packages/p/putty/pspec_x86_64.xml
**Summary**
- Major refactoring of Unicode handling to allow the use of 'foreign' Unicode characters, i.e. outside the system's configured default character set / code page. Not yet complete, but the following things work:
- Windows console: usernames and passwords entered interactively into PSCP, PSFTP and Plink can use foreign characters.
- Windows command line: usernames, remote commands, and filenames entered via command-line options can use foreign characters.
- PuTTY's own terminal (on Windows and Unix): even if it's not configured into UTF-8 mode for the main session, interactive usernames and passwords can use foreign characters.
- Unicode version update: all character analysis is updated to Unicode 16.0.0.
- Unicode terminal rendering: national and regional flags are now …
> putty: update to 0.82

- packages/s/snapd/files/wrapper.sh
- packages/s/snapd/package.yml
- packages/s/snapd/pspec_x86_64.xml
**Summary**
- Add a sentence to the warning which runs for every snap, telling users that snaps will stop working soon.
- Part of https://github.com/getsolus/packages/issues/325
- See also https://github.com/getsolus/help-center-docs/pull/589
Sync Message:
The warning that pops up whenever you run a snap has been changed to include the sentence **"Snaps will stop working in early January 2025."** This is part of a process we started back in July to remove snap support from Solus; we wrote about our reasons for this in a [blog post](https://getsol.us/2024/07/15/dropping-apparmor-kernel-patches/). The Help Center has [a page](https://help.getsol.us/docs/user/software/third-party/snap/) with more details about the warning and what you can do if you have snaps installed. Most users will not …
> snapd: Update confinement warning with a date

- packages/v/virtualbox/files/virtualbox.conf
- packages/v/virtualbox/package.yml
- packages/v/virtualbox/pspec_x86_64.xml
**Summary**
"In kernel 6.12, KVM initializes virtualization on module loading by default. This prevents VirtualBox VMs from starting."
https://www.virtualbox.org/wiki/Changelog
**Test Plan**
See that VirtualBox VMs now start.
**Checklist**
> virtualbox: KVM fix

- packages/r/rymdport/package.yml
- packages/r/rymdport/pspec_x86_64.xml
**Summary**
- The received text is now read-only.
- Received items are now not shown until after the download starts.
- Fixed a bug where the folder icon did not display until the receive completed.
- Cleaned up and optimized various code paths.
- Bump to Go 1.21 as lowest supported compiler version.
- Updated fyne to v2.5.3.
- Updated many other dependencies for various fixes and improvements.
**Test Plan**
- Send a file across local network
**Checklist**
> rymdport: Update to v3.7.0

- repo_data/distribution.xml
- repo_data/distribution.xml.in
**Summary**
This package is being deprecated for a few reasons
- It is tricky to package, breaking often, and does not have a consistent maintainer
- Currently does not build
- As of release 2.9.0, upstream considers Flatpak to be the only supported way to install on linux
- [Upstream release notes here](https://github.com/prusa3d/PrusaSlicer/releases/tag/version_2.9.0)
Resolves https://github.com/getsolus/packages/issues/4645
> prusa-slicer: Deprecate

- packages/w/wine/package.yml
- packages/w/wine/pspec_x86_64.xml
**Summary**
Bugfix release
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-10.0-rc3)
**Test Plan**
**Checklist**
> wine: Update to v10.0-rc3

- packages/b/budgie-extras/files/0001-budgie-hotcorners-Fix-formatting-of-defaults-file-JSON.patch
- packages/b/budgie-extras/files/series
- packages/b/budgie-extras/package.yml
- packages/b/budgie-extras/pspec_x86_64.xml
**Summary**
- Fix parsing of default commands
**Test Plan**
Restart Budgie Panel with the Hotcorners applet added, open the applet's settings, click on a corner, enable the command field, and open the dropdown box to see the populated list of default commands.
**Checklist**
> budgie-extras: Fix parsing of default commands

- packages/m/mu/abi_used_symbols
- packages/m/mu/monitoring.yml
- packages/m/mu/package.yml
- packages/m/mu/pspec_x86_64.xml
**Summary**
- documentation improvements
- removal of the old threading option and cleanup
- 'lazy' indexing is even lazier (faster)
- make References:/In-reply-to: headers searchable
- add new combination-field "related:" to search by msgid: or references:
- new command 'mu4e-view-jump-to-mime-part', to jump to some mime part by number
- new variable mu4e-trash-without-flag, if set to non-nil, "trashing" a message will not add the "T" flag
**Test Plan**
- index, search and view message
**Checklist**
> mu: Update to 1.12.8

- packages/f/fb2converter/monitoring.yml
- packages/f/fb2converter/package.yml
- packages/f/fb2converter/pspec_x86_64.xml
**Summary**
- Adding new configuration document.transform.dialogue
- Updating to go1.23.4 and latest packages.
- Release not monitored, see https://archive.is/raGbr
- [changelog](https://github.com/rupor-github/fb2converter/compare/v1.76.1...v1.76.2)
**Test Plan**
- fb2c h
**Checklist**
> fb2converter: Update to 1.76.2

- packages/py/python-maturin/abi_used_libs
- packages/py/python-maturin/abi_used_symbols
- packages/py/python-maturin/package.yml
- packages/py/python-maturin/pspec_x86_64.xml
- packages/py/python-orjson/package.yml
- packages/py/python-orjson/pspec_x86_64.xml
**Summary**
This updates `python-maturin` and `python-orjson` to their latest versions. The latter is necessary for compatibility with maturin 1.8.0
**Test Plan**
- Succesfully built `python-orjson`
- Ran some examples from the orjson README
**Checklist**
> Update maturin and orjson

- packages/s/sof-firmware/files/sof-firmware.metainfo.xml
- packages/s/sof-firmware/monitoring.yml
- packages/s/sof-firmware/package.yml
- packages/s/sof-firmware/pspec_x86_64.xml
**Summary**
- The binary release includes latest versions of firmware, tool and DSP topologies for all Intel released platforms
- Bugfixes
Full release notes [here](https://github.com/thesofproject/sof-bin/releases)
**Solus**
Update package description
**Test Plan**
Verified firmware files were installed to correct paths.
Restarted pipewire.
**Checklist**
> sof-firmware: Update to v2.11.3

- packages/w/wlopm/package.yml
- packages/w/wlopm/pspec_x86_64.xml
**Summary**
- Install to /usr and not /usr/local
**Test Plan**
Restart Budgie and see that `swayidle` automatically starts, and that the `wlopm` binary is found in the path.
**Checklist**
> wlopm: Fix install location

- packages/o/onefetch/abi_used_symbols
- packages/o/onefetch/package.yml
- packages/o/onefetch/pspec_x86_64.xml
**Summary**
- Add language support for OpenSCAD
- Add language support for Modelica
- Add language support for ATS
- Add language support for CUDA
- Add missing nerd fonts icons for some language
**Test Plan**
- Run on packages repo
**Checklist**
> onefetch: Update to v2.23.1

- packages/w/wesnoth/MAINTAINERS.md
- packages/w/wesnoth/abi_used_libs
- packages/w/wesnoth/abi_used_symbols
- packages/w/wesnoth/package.yml
- packages/w/wesnoth/pspec_x86_64.xml
**Summary**
- Campaigns
- Eastern Invasion
- S04c: achievement now only triggers when escaping with all knights alive
- S11/S99: flying units can no longer enter prison cells via the river
- S12: fixed Dra-Nak (if present) having incorrect traits and portraits
- S17b: AI is now more forced to recruit only higher-level units when gold reserves get too high
- S99: prisoners now escape if their jailers are killed
- Under the Burnings Suns
- S04: added sprite for the Cold Dagger item
- Editor: Added Show Tool Information toggle option in the menus and toolbar to allow hiding the informational tooltip on the edge of the screen that shows the current editor tool's usage and palette information
- Translations: Updated Arabic, Bengali, British English, Chinese (Simplified), Czech, Finnish, …
> wesnoth: Update to v1.18.3

- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
**Summary**
No summarized changelog available
Full commit log available [here](https://github.com/notofonts/notofonts.github.io/compare/noto-monthly-release-2024.12.01...noto-monthly-release-2025.01.01)
**Test Plan**
- Wrote some text in LibreOffice Writer
- Confirmed Noto as system font looked okay
**Checklist**
> noto-sans-ttf: Update to v2025.01.01

- packages/s/snapd/files/wrapper.sh
- packages/s/snapd/package.yml
- packages/s/snapd/pspec_x86_64.xml
**Summary**
Fix text to be two lines not three per spec
Change urgency to critical so users must manually dismiss the notification to give them time to copy the link
Resolves #4636
**Test Plan**
Ran the Spotify and Termius snaps from command line and App menu
Verified the correct warning appeared
**Checklist**
> snapd: bugfix: Fix formatting error and change to critical

- packages/d/discover/files/0001-PackageKitBackend-Add-the-Drivers-menu-filtered-by-t.patch
- packages/d/discover/package.yml
- packages/d/discover/pspec_x86_64.xml
**Summary**
Updates our "hardware drivers" category patch to make the icon more consistent with upstream's other icons.
Fixes #4678.
**Test Plan**
- Build from this PR.
- Install the resulting package.
- Launch Discover, ensure that the "hardware drivers" section has an icon that looks consistent and that Discover doesn't blow up on launch.
**Checklist**
> discover: Make hardware drivers icon consistent

- packages/l/llvm/abi_used_libs
- packages/l/llvm/files/0001-Use-mimalloc-for-clang-lld-llvm.patch
- packages/l/llvm/package.yml
- packages/l/llvm/pspec_x86_64.xml
I saw the developer of MOLD mention that using mimalloc with LLD improved performance by about 10%, so I set about seeing how that could be implemented in our package. 
There were basically three methods that I could use:
1. Build a static libmimalloc.a and force it to be linked in (GROSS)
2. Use LD_PRELOAD to force libmimalloc.so to be loaded before each binary invocation. This would be annoying to do as it would likely involve a wrapper script of some kind.
3. Modify the code so that it was directly used as a library. This appeared to be the best fit for our use as a distribution package. (This is what I chose)
This PR essentially modifies LLVM to create a new LLVM library `libLLVMMimalloc.a` and then statically links that into the clang, lld, and llvm-ar binaries (as those seemed to be …
> llvm: Use mimalloc for lld/llvm/clang

- packages/py/python-maturin/package.yml
- packages/py/python-maturin/pspec_x86_64.xml
**Summary**
Changes:
- Update minimal manylinux version for riscv64
- Make invalid version info in `pyproject.toml` less fatal
- Make `maturin develop` fail if version info is missing in `pyproject.toml`
**Test Plan**
**Checklist**
> python-maturin: Update to v1.8.1

- packages/d/drumstick/abi_symbols
- packages/d/drumstick/abi_used_symbols
- packages/d/drumstick/package.yml
- packages/d/drumstick/pspec_x86_64.xml
- packages/v/vmpk/abi_used_symbols
- packages/v/vmpk/monitoring.yml
- packages/v/vmpk/package.yml
- packages/v/vmpk/pspec_x86_64.xml
**Summary**
* Update drumstick to 2.10.0
* Update vmpk to 0.9.1 (to use new drumstick)
**Test Plan**
* Play "Hot crossed buns" on virtual keyboards in drumstick and vmpk
**Checklist**
> Update Drumstick and vmpk

- packages/py/python-neovim/package.yml
- packages/py/python-neovim/pspec_x86_64.xml
**Summary**
- Add missing runtime dependency on `python-typing-extensions`
**Test Plan**
Inspect the built package and see `python-typing-extensions` in the list of dependencies.
**Checklist**
> python-neovim: Add missing runtime dependency

- packages/w/watchexec/package.yml
- packages/w/watchexec/pspec_x86_64.xml
**Summary**
Changelog: https://github.com/watchexec/watchexec/releases/tag/v2.2.1
**Test Plan**
* Ran within a few projects to run tests.
**Checklist**
> watchexec: Update to v2.2.1

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Document the base repo resolution functions
- Document how to set gh-merge-base
- Add pending status for workflow runs
- Add support for listing autolink references
- Add mention of classic token in gh auth login docs
- Allow setting security_and_analysis settings in gh repo edit
- Upgrade generated workflows
- Myriad fixes to provide clarity on determining tracking ref in PR create
- Handle missing upstream configs for `gh pr create`
- Add non-TTY output when fork is newly created
**Test Plan**
**Checklist**
> github-cli: Update to v2.65.0

- packages/w/wildmidi/abi_libs
- packages/w/wildmidi/abi_symbols
- packages/w/wildmidi/abi_used_symbols
- packages/w/wildmidi/package.yml
- packages/w/wildmidi/pspec_x86_64.xml
**Summary**
- A lot of player cleanup and refactoring, thanks to initial work by Azamat H. Hackimov, with addition of several safeguards and minor fixes. Ability to choose which audio output backends to include in the build system: see the cmake script for the relevant WANT_??? options. Player's --help command line switch lists the available backends. Thanks to initial work by Azamat H. Hackimov.
- Improved pkg-config file generation in cmake script
- Workaround a link failure on AmigaOS4 with newer SDKs
- Full changelog [here](https://github.com/Mindwerks/wildmidi/releases/tag/wildmidi-0.4.6)
Resolves https://github.com/getsolus/packages/issues/4744
**Test Plan**
- Play a test MIDI file from the command line
**Checklist**
> wildmidi: Update to v0.4.6

- packages/a/acpica-unix/package.yml
- packages/a/acpica-unix/pspec_x86_64.xml
**Summary**
- Fix 2 critical CVE addressing memory leaks
- EINJ V2 updates
- CDAT updates
- Fix mutex handling, don't release ones that were never acquired
**Security**
- Note these CVEs only affect very old kernels no longer used by Solus
- CVE-2017-13693
- CVE-2017-13694
**Test Plan**
- Rebuild edk2-ovmf, run a qemu virtual machine with UEFI
**Checklist**
> acpica-unix: Update to v20241212

- packages/k/keybase/files/io.keybase.keybase.metainfo.xml
- packages/k/keybase/package.yml
- packages/k/keybase/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> keybase: Add appstream metainfo

- packages/g/git/package.yml
- packages/g/git/pspec_x86_64.xml
**Summary**
- Use after free and double freeing at the end in "git log -L... -p" had been identified and fixed.
- "git maintenance start" crashed due to an uninitialized variable reference, which has been corrected.
- Fail gracefully instead of crashing when attempting to write the contents of a corrupt in-core index as a tree object.
- A "git fetch" from the superproject going down to a submodule used a wrong remote when the default remote names are set differently between them.
- The "gitk" project tree has been synchronized again with its new maintainer, Johannes Sixt.
**Test Plan**
- Make some commits
**Checklist**
> git: Update to v2.47.1

- packages/s/seatd/abi_used_symbols
- packages/s/seatd/monitoring.yml
- packages/s/seatd/package.yml
- packages/s/seatd/pspec_x86_64.xml
**Summary**
- [0.9.1](https://git.sr.ht/~kennylevinsen/seatd/refs/0.9.1)
- [0.9.0](https://git.sr.ht/~kennylevinsen/seatd/refs/0.9.0)
**Test Plan**
- Test revdeps:
- Test `gamescope`: launch supertuxkart
- Test `aquamarine`: launch hyprland session
- Test `wlroots`: launch sway session
- No quick way to test `cosmic-comp`
**Checklist**
> seatd: Update to v0.9.1

- packages/v/valkey/abi_symbols
- packages/v/valkey/package.yml
- packages/v/valkey/pspec_x86_64.xml
**Summary**
- Fix an uncommon crash when using TLS with dual channel replication.
- Make sure repl_down_since is correctly reset when dual channel replication fails.
- Fix a performance regression where a replica does not properly initialize
- the database size when loading a snapshot during replication.
- Make sure the last accessed time is correctly updated when using the TOUCH command with the CLIENT NO-TOUCH option.
- Fix a bug where total_net_repl_output_bytes may report the wrong.
- Fix a bug where used_memory_scripts may report the wrong value.
- Fix a bug where server might crash when using active defrag when scripts are evicted from the script cache.
- Fix a bug where extra memory would be used when storing strings in the inline protocol.
- Fix a bug where the SORT command may …
> valkey: Update to v8.0.2

- packages/g/gpxsee/package.yml
- packages/g/gpxsee/pspec_x86_64.xml
**Summary**
- Improved ENC maps style/rendering.
- Minor IMG maps fixes.
**Test Plan**
- open map; zoom and pan
**Checklist**
> gpxsee: Update to 13.34

- packages/e/eopkg/monitoring.yml
- packages/e/eopkg/package.yml
- packages/e/eopkg/pspec_x86_64.xml
**Packaging**
Fix the description and component of `python-eopkg`, these were not overridden for the pure Python package.
**Test Plan**
```console
$ env LC_ALL=C eopkg info python-eopkg
Installed package:
Name                : python-eopkg, version: 4.1.6, release: 18
Summary             : The Solus package manager (pure python3 eopkg.py3 version)
Description         : The Solus package manager (pure python3 eopkg.py3 version)
Licenses            : GPL-2.0-or-later
Component           : programming.python
Dependencies        : iksemel python-ordered-set python-xattr 
Distribution        : Solus, Dist. Release: 1
Architecture        : x86_64, Installed Size: 3.91 MB
Reverse Dependencies: ypkg 
```
**Checklist**
> eopkg: Fix description and component of python-eopkg

- packages/s/starship/abi_used_symbols
- packages/s/starship/package.yml
- packages/s/starship/pspec_x86_64.xml
**Summary**
- Use best match instead of first match for `battery.display` threshold
- Detect bun using new text-format lockfile
- Allow direnv to detect environment variables
- Add `{success,failure}_style` options
- Handle variable bash `$SHLVL` behavior with explicit option
- Preserve ViModeChangeHandler
- Do not use cygpath for elvish
- Add trailing space to `pipestatus_format`
**Test Plan**
Start a new terminal session, navigate to different types of projects and directories.
**Checklist**
> starship: Update to v1.22.0

- packages/f/fb2converter/package.yml
- packages/f/fb2converter/pspec_x86_64.xml
**Summary**
- Fixing spaces when splitting sentences into words
- [changelog](https://github.com/rupor-github/fb2converter/compare/v1.76.2...v1.76.3)
**Test Plan**
- fb2c convert in.fb2
**Checklist**
> fb2converter: Update to 1.76.3

- packages/p/perl-capture-tiny/package.yml
- packages/p/perl-capture-tiny/pspec_x86_64.xml
**Summary**
- Stringify '$]' for far future compatibility. 
- Fixed docs about custom files for capture
**Test Plan**
- Ran below code and checked it worked as expected:
```perl
use strict;
use warnings;
use Capture::Tiny 'capture';
my ($stdout, $stderr) = capture {
print "Hello, Capture::Tiny!\n";
warn "This is an error message.\n";
};
print "Captured STDOUT: $stdout\n";
print "Captured STDERR: $stderr\n";
```
**Checklist**
> perl-capture-tiny: Update to v0.50

- packages/i/input-remapper/monitoring.yaml
- packages/i/input-remapper/package.yml
- packages/i/input-remapper/pspec_x86_64.xml
**Summary**
- Fix appstream generation
- Remove duplicate appstream metainfo
- Rename desktop file to match appstream metainfo
**Test Plan**
**Checklist**
> input-remapper: Housekeeping

- packages/b/budgie-desktop-branding/package.yml
- packages/b/budgie-desktop-branding/pspec_x86_64.xml
- packages/x/xfce4-desktop-branding/package.yml
- packages/x/xfce4-desktop-branding/pspec_x86_64.xml
- packages/x/xfdesktop/package.yml
- packages/x/xfdesktop/pspec_x86_64.xml
**Summary**
- **xfdesktop: Update default background**
- **xfce4-desktop-branding: Update to v1.1.0**
- **budgie-desktop-branding: Update to v23.0**
**Test Plan**
Start sessions in a VM, see new backgrounds
**Checklist**
> update xfce budgie backgrounds

- packages/py/python-orjson/abi_used_symbols
- packages/py/python-orjson/package.yml
- packages/py/python-orjson/pspec_x86_64.xml
**Summary**
Changes:
- Specify build system dependency on `maturin>=1,<2` again
- Allocate memory using `PyMem_Malloc()` and similar APIs for integration with pymalloc, mimalloc, and tracemalloc
- Source distribution does not ship compressed test documents and relevant tests skip if fixtures are not present
- Build now depends on Rust 1.82 or later instead of 1.72
**Test Plan**
**Checklist**
> python-orjson: Update to v3.10.14

- packages/a/armagetronad/package.yml
- packages/a/armagetronad/pspec_x86_64.xml
**Summary**
Rename app  icon to follow appstream metainfo
**Test Plan**
**Checklist**
> armagetronad: Fix appstream generation

- packages/c/calamares/files/install/branding/solus/branding.desc
- packages/c/calamares/package.yml
- packages/c/calamares/pspec_x86_64.xml
**Summary**
Update branding for 4.7.
**Test Plan**
Spin a smoketest ISO, open the installer, and see the new version and name on the Welcome page.
**Checklist**
> calamares: Update branding for 4.7

- packages/c/calamares/files/install/modules/shellprocess_postinstall.conf
- packages/c/calamares/package.yml
- packages/c/calamares/pspec_x86_64.xml
- packages/c/clr-boot-manager/abi_used_symbols
- packages/c/clr-boot-manager/package.yml
- packages/c/clr-boot-manager/pspec_x86_64.xml
**Summary**
As part of the CBM changes in [CBM PR 7], CBM will now parse the system `/etc/vconsole.conf` file and explicitly set the corresponding
`rd.vconsole.font=(...) rd.vconsole.keymap=(...)`
options on the kernel commandline, such that they are used in rescue initrd shells.
[CBM PR 7]: https://github.com/getsolus/clr-boot-manager/pull/7
To make it clearer and more discoverable to the user what these variables are currently set to in the root fs, the present change ensures that, on new installs, the Solus default font selection of the terminus 32px bold console font with unicode support (ter-v32b), will now also be explicitly listed on the kernel command line for troubleshooting/rescue purposes via CBM.
This is primarily an ergonomics change meant to help Solus users understand how …
> calamares: Explicitly set /etc/vconsole.conf font

- packages/o/obs-cmd/files/fix-version.patch
- packages/o/obs-cmd/package.yml
- packages/o/obs-cmd/pspec_x86_64.xml
**Summary**
Changelog: https://github.com/grigio/obs-cmd/releases/tag/v0.18.2
**Test Plan**
* Checked version reported correctly.
**Checklist**
> obs-cmd: Update to v0.18.2

- packages/s/signal-desktop/package.yml
- packages/s/signal-desktop/pspec_x86_64.xml
**Summary**
- We fixed a bug with @ mentions that sometimes incorrectly included your own account in the autocomplete suggestion list. As a narcissistic workaround, you can still use third-person narration to talk about yourself in your group chats if you ever miss this bug.
**Test Plan**
- Sent messages and checked them in my phone
**Checklist**
> signal-desktop: Update to 7.38.0

- packages/f/firefox/package.yml
- packages/f/firefox/pspec_x86_64.xml
**Summary**
Update firefox to v134.0.1
Changelog available [here](https://www.mozilla.org/en-US/firefox/134.0.1/releasenotes/)
**Test Plan**
- Watch Youtube.
- Test widevine
**Checklist**
> firefox: Update to v134.0.1

- packages/k/kitty/abi_used_symbols
- packages/k/kitty/package.yml
- packages/k/kitty/pspec_x86_64.xml
**Summary**
**Test Plan**
- open term; run cli; view stdout with pager kitten
**Checklist**
> kitty: Update to 0.39.0

- packages/s/sox_ng/package.yml
- packages/s/sox_ng/pspec_x86_64.xml
**Summary**
- Make reading from ffmpeg work on Unix too. popen("rb") returns NULL with glibc (!)
**Test Plan**
- Checked all build.
**Checklist**
> sox_ng: Update to v14.5.0.3

- packages/w/wine/package.yml
- packages/w/wine/pspec_x86_64.xml
**Summary**
Bugfix release
Full changelog available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-10.0-rc6)
**Test Plan**
**Checklist**
> wine: Update to v10.0-rc6

- packages/f/fb2converter/package.yml
- packages/f/fb2converter/pspec_x86_64.xml
**Summary**
- [changelog](https://github.com/rupor-github/fb2converter/compare/v1.76.3...v1.76.4)
**Test Plan**
- fb2c convert in.fb2
**Checklist**
> fb2converter: Update to 1.76.4

- packages/f/firefox/package.yml
- packages/f/firefox/pspec_x86_64.xml
**Summary**
Update firefox to v134.0.2
Changelog available [here](https://www.mozilla.org/en-US/firefox/134.0.2/releasenotes/)
**Test Plan**
- Watch Youtube.
- Test Widevine.
**Checklist**
> firefox: Update to v134.0.2

- packages/n/neovim-qt/abi_used_symbols
- packages/n/neovim-qt/package.yml
- packages/n/neovim-qt/pspec_x86_64.xml
**Summary**
- settings: store window geometry in ~/.config/nvim-qt/window_geometry.conf
- Discard resize if already resizing for same size
- Add option restore_window_geometry
- Avoid a flashing window blink during startup
- Set a default size on first launch
**Test Plan**
Open and edit a file with `nvim-qt`.
**Checklist**
> neovim-qt: Update to v0.2.19

- packages/d/doflicky/package.yml
- packages/d/doflicky/pspec_x86_64.xml
**Summary**
Update to the latest commit removing support for the NVIDIA 470 driver series. This avoids situations where an unsupported (by upstream) driver gets recommended for new installations (with old GPUs).
**Test Plan**
Installed and launched `doflicky` without the 470 modaliases
**Checklist**
> doflicky: Remove NVIDIA 470 driver series

- packages/w/woeusb/package.yml
- packages/w/woeusb/pspec_x86_64.xml
**Summary**
- Needs p7zip to work.
**Test Plan**
- Checked it installed p7zip and did not complain.
**Checklist**
> woeusb: add p7zip as rundep

- packages/py/pysolfc/package.yml
- packages/py/pysolfc/pspec_x86_64.xml
**Summary**
Changes:
- New fullscreen mode, accessible by pressing F11
- Easy option to clear advanced search options
- Lots of bugfixes and enhancements
**Test Plan**
- Played a few rounds of Klondike
- Tried the new fullscreen mode
**Checklist**
> pysolfc: Update to v3.2.0

- packages/w/wine/package.yml
- packages/w/wine/pspec_x86_64.xml
**Summary**
Bugfix release
Full commit log available [here](https://gitlab.winehq.org/wine/wine/-/compare/wine-10.0-rc6...wine-10.0)
Full release notes since 9.0 available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-10.0)
**Test Plan**
**Checklist**
> wine: Update to v10.0

- packages/y/youtube-viewer/package.yml
- packages/y/youtube-viewer/pspec_x86_64.xml
**Summary**
Changes:
- GUI: Added the keybind `CTRL+B` for playing only the audio of a selected video
- CLI: added the `--set-mtime` option and the `set_mtime` config-option
- CLI: normalize the filename after applying the formatting
- CLI: fixed the posting of comments that contain Unicode characters
- When the selected audio quality is not available, fallback to the best available
- No longer try to extract streaming URLs from invidious instances
**Test Plan**
Watched a bunch of YouTube videos using CLI and GUI interfaces
**Checklist**
> youtube-viewer: Update to v3.11.4

- common/CI/config.yaml
**Summary**
Solus 4.7 has been released, so we have no more need of a freeze.
**Test Plan**
n/a
**Checklist**
> common: Lift the freeze for 4.7

- packages/g/gexiv2/abi_used_symbols
- packages/g/gexiv2/package.yml
- packages/g/gexiv2/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked license and homepage.
**Checklist**
> gexiv2: housekeeping

- packages/f/fb2converter/package.yml
- packages/f/fb2converter/pspec_x86_64.xml
**Summary**
- [changelog](https://github.com/rupor-github/fb2converter/compare/v1.76.4...v1.77.0)
**Test Plan**
- fb2c convert in.fb2
**Checklist**
> fb2converter: Update to 1.77.0

- packages/b/brlaser/abi_used_symbols
- packages/b/brlaser/files/1000-solus-duplex.patch
- packages/b/brlaser/monitoring.yaml
- packages/b/brlaser/package.yml
- packages/b/brlaser/pspec_x86_64.xml
**Summary**
New printers added:
- Brother DCP-7010
- Brother DCP-B7500D series
- Brother DCP-L2560DW series
- Brother HL-2240 series
- Brother HL-2260D
- Brother HL-5140 series
- Brother HL-5370DW series
- Brother HL-5450DN series
- Brother HL-L2402D
- Brother MFC-8440
- Brother MFC-L2690DW
- Brother HL-L2400DW
- Brother HL-L2405W
Full changelog [here](https://github.com/Owl-Maintain/brlaser/releases/tag/v6.2.7)
**Packaging**
- Added patch and sed fixup to address duplex printing issues particular to Solus
**Test Plan**
- Check duplex printing with long and short edge
**Checklist**
> brlaser: Update to v6.2.7

- common/Scripts/get-py-deps.py
**Summary**
- Prints a list of python dependencies from a package.yml or a .egg-info or .dist-info path
**Test Plan**
python3 get-py-deps.py
python3 get-py-deps.py /usr/lib/python3.11/site-packages/requests-2.31.0-py3.11.egg-info
**Checklist**
> common/Scripts: Add get-py-deps.py

- packages/q/qtractor/abi_used_symbols
- packages/q/qtractor/package.yml
- packages/q/qtractor/pspec_x86_64.xml
**Summary**
- Duplex MIDI Clock mode is not allowed anymore
- Immediate and consecutive plugin parameter changes are now merged into a single undo-able command, reflecting only the first value change in the series, dropping the previous old algorithm, which was dead wrong if not utterly defective
- Unique track names resolve to the first line only
- Help/Shortcuts: Search tool gets implemented; all changed MIDI controller shortcuts are reverted to their previous settings, when discarding or dismissing the dialog
- Fixed missing MIDI SPP in some cases
**Test Plan**
Launch the app, play midi
**Checklist**
> qtractor: Update to v1.5.2

- packages/k/k3b/package.yml
- packages/k/k3b/pspec_x86_64.xml
- repo_data/distribution.xml
- repo_data/distribution.xml.in
**Summary**
Sox was not deprecated properly and k3b needs to switch to using sox_ng
Signed-off-by: Troy Harvey <harveydevel@gmail.com>
**Test Plan**
Make sure the k3b installs using sox_ng rundep.
**Checklist**
> sox: Deprecate

- packages/w/wxmaxima/abi_used_symbols
- packages/w/wxmaxima/package.yml
- packages/w/wxmaxima/pspec_x86_64.xml
**Summary**
- Remove the change label width popup menu.
- If an empty worksheet is saved as wxmx, allow it to be read again. The generated content.xml was empty, which was no valid XML.
- Fix compiling with clang++.
- CopyAsMathML: encode "<" and ">" as HTML entities (valid XML).
- CopyAsMathML: improvements (operators and identifiers)
- HTML export: print the output labels on the left side.
Full changelog can read [here](https://github.com/wxMaxima-developers/wxmaxima/compare/Version-24.11.0...Version-25.01.0)
**Test Plan**
Launch the app and load recent file
**Checklist**
> wxmaxima: Update to v25.01.0

- packages/c/caddy/files/0001-Remove-update-command-functionality.patch
- packages/c/caddy/package.yml
- packages/c/caddy/pspec_x86_64.xml
**Summary**
- [2.9.0](https://github.com/caddyserver/caddy/releases/tag/v2.9.0)
- [2.9.1](https://github.com/caddyserver/caddy/releases/tag/v2.9.1)
**Test Plan**
Start and stop a local Caddy server.
**Checklist**
> caddy: Update to v2.9.1

- common/Scripts/yauto.py
**Summary**
Add a method for including additional dependencies in `yauto` and use it for the `pyproject.toml` dependencies instead of writing them as a string.
Part of https://github.com/getsolus/packages/issues/4914
**Test Plan**
`
go-task new -- rapidyaml https://github.com/biojppm/rapidyaml/archive/refs/tags/v0.7.2.tar.gz` succeeds
**Checklist**
> yauto: Add extra python dependencies as DepObjects instead of string

- packages/b/blueman/package.yml
- packages/b/blueman/pspec_x86_64.xml
**Summary**
Changes:
- Fix Rfcom plugin dbus signature
- Set an initial selected device in blueman-sendto
- AutoConnect: Store bluetooth address instead of object path
- Applet: Handle UnknownObject DBus error
- Make search button available after device list becomes empty
- Fix Fatal LoadException
- Terminate applet on manager termination if it was started by manager
- Add Galic and Esperanto translations
- AutoConnect: Automatically convert path to address
- Add toggle to force symbolic statusicon
**Test Plan**
- Connected and disconnected my Bluetooth headphones
- Switched Bluetooth audio codec for my headphones
**Checklist**
> blueman: Update to v2.4.4

- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
**Summary**
Full commit log available [here](https://github.com/notofonts/notofonts.github.io/compare/noto-monthly-release-2025.01.01...noto-monthly-release-2025.02.01)
**Test Plan**
- Confirmed everything looked alright with system font set to Noto Sans
- Wrote text in Noto Sans and Noto Serif in LibreOffice Writer
**Checklist**
> noto-sans-ttf: Update to v2025.02.01

- packages/a/ardour/abi_libs
- packages/a/ardour/abi_symbols
- packages/a/ardour/package.yml
- packages/a/ardour/pspec_x86_64.xml
**Summary**
- Ardour 8.11 is a hotfix release that contains a fix for a critical workflow-blocking bug. All users of 8.10 and all Linux distributions should upgrade to 8.11 as soon as possible.
- Full release notes [here](http://ardour.org/whatsnew.html)
**Test Plan**
- Listen to a click track
**Checklist**
> ardour: Update to v8.11

- packages/d/discord/files/disable-breaking-updates.py
- packages/d/discord/files/discord.sh
- packages/d/discord/package.yml
- packages/d/discord/pspec_x86_64.xml
**Summary**
Disable forced client updates that break discord until an update can be cherry-picked.
Taken from https://github.com/flathub/com.discordapp.Discord/blob/master/disable-breaking-updates.py
**Test Plan**
- Make sure discord launches correctly.
- Check that script works when Discord is not updated to the latest version.
**Checklist**
> discord: Disabled forced updates

- packages/x/xfce4-panel/package.yml
- packages/x/xfce4-panel/pspec_x86_64.xml
**Summary**
- libxfce4panel: Fix ABI break
**Test Plan**
Start a new Xfce session.
**Checklist**
> xfce4-panel: Update to v4.20.3

- packages/r/rtmpdump/package.yml
- packages/r/rtmpdump/pspec_x86_64.xml
**Summary**
- March 2024, v2.6
- miscellaneous cleanup of authentication and encryption support
- miscellaneous protocol fixes
- withdraw v2.5 RTMPE type 10 support, code was too broken/non-portable
- 31 March 2012, v2.5
- add RTMPE type 10 handshake support for x86 systems
- add NetStream.Authenticate.UsherToken for Justin.tv
Full changelog [here](https://git.ffmpeg.org/gitweb/rtmpdump.git/blob_plain/6f6bb1353fc84f4cc37138baa99f586750028a01:/ChangeLog)
**Security**
- CVE-2015-8270
- CVE-2015-8271
- CVE-2015-8272
**Test Plan**
- Only revdep is `gstreamer-1.0-plugins-bad`; run nheko, which uses the gstreamer revdep
**Checklist**
> rtmpdump: Update to v2.6

- packages/py/python-maturin/package.yml
- packages/py/python-maturin/pspec_x86_64.xml
**Summary**
Changes:
- Update manylinux/musllinux policies to the latest main
- Exclude packages not in the dependency tree when finding bindings
- Use `uv` automatically when running `maturin develop` inside a uv-created venv
- Consider abi3 minor version when resolving Python interpreters
- Fix clippy warning
- Handle archived dylibs on AIX
- Fix constant rebuilds
- Fix the name of the .data directory in the generated wheel
- Update minimal manylinux version for loongarch64
- Simplify emcc_version using -dumpversion flag
- Strip a possible -git suffix from emcc version
Full release notes available [here](https://github.com/PyO3/maturin/releases/tag/v1.8.2)
**Test Plan**
**Checklist**
> python-maturin: Update to v1.8.2

- packages/x/xfdesktop/MAINTAINERS.md
- packages/x/xfdesktop/abi_used_libs
- packages/x/xfdesktop/abi_used_symbols
- packages/x/xfdesktop/package.yml
- packages/x/xfdesktop/pspec_x86_64.xml
**Summary**
- Enable the usage of application menu
Fixes https://github.com/getsolus/packages/issues/5011
**Test Plan**
Start a new Xfce session, enable the application menu on right click in Desktop settings, right click on the desktop.
**Checklist**
> xfdesktop: Enable usage of application menu

- packages/t/thunar/MAINTAINERS.md
- packages/t/thunar/package.yml
- packages/t/thunar/pspec_x86_64.xml
**Summary**
- Fix wrong selection after rename in list view
- Prevent location bar crash
- Re-allow sorting in search mode
- Fix signal emitting
- Fix GMount leak in 'thunar_file_get_emblem_names'
- Store g_files separately in jobs
- Pass g_files into jobs instead of ThunarFiles
- Ask for confirmation when deleting trashed files
- Prevent files from vanishing after save
- Fix selection after toggling hidden files visibility
- Clean up location button context menu
**Test Plan**
Start Thunar, navigate between a couple of directories.
**Checklist**
> thunar: Update to v4.20.2

- packages/x/xfce4-settings/MAINTAINERS.md
- packages/x/xfce4-settings/abi_used_libs
- packages/x/xfce4-settings/abi_used_symbols
- packages/x/xfce4-settings/package.yml
- packages/x/xfce4-settings/pspec_x86_64.xml
**Summary**
- Install missing helper opera-mailer.desktop
- Delay RRScreenChangeNotify handling when DPMSModeOff
- Fix error handling in main()
- Don't disable DPI setting by default
- wayland: Add missing struct member initialization
- displays: Always enable first output
- Translation Updates
**Test Plan**
Start a new Xfce session, observe that nothing is out of the ordinary.
**Checklist**
> xfce4-settings: Update to v4.20.1

- packages/g/gleam/package.yml
- packages/g/gleam/pspec_x86_64.xml
**Summary**
Gleam's built in LSP has gained some very useful new features, including:
* Rename variables and arguments
* Generate function code action
* Pattern match code action
Plus many more improvements to the compiler in this very nice upgrade.
Read more in the news article: https://gleam.run/news/gleam-gets-rename-variable/
**Test Plan**
**Checklist**
> gleam: Update to v1.8.0

- packages/w/watchexec/abi_used_symbols
- packages/w/watchexec/package.yml
- packages/w/watchexec/pspec_x86_64.xml
**Summary**
Changelog: https://github.com/watchexec/watchexec/releases/tag/v2.3.0
**Test Plan**
* Ran within a few projects to run tests.
**Checklist**
> watchexec: Update to v2.3.0

- packages/o/oniguruma/abi_symbols
- packages/o/oniguruma/monitoring.yaml
- packages/o/oniguruma/package.yml
- packages/o/oniguruma/pspec_x86_64.xml
**Summary**
Update oniguruma to the latest upstream release. Also added monitoring.yaml. Required for #5023 
**Test Plan**
Built, installed, and tested latest ghostty (1.1.0)
**Checklist**
> oniguruma: Update to 6.9.10

- packages/p/password-store/monitoring.yaml
- packages/p/password-store/package.yml
- packages/p/password-store/pspec_x86_64.xml
**Summary**
- Add wl-clipboard as a rundep
- Resolves https://github.com/getsolus/packages/issues/4991
**Test Plan**
- Follow guide [here](https://medium.com/@chasinglogic/the-definitive-guide-to-password-store-c337a8f023a1) to create a test password, see that it copies in wayland session
**Checklist**
> password-store: Add wl-clipboard as a rundep

- packages/m/man-pages/package.yml
- packages/m/man-pages/pspec_x86_64.xml
**Summary**
- Add a few programs that are useful for maintaining manual pages
- Split keyctl.2
- man2/, man3/: SYNOPSIS: Rename function parameters for consistency and correctness
- man2/, man3/: SYNOPSIS: Use typeof() to improve readability of function pointers
- man1/: SYNOPSIS: Use .SY/.YS for formatting commands
- Refactor *FLAGS and LDLIBS variables, as requested by some distros.
Full release notes available [here](https://lore.kernel.org/lkml/5879567.Si16P0KhqQ@pip/T/)
Packaging change: clean up license terms a bit and add some missing licenses
**Test Plan**
- Looked at some of the new and changed man pages
- Used the `pdfman` utility to view the `pdfman` man page as pdf
**Checklist**
> man-pages: Update to v6.10

- packages/g/geoclue/abi_used_symbols
- packages/g/geoclue/files/beacondb-fixes.patch
- packages/g/geoclue/files/beacondb-user-agent.patch
- packages/g/geoclue/package.yml
- packages/g/geoclue/pspec_x86_64.xml
**Summary**
Add two patches recommended by the beacondb maintainer
One patch enables users to successfully submit WiFi geolocation data.
The other patch includes OS name and version in the User Agent string.
This has been requested by beacondb because they don't use API keys.
Details:
https://gitlab.freedesktop.org/geoclue/geoclue/-/merge_requests/192
https://gitlab.freedesktop.org/geoclue/geoclue/-/issues/207
**Test Plan**
Confirmed geolocation was working using `where-am-i` demo
**Checklist**
> geoclue: Add recommended patches for beacondb

- packages/py/python-sdl2/monitoring.yaml
- packages/py/python-sdl2/package.yml
- packages/py/python-sdl2/pspec_x86_64.xml
**Summary**
Changes:
- Updated to wrap new functions and constants in SDL 2.30.10
- Updated to wrap new functions and constants in SDL_mixer 2.8.0
- Updated to wrap new function in SDL_image 2.8.0
- Added a new function `sdl2.ext.get_key_state` for checking if a given key is currently down or up independently of the SDL event queue
Packaging changes: Changed license terms to be mostly SPDX, guided by [this](https://github.com/py-sdl/py-sdl2/blob/master/doc/copying.rst)
**Test Plan**
Launched and configured `m64py`
**Checklist**
> python-sdl2: Update to v0.9.17 and add monitoring.yml

- packages/a/ack/monitoring.yaml
- packages/a/ack/package.yml
- packages/a/ack/pspec_x86_64.xml
**Summary**
- The rules for Pytest were modified so that zsh's ad hoc scraping of filetypes for tab completion wouldn't blow up.
- Add --and and --or options to allow combinations of search terms. This is in addition to the --not that was added in v3.7.0.
- Add support for Pytest filetype.
- Add support for Terraform. Thanks, Thiago Perrotta.
- Full changelog [here](https://beyondgrep.com/changes.txt)
**Test Plan**
- Run some basic filters on file outputs
**Checklist**
> ack: Update to v3.8.1

- packages/d/darktable/abi_symbols
- packages/d/darktable/abi_used_symbols
- packages/d/darktable/package.yml
- packages/d/darktable/pspec_x86_64.xml
**Summary**
- Release notes [here](https://www.darktable.org/2025/02/darktable-5.0.1-released/)
**Test Plan**
- Look at a RAW image
**Checklist**
> darktable: Update to v5.0.1

- packages/g/ghostty/abi_used_symbols
- packages/g/ghostty/files/5762-add-back-fetch-script.patch
- packages/g/ghostty/package.yml
- packages/g/ghostty/pspec_x86_64.xml
**Summary**
Update ghostty to 1.1.2. Resolves #5043
Enhancements:
- Server-side decorations work for X11 too now
- More input method editor improvements
See the [1.1.1 Release Notes](https://ghostty.org/docs/install/release-notes/1-1-1) for detailed changes since 1.1.0 (as the 1.1.2 release contains no changes for Linux users).
**Test Plan**
- Use ghostty to submit this PR
**Checklist**
> ghostty: Update to 1.1.2

- packages/i/ibus/abi_symbols
- packages/i/ibus/abi_used_symbols
- packages/i/ibus/monitoring.yaml
- packages/i/ibus/package.yml
- packages/i/ibus/pspec_x86_64.xml
**Summary**
- Implement preedit color in Plasma Wayland
- Implement `ibus start/restart` for Plasma Wayland
- Show preferences menu item in activate menu
- Fix control keys with game application
- Fix typing freeze with barcode reader
- Fix memory issues
- Fix preedit issue with X applications
- Improve the search for engines
- Identify SUPER_MASK in GTK4 with MOD4_MASK
- Fix SEGV with Super-space in Wayland
- Free names in `ibus_engine_filter_key_event()`
- Fix ibus-daemon timeout in Plasma Wayland
- Set Indicator status at launching time
- Enhance compose keys
- Update compose keys with latest Xorg and GTK
- Use localectl to get current XKB in Wayland instead of setxkbmap
- Update XKB engines
- Update Unicode category
- Change IBus unique name for security issue
- Ignore Super modifier …
> ibus: Update to v1.5.31

- packages/d/deno/abi_symbols
- packages/d/deno/abi_used_symbols
- packages/d/deno/package.yml
- packages/d/deno/pspec_x86_64.xml
**Summary**
Updated `deno` to v2.1.10. This update brings Deno 2.0, the latest major version release, of this alternative JavaScript/TypeScript runtime. For more details on the most notable changes, see the official Deno 2.0 [announcement](https://deno.com/blog/v2.0).
**Test Plan**
- Successfully built and ran the default `fresh` template project.
- Successfully ran some of my TypeScript scripts.
**Checklist**
> deno: Update to v2.1.10

- packages/s/sof-firmware/package.yml
- packages/s/sof-firmware/pspec_x86_64.xml
**Summary**
- The binary release includes latest versions of firmware, tool and DSP topologies for all Intel released platforms
**Highlights**
- New platforms: NXP IMX95
- Zephyr RTOS support added: AMD ACP6.0, MediaTek 8195/86/88
- HIFI5 optimization added to multiple components: IIR core, ARIA and volume
- Zephyr loadable module (LLEXT) support extended in SOF with capability to handle libraries of loadable modules.
- Support added to mark module functions as "cold", allowing code to be run directly from DRAM and save on SRAM usage on platforms supporting the feature.
- Topology: support for new product configurations for Intel LNL/ARL/MTL and NXP IMX95.
- Topology: microphone (IIR and DRC) and speaker processing (IIR, FIR and DRC) added to Intel DSP topologies with Soundwire codecs. …
> sof-firmware: Update to v2.12

- packages/l/libgtk-layer-shell/abi_symbols
- packages/l/libgtk-layer-shell/abi_used_symbols
- packages/l/libgtk-layer-shell/package.yml
- packages/l/libgtk-layer-shell/pspec_x86_64.xml
- packages/w/waybar/package.yml
- packages/w/waybar/pspec_x86_64.xml
- packages/w/wlogout/package.yml
- packages/w/wlogout/pspec_x86_64.xml
- packages/x/xfce4-docklike-plugin/package.yml
- packages/x/xfce4-docklike-plugin/pspec_x86_64.xml
- packages/x/xfce4-notifyd/package.yml
- packages/x/xfce4-notifyd/pspec_x86_64.xml
- packages/x/xfce4-panel/package.yml
- packages/x/xfce4-panel/pspec_x86_64.xml
- packages/x/xfce4-session/package.yml
- packages/x/xfce4-session/pspec_x86_64.xml
- packages/x/xfce4-terminal/package.yml
- packages/x/xfce4-terminal/pspec_x86_64.xml
- packages/x/xfce4-whiskermenu-plugin/package.yml
- packages/x/xfce4-whiskermenu-plugin/pspec_x86_64.xml
- packages/x/xfdesktop/package.yml
- packages/x/xfdesktop/pspec_x86_64.xml
**Summary**
- **libgtk-layer-shell: Update to v0.9.0**
- **xfce4-session: Rebuild against gtk-layer-shell 0.9.0**
- **xfce4-terminal: Rebuild against gtk-layer-shell 0.9.0**
- **xfce4-docklike-plugin: Rebuild against gtk-layer-shell 0.9.0**
- **xfce4-notifyd: Rebuild against gtk-layer-shell 0.9.0**
- **xfce4-whiskermenu-plugin: Rebuild against gtk-layer-shell 0.9.0**
- **xfce4-panel: Rebuild against gtk-layer-shell 0.9.0**
- **xfdesktop: Rebuild against gtk-layer-shell 0.9.0**
- **wlogout: Rebuild against gtk-layer-shell 0.9.0**
- **waybar: Rebuild against gtk-layer-shell 0.9.0**
**Test Plan**
Build budgie-desktop-view (main) against libgtk-layer-shell. gtk_layer_shell_try_commit was now available, I was able to cook, and my local b-d-v supports Wayland again.
**Checklist**
> Update libgtk-layer-shell to 0.9.0

- packages/py/python-ipython/package.yml
- packages/py/python-ipython/pspec_x86_64.xml
- repo_data/distribution.xml
- repo_data/distribution.xml.in
**Summary**
Undeprecate python-ipython to replace python3-ipython
NOTE: The undeprecation must be done first before performing the rest of the rebuilds
**Test Plan**
N/A
**Checklist**
> Python ipython sortout

- packages/l/labwc/package.yml
- packages/l/labwc/pspec_x86_64.xml
- packages/s/sway/package.yml
- packages/s/sway/pspec_x86_64.xml
- packages/x/xdg-desktop-portal-wlr/abi_used_symbols
- packages/x/xdg-desktop-portal-wlr/package.yml
- packages/x/xdg-desktop-portal-wlr/pspec_x86_64.xml
**Summary**
- **labwc: split extraneous rundeps and session into session sub-package**
- **xdg-desktop-portal-wlr: Update to 0.7.1**
- **sway: split extraneous rundeps and session into session sub-package**
Resolves https://github.com/getsolus/packages/issues/4698
**Test Plan**
Installed labwc and then was able to uninstall alacritty.
xdg-desktop-portal-wlr: Validated with screensharing
**Checklist**
> sway & labwc: decouple rundeps

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Changelog available [here](https://github.com/cli/cli/releases/tag/v2.67.0).
**Security**
- CVE-2025-25204
**Test Plan**
**Checklist**
> github-cli: Update to v2.67.0

- packages/t/typst/abi_used_symbols
- packages/t/typst/monitoring.yaml
- packages/t/typst/package.yml
- packages/t/typst/pspec_x86_64.xml
**Summary**
Update to the latest upstream release.
Enhancements:
- There is now a distinction between proper paragraphs and inline-level content
- `outline` has a better out-of-the-box look and is more customizable
- `curve` supersedes `path` for simpler and more flexible Bézier curves
- `image` now supports raw pixel raster formats (for generating images within Typst documents)
- Functions that accept file paths now also accept raw bytes
- Wasm plubins are more flexible and automatically run multi-threaded
- Single-letter strings in math are no longer displayed in italics
- You can now specify which charset should be covered by which font family
- `pdf.embed` lets you embed arbitrary files in the exported PDF
- Experimental HTML export is now available (behind the `--features html` CLI …
> typst: Update to 0.13.0

- packages/z/zenergy/monitoring.yaml
- packages/z/zenergy/package.yml
- packages/z/zenergy/pspec_x86_64.xml
**Summary**
- introduce the zenergy driver
- Allows users to monitor energy usage of AMD Zen CPU's
**Test Plan**
Install module and run goverlay.
**Checklist**
Resolves https://github.com/getsolus/packages/issues/5006
The zenergy driver is a fork of amd_energy modified to allow nonroot users to monitor the energy usage of their AMD Zen Cpus. Combined with MangoHud, users are able to log power usage when gaming.
> zenergy: Add at v1.0

- packages/p/picard/monitoring.yaml
- packages/p/picard/package.yml
- packages/p/picard/pspec_x86_64.xml
**Summary**
Update MusicBrainz Picard to the latest upstream release.
Enhancements:
- Avoid manual copying of authentication tokens
- Support PKCE for OAuth2 authorization
- Implement OAuth2 token revocation on the server
- Add context menu action to merge original and new metadata values
Bugfixes:
- Fix endless recursion on opening script editor dialog
- Fix inaccessible filename options when target path has permissions errors
- Correct capitalization for some headings
- Fix crashes caused by poorly formatted date tags
- Fix incorrect disc numbers when submitting release
- Fix crash when right-clicking on a multi-selection of new tag values
- Correctly handle cover image size for OPUS audio file metadata
Full changelog [here](https://github.com/metabrainz/picard/compare/release-2.12.3...r …
> picard: Update to 2.13.3

- packages/e/eza/package.yml
- packages/e/eza/pspec_x86_64.xml
**Summary**
- Add prettier icon for *.prettierignore
- Add icon for *.hrl
- Add photoshop icon for *.psb
- Add eslint icon for .eslintignore
- Add renovate icon for renovate.json
- Add elixir icon for *.eex, *.leex and mix.lock
**Test Plan**
List files and folders.
**Checklist**
> eza: Update to v0.20.22

- packages/t/tlp/package.yml
- packages/t/tlp/pspec_x86_64.xml
**Summary**
- Battery care is at the forefront of this new release, with charge thresholds and recalibrate/discharge for Chromebooks and Framework laptops, and charge thresholds for Dell laptops.
- Full changelog [here](https://github.com/linrunner/TLP/blob/main/changelog)
**Test Plan**
- disable power-profile-daemon
- enable tlp
- show status with `tlp-stat`
**Checklist**
> tlp: Update to v1.8.0

- packages/p/packagekit/package.yml
- packages/p/packagekit/pspec_x86_64.xml
**Summary**
PackageKit software centers are now supported on Solus, so we don't need to have a scary warning on the PackageKit package anymore.
**Test Plan**
- Build the package from this PR.
- Install the resulting .eopkg.
- Sanity check that PackageKit isn't completely broken.
This change only touches the description and summary fields, so extensive testing is unnecessary.
**Checklist**
> packagekit: Remove "unsupported" warning

- packages/o/opera-stable/files/com.opera.Opera.metainfo.xml
- packages/o/opera-stable/package.yml
- packages/o/opera-stable/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> opera-stable: Add appstream metainfo

- packages/f/freefilesync/files/org.freefilesync.FreeFileSync.appdata.xml
- packages/f/freefilesync/package.yml
- packages/f/freefilesync/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> freefilesync: Add appstream metainfo

- packages/s/socat/abi_used_symbols
- packages/s/socat/monitoring.yaml
- packages/s/socat/package.yml
- packages/s/socat/pspec_x86_64.xml
**Summary**
- Refer to changelog [here](http://www.dest-unreach.org/socat/CHANGES)
Resolves https://github.com/getsolus/packages/issues/5114
**Security**
- CVE-2024-54661
**Test Plan**
- kwallet-pam is a revdep. kwallet runs
**Checklist**
> socat: Update to v1.8.0.3

- packages/n/nemo/package.yml
- packages/n/nemo/pspec_x86_64.xml
**Summary**
- layout editor: Don't use gettext.install to set up the locale
- nemo-places-sidebar.c: Fix query-tooltip callback
- nemo-style-fallback-mandatory.css: Add fallback support for the floating status bar
**Test Plan**
Open Nemo and navigate between different folders.
**Checklist**
> nemo: Update to v6.4.5

- packages/l/lutris/package.yml
- packages/l/lutris/pspec_x86_64.xml
**Summary**
Changes:
- Fix Proton integration bugs so Proton-fixes are applied
- Do not offer DXVK, VKD3D, D3D Extras or DDXVK-NVAPI on Proton versions
- The "Enable Esync" and "Enable Fsync" settings are now passed on to Proton
- DXVK's integrated D8VK will be enabled in Proton
- Emulator BIOS file location (used by libretro) may be set in Preferences
- Obtain the release year from GOG and Itch.io
- MAME Machine setting uses a searchable entry for its enourmous list
- Support for importing Commodore 64 ROMs
**Test Plan**
Installed, played, configured and uninstalled a (Windows) game
**Checklist**
> lutris: Update to v0.5.19

- packages/f/flask-cors/package.yml
- packages/f/flask-cors/pspec_x86_64.xml
**Summary**
Highlighted change:
- Breaking: Change default to disable private network access
Release notes:
- [5.0.0](https://github.com/corydolphin/flask-cors/releases/tag/5.0.0)
- [5.0.1](https://github.com/corydolphin/flask-cors/releases/tag/5.0.1)
**Test Plan**
Ran some examples from the project's README and docs
**Checklist**
> flask-cors: Update to v5.0.1

- packages/m/msmtp/MAINTAINERS.md
- packages/m/msmtp/abi_used_symbols
- packages/m/msmtp/monitoring.yaml
- packages/m/msmtp/package.yml
- packages/m/msmtp/pspec_x86_64.xml
**Summary**
Bugfixes:
- The option -F was fixed
Enhancements:
- Support for SCRAM-SHA-*-PLUS authentication
- A Resent-From header, if present, is now taken into consideration when --read-envelope-from is used.
- Improved msmtpq script
- Improved internationalization support
- Translations were updated
- [News](https://marlam.de/msmtp/news/)
Packaging:
- Added MAINTAINERS.md
- Added monitoring.yaml
**Test Plan**
Installed locally and sent a view emails using it.
**Checklist**
> msmtp: Update to 1.8.28

- packages/f/fritzing-parts/MAINTAINERS.md
- packages/f/fritzing-parts/monitoring.yaml
- packages/f/fritzing-parts/package.yml
- packages/f/fritzing-parts/pspec_x86_64.xml
**Summary**
Depends on #5177
Enhancements:
- Added PSoC™ 6 Artificial Intelligence Evaluation Kit
- Added Calliope Mini 3
- [1.0.4](https://blog.fritzing.org/2024/10/08/fritzing-1-0-4.html)
Packaging:
- Added MAINTAINERS.md
- Added minitoring.yaml
**Test Plan**
Installed, opened and edited some projects.
**Checklist**
> fritzing-parts: Update to 1.0.4

- packages/e/egl-wayland/package.yml
- packages/e/egl-wayland/pspec_x86_64.xml
**Summary**
Changes:
- Fix possible undefined behavior while reading from socket in buffer release thread
**Test Plan**
- Rebooted
- Logged into a GNOME Wayland session
- Launched Steam and played two games
- Ran `xeglgears`, `vkcube`, `glxgears`
**Checklist**
> egl-wayland: Update to v1.1.18

- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
**Summary**
Commit log available [here](https://github.com/notofonts/notofonts.github.io/compare/noto-monthly-release-2025.02.01...noto-monthly-release-2025.03.01)
**Test Plan**
- Wrote some text in Noto Sans and Noto Serif
- Confirmed system looked alright with Noto Sans system font
**Checklist**
> noto-sans-ttf: Update to v2025.03.01

- packages/b/bash/files/profile/profile
- packages/b/bash/package.yml
- packages/b/bash/pspec_x86_64.xml
**Summary**
If a user creates `/etc/profile.d` but does not add a script to the folder, opening a terminal shows an error.
**Test Plan**
- mkdir -p /etc/profile.d
- open terminal
- see `bash: /etc/profile.d/*.sh: No such file or directory` error
- install package
- open terminal
- see no error
**Checklist**
> bash: Fix source error

- .github/workflows/script_lint.yml
- common/Scripts/worklog.py
**Summary**
Add `sync-note-prs` to list PRs with the `Topic: Sync Notes` label.
**Test Plan**
```console
./common/Scripts/worklog.py highlights "1 week ago" -f tty
./common/Scripts/worklog.py highlights "1 week ago" -f md
./common/Scripts/worklog.py highlights "1 week ago" -f html
```
**Checklist**
> common/Scripts/worklog.py: Add listing of PR sync notes

- packages/p/papers/abi_used_symbols
- packages/p/papers/package.yml
- packages/p/papers/pspec_x86_64.xml
**Summary**
Release notes can be read [here]( https://download.gnome.org/sources/papers/47/papers-47.4.news)
**Test Plan**
Launch the app, open a document and test print preview
**Checklist**
> papers: Update to v47.4

- packages/py/python-maturin/package.yml
- packages/py/python-maturin/pspec_x86_64.xml
**Summary**
Changes:
- Fix cargo run uniffi-bindgen when cross compiling
- Add rnet python library to examples
- Bump the attest-build-provenance version in the generated ci file
- Fix platform tag on Solaris/Illumos
- Auto detect PyPy 3.11
- Update manylinux/musllinux policies to the latest main
- Don't install dependencies when running `maturin develop --skip-install`
- Upgrade pyo3 to 0.24.0
- Fix auditwheel .so relocation for namespace modules
**Test Plan**
**Checklist**
> python-maturin: Update to v1.8.3

- packages/l/libheif/abi_used_libs
- packages/l/libheif/abi_used_symbols
- packages/l/libheif/package.yml
- packages/l/libheif/pspec_x86_64.xml
**Summary**
Changes:
- C++ and Go wrapper licenses have been changed to MIT
- Support SVT-AV1 v3.0.0 encoder
- Support emscripten builds for ES6 modules
Packaging change: Enable libsharpyuv (high quality color space conversion) and openh264 functionality
**Test Plan**
Encoded and decoded a bunch of images
**Checklist**
> libheif: Update to v1.19.7

- packages/s/sdl2/package.yml
- packages/s/sdl2/pspec_x86_64.xml
**Summary**
[changelog](https://github.com/libsdl-org/SDL/releases/tag/release-2.32.2)
Main focus for Linux is a fix with pulseaudio
**Test Plan**
Rebuild lite-xl, and launch
**Checklist**
> sdl2: Update to v2.32.2

- packages/a/ardour/abi_libs
- packages/a/ardour/abi_symbols
- packages/a/ardour/package.yml
- packages/a/ardour/pspec_x86_64.xml
**Summary**
- The bug fix introduced in 8.11 turned out to be incorrect, and broke several other things in subtle ways. 8.12 is a completely new approach to fixing the problem with region lengths after certain operations could cause sessions to be unloadable. 8.12 will also correctly load sessions suffering from this problem.
- For several previous versions, the packaging of translation files on macOS was broken. This has been corrected, and translations should work again on that platform.
**Test Plan**
- Start a new session, listen to click track
**Checklist**
> ardour: Update to v8.12

- packages/z/zellij/abi_used_symbols
- packages/z/zellij/package.yml
- packages/z/zellij/pspec_x86_64.xml
**Summary**
- Added stacked resizing: When resizing panes, Zellij will attempt to stack them with their neighbors
- Added pinned floating panes
- New theme definition spec
- New Rust plugin APIs
- Added double/triple mouse click text selection in terminals
- Added showing release notes and tips on startup
**Test Plan**
Re-open Konsole, autostarting Zellij, see the new release notes pane appear. Change directories, make this PR.
**Checklist**
> zellij: Update to v0.42.0

- packages/e/eza/abi_used_symbols
- packages/e/eza/package.yml
- packages/e/eza/pspec_x86_64.xml
**Summary**
- Make temp files visible on white background
- Add `.exercism` folder icon
- Add `.ocamlinit` icon
- Add `.opam` icon
- Add gcloud icon for .gcloudignore
- Add vim icon for .gvimrc, _vimrc and _gvimrc
- Add fennel icon for ~/.fennelrc and ~/.config/fennel/fennelrc
**Test Plan**
**Checklist**
> eza: Update to v0.20.24

- packages/h/heroic-games-launcher/files/com.heroicgameslauncher.hgl.metainfo.xml
- packages/h/heroic-games-launcher/package.yml
- packages/h/heroic-games-launcher/pspec_x86_64.xml
**Summary**
Use our own AppStream metainfo file because the one shipped in their source is a template that requires updating using upstream internal workflow.
**Test Plan**
`appstream-builder --packages-dir=. --include-failed -v `
**Checklist**
> heroic-games-launcher: Use our own AppStream metainfo file

- packages/f/firefox/files/prefs.js
- packages/f/firefox/package.yml
- packages/f/firefox/pspec_x86_64.xml
**Summary**
This makes firefox use beacondb as a geolocation service.
Necessary for systems without geoclue, or with geoclue but no WiFi.
**Test Plan**
- Tested using https://browserleaks.com/geo
- Geolocation now works on my desktop PC
- Geolocation now works on laptop (with WiFi) when geoclue is disabled
**Checklist**
> firefox: Use beacondb geolocation

- common/Hooks/prepare-commit-msg.py
Helps with scriptability for large stack updates and will attempt to autowrite the commit message without needing to open up the editor.
e.g. git commit -m "autocommitmsg" -> "nano: Update to v1.2.3"
Use with caution as not all cases are handled, notably "Rebuild against libfoo" is not currently.
**Test Plan**
`git commit -m "autocommitmsg"` gets transformed to "libquotient: Update to v0.9.3" for a libquotient update.
`git commit -m "do my normal message"` does not get transformed. 
**Checklist**
> common/Hooks: Auto-generate commit msg from "autocommitmsg" with -m flag

- packages/g/github-cli/monitoring.yaml
- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Commands that accept filepath arguments will do glob expansion for `*` characters
- `gh issue/pr comment --edit-last` no longer creates a comment in non-interactive mode if there weren't one. A new flag `--create-if-none` provides this behaviour
- `gh repo sync` provides a more informative error for missing workflow permissions when the token is provided by a GitHub app
- `gh api` no longer tries to encode URLs incorrectly
**Test Plan**
**Checklist**
> github-cli: Update to v2.69.0

- packages/m/mir/abi_used_symbols
- packages/m/mir/package.yml
- packages/m/mir/pspec_x86_64.xml
**Summary**
- Do not mutate a container whilst iterating over it
- Fix crash when disconnecting monitors
- Fix policy destructors not getting called when a surface has been launched on the desktop
**Test Plan**
Start a new Budgie Wayland session using Miriway.
**Checklist**
> mir: Update to v2.20.1

- packages/b/bibletime/abi_used_symbols
- packages/b/bibletime/package.yml
- packages/b/bibletime/pspec_x86_64.xml
**Summary**
- Fixed a compatibility issue causing BibleTime to loop on startup consuming all memory and crashing when reading configuration files written by previous versions of BibleTime based on Qt5.
- Fixed compilation against Sword 1.8.1.
**Test Plan**
- Changed language and read a bible verse.
**Checklist**
> bibletime: Update to v3.1.1

- packages/w/which/package.yml
- packages/w/which/pspec_x86_64.xml
**Summary**
- The function that decides if a found path is executable (file_status) was updated to that of bash version 5.2.
- Full changelog [here](https://git.savannah.gnu.org/cgit/which.git/tree/NEWS)
**Test Plan**
- Locate some binaries
**Checklist**
> which: Update to v2.23

- packages/p/pipx/package.yml
- packages/p/pipx/pspec_x86_64.xml
**Summary**
- Use minimum supported Python to build zipapp
- Resolves https://github.com/getsolus/packages/issues/4944
**Test Plan**
- Installed and uninstalled cowsay with this.
**Checklist**
- Maintainer has not updated this since the issue was open so I am doing the update now.
> pipx: Update to v1.7.1

- packages/w/wavpack/abi_used_symbols
- packages/w/wavpack/package.yml
- packages/w/wavpack/pspec_x86_64.xml
**Summary**
- [5.8.1](https://github.com/dbry/WavPack/releases/tag/5.8.1)
- [5.7.0](https://github.com/dbry/WavPack/releases/tag/5.7.0)
**Test Plan**
Run some the the revdeps: easytag, mixx, audacity
**Checklist**
> wavpack: Update to v5.8.1

- packages/t/typst/abi_used_symbols
- packages/t/typst/package.yml
- packages/t/typst/pspec_x86_64.xml
**Summary**
Update to the latest Typst release. 
- Fix CPU usage when running `typst watch`
- Fix a few bugs with HTML export (experimental!)
- Fix a regression re. querieing labeled symbols
- Fix false positive deprecation warnings for type/str comparisons
See the [changelog](https://typst.app/docs/changelog/0.13.1/) for full details.
**Test Plan**
Compile a complex document (an IEEE conference paper in my case) and verify the result.
**Checklist**
> typst: Update to 0.13.1

- packages/d/discover/package.yml
- packages/d/discover/pspec_x86_64.xml
**Summary**
- Add missing dependencies for Budgie and Xfce
**Test Plan**
Install this package in an Xfce VM that did not previously have Discover installed.
**Checklist**
> discover: Add missing dependencies for Budgie and Xfce

- packages/w/weechat/abi_symbols
- packages/w/weechat/abi_used_symbols
- packages/w/weechat/package.yml
- packages/w/weechat/pspec_x86_64.xml
**Summary**
Changelog available [here](https://github.com/weechat/weechat/releases/tag/v4.6.0).
**Test Plan**
**Checklist**
> weechat: Update to v4.6.0

- packages/e/egl-gbm/package.yml
- packages/e/egl-gbm/pspec_x86_64.xml
- packages/n/nvidia-beta-driver/package.yml
- packages/n/nvidia-beta-driver/pspec_x86_64.xml
- packages/n/nvidia-developer-driver/package.yml
- packages/n/nvidia-developer-driver/pspec_x86_64.xml
- packages/n/nvidia-glx-driver/package.yml
- packages/n/nvidia-glx-driver/pspec_x86_64.xml
**Summary**
egl-gbm 1.1.21 now provides its own ICD file. This updates egl-gbm and removes the ICD files from the nvidia drivers where applicable.
**Test Plan**
- Successfully booted into a GNOME Wayland session and ran `xeglgears`
**Checklist**
> egl-gbm: Update to 1.1.2.1 and rebuild nvidia drivers

- packages/p/putty/package.yml
- packages/p/putty/pspec_x86_64.xml
**Summary**
- Support for ML-KEM, the NIST-standardised post-quantum key exchange mechanism. (In addition to NTRU Prime, which has been supported since 0.78.)
- Bug fix: psftp -b works again.
- Bug fix: assertion failure if an SSH connection times out at the login prompt.
- Bug fix: crash in Pageant if an SSH connection is abandoned while waiting for a deferred decryption passphrase.
- Bug fix: tight loop if PuTTY tried to send an empty answerback string.
- Bug fix: accidental truncation of some configuration edit boxes' contents to 127 characters.
- Bug fix: restored interoperation with third-party tools that auto-fill login prompts by sending ^M for Return.
- Bug fix: confusion when terminal window resized by tools like FancyZones.
- Bug fix: the small keypad keys didn't reliably work …
> putty: Update to v0.83

- packages/py/python-orjson/abi_used_symbols
- packages/py/python-orjson/package.yml
- packages/py/python-orjson/pspec_x86_64.xml
**Summary**
Changes:
- Improve performance of serialization on amd64 machines with AVX-512
- ABI compatibility with CPython 3.14 alpha 6
- Drop support for Python 3.8
**Test Plan**
**Checklist**
> python-orjson: Update to v3.10.16

- packages/x/xdg-desktop-portal-gnome/package.yml
- packages/x/xdg-desktop-portal-gnome/pspec_x86_64.xml
Fixes #5293.
**Summary**
Add `nautilus` to the rundep of `xdg-desktop-portal-gnome`.
**Test Plan**
A file chooser dialogue pops up correctly when I try to upload an image to GitHub.
**Checklist**
> xdg-desktop-portal-gnome: Add nautilus as rundep

- packages/x/xfce4-session/files/0001-scripts-Only-use-dbus-run-session-if-address-is-unse.patch
- packages/x/xfce4-session/package.yml
- packages/x/xfce4-session/pspec_x86_64.xml
**Summary**
- Fix service access on Wayland
**Test Plan**
Start a new Xfce4 Wayland session and see that Neochat auto logs in normally.
**Checklist**
> xfce4-session: Fix service access on Wayland

- packages/h/heroic-games-launcher/abi_used_symbols
- packages/h/heroic-games-launcher/package.yml
- packages/h/heroic-games-launcher/pspec_x86_64.xml
**Summary**
Update Heroic to the latest upstream release. Fixes #5321.
Improvements:
- Switch to Proton-GE as default (from Wine-GE) for better compatibility
- Use Unified Launcher (umu) by default for Proton games
- Better anti-cheat logging to help you troubleshoot
- Built-in wiki links for relevant information on specific games
- New "Guided Tour" for library, filters, and sidebar
- Lots of UI & customization improvements
- ... and much more! See release notes for complete details
Release Notes:
[2.16.0](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.16.0)
[2.16.1](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.16.1)
**Test Plan**
Open Heroic and navigate around store pages & library. Launch a game and make sure things work. …
> heroic-games-launcher: Update to 2.16.1

- packages/r/r2modman/package.yml
- packages/r/r2modman/pspec_x86_64.xml
**Summary**
Icons for r2modman should now be installed.
**Test Plan**
Installed the package and everything seems to be working fine. The icon now shows on the taskbar + application menu and i've checked the font directories to make sure everything was installed in the right place. This is my first ever commit so please check it carefully and I apologise in advance if there are any mistakes. I originally did it manually with a line per font size but saw how the firefox package did its font installation and copied that over and tried to change it to work with r2modman as i assume this is the way it should be done.
**Checklist**
> r2modman: Add icon installation

- packages/n/neovide/abi_used_symbols
- packages/n/neovide/files/0001-Use-fully-qualified-app_id.patch
- packages/n/neovide/package.yml
- packages/n/neovide/pspec_x86_64.xml
**Summary**
Updated neovide to v0.14.1. On my computer this update fixes my malfunctioning `<` key that can type normally in `nvim` but is not picked by `neovide` at all.
Changelog:
- [0.14.1](https://github.com/neovide/neovide/releases/tag/0.14.1)
- [0.14.0](https://github.com/neovide/neovide/releases/tag/0.14.0)
**Test Plan**
An afternoon of coding in Neovide with all of my plugins working.
**Checklist**
> neovide: Update to v0.14.1

- packages/i/inkscape/package.yml
- packages/i/inkscape/pspec_x86_64.xml
**Summary**
- Add a rundep on python-tinycss2, as required by many of the extensions which ship by default with Inkscape.
**Test Plan**
1. Install Inkscape from the repository.
2. Navigate to Extensions > JessyInk > Transitions (or any number of other extensions).
3. Click "Apply". 
4. Note the ugly error.
5. Build Inkscape from this PR, install it, and try the extension again.
6. Note the lack of ugly error.
If you can't reproduce the problem, that's because you already fixed it by having `python-tinycss2` installed :)
**Checklist**
> inkscape: Add missing rundep python-tinycss2

- packages/a/appstream-data/package.yml
- packages/a/appstream-data/pspec_x86_64.xml
**Summary**
**Test Plan**
- Built and installed `appstream-data` from this PR.
- Searched for Deskflow (newly added package) in Discover. It was listed correctly. 
- Searched for KDevelop in Discover. It was also listed correctly, unlike how things were in appstream-data v67.
This run was also conducted as a test of a new modification to the appstream generation automation, which no longer parses `-devel` packages. PR here to see how this works: https://github.com/getsolus/solus-appstream-data/pull/10
**Checklist**
> appstream-data: Update to v68

- packages/g/gpxsee/abi_used_symbols
- packages/g/gpxsee/package.yml
- packages/g/gpxsee/pspec_x86_64.xml
**Summary**
- Added support for Velocitek VTK files
- Added support for 70mai cameras GPS logs
- Added support for geo URIs
- Improved IMG nautical charts rendering
**Test Plan**
- open map, zoom and pan
**Checklist**
> gpxsee: Update to 13.38

- packages/m/mousepad/MAINTAINERS.md
- packages/m/mousepad/abi_libs
- packages/m/mousepad/abi_symbols
- packages/m/mousepad/abi_used_symbols
- packages/m/mousepad/package.yml
- packages/m/mousepad/pspec_x86_64.xml
**Summary**
- Fix GError leak in mousepad_file_autosave_delete_finish
- Save session when an inactive tab is closed
- Fix possible dereference of null pointer
- Extend saved state comparison to auto-saved modified files
- Avoid unnecessary switching to the tab to be closed
- Set current name in save-as dialog for deleted files too
- Fix broken shortcut for reload action
- Hide the launcher for mousepad-settings
- Make widgets focusable again in preferences dialog
- Fix broken conditional to exit on allowed error
- Disconnect from buffer signals when data object is released
**Test Plan**
Open and edit a yaml file in Mousepad.
**Checklist**
> mousepad: Update to v0.6.5

- packages/f/fsearch/abi_used_symbols
- packages/f/fsearch/monitoring.yaml
- packages/f/fsearch/package.yml
- packages/f/fsearch/pspec_x86_64.xml
**Summary**
- This release fixes a buffer overflow on some systems where the data type time_t is less than 8 bytes in size. Typically this affects 32bit systems.
**Test Plan**
- Use fsearch to find all recent pdfs
**Checklist**
> fsearch: Update to v0.2.3

- packages/a/appstream-data/package.yml
- packages/a/appstream-data/pspec_x86_64.xml
**Summary**
Update Appstream Data to v69
**Test Plan**
- Build `appstream-data` from this PR.
- Install it.
- Launch Discover and make sure applications show up.
**Checklist**
> appstream-data: Update to v69

- packages/d/darkly/abi_used_symbols
**Summary**
Adds the updated abi_used_symbols file which was missing in the original merge.
**Checklist**
> [NFC] darkly: update abi_used_symbols

- packages/o/opensnitch/files/opensnitch_group_update.toml
- packages/o/opensnitch/package.yml
- packages/o/opensnitch/pspec_x86_64.xml
**Summary**
- Utilize qol-assist to add users on next boot
**Test Plan**
Remove myself from opensnitch group and install package. Reboot and verify I am part of the opensnitch group.
Finally launch opensnitch
**Checklist**
> opensnitch: Automatically add users to opensnitch group

- packages/s/sof-firmware/package.yml
- packages/s/sof-firmware/pspec_x86_64.xml
**Summary**
- The binary release includes latest versions of firmware, tool and DSP topologies for all Intel released platforms
**Highlights**
For v2.12 series (Meteor Lake and newer), the following new topology files have been added since v2.12:
v2.12.x/sof-ipc4-tplg-v2.12
├── sof-lnl-cs42l43-l0-cs35l56-l23-2ch.tplg
├── sof-lnl-cs42l43-l0-cs35l56-l23-4ch.tplg
├── sof-lnl-cs42l43-l0-cs35l56-l3-2ch.tplg
├── sof-lnl-cs42l43-l2-cs35l56x6-l13.tplg
Full release notes [here](https://github.com/thesofproject/sof-bin/releases)
**Test Plan**
Verified firmware files were installed to correct paths.
Restarted pipewire.
**Checklist**
> sof-firmware: Update to v2.12.1

- packages/d/double-conversion/abi_used_symbols
- packages/d/double-conversion/package.yml
- packages/d/double-conversion/pspec_x86_64.xml
**Summary**
Release note can be read [here](https://github.com/google/double-conversion/releases/tag/v3.3.1)
**Test Plan**
Rebuild `python-ujson` locally
**Checklist**
> double-conversion: Update to v3.3.1

- packages/l/lcov/package.yml
- packages/l/lcov/pspec_x86_64.xml
**Summary**
Release notes:
- [2.3.1](https://github.com/linux-test-project/lcov/releases/tag/v2.3.1)
- [2.3](https://github.com/linux-test-project/lcov/releases/tag/v2.3)
- [2.2](https://github.com/linux-test-project/lcov/releases/tag/v2.2)
**Test Plan**
Rebuild `nomacs` locally
**Checklist**
> lcov: Update to v2.3.1

- packages/q/qpwgraph/abi_used_symbols
- packages/q/qpwgraph/package.yml
- packages/q/qpwgraph/pspec_x86_64.xml
**Summary**
- Loading a patchbay profile (*.qpwgraph) from the command line, is now properly shown on the main window title and toolbar.
- Added PipeWire command line version information.
**Test Plan**
Launch the apps, see my setup graph
**Checklist**
> qpwgraph: Update to v0.8.3

- packages/c/codespell/package.yml
- packages/c/codespell/pspec_x86_64.xml
**Summary**
Release notes:
- [2.4.1](https://github.com/codespell-project/codespell/releases/tag/v2.4.1)
- [2.4.0](https://github.com/codespell-project/codespell/releases/tag/v2.4.0)
**Test Plan**
Check my personal website spelling
**Checklist**
> codespell: Update to v2.4.1

- packages/a/astromenace/files/0001-Remove-remote-icon-from-appdata.patch
- packages/a/astromenace/package.yml
- packages/a/astromenace/pspec_x86_64.xml
**Summary**
Fix appstream metainfo generation
**Test Plan**
**Checklist**
> astromenace: Fix appstream metainfo generation

- packages/s/showtime/package.yml
- packages/s/showtime/pspec_x86_64.xml
**Summary**
Add `gstreamer-1.0-plugins-rs` to rundeps
**Test Plan**
Launch it in Xfce VM and play video
**Checklist**
> showtime: Add missing rundeps

- packages/a/appstream-data/package.yml
- packages/a/appstream-data/pspec_x86_64.xml
**Summary**
**Test Plan**
- Build and install `appstream-data` from this PR.
- Open Discover and search for "Astromenace". 
- See that it is now listed correctly from the Solus repository.
**Checklist**
> appstream-data: Update to v71

- packages/x/xfce4-pulseaudio-plugin/abi_used_symbols
- packages/x/xfce4-pulseaudio-plugin/package.yml
- packages/x/xfce4-pulseaudio-plugin/pspec_x86_64.xml
**Summary**
- Fix gauge notifications
- Change plugin behavior when recording indicator is visible/hidden
- Avoid ScaleMenuItem conflicts
- Prevent "g_hash_table_lookup" crash when "key" is NULL
- Rotate plugin in vertical/deskbar orientation
- Fix libxfce4panel include
**Test Plan**
Restart an Xfce VM and play a youtube video with sound. Hear sound.
**Checklist**
> xfce4-pulseaudio-plugin: Update to v0.5.0

- packages/a/antidote/package.yml
- packages/a/antidote/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://github.com/mattmc3/antidote/releases/tag/v1.9.8).
**Test Plan**
- Loaded plugins.
**Checklist**
> antidote: Update to v1.9.8

- packages/a/adw-gtk3-theme/package.yml
- packages/a/adw-gtk3-theme/pspec_x86_64.xml
**Summary**
Fixes a crash in chromium browser with the light theme.
**Test Plan**
Switch to this theme in Budgie.
**Checklist**
> adw-gtk3-theme: Update to v5.10

- packages/z/zellij/package.yml
- packages/z/zellij/pspec_x86_64.xml
**Summary**
This patch release is mainly intended to address a breaking change in the Rust compiler that caused compilation to fail with `--locked` starting from Rust version 1.86.
This patch also includes some terminal rendering performance improvements - namely consolidating some renders and thus reducing the occasional text flicker.
**Test Plan**
Start a new zellij session, run commands, make this PR.
**Checklist**
> zellij: Update to v0.42.2

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
This release contains dark shipped [sic?] changes that are part of a larger GitHub CLI accessibility preview still under development. More information about these will be announced later this month including various channels to work with GitHub and GitHub CLI maintainers on shaping these experiences.
- Ensure table headers are thematically contrasting
Full changelog available [here](https://github.com/cli/cli/releases/tag/v2.70.0).
**Test Plan**
**Checklist**
> github-cli: Update to v2.70.0

- packages/s/svtplay-dl/package.yml
- packages/s/svtplay-dl/pspec_x86_64.xml
**Summary**
-   svtplay: when we have both subtitles `svenska` and `svenska (allt tal)` it will only download `allt tal`
-   svtplay: fixed -A on `kategorier`
-   svtplay: improve detection on season info based on year
-   subtitles wont be downloaded again on already existing file when using `-M` and `-A`
-   added support for svtbarn
-   tv4play: fixed a crash on downloading clips
-   fixed a crash on bad filenames on windows with `:` in the name
-   changed how configs works.
-   it will check current working directory first for the file `svtplay-dl.yaml`
-   on *nix then `$XDG_CONFIG_HOME/svtplay-dl/svtplay.yaml` / `~/.config/svtplay-dl/svtplay-dl.yaml` then the old `~/.svtplay-dl.yaml`
**Test Plan**
- Downloaded a video from svtbarn.
**Checklist**
> svtplay-dl: Update to v4.109

- packages/o/obs-cmd/files/fix-version.patch
- packages/o/obs-cmd/package.yml
- packages/o/obs-cmd/pspec_x86_64.xml
**Summary**
Changelog: https://github.com/grigio/obs-cmd/releases/tag/v0.18.3
**Test Plan**
* Checked version reported correctly.
**Checklist**
> obs-cmd: Update to v0.18.3

- packages/m/man-pages/package.yml
- packages/m/man-pages/pspec_x86_64.xml
**Summary**
Release notes:
- [6.11](https://lkml.iu.edu/hypermail/linux/kernel/2502.1/10564.html)
- [6.12](https://kernel.googlesource.com/pub/scm/docs/man-pages/man-pages/+/refs/tags/man-pages-6.12)
- [6.13](https://lkml.org/lkml/2025/3/7/1714)
**Test Plan**
- Checked out some new and updated man pages
**Checklist**
> man-pages: Update to v6.13

- packages/e/eza/abi_used_symbols
- packages/e/eza/package.yml
- packages/e/eza/pspec_x86_64.xml
**Summary**
- Don’t truncate branch name
- Fix Hi extension icon
- Add MS DOS icon for *.com
- Add ruby icon for config.ru, Gemfile, Gemfile.lock, procfile, rake, rakefile and change ruby icon
- Add python icon for *.pxd and *.pyx
- Add markdown icon for *.mdx
- Add fsharp icon for *.f# and *.fsscript
- Add clojure icon for *.cljc and *.edn
**Test Plan**
**Checklist**
> eza: Update to v0.21.1

- packages/c/caddy/abi_used_symbols
- packages/c/caddy/files/0001-Remove-update-command-functionality.patch
- packages/c/caddy/files/0001-Tweak-welcome-site-for-Solus.patch
- packages/c/caddy/package.yml
- packages/c/caddy/pspec_x86_64.xml
**Summary**
Changelog available [here](https://github.com/caddyserver/caddy/releases/tag/v2.10.0).
**Test Plan**
Start and stop a Caddy webserver.
**Checklist**
> caddy: Update to v2.10.0

- packages/w/weechat/package.yml
- packages/w/weechat/pspec_x86_64.xml
**Summary**
- core: fix write of weechat.log to stdout with `weechat-headless --stdout`
- core: add refresh of window title on buffer switch, when option weechat.look.window_title is set
**Test Plan**
**Checklist**
> weechat: Update to v4.6.2

- packages/x/xrdp-xfce4-integration/files/startwm.sh
- packages/x/xrdp-xfce4-integration/package.yml
- packages/x/xrdp-xfce4-integration/pspec_x86_64.xml
**Summary**
Fixed an [issue](https://discuss.getsol.us/d/11513-xfce-panel-plugins-not-available-through-xrdp/3) with correctly starting an XFCE session when connecting via XRDP.
**Summary**
**Test Plan**
**Checklist**
> xrdp-xfce4-integration: Use the correct binary in the startwm.sh

- packages/e/egl-x11/abi_used_symbols
- packages/e/egl-x11/abi_used_symbols32
- packages/e/egl-x11/package.yml
- packages/e/egl-x11/pspec_x86_64.xml
**Summary**
Changes:
- Fix a crash if an application tries to call eglSwapInterval with a non-window surface
- Fix `eglQueryDisplayAttrib` so that it returns the correct value for `EGL_TRACK_REFERENCES_KHR`
- Relax the GBM dependency so that it can work with libgbm 21.2 or later
**Test Plan**
Used several XWayland apps in a GNOME Wayland session
**Checklist**
> egl-x11: Update to v1.0.1

- packages/e/egl-wayland/package.yml
- packages/e/egl-wayland/pspec_x86_64.xml
**Summary**
Changes:
- Fix an issue causing EGL_EXT_present_opaque to be advertised on non-Wayland EGLDisplays
**Test Plan**
Used my GNOME Wayland session with various apps for half an hour
**Checklist**
> egl-wayland: Update to v1.1.19

- packages/o/openshot-qt/package.yml
- packages/o/openshot-qt/pspec_x86_64.xml
**Summary**
`python3-qt5` doesn't include Qt5WebView anymore, use `python-qtwebengine` instead
Resolves getsolus/packages#5503
**Test Plan**
Make sure `openshot-qt` launches
**Checklist**
> openshot-qt: Rundep on python-qtwebwngine

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- `gh pr create`: Support Git's `@{push}` revision syntax for determining head ref
- Introduce option to opt-out of spinners
- Update configuration support for accessible colors
- `gh config`: add config settings for accessible prompter and disabling spinner
- Fix multi pages search for gh search
- Fix: `project` commands use shared progress indicator
- Issue commands should parse args early
- Feature detect v1 projects on `issue view`
- Feature detect v1 projects on `issue create`
- Feature detect v1 projects on web mode issue create
- Feature detect v1 projects on issue edit
**Test Plan**
**Checklist**
> github-cli: Update to v2.71.2

- packages/s/steam/package.yml
- packages/s/steam/pspec_x86_64.xml
**Summary**
Changes:
- Build using updated Steam client
- steam.desktop: Update URL used to implement the Community action
- steam.desktop: Update URL used to implement the News action
- steam.desktop: Consistently use an absolute path for the steam executable
- bin_steam.sh: Take over responsibility for running steamdeps during launch
- bin_steam.sh: Remove support for parsing steamdeps.txt
- Appstream metainfo: Normalize homepage URL
- Appstream metainfo: Replace <developer_name> with <developer> as per Appstream 1.0
**Note regarding steam.desktop absolute path change:**
> Some users are known to have a script named steam earlier in the $PATH; for example they might have a /usr/local/bin/steam that passes extra options, sets environment variables, or runs Steam wrapped by some sort of …
> steam: Update to v1.0.0.83

- packages/g/gpxsee/package.yml
- packages/g/gpxsee/pspec_x86_64.xml
**Summary**
- Fixed switched ENC maps units multipliers
- Fixed Vakaros VKX MIME magic detection
- Improved ENC maps style/rendering
- Added support for Vakaros VKX files
- Improved ENC maps rendering performance
**Test Plan**
- open map file; zoom and pan
**Checklist**
> gpxsee: Update to 13.41

- packages/k/kitty/abi_symbols
- packages/k/kitty/package.yml
- packages/k/kitty/pspec_x86_64.xml
**Summary**
- Fixed rendering of emoji using the VS16 variation selector to fail
- Fixed tab bar margins to not be properly blanked
- Fixed incorrect initial font size on some compositors
- Fixed regression hyperlink underline on hover to remain on screen
**Test Plan**
- run cli; view cli output with pager kitten
**Checklist**
> kitty: Update to 0.41.1

- packages/s/stress-ng/abi_used_symbols
- packages/s/stress-ng/package.yml
- packages/s/stress-ng/pspec_x86_64.xml
**Summary**
- adds new stressors
- changelog is located [here](https://github.com/ColinIanKing/stress-ng/releases/tag/V0.18.12)
**Test Plan**
Run s-tui see cpu utilization increase
**Checklist**
> stress-ng: Update to v0.18.12

- packages/p/puzzles/package.yml
- packages/p/puzzles/pspec_x86_64.xml
**Summary**
No changelog available.
Full commit log available [here](https://git.tartarus.org/?p=simon/puzzles.git;a=shortlog)
**Test Plan**
Played a bunch of puzzles
**Checklist**
> puzzles: Update to v20250303

- packages/x/xreader/abi_used_symbols
- packages/x/xreader/package.yml
- packages/x/xreader/pspec_x86_64.xml
**Summary**
- epub: Disable support for sidebar thumbnails
- ev-sidebar-thumbnails.c: Don't attempt to generate thumbnails for epub docs.
- ev-window.c: Check that we have a document set before accessing it.
- epub-document.c: Fix null pointer crash when building a TOC.
**Test Plan**
Open a PDF document with `xreader`.
**Checklist**
> xreader: Update to v4.2.6

- packages/q/q4wine/abi_used_symbols
- packages/q/q4wine/package.yml
- packages/q/q4wine/pspec_x86_64.xml
**Summary**
Changes:
- Updated Dutch translation
- Fixed: qm files are created in CMAKE_BINARY_DIR
- Fixed: Qt6 deprecation warnings
- Fixed: No such signal QComboBox::currentIndexChanged(const QString)
- Fixed: Ignoring return value of function declared with 'nodiscard' attribute
- Fixed: No such signal SingleApplication::messageReceived(const QString)
- Fixed: Wine variables are not parsed properly for wine prefix kill action
- Fixed: Invalid qm file location for cmake 4.x and qt6.9.x
**Test Plan**
Configured my wine prefixes and launched some apps
**Checklist**
> q4wine: Update to v1.4.2

- packages/g/graphviz/abi_used_symbols
- packages/g/graphviz/package.yml
- packages/g/graphviz/pspec_x86_64.xml
- packages/py/pygraphviz/abi_used_symbols
- packages/py/pygraphviz/monitoring.yaml
- packages/py/pygraphviz/package.yml
- packages/py/pygraphviz/pspec_x86_64.xml
**Summary**
Update `graphviz` to v12.2.1 and `pygraphviz` to 1.14 (for changelogs see the commit messages)
Also change the `check` commands for `pygraphviz` to something that still works (and more closely matches upstream CI workflow).
Two tests had to be disabled (they also fail for the old version). The `graphviz` updates fixes additional test failures.
**Test Plan**
- Create some simple graphs with `graphviz`
- Test some examples from the `pygraphviz` tutorial
- Test some examples from the `networkx` tutorial
**Checklist**
> Update graphviz and pygraphviz

- common/Scripts/yauto.py
**Summary**
This slightly adjusts `yauto` to add `python-setuptools` as a build dependency for python modules using `setup.py`, to be more compatible with the recent setuptools debundling.
**Test Plan**
- `go-task new -- rapidyml https://github.com/biojppm/rapidyaml/archive/refs/tags/v0.7.2.tar.gz`
- Confirmed `python-setuptools` was added as a build dep
**Checklist**
> yauto: Add python-setuptools as dep for python modules using setup.py

- packages/s/scd2html/MAINTAINERS.md
- packages/s/scd2html/monitoring.yml
- packages/s/scd2html/package.yml
- packages/s/scd2html/pspec_x86_64.xml
**Summary**
Add package scd2html, which generates HTML from scdoc source files.
Resolves getsolus/packages#3574
**Test Plan**
* Used with various *.scd files to generate HTML
**Checklist**
> scd2html: Add at v1.0.0

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- This release marks the public preview of several accessibility improvements to the GitHub CLI that have been under development over the past year in partnership with our friends at Charm including:
- customizable and contrasting colors
- non-interactive user input prompting
- text-based spinners
- Introduce `gh accessibility` help topic highlighting GitHub CLI accessibility experiences
- [gh pr view] Support `closingIssuesReferences` JSON field
- Fix expected error output of `TestRepo/repo-set-default`
- Ensure accessible password and auth token prompters disable echo mode
- Fix: Accessible multiselect prompt respects default selections
**Test Plan** …
> github-cli: Update to v2.72.0

- packages/o/obs-cmd/files/fix-version.patch
- packages/o/obs-cmd/package.yml
- packages/o/obs-cmd/pspec_x86_64.xml
**Summary**
Changelog: https://github.com/grigio/obs-cmd/releases/tag/v0.18.4
**Test Plan**
* Checked version reported correctly.
**Checklist**
> obs-cmd: Update to v0.18.4

- packages/l/labwc/abi_used_symbols
- packages/l/labwc/package.yml
- packages/l/labwc/pspec_x86_64.xml
**Summary**
- Support all pango font weight options
- Add theme option `osd.workspace-switcher.boxes.border.width`
- Add theme option `osd.window-switcher.item.icon.size`
- Localize desktop-entry application names used by the window switcher via `desktop_entry_name` or the `%n` specifier
- Add `HideCursor` action
- Support application icons in window-switcher using `<field content="icon"/>` and use this by default
- Support application icons in client-list-combined-menu
- Support the use of the keypad-enter key when using menu
- Show fallback icon in SSD titlebar when no `app_id` is set via `<theme><fallbackAppIcon>`
Full changelog available [here](https://github.com/labwc/labwc/releases/tag/0.8.4).
**Test Plan**
Start a new session, …
> labwc: Update to v0.8.4

- packages/e/eopkg/package.yml
- packages/e/eopkg/pspec_x86_64.xml
**Summary**
Release notes can be found [here](https://github.com/getsolus/eopkg/releases/v4.2.0).
Sync Notes: "This week, `eopkg.bin` was updated to version 4.2.0. This release adds a few exciting features and fixes, including the ability to reorder repositories and a fix for some very slow package updates. We've also removed some dead weight in the form of HTTP Basic-Auth support for repositories, which we couldn't think of a good use for. [Read the full changelog](https://github.com/getsolus/eopkg/releases/v4.2.0) if you're interested, and make sure to check out the `eopkg.bin` command if you do package management from the command line. This compiled python3 eopkg will replace the old python2 version as default on all Solus systems soon (we don't give ETAs)."
**Test Plan**
- Build and …
> eopkg: Update to v4.2.0

- common/Scripts/yauto.py
**Summary**
Make it so `python-setuptools` is only added once, by checking whether one of the relevant python build types has already been detected and handled previously.
Fix a small logic error that let pkgconfig deps override python deps in some cases
Also remove some now no longer necessary elements from the check when constructing `builddeps`
**Test Plan**
- `go-task new -- rapidyml https://github.com/biojppm/rapidyaml/archive/refs/tags/v0.7.2.tar.gz`
- `go-task new -- python3 https://www.python.org/ftp/python/3.11.11/Python-3.11.11.tar.xz`
- `go-task new -- python-vdf https://github.com/solsticegamestudios/vdf/archive/refs/tags/v4.0.tar.gz`
- `go-task new -- gtkwave https://sourceforge.net/projects/gtkwave/files/gtkwave-gtk3-3.3.111/gtkwave-gtk3-3.3.111.tar.gz`
**Checklist**
> yauto: Avoid adding setuptools more than once

- packages/a/adw-gtk3-theme/package.yml
- packages/a/adw-gtk3-theme/pspec_x86_64.xml
**Summary**
- Message dialogs now closer to libadwaita.
- Some minor color changes.
- Libhandy viewswitcher buttons now look like normal buttons.
- Many other various tweaks.
Full changelog can be read [here](https://github.com/lassekongo83/adw-gtk3/compare/v5.10...v6.2)
**Test Plan**
Use the theme and make sure nothing looks wrong
**Checklist**
> adw-gtk3-theme: Update to v6.2

- packages/i/inkscape/package.yml
- packages/i/inkscape/pspec_x86_64.xml
- repo_data/distribution.xml
- repo_data/distribution.xml.in
**Summary**
Rename inkscape-docs to inkscape-tutorials to match what upstream calls it                                                                                           
Resolves getsolus/packages#3050
**Test Plan**
Install the package and open tutorial
**Checklist**
> inkscape: Rename inkscape-docs to inkscape-tutorials

- packages/b/budgie-desktop-branding/package.yml
- packages/b/budgie-desktop-branding/pspec_x86_64.xml
- packages/x/xfce4-desktop-branding/package.yml
- packages/x/xfce4-desktop-branding/pspec_x86_64.xml
**Summary**
Add dependency on `maliit-keyboard` to Budgie and Xfce desktop brandings.
**Test Plan**
I don't actually know how to get an onscreen keyboard to pop up.
**Checklist**
> Install `maliit-keyboard` on Budgie and Xfce

- packages/d/deluge/package.yml
- packages/d/deluge/pspec_x86_64.xml
**Summary**
Add python-setuptools to rundeps
Prevents deluge from crashing on launch
**Test Plan**
Launched deluge. Verified it opened correctly and was able to process a torrent.
**Checklist**
> deluge: [NFC] Add python-setuptools to rundeps

- packages/f/fluid-soundfont/package.yml
- packages/f/fluid-soundfont/pspec_x86_64.xml
**Summary**
- Fluidsynth expect soundfont in `/usr/share/soundfonts/default.sf2`. The symlink ensure that midi file can be played without specifying a directory.
- Fix version number
**Test Plan**
Install package and run `fluidsynth example.mid`
**Checklist**
> fluid-soundfont: Fix version number & add symlink

- repo_data/distribution.xml
- repo_data/distribution.xml.in
**Summary**
Looks like it was missed when Qt4 was deprecated.
Fixes https://github.com/getsolus/packages/issues/5649
**Test Plan**
n/a
**Checklist**
> repo_data: Deprecate `shiboken-devel`

- packages/s/steam/package.yml
- packages/s/steam/pspec_x86_64.xml
**Summary**
- Renames steam-udev-rules to steam-devices
- matches upstream name and in external documentation
**Test Plan**
Play balatro using steam flatpak with controller
**Checklist**
Resolves https://github.com/getsolus/packages/issues/5643
> steam: rename udev-rules to device

- packages/e/eopkg/package.yml
- packages/e/eopkg/pspec_x86_64.xml
**Summary**
Updates eopkg to v4.2.1. See the full changelog [here](https://github.com/getsolus/eopkg/releases/tag/v4.2.1).
Fixes #2892.
**Test Plan**
1. Extract [componentdb.cache.zip](https://github.com/user-attachments/files/20199048/componentdb.cache.zip) somewhere on your system. This is a known-bad ComponentDB cache file which triggers the aforementioned bug.
2. Regenerate caches using `sudo eopkg.bin ur --force`.
3. Note that `eopkg.bin lc --debug` works.
4. Copy `componentdb.cache` which you just downloaded to `/var/cache/eopkg/`. Do not remove or alter `componentdb.cache.version` in that directory.
5. Note that `eopkg.bin lc --debug` now crashes with a terrible error.
6. Build and install `eopkg` from this PR.
7. Regenerate caches using `sudo eopkg.bin ur --force`.
8.  Note that …
> eopkg: Update to v4.2.1

- packages/g/gnome-software/files/0001-Allow-notification-to-autostart-on-all-editions.patch
- packages/g/gnome-software/package.yml
- packages/g/gnome-software/pspec_x86_64.xml
**Summary**
Allow notification to autostart on all editions
**Test Plan**
Install on non-Gnome VM and see if notification shows up
**Checklist**
> gnome-software: Allow notification to autostart on all editions

- packages/o/obs-vkcapture/abi_symbols
- packages/o/obs-vkcapture/abi_symbols32
- packages/o/obs-vkcapture/package.yml
- packages/o/obs-vkcapture/pspec_x86_64.xml
**Summary**
Changes:
- Fixed washed out colors when using 10bit video format
- GL: Fixed capture for osu! and Minecraft Bedrock
**Test Plan**
Captured some gameplay footage in "b"
**Checklist**
> obs-vkcapture: Update to v1.5.2

- packages/d/darkly/abi_used_symbols
- packages/d/darkly/package.yml
- packages/d/darkly/pspec_x86_64.xml
**Summary**
Updated to v0.5.20
Release notes can be found [here](https://github.com/Bali10050/Darkly/releases/tag/v0.5.20).
**Test Plan**
Checked to see if everything still works and is themed.
**Checklist**
> darkly: Update to v0.5.20

- packages/v/vivaldi-snapshot/package.yml
- packages/v/vivaldi-snapshot/pspec_x86_64.xml
- packages/v/vivaldi-stable/package.yml
- packages/v/vivaldi-stable/pspec_x86_64.xml
**Summary**
Switches both packages to use the newer metainfo directory, and ensures that the metainfo files pass validation.
- **vivaldi-stable: Fix metainfo file**
- **vivaldi-snapshot: Fix appstream metainfo**
**Test Plan**
Extract each built `.eopkg`, and run `appstreamcli validate --explain` on each appstream metainfo file.
**Checklist**
> vivaldi fix metainfo

- packages/b/brave/package.yml
- packages/b/brave/pspec_x86_64.xml
**Summary**
- Fix install location for metainfo
**Test Plan**
Extract the built `.eopkg` file, and run `appstreamcli validate install/usr/share/metainfo/com.brave.Browser.metainfo.xml --explain`, and see that validation was successful.
**Checklist**
> brave: Fix metainfo location

- packages/t/terminator/package.yml
- packages/t/terminator/pspec_x86_64.xml
**Summary**
Changes:
- Fix invalid escape sequences
- Add plugin to clone ssh and container sessions when terminal is split
- Add reverse search keyboard binding
- Fix translation in popup menu
- Searchbar improvements
- Fix the Save button behavior for Layouts
- Fix test failure
- Ensure that when the layout item is changed the layout sub item also gets reset to first item
- Clean up VTE notification-received signal check
- Fix TypeError in reconfigure() of terminal.py
- Updates for file po/terminator.pot in hu
**Test Plan**
- Check and submit these changes using `terminator`
- Play around with vertical/horizontal splits
**Checklist**
> terminator: Update to v2.1.5

- repo_data/distribution.xml
- repo_data/distribution.xml.in
**Summary**
Files have been merged into the main `rocm-hip` package (in https://github.com/getsolus/packages/pull/2019)
**Checklist**
> repo_data: Deprecate rocm-hip-devel

- packages/l/liteide/abi_used_symbols
- packages/l/liteide/monitoring.yaml
- packages/l/liteide/package.yml
- packages/l/liteide/pspec_x86_64.xml
**Summary**
- LiteIDE support Go1.24
- LiteFind fix FindFilesThread stop
- LiteBuild Add FileBuild menu item
- Fix src/3rdparty/libvterm: crash when out of memory while opening a terminal window Potential Vulnerability in Cloned Function
**Test Plan**
- Installed, checked version and loaded plugins.
**Checklist**
> liteide: Update to v38.4

- packages/m/mutt/abi_used_symbols
- packages/m/mutt/monitoring.yaml
- packages/m/mutt/package.yml
- packages/m/mutt/pspec_x86_64.xml
**Summary**
- 2.2.14:  This is a bug-fix release, fixing a couple possible crashes, in GPGME and with IMAP when logging out, and correcting a small issue with unnecessary encoding of "." in attachment names (2231 encoding).
- 2.2.13: This is a bug-fix release, fixing a possible dangling pointer reference in the SMTP client.
- Change homepage to GitLab, mutt.org does not support https
**Test Plan**
- Launch mutt, create an inbox
**Checklist**
> mutt: Update to v2.2.14

- packages/m/marble/files/0001-Fix-appstream-metainfo.patch
- packages/m/marble/package.yml
- packages/m/marble/pspec_x86_64.xml
**Summary**
Fix appstream metainfo
**Test Plan**
Run `appstreamcli compose install/ --media-dir=media --media-baseurl=localhost:8000 --verbose`
**Checklist**
> marble: Fix appstream metainfo

- packages/m/msmtp/package.yml
- packages/m/msmtp/pspec_x86_64.xml
**Summary**
Enhancements:
- Added a new configuration command set_to_header
- Added a new substitution pattern %F for the from command
- Many improvements in the msmtpq script
- Updated translations
- [News](https://marlam.de/msmtp/news/)
**Test Plan**
Installed locally and sent a view emails using it.
**Checklist**
> msmtp: Update to 1.8.29

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Add `preview prompter` command
- Revert "[gh config] Escape pipe symbol in Long desc for website manual"
- Fix formatting in allowed values for `gh config --help`
- Add retry logic when fetching TUF content in `gh attestation` commands
**Security**
- CVE-2025-48938
**Test Plan**
**Checklist**
> github-cli: Update to v2.74.0

- packages/m/msmtp/package.yml
- packages/m/msmtp/pspec_x86_64.xml
**Summary**
Bugfixes:
- Fixes a double-free bug that was introduced in 1.8.29
- [News](https://marlam.de/msmtp/news/)
**Test Plan**
Installed locally and sent test emails.
**Checklist**
> msmtp: Update to 1.8.30

- packages/y/ypkg/files/python312-compat.patch
- packages/y/ypkg/package.yml
- packages/y/ypkg/pspec_x86_64.xml
**Summary**
Cherry-pick ConfigParser fix
**Test Plan**
- Build ypkg with patched ypkg and see that packager information is populated in pspec.
**Checklist**
> ypkg: Patch for python312

- packages/h/helix/files/hx
- packages/h/helix/package.yml
- packages/h/helix/pspec_x86_64.xml
**Summary**
- Add desktop appinfo file
- Add AppStream metainfo file
- Add application icon
- Add completions for Bash, Fish, and ZSH
- Use upstream Helix launcher, as ours used the wrong runtime path
**Test Plan**
- Open Budgie Menu and found Helix listed in applications.
- Ran `appstreamcli validate --explain` on the installed metainfo file
- Tested completions in Fish shell
- Edited and saved a file
**Checklist**
> helix: Add application info and completions

- packages/w/watchexec/abi_used_symbols
- packages/w/watchexec/package.yml
- packages/w/watchexec/pspec_x86_64.xml
**Summary**
Changelog v2.3.2: https://github.com/watchexec/watchexec/releases/tag/v2.3.2
Changelog v2.3.1: https://github.com/watchexec/watchexec/releases/tag/v2.3.1
**Test Plan**
* Ran within a few projects to run tests.
**Checklist**
> watchexec: Update to v2.3.2

- packages/q/qutebrowser/package.yml
- packages/q/qutebrowser/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://github.com/qutebrowser/qutebrowser/blob/main/doc/changelog.asciidoc#v351-2025-06-05).
**Test Plan**
- Surfed the web.
**Checklist**
> qutebrowser: Update to v3.5.1

- packages/d/darkly/package.yml
- packages/d/darkly/pspec_x86_64.xml
**Summary**
Seems to be a minor bugfix update. Release notes can be found [here](https://github.com/Bali10050/Darkly/releases/tag/v0.5.21).
**Test Plan**
Updated the package and checked to see if everything was still working.
**Checklist**
> darkly: Update to v0.5.21

- packages/m/meson/package.yml
- packages/m/meson/pspec_x86_64.xml
**Summary**
- meson includes bash and zsh autocompletions but are not install when building. This installs them.
**Test Plan**
run meson in command line and tab to see options
**Checklist**
> meson: Install autocompletions

- packages/s/syncthing/package.yml
- packages/s/syncthing/pspec_x86_64.xml
**Summary**
**Syncthing 2 is coming**
Syncthing version 1.x will soon be replaced by Syncthing version 2.x. Version 2 brings a new database format and various cleanups, but remains protocol compatible with Syncthing 1.
More detailed information about Syncthing 2 can be found in the release notes at [https://github.com/syncthing/syncthing/releases](https://github.com/syncthing/syncthing/releases).
**Fixes**
- fix(config): deep copy configuration defaults
- fix(config): mark audit log options as needing restart
- fix(versioner): fix perms of created folders
- fix(syncthing): ensure both config and data dirs exist at startup
- fix(gui): update `uncamel()` to handle strings like 'IDs'
**Features**
- feat(gui): close a modal when pressing ESC after switching modal tabs
Full changelog available …
> syncthing: Update to v1.29.7

- packages/b/budgie-desktop-branding/package.yml
- packages/b/budgie-desktop-branding/pspec_x86_64.xml
- packages/f/font-noto-emoji/files/noto-emoji.metainfo.xml
- packages/f/font-noto-emoji/monitoring.yaml
- packages/f/font-noto-emoji/package.yml
- packages/f/font-noto-emoji/pspec_x86_64.xml
- packages/g/gnome-desktop-branding/package.yml
- packages/g/gnome-desktop-branding/pspec_x86_64.xml
- packages/m/mate-desktop-branding/package.yml
- packages/m/mate-desktop-branding/pspec_x86_64.xml
- packages/n/noto-sans-ttf/files/noto-sans-ttf.metainfo.xml
- packages/n/noto-sans-ttf/files/noto-serif-ttf.metainfo.xml
- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
- packages/p/plasma-desktop-branding/package.yml
- packages/p/plasma-desktop-branding/pspec_x86_64.xml
- packages/x/xfce4-desktop-branding/package.yml
- packages/x/xfce4-desktop-branding/pspec_x86_64.xml
**Summary**
- noto-emoji uses a different source and different versioning it doesn't make sense to contain it within noto
- Our appstream catalog uses the "emoji" icons for the noto-sans package causing confusion, splitting it out will prevent this
- Improve the appstream metainfo for noto-{sans,serif} whilst we're here to pass `appstreamcli validate`
- Add rundep on `font-noto-emoji` to all branding packages to ensure it continues to be installed.
**Test Plan**
Test upgrade paths, test appstream metainfo composition.
**Checklist**
> Split out font-noto-emoji into it's own package

- packages/n/nvidia-vaapi-driver/package.yml
- packages/n/nvidia-vaapi-driver/pspec_x86_64.xml
**Summary**
Changes:
- Fixed to work with newer NVIDIA drivers
- Reworked decoder cleanup to attempt to prevent simultaneous destroys
- Reverted single plane export
- Dial in the log2GobsPerBlockY threshold a bit more
- Implement log2GobsPerBlockY values for even smaller images
- Round up surface sizes and display area for subsampled chroma videos
- Fix some potential deadlocks and H.264 video decode error when seeking
- Fix 545.29 driver version check
- Fixed crashes caused by invalid concurrent writes to `drv->nextObjId`
- Fix "possibly uninitialized" warning
- Fix 32-bit issues
**Test Plan**
`
Confirmed video acceleration in `firefox` works with the `nvidia-beta-driver
**Checklist**
> nvidia-vaapi-driver: Update to v0.0.14

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Document support for `@copilot` in `gh [pr|issue] edit --add-assignee` and `--remove-assignee`
- Fix pr edit when URL is provided
- Fix const in PR finder tests
**Test Plan**
**Checklist**
> github-cli: Update to v2.74.1

- packages/s/scrcpy/abi_used_symbols
- packages/s/scrcpy/package.yml
- packages/s/scrcpy/pspec_x86_64.xml
**Summary**
Changes:
- Associate UHID devices to virtual displays
- Fix audio capture (again) on Android 16
- Fix segfault with --no-window without --no-control
- Fix default locked capture orientation
- Add app name SDL hint
- Report specific error for INJECT_EVENT permission
Full release notes available [here](https://github.com/Genymobile/scrcpy/releases/tag/v3.3)
**Test Plan**
Mirrored my phone's screen and controlled it with mouse and keyboard
**Checklist**
> scrcpy: Update to v3.3

- packages/g/gnome-software/files/0001-Show-console-apps.patch
- packages/g/gnome-software/package.yml
- packages/g/gnome-software/pspec_x86_64.xml
**Summary**
Discover shows console applications by default, make gnome-software do the same.
**Test Plan**
- See if wine is available as a native package.
- Install wine.
**Checklist**
> gnome-software: Enable show console applications

- packages/h/httrack/abi_used_symbols
- packages/h/httrack/package.yml
- packages/h/httrack/pspec_x86_64.xml
**Summary**
- Fixed CVE-2017-14062
**Test Plan**
- Mirror a test site
**Checklist**
> httrack: Update to v3.49.6

- packages/py/python-constantly/package.yml
- packages/py/python-constantly/pspec_x86_64.xml
**Summary**
- Re-enable tests
**Test Plan**
**Checklist**
> python-constantly: Re-enable tests

- packages/py/python-binaryornot/package.yml
- packages/py/python-binaryornot/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> python-binaryornot: Fix tests

- packages/py/python-hatch-vcs/package.yml
- packages/py/python-hatch-vcs/pspec_x86_64.xml
**Summary**
- Re-enable test suite
**Test Plan**
**Checklist**
> python-hatch-vcs: Re-enable tests

- packages/py/python-pathspec/package.yml
- packages/py/python-pathspec/pspec_x86_64.xml
**Summary**
- Re-enable test suite
**Test Plan**
**Checklist**
> python-pathspec: Re-enable tests

- packages/py/python-babel/package.yml
- packages/py/python-babel/pspec_x86_64.xml
**Summary**
I really wish we had separate macros for PEP517 projects and setup.py projects...
**Test Plan**
**Checklist**
> python-babel: Fix tests

- packages/j/jq/abi_symbols
- packages/j/jq/abi_used_symbols
- packages/j/jq/package.yml
- packages/j/jq/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://github.com/jqlang/jq/releases/tag/jq-1.8.0).
- This release includes a number of improvements since the last version. Note that some changes may introduce breaking changes to existing scripts, so be sure to read the release notes carefully.
**Security**
- CVE-2024-23337
- CVE-2024-53427
- CVE-2025-48060
**Test Plan**
- echo '{"foo": "bar"}' | jq '.foo'
**Checklist**
> jq: Update to v1.8.0

- packages/a/appstream-catalog/package.yml
- packages/a/appstream-catalog/pspec_x86_64.xml
**Summary**
Update Appstream Catalog
**Test Plan**
Search for Hexchat, see it is no longer available from the Solus repository.
**Checklist**
> appstream-catalog: Update to latest catalog

- packages/p/pisi/actions.py
- packages/p/pisi/pspec.xml
**Summary**
- Makes python3-based `eopkg.bin` the default eopkg.
**Test Plan**
1. Build and install `pisi` from this PR.
2. Note that `file /usr/bin/eopkg` now reports `/usr/bin/eopkg: symbolic link to eopkg.bin`, and other eopkg symlinks are similarly changed.
3. Note that the upgrade didn't blow up.
4. Try some eopkg operations to make sure stuff works.
The above is what I did. This PR will need ***extensive*** testing -- before this hits stable, we need to make sure upgrades from very old ISOs still work, etc. I think we should test this as a PR until next sync, and then advertise in next week's sync notes that this will be landing shortly after sync so people who don't want to test it yet can switch their systems to stable temporarily. 
**Checklist**
> pisi: Make `eopkg.bin` the default

- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
**Summary**
No changelog available
Full commit log available [here](https://github.com/notofonts/notofonts.github.io/compare/noto-monthly-release-2025.03.01...noto-monthly-release-2025.06.01)
**Test Plan**
- Tested the Noto Sans/Serif in LibreOffice Writer
- Confirmed default Noto Sans system font looked alright in my session
**Checklist**
> noto-sans-ttf: Update to v2025.06.01

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Fix assignees being dropped from `gh pr edit`
- Add accurate context when run rerun fails
- Avoid requesting PR reviewer twice
- Quote filenames suggested at the end of worklow run
**Test Plan**
**Checklist**
> github-cli: Update to v2.74.2

- common/CI/package_checks.py
**Summary**
Update the `PackageBumped` check to check each commit individually, and check the untracked/modified files separately.
Resolves #5900
**Test Plan**
Ran locally against #5881. It now finds:
```
WRN packages/d/dotnet/package.yml:1: Package release is not incremented by 1 (ref: dc4f4a2d97b65beafde2016fe572f983318e3bfa)
```
Previously, it found:
```
WRN packages/d/dotnet-8/package.yml:1: Package release is not 1
ERR packages/d/dotnet-8/pspec_x86_64.xml:1: Package release is not 1
WRN packages/d/dotnet/package.yml:1: Package release is not incremented by 1
ERR packages/d/dotnet/pspec_x86_64.xml:1: Package release is not incremented by 1
```
**Checklist**
> ci/package_checks: Run package version checks against commits

- packages/l/libwebp/abi_used_symbols
- packages/l/libwebp/abi_used_symbols32
- packages/l/libwebp/package.yml
- packages/l/libwebp/pspec_x86_64.xml
**Summary**
This is a binary compatible release
Changes:
- `cross_color_transform_bits` added to WebPAuxStats
- minor lossless encoder speed and compression improvements
- lossless encoding does not use floats anymore
- additional Arm optimizations for lossy & lossless + general code generation improvements
- improvements to WASM performance
- improvements and corrections in webp-container-spec.txt and webp-lossless-bitstream-spec.txt
- further security related hardening and increased fuzzing coverage w/fuzztest
- miscellaneous warning, bug & build fixes
- gif2webp: add -sharp_yuv & -near_lossless
- img2webp: add -exact & -noexact
- exit codes normalized; running an example program with no arguments will output its help and exit with an error
**Test Plan**
- Opened and edited some webp …
> libwebp: Update to v1.5.0

- packages/py/python-beautifulsoup4/package.yml
- packages/py/python-beautifulsoup4/pspec_x86_64.xml
**Summary**
Changes:
- If you pass a function as the first argument to a find* method, the function will only ever be called once per tag, with the Tag object as the argument. Starting in 4.13.0, there were cases where the function would be called with a Tag object and then called again with the name of the tag.
- Added a passthrough implementation for NavigableString.__getitem__ which gives a more helpful exception if the user tries to treat it as a Tag and access its HTML attributes.
- Fixed a bug that caused an exception when unpickling the result of parsing certain invalid markup with lxml as the tree builder.
- Converted the AUTHORS file to UTF-8 for PEP8 compliance.
**Test Plan**
- Ran a bunch of examples from the project's documentation
- Confirmed `anki` works correctly …
> python-beautifulsoup4: Update to v4.13.4

- packages/v/vlc/abi_used_symbols
- packages/v/vlc/package.yml
- packages/v/vlc/pspec_x86_64.xml
**Summary**
- Make AppStream app-id consistent with Flathub
**Test Plan**
Inspected the built eopkg file, and opened the metainfo file; saw that it uses uppercase VLC as the ID.
**Checklist**
> vlc: Fix AppStream metainfo to be consistent with Flathub

- common/Scripts/publish_series.py
**Summary**
Add a script (`publish_series.py`) that publishes a series of commits. This is useful, as it allows for building PRs with multiple commits on the same package.
The script also has the following useful flags:
- `--dry-run` to perform a run without actually pushing anything.
- `--render-commits` to render the commit messages in a browser.
- `--wait` to wait for builds to complete (similar to the current `build_pr` script).
This also waits for an index update by checking the `Last-Modified` header of the checksum.
- `--skip-push` to skip pushing and build from a set of commits on main instead.
**Test Plan**
Publish a series of builds on the build server ('Various updates').
**Checklist**
> common/Scripts: add script for building a series of commits

- packages/t/thunar/abi_used_symbols
- packages/t/thunar/files/620.patch
- packages/t/thunar/package.yml
- packages/t/thunar/pspec_x86_64.xml
**Summary**
Changelog available [here](https://gitlab.xfce.org/xfce/thunar/-/tags/thunar-4.20.3).
I've also added a patch adding support for JXL, AVIF, and WebP for setting wallpapers.
**Test Plan**
Open Thunar, browse different folders.
**Checklist**
> thunar: Update to v4.20.3

- packages/e/eopkg/package.yml
- packages/e/eopkg/pspec_x86_64.xml
**Summary**
This was very useful when testing rapid `eopkg` changes, but is no longer necessary (and is confusing) now that we deploy `eopkg` using a proper tarball. Leaving the git tag logic commented out in case we want to use it for future development testing.
**Test Plan**
1. Run `eopkg --version`. Note the output: `eopkg 4.2.1 ()`.
2. Build and install `eopkg` from this PR.
3. Run `eopkg --version` again. Note that the output no longer contains `()`. 
Fixes https://github.com/getsolus/eopkg/issues/136.
**Checklist**
> eopkg: Remove git tag reference from version string

- packages/g/gnome-clocks/abi_used_symbols
- packages/g/gnome-clocks/package.yml
- packages/g/gnome-clocks/pspec_x86_64.xml
- packages/g/gnome-contacts/package.yml
- packages/g/gnome-contacts/pspec_x86_64.xml
**Summary**
- gnome-clocks: Remove libgeocode-glib from builddeps                                                           
- gnome-contacts: Remove libgeocode-glib from builddeps 
I think we can remove libsoup-2.4 build of geocode-glib
**Test Plan**
Launch the apps and make sure it functions properly
**Checklist**
> Remove libgeocode-glib from builddeps

- packages/n/noto-sans-ttf/files/noto-sans-ttf.metainfo.xml
- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
**Summary**
No changelog available
Full commit log available [here](https://github.com/notofonts/notofonts.github.io/compare/noto-monthly-release-2025.06.01...noto-monthly-release-2025.07.01)
**Test Plan**
- Wrote some text using Noto Sans/Serif in LibreOffice
- Confirmed UI with Noto Sans system font looked alright
**Checklist**
> noto-sans-ttf: Update to v2025.07.01

- packages/py/python-yapsy/files/remove-deprecated-apis.patch
- packages/py/python-yapsy/package.yml
- packages/py/python-yapsy/pspec_x86_64.xml
**Summary**
This fixes, among other things, issues with importlib
Resolves https://github.com/getsolus/packages/issues/5965
**Test Plan**
- Successfully launched `gradience`
**Checklist**
> python-yapsy: Add patch to remove deprecated APIs

- packages/a/asciidoc/package.yml
- packages/a/asciidoc/pspec_x86_64.xml
**Summary**
Breaking Changes
AsciiDoc.py has been rewritten to be a proper Python package, installable via pip.
- Full changelog [here](https://github.com/asciidoc-py/asciidoc-py/blob/main/CHANGELOG.adoc#version-1021-2024-07-16)
**Test Plan**
- Converted an AsciiDoc to HTML
**Checklist**
> asciidoc: Update to v10.2.1

- packages/e/eza/package.yml
- packages/e/eza/pspec_x86_64.xml
**Summary**
**Breaking Change:** The behavior of the `-d` flag has been refined to be more
consistent with `ls`. Its long flag has been changed to `--treat-dirs-as-files`
for clarity, while `--list-dirs` is retained as a backward-compatible alias to be
removed in a future release.
- Replace default_input_path check with "." check
**Test Plan**
**Checklist**
> eza: Update to v0.22.0

- packages/g/gcstar/monitoring.yaml
- packages/g/gcstar/package.yml
- packages/g/gcstar/pspec_x86_64.xml
**Summary**
Intermediate version to incorporate updates since 2025-04-29.
Enhancements:
- The images associated to items can be rotated
- [1.8.1 pre-release](https://gitlab.com/GCstar/GCstar/-/raw/main/gcstar/CHANGELOG)
Package:
- Fix homepage link
**Test Plan**
- Opened library and edited some entries.
**Checklist**
> gcstar: Update to 1.8.0 + updates until 2025-07-02

- packages/x/xfce4-panel/abi_used_symbols
- packages/x/xfce4-panel/files/wayland-wrapper-Prevent-plugin-allocation-blocking.patch
- packages/x/xfce4-panel/package.yml
- packages/x/xfce4-panel/pspec_x86_64.xml
**Summary**
- Fix system tray not appearing sometimes on Wayland
**Test Plan**
Restarted the panel while the tray was broken with `xfce4-panel -r`, and see that the tray immediately appeared.
**Checklist**
> xfce4-panel: Backport patch for systray on Wayland

- packages/l/libvips/abi_used_symbols
- packages/l/libvips/package.yml
- packages/l/libvips/pspec_x86_64.xml
**Summary**
Changes:
- fix API docs build with meson < 0.60
- improve function checks in meson
- tiff: use correct log domain in threadsafe warning handlers
- shift 16-bit output down to 8-bit when unsupported by saver
- text: prevent use of rgba subpixel anti-aliasing
- tiffsave: always apply resolution unit conversion
- cache: suppress invalidation errors in release builds
- dzsave: IIIF: use named region of 'full' when no crop takes place
- pdfload: fix potential crash with pdfium < 6633
**Test Plan**
Edited a bunch of images using `vips`
**Checklist**
> libvips: Update to v8.17.1

- packages/g/grim/abi_used_symbols
- packages/g/grim/monitoring.yaml
- packages/g/grim/package.yml
- packages/g/grim/pspec_x86_64.xml
**Summary**
- grim has moved to gitlab.freedesktop.org
- Add support for ext-image-copy-capture-v1
- Add support for toplevel capture via -T
**Test Plan**
- Take screenshots in Sway
**Checklist**
> grim: Update to v1.5.0

- repo_data/distribution.xml
- repo_data/distribution.xml.in
**Summary**
This subpackage was replaced by `mariadb-common` in https://github.com/getsolus/packages/pull/3327
> Deprecate mariadb-libs

- packages/py/python-orjson/abi_used_symbols
- packages/py/python-orjson/package.yml
- packages/py/python-orjson/pspec_x86_64.xml
**Summary**
Changes:
- Use a deserialization buffer allocated per request instead of a shared buffer allocated on import
- ABI compatibility with CPython 3.14 beta 4
**Test Plan**
**Checklist**
> python-orjson: Update to v3.11.0

- packages/d/docker-compose/package.yml
- packages/d/docker-compose/pspec_x86_64.xml
**Summary**
- docker-compose now uses bake for builds (introduced in v2.37.0) by default
- external binaries as service provider to extend compose behavior
- various bug fixes, improvements and new features
Release notes can be found [here](https://github.com/docker/compose/releases)
Notable release notes:
- https://github.com/docker/compose/releases/tag/v2.38.0
- https://github.com/docker/compose/releases/tag/v2.37.0
- https://github.com/docker/compose/releases/tag/v2.36.0
**Test Plan**
did run builds and few containers with docker-compose
**Checklist**
> docker-compose: Update to v2.38.2

- packages/h/httpd/abi_symbols
- packages/h/httpd/abi_used_symbols
- packages/h/httpd/package.yml
- packages/h/httpd/pspec_x86_64.xml
**Summary**
- Changelog [here](https://downloads.apache.org/httpd/CHANGES_2.4.64)
**Security**
- CVE-2025-53020
- CVE-2025-49812
- CVE-2025-49630
- CVE-2025-23048
- CVE-2024-47252
- CVE-2024-43204
- CVE-2024-42516
**Test Plan**
- Installed, nothing blew up. Very few user-facing rev-deps
**Checklist**
> httpd: Update to v2.4.64

- packages/t/tv-lite/abi_used_symbols
- packages/t/tv-lite/package.yml
- packages/t/tv-lite/pspec_x86_64.xml
**Summary**
- Some build fixes
- Fixed VLC options behavior
- Remember highlighted position in lists
- Work on Wayland
**Test Plan**
- Watched tv.
**Checklist**
> tv-lite: Update to v0.7.8

- packages/r/rustup/package.yml
- packages/r/rustup/pspec_x86_64.xml
**Summary**
- Resolves https://github.com/getsolus/packages/issues/6105
**Test Plan**
- rustup now warns of conflict when rust-devel is already installed
**Checklist**
> rustup: Add conflict for rust-devel

- packages/n/noto-sans-ttf/files/noto-sans-ttf.metainfo.xml
- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
**Summary**
No changelog available.
Full commit log available [here](https://github.com/notofonts/notofonts.github.io/compare/noto-monthly-release-2025.07.01...noto-monthly-release-2025.08.01)
**Test Plan**
- Wrote some text using Noto Sans/Serif in LibreOffice
- Confirmed UI with Noto Sans system font looked alright
**Checklist**
> noto-sans-ttf: Update to v2025.08.01

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- Fixes regressions related to `gh pr create`.
**Test Plan**
**Checklist**
> github-cli: Update to v2.76.2

- packages/c/calamares/files/install/modules/shellprocess_postinstall.conf
- packages/c/calamares/package.yml
- packages/c/calamares/pspec_x86_64.xml
**Summary**
- Don't fetch the repository index when adding the Shannon repository
Fixes https://github.com/getsolus/packages/issues/4050
Fixes https://github.com/getsolus/packages/issues/4950
**Test Plan**
Testing will happen during ISO/release testing.
**Checklist**
> calamares: Modify configuration

- packages/e/eopkg/package.yml
- packages/e/eopkg/pspec_x86_64.xml
**Summary**
Release notes can be found [here](https://github.com/getsolus/eopkg/releases/v4.3.0).
> [!WARNING]
> This PR depends on #6162. Land that first.
For sync notes: 
This week, enjoy a newly-released version of `eopkg`! Version 4.3.0 contains systemd-inhibit support, Zsh completions, usability improvements, general bugfixes, and more. This is another step towards modernization of Solus infrastructure and tooling, including the eventual removal of Python 2.  Read the full changelog [here](https://github.com/getsolus/eopkg/releases/v4.3.0).
**Test Plan**
Give special attention to testing `eopkg` operations in general during the week following this PR landing. 
There was one specific packaging change for this version, which should be tested specially:
- Check out #6162 and follow its …
> eopkg: Update to v4.3.0

- packages/e/eopkg/package.yml
- packages/e/eopkg/pspec_x86_64.xml
**Summary**
Release notes can be found [here](https://github.com/getsolus/eopkg/releases/tag/v4.3.1). See #6163 for full notes.
**Test Plan**
See test plan at https://github.com/getsolus/eopkg/pull/170.
**Checklist**
> eopkg: Update to v4.3.1

- packages/k/keepassxc/abi_used_symbols
- packages/k/keepassxc/package.yml
- packages/k/keepassxc/pspec_x86_64.xml
**Summary**
This allows the "Clear clipboard after" functionality to work under Wayland
Resolves https://github.com/getsolus/packages/issues/6170
**Test Plan**
Confirmed clipboard gets cleared after the time interval set in options
**Checklist**
> keepassxc: Add wl-clipboard runtime dependency

- packages/py/python-orjson/package.yml
- packages/py/python-orjson/pspec_x86_64.xml
**Summary**
Changes:
- Fix build using Rust 1.89 on amd64
- Build now depends on Rust 1.85 or later instead of 1.82
- Fix str on big-endian architectures
**Test Plan**
**Checklist**
> python-orjson: Update to v3.11.2

- packages/b/budgie-screensaver/abi_used_symbols
- packages/b/budgie-screensaver/files/budgie-fingerprint
- packages/b/budgie-screensaver/package.yml
- packages/b/budgie-screensaver/pspec_x86_64.xml
**Summary**
Allow unlocking the screensaver using fingerprints if any are enabled.
**Test Plan**
Tested on both a system with and without a fingerprint reader:
1. Install package
2. Lock screen
3. Unlock using either fingerprint or password
**Checklist**
> budgie-screensaver: Enable fingerprint unlocking

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
Changelogs:
- [2.77.0](https://github.com/cli/cli/releases/tag/v2.77.0)
- [2.78.0](https://github.com/cli/cli/releases/tag/v2.78.0)
**Test Plan**
**Checklist**
> github-cli: Update to v2.78.0

- packages/n/nano/package.yml
- packages/n/nano/pspec_x86_64.xml
**Summary**
- *reason alone was a defective compass*
- The GotoLine menu accepts the prefixes ++ and -- for jumping a number of lines forward or backward.
- Anchors are not forgotten when a line number is given on the command line.
**Test Plan**
- Edit a text file
**Checklist**
> nano: Update to v8.6

- packages/n/nginx/abi_symbols
- packages/n/nginx/abi_used_symbols
- packages/n/nginx/package.yml
- packages/n/nginx/pspec_x86_64.xml
**Summary**
- Release notes [here](https://github.com/nginx/nginx/releases/tag/release-1.29.1)
**Security**
- CVE-2025-53859
**Test Plan**
- See nginx running as a service
**Checklist**
> nginx: Update to v1.29.1

- packages/o/openxr/abi_libs
- packages/o/openxr/abi_symbols
- packages/o/openxr/abi_used_symbols
- packages/o/openxr/package.yml
- packages/o/openxr/pspec_x86_64.xml
**Summary**
Updated to v1.1.51
Release notes: 
[1.1.50
](https://github.com/KhronosGroup/OpenXR-SDK-Source/releases/tag/release-1.1.50) [1.1.51](https://github.com/KhronosGroup/OpenXR-SDK-Source/releases/tag/release-1.1.51)
**Test Plan**
Installed package alongside the dev version and built an envision profile
**Checklist**
> openxr: Update to v1.1.51

- packages/s/syncthing-gtk/files/0002-Update-to-work-with-syncthing-2.0.patch
- packages/s/syncthing-gtk/package.yml
- packages/s/syncthing-gtk/pspec_x86_64.xml
**Summary**
Update flags to work with syncthing 2.x
**Test Plan**
Restarted syncthing-gtk and verified
- it loads with no errors
- Tray icon appears
- UI looks good
- Can restart the daemon from the UI
- Can properly browse shares
**Checklist**
> syncthing-gtk: Patch to work with syncthing 2.x

- common/Scripts/release_monitoring.py
**Summary**
https://cve.circl.lu/ seem to have changed their search query. 
Using the currently suggested double-check URL in the monitoring.yaml leads to a 404 page. This PR updates the comment to the new query format.
**Test Plan**
- Checked if the new url worked for a known vendor/product pair
**Checklist**
> common/Scripts: update CVE search URL

- packages/py/python-typer/monitoring.yaml
- packages/py/python-typer/package.yml
- packages/py/python-typer/pspec_x86_64.xml
**Summary**
Initial inclusion of python-typer.
Having this included in the repository now will make my life way easier in regards to testing ypkg, which will be using `typer`. This might also be of help to Hans for `eopkg` work.
**Test Plan**
Check that basic functionality works. The real test will be when ypkg uses it.
**Checklist**
> python-typer: Add at v0.17.3

- packages/s/solbuild/abi_used_symbols
- packages/s/solbuild/package.yml
- packages/s/solbuild/pspec_x86_64.xml
- packages/y/ypkg/package.yml
- packages/y/ypkg/pspec_x86_64.xml
**Summary**
- **solbuild: Update to 1.8.1**
- **ypkg: Update to 35.0.0**
This PR updates both `solbuild` and `ypkg` to the latest releases. Please see the individual release notes for more details.
**Test Plan**
- Build and install `solbuild`
```bash
go-task build-localcp
sudo eopkg it ./solbuild-*.eopkg
```
- Build and install `ypkg`
```bash
go-task build-localcp
sudo eopkg it ./ypkg-*.eopkg
```
- Build a package like `nano`
```bash
gotopkg nano
go-task build-local
```
**Checklist**
> ypkg update

- packages/m/msmtp/package.yml
- packages/m/msmtp/pspec_x86_64.xml
**Summary**
Bugfixes:
- Fixed check of error conditions with the --read-envelope-from option
- Fixed handling of null bytes in the input by msmtpd (msmtp handled them correctly)
- Fixed handling of very long OAuth tokens
- [News](https://marlam.de/msmtp/news/)
**Test Plan**
- Build and installed locally
- Sent test email
**Checklist**
> msmtp: Update to 1.8.31

- packages/o/openrct2/abi_used_libs
- packages/o/openrct2/abi_used_symbols
- packages/o/openrct2/package.yml
- packages/o/openrct2/pspec_x86_64.xml
**Summary**
- *Climbing the North Face of the Uxbridge Road*
- Release notes [here](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.26)
**Test Plan**
- Start a new scenario
**Checklist**
> openrct2: Update to v0.4.26

- packages/s/scrcpy/package.yml
- packages/s/scrcpy/pspec_x86_64.xml
**Summary**
Changes:
- Fix virtual display after Android 16 upgrade
- Workaround clipboard issue on Samsung devices
- Various technical fixes
Full release notes available [here](https://github.com/Genymobile/scrcpy/releases/tag/v3.3.2)
**Test Plan**
- Mirrored my phone's display
- Controlled my phone with mouse and keyboard
**Checklist**
> scrcpy: Update to v3.3.2

- packages/e/eopkg/package.yml
- packages/e/eopkg/pspec_x86_64.xml
**Summary**
Resolves getsolus/packages#6292
**Test Plan**
- Run env LANG=fr_FR.UTF-8 eopkg --help and make sure French translations load.
**Checklist**
> eopkg: Add translations to nuitka-compiled version

- packages/y/ypkg/package.yml
- packages/y/ypkg/pspec_x86_64.xml
**Summary**
Add `python-zstandard` to the runtime dependencies, and remove `tree` from the build dependencies.
**Test Plan**
Inspect the .eopkg metadata and see that `python-zstandard` was added to the dependency list.
**Checklist**
> ypkg: Add python-zstandard to the runtime dependencies

- packages/e/expat/abi_symbols
- packages/e/expat/abi_symbols32
- packages/e/expat/abi_used_symbols
- packages/e/expat/package.yml
- packages/e/expat/pspec_x86_64.xml
**Summary**
Changelog available [here](https://github.com/libexpat/libexpat/blob/R_2_7_2/expat/Changes).
**Security**
- CVE-2025-59375
**Test Plan**
Build `gdb` against this version.
**Checklist**
> expat: Update to v2.7.2

- packages/f/fping/abi_used_symbols
- packages/f/fping/package.yml
- packages/f/fping/pspec_x86_64.xml
**Summary**
- Memory allocation safety checks for event storage
- Fix off-by-one boundary check in seqmap code
- The minimum value for the period (-p flag) is now 0.001 milliseconds, since it probably never makes sense to use a smaller value, and to avoid doing a very large memory allocation for event storage.
**Test Plan**
- fping google.se
**Checklist**
> fping: Update to v5.4

- packages/l/libvips/abi_symbols
- packages/l/libvips/package.yml
- packages/l/libvips/pspec_x86_64.xml
**Summary**
Changes:
- rank: fix an off-by-one error
- popplerload, svgload: validate page size
- pdfiumload: allow both dpi and scale to be set
- svgload: honor DPI when scaling elements with non-pixel units
- disable redundant Highway AVX512 targets
- openslideload_source: flag operation as "nocache"
- remove vipsprofile.1 man page from install
- tiffload: ensure processing halts for memory-related errors
- tiffload: increase memory limit from 20MB to 50MB
- fix vapi build
- tiffsave: include sample format when copying tiff data
**Test Plan**
Edited a bunch of images using `vip`
**Checklist**
> libvips: Update to v8.17.2

- packages/r/rclone/package.yml
- packages/r/rclone/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://rclone.org/changelog/#v1-71-0-2025-08-22).
**Test Plan**
- Checked settings.
**Checklist**
> rclone: Update to v1.71.0

- packages/d/deno/MAINTAINERS.md
- packages/d/deno/abi_used_symbols
- packages/d/deno/package.yml
- packages/d/deno/pspec_x86_64.xml
**Summary**
**Changelogs:**
- [2.4.2](https://github.com/denoland/deno/releases/tag/v2.4.2)
- [2.4.3](https://github.com/denoland/deno/releases/tag/v2.4.3)
- [2.4.4](https://github.com/denoland/deno/releases/tag/v2.4.4)
- [2.4.5](https://github.com/denoland/deno/releases/tag/v2.4.5)
- [2.5.0](https://github.com/denoland/deno/releases/tag/v2.5.0)
- [2.5.1](https://github.com/denoland/deno/releases/tag/v2.5.1)
- [2.5.2](https://github.com/denoland/deno/releases/tag/v2.5.2)
Read what is new in the 2.5 series [here](https://deno.com/blog/v2.5)
**Test Plan**
- Successfully built and ran the default `fresh` template project.
**Checklist**
> deno: Update to v2.5.2

- packages/d/deno/package.yml
- packages/d/deno/pspec_x86_64.xml
**Summary**
- Remove extra character in package summary
**Test Plan**
See that the summary now only has one A.
**Checklist**
> deno: Remove extra char in summary

- packages/m/miriway/abi_used_libs
- packages/m/miriway/abi_used_symbols
- packages/m/miriway/package.yml
- packages/m/miriway/pspec_x86_64.xml
**Summary**
Changelog available [here](https://github.com/Miriway/Miriway/releases/tag/v25.11).
**Test Plan**
Start a Budgie Miriway session.
**Checklist**
> miriway: Update to v25.11

- packages/l/libquotient/package.yml
- packages/l/libquotient/pspec_x86_64.xml
- packages/n/neochat/package.yml
- packages/n/neochat/pspec_x86_64.xml
**Summary**
Changelog available [here](https://github.com/quotient-im/libQuotient/releases/tag/0.9.5).
**Test Plan**
Start NeoChat after installing this version, see that NeoChat still functions.
**Checklist**
> libquotient: Update to v0.9.5

- common/Scripts/yauto.py
**Summary**
As discussed in https://github.com/getsolus/ypkg/pull/121, this PR adds a hint for the yaml-language-server to the autogenerated package.yml. 
There was also one more yes -> true conversion to be found in the script. 
**Test Plan**
- Have the JSON schema from https://github.com/getsolus/ypkg/pull/121 installed in  /usr/share/ypkg/schema/schema.json
- Have a yaml language server setup in your editor
- Create a new package with `go-task new`
- Check that the schema is picked up and you get LSP hints
**Checklist**
> yauto: Add json schema hint to generated file

- packages/c/cnijfilter2/package.yml
- packages/o/owncloud-client/package.yml
- packages/v/vscode/package.yml
**Summary**
- **[NFC] cnijfilter2: Use `false` instead of `no`**
- **[NFC] vscode: Use `true`/`false` instead of `yes`/`no`**
- **[NFC] owncloud-client: Use `false` instead of `no`**
**Test Plan**
n/a
**Checklist**
> fix more booleans

- packages/h/hyprlock/abi_symbols
- packages/h/hyprlock/abi_used_symbols
- packages/h/hyprlock/package.yml
- packages/h/hyprlock/pspec_x86_64.xml
**Summary**
A new patch release with some fixes :)
Release notes link:
- https://github.com/hyprwm/hyprlock/releases/tag/v0.9.2
Changes:
- Make detection of PAM library more portable
- background: monitor transforms fixups
- core: remove dmabuf listeners after we are done with Screencopy
- renderer: move asyncResourceGatherer out of the rendere
- core: monitor replug workaround for nvidia
- lock-surface: remove redundant sendDestroy calls
- Refactor asset management to use shared_ptr
- renderer: fix nvidia workaround
**Test Plan**
Run hyprlock with hyprland and wlogout (configured for locking with hyprlock)
**Checklist**
> hyprlock: Update to 0.9.2

- packages/g/gamescope/abi_used_symbols
- packages/g/gamescope/monitoring.yaml
- packages/g/gamescope/package.yml
- packages/g/gamescope/pspec_x86_64.xml
**Summary**
- steamcompmgr: Hold wlserver_lock around handle_presented_xdg
- Resolves https://github.com/getsolus/packages/issues/6373
**Test Plan**
- Checked version.
**Checklist**
> gamescope: Update to v3.16.17

- packages/d/darkly/MAINTAINERS.md
- packages/d/darkly/package.yml
- packages/d/darkly/pspec_x86_64.xml
**Summary**
Updated Darkly to the latest version.
Release notes can be found [here](https://github.com/Bali10050/Darkly/releases/tag/v0.5.23).
**Test Plan**
Installed the package and everything continued to work as it should.
**Checklist**
> darkly: Update to v0.5.23

- packages/d/desktop-file-utils/abi_used_libs
- packages/d/desktop-file-utils/abi_used_symbols
- packages/d/desktop-file-utils/package.yml
- packages/d/desktop-file-utils/pspec_x86_64.xml
**Summary**
- Increase GLib requirement to 2.26
- Fix install failing on second run
- Fix use of deprecated Meson feature resulting in a warning Anarki). desktop-file-validate
- Allow groups with the same name as interfaces in Implements
- Add support for the COSMIC environment
**Test Plan**
- Checked a desktop file.
**Checklist**
> desktop-file-utils: Update to v0.28

- packages/h/hyprpolkitagent/package.yml
- packages/h/hyprpolkitagent/pspec_x86_64.xml
**hyprpolkitagent: Fix run dependency for hyprpolkitagent**
**Summary**
Added:
rundeps    :
- hyprland-qt-support
**Test Plan**
Discovered on new/clean hyprland install that hyprpolkitagent is missing hyprland-qt-support
For testing:
- installed hyprpolkitagent -> run dependency installed
- run hyprpolkitagent -> without any errors
**Checklist**
> fix hyprpolkitagent

- packages/f/flatpak-builder/package.yml
- packages/f/flatpak-builder/pspec_x86_64.xml
- repo_data/distribution.xml
- repo_data/distribution.xml.in
**Summary**
`bzr` depends on Python 2, so it is time for it to ride off into the sunset.
**Test Plan**
n/a
**Checklist**
> deprecate bzr

- packages/l/libogg/package.yml
- packages/l/libogg/pspec_x86_64.xml
**Summary**
Convert recipe to use cmake instead of autotools
**Test Plan**
Build `endless-sky` against this package
**Checklist**
> libogg: Use cmake instead of autotools
