getsolus/packages

packages/n/neovim/abi_symbols
packages/n/neovim/package.yml
packages/n/neovim/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/neovim/neovim/releases/tag/v0.10.1).
**Test Plan**
Run `nvim`, edit a file, save a file.
**Checklist**

neovim: Update to 0.10.1

---

packages/s/starship/package.yml
packages/s/starship/pspec_x86_64.xml

**Summary**
- Fix package description with `eopkg info starship`
**Test Plan**
Install the package and run `eopkg info starship`.
**Checklist**

starship: Fix package description and tests on builder

---

packages/l/liquid-dsp/package.yml
packages/l/liquid-dsp/pspec_x86_64.xml

**Summary**
Adds homepage url to liquid-dsp
**Test Plan**
**Checklist**

liquid-dsp: add homepage

---

packages/l/lilv/package.yml
packages/l/lilv/pspec_x86_64.xml

**Summary**
Adds homepage url to lilv
**Test Plan**
**Checklist**

lilv: add homepage

---

packages/l/lightscreen/abi_used_symbols
packages/l/lightscreen/package.yml
packages/l/lightscreen/pspec_x86_64.xml

**Summary**
Adds homepage url to lightscreen
**Test Plan**
**Checklist**

lightscreen: add homepage

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v31.0.0/CHANGELOG.md)
**Test Plan**
**Checklist**

font-iosevka-ttf: Update to 31.0.0

---

packages/n/ncdu/abi_used_symbols
packages/n/ncdu/package.yml
packages/n/ncdu/pspec_x86_64.xml

**Summary**
- Add parallel scanning flag
- Improve JSON export and import performance
- Bugfixes
- [changelog](https://dev.yorhel.nl/ncdu/changes2)
**Test Plan**
- ncdu -t 2
**Checklist**

ncdu: Update to 2.5

---

packages/py/pychromecast/package.yml
packages/py/pychromecast/pspec_x86_64.xml

**Summary**
Adds homepage to `pychromecast`
**Test Plan**
**Checklist**

pychromecast: add homepage

---

packages/l/lzop/package.yml
packages/l/lzop/pspec_x86_64.xml

**Summary**
Add homepage in package.yml.
Change build from %configure to %reconfigure
**Test Plan**
Verify homepage reference in package.yml
Build and install package.  Compress some files and un-compress the files successfully.
**Checklist**

lzop: add homepage

---

packages/l/lzo/package.yml
packages/l/lzo/pspec_x86_64.xml

**Summary**
- add `lzo` homepage to `package.yml`
**Test Plan**
- verify homepage key in `package.yml`
- build and install package, execute lzop file compressions and extractions successfully.
**Checklist**

lzo: add homepage

---

packages/l/lxappearance/package.yml
packages/l/lxappearance/pspec_x86_64.xml

**Summary**
- add homepage to `package.yml`
**Test Plan**
- build and install
- open new build of application and make successful changes
**Checklist**

lxappearance: add homepage

---

packages/l/libglu/abi_used_symbols
packages/l/libglu/abi_used_symbols32
packages/l/libglu/package.yml
packages/l/libglu/pspec_x86_64.xml

**Summary**
- Add homepage to libglu package.yml
**Test Plan**
- verify homepage link opens properly
- install package without error.
**Checklist**

libglu:  add homepage

---

packages/g/gst-python/package.yml
packages/g/gst-python/pspec_x86_64.xml
packages/g/gst-rtsp-server/package.yml
packages/g/gst-rtsp-server/pspec_x86_64.xml
packages/g/gstreamer-1.0-libav/abi_used_symbols
packages/g/gstreamer-1.0-libav/package.yml
packages/g/gstreamer-1.0-libav/pspec_x86_64.xml
packages/g/gstreamer-1.0-plugins-bad/abi_used_symbols
packages/g/gstreamer-1.0-plugins-bad/package.yml
packages/g/gstreamer-1.0-plugins-bad/pspec_x86_64.xml
packages/g/gstreamer-1.0-plugins-base/package.yml
packages/g/gstreamer-1.0-plugins-base/pspec_x86_64.xml
packages/g/gstreamer-1.0-plugins-good/package.yml
packages/g/gstreamer-1.0-plugins-good/pspec_x86_64.xml
packages/g/gstreamer-1.0/package.yml
packages/g/gstreamer-1.0/pspec_x86_64.xml
packages/g/gstreamer-editing-services/package.yml
packages/g/gstreamer-editing-services/pspec_x86_64.xml
packages/g/gstreamer-vaapi/package.yml
packages/g/gstreamer-vaapi/pspec_x86_64.xml

**Summary**
[Changelog](https://gstreamer.freedesktop.org/releases/1.24/#1.24.6)
**Test Plan**
Play a video in totem
**Checklist**

Gstreamer 1.24.6

---

packages/py/python-google-api-core/package.yml
packages/py/python-google-api-core/pspec_x86_64.xml

**Summary**
Adds homepage to `python-google-api-core`
**Test Plan**
**Checklist**

python-google-api-core: add homepage

---

packages/l/log4perl/package.yml
packages/l/log4perl/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

log4perl: add homepage

---

packages/py/python-google-auth-oauthlib/package.yml
packages/py/python-google-auth-oauthlib/pspec_x86_64.xml

**Summary**
Adds homepage to `python-google-auth-oauthlib`
**Test Plan**
**Checklist**

python-google-auth-oauthlib: add homepage

---

packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
- Mailslots reimplemented using server-side I/O
- More support for ODBC Windows drivers
- Still more user32 data structures in shared memory
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.14)
**Test Plan**
- Used `winemine`, `winecfg`, `wineconsole`, `winefile`
**Checklist**

wine: Update to 9.14

---

packages/py/python-hkdf/package.yml
packages/py/python-hkdf/pspec_x86_64.xml

**Summary**
Adds homepage to `python-hkdf`
**Test Plan**
**Checklist**

python-hkdf: add homepage

---

packages/py/python-helpdev/package.yml
packages/py/python-helpdev/pspec_x86_64.xml

**Summary**
Adds homepage to `python-helpdev`
**Test Plan**
**Checklist**

python-helpdev: add homepage

---

packages/l/lsb-release/package.yml
packages/l/lsb-release/pspec_x86_64.xml

**Summary**
- add homepage to package.yml
- update source URL - current URL was no longer valid
**Test Plan**
**Checklist**

lsb-release: add homepage & update source URL

---

packages/l/ltrace/abi_used_symbols
packages/l/ltrace/package.yml
packages/l/ltrace/pspec_x86_64.xml

- **Summary**
- Reformat description
- Update to License
**Test Plan**
- build and install
- execute various ltrace command options successfully getting trace output.
**Checklist**

ltrace: add homepage

---

packages/l/lua51/package.yml
packages/l/lua51/pspec_x86_64.xml

**lua51: add homepage**
**Summary**
Add homepage to lua 5.1
**Test Plan**
Ensure package builds
**Checklist**

lua51 : Add homepage

---

packages/l/libzen/abi_used_symbols
packages/l/libzen/package.yml
packages/l/libzen/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libzen: add homepage

---

packages/e/eza/abi_used_symbols
packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Fix breakage from time crate
**Test Plan**
List files in a directory, both with and without showing additional information.
**Checklist**

eza: Update to 0.18.24

---

packages/py/python-inflection/package.yml
packages/py/python-inflection/pspec_x86_64.xml

**Summary**
Adds homepage to `python-inflection`
**Test Plan**
**Checklist**

python-inflection: Add homepage

---

packages/t/ttyplot/abi_used_symbols
packages/t/ttyplot/package.yml
packages/t/ttyplot/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/tenox7/ttyplot/releases/tag/1.7.0)
**Test Plan**
- echo 1 2 3 | TERM=vt100 ttyplot
**Checklist**

ttyplot: Update to 1.7.0

---

packages/py/python-isodate/package.yml
packages/py/python-isodate/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-isodate: Add homepage

---

packages/s/svtplay-dl/package.yml
packages/s/svtplay-dl/pspec_x86_64.xml

**Summary**
- sr: fix support for music files via language argument
- setup: use entry point instead of scripts
**Test Plan**
- Checked version.
**Checklist**

svtplay-dl: update to 4.97.1

---

packages/py/python-libtmux/package.yml
packages/py/python-libtmux/pspec_x86_64.xml

**Summary**
- Adds `homepage` to `package.yml`
**Test Plan**
**Checklist**

python-libtmux: Add homepage

---

packages/py/python-kaptan/package.yml
packages/py/python-kaptan/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-kaptan: Add homepage

---

packages/py/python-absl-py/package.yml
packages/py/python-absl-py/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-absl-py: Add homepage

---

packages/py/python-multidict/package.yml
packages/py/python-multidict/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-multidict: Add homepage

---

packages/py/python-monotonic/package.yml
packages/py/python-monotonic/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-monotonic: Add homepage

---

packages/py/python-magic/package.yml
packages/py/python-magic/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-magic: Add homepage

---

packages/l/lmms/files/lmms.appdata.xml
packages/l/lmms/package.yml
packages/l/lmms/pspec_x86_64.xml

**Summary**
- add appstream data (adapted from flathub lmms)
**Test Plan**
ensure appstream data is install.
**Checklist**
Resolves https://github.com/getsolus/packages/issues/3381

lmms: add appstream data

---

packages/py/python-munkres/package.yml
packages/py/python-munkres/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-munkres: Add homepage

---

packages/c/cvassistant/files/io.sourceforge.cvassistant.cvassistant.metainfo.xml
packages/c/cvassistant/monitoring.yml
packages/c/cvassistant/package.yml
packages/c/cvassistant/pspec_x86_64.xml

**Summary**
- Housekeeping
**Test Plan**
- Verified the appstream metadata.
**Checklist**

cvassistant: housekeeping

---

packages/py/python-pastel/package.yml
packages/py/python-pastel/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pastel: Add homepage

---

packages/py/python-pefile/package.yml
packages/py/python-pefile/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pefile: Add homepage

---

packages/py/python-pivy/package.yml
packages/py/python-pivy/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pivy: Add homepage

---

packages/py/python-pkgconfig/package.yml
packages/py/python-pkgconfig/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pkgconfig: Add homepage

---

packages/py/python-pretend/package.yml
packages/py/python-pretend/pspec_x86_64.xml

**Summary**
- Adds `homepage` to `package.yml`
**Test Plan**
**Checklist**

python-pretend: Add homepage

---

packages/py/python-pyaes/package.yml
packages/py/python-pyaes/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pyaes: Add homepage

---

packages/py/python-pycountry/package.yml
packages/py/python-pycountry/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pycountry: Add homepage

---

packages/py/python-oauth2client/package.yml
packages/py/python-oauth2client/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-oauth2client: Add homepage

---

packages/py/python-nose/package.yml
packages/py/python-nose/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-nose: Add homepage

---

packages/p/perl-class-factory-util/monitoring.yml
packages/p/perl-class-factory-util/package.yml
packages/p/perl-class-factory-util/pspec_x86_64.xml

**Summary**
**Test Plan**
Verified that homepage is relevant and working
**Checklist**

perl-class-factory-util: Housekeeping

---

packages/p/perl-error/monitoring.yml
packages/p/perl-error/package.yml
packages/p/perl-error/pspec_x86_64.xml

**Summary**
**Test Plan**
Verified homepage loads relevant information
**Checklist**

perl-error: Housekeeping

---

packages/p/perl-extutils-config/monitoring.yml
packages/p/perl-extutils-config/package.yml
packages/p/perl-extutils-config/pspec_x86_64.xml

**Summary**
- Add a but method
- Add ExtUtils::Config::MakeMaker
**Test Plan**
Rebuild `perl-module-build-tiny` and `perl-readonly`
**Checklist**

perl-extutils-config: Update to 0.009

---

packages/py/python-pylev/package.yml
packages/py/python-pylev/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pylev: Add homepage

---

packages/py/python-pyinsane2/package.yml
packages/py/python-pyinsane2/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pyinsane2: Add homepage

---

packages/l/lv2/package.yml
packages/l/lv2/pspec_x86_64.xml

**Summary**
- Remove build dependency on cairo-gl
**Test Plan**
- Successfully build and install new package
- Execute Ardour (as a sample app) and ensure LV2 plugins are available
**Checklist**

lv2: add homepage

---

packages/l/libvorbis/abi_libs32
packages/l/libvorbis/abi_symbols32
packages/l/libvorbis/abi_used_symbols32
packages/l/libvorbis/package.yml
packages/l/libvorbis/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libvorbis: add homepage

---

packages/py/python-pyliblzma/abi_used_symbols
packages/py/python-pyliblzma/package.yml
packages/py/python-pyliblzma/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pyliblzma: Add homepage

---

packages/l/libgtksourceview4/package.yml
packages/l/libgtksourceview4/pspec_x86_64.xml

**Summary**
- Added homepage
**Test Plan**
Ensure homepage key is in pspec.xml
**Checklist**

libgtksourceview4: Housekeeping

---

packages/p/perl-module-runtime/monitoring.yml
packages/p/perl-module-runtime/package.yml
packages/p/perl-module-runtime/pspec_x86_64.xml

**Summary**
**Test Plan**
Verified homepage loads relevant information
**Checklist**

perl-module-runtime: Housekeeping

---

packages/f/freeciv/package.yml
packages/f/freeciv/pspec_x86_64.xml

**Summary**
Release notes available [here](https://freeciv.fandom.com/wiki/NEWS-3.1.2)
**Test Plan**
Played a couple of rounds
**Checklist**

freeciv: Update to 3.1.2

---

packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
- Prototype and constructor objects in MSHTML
- More support for ODBC Windows drivers
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.15)
**Test Plan**
- Used `winemine`, `winecfg`, `wineconsole`, `winefile`
**Checklist**

wine: Update to 9.15

---

packages/a/aisleriot/package.yml
packages/a/aisleriot/pspec_x86_64.xml

**Summary**
- README: Update user manual URI
**Test Plan**
- Played a game.
**Checklist**

aisleriot: update to 3.22.33

---

packages/a/alabaster/package.yml
packages/a/alabaster/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://alabaster.readthedocs.io/en/latest/changelog.html#id1).
**Test Plan**
**Checklist**

alabaster: update to 1.0.0

---

packages/py/python-orjson/package.yml
packages/py/python-orjson/pspec_x86_64.xml

**Summary**
Changes:
- Improve performance of stable Rust amd64 builds
**Test Plan**
- Ran some examples from the project's README
**Checklist**

python-orjson: Update to 3.10.7

---

packages/py/python-pyotherside/package.yml
packages/py/python-pyotherside/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pyotherside: Add homepage

---

packages/py/python-pyside2-tools/package.yml
packages/py/python-pyside2-tools/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pyside2-tools: Add homepage

---

packages/py/python-pyrfc3339/package.yml
packages/py/python-pyrfc3339/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pyrfc3339: Add homepage

---

packages/g/gparted/abi_used_libs
packages/g/gparted/abi_used_symbols
packages/g/gparted/monitoring.yml
packages/g/gparted/package.yml
packages/g/gparted/pspec_x86_64.xml

**Summary**
- Full release note can be found [here](https://sourceforge.net/projects/gparted/files/gparted/gparted-1.6.0/)
**Test Plan**
Format a blank disk and create new partition in VM
**Checklist**

gparted: Update to 1.6.0

---

packages/y/yquake2/abi_used_symbols
packages/y/yquake2/package.yml
packages/y/yquake2/pspec_x86_64.xml

**Summary**
Full changelog can be read [here](https://raw.githubusercontent.com/yquake2/yquake2/QUAKE2_8_41/CHANGELOG)
**Test Plan**
TBD
**Checklist**

yquake2: Update to 8.41

---

packages/l/libt1ha/package.yml
packages/l/libt1ha/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libt1ha: add homepage

---

packages/f/feh/files/org.finalrewind.feh.feh.metainfo.xml
packages/f/feh/package.yml
packages/f/feh/pspec_x86_64.xml

**Summary**
- Add appstreamdata
**Test Plan**
- Build app and run `appstream-builder --packages-dir=. --include-failed -v`
- Install in vm and execute `appstream-util validate /usr/share/metainfo/org.finalrewind.feh.feh.metainfo.xml`
- Ensure both produce the expected results
**Checklist**

feh: Housekeeping

---

packages/g/gufw/files/io.github.costales.gufw.metainfo.xml
packages/g/gufw/package.yml
packages/g/gufw/pspec_x86_64.xml

**Summary**
- Add appstream data
**Test Plan**
- Build and validate with appstream-builder and appstream-util validate
**Checklist**

gufw: Housekeeping

---

packages/s/sndio/abi_used_symbols
packages/s/sndio/abi_used_symbols32
packages/s/sndio/monitoring.yml
packages/s/sndio/package.yml
packages/s/sndio/pspec_x86_64.xml

**Summary**
**Test Plan**
- Checked mpd which is dependent on this.
**Checklist**

sndio: update to 1.10.0

---

packages/d/dreamchess/files/org.dreamchess.dreamchess.metainfo.xml
packages/d/dreamchess/package.yml
packages/d/dreamchess/pspec_x86_64.xml

**Summary**
**Test Plan**
- Verified the appstream metainfo
**Checklist**

dreamchess: add appstream metainfo

---

packages/d/dfarc/abi_used_symbols
packages/d/dfarc/files/org.gnu.dfarc.metainfo.xml
packages/d/dfarc/package.yml
packages/d/dfarc/pspec_x86_64.xml

**Summary**
**Test Plan**
- Verified appstream metainfo
**Checklist**

dfarc: add appstream metainfo

---

packages/l/libsigsegv/abi_symbols
packages/l/libsigsegv/monitoring.yml
packages/l/libsigsegv/package.yml
packages/l/libsigsegv/pspec_x86_64.xml

**Summary**
- Fix license
- Add `monitoring.yml`
Part of https://github.com/getsolus/packages/issues/3554
**Test Plan**
Rebuild `clisp` against this package.
**Checklist**

libsigsegv: Housekeeping

---

packages/d/dogtail/files/com.gitlab.dogtail.metainfo.xml
packages/d/dogtail/package.yml
packages/d/dogtail/pspec_x86_64.xml

**Summary**
**Test Plan**
- Verified the appstream metainfo.
**Checklist**
- Should be or-later license according to gitlab.

dogtail: add appstream metainfo

---

packages/p/perl-regexp-common/monitoring.yml
packages/p/perl-regexp-common/package.yml
packages/p/perl-regexp-common/pspec_x86_64.xml

**Summary**
Full changelog can ber read [here](https://fastapi.metacpan.org/source/ABIGAIL/Regexp-Common-2024080801/Changes)
**Test Plan**
Rebuild `biber` and `cloc` against this package
**Checklist**

perl-regexp-common: Update 2024080801

---

packages/l/libvdpau-va-gl/abi_used_symbols
packages/l/libvdpau-va-gl/package.yml
packages/l/libvdpau-va-gl/pspec_x86_64.xml

**Summary**
- Added homepage
- Organized builddeps
**Test Plan**
Ensure pspec.xml contains homepage key
**Checklist**

libvdpau-va-gl: Housekeeping

---

packages/g/gapless/package.yml
packages/g/gapless/pspec_x86_64.xml

**Summary**
- Fix initial view when no music.
- Fix Drag-drop when no music.
- Update translation: Hindi, Occitan, Persian, Brazilian Portuguese, Hungarian, Swedish, Turkish, Belarusian.
**Test Plan**
Play Tokyo by Annaland
**Checklist**

gapless: Update to 3.8.2

---

packages/py/python-pysocks/package.yml
packages/py/python-pysocks/pspec_x86_64.xml

**Summary**
Adds `homepage` key to `package.yml`
**Test Plan**
**Checklist**

python-pysocks: Add homepage

---

packages/py/python-pythondialog/package.yml
packages/py/python-pythondialog/pspec_x86_64.xml

**Summary**
Adds `homepage` key to `package.yml`
**Test Plan**
**Checklist**

python-pythondialog: Add homepage

---

packages/py/python-pyyaml-env-tag/package.yml
packages/py/python-pyyaml-env-tag/pspec_x86_64.xml

**Summary**
Adds `homepage` key to `package.yml`
**Test Plan**
**Checklist**

python-pyyaml-env-tag: Add homepage

---

packages/l/lsd/abi_used_symbols
packages/l/lsd/files/0001_240d513_use_cache_for_user_and_group_in_linux.patch
packages/l/lsd/package.yml
packages/l/lsd/pspec_x86_64.xml

**Summary**
- Rebuild using new cargo macros [#3111](https://github.com/getsolus/packages/issues/3111)
- Resolves build issue [#3306](https://github.com/getsolus/packages/issues/3306)
**Test Plan**
**Checklist**

lsd: Rebuild using cargo macros

---

packages/py/python-sane/package.yml
packages/py/python-sane/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-sane: Add homepage

---

packages/py/python-rxpy/package.yml
packages/py/python-rxpy/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-rxpy: Add homepage

---

packages/py/python-requests-oauthlib/package.yml
packages/py/python-requests-oauthlib/pspec_x86_64.xml

**Summary**
Adds `homepage `key` to `package.yml`
**Test Plan**
**Checklist**

python-requests-oauthlib: Add homepage

---

packages/l/libsrtp/package.yml
packages/l/libsrtp/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libsrtp: Add homepage

---

packages/m/mercurial/package.yml
packages/m/mercurial/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://wiki.mercurial-scm.org/Release6.8).
**Test Plan**
- Installed checked version.
**Checklist**

mercurial: Update to 6.8.1

---

packages/py/python-smartypants/package.yml
packages/py/python-smartypants/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-smartypants: Add homepage

---

packages/b/bandwhich/abi_used_symbols
packages/b/bandwhich/package.yml
packages/b/bandwhich/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/imsnif/bandwhich/blob/v0.23.0/CHANGELOG.md)
**Test Plan**
- bandwhich --interface tailscale0
**Checklist**

bandwhich: Update to 0.23.0

---

packages/c/cemu/package.yml
packages/c/cemu/pspec_x86_64.xml

**Summary**
Update cemu to the latest release.
Full changelog available [here](https://github.com/cemu-project/Cemu/compare/v2.0-91...v2.0-94)
**Test Plan**
Launch a somewhat demanding/unoptimized title and ensure things work as expected, with and without graphics packs. Ensure controllers work correctly.
**Checklist**

cemu: Update to 2.0-94

---

packages/c/cendric/abi_used_symbols
packages/c/cendric/files/ch.cendric.cendric.metainfo.xml
packages/c/cendric/package.yml
packages/c/cendric/pspec_x86_64.xml
packages/c/cool-retro-term/files/fix-screenshot.patch
packages/c/cool-retro-term/package.yml
packages/c/cool-retro-term/pspec_x86_64.xml
packages/d/dfarc/files/org.gnu.dfarc.metainfo.xml
packages/d/dfarc/package.yml
packages/d/dfarc/pspec_x86_64.xml
packages/d/dhewm3/files/dhewm3-roe.desktop
packages/d/dhewm3/files/dhewm3.desktop
packages/d/dhewm3/files/org.dhewm3.Dhewm3.metainfo.xml
packages/d/dhewm3/package.yml
packages/d/dhewm3/pspec_x86_64.xml
packages/d/diodon/files/io.github.diodon_dev.diodon.metainfo.xml
packages/d/diodon/package.yml
packages/d/diodon/pspec_x86_64.xml
packages/d/dogtail/files/com.gitlab.dogtail.metainfo.xml
packages/d/dogtail/package.yml
packages/d/dogtail/pspec_x86_64.xml
packages/d/dreamchess/files/org.dreamchess.dreamchess.metainfo.xml
packages/d/dreamchess/package.yml
packages/d/dreamchess/pspec_x86_64.xml
packages/g/gufw/files/io.github.costales.gufw.metainfo.xml
packages/g/gufw/package.yml
packages/g/gufw/pspec_x86_64.xml
packages/p/proton-vpn-gtk-app/files/com.protonvpn.www.metainfo.xml
packages/p/proton-vpn-gtk-app/package.yml
packages/p/proton-vpn-gtk-app/pspec_x86_64.xml

**Summary**
- cendric: Fix license info and name on appstream metainfo
- dfarc: Fix capitalization on appstream metainfo
- dhewm3: Housekeeping
- dreamchess: Fix capitalization on appstream metainfo
- gufw: Fix capitalization on appstream metainfo
- dogtail: Fix capitalization on appstream metainfo
- diodon: Fix capitalization on appstream metainfo
- cool-retro-term: Fix appstream metainfo screenshot
- proton-vpn-gtk-app: Fix appstream metainfo screenshot
**Test Plan**
None
**Checklist**

Various AppStream metainfo fixes

---

packages/l/libticonv/abi_symbols
packages/l/libticonv/abi_used_symbols
packages/l/libticonv/package.yml
packages/l/libticonv/pspec_x86_64.xml

**Summary**
**Test Plan**
- Successfully build and install package
- Test by installing and running TiLP
**Checklist**

libticonv: Add homepage

---

packages/l/libticables/abi_used_symbols
packages/l/libticables/package.yml
packages/l/libticables/pspec_x86_64.xml

**Summary**
**Test Plan**
- Successfully build and install package
- Test by installing and running TiLP
**Checklist**

libticables: Add homepage

---

packages/l/libtifiles/abi_used_symbols
packages/l/libtifiles/package.yml
packages/l/libtifiles/pspec_x86_64.xml

**Summary**
**Test Plan**
- Successfully build and install package
- Test by installing and running TiLP
**Checklist**

libtifiles: Add homepage

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v31.3.0/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 31.3.0

---

packages/l/libtpms/package.yml
packages/l/libtpms/pspec_x86_64.xml

**Summary**
**Test Plan**
- Successfully build and install new package
- Successfully created QEMU VMs using both TPM Emulated & Pass through options
**Checklist**

libtpms: Add homepage

---

packages/py/python-slip/package.yml
packages/py/python-slip/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-slip: Add homepage

---

packages/k/keybase/package.yml
packages/k/keybase/pspec_x86_64.xml

**Summary**
Changes:
- Chat attachments improvements
- Miscellaneous bugfixes
**Test Plan**
- Sent some chat messages
- Encrypted and decrypted a file
- Checked my wallet balance
**Checklist**

keybase: Update to 6.4.0

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- [changelog](https://tailscale.com/changelog#2024-08-22-client)
**Test Plan**
**Checklist**

tailscale: Update to 1.72.1

---

packages/x/xemu/abi_used_symbols
packages/x/xemu/files/0001-Better-follow-freedesktop-specifications.patch
packages/x/xemu/package.yml
packages/x/xemu/pspec_x86_64.xml

**Summary**
- i386: Implement EBL_CR_POWERON MSR for Xbox CPU
**Test Plan**
- Installed, started and checked version.
**Checklist**
- Patch modified since they renamed a file.

xemu: Update to 0.7.132

---

packages/w/wine/abi_symbols
packages/w/wine/abi_symbols32
packages/w/wine/abi_used_symbols
packages/w/wine/abi_used_symbols32
packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
- Initial Driver Store implementation
- Pbuffer support in the Wayland driver
- More prototype objects in MSHTML
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.16)
**Test Plan**
**Checklist**

wine: Update to 9.16

---

packages/l/libsmbios/package.yml
packages/l/libsmbios/pspec_x86_64.xml

**Summary**
**Test Plan**
- Successfully rebuild and install package
- Execute symbios-sys-info getting same results as prior to the rebuld
**Checklist**

libsmbios: add homepage

---

packages/m/mpv/package.yml
packages/m/mpv/pspec_x86_64.xml

**Summary**
- Add new summary and description.
- Resolves https://github.com/getsolus/packages/issues/3576
**Test Plan**
- Checked the pspec file.
**Checklist**

mpv: housekeeping

---

packages/p/pcsc-tools/package.yml
packages/p/pcsc-tools/pspec_x86_64.xml
packages/p/perl-pcsc/monitoring.yml
packages/p/perl-pcsc/package.yml
packages/p/perl-pcsc/pspec_x86_64.xml

**Summary**
- perl-pcsc: Update 1.4.16
- pcsc-tools: Update to 1.7.2
**Test Plan**
Run `gscriptor` and make sure it behaves normally
**Checklist**

Update pcsc-tools and perl-pcsc

---

packages/p/progress/package.yml
packages/p/progress/pspec_x86_64.xml

**Summary**
- added homepage
- updated to 0.17
**Test Plan**
Compress solus-packages into a zip and run progress
**Checklist**

progress: Update to 0.17

---

packages/l/libunibreak/package.yml
packages/l/libunibreak/pspec_x86_64.xml

**Summary**
**Test Plan**
- Successfully build and install new package
- Successfully execute and split text using[ breaktext](https://github.com/adah1972/breaktext) utility
**Checklist**

libunibreak: Add homepage

---

packages/i/i3-style/MAINTAINERS.md
packages/i/i3-style/abi_used_symbols
packages/i/i3-style/package.yml
packages/i/i3-style/pspec_x86_64.xml

**Summary**
rebuilt the package to support the new rust macros
**Summary**
added %cargo_build and cargo fetch to support the rebuild
**Test Plan**
installed using eopkg, I do not have i3 installed so cannot fully test the package
**Checklist**

i3-style:cargo macro rebuild

---

packages/s/steam/package.yml
packages/s/steam/pspec_x86_64.xml

**Summary**
Changes:
- bin_steam.sh: Optimize the case where Steam is already running, by using steam-runtime-steam-remote (if available) to forward the command-line to the running instance
- bin_steam.sh: Don't copy bootstrap.tar.xz if it already matches
- Build using updated Steam client
- Update steam-devices subproject up to 2024-05-22
- Added: Performance Designed Products Victrix Pro FS-12
- buildutil: Internal changes
**Test Plan**
Successfully launched Steam, updated it, and used it to play a game
**Checklist**

steam: Update to 1.0.0.81

---

repo_data/distribution.xml
repo_data/distribution.xml.in

**Summary**
Project was archived upstream
Resolves getsolus/packages#3066
**Test Plan**
N/A
**Checklist**
N/A

repo_data: Deprecate toluapp

---

repo_data/distribution.xml
repo_data/distribution.xml.in

**Summary**
- Resolves https://github.com/getsolus/packages/issues/2063
**Test Plan**
- Ran the script for removal. Checked the package was added.
**Checklist**

hal-flash: deprecate

---

packages/u/unrar/abi_used_symbols
packages/u/unrar/package.yml
packages/u/unrar/pspec_x86_64.xml

**Summary**
**Test Plan**
- Decompress a test rar archive
**Checklist**

unrar: Update to 7.0.9

---

packages/z/zotero/package.yml
packages/z/zotero/pspec_x86_64.xml

**Summary**
- [changelog](https://www.zotero.org/support/changelog#changes_in_703_august_26_2024)
**Test Plan**
- export bibliography file
**Checklist**

zotero: Update to 7.0.3

---

packages/n/nano-syntax-highlighting/files/0001-Fix-git-commit-colours-for-dark-terminals.patch
packages/n/nano-syntax-highlighting/package.yml
packages/n/nano-syntax-highlighting/pspec_x86_64.xml
packages/n/nano/package.yml
packages/n/nano/pspec_x86_64.xml
packages/n/nanorc/package.yml
packages/n/nanorc/pspec_x86_64.xml

**Summary**
- Add at 2022.11.02
**Test Plan**
- Checked all build.
**Checklist**

nano-syntax-highlighting: add at 2022.11.02

---

packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
**Test Plan**
- C-S-g to open cli output in pager
**Checklist**

kitty: Update to 0.36.1

---

packages/y/youtube-viewer/package.yml
packages/y/youtube-viewer/pspec_x86_64.xml

**Summary**
Release notes:
- [3.11.0](https://github.com/trizen/youtube-viewer/releases/tag/3.11.0)
- [3.11.1](https://github.com/trizen/youtube-viewer/releases/tag/3.11.1)
- [3.11.2](https://github.com/trizen/youtube-viewer/releases/tag/3.11.2)
- [3.11.3](https://github.com/trizen/youtube-viewer/releases/tag/3.11.3)
Resolves https://github.com/getsolus/packages/issues/3501
**Test Plan**
Played a bunch of YouTube videos
**Checklist**

youtube-viewer: Update to 3.11.3 and fix build

---

packages/o/openrct2/abi_used_symbols
packages/o/openrct2/package.yml
packages/o/openrct2/pspec_x86_64.xml

**Summary**
- [0.4.14](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.14)
- [0.4.13](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.13)
- [0.4.12](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.12)
- [0.4.11](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.11)
- [0.4.10](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.10)
Resolves https://github.com/getsolus/packages/issues/3732
**Test Plan**
- Play a scenario for a bit
**Checklist**

openrct2: Update to 0.4.14

---

packages/k/kitty/abi_used_symbols
packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
**Test Plan**
- kitty -v
**Checklist**

kitty: Update to 0.36.2

---

packages/p/polylith/package.yml
packages/p/polylith/pspec_x86_64.xml

**Summary**
Release notes available [here](https://github.com/polyfy/polylith/releases/tag/v0.2.21)
**Summary**
Updated to latest version, supporting newer clojure features.
**Test Plan**
Built installed eopkg and ran poly checking the version info
**Checklist**

polylith: Update to version 0.2.21

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v31.6.0/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 31.6.0

---

packages/c/clojure-tools/package.yml
packages/c/clojure-tools/pspec_x86_64.xml

**Changelog**
https://github.com/clojure/clojure/blob/master/changes.md#changes-to-clojure-in-version-1120
**Summary**
Updates to latest version of clojure language
**Test Plan**
Installed the built package and ran the command executing some code at the repl.
**Checklist**

clojure-tools: Update to 1.12.0.1479

---

packages/f/freeorion/abi_used_symbols
packages/f/freeorion/package.yml
packages/f/freeorion/pspec_x86_64.xml

**Summary**
[Changelog](https://github.com/freeorion/freeorion/releases/tag/v0.5.0.1)
**Test Plan**
Run tutorial
**Checklist**

freeorion: Update to 0.5.0.1

---

packages/h/highlight/MAINTAINERS.md
packages/h/highlight/abi_used_symbols
packages/h/highlight/monitoring.yml
packages/h/highlight/package.yml
packages/h/highlight/pspec_x86_64.xml

**Summary**
- [4.13](https://gitlab.com/saalen/highlight/-/releases/v4.13)
- [4.11](https://gitlab.com/saalen/highlight/-/releases/v4.11)
- [4.10](https://gitlab.com/saalen/highlight/-/releases/v4.10)
**Test Plan**
- Feed various source files, see formatted terminal output
**Checklist**

highlight: Update to 4.13

---

packages/w/weechat/package.yml
packages/w/weechat/pspec_x86_64.xml

**Summary**
- core, plugins: fix integer overflow in loops
**Test Plan**
**Checklist**

weechat: Update to 4.4.2

---

packages/e/eza/abi_used_symbols
packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
Changelog available[here](https://github.com/eza-community/eza/releases/tag/v0.19.2).
**Test Plan**
List files in a directory.
**Checklist**

eza: Update to 0.19.2

---

packages/u/utsushi/abi_used_libs
packages/u/utsushi/abi_used_symbols
packages/u/utsushi/files/0001-Remove-constraint-on-sane-minor-version-0.patch
packages/u/utsushi/package.yml
packages/u/utsushi/pspec_x86_64.xml

**Summary**
Resolves #3791
**Test Plan**
- Lauched the app and clicked some buttons (I don't have a scanner to test)
**Checklist**

utsushi: Fix build with sane-backends > 1.0.x

---

packages/l/libraw1394/package.yml
packages/l/libraw1394/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libraw1394: include homepage

---

packages/l/libqaccessibilityclient/abi_used_symbols
packages/l/libqaccessibilityclient/package.yml
packages/l/libqaccessibilityclient/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libqaccessibilityclient: include homepage

---

packages/l/libpgm/abi_used_symbols
packages/l/libpgm/package.yml
packages/l/libpgm/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libpgm: include homepage

---

packages/l/libkate/abi_used_symbols
packages/l/libkate/package.yml
packages/l/libkate/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libkate: include homepage

---

packages/o/onionshare-cli/monitoring.yml
packages/o/onionshare/monitoring.yml

**Summary**
Add monitoring for both onionshare packages.
May be fast-forwarded.
**Test Plan**
Not needed.
**Checklist**

onionshare: [NFC] Add monitoring.yml

---

packages/l/libglade/MAINTAINERS.md
packages/l/libglade/abi_used_symbols
packages/l/libglade/package.yml
packages/l/libglade/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libglade: include homepage

---

packages/l/libstrangle/abi_used_symbols
packages/l/libstrangle/abi_used_symbols32
packages/l/libstrangle/files/fix-compilation-gcc13.patch
packages/l/libstrangle/package.yml
packages/l/libstrangle/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**
- Added patch to make it build.

libstrangle: include homepage

---

packages/e/ecwolf/abi_used_symbols
packages/e/ecwolf/files/tmemory-const-correctness.patch
packages/e/ecwolf/package.yml
packages/e/ecwolf/pspec_x86_64.xml

**Summary**
Resolves https://github.com/getsolus/packages/issues/3586
**Test Plan**
- Executed `ecwolf --help`
- Tried to run Wolfenstein 3D shareware version (loaded, but failed)
Note: same thing happens with the current version in the repository)
**Checklist**

ecwolf: Fix build

---

packages/p/playerctl/abi_libs
packages/p/playerctl/abi_symbols
packages/p/playerctl/abi_used_symbols
packages/p/playerctl/package.yml
packages/p/playerctl/pspec_x86_64.xml

**Summary**
- add homepage
**Test Plan**
Check homepage tag is in pspec.xml
**Checklist**

playerctl: Housekeeping

---

packages/c/chocolate-doom/monitoring.yml

**Summary**
Add monitoring.yml according to https://help.getsol.us/docs/packaging/monitoring.yml/
Anitya ID: https://release-monitoring.org/project/8547/
CPE: https://cve.circl.lu/search/chocolate-doom/chocolate-doom
**Test Plan**
Not needed.
**Checklist**

chocolate-doom: [NFC] Add monitoring.yml

---

packages/z/zotero/abi_used_symbols
packages/z/zotero/package.yml
packages/z/zotero/pspec_x86_64.xml

**Summary**
- [changelog](https://www.zotero.org/support/changelog#changes_in_705_september_11_2024)
**Test Plan**
- export bib file
**Checklist**

zotero: Update to 7.0.5

---

packages/l/libssh2/package.yml
packages/l/libssh2/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libssh2: include homepage

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- [changelog](https://tailscale.com/changelog/#2024-09-12-client)
**Test Plan**
**Checklist**

tailscale: Update to 1.74.0

---

packages/l/libtorrent/abi_used_symbols
packages/l/libtorrent/package.yml
packages/l/libtorrent/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libtorrent: include homepage

---

packages/o/openpaperwork-core/monitoring.yml
packages/o/openpaperwork-gtk/monitoring.yml
packages/p/paperwork-backend/monitoring.yml
packages/p/paperwork-shell/monitoring.yml
packages/p/paperwork/monitoring.yml

**Summary**
Add monitoring for paperwork and it's related packages.
May be fast-forwarded.
**Test Plan**
Not needed.
**Checklist**

paperwork: [NFC] Add monitoring.yml

---

packages/l/libtermkey/package.yml
packages/l/libtermkey/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libtermkey: include homepage

---

packages/l/libutempter/abi_used_symbols
packages/l/libutempter/package.yml
packages/l/libutempter/pspec_x86_64.xml

**Summary**
**Test Plan**
- Installed, started guake which is dependent on this.
**Checklist**

libutempter: Update to 1.2.1

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v31.6.1/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 31.6.1

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- [changelog](https://tailscale.com/changelog#2024-09-18-client)
**Test Plan**
**Checklist**

tailscale: Update to 1.74.1

---

packages/l/libzim/package.yml
packages/l/libzim/pspec_x86_64.xml
packages/z/zim-tools/abi_used_symbols
packages/z/zim-tools/package.yml
packages/z/zim-tools/pspec_x86_64.xml

**Summary**
- Update dependencies
**Test Plan**
- zimcheck file.zim
**Checklist**

zim-tools: update to 3.5.0

---

packages/p/plata-theme/package.yml
packages/p/plata-theme/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

plata-theme: add homepage

---

packages/p/proc-maps/package.yml
packages/p/proc-maps/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

proc-maps: add homepage

---

packages/p/polyclipping/abi_used_symbols
packages/p/polyclipping/package.yml
packages/p/polyclipping/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

polyclipping: add homepage

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v31.7.0/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 31.7.0

---

packages/p/portaudio/abi_used_symbols
packages/p/portaudio/abi_used_symbols32
packages/p/portaudio/package.yml
packages/p/portaudio/pspec_x86_64.xml

**Summary**
- Include homepage
**Test Plan**
**Checklist**
- Changed version name to the one of the tagged release.

portaudio: add homepage

---

packages/py/python-snowballstemmer/package.yml
packages/py/python-snowballstemmer/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-snowballstemmer: Add homepage

---

packages/p/plplot/abi_symbols
packages/p/plplot/abi_used_libs
packages/p/plplot/abi_used_symbols
packages/p/plplot/package.yml
packages/p/plplot/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

plplot: add homepage

---

packages/py/python-socketio/package.yml
packages/py/python-socketio/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-socketio: Adds homepage

---

packages/py/python-sphinxcontrib-websupport/package.yml
packages/py/python-sphinxcontrib-websupport/pspec_x86_64.xml

**Summary**
- Changes the license to `BSD-2-Clause`
**Test Plan**
- Checked homepage was added and the license was changed
**Checklist**

python-sphinxcontrib-websupport: Add homepage

---

packages/p/polkit-qt-1/abi_used_symbols
packages/p/polkit-qt-1/package.yml
packages/p/polkit-qt-1/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

polkit-qt-1: add homepage

---

packages/py/python-stevedore/package.yml
packages/py/python-stevedore/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-stevedore: Add homepage

---

packages/py/python-stopit/package.yml
packages/py/python-stopit/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-stopit: Add homepage

---

packages/p/playmyvideos/abi_used_symbols
packages/p/playmyvideos/package.yml
packages/p/playmyvideos/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

playmyvideos: add homepage

---

packages/p/pep8/package.yml
packages/p/pep8/pspec_x86_64.xml

**Summary**
Added homepage https://pycodestyle.pycqa.org
Updated license from Expat to MIT
**Checklist**

pep8: Add homepage & update license

---

packages/py/python-tensorboard/package.yml
packages/py/python-tensorboard/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-tensorboard: Add homepage

---

packages/py/python-uritemplate/package.yml
packages/py/python-uritemplate/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-uritemplate: Add homepage

---

packages/py/python-typogrify/package.yml
packages/py/python-typogrify/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-typogrify: Add homepage

---

packages/p/pngxx/package.yml
packages/p/pngxx/pspec_x86_64.xml

**Summary**
Added homepage https://www.nongnu.org/pngpp/
**Checklist**

pngxx: Add homepage

---

packages/g/gleam/package.yml
packages/g/gleam/pspec_x86_64.xml

**Summary**
Changelog:
https://github.com/gleam-lang/gleam/blob/main/CHANGELOG.md#v151---2024-09-26
**Test Plan**
**Checklist**

gleam: Update to 1.5.1

---

packages/t/tmux/package.yml
packages/t/tmux/pspec_x86_64.xml

**Summary**
- Changelog available [here](https://raw.githubusercontent.com/tmux/tmux/3.5/CHANGES)
**Test Plan**
- Tried a tmux session
**Checklist**

tmux: Update to 3.5

---

packages/n/ncdu/abi_used_libs
packages/n/ncdu/abi_used_symbols
packages/n/ncdu/package.yml
packages/n/ncdu/pspec_x86_64.xml

**Summary**
- [changelog](https://dev.yorhel.nl/ncdu/changes2)
**Test Plan**
- ncdu
**Checklist**

ncdu: Update to 2.6

---

packages/l/languagetool/files/git.properties
packages/l/languagetool/package.yml
packages/l/languagetool/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/languagetool-org/languagetool/blob/master/languagetool-standalone/CHANGES.md#65-2024-09-27)
**Test Plan**
- M-x langtool-check
**Checklist**

languagetool: Update to 6.5

---

packages/k/kpmcore/abi_symbols
packages/k/kpmcore/files/52.diff
packages/k/kpmcore/package.yml
packages/k/kpmcore/pspec_x86_64.xml

**Summary**
https://github.com/calamares/calamares/issues/2367
**Test Plan**
Not tested
**Checklist**

kpmcore: Revert commit that broke calamares

---

packages/py/python-zope.component/package.yml
packages/py/python-zope.component/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-zope.component: Add homepage

---

packages/py/python-zope.deferredimport/package.yml
packages/py/python-zope.deferredimport/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-zope.deferredimport: Add homepage

---

packages/p/proton-vpn-gtk-app/package.yml
packages/p/proton-vpn-gtk-app/pspec_x86_64.xml

**Summary**
Changelog can be found [here](https://raw.githubusercontent.com/ProtonVPN/proton-vpn-gtk-app/refs/tags/v4.5.0/CHANGELOG.md)
**Test Plan**
Connect to a server
**Checklist**

proton-vpn-gtk-app: Update to 4.5.0

---

packages/l/lime3ds/package.yml
packages/l/lime3ds/pspec_x86_64.xml

**Summary**
Release notes
- [2118.2](https://github.com/Lime3DS/Lime3DS/releases/tag/2118.2)
- [2118.1](https://github.com/Lime3DS/Lime3DS/releases/tag/2118.1)
**Test Plan**
Play Fire Emblem: Awakening
**Checklist**

lime3ds: Update to 2118.2

---

packages/py/python-zope.proxy/package.yml
packages/py/python-zope.proxy/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-zope.proxy: Add homepage

---

packages/py/python-zope.event/package.yml
packages/py/python-zope.event/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-zope.event: Add homepage

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Relicense to EUPL-1.2
- Add `opml` file extension
- Add a regen rule
- Update just, add more formats
- Recursively walk symlinks pointing at dirs
- Add `--follow-symlinks` option
- Add autocomplete for `--follow-symlinks`
- Show directories last
**Test Plan**
List files in a directory.
**Checklist**

eza: Update to 0.20.1

---

packages/k/kraft/abi_used_symbols
packages/k/kraft/monitoring.yml
packages/k/kraft/package.yml
packages/k/kraft/pspec_x86_64.xml

**Summary**
- Abort Akonadi start if it is already broken
- Allow negative values for items in the catalog
**Test Plan**
Create a new invoice item.
**Checklist**

kraft: Update to 1.2.2

---

packages/py/python-trustme/package.yml
packages/py/python-trustme/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-trustme: Add homepage

---

SECURITY.md

**Summary**
Add a security policy.
Part of  #1738
**Test Plan**
Look at rendered version in GitHub.
**Checklist**

SECURITY: Add security policy

---

packages/e/ecwolf/files/net.maniacsvault.ecwolf.metainfo.xml
packages/e/ecwolf/package.yml
packages/e/ecwolf/pspec_x86_64.xml

**Summary**
**Test Plan**
- Verified that the appstream metainfo was correct.
**Checklist**

ecwolf: add appstream metainfo

---

packages/h/hunspell-uk/package.yml
packages/h/hunspell-uk/pspec_x86_64.xml

**Summary**
- Updates related to improvements of Ukrainian language corpus
**Test Plan**
- M-x flyspell-buffer
**Checklist**

hunspell-uk: Update to 6.5.3

---

packages/w/wine/abi_symbols
packages/w/wine/abi_used_symbols
packages/w/wine/abi_used_symbols32
packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
- Character tables updates to Unicode 16.0.0
- Better window positioning in the Wayland driver
- More support for network sessions in DirectPlay
- Support for plug&play device change notifications
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.19)
**Test Plan**
- Ran `winefile`, `winemine`, `wineconsole`, `winecfg`
**Checklist**

wine: Update to 9.19

---

packages/s/steam/package.yml
packages/s/steam/pspec_x86_64.xml

**Summary**
Changes:
- Build using updated Steam client
- Expand the bootstrap tarball:
- Add steam-runtime-check-requirements
- Add steam-runtime-identify-library-abi and its dependencies
- Add srt-logger
- Add 32-bit libcurl and its dependencies for the crash report uploader
- Add fonts required by the Steam client
- bin_steam.sh:
- Start writing to console-linux.txt as early as possible
- Try harder to create `~/.steam/steam` atomically
**Test Plan**
- Launched Steam
- Updated Steam
- Played a Steam game
**Checklist**

steam: Update to 1.0.0.82

---

packages/o/openssl/files/0001-Fix-soname-dynamic-loading.patch
packages/o/openssl/package.yml
packages/o/openssl/pspec_x86_64.xml

openssl: Fix dynamic loading of compression libraries

---

packages/py/python-pivy/abi_used_symbols
packages/py/python-pivy/package.yml
packages/py/python-pivy/pspec_x86_64.xml
packages/s/soqt/abi_used_symbols
packages/s/soqt/package.yml
packages/s/soqt/pspec_x86_64.xml

**Summary**
- Link build artifacts to Coin v4.0.2
- Update CI workflow and build matrix
- Fixed numerous typos found with codespell
**Test Plan**
- Checked it installed correctly.
**Checklist**

soqt: update to 1.6.2

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Bring help text in line with available flags
- Do not print parent filename with `--absolute=on`
**Test Plan**
List files in folders in a directory.
**Checklist**

eza: Update to 0.20.2

---

packages/d/distrobox/package.yml
packages/d/distrobox/pspec_x86_64.xml

**Summary**
[changelog](https://github.com/89luca89/distrobox/releases/tag/1.8.0)
**Test Plan**
Install update and run existing containers
**Checklist**

distrobox: Update to 1.8.0

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v31.9.1/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 31.9.1

---

packages/v/visidata/package.yml
packages/v/visidata/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/saulpw/visidata/releases/tag/v3.1.1)
**Test Plan**
- search, filter out and rows
**Checklist**

visidata: Update to 3.1.1

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- [changelog](https://tailscale.com/changelog#2024-10-10-client)
**Test Plan**
**Checklist**

tailscale: Update to 1.76.0

---

packages/f/fio/abi_symbols
packages/f/fio/abi_used_symbols
packages/f/fio/package.yml
packages/f/fio/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/axboe/fio/compare/fio-3.37...fio-3.38)
**Test Plan**
- simulate io load
**Checklist**

fio: Update to 3.38

---

packages/s/starship/package.yml
packages/s/starship/pspec_x86_64.xml

**Summary**
- Revert skip unnecessary indirection in starship init fish
**Test Plan**
Launch a new shell session.
**Checklist**

starship: Update to 1.21.1

---

packages/s/streamlink/MAINTAINERS.md
packages/s/streamlink/monitoring.yml
packages/s/streamlink/package.yml
packages/s/streamlink/pspec_x86_64.xml

**Summary**
[Changelog](https://github.com/streamlink/streamlink/blob/6.11.0/CHANGELOG.md#streamlink-6110-2024-10-01)
Resolves #4056.
**Packaging Changes**
- Remove myself as maintainer
- Add monitoring info
- Enable testsuite
**Test Plan**
- Play a twitch stream in celluloid
**Checklist**

streamlink: Update to 6.11.0

---

packages/l/libuv/abi_symbols
packages/l/libuv/abi_used_symbols
packages/l/libuv/package.yml
packages/l/libuv/pspec_x86_64.xml
packages/m/msgpack/abi_symbols
packages/m/msgpack/monitoring.yml
packages/m/msgpack/package.yml
packages/m/msgpack/pspec_x86_64.xml
packages/n/neovim/abi_symbols
packages/n/neovim/abi_used_libs
packages/n/neovim/abi_used_symbols
packages/n/neovim/package.yml
packages/n/neovim/pspec_x86_64.xml

**Summary**
- **libuv: Update to 1.49.0**
- **msgpack: Update to 6.1.0**
- **neovim: Update to 0.10.2**
**Test Plan**
Edit a file with Neovim.
**Checklist**

neovim update

---

packages/z/zotero/package.yml
packages/z/zotero/pspec_x86_64.xml

**Summary**
- [changelog](https://www.zotero.org/support/changelog)
**Test Plan**
**Checklist**

zotero: Update to 7.0.8

---

packages/py/python-qtpy/monitoring.yml
packages/py/python-qtpy/package.yml
packages/py/python-qtpy/pspec_x86_64.xml

**Summary**
This updates the description to use the current upstream one so it mentions Qt6 capabilities (and removes mentions of Qt4)
**Test Plan**
Looked at the new description, I guess
**Checklist**

python-qtpy: Update description and add monitoring.yml

---

packages/c/copyq/abi_symbols
packages/c/copyq/abi_used_symbols
packages/c/copyq/package.yml
packages/c/copyq/pspec_x86_64.xml

**Summary**
- Full changelog [here](https://github.com/hluk/CopyQ/releases/tag/v9.1.0)
**Test Plan**
- Launch `copyq`, copy things into the clipboard, check them in the app.
**Checklist**

copyq: Update to 9.1.0

---

packages/e/eopkg/README.md

**Summary**
Add maintainer notes for eopkg and ypkg rebuilds.

eopkg: Create README.md that mentions when to rebuild ypkg

---

packages/o/onedrive-gui/package.yml
packages/o/onedrive-gui/pspec_x86_64.xml

**Summary**
Changes:
- Add a scrollbar on sync option page for better compatibility with small screens
- Show the version of OneDriveGUI in logs and in main window title
- Main window can now resized freely for better compatibility with small screens, allow corner snapping, etc.
- Add scrollbar in GUI Settings window
- Minor layout changes in the profile settings
**Test Plan**
Synced my onedrive folder
**Checklist**

onedrive-gui: Update to v1.1.1

---

packages/t/thunar/abi_libs
packages/t/thunar/abi_symbols
packages/t/thunar/abi_used_libs
packages/t/thunar/abi_used_symbols
packages/t/thunar/package.yml
packages/t/thunar/pspec_x86_64.xml

**Summary**
- Build the trash plugin for XFCE4 panel
Fixes https://github.com/getsolus/packages/issues/4006
**Test Plan**
Add the trash plugin to a panel and click it.
**Checklist**

thunar: Build the trash plugin for XFCE4 panel

---

packages/v/vala/package.yml
packages/v/vala/pspec_x86_64.xml

**Summary**
- Add new homepage
**Test Plan**
- Checked homepage was replaced.
**Checklist**

vala: add new homepage

---

packages/c/conky/package.yml
packages/c/conky/pspec_x86_64.xml

**Summary**
- Removed toluapp-devel as dependency
- Part of https://github.com/getsolus/packages/issues/4143
**Test Plan**
- Started it and checked the default configuration.
**Checklist**

conky: fix dependencies

---

.github/ISSUE_TEMPLATE/report-packaging-problems.yml

**Summary**
Add template for people to report problems building a package, or with the packaging of an application
**Test Plan**
Linited the yaml file

Add template for reporting problems with packages

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Ensure nested tree parts align under item name
**Test Plan**
**Checklist**

eza: Update to v0.20.5

---

packages/l/libplatform/package.yml
packages/l/libplatform/pspec_x86_64.xml

**Summary**
- Add homepage, fix license
- Remove static libs
**Test Plan**
- libcec builds
**Checklist**

libplatform: Packaging refresh

---

packages/m/mu/abi_used_symbols
packages/m/mu/package.yml
packages/m/mu/pspec_x86_64.xml

**Summary**
- many documentation fixes
- fix some mu4e-compose-captured-message corner case
- mu4e: fix 'user-agent' field
**Test Plan**
- search and view message
**Checklist**

mu: Update to 1.12.7

---

packages/s/syncthing/package.yml
packages/s/syncthing/pspec_x86_64.xml

**Summary**
Bugfixes & enhancements
**Test Plan**
- Restart Syncthing-GTK, use it to restart syncthing, verify all folders sync
**Checklist**

syncthing: Update to v1.28.0

---

packages/g/ghc/package.yml
packages/g/ghc/pspec_x86_64.xml

**Summary**
- Fix dependencies
- Part of https://github.com/getsolus/packages/issues/4143
**Test Plan**
**Checklist**

ghc: fix dependencies

---

packages/m/mate-menu/package.yml
packages/m/mate-menu/pspec_x86_64.xml

**Summary**
- Add homepage
**Test Plan**
**Checklist**

mate-menu: add homepage

---

packages/m/mate-netbook/package.yml
packages/m/mate-netbook/pspec_x86_64.xml

**Summary**
- Add homepage
**Test Plan**
**Checklist**

mate-netbook: add homepage

---

packages/m/mate-icon-theme-faenza/package.yml
packages/m/mate-icon-theme-faenza/pspec_x86_64.xml

**Summary**
- Add homepage
**Test Plan**
**Checklist**

mate-icon-theme-faenza: add homepage

---

packages/m/mate-dock-applet/package.yml
packages/m/mate-dock-applet/pspec_x86_64.xml

**Summary**
- Add homepage
**Test Plan**
**Checklist**

mate-dock-applet: add homepage

---

packages/z/zotero/package.yml
packages/z/zotero/pspec_x86_64.xml

**Summary**
- Reader: Added “Search Outline” feature in sidebar
- Reader: Don't switch to Annotations tab when clicking annotation with sidebar opened to another tab
- Added View → Columns and View → Sort By to all windows
- Added Move Column Left menu option in View → Columns as alternative to drag-and-drop column reordering
- Match annotation text and comments in All Fields & Tags quick-search mode rather than Everything mode
- bugfixes
- [changelog](https://www.zotero.org/support/changelog#changes_in_709_october_30_2024)
**Test Plan**
**Checklist**

zotero: Update to 7.0.9

---

packages/s/sweethome3d/files/sweethome3d.sh
packages/s/sweethome3d/package.yml
packages/s/sweethome3d/pspec_x86_64.xml

**Summary**
- Removed arch comment
**Test Plan**
- Checked it still launched.
**Checklist**

sweethome3d: housekeeping

---

packages/w/weechat/package.yml
packages/w/weechat/pspec_x86_64.xml

**Summary**
- irc: fix crash on /list buffer when a filter is set
- core: always send the signal "buffer_switch", even when the buffer is opening
**Test Plan**
**Checklist**

weechat: Update to v4.4.3

---

packages/b/brasero/abi_used_symbols
packages/b/brasero/files/fix-build-gcc14.patch
packages/b/brasero/package.yml
packages/b/brasero/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**
- Added patch to make it build.
- I used 3850 and 4063 when building this.

brasero: change homepage

---

packages/d/dconf/MAINTAINERS.md
packages/d/dconf/abi_used_symbols
packages/d/dconf/abi_used_symbols32
packages/d/dconf/package.yml
packages/d/dconf/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**
- Removed inactive maintainer.

dconf: change homepage

---

packages/f/freeimage/monitoring.yml
packages/g/gedit/monitoring.yml
packages/l/libical/monitoring.yml
packages/l/libwebkit-gtk/monitoring.yml
packages/l/libwebkit-gtk41/monitoring.yml
packages/l/libwebkit-gtk6/monitoring.yml
packages/m/msgpack/monitoring.yml
packages/p/perl-gtk2-appindicator/monitoring.yml
packages/s/sdl2-image/monitoring.yml
packages/z/zynaddsubfx/monitoring.yml

**Summary**
This fixes all the instances of malformed monitoring.yml files. Discovered by running the Serpent OS [ent tool](https://github.com/serpent-os/ent)
**Test Plan**
Succesfully ran `ent check updates` on the whole packages folder
**Checklist**
- [N/A] Package was built and tested against unstable

repo-wide: Fix malformed monitoring.yml files

---

packages/e/easytag/monitoring.yml
packages/e/easytag/package.yml
packages/e/easytag/pspec_x86_64.xml

**Summary**
- change homepage
- add monitoring.yml
**Test Plan**
**Checklist**

easytag: change homepage, add monitoring

---

packages/e/eog-plugins/package.yml
packages/e/eog-plugins/pspec_x86_64.xml
packages/e/eog/package.yml
packages/e/eog/pspec_x86_64.xml

**Summary**
- change homepage for eog
- change homepage for eog-plugins
**Test Plan**
- Checked homepages were added
**Checklist**

eog: change homepage

---

packages/l/lf/MAINTAINERS.md
packages/l/lf/monitoring.yml
packages/l/lf/package.yml
packages/l/lf/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/gokcehan/lf/releases/tag/r33)
**Test Plan**
- Browsed around some folders
**Checklist**

lf: Update to v33

---

packages/p/puzzles/monitoring.yml
packages/p/puzzles/package.yml
packages/p/puzzles/pspec_x86_64.xml

**Summary**
Commit log available [here](https://git.tartarus.org/?p=simon/puzzles.git;a=shortlog)
**Test Plan**
Played a bunch of different puzzles
**Checklist**

puzzles: Update to v20241021 and add monitoring.yml

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v32.0.1/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 32.0.1

---

packages/d/deja-dup/abi_used_symbols
packages/d/deja-dup/monitoring.yml
packages/d/deja-dup/package.yml
packages/d/deja-dup/pspec_x86_64.xml

**Summary**
**Test Plan**
- Checked homepage was changed
**Checklist**

deja-dup: change homepage

---

packages/l/libresprite/monitoring.yml
packages/l/libresprite/package.yml
packages/l/libresprite/pspec_x86_64.xml

**Summary**
- Note down any known issues
**Test Plan**
- export png to sprite sheet
**Checklist**

libresprite: Add monitoring.yml

---

packages/i/i3lock/abi_used_symbols
packages/i/i3lock/monitoring.yml
packages/i/i3lock/package.yml
packages/i/i3lock/pspec_x86_64.xml

**Summary**
- unlock indicator: display current keyboard layout when user types password (with --show-keyboard-layout flag).
- Resolves https://github.com/getsolus/packages/issues/4239
**Test Plan**
- Locked and unlocked my computer.
**Checklist**

i3lock: Update to v2.15

---

packages/d/devhelp/MAINTAINERS.md
packages/d/devhelp/abi_used_symbols
packages/d/devhelp/package.yml
packages/d/devhelp/pspec_x86_64.xml

**Summary**
- Fix license and homepage.
**Test Plan**
- Checked license and homepage was correct.
**Checklist**

devhelp: housekeeping

---

packages/e/evolution-ews/package.yml
packages/e/evolution-ews/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

evolution-ews: change homepage

---

packages/f/font-firago/files/firago.metainfo.xml
packages/f/font-firago/monitoring.yml
packages/f/font-firago/package.yml
packages/f/font-firago/pspec_x86_64.xml

**Summary**
- Only ship .otf files
- Add appstream metainfo (Part of getsolus/packages#449)
**Test Plan**
Run `appstream-builder --packages-dir=. --include-failed -v `
**Checklist**

font-firago: Housekeeping

---

packages/f/file-roller/package.yml
packages/f/file-roller/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

file-roller: change homepage

---

packages/f/folks/MAINTAINERS.md
packages/f/folks/package.yml
packages/f/folks/pspec_x86_64.xml

**Summary**
- Remove old maintainer
**Test Plan**
**Checklist**

folks: housekeeping

---

packages/g/ghex/package.yml
packages/g/ghex/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

ghex: change homepage

---

SECURITY.md

**Summary**
Adjust according to the [Style Guide](https://help.getsol.us/docs/user/contributing/style/):
- No Latin abbreviations (removed the term altogether since it seemed redundant)
- Sentence case for headings
Remove the repetition in one of the sentences.

Fix minor SECURITY.md style issues

---

packages/u/unrar/files/0001-Fix-amateur-hour-shit.patch
packages/u/unrar/monitoring.yml
packages/u/unrar/package.yml
packages/u/unrar/pspec_x86_64.xml

**Summary**
- No changelog provided
**Test Plan**
- Extract a test rar archive
**Checklist**

unrar: Update to v7.1.1

---

.github/ISSUE_TEMPLATE/request-package-deprecation.yml

Test new label

---

packages/m/mixxx/abi_used_symbols
packages/m/mixxx/package.yml
packages/m/mixxx/pspec_x86_64.xml

**Summary**
- Changelog available [here](https://github.com/mixxxdj/mixxx/blob/2.4.1/CHANGELOG.md)
Resolves https://github.com/getsolus/packages/issues/4303
**Test Plan**
- Play a song
**Checklist**

mixxx: Update to v2.4.1

---

packages/l/lite-xl/monitoring.yml
packages/l/lite-xl/package.yml
packages/l/lite-xl/pspec_x86_64.xml

**Summary**
* add monitoring.yml (Part of https://github.com/getsolus/packages/issues/4121)
**Checklist**

lite-xl: Housekeeping

---

packages/f/firejail/files/0001-Support-a-stateless-configuration.patch
packages/f/firejail/package.yml
packages/f/firejail/pspec_x86_64.xml

**Summary**
Fixes https://github.com/getsolus/packages/issues/4215 and one other config issue I encountered during testing
**Test Plan**
Launched some AppImages and regular apps using `firejail`
**Checklist**

firejail: Fix stateless configuration

---

packages/z/z3/monitoring.yml
packages/z/zam-plugins/monitoring.yml
packages/z/zanshin/monitoring.yml
packages/z/zbar/monitoring.yml
packages/z/zelda-roth-se/monitoring.yml
packages/z/zenity/monitoring.yml
packages/z/zfp/monitoring.yml
packages/z/zig/monitoring.yml
packages/z/zim-tools/monitoring.yml
packages/z/zimg/monitoring.yml
packages/z/zinnia/monitoring.yml
packages/z/zip/monitoring.yml
packages/z/zita-convolver/monitoring.yml
packages/z/zita-resampler/monitoring.yml
packages/z/zix/monitoring.yml
packages/z/zmusic/monitoring.yml
packages/z/zopfli/monitoring.yml
packages/z/zotero/monitoring.yml
packages/z/zpaq/monitoring.yml
packages/z/zram-generator/monitoring.yml
packages/z/zsdx/monitoring.yml
packages/z/zsh-autosuggestions/monitoring.yml
packages/z/zsh-syntax-highlighting/monitoring.yml
packages/z/zsxd/monitoring.yml
packages/z/zsync/monitoring.yml
packages/z/zuki-themes/monitoring.yml
packages/z/zuluCrypt/monitoring.yml
packages/z/zxing-cpp/monitoring.yml
packages/z/zziplib/monitoring.yml

**Summary**
Add monitoring.yml
**Test Plan**
**Checklist**
- [n/a] Package was built and tested against unstable

[NFC] repo-wide: Add monitoring.yml

---

packages/t/tailscale/monitoring.yml
packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- [changelog](https://tailscale.com/changelog#2024-11-08)
**Test Plan**
**Checklist**

tailscale: Update to 1.76.6

---

packages/t/totem/package.yml
packages/t/totem/pspec_x86_64.xml

**Summary**
- Change homepage (Part of getsolus/packages#4116)
**Test Plan**
Veriry homepage is changed
**Checklist**

totem: Change homepage

---

packages/v/vinagre/abi_used_symbols
packages/v/vinagre/files/vinagre-appdata-fixes.patch
packages/v/vinagre/files/vinagre-c99.patch
packages/v/vinagre/files/vinagre-incompatible-pointer.patch
packages/v/vinagre/files/vinagre-infinite-loop.patch
packages/v/vinagre/monitoring.yml
packages/v/vinagre/package.yml
packages/v/vinagre/pspec_x86_64.xml

**Summary**
- Fix build
- Change homepage (Part of getsolus/packages#4116)
**Test Plan**
Launch the app
**Checklist**

vinagre: Fix build and housekeeping

---

packages/e/exercism-cli/monitoring.yml
packages/e/exercism-cli/package.yml
packages/e/exercism-cli/pspec_x86_64.xml

**Summary**
- feat: add uiua test command
**Test Plan**
- Run the `configure` command, see proper setup
**Checklist**

exercism-cli: Update to v3.5.4

---

packages/t/tetrs/files/Cargo.lock
packages/t/tetrs/package.yml
packages/t/tetrs/pspec_x86_64.xml

**Summary**
- "Level" terminology has been changed to "Gravity" to accurately describe its purpose.
-  A gravity level of 0 specially denotes no gravity.
- Initial Hold System and Initial Rotation System implemented.
- Ocular RS: Added special 180° rotations (notably S/Z, L/J).
- Experimental tetromino color scheme added.
- (Semi-hidden: locked tiles can use a different color scheme, but this must be manually set in the config file.)
- More tweaks and such.
**Test Plan**
- Played a game.
**Checklist**

tetrs: Update to v0.2.4

---

packages/g/gpxsee/abi_used_symbols
packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- New Mapsforge (OpenAndroMaps) render theme.
**Test Plan**
- open map, zoom and pan
**Checklist**

gpxsee: Update to 13.28

---

packages/f/font-iosevka-ttf/monitoring.yml
packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v32.1.0/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 32.1.0

---

packages/m/mullvad/package.yml
packages/m/mullvad/pspec_x86_64.xml

**Summary**
- Update package to install the icon
**Test Plan**
- Logout of system and search for mullvad in app launcher
**Checklist**

mullvad: Install icon

---

packages/l/libchamplain/abi_used_symbols
packages/l/libchamplain/monitoring.yml
packages/l/libchamplain/package.yml
packages/l/libchamplain/pspec_x86_64.xml

**Summary**
- Changed homepage and added monitoring file
**Test Plan**
**Checklist**

libchamplain: housekeeping

---

packages/s/solaar/monitoring.yml
packages/s/solaar/package.yml
packages/s/solaar/pspec_x86_64.xml

**Summary**
- Update package to add libayatana-appindicator rundep
- add monitoring.yml
- resolves https://github.com/getsolus/packages/issues/4232
**Test Plan**
Install solaar. Verify indicator is present. 
**Checklist**

solaar: Install missing dependency

---

packages/l/libgdata/MAINTAINERS.md
packages/l/libgdata/abi_used_symbols
packages/l/libgdata/monitoring.yml
packages/l/libgdata/package.yml
packages/l/libgdata/pspec_x86_64.xml

**Summary**
- Fixed license and homepage
**Test Plan**
- Checked what I changed.
**Checklist**

libgdata: housekeeping

---

packages/r/rebar3/package.yml
packages/r/rebar3/pspec_x86_64.xml

**Summary**
Changelog: https://github.com/erlang/rebar3/releases/tag/3.24.0
**Test Plan**
* Created new project with `new` command.
* Compiled new project.
* Compiled existing project.
**Checklist**

rebar3: Update to v3.24.0

---

packages/g/gleam/abi_used_symbols
packages/g/gleam/package.yml
packages/g/gleam/pspec_x86_64.xml

**Summary**
v1.6.1 Changelog: https://github.com/gleam-lang/gleam/releases/tag/v1.6.1
v1.6.0 Changelog (article): https://gleam.run/news/context-aware-compilation/
**Test Plan**
**Checklist**

gleam: Update to v1.6.1

---

packages/l/libgtksourceview2/package.yml
packages/l/libgtksourceview2/pspec_x86_64.xml

**Summary**
- Change homepage and license
**Test Plan**
- Checked what I changed.
**Checklist**
- Nothing on release monitoring matches this version so added no monitoring file.

libgtksourceview2: housekeeping

---

packages/l/libgxps/MAINTAINERS.md
packages/l/libgxps/abi_used_symbols
packages/l/libgxps/package.yml
packages/l/libgxps/pspec_x86_64.xml

**Summary**
- Change homepage, fix maintainer
**Test Plan**
- Checked changes.
**Checklist**

libgxps: housekeeping

---

packages/l/lollypop/package.yml
packages/l/lollypop/pspec_x86_64.xml

**Summary**
- Fix an issue on mobile devices.
**Test Plan**
- Checked it started.
**Checklist**

lollypop: Update to v1.4.40

---

packages/l/libgit2-glib/package.yml
packages/l/libgit2-glib/pspec_x86_64.xml

**Summary**
**Test Plan**
- Checked it was changed.
**Checklist**

libgit2-glib: housekeeping

---

packages/l/libgweather/MAINTAINERS.md
packages/l/libgweather/package.yml
packages/l/libgweather/pspec_x86_64.xml

**Summary**
**Test Plan**
- Checked all was changed.
**Checklist**

libgweather: housekeeping

---

packages/j/just/MAINTAINERS.md
packages/j/just/monitoring.yml
packages/j/just/package.yml
packages/j/just/pspec_x86_64.xml

**Summary**
- Release notes available [here](https://github.com/casey/just/releases/tag/1.37.0)
**Test Plan**
- Run some test commands from a test `justfile`
**Checklist**

just: Update to v1.37.0

---

packages/f/font-ubuntu-ttf/monitoring.yml
packages/f/font-ubuntu-ttf/package.yml
packages/f/font-ubuntu-ttf/pspec_x86_64.xml

**Summary**
- Use correct spdx identifier
- add monitoring.yml
**Test Plan**
rebuild and ensure the updated license is in pspec
**Checklist**

font-ubuntu-ttf: Fix License

---

packages/l/libshumate/package.yml
packages/l/libshumate/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libshumate: housekeeping

---

packages/l/libsecret/MAINTAINERS.md
packages/l/libsecret/abi_used_symbols
packages/l/libsecret/package.yml
packages/l/libsecret/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libsecret: housekeeping

---

packages/l/libpeas-2/package.yml
packages/l/libpeas-2/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libpeas-2: housekeeping

---

packages/l/lightsoff/MAINTAINERS.md
packages/l/lightsoff/monitoring.yml
packages/l/lightsoff/package.yml
packages/l/lightsoff/pspec_x86_64.xml

**Summary**
* Updated translations
**Test Plan**
- Played a game.
**Checklist**

lightsoff: Update to 46.0

---

packages/l/libpeas/package.yml
packages/l/libpeas/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libpeas: housekeeping

---

packages/l/libgudev/MAINTAINERS.md
packages/l/libgudev/abi_used_symbols
packages/l/libgudev/abi_used_symbols32
packages/l/libgudev/monitoring.yml
packages/l/libgudev/package.yml
packages/l/libgudev/pspec_x86_64.xml

**Summary**
- Change homepage and fix maintainer
**Test Plan**
- Checked changes.
**Checklist**

libgudev: housekeeping

---

.github/pull_request_template.md

**Summary**
This adds an item to the checklist prompting maintainers to let us know if they think the change should be mentioned in the sync notes. As suggested by @ReillyBrogan in matrix.
**Test Plan**
N/A, this is a change to github configuration.
**Checklist**

Add sync notes checkbox to PR template

---

packages/p/phodav/abi_used_symbols
packages/p/phodav/monitoring.yml
packages/p/phodav/package.yml
packages/p/phodav/pspec_x86_64.xml

**Summary**
- Change homepage (Part of getsolus/packages#4116)
- Fix monitoring.yml
**Test Plan**
Make sure change is applied
**Checklist**

phodav: Housekeeping

---

packages/q/qtractor/abi_used_symbols
packages/q/qtractor/package.yml
packages/q/qtractor/pspec_x86_64.xml

**Summary**
Full changelog can be found [here](https://sourceforge.net/p/qtractor/code/ci/v1.4.0/tree/ChangeLog)
Resolves getsolus/packages#4393
**Test Plan**
Launch the app
**Checklist**

qtractor: Update to v1.4.0

---

packages/l/libsignal-protocol-c/MAINTAINERS.md
packages/py/python-aiohttp/MAINTAINERS.md
packages/py/python-aiosignal/MAINTAINERS.md
packages/py/python-expandvars/MAINTAINERS.md
packages/py/python-frozenlist/MAINTAINERS.md
packages/py/python-proton-core/MAINTAINERS.md
packages/py/python-proton-keyring-linux/MAINTAINERS.md
packages/py/python-proton-vpn-core-api/MAINTAINERS.md
packages/py/python-proton-vpn-network-manager/MAINTAINERS.md
packages/py/python-yarl/MAINTAINERS.md

**Summary**
Add MAINTAINERS.md files to packages I maintained
**Test Plan**
n/a
**Checklist**

[NFC] repo-wide: Add MAINTAINERS.md files

---

packages/f/freecell-solver/abi_used_symbols
packages/f/freecell-solver/monitoring.yml
packages/f/freecell-solver/package.yml
packages/f/freecell-solver/pspec_x86_64.xml

**Summary**
Changes:
- Avoid packaging `/.tidyall.d`
- Renames to "global_instance" and clean-ups
- Add experimental functions in FC_SOLVE_INSTANCE_PARAMS_QUERYING
- Fewer compile-time / lint-time warnings
- Convert some regular expressions from `+\d+` to `+[0-9]+`
**Test Plan**
Built and played Freecell in `kpat`
**Checklist**

freecell-solver: Update to v6.12.0 and add monitoring.yml

---

packages/a/aisleriot/package.yml
packages/a/aisleriot/pspec_x86_64.xml

**Summary**
Full commit log available [here](https://gitlab.gnome.org/GNOME/aisleriot/-/compare/3.22.33...3.22.34)
**Test Plan**
Played a game of Solitaire
**Checklist**

aisleriot: Update to v3.22.34

---

packages/m/mixxx/abi_used_symbols
packages/m/mixxx/package.yml
packages/m/mixxx/pspec_x86_64.xml

**Summary**
Full changelog can be found [here](https://raw.githubusercontent.com/mixxxdj/mixxx/refs/tags/2.4.2/CHANGELOG.md)
**Test Plan**
Launch the app
**Checklist**

mixxx: Update to v2.4.2

---

packages/w/warzone2100/package.yml
packages/w/warzone2100/pspec_x86_64.xml

**Summary**
- Numerous fixes for crashes, cleanup issues, and memory leaks
- Fix: Handling certain network socket disconnects and error states
- Full changelog [here](https://raw.githubusercontent.com/Warzone2100/warzone2100/4.5.5/ChangeLog)
**Test Plan**
- Play the tutorial for a while
**Checklist**

warzone2100: Update to v4.5.5

---

packages/f/fluidsynth/abi_symbols
packages/f/fluidsynth/package.yml
packages/f/fluidsynth/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/FluidSynth/fluidsynth/releases/tag/v2.4.0).
**Test Plan**
- Loaded VLC with this installed.
- Resolves https://github.com/getsolus/packages/issues/4364
**Checklist**

fluidsynth: Update to v2.4.0

---

packages/l/lite-xl/package.yml
packages/l/lite-xl/pspec_x86_64.xml

**Summary**
- QOL update
- [changelog](https://github.com/lite-xl/lite-xl/releases/tag/v2.1.6)
**Test Plan**
open a project in lite-xl
**Checklist**

lite-xl: Update to v2.1.6

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v32.2.0/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 32.2.0

---

packages/g/gapless/package.yml
packages/g/gapless/pspec_x86_64.xml

**Summary**
- Optimize scrolling to current item at startup.
- Update translation: Swedish, Finnish, Occitan, Turkish.
**Test Plan**
Play "Talking to Myself by Linkin Park"
**Checklist**

gapless: Update to v4.3

---

packages/g/gst-python/package.yml
packages/g/gst-python/pspec_x86_64.xml
packages/g/gst-rtsp-server/package.yml
packages/g/gst-rtsp-server/pspec_x86_64.xml
packages/g/gstreamer-1.0-libav/abi_used_symbols
packages/g/gstreamer-1.0-libav/package.yml
packages/g/gstreamer-1.0-libav/pspec_x86_64.xml
packages/g/gstreamer-1.0-plugins-bad/abi_symbols
packages/g/gstreamer-1.0-plugins-bad/package.yml
packages/g/gstreamer-1.0-plugins-bad/pspec_x86_64.xml
packages/g/gstreamer-1.0-plugins-base/abi_used_symbols
packages/g/gstreamer-1.0-plugins-base/abi_used_symbols32
packages/g/gstreamer-1.0-plugins-base/package.yml
packages/g/gstreamer-1.0-plugins-base/pspec_x86_64.xml
packages/g/gstreamer-1.0-plugins-good/abi_used_symbols
packages/g/gstreamer-1.0-plugins-good/package.yml
packages/g/gstreamer-1.0-plugins-good/pspec_x86_64.xml
packages/g/gstreamer-1.0-plugins-ugly/package.yml
packages/g/gstreamer-1.0-plugins-ugly/pspec_x86_64.xml
packages/g/gstreamer-1.0/package.yml
packages/g/gstreamer-1.0/pspec_x86_64.xml
packages/g/gstreamer-editing-services/package.yml
packages/g/gstreamer-editing-services/pspec_x86_64.xml
packages/g/gstreamer-vaapi/package.yml
packages/g/gstreamer-vaapi/pspec_x86_64.xml

Release notes:
- [1.24.10](https://gstreamer.freedesktop.org/releases/1.24/#1.24.10)

gstreamer-1.0: Update to v1.24.10

---

packages/m/melonds/abi_used_symbols
packages/m/melonds/files/dont-fix-libslirp-interface.patch
packages/m/melonds/files/fix-build-with-gcc14.patch
packages/m/melonds/package.yml
packages/m/melonds/pspec_x86_64.xml

**Summary**
Fix build
**Test Plan**
Launch the app and play some games
**Checklist**

melonds: Fix build

---

packages/w/warpinator/package.yml
packages/w/warpinator/pspec_x86_64.xml

**Summary**
Update translations
**Test Plan**
Launch the app, connect to phone, and transfer files
**Checklist**

warpinator: Update to v1.8.7

---

packages/a/appstream-data/package.yml
packages/a/appstream-data/pspec_x86_64.xml

**Summary**
Update Appstream data
**Test Plan**
- Build Appstream data from this PR
- Open Discover, see that it doesn't break
**Checklist**

appstream-data: Update to v52

---

packages/z/zotero/package.yml
packages/z/zotero/pspec_x86_64.xml

**Summary**
- [changelog](https://www.zotero.org/support/changelog#changes_in_7011_december_6_2024)
**Test Plan**
**Checklist**

zotero: Update to 7.0.11

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- [changelog](https://tailscale.com/changelog#2024-12-05-client)
**Test Plan**
**Checklist**

tailscale: Update to 1.78.1

---

packages/l/lite-xl/package.yml
packages/l/lite-xl/pspec_x86_64.xml

**Summary**
- bug fix update
- [changelog](https://github.com/lite-xl/lite-xl/blob/v2.1.7/changelog.md)
**Test Plan**
- Open textfile in lite-xl
**Checklist**

lite-xl: Update to v2.1.7

---

packages/a/atril/monitoring.yml
packages/a/atril/package.yml
packages/a/atril/pspec_x86_64.xml
packages/m/mate-applets/abi_used_symbols
packages/m/mate-applets/monitoring.yml
packages/m/mate-applets/package.yml
packages/m/mate-applets/pspec_x86_64.xml
packages/m/mate-notification-daemon/abi_used_symbols
packages/m/mate-notification-daemon/monitoring.yml
packages/m/mate-notification-daemon/package.yml
packages/m/mate-notification-daemon/pspec_x86_64.xml
packages/m/mate-panel/abi_used_symbols
packages/m/mate-panel/monitoring.yml
packages/m/mate-panel/package.yml
packages/m/mate-panel/pspec_x86_64.xml

**Summary**
Update some of the mate components/apps to their latest versions and add monitoring.yml's
**Test Plan**
- Viewed a document in `atril`
- Tested different notification themes
- Added apps to my panel
**Checklist**

Mate updates

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Use `safe terminal_size_of`
- Use `terminal_size_of` with borrowed raw handle
- Add Gleam lang icon
**Test Plan**
**Checklist**

eza: Update to v0.20.12

---

packages/h/handbrake/abi_symbols
packages/h/handbrake/abi_used_libs
packages/h/handbrake/abi_used_symbols
packages/h/handbrake/package.yml
packages/h/handbrake/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/HandBrake/HandBrake/releases/tag/1.9.0).
**Test Plan**
- Checked settings and menus.
**Checklist**

handbrake: Update to 1.9.0

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v32.2.1/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 32.2.1

---

packages/s/sox_ng/package.yml
packages/s/sox_ng/pspec_x86_64.xml

**Summary**
- Add correct license, see https://codeberg.org/sox_ng/sox_ng/wiki/Copyright
**Test Plan**
- Checked license was added.
**Checklist**

sox_ng: fix license

---

packages/f/fluidsynth/package.yml
packages/f/fluidsynth/pspec_x86_64.xml

**Summary**
- Fix clicks and pops caused when changing parameters of the lowpass filter
- Minor adjustment to AWE32 NRPN behavior
Resolves https://github.com/getsolus/packages/issues/4526
**Test Plan**
- Play a sample MIDI file from the command line
**Checklist**

fluidsynth: Update to v2.4.1

---

packages/w/weechat/abi_symbols
packages/w/weechat/package.yml
packages/w/weechat/pspec_x86_64.xml

**Summary**
Full changelog available [here](https://github.com/weechat/weechat/releases/tag/v4.5.0).
**Test Plan**
Connect to Libera and send and receive messages.
**Checklist**

weechat: Update to v4.5.0

---

packages/g/gnucash/abi_symbols
packages/g/gnucash/package.yml
packages/g/gnucash/pspec_x86_64.xml

**Summary**
Release note can be read [here](https://github.com/Gnucash/gnucash/releases/tag/5.10)
**Test Plan**
Open my existing account
**Checklist**

gnucash: Update to v5.10

---

packages/b/budgie-extras/abi_used_symbols
packages/b/budgie-extras/package.yml
packages/b/budgie-extras/pspec_x86_64.xml

**Summary**
Add bluetooth tethering support to the network applet
**Test Plan**
Install all applet in VM
**Checklist**

budgie-extras: Update to v1.8.0

---

packages/b/brogue/MAINTAINERS.md
packages/b/brogue/abi_used_symbols
packages/b/brogue/package.yml
packages/b/brogue/pspec_x86_64.xml

**Summary**
Full changelog can found [here](https://raw.githubusercontent.com/tmewett/BrogueCE/refs/tags/v1.14.1/CHANGELOG.md)
**Test Plan**
Play the first level
**Checklist**

brogue: Update to v1.14.1

---

packages/m/mlt/abi_symbols
packages/m/mlt/abi_used_symbols
packages/m/mlt/package.yml
packages/m/mlt/pspec_x86_64.xml

**Summary**
Full changelog can be found [here](https://raw.githubusercontent.com/mltframework/mlt/refs/tags/v7.28.0/NEWS)
Resolves getsolus/packages#4500
**Test Plan**
Launch kdenlive, shotcut, and synfigstudio
**Checklist**

mlt: Update to v7.28.0

---

packages/a/armagetronad/abi_used_symbols
packages/a/armagetronad/monitoring.yml
packages/a/armagetronad/package.yml
packages/a/armagetronad/pspec_x86_64.xml

**Summary**
- Refer to notes [here](https://gitlab.com/armagetronad/armagetronad/-/blob/trunk/CHANGELOG.md?ref_type=heads)
**Test Plan**
- Beat the computer in a round
**Checklist**

armagetronad: Update to v0.2.9.2.3

---

packages/f/fzf/MAINTAINERS.md
packages/f/fzf/package.yml
packages/f/fzf/pspec_x86_64.xml

**Summary**
Full changelog can be found [here](https://raw.githubusercontent.com/junegunn/fzf/refs/tags/v0.57.0/CHANGELOG.md)
**Test Plan**
Use `fzf` in local git repo
**Checklist**

fzf: Update to v0.57.0

---

packages/f/fastfetch/package.yml
packages/f/fastfetch/pspec_x86_64.xml

**Summary**
Full changelog can be found [here](https://raw.githubusercontent.com/fastfetch-cli/fastfetch/refs/tags/2.32.1/CHANGELOG.md)
**Test Plan**
Run the app
**Checklist**

fastfetch: Update to v2.32.1

---

packages/f/fortune-mod/package.yml
packages/f/fortune-mod/pspec_x86_64.xml

**Summary**
- prepare dist for a release; ChangeLog date
- New version: 3.24.0
**Test Plan**
fortune  -o
**Checklist**

fortune-mod: Update to v3.24.0

---

.github/pull_request_template.md

pull_request_template.md: Add Sync Notes label instruction

---

packages/x/xfce4-screensaver/abi_used_symbols
packages/x/xfce4-screensaver/package.yml
packages/x/xfce4-screensaver/pspec_x86_64.xml

**Summary**
Changelog available [here](https://www.mail-archive.com/xfce-announce@xfce.org/msg01031.html).
**Test Plan**
Rebooted, locked the session, unlocked the session.
**Checklist**

xfce4-screensaver: Update to v4.18.4

---

packages/u/unrar/package.yml
packages/u/unrar/pspec_x86_64.xml

**Summary**
No changelog available
**Test Plan**
Test using sample file from [here](https://getsamplefiles.com/sample-archive-files/rar)
**Checklist**

unrar: Update to v7.1.2

---

packages/g/gnuplot/abi_used_symbols
packages/g/gnuplot/monitoring.yml
packages/g/gnuplot/package.yml
packages/g/gnuplot/pspec_x86_64.xml

**Summary**
- [changelog](http://gnuplot.info/ReleaseNotes_6_0_2.html)
**Test Plan**
- plot data using 1:2 with line title 'table-name'
**Checklist**

gnuplot: Update to 6.0.2

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/cli/cli/releases/tag/v2.64.0).
**Test Plan**
Run `gh status`, `gh pr create`, and create this Pull Request.
**Checklist**

github-cli: Update to v2.64.0

---

packages/w/weechat/package.yml
packages/w/weechat/pspec_x86_64.xml

**Summary**
- relay: fix crash after `/upgrade` when relay clients are connected
- api: fix creation of empty buffer in function infolist_new_var_buffer
- core: fix detection of dl library
- logger: fix path displayed when the logs directory can not be created
**Test Plan**
Connect to Libera, join a room, send and receive messages.
**Checklist**

weechat: Update to v4.5.1

---

packages/t/thunar-archive-plugin/monitoring.yml
packages/t/thunar-archive-plugin/package.yml
packages/t/thunar-archive-plugin/pspec_x86_64.xml
packages/x/xarchiver/files/xarchiver.metainfo.xml
packages/x/xarchiver/package.yml
packages/x/xarchiver/pspec_x86_64.xml

**Summary**
- Add/fix support for bz2 and bz3 files
- Add a few more compression mimetypes, sort the list
Fixes https://github.com/getsolus/packages/issues/4655
Fixes https://github.com/getsolus/packages/issues/4656
Part of https://github.com/getsolus/packages/issues/1389
Part of https://github.com/getsolus/packages/issues/4121
**Test Plan**
Extract an archive using the Thunar right-click menu.
Validate installed metainfo file for `xarchiver`.
**Checklist**

thunar-archive-plugin: Update to v0.5.2

---

packages/g/gtkhash/abi_libs
packages/g/gtkhash/abi_symbols
packages/g/gtkhash/abi_used_libs
packages/g/gtkhash/abi_used_symbols
packages/g/gtkhash/files/msgfmt.patch
packages/g/gtkhash/monitoring.yml
packages/g/gtkhash/package.yml
packages/g/gtkhash/pspec_x86_64.xml

**Summary**
- Build Thunar plugin
- Add dependency to the respective file manager for each plugin
Fixes https://github.com/getsolus/packages/issues/4657
**Test Plan**
- Install the Thunar plugin, view a file's properties, and generate a bunch of checksum hashes in the Checksums tab.
- Inspect the package metadata for all plugin packages and make sure that the dependencies are correct.
**Checklist**

gtkhash: Build thunar plugin

---

packages/s/sox_ng/abi_used_symbols
packages/s/sox_ng/package.yml
packages/s/sox_ng/pspec_x86_64.xml

**Summary**
- Make reading from ffmpeg work by popen()ing "rb"
- Add support for more codecs with ffmpeg
**Test Plan**
- Checked new codecs were loaded.
**Checklist**

sox_ng: Update to v14.5.0.2

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v32.3.0/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 32.3.0

---

packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
**Test Plan**
- run cli; open stdout in pager kitten
**Checklist**

kitty: Update to 0.38.1

---

packages/t/thunar-archive-plugin/abi_used_symbols
packages/t/thunar-archive-plugin/package.yml
packages/t/thunar-archive-plugin/pspec_x86_64.xml

**Summary**
- Resolve conflicting mnemonics
- Support setting WAYLAND environment
- Avoid deprecated functions
**Test Plan**
Create and extract an archive via the Thunar context menu.
**Checklist**

thunar-archive-plugin: Update to v0.5.3

---

packages/t/thunar-media-tags-plugin/abi_used_symbols
packages/t/thunar-media-tags-plugin/package.yml
packages/t/thunar-media-tags-plugin/pspec_x86_64.xml

**Summary**
- Fix AtkRelationSet leaks
**Test Plan**
View a song file's media tags.
**Checklist**

thunar-media-tags-plugin: Update to v0.5.0

---

packages/q/qtractor/package.yml
packages/q/qtractor/pspec_x86_64.xml

**Summary**
Fixed and awfully bad MIDI metronome and clock timing, a reminiscence from the higher resolution MIDI queueing
**Test Plan**
Launch the app and play some midi
**Checklist**

qtractor: Update to v1.5.1

---

packages/p/piksemel/monitoring.yml
packages/p/piksemel/package.yml
packages/p/piksemel/pspec_x86_64.xml

**Summary**
**Test Plan**
It builds
**Checklist**

piksemel: Housekeeping

---

packages/s/solaar/package.yml
packages/s/solaar/pspec_x86_64.xml

**Summary**
- Release notes available [here](https://github.com/pwr-Solaar/Solaar/releases/tag/1.1.14)
**Test Plan**
- Change some settings on MX Master  mouse.
**Checklist**

solaar: Update to v1.1.14

---

packages/w/winetricks/package.yml
packages/w/winetricks/pspec_x86_64.xml

**Summary**
No summarized changelog available
Full commit log available [here](https://github.com/Winetricks/winetricks/compare/20240105...20250102)
**Test Plan**
Installed an additional component in my Wine prefix
**Checklist**

winetricks: Update to v20250102

---

packages/g/goverlay/package.yml
packages/g/goverlay/pspec_x86_64.xml

**Summary**
Fix version number to match upstream versioning scheme
**Checklist**
- [n/a] Package was built and tested against unstable

goverlay: Fix version number

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v32.3.1/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 32.3.1

---

packages/t/The-Powder-Toy/abi_used_symbols
packages/t/The-Powder-Toy/package.yml
packages/t/The-Powder-Toy/pspec_x86_64.xml

**Summary**
Release notes available [here](https://powdertoy.co.uk/Download/Changelog.html)
**Test Plan**
Play with sand and snow
**Checklist**

The-Powder-Toy: Update to v99.0.377

---

packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
Bugfix release
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-10.0-rc4)
**Test Plan**
- Played Age Of Empires I Trial
**Checklist**

wine: Update to v10.0-rc4

---

packages/h/hunspell-uk/monitoring.yml
packages/h/hunspell-uk/package.yml
packages/h/hunspell-uk/pspec_x86_64.xml

**Summary**
- Dictionary update
**Test Plan**
- M-x flyspell-buffer
**Checklist**

hunspell-uk: Update to 6.5.4

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Add new icons
**Test Plan**
**Checklist**

eza: Update to v0.20.15

---

packages/g/gleam/abi_used_symbols
packages/g/gleam/package.yml
packages/g/gleam/pspec_x86_64.xml

**Summary**
Changelog (article):
https://gleam.run/news/improved-performance-and-publishing/
**Test Plan**
**Checklist**

gleam: Update to v1.7.0

---

packages/v/vice/MAINTAINERS.md
packages/v/vice/abi_used_libs
packages/v/vice/abi_used_symbols
packages/v/vice/monitoring.yml
packages/v/vice/package.yml
packages/v/vice/pspec_x86_64.xml

**Summary**
- See changelog [here](https://vice-emu.sourceforge.io/NEWS)
**Test Plan**
- Run a few different emulated machines
**Checklist**

vice: Update to v3.9

---

packages/w/warpinator/package.yml
packages/w/warpinator/pspec_x86_64.xml

**Summary**
Update translations
**Test Plan**
Launch the app
**Checklist**

warpinator: Update to v1.8.8

---

packages/b/bash-completion/files/0001-Use-a-stateless-configuration.patch
packages/b/bash-completion/package.yml
packages/b/bash-completion/pspec_x86_64.xml

**Summary**
Full changelog can be found [here](https://raw.githubusercontent.com/scop/bash-completion/refs/tags/2.16.0/CHANGELOG.md)
**Test Plan**
Try a few completion
**Checklist**

bash-completion: Update to v2.16.0

---

packages/m/metacity/files/series
packages/m/metacity/monitoring.yml
packages/m/metacity/package.yml
packages/m/metacity/pspec_x86_64.xml

**Summary**
- Change homepage (Part of getsolus/packages#4116)
**Test Plan**
Make sure homepage is applied to pspec
**Checklist**

metacity: Housekeeping

---

packages/t/tetrs/files/Cargo.lock
packages/t/tetrs/package.yml
packages/t/tetrs/pspec_x86_64.xml

**Summary**
- Revamped movement handling! (Is now guideline-compliant)
- 0 ARR finesse etc. should be better now.
- (As usual, only noticeable with enhanced keyboard events, e.g. with Kitty.)
- New game configuration option: "assume enhanced key events".
- Can be used to manually override the otherwise automatic detection of enhanced keyboard events (the Kitty protocol).
- Tweaked lock delay curve, ground time max (3s -> 2s), soft drop factor (15x -> 10x).
- Tweaked Master mode goal.
- Starts at lvl 20 and ends at lvl 35.
- Custom start boards (./tetrs_tui --custom-board=...) are now also stored in the save file.
- Can be deleted/reset in the New Game menu with [del].
**Summary**
**Test Plan**
- Played it.
**Checklist**

tetrs: Update to v0.2.5

---

packages/o/openrct2/abi_used_symbols
packages/o/openrct2/package.yml
packages/o/openrct2/pspec_x86_64.xml

**Summary**
- Changelog [here](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.18)
**Test Plan**
- Start a new scenario
**Checklist**

openrct2: Update to v0.4.18

---

packages/d/d-feet/MAINTAINERS.md
packages/d/d-feet/monitoring.yml
packages/d/d-feet/package.yml
packages/d/d-feet/pspec_x86_64.xml

**Summary**
**Test Plan**
Makes sure homepage is changed
**Checklist**

d-feet: Housekeeping

---

packages/v/virtualbox/files/org.virtualbox.virtualbox.metainfo.xml
packages/v/virtualbox/package.yml
packages/v/virtualbox/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

virtualbox: Add appstream metainfo

---

packages/a/appstream-data/package.yml
packages/a/appstream-data/pspec_x86_64.xml

**Summary**
Update Appstream data
**Test Plan**
- Build Appstream data from this PR
- Open Discover, see that it doesn't break
**Checklist**

appstream-data: Update to v53

---

packages/l/librsvg/package.yml
packages/l/librsvg/pspec_x86_64.xml

**Summary**
**Test Plan**
- Check license and homepage.
**Checklist**

librsvg: housekeeping

---

packages/l/libvte/package.yml
packages/l/libvte/pspec_x86_64.xml

**Summary**
- Fix homepage and license
**Test Plan**
- Checked license and homepage.
**Checklist**

libvte: housekeeping

---

packages/l/libsoup/abi_used_symbols
packages/l/libsoup/abi_used_symbols32
packages/l/libsoup/package.yml
packages/l/libsoup/pspec_x86_64.xml

**Summary**
- Change homepage and fix licesnse
**Test Plan**
- Checked homepage and license.
**Checklist**

libsoup: housekeeping

---

packages/s/shotwell/package.yml
packages/s/shotwell/pspec_x86_64.xml

**Summary**
- Changed homepage
**Test Plan**
- Checked homepage
**Checklist**

shotwell: update homepage

---

common/CI/config.yaml

Implement ISO freeze for 2025-01-11 thru 2025-01-16

Add freeze period for 2025-01

---

packages/s/sound-juicer/abi_used_symbols
packages/s/sound-juicer/package.yml
packages/s/sound-juicer/pspec_x86_64.xml

**Summary**
**Test Plan**
- Checked license and homepage
**Checklist**

sound-juicer: housekeeping

---

packages/s/seahorse/package.yml
packages/s/seahorse/pspec_x86_64.xml

**Summary**
- Fix homepage and license
**Test Plan**
- Checked license and homepage.
**Checklist**

seahorse: housekeeping

---

packages/t/tilp/abi_used_symbols
packages/t/tilp/files/0001-Fix-appdata-and-desktop-files.patch
packages/t/tilp/monitoring.yaml
packages/t/tilp/package.yml
packages/t/tilp/pspec_x86_64.xml

**Summary**
- Fix appstream generation:
- Patch appdata and desktop file
- Install app icon to proper path
**Test Plan**
**Checklist**

tilp: Housekeeping

---

packages/n/networkmanager-pptp/package.yml
packages/n/networkmanager-pptp/pspec_x86_64.xml

**Summary**
- Change homepage.
**Checklist**
- Change homepage.

networkmanager-pptp: update homepage

---

packages/l/lolcat/monitoring.yaml
packages/r/ruby-manpages/monitoring.yaml
packages/r/ruby-optimist/monitoring.yaml
packages/r/ruby-paint/monitoring.yaml

**Summary**
- Add monitoring
**Test Plan**
- Checked that it was YAML this time around.
**Checklist**

 [NFC] repo-wide: Add monitoring.yaml files

---

packages/py/py/monitoring.yaml
packages/py/pychess/monitoring.yaml
packages/py/pygal/monitoring.yaml
packages/py/python-levenshtein/monitoring.yaml
packages/py/python-mistune/monitoring.yaml
packages/py/python-notify2/monitoring.yaml
packages/py/python-peewee/monitoring.yaml
packages/py/python-pylev/monitoring.yaml
packages/py/python-pyocr/monitoring.yaml
packages/py/python-pypng/monitoring.yaml
packages/py/python-pyrsistent/monitoring.yaml
packages/py/python-pyte/monitoring.yaml
packages/py/python-requests/monitoring.yaml
packages/py/python-slip/monitoring.yaml
packages/py/python-starlette/monitoring.yaml
packages/py/python-testpath/monitoring.yaml
packages/py/python-tifffile/monitoring.yaml
packages/py/python-ujson/monitoring.yaml
packages/py/python-unidecode/monitoring.yaml

**Summary**
- Initial pass at py subfolder
**Test Plan**
N/A
**Checklist**

[NFC] repo-wide: Add monitoring.yaml files

---

packages/s/simsu/abi_used_symbols
packages/s/simsu/monitoring.yaml
packages/s/simsu/package.yml
packages/s/simsu/pspec_x86_64.xml

**Summary**
- General:
- Improved deployment
- Bug Fixes:
- FIXED: Very wide window when played for first time
- Translation Updates
- Portuguese
**Test Plan**
- Play a game
**Checklist**

simsu: Update to 1.4.4

---

packages/g/geary/package.yml
packages/g/geary/pspec_x86_64.xml

**Summary**
- Fix homepage and license
**Test Plan**
- Checked license and homepage.
**Checklist**

geary: housekeeping

---

packages/g/gedit-plugins/package.yml
packages/g/gedit-plugins/pspec_x86_64.xml

**Summary**
- Fix homepage
**Test Plan**
- Check files.
**Checklist**

gedit-plugins: fix homepage

---

packages/c/calamares/files/install/modules/finished.conf
packages/c/calamares/package.yml
packages/c/calamares/pspec_x86_64.xml

**Summary**
Enable the 'Restart now' checkbox after installation.
**Test Plan**
Install Solus with an ISO with this update.
**Checklist**

calamares: Enable reboot after installation

---

common/CI/config.yaml
common/iso_packages.txt

**Summary**
Updates the ISO packages list.
**Test Plan**
n/a
**Checklist**

common: Update iso_packages.txt

---

packages/g/gnome-desktop-branding/package.yml
packages/g/gnome-desktop-branding/pspec_x86_64.xml

**Summary**
Change default background
**Test Plan**
Spin gnome ISO and boot
**Checklist**

gnome-desktop-branding: Update to latest git

---

packages/g/gtk-vnc/package.yml
packages/g/gtk-vnc/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

gtk-vnc: housekeeping

---

packages/g/gupnp-av/MAINTAINERS.md
packages/g/gupnp-av/package.yml
packages/g/gupnp-av/pspec_x86_64.xml

**Summary**
- Remove old maintainer
**Test Plan**
- Checked files
**Checklist**

gupnp-av: housekeeping

---

packages/g/gnome-bluetooth/package.yml
packages/g/gnome-bluetooth/pspec_x86_64.xml

**Summary**
- Fix homepage
**Test Plan**
**Checklist**

gnome-bluetooth: fix homepage

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v32.4.0/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 32.4.0

---

packages/z/zig/MAINTAINERS.md

**Summary**
- Replace maintainer contact
**Test Plan**
- :-)
**Checklist**

zig: Update maintainers.md

---

packages/d/distrobox/monitoring.yaml
packages/d/distrobox/package.yml
packages/d/distrobox/pspec_x86_64.xml

**Summary**
- add monitoring file
- [changelog](https://github.com/89luca89/distrobox/releases/tag/1.8.1)
**Test Plan**
Update current distrobox containers
**Checklist**

distrobox: Update to v1.8.1

---

packages/d/doublecmd/package.yml
packages/d/doublecmd/pspec_x86_64.xml

**Summary**
- [Changelog](https://github.com/doublecmd/doublecmd/compare/v1.1.21...v1.1.22)
**Test Plan**
- Copy a file from left pane to right pane.
**Checklist**

doublecmd: Update to 1.1.22

---

packages/f/freeciv/abi_symbols
packages/f/freeciv/abi_used_libs
packages/f/freeciv/abi_used_symbols
packages/f/freeciv/package.yml
packages/f/freeciv/pspec_x86_64.xml

**Summary**
- [Changelog](https://freeciv.fandom.com/wiki/NEWS-3.1.4)
**Test Plan**
- Start a game and play
**Checklist**

freeciv: Update to 3.1.4

---

packages/o/os-release/files/os-release
packages/o/os-release/files/solus-release
packages/o/os-release/package.yml
packages/o/os-release/pspec_x86_64.xml

os-release: Prepare for 4.7

---

packages/g/gnome-browser-connector/monitoring.yaml
packages/g/gnome-browser-connector/package.yml
packages/g/gnome-browser-connector/pspec_x86_64.xml

**Summary**
- Fix homepage
**Test Plan**
**Checklist**

gnome-browser-connector: fix homepage

---

packages/g/gupnp/MAINTAINERS.md
packages/g/gupnp/package.yml
packages/g/gupnp/pspec_x86_64.xml

**Summary**
- Remove old maintainer
**Test Plan**
**Checklist**

gupnp: housekeeping

---

packages/g/glib2/package.yml
packages/g/glib2/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

glib2: change homepage

---

packages/g/git-cola/package.yml
packages/g/git-cola/pspec_x86_64.xml

**Summary**
- Full changelog [here](https://github.com/git-cola/git-cola/blob/main/CHANGES.rst#v4110)
**Test Plan**
- Browse `git-cola` repo using the GUI, see the diff changes.
**Checklist**

git-cola: Update to 4.11.0

---

packages/n/nsxiv/abi_used_symbols
packages/n/nsxiv/monitoring.yaml
packages/n/nsxiv/package.yml
packages/n/nsxiv/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://codeberg.org/nsxiv/nsxiv/src/branch/master/etc/CHANGELOG.md).
**Test Plan**
- Opened an image.
**Checklist**

nsxiv: Update to v33

---

packages/g/gupnp-dlna/MAINTAINERS.md
packages/g/gupnp-dlna/abi_used_symbols
packages/g/gupnp-dlna/package.yml
packages/g/gupnp-dlna/pspec_x86_64.xml

**Summary**
- Remove old maintainer
**Test Plan**
**Checklist**

gupnp-dlna: housekeeping

---

packages/g/gupnp-igd/monitoring.yaml
packages/g/gupnp-igd/package.yml
packages/g/gupnp-igd/pspec_x86_64.xml

**Summary**
**Test Plan**
- Check license and homepage.
**Checklist**

gupnp-igd: housekeeping

---

packages/d/distrobox/package.yml
packages/d/distrobox/pspec_x86_64.xml

**Summary**
[bugfix update](https://github.com/89luca89/distrobox/releases/tag/1.8.1.2)
**Test Plan**
launch distrobox container
**Checklist**

distrobox: Update to v1.8.1.2

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Support additional yaml file extension, clippy
**Test Plan**
**Checklist**

eza: Update to v0.20.18

---

packages/s/sway/abi_used_symbols
packages/s/sway/package.yml
packages/s/sway/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/swaywm/sway/releases/tag/1.10.1)
**Test Plan**
- Start a sway session
**Checklist**

sway: Update to v1.10.1

---

packages/t/tiled/abi_used_symbols
packages/t/tiled/package.yml
packages/t/tiled/pspec_x86_64.xml

**Summary**
- YY plugin: Fixed compatibility with GameMaker 2024
- Fixed crash while handling file reloads without any files opened
- Fixed crash when closing the last file with multiple custom properties selected
**Test Plan**
- open tmx file, edit, save
**Checklist**

tiled: Update to 1.11.2

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Fix regression in theme config location, simplify path
- Fix wrong file name for Brewfile
**Test Plan**
**Checklist**

eza: Update to v0.20.19

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
Full changelog available [here](https://github.com/cli/cli/releases/tag/v2.66.0).
**Test Plan**
**Checklist**

github-cli: Update to v2.66.1

---

packages/a/aerc/package.yml
packages/a/aerc/pspec_x86_64.xml

**Summary**
Changelog: https://git.sr.ht/~rjarry/aerc/refs
**Test Plan**
* Build and install package locally.
* Run with real email credentials.
**Checklist**

aerc: Update to 0.20.1

---

packages/p/pidgin/abi_used_symbols
packages/p/pidgin/package.yml
packages/p/pidgin/pspec_x86_64.xml

**Summary**
- Bug fixes and minor improvements
Full changelog available [here](https://pidgin.im/posts/) or [here](https://discourse.imfreedom.org/tag/release)
**Test Plan**
- Launched pidgin
- Verified connection to an existing jabber account, successful message exchange.
**Checklist**

pidgin: Update to v2.14.14

---

packages/o/openrct2/package.yml
packages/o/openrct2/pspec_x86_64.xml

**Summary**
- Changelog [here](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.19)
- And [here](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.19.1)
**Test Plan**
- Play a scenario for a while
**Checklist**

openrct2: Update to v0.4.19.1

---

packages/f/fluidsynth/abi_symbols
packages/f/fluidsynth/package.yml
packages/f/fluidsynth/pspec_x86_64.xml

**Summary**
- [2.4.3](https://github.com/FluidSynth/fluidsynth/releases/tag/v2.4.3)
- [2.4.2](https://github.com/FluidSynth/fluidsynth/releases/tag/v2.4.2)
**Test Plan**
Play this banger: https://en.wikipedia.org/wiki/File:MIDI_sample.mid?oldformat=true
**Checklist**

fluidsynth: Update to v2.4.3

---

packages/f/fzf/package.yml
packages/f/fzf/pspec_x86_64.xml

**Summary**
Release note is available [here](https://junegunn.github.io/fzf/releases/0.59.0/)
**Test Plan**
Use it the search file in repo directory
**Checklist**

fzf: Update to v0.59.0

---

packages/n/nautilus-python/monitoring.yaml
packages/n/navi/monitoring.yaml
packages/n/nbd/monitoring.yaml
packages/n/ncmpcpp/monitoring.yaml
packages/n/ncurses5/monitoring.yaml
packages/n/neochat/monitoring.yaml
packages/n/neon/monitoring.yaml
packages/n/networkx/monitoring.yaml
packages/n/neverball/monitoring.yaml
packages/n/nheko/monitoring.yaml
packages/n/ninja/monitoring.yaml
packages/n/ninvaders/monitoring.yaml
packages/n/nlohmann-json/monitoring.yaml
packages/n/nnn/monitoring.yaml
packages/n/notmuch/monitoring.yaml
packages/n/nss-mdns/monitoring.yaml
packages/n/nuitka/monitoring.yaml
packages/n/numactl/monitoring.yaml
packages/n/numpy/monitoring.yaml

**Summary**
First pass at N directory
**Test Plan**
N/A
**Checklist**
- [n/a ] Package was built and tested against unstable

[NFC] repo-wide: Add monitoring.yaml

---

packages/b/bluejay/package.yml
packages/b/bluejay/pspec_x86_64.xml

**Summary**
- Make project REUSE compliant
- Fix screenshot URL in appstream metainfo
- Add Ukrainian translations
**Test Plan**
Verify that appstream data passes validation, run the application, and connect and disconnect Bluetooth devices.
**Checklist**

bluejay: Update to v1.0.2

---

packages/w/waybar/abi_used_symbols
packages/w/waybar/files/0001-Fix-std-bad_casts-in-tray-module.patch
packages/w/waybar/package.yml
packages/w/waybar/pspec_x86_64.xml

**Summary**
- Backport a fix for the tray module not showing icons
Ref https://github.com/Alexays/Waybar/issues/3597
**Test Plan**
Restart waybar while running Niri and see that I have tray icons again.
**Checklist**

waybar: Backport fix for tray module

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Make `flake.lock` icon the nix logo
**Test Plan**
**Checklist**

eza: Update to v0.20.20

---

packages/s/sysstat/package.yml
packages/s/sysstat/pspec_x86_64.xml

**Summary**
- See changes [here](https://github.com/sysstat/sysstat/blob/master/CHANGES)
**Test Plan**
- Run some utilities like `iostat`
**Checklist**

sysstat: Update to v12.7.7

---

packages/py/python-spyder-kernels/package.yml
packages/py/python-spyder-kernels/pspec_x86_64.xml
packages/s/spyder3/package.yml
packages/s/spyder3/pspec_x86_64.xml

**Summary**
- [6.0.4](https://github.com/spyder-ide/spyder/releases/tag/v6.0.4)
- [6.0.3](https://github.com/spyder-ide/spyder/releases/tag/v6.0.3)
**Test Plan**
- Run a few python scripts
**Checklist**

spyder3: Update to 6.0.4

---

packages/s/syncthing/package.yml
packages/s/syncthing/pspec_x86_64.xml

**Summary**
Bugfixes & enhancements
**Test Plan**
- Restart Syncthing-GTK, use it to restart syncthing, verify all folders sync
**Checklist**

syncthing: Update to v1.29.2

---

packages/s/sqlite3/abi_used_libs32
packages/s/sqlite3/abi_used_symbols
packages/s/sqlite3/abi_used_symbols32
packages/s/sqlite3/files/sqlite-lemon-system-template.patch
packages/s/sqlite3/package.yml
packages/s/sqlite3/pspec_x86_64.xml

**Summary**
- introduces the lemon parser
- update sqlite to latest version
**Test Plan**
create [test db](https://docs.python.org/3/library/sqlite3.html#tutorial) in python.
**Checklist**

sqlite3: Update to 3.48.0

---

packages/x/x11perf/monitoring.yaml

**Summary**
Change extension from `yml` to `yaml` and add RSS feed.
**Test Plan**
n/a
**Checklist**

[NFC] x11perf: Fix monitoring.yaml

---

common/Scripts/yauto.py

**Summary**
The previous change to pyproject.toml happened to only work for sources also using other, higher-priority build systems. The logic for adding the dependencies to PYTHON_MODULE recipes was still based on strings.
Additionally the dependencies were added multiple times for each `pyproject.toml` or `setup.cfg file` found. Don't add additional dependencies if PEP 517 is already among known_types
Make sure the PEP517 dependencies are correctly added if the source also uses other build systems instead of wrapping them in pkgconfig()
Previous behaviour:
```
 go-task new -- pip-tools https://files.pythonhosted.org/packages/1a/87/1ef453f10fb0772f43549686f924460cc0a2404b828b348f72c52cb2f5bf/pip-tools-7.4.1.tar.gz
task: [new] /home/thomas/Projects/SolusPackaging/common/Scripts/new-packag …
```

yauto: Only add pyproject.toml deps once

---

packages/h/hwdata/package.yml
packages/h/hwdata/pspec_x86_64.xml

**Summary**
- Update pci, usb and vendor ids
**Test Plan**
- Installed, no fires
**Checklist**

hwdata: Update to v0.392

---

packages/h/hunspell-da/monitoring.yaml
packages/h/hunspell-da/package.yml
packages/h/hunspell-da/pspec_x86_64.xml
packages/h/hunspell-es/monitoring.yaml
packages/h/hunspell-es/package.yml
packages/h/hunspell-es/pspec_x86_64.xml
packages/h/hunspell-hu/monitoring.yaml
packages/h/hunspell-hu/package.yml
packages/h/hunspell-hu/pspec_x86_64.xml
packages/h/hunspell-id/monitoring.yaml
packages/h/hunspell-id/package.yml
packages/h/hunspell-id/pspec_x86_64.xml
packages/h/hunspell-pl/monitoring.yaml
packages/h/hunspell-pl/package.yml
packages/h/hunspell-pl/pspec_x86_64.xml
packages/h/hunspell-ru/package.yml
packages/h/hunspell-ru/pspec_x86_64.xml

**Summary**
- Updates for some hunspell dictionaries
**Test Plan**
- Install OK
**Checklist**

Hunspell updates

---

packages/s/sdl3/abi_symbols
packages/s/sdl3/abi_used_symbols
packages/s/sdl3/package.yml
packages/s/sdl3/pspec_x86_64.xml

**Summary**
3.2.4 [changelog](https://github.com/libsdl-org/SDL/releases/tag/release-3.2.4)
3.2.2 [changelog](https://github.com/libsdl-org/SDL/releases/tag/release-3.2.2)
**Test Plan**
Create a window with sdl3
**Checklist**

sdl3: Update to v3.2.4

---

packages/b/brave/files/com.brave.Browser.metainfo.xml
packages/b/brave/package.yml
packages/b/brave/pspec_x86_64.xml

**Summary**
- Changelog [here](https://community.brave.com/t/release-channel-1-75-178/598553)
- Resolves #44008
**Test Plan**
- Open a few web sites
**Checklist**

brave: Update to 1.75.178

---

packages/r/re2c/abi_used_symbols
packages/r/re2c/package.yml
packages/r/re2c/pspec_x86_64.xml

**Summary**
[changelog](https://re2c.org/releases/release_notes.html#release-4-1)
**Test Plan**
run example lexer
**Checklist**

re2c: Update to v4.1

---

packages/s/sdl2/abi_used_symbols
packages/s/sdl2/abi_used_symbols32
packages/s/sdl2/package.yml
packages/s/sdl2/pspec_x86_64.xml

**Summary**
[2.32.0 changelog](https://github.com/libsdl-org/SDL/releases/tag/release-2.32.0) 
[2.30.12 changelog](https://github.com/libsdl-org/SDL/releases/tag/release-2.30.12)
**Test Plan**
rebuild lite-xl and launch
**Checklist**

sdl2: Update to v2.32.0

---

packages/a/aisleriot/abi_symbols
packages/a/aisleriot/abi_used_symbols
packages/a/aisleriot/package.yml
packages/a/aisleriot/pspec_x86_64.xml

**Summary**
Full commit log available [here](https://gitlab.gnome.org/GNOME/aisleriot/-/compare/3.22.34...3.22.35)
**Test Plan**
Played a couple rounds of Klondike/Canfield
**Checklist**

aisleriot: Update to v3.22.35

---

packages/x/xfce4-notifyd/abi_used_symbols
packages/x/xfce4-notifyd/package.yml
packages/x/xfce4-notifyd/pspec_x86_64.xml
packages/x/xfdesktop/abi_used_symbols
packages/x/xfdesktop/package.yml
packages/x/xfdesktop/pspec_x86_64.xml

**Summary**
- **xfce4-notifyd: Update to v0.9.7**
- **xfdesktop: Update to v4.20.1**
**Test Plan**
Start a new Xfce session, send a notification.
**Checklist**

xfce4 updates

---

packages/g/git-lfs/package.yml
packages/g/git-lfs/pspec_x86_64.xml

**Summary**
- Correct shell completion permissions
**Test Plan**
- Completions available in bash, fish, zsh
**Checklist**

git-lfs: Correct shell completion permissions

---

packages/py/python-typeguard/package.yml
packages/py/python-typeguard/pspec_x86_64.xml

Automatic update, please verify before landing

python-typeguard: Update to v4.4.2 (auto-update)

---

packages/py/python-myst-parser/package.yml
packages/py/python-myst-parser/pspec_x86_64.xml

Automatic update, please verify before landing

python-myst-parser: Update to v4.0.1 (auto-update)

---

common/Scripts/yauto.py

**Summary**
The PKG_CHECK_MODULES macro in configure.ac files can define more than one module (see [here](https://autotools.info/pkgconfig/pkg_check_modules.html)).
Previously all the entries were simply added into the same `pkgconfig()`.
This properly separates them into their own entries and also accepts "<=" and "=" comparators (though these aren't used for anything except detecting version definitions)
Also fix adding dependencies for combined configure.ac/Python projects
Old behaviour:
```
 go-task new -- gammastep https://gitlab.com/chinstrap/gammastep/-/archive/v2.0.9/gammastep-v2.0.9.tar.bz2
[...]
 yq '.builddeps' packages/g/gammastep/package.yml
- pkgconfig(libdrm)
- pkgconfig(x11)
- pkgconfig(xxf86vm)
- pkgconfig(xcb)
- pkgconfig(xcb-randr)
- pkgconfig(wayland-client …
```

yauto: Handle PKG_CHECK_MODULES that define multiple modules

---

packages/z/zenergy/MAINTAINERS.md
packages/z/zenergy/package.yml
packages/z/zenergy/pspec_x86_64.xml

**Summary**
- add Maintainer file
- replace KERNELDIR with KDIR to fix building on the server
**Test Plan**
Compile and run goverlay
**Checklist**

zenergy: Fix compilation

---

packages/w/waycheck/package.yml
packages/w/waycheck/pspec_x86_64.xml

**Summary**
- Update to *Colors of Nature*
- Release notes [here](https://gitlab.freedesktop.org/serebit/waycheck/-/releases/v1.6.0)
**Test Plan**
- Launch waycheck, see that it checks my way(land)
**Checklist**

waycheck: Update to v1.6.0

---

packages/a/adwaita-fonts/files/adwaita-fonts.metainfo.xml
packages/a/adwaita-fonts/monitoring.yaml
packages/a/adwaita-fonts/package.yml
packages/a/adwaita-fonts/pspec_x86_64.xml

**Summary**
Add adwaita-fonts at v48.2
**Test Plan**
Set fonts as UI and terminal font
**Checklist**

adwaita-fonts: Add at v48.2

---

packages/c/consul/monitoring.yaml
packages/n/nomad/monitoring.yaml
packages/t/terraform/monitoring.yaml

**Summary**
Remove lefover files from HashiCorp deprecation
**Test Plan**
n/a
**Checklist**
- [ n/a] Package was built and tested against unstable

Remove lefover files from HashiCorp deprecation

---

packages/s/simplenote/files/com.simplenote.Simplenote.appdata.xml
packages/s/simplenote/monitoring.yaml
packages/s/simplenote/package.yml
packages/s/simplenote/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

simplenote: Housekeeping

---

packages/u/utsushi/files/com.github.utsushi.Utsushi.metainfo.xml
packages/u/utsushi/monitoring.yaml
packages/u/utsushi/package.yml
packages/u/utsushi/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

utsushi: Add appstream metainfo

---

packages/q/qdirstat/abi_used_symbols
packages/q/qdirstat/files/add-appstream.patch
packages/q/qdirstat/monitoring.yaml
packages/q/qdirstat/package.yml
packages/q/qdirstat/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

qdirstat: Housekeeping

---

common/Scripts/appstream_ignored_packages.txt

**Summary**
Add this packages to be ignored:
- kde-cli-tools
- cups
- geoclue
- fish
- efl
- visidata

appstream_ignored_packages.txt : Add more ignored packages

---

packages/e/etcher/files/io.balena.etcher.metainfo.xml
packages/e/etcher/monitoring.yaml
packages/e/etcher/package.yml
packages/e/etcher/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

etcher: Housekeeping

---

packages/e/eqonomize/monitoring.yaml
packages/e/eqonomize/package.yml
packages/e/eqonomize/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

eqonomize: Housekeeping

---

packages/q/q4wine/abi_used_symbols
packages/q/q4wine/files/ua.org.brezblock.q4wine.appdata.xml
packages/q/q4wine/monitoring.yaml
packages/q/q4wine/package.yml
packages/q/q4wine/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

q4wine: Housekeeping

---

packages/u/uget/files/com.ugetdm.uGet.appdata.xml
packages/u/uget/package.yml
packages/u/uget/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

uget: Add appstream metainfo

---

packages/t/telegram/abi_used_symbols
packages/t/telegram/package.yml
packages/t/telegram/pspec_x86_64.xml

**Summary**
- [5.11.1](https://github.com/telegramdesktop/tdesktop/releases/tag/v5.11.1)
- [5.11.0](https://github.com/telegramdesktop/tdesktop/releases/tag/v5.11.0)
Resolves https://github.com/getsolus/packages/issues/5024
**Test Plan**
- Launch app
**Checklist**

telegram: Update to v5.11.1

---

packages/o/openrct2/abi_used_symbols
packages/o/openrct2/package.yml
packages/o/openrct2/pspec_x86_64.xml

**Summary**
- Update to 4.20 *Both peaks of Mount Kilimanjaro*
- Release notes [here](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.20)
**Test Plan**
- Play a new scenario
**Checklist**

openrct2: Update to v0.4.20

---

packages/p/parley/package.yml
packages/p/parley/pspec_x86_64.xml

**Summary**
Add missing rundeps:
- kf6-kcmutils
- kf6-kirigami
- translate-shell
**Test Plan**
Launch the app, open settings, and verify translation
**Checklist**

parley: Add missing rundeps

---

packages/z/zenergy/package.yml
packages/z/zenergy/pspec_x86_64.xml

**Summary**
- rework package.yml to prevent the current build from overriding lts
**Test Plan**
Install both builds and boot into each kernel. Run goverlay and run sensors.
**Checklist**

zenergy: Fix lts build

---

packages/s/stone-soup/files/0001-Fix-all-requirement-for-valid-appstream-metainfo.patch
packages/s/stone-soup/files/stone-soup-tiles.desktop
packages/s/stone-soup/files/stone-soup.desktop
packages/s/stone-soup/monitoring.yaml
packages/s/stone-soup/package.yml
packages/s/stone-soup/pspec_x86_64.xml

**Summary**
- Split packages to `-console` and `-tiles`
**Test Plan**
- Install and launch all binary
- `appstream-builder --packages-dir=. --include-failed -v`
**Checklist**

stone-soup: Split to several subpackages and housekeeping

---

packages/h/handbrake/MAINTAINERS.md
packages/h/handbrake/package.yml
packages/h/handbrake/pspec_x86_64.xml

**Summary**
Full changelog can read [here](https://github.com/HandBrake/HandBrake/blob/1.9.2/NEWS.markdown)
**Test Plan**
Convert a video
**Checklist**

handbrake: Update to v1.9.2

---

packages/h/hwdata/package.yml
packages/h/hwdata/pspec_x86_64.xml

**Summary**
- Update pci, usb and vendor ids
- Fix usb.ids encoding and a couple of typos
- Fix configure to honor --prefix
**Test Plan**
- hyprland runs
**Checklist**

hwdata: Update to v0.393

---

packages/g/github-cli/abi_used_symbols
packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
Full changelog available [here](https://github.com/cli/cli/releases/tag/v2.68.0).
**Test Plan**
**Checklist**

github-cli: Update to v2.68.1

---

packages/d/dunst/abi_used_symbols
packages/d/dunst/package.yml
packages/d/dunst/pspec_x86_64.xml

**Summary**
- Changelog [here](https://github.com/dunst-project/dunst/releases/tag/v1.12.2)
**Test Plan**
- See notifications in a Sway session
**Checklist**

dunst: Update to v1.12.2

---

packages/a/appstream-data/package.yml
packages/a/appstream-data/pspec_x86_64.xml

**Summary**
Update Appstream data
**Test Plan**
Build Appstream data from this PR
Open Discover, see that it doesn't break
**Checklist**

appstream-data: Update to v60

---

packages/m/morewaita-icon-theme/package.yml
packages/m/morewaita-icon-theme/pspec_x86_64.xml

**Summary**
Release note can be read [here](https://github.com/somepaulo/MoreWaita/releases/tag/v47.4)
**Test Plan**
Set icon theme
**Checklist**

morewaita-icon-theme: Update to v47.4

---

packages/a/appstream-data/package.yml
packages/a/appstream-data/pspec_x86_64.xml

**Summary**
Update appstream data
**Test Plan**
Opened Discover, searched for Fragments, saw that it is available from Solus.
**Checklist**

appstream-data: Update to v64

---

packages/l/libvips/abi_used_symbols
packages/l/libvips/package.yml
packages/l/libvips/pspec_x86_64.xml

**Summary**
Release notes available [here](https://github.com/libvips/libvips/releases/tag/v8.16.1)
**Test Plan**
Edited a bunch of images using `vips`
**Checklist**

libvips: Update to v8.16.1

---

packages/s/sox_ng/abi_symbols
packages/s/sox_ng/abi_used_libs
packages/s/sox_ng/abi_used_symbols
packages/s/sox_ng/package.yml
packages/s/sox_ng/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://codeberg.org/sox_ng/sox_ng/releases/tag/sox_ng-14.5.1).
**Test Plan**
- Installed checked version.
**Checklist**

sox_ng: Update to v14.5.1

---

packages/s/sdl3/abi_used_symbols
packages/s/sdl3/package.yml
packages/s/sdl3/pspec_x86_64.xml

**Summary**
[3.2.8 changelog](https://github.com/libsdl-org/SDL/releases/tag/release-3.2.8)
[3.2.6 changelog](https://github.com/libsdl-org/SDL/releases/tag/release-3.2.6)
3.2.6 includes fixes and improvements for wayland
**Test Plan**
Run example code and see displayed window.
**Checklist**

sdl3: Update to v3.2.8

---

packages/a/appstream-data/README.md
packages/a/appstream-data/Taskfile.yml

**Summary**
- Add a README describing what `appstream-data` is and how to work with it.
- Add a package-specific `Taskfile.yml` containing automation of the week-to-week drudgery of updating this package.
**Test Plan**
- Follow the directions listed in the README in this PR to update the `appstream-data` package, including use of the new `Taskfile.yml`. Documentation and automation are both under test in this PR.
**Checklist**

[NFC] appstream-data: Add documentation and light automation

---

packages/a/appstream-data/package.yml
packages/a/appstream-data/pspec_x86_64.xml

**Summary**
**Test Plan**
- Build and install the package from this PR.
- Open Discover and search for a package. See that it works.
**Checklist**

appstream-data: Update to v65

---

packages/g/gleam/abi_used_symbols
packages/g/gleam/package.yml
packages/g/gleam/pspec_x86_64.xml

**Summary**
v1.9.1 changelog: https://github.com/gleam-lang/gleam/blob/v1.9.1/CHANGELOG.md#v191---2025-03-10
v1.9.0 article: https://gleam.run/news/hello-echo-hello-git/
**Test Plan**
**Checklist**

gleam: Update to v1.9.1

---

packages/s/snippetexpander/abi_used_symbols
packages/s/snippetexpander/package.yml
packages/s/snippetexpander/pspec_x86_64.xml

**Summary**
Changelog: https://git.sr.ht/~ianmjones/snippetexpander/refs/v1.1.0
**Test Plan**
* Build and install package locally.
* Test main window, adding snippets etc.
* Test search and paste window.
* Test auto expand functionality in compatible app (e.g. LibreOffice Writer)
* Test CLI.
**Checklist**

snippetexpander: Update to v1.1.0

---

packages/g/gthumb/abi_used_symbols
packages/g/gthumb/package.yml
packages/g/gthumb/pspec_x86_64.xml

**Summary**
- Changed homepage
**Test Plan**
**Checklist**

gthumb: change homepage

---

packages/m/mmv/monitoring.yaml
packages/m/mmv/package.yml
packages/m/mmv/pspec_x86_64.xml

**Summary**
- Move `mmv` out of system.base
- Add monitoring.yaml (Part of #4121)
**Test Plan**
**Checklist**

mmv: Move out system.base

---

packages/z/zellij/abi_used_symbols
packages/z/zellij/package.yml
packages/z/zellij/pspec_x86_64.xml

**Summary**
- Patch release for Windows Terminal bug causing jitter and phantom input on mouse events
- Full notes [here](https://github.com/zellij-org/zellij/releases/tag/v0.42.1)
**Test Plan**
- See mouse spam no longer occurs
**Checklist**

zellij: Update to v0.42.1

---

packages/b/brave/package.yml
packages/b/brave/pspec_x86_64.xml

**Summary**
- [Changelog](https://community.brave.com/t/release-channel-1-76-82/607384) 
**Test Plan**
- Open a few websites
**Checklist**

brave: Update to 1.76.82

---

packages/e/eglexternalplatform/package.yml
packages/e/eglexternalplatform/pspec_x86_64.xml

**Summary**
Changes:
- Override the installation directory of the pkg-config file to put it in the correct architecture-independent directory
**Test Plan**
Successfully built all the `egl-` packages
**Checklist**

eglexternalplatform: Update to v1.2.1

---

packages/n/nicotine-plus/package.yml
packages/n/nicotine-plus/pspec_x86_64.xml

**Summary**
See [here](https://github.com/nicotine-plus/nicotine-plus/releases/tag/3.3.10) for changelog. The Nicotine Plus package hasn't been updated 10 months, so this will be it's first update in a while.
**Test Plan**
- Downloaded a file
- Shared folders
- Used chatrooms
**Checklist**

nicotine-plus: Update to v3.3.10

---

packages/f/fluidsynth/abi_symbols
packages/f/fluidsynth/abi_used_symbols
packages/f/fluidsynth/package.yml
packages/f/fluidsynth/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/FluidSynth/fluidsynth/releases/tag/v2.4.4)
**Test Plan**
- Play a MIDI sample from the command-line
**Checklist**

fluidsynth: Update to v2.4.4

---

packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
- Release notes [here](https://sw.kovidgoyal.net/kitty/changelog/#id1)
- Packaging note: Bumped bundled icon font and SIMD library
**Test Plan**
- Run kitty terminal, use some basic commands
**Checklist**

kitty: Update to v0.41.0

---

packages/y/youtube-viewer/package.yml
packages/y/youtube-viewer/pspec_x86_64.xml

**Summary**
Changes:
- Workaround for the `403 Forbidden` issue
- Fixed the `400 Bad Request` issue (caused by YouTube changes)
**Test Plan**
Viewed a bunch of videos using TUI and GUI
**Checklist**

youtube-viewer: Update to v3.11.5

---

packages/s/scrcpy/package.yml
packages/s/scrcpy/pspec_x86_64.xml

**Summary**
Changes:
- Add many audio sources
- Improve/fix camera listing
- Add `--display-ime-policy`
- Allow controls with `--no-window`
- Add workaround for Pico 4 Ultra
- Fix rotation after a recent Android 15 upgrade
- Fix audio capture on Android 16
- Various technical fixes
Full release notes available [here](https://github.com/Genymobile/scrcpy/releases/tag/v3.2)
**Test Plan**
Mirrored and controlled my phone from my PC
**Checklist**

scrcpy: Update to v3.2

---

packages/m/mullvad/package.yml
packages/m/mullvad/pspec_x86_64.xml

**Summary**
- update to latest
- [changelog](https://github.com/mullvad/mullvadvpn-app/releases/tag/2025.5)
**Summary**
Update to last version (2025.5)
**Test Plan**
**Checklist**

mullvad: Update to v2025.5

---

packages/z/zenergy/package.yml
packages/z/zenergy/pspec_x86_64.xml

**Summary**
- remove E from socket and core
- support zen5 and phoenix desktop
**Test Plan**
Install module, observe it still loads, and run sensors
**Checklist**

zenergy: Update to v1.0.1

---

packages/d/deepin-icon-theme/package.yml
packages/d/deepin-icon-theme/pspec_x86_64.xml

**Summary**
**Test Plan**
- Install and switch to deepin icons
**Checklist**

deepin-icon-theme: Update to v2025.03.27

---

packages/z/zotero/package.yml
packages/z/zotero/pspec_x86_64.xml

**Summary**
- Smoother zooming in PDF reader
- Improved performance while downloading large files
- Added undo/redo support in reader
- Fixed PDF blurriness at some zoom levels
- [changelog](https://www.zotero.org/support/changelog)
**Test Plan**
**Checklist**

zotero: Update to 7.0.15

---

packages/l/languagetool/package.yml
packages/l/languagetool/pspec_x86_64.xml

**Summary**
- added and improved rules
- extended dictionary
- [changelog](https://github.com/languagetool-org/languagetool/blob/v6.6/languagetool-standalone/CHANGES.md)
**Test Plan**
- M-x langtool-check; M-x langtool-correct-buffer; M-x langtool-check-done
**Checklist**

languagetool: Update to 6.6

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Fix formatting issue
- Fix unchecked unwraps
- Remove unnecessary `unsafe` blocks
**Test Plan**
**Checklist**

eza: Update to v0.21.0

---

common/Scripts/appstream_ignored_packages.txt
packages/e/eviacam/files/com.crea_si.eviacam.enable_viacam.metainfo.xml
packages/e/eviacam/package.yml
packages/e/eviacam/pspec_x86_64.xml
packages/g/gbml/abi_used_symbols
packages/g/gbml/files/com.gitlab.gaming_backup_multitool_for_linux.metainfo.xml
packages/g/gbml/files/gaming-backup-multitool-linux.desktop
packages/g/gbml/monitoring.yaml
packages/g/gbml/package.yml
packages/g/gbml/pspec_x86_64.xml
packages/g/gcstar/files/io.gitlab.gcstar.gcstar.metainfo.xml
packages/g/gcstar/monitoring.yaml
packages/g/gcstar/package.yml
packages/g/gcstar/pspec_x86_64.xml
packages/g/gprename/files/net.sourceforge.gprename.gprename.metainfo.xml
packages/g/gprename/monitoring.yaml
packages/g/gprename/package.yml
packages/g/gprename/pspec_x86_64.xml

**Summary**
- Add aerc and compiz to ignore                                                                                          
- gprename: Housekeeping                                                                                                                                       
- gcstar: Housekeeping                                                                                                                                         
- gbml: Housekeeping                                                                                                                                           
- eviacam: Add appstream metainfo         
**Test Plan**
`appstream-builder --packages-dir=. --include-failed -v `
**Checklist**

More AppStream metainfo

---

packages/s/shotcut/abi_used_symbols
packages/s/shotcut/package.yml
packages/s/shotcut/pspec_x86_64.xml

**Summary**
- Release notes [here](https://www.shotcut.org/blog/new-release-250329/)
**Test Plan**
- Load a video clip into the timeline
**Checklist**

shotcut: Update to v25.03.29

---

packages/l/less/monitoring.yaml
packages/l/less/package.yml
packages/l/less/pspec_x86_64.xml

**Summary**
- Release notes [here](https://www.greenwoodsoftware.com/less/news.668.html)
**Test Plan**
- Page through some files
**Checklist**

less: Update to v668

---

packages/b/bluefish/abi_symbols
packages/b/bluefish/abi_used_symbols
packages/b/bluefish/package.yml
packages/b/bluefish/pspec_x86_64.xml

**Summary**
- Bluefish 2.2.17 is a maintenance release that has only code cleanup fixes to comply better with modern compiler standards.
**Test Plan**
- Open some text files and edit them
**Checklist**

bluefish: Update to v2.2.17

---

packages/l/libimagequant/package.yml
packages/l/libimagequant/pspec_x86_64.xml

**Summary**
**Test Plan**
- Run tuxpaint, make a terrible drawing
**Checklist**

libimagequant: Update to v4.3.4

---

packages/s/showtime/monitoring.yaml
packages/s/showtime/package.yml
packages/s/showtime/pspec_x86_64.xml

**Summary**
Add showtime at v48.0
**Test Plan**
Play video
**Checklist**

showtime: Add at v48.0

---

packages/o/openrct2/package.yml
packages/o/openrct2/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.21)
**Test Plan**
- Play a scenario for a minute
**Checklist**

openrct2: Update to v0.4.21

---

packages/p/power-profiles-daemon/abi_used_symbols
packages/p/power-profiles-daemon/package.yml
packages/p/power-profiles-daemon/pspec_x86_64.xml

**Summary**
- introduce configurable actions
**Test Plan**
Install on laptop and list actions. Enable them and see if laptop still functions
**Checklist**

power-profiles-daemon: Update to v0.30

---

packages/c/cpu-x/abi_used_libs
packages/c/cpu-x/abi_used_symbols
packages/c/cpu-x/package.yml
packages/c/cpu-x/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/TheTumultuousUnicornOfDarkness/CPU-X/blob/master/ChangeLog.md#v520---2025-03-21)
**Test Plan**
Run cpu-x and see cpu information 
**Checklist**

cpu-x: Update to v5.2.0

---

packages/g/goverlay/package.yml
packages/g/goverlay/pspec_x86_64.xml
packages/m/mangohud/abi_used_symbols
packages/m/mangohud/package.yml
packages/m/mangohud/pspec_x86_64.xml

**Summary**
General bug fixes
**Test Plan**
Run goverlay to see metrics still display. 
**Checklist**

Update Mangohud and Goverlay to latest

---

packages/h/hyprland-protocols/package.yml
packages/h/hyprland-protocols/pspec_x86_64.xml

**Summary**
- A minor release with le new protocol
**Test Plan**
- Launch hyprland session
**Checklist**

hyprland-protocols: Update to v0.6.4

---

packages/d/darkly/monitoring.yaml

**Summary**
**Test Plan**
**Checklist**

[NFC] darkly : Fix monitoring.yaml

---

packages/u/unrar/package.yml
packages/u/unrar/pspec_x86_64.xml

**Summary**
No changelog
**Test Plan**
Extract an archive
**Checklist**

unrar: Update to v7.1.6

---

packages/w/wireless-regdb/package.yml
packages/w/wireless-regdb/pspec_x86_64.xml

**Summary**
Changelog can read [here](https://lore.kernel.org/linux-wireless/Z7b1ww9K1kNUpMaW@wens.tw/)
**Test Plan**
Install package
**Checklist**

wireless-regdb: Update to v2025.02.20

---

packages/t/terminology/abi_used_libs
packages/t/terminology/abi_used_symbols
packages/t/terminology/package.yml
packages/t/terminology/pspec_x86_64.xml

**Summary**
Release note can read [here](https://www.enlightenment.org/news/2025-03-23-terminology-1.14.0)
**Test Plan**
Lauch app, execute a few commands
**Checklist**

terminology: Update to v1.14.0

---

packages/y/yq/MAINTAINERS.md
packages/y/yq/abi_used_symbols
packages/y/yq/package.yml
packages/y/yq/pspec_x86_64.xml

**Summary**
Full release note can read [here](https://raw.githubusercontent.com/mikefarah/yq/refs/tags/v4.45.1/release_notes.txt)
**Test Plan**
Use `yq` as usual
**Checklist**

yq: Update to v4.45.1

---

packages/r/remmina/abi_symbols
packages/r/remmina/abi_used_symbols
packages/r/remmina/package.yml
packages/r/remmina/pspec_x86_64.xml

**Summary**
Full changelog can read [here](https://gitlab.com/Remmina/Remmina/-/raw/rel/v1.4.40/CHANGELOG.md?ref_type=heads)
Resolves getsolus/packages#5382
**Test Plan**
Launch app
**Checklist**

remmina: Update to v1.4.40

---

packages/q/qt5ct/abi_symbols
packages/q/qt5ct/abi_used_symbols
packages/q/qt5ct/package.yml
packages/q/qt5ct/pspec_x86_64.xml

**Summary**
- Reworked color settings
- Fixed issue with app-specific palette
- Fixed compatibility with old Qt versions
- Updated Chinese (Taiwan) translation
- Updated Dutch translation
- Updated Greek translation
- Updated Polish translation
- Updated Russian translation
**Test Plan**
Launch the app, set font type
**Checklist**

qt5ct: Update to v1.9

---

packages/u/up/abi_used_symbols
packages/u/up/package.yml
packages/u/up/pspec_x86_64.xml

**Summary**
Use upstream version number (even if it is dumb)
**Test Plan**
TBD
**Checklist**

up: Fix version number

---

packages/g/gum/abi_used_symbols
packages/g/gum/package.yml
packages/g/gum/pspec_x86_64.xml

**Summary**
Release notes:
- [0.16.0](https://github.com/charmbracelet/gum/releases/tag/v0.16.0)
- [0.15.2](https://github.com/charmbracelet/gum/releases/tag/v0.15.2)
- [0.15.1](https://github.com/charmbracelet/gum/releases/tag/v0.15.1)
- [0.15.0](https://github.com/charmbracelet/gum/releases/tag/v0.15.0)
**Test Plan**
Use `go-task infra:build-pr `
**Checklist**

gum: Update to v0.16.0

---

packages/g/gzdoom/MAINTAINERS.md
packages/g/gzdoom/package.yml
packages/g/gzdoom/pspec_x86_64.xml

**Summary**
Release note can read [here](https://github.com/ZDoom/gzdoom/releases/tag/g4.14.1)
**Test Plan**
Play the first level
**Checklist**

gzdoom: Update to v4.14.1

---

packages/d/diffoscope/package.yml
packages/d/diffoscope/pspec_x86_64.xml

**Summary**
Full changelog can be read [here](https://salsa.debian.org/reproducible-builds/diffoscope/-/raw/293/debian/changelog?ref_type=tags)
**Test Plan**
Compare eopkg(s) archive
**Checklist**

diffoscope: Update to v293

---

packages/b/broot/abi_used_symbols
packages/b/broot/package.yml
packages/b/broot/pspec_x86_64.xml

**Summary**
Full changelog can read [here](https://github.com/Canop/broot/blob/v1.45.1/CHANGELOG.md)
**Test Plan**
Check directories
**Checklist**

broot: Update to v1.45.1

---

packages/c/claws-mail/abi_symbols
packages/c/claws-mail/abi_used_symbols
packages/c/claws-mail/package.yml
packages/c/claws-mail/pspec_x86_64.xml

**Summary**
Full changelog can read [here](https://git.claws-mail.org/?p=claws.git;a=blob_plain;f=NEWS;hb=refs/tags/4.3.1)
**Test Plan**
Set up an account and fetch email
**Checklist**

claws-mail: Update to v4.3.1

---

packages/b/black-hole-solver/abi_used_symbols
packages/b/black-hole-solver/package.yml
packages/b/black-hole-solver/pspec_x86_64.xml

**Summary**
- Fixed running `black_hole_solver_run` with the same (or a smaller) iterations limit.  It ran indefinetely then (Possible Denial-of-service?)
- Fix some hypothetical resource leaks (e.g.: with `fopen()`).
- Cleanups: add `const`s , convert `int` to `bool`, etc.
- Add tests.
**Test Plan**
Launch `kpat` and play a game
**Checklist**

black-hole-solver: Update to v1.14.0

---

packages/x/xiphos/package.yml
packages/x/xiphos/pspec_x86_64.xml

**Summary**
- Corrected a GTK signal error.
- Updated FR + IT manuals for recent key sequence additions.
- Much better fix to replace previous 1st time user mod.mgr flaw.
**Test Plan**
- Read a verse.
**Checklist**

xiphos: Update to v4.3.2

---

packages/a/adw-gtk3-theme/package.yml
packages/a/adw-gtk3-theme/pspec_x86_64.xml

**Summary**
Changelogs:
- [5.8](https://github.com/lassekongo83/adw-gtk3/releases/tag/v5.8)
- [5.7](https://github.com/lassekongo83/adw-gtk3/releases/tag/v5.7)
**Test Plan**
Apply theme on Gnome
**Checklist**

adw-gtk3-theme: Update to v5.8

---

packages/t/typos/abi_used_libs
packages/t/typos/abi_used_symbols
packages/t/typos/package.yml
packages/t/typos/pspec_x86_64.xml

**Summary**
- update to latest
- changelogs is available [here](https://github.com/crate-ci/typos/releases)
**Test Plan**
Test the new options.
**Checklist**

typos: Update to v1.31.1

---

packages/c/crun/abi_symbols
packages/c/crun/abi_used_symbols
packages/c/crun/package.yml
packages/c/crun/pspec_x86_64.xml

**Summary**
- Update to latest
- Release notes [here](https://github.com/containers/crun/releases)
**Test Plan**
Create new container using distrobox
**Checklist**

crun: Update to v1.21

---

packages/a/appstream-data/package.yml
packages/a/appstream-data/pspec_x86_64.xml

**Summary**
**Summary**
**Test Plan**
Open Discover, search for Showtime, see that it is available from the Solus repository.
**Checklist**

appstream-data: Update to v70

---

packages/p/polybar/abi_used_symbols
packages/p/polybar/package.yml
packages/p/polybar/pspec_x86_64.xml

**Summary**
Release note can read [here](https://github.com/polybar/polybar/releases/tag/3.7.2)
**Test Plan**
Launch polybar
**Checklist**

polybar: Update to v3.7.2

---

packages/y/yquake2/MAINTAINERS.md
packages/y/yquake2/abi_used_symbols
packages/y/yquake2/package.yml
packages/y/yquake2/pspec_x86_64.xml

**Summary**
Full changelog can read [here](https://raw.githubusercontent.com/yquake2/yquake2/refs/tags/QUAKE2_8_50/CHANGELOG)
**Test Plan**
Play a short session of Quake II
**Checklist**

yquake2: Update to v8.5.0

---

packages/p/pcsc-tools/package.yml
packages/p/pcsc-tools/pspec_x86_64.xml

**Summary**
Full release note can be found [here](https://github.com/LudovicRousseau/pcsc-tools/releases/tag/1.7.3)
**Test Plan**
Launch gscriptor
**Checklist**

pcsc-tools: Update to v1.7.3

---

packages/p/ptex/abi_used_symbols
packages/p/ptex/package.yml
packages/p/ptex/pspec_x86_64.xml

**Summary**
[Changelog](https://github.com/wdas/ptex/compare/v2.4.2...v2.4.3)
**Test Plan**
Rebuild `openimageio` locally
**Checklist**

ptex: Update to v2.4.3

---

common/CI/config.yaml

**Summary**
Remove `libadwaita` from ignore list

common/CI : Remove libadwaita from ignore list

---

packages/o/onefetch/abi_used_symbols
packages/o/onefetch/package.yml
packages/o/onefetch/pspec_x86_64.xml

**Summary**
- add language support for Lean
- add language support for Typst
- add language support for Razor
**Test Plan**
- Run onefetch on the packages repo
**Checklist**

onefetch: Update to v2.24.0

---

packages/l/lazygit/package.yml
packages/l/lazygit/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/jesseduffield/lazygit/releases/tag/v0.49.0)
**Test Plan**
- Create this commit and push it
**Checklist**

lazygit: Update to v0.49.0

---

packages/b/blender/package.yml
packages/b/blender/pspec_x86_64.xml

**Summary**
- Release notes [here](https://developer.blender.org/docs/release_notes/4.4/corrective_releases/#blender-441)
**Test Plan**
- Render a cube
**Checklist**

blender: Update to v4.4.1

---

packages/a/appstream-data/package.yml
packages/a/appstream-data/pspec_x86_64.xml

**Test Plan**
- See screenshots for localsend
**Checklist**

appstream-data: Update to v72

---

packages/g/gleam/package.yml
packages/g/gleam/pspec_x86_64.xml

**Summary**
v1.10.0 article: https://gleam.run/news/global-rename-and-find-references/
**Test Plan**
**Checklist**

gleam: Update to v1.10.0

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- [changelog](https://tailscale.com/changelog#2025-04-17-client)
**Test Plan**
- tailscale status; tailscale netcheck
**Checklist**

tailscale: Update to 1.82.5

---

packages/m/mu/package.yml
packages/m/mu/pspec_x86_64.xml

**Summary**
- show information about how the server interpreted last query
- new "transient" menu provides access to common functions in mu4e
- gnus mailing-list management command now also work in mu4e
- cleanup after indexing has been sped up significantly
- updated documentation
**Test Plan**
- search for and view message
**Checklist**

mu: Update to 1.12.9

---

packages/k/keepass/package.yml
packages/k/keepass/pspec_x86_64.xml

**Summary**
Release notes available [here](https://keepass.info/news/n250304_2.58.html)
**Test Plan**
- Opened my password database
- Created a new entry
- Let `keepass` perform Auto-Type
**Checklist**

keepass: Update to v2.58

---

packages/g/gdb/abi_used_symbols
packages/g/gdb/package.yml
packages/g/gdb/pspec_x86_64.xml

**Summary**
Release notes:
- [16.1](https://sourceware.org/pipermail/gdb-announce/2025/000143.html)
- [16.2](https://sourceware.org/pipermail/gdb-announce/2025/000144.html)
**Test Plan**
- Started a simple C program with `gdb` and stepped through it
- Attached `gdb` to an already running process
- Printed a stack trace with `gstack`
**Checklist**

gdb: Update to v16.2

---

packages/z/zenergy/package.yml
packages/z/zenergy/pspec_x86_64.xml

**Summary**
- restore E from socket and core
**Test Plan**
Run goverlay and ensure power usage shows on 5800x3d
**Checklist**

zenergy: Update to v1.0.2

---

packages/q/qpdf/abi_symbols
packages/q/qpdf/abi_used_symbols
packages/q/qpdf/package.yml
packages/q/qpdf/pspec_x86_64.xml

**Summary**
Release note can read [here](https://qpdf.readthedocs.io/en/11.10/release-notes.html)
**Test Plan**
Try a few command line arguments
**Checklist**

qpdf: Update to v11.10.1

---

packages/y/youtube-viewer/package.yml
packages/y/youtube-viewer/pspec_x86_64.xml

**Summary**
Changes:
- Bug-fix: when there are multiple audio tracks, select the default one
**Test Plan**
Searched and played several videos using CLI and GUI
**Checklist**

youtube-viewer: Update to v3.11.6

---

packages/d/dolphin-emu/package.yml
packages/d/dolphin-emu/pspec_x86_64.xml

**Summary**
Hotfix release
Release notes available [here](https://fosstodon.org/@dolphin@dolphin-emu.org/114377878898703798)
**Test Plan**
- Played a Gamecube game
- Changed controller settings
- Changed graphics settings
**Checklist**

dolphin-emu: Update to v2503a

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Add icon for '.stowrc' files
- Performance: Use a hashmap when possible for file extension matching
**Test Plan**
**Checklist**

eza: Update to v0.21.2

---

packages/l/libgtkmm-2/abi_used_symbols
packages/l/libgtkmm-2/package.yml
packages/l/libgtkmm-2/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

libgtkmm-2: change homepage

---

packages/t/tickrs/package.yml
packages/t/tickrs/pspec_x86_64.xml

**Summary**
- User agent added to fix failing yahoo finance API requests
**Test Plan**
- run TUI; check results
**Checklist**

tickrs: Update to 0.14.11

---

packages/h/hunspell-uk/package.yml
packages/h/hunspell-uk/pspec_x86_64.xml

**Summary**
- Update dictionary with latest language corpus
**Test Plan**
- M-x flyspell-buffer
- M-x flyspell-goto-next-error
- M-x flyspell-correct-at-point
**Checklist**

hunspell-uk: Update to 6.6.1

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v33.2.2/CHANGELOG.md#3322)
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 33.2.2

---

packages/n/neovim/abi_symbols
packages/n/neovim/package.yml
packages/n/neovim/pspec_x86_64.xml

**Summary**
No changelog available.
**Test Plan**
Edit a file with `nvim`.
**Checklist**

neovim: Update to v0.11.1

---

packages/s/starship/abi_used_symbols
packages/s/starship/package.yml
packages/s/starship/pspec_x86_64.xml

**Summary**
- Add network namespace module
- Add support for pixi
- c++: adding c++ module
- completions: Offer Nushell completions
- nodejs: disable if bun project files detected
- python: add support for `python_binary` arguments in config
- battery: prefer charge ratio over current capacity
- Change to a non-yanked version of the log crate
**Test Plan**
Start a new terminal session using Starship.
**Checklist**

starship: Update to v1.23.0

---

packages/u/upower/package.yml
packages/u/upower/pspec_x86_64.xml

**Summary**
- Fix for unstable onbattery status on laptops
**Test Plan**
Install on framework laptop
**Checklist**

upower: Update to v1.90.9

---

packages/b/bluez/package.yml
packages/b/bluez/pspec_x86_64.xml

**Summary**
- Use https for homepage
**Test Plan**
Make sure pspec file has new homepage
**Checklist**
Part of https://github.com/getsolus/packages/issues/5522

bluez: Use https url

---

packages/y/yaru-theme/package.yml
packages/y/yaru-theme/pspec_x86_64.xml

**Summary**
Changelog available [here](https://raw.githubusercontent.com/ubuntu/yaru/refs/tags/25.04.2-0ubuntu1/debian/changelog)
**Test Plan**
- Switched to a bunch of different gtk themes and looked at my windows/menu
- Switched to the icon theme and looked at my app icons
**Checklist**

yaru-theme: Update to v25.04.2

---

packages/s/surfn-icon-theme/monitoring.yaml
packages/s/surfn-icon-theme/package.yml

**Summary**
No changelog available
New themes:
- Surfn Numixs
- Surfn Qogir
**Test Plan**
Switched to a bunch of the different icon themes and looked at my app icons
**Checklist**

surfn-icon-theme: Update to v25.04.01 and add monitoring.yaml

---

packages/w/wmenu/abi_used_symbols
packages/w/wmenu/package.yml
packages/w/wmenu/pspec_x86_64.xml

**Summary**
**Test Plan**
- Launch some apps in a wayland session
**Checklist**

wmenu: Update to v0.2.0

---

packages/b/bleachbit/package.yml
packages/b/bleachbit/pspec_x86_64.xml

**Summary**
- Release notes [here](https://www.bleachbit.org/news/bleachbit-500)
**Test Plan**
- Use bleachbit to empty trash
**Checklist**

bleachbit: Update to v5.0.0

---

packages/l/libpeas-2/package.yml
packages/l/libpeas-2/pspec_x86_64.xml

**Summary**
- Generate VAPI bindings for Vala
**Test Plan**
Try to port Budgie to libpeas-2. Do not ask.
**Checklist**

libpeas-2: Generate VAPI bindings for Vala

---

packages/o/openrct2/abi_used_symbols
packages/o/openrct2/package.yml
packages/o/openrct2/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.22)
**Test Plan**
- Play a new scenario
**Checklist**

openrct2: Update to v0.4.22

---

packages/b/blender/package.yml
packages/b/blender/pspec_x86_64.xml

**Summary**
- Bug fix: Crashing in compositor
**Test Plan**
- Render a scene
**Checklist**

blender: Update to v4.4.3

---

packages/h/hplip/abi_symbols
packages/h/hplip/abi_used_symbols
packages/h/hplip/files/hplip-hpaio-gcc14.patch
packages/h/hplip/files/hplip-pserror-gcc14.patch
packages/h/hplip/files/hplip.metainfo.xml
packages/h/hplip/files/python3.patch
packages/h/hplip/files/series
packages/h/hplip/package.yml
packages/h/hplip/pspec_x86_64.xml

**Summary**
Fix build
Resolves getsolus/packages#3639
**Test Plan**
No testing has been performed.
**Checklist**

hplip: Fix build and metainfo

---

packages/s/syncthing/package.yml
packages/s/syncthing/pspec_x86_64.xml

**Summary**
Bugfixes & enhancements
**Test Plan**
- Restart Syncthing-GTK, use it to restart syncthing, verify all folders sync
**Checklist**

syncthing: Update to v1.29.6

---

packages/py/python-pyotherside/abi_used_symbols
packages/py/python-pyotherside/monitoring.yaml
packages/py/python-pyotherside/package.yml
packages/py/python-pyotherside/pspec_x86_64.xml

**Summary**
Changelog can be read [here](https://github.com/thp/pyotherside/blob/1.6.2/docs/index.rst#changelog)
**Test Plan**
TBD
**Checklist**

python-pyotherside: Update to v1.6.2

---

packages/f/fontforge/abi_used_symbols
packages/f/fontforge/files/0001-Fix-errors-in-French-and-Italian-translations.patch
packages/f/fontforge/files/Fix_Splinefont_shell_invocation.patch
packages/f/fontforge/monitoring.yaml
packages/f/fontforge/package.yml
packages/f/fontforge/pspec_x86_64.xml

**Summary**
Fix build.
**Test Plan**
Open the main window.
**Checklist**

fontforge: Fix build

---

packages/e/eqy/README.md
packages/s/sby/README.md
packages/y/yosys/MAINTAINERS.md
packages/y/yosys/README.md

- Add READMEs to yosys, eqy, and sby indicating that their versions should be synchronized
- Add a MAINTAINTERS.md to yosys

[NFC] Add READMEs to packages synchronized with yosys

---

packages/a/appstream-data/package.yml
packages/a/appstream-data/pspec_x86_64.xml

**Summary**
**Test Plan**
Search for an application in Discover.
**Checklist**

appstream-data: Update to v73

---

packages/h/hwdata/package.yml
packages/h/hwdata/pspec_x86_64.xml

**Summary**
- Update pci, usb and vendor ids
**Test Plan**
- Installed. Nothing interesting happened
**Checklist**

hwdata: Update to v0.395

---

packages/h/hplip/files/0001-device_type-edge-handling-for-NoneType.patch
packages/h/hplip/files/series
packages/h/hplip/package.yml
packages/h/hplip/pspec_x86_64.xml

**Summary**
Update hplip to v3.25.2
**Test Plan**
Testing performed by TraceyC
**Checklist**

hplip: Update to v3.25.2

---

packages/r/rmlint/abi_used_symbols
packages/r/rmlint/monitoring.yaml
packages/r/rmlint/package.yml
packages/r/rmlint/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/sahib/rmlint/releases/tag/v2.10.3).
**Test Plan**
Ran `rmlint`, inspected the output files.
**Checklist**

rmlint: Update to v2.10.3

---

packages/s/sqlite3/package.yml
packages/s/sqlite3/pspec_x86_64.xml

**Summary**
- Update to latest
- Changelog located [here](https://www.sqlite.org/releaselog/3_49_2.html)
- general bug fixes
**Test Plan**
Run python sqlite3 example; verify db is created and commands executed
**Checklist**

sqlite3: Update to v3.49.2

---

packages/p/pinta/monitoring.yaml
packages/p/pinta/package.yml
packages/p/pinta/pspec_x86_64.xml

**Summary**
- Move to GTK4/libadwaita (required for 3.0+)
- Release notes [here](https://github.com/PintaProject/Pinta/releases/tag/3.0)
- Related to https://github.com/getsolus/packages/issues/5599
**Test Plan**
- Make a doodle
**Checklist**

pinta: Update to v3.0

---

packages/e/eza/abi_used_symbols
packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Add support for .ipynb file icons
**Test Plan**
**Checklist**

eza: Update to v0.21.3

---

packages/w/weechat/abi_used_symbols
packages/w/weechat/package.yml
packages/w/weechat/pspec_x86_64.xml

**Summary**
- core: fix integer overflow with decimal numbers in calculation of expression
- core: fix integer overflow in base32 encoding/decoding
- core: fix integer overflow in function util_version_number
- core: fix buffer overflow in function util_parse_time
- core: fix buffer overflow in function eval_syntax_highlight_colorize
- core: fix buffer overflow in function eval_string_base_encode
- core: fix buffer overflow in function eval_string_range_chars
- core: fix memory leak in function util_parse_delay
**Test Plan**
**Checklist**

weechat: Update to v4.6.3

---

packages/m/mlt/abi_symbols
packages/m/mlt/abi_used_symbols
packages/m/mlt/package.yml
packages/m/mlt/pspec_x86_64.xml
packages/s/shotcut/abi_used_symbols
packages/s/shotcut/package.yml
packages/s/shotcut/pspec_x86_64.xml

**Summary**
- Update mlt
- Update shotcut
**Test Plan**
- Add a video to the timeline
**Checklist**

Shotcut: Update to 2025.05.11

---

packages/py/python-maturin/abi_used_symbols
packages/py/python-maturin/package.yml
packages/py/python-maturin/pspec_x86_64.xml
packages/py/python-setuptools-rust/package.yml
packages/py/python-setuptools-rust/pspec_x86_64.xml

**Summary**
- Update `python-setuptools-rust` to 1.11.1
- Update `python-maturin` to 1.8.6
Changelogs in the commit messages
**Test Plan**
- Successfully built `python-maturin`
- Successfully built `python-orjson`
**Checklist**

Update python-setuptools-rust and python-maturin

---

repo_data/distribution.xml
repo_data/distribution.xml.in

**Summary**
Was renamed [here](https://github.com/getsolus/packages/pull/5654) to steam-devices
**Test Plan**
n/a
**Checklist**

repo_data: Deprecate steam-udev-rules

---

common/Scripts/get-font-providers.sh

**Summary**
Adds a script to get font provides for a font package
**Test Plan**
17f35f4a5f77cf9488b01d666e0ea8781603e921
826ebf5add909ca0fd97c556565a41b90e1deed9
**Checklist**

common/Scripts: Add script to get font provides for appstream metainfo

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
Full changelog available [here](https://github.com/cli/cli/releases/tag/v2.73.0).
**Test Plan**
**Checklist**

github-cli: Update to v2.73.0

---

packages/k/keybase/abi_used_symbols
packages/k/keybase/package.yml
packages/k/keybase/pspec_x86_64.xml

**Summary**
Changes:
- Fix team deletion not working
**Test Plan**
- Sent a message
- Encrypted and decrypted a file
- Checked my wallet balance
**Checklist**

keybase: Update to v6.5.1

---

packages/py/python3-urwid/package.yml
packages/py/python3-urwid/pspec_x86_64.xml
packages/s/s-tui/MAINTAINERS.md
packages/s/s-tui/monitoring.yaml
packages/s/s-tui/package.yml
packages/s/s-tui/pspec_x86_64.xml

**Summary**
- Release note can read [here](https://github.com/amanusk/s-tui/releases/tag/v1.2.0)
Resolves #5664 
**Test Plan**
**Checklist**

s-tui: Update to v1.2.0

---

packages/s/s-tui/files/use-zenergy.patch
packages/s/s-tui/package.yml
packages/s/s-tui/pspec_x86_64.xml

**Summary**
- add stress-ng as dependency
- patch to use zenergy driver
**Test Plan**
Execute s-tui as root and see new power section
**Checklist**

s-tui: Add missing dep, patch to use zenergy

---

packages/a/appstream-data/package.yml
packages/a/appstream-data/pspec_x86_64.xml

**Summary**
**Test Plan**
- Build the package from this PR.
- Install it.
- Make sure Discover can still see packages. Search specifically for KDE Connect and QTractor, as those had metainfo changes explicitly mentioned in commits.
**Checklist**

appstream-data: Update to v74

---

packages/a/antidote/MAINTAINERS.md
packages/a/antidote/package.yml
packages/a/antidote/pspec_x86_64.xml

**Summary**
- [antidote-script] Add double quote to file path on script
**Test Plan**
- Loaded some plugins.
**Checklist**
- Removed myself as maintainer as I am not using this anymore.

antidote: Update to v1.9.10

---

packages/p/pdfarranger/monitoring.yaml
packages/p/pdfarranger/package.yml
packages/p/pdfarranger/pspec_x86_64.xml

**Summary**
Release note can read [here](https://github.com/pdfarranger/pdfarranger/releases/tag/1.12.0)
**Test Plan**
Open a pdf file and extract some pages as image
**Checklist**

pdfarranger: Update to v1.12.0

---

packages/c/caprice32/abi_used_symbols
packages/c/caprice32/files/0001-Add-missing-include.patch
packages/c/caprice32/files/caprice32.desktop
packages/c/caprice32/monitoring.yaml
packages/c/caprice32/package.yml
packages/c/caprice32/pspec_x86_64.xml

**Summary**
- Fix build
- Fix metainfo
**Test Plan**
Run `appstreamcli compose install/ --media-dir=media --media-baseurl=localhost:8000 --verbose`
**Checklist**

caprice32: Fix build and housekeeping

---

packages/b/bzr/abi_used_libs
packages/b/bzr/abi_used_symbols
packages/b/bzr/monitoring.yaml
packages/b/bzr/package.yml
packages/b/bzr/pspec_x86_64.xml

**Summary**
- Update homepage
**Test Plan**
**Checklist**

bzr: update homepage

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Escape spaces in file path to make them work correctly
- List inside working dir with `--list-dirs` and no path passed
- Add swift icon for *.xcplayground
- Add dropbox icon
**Test Plan**
**Checklist**

eza: Update to v0.21.4

---

packages/a/appstream-catalog/README.md
packages/a/appstream-catalog/package.yml
packages/a/appstream-catalog/pspec_x86_64.xml

**Summary**
Update Appstream Catalog
**Test Plan**
Open Discover and see that packages are shown.
**Checklist**

appstream-catalog: Update to latest catalog

---

packages/c/cmatrix/abi_used_symbols
packages/c/cmatrix/monitoring.yaml
packages/c/cmatrix/package.yml
packages/c/cmatrix/pspec_x86_64.xml

**Summary**
- Update homepage
- Update license
**Test Plan**
- Checked homepage and license was updated.
**Checklist**

cmatrix: packaging fixes

---

packages/o/obs-studio/abi_used_symbols
packages/o/obs-studio/files/add_missing_include.patch
packages/o/obs-studio/package.yml
packages/o/obs-studio/pspec_x86_64.xml

**Summary**
- Fix build with libstdc++ 15
**Test Plan**
- TBD
**Checklist**

obs-studio: Fix build with libstdc++ 15

---

packages/u/usbutils/abi_used_symbols
packages/u/usbutils/files/usbreset.patch
packages/u/usbutils/package.yml
packages/u/usbutils/pspec_x86_64.xml

**Summary**
Full changelog can read [here](https://raw.githubusercontent.com/gregkh/usbutils/refs/tags/v018/NEWS)
**Test Plan**
Run a few commands and make sure it works as expected
**Checklist**

usbutils: Update to v018

---

packages/c/cereal/package.yml
packages/c/cereal/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

cereal: change homepage

---

packages/r/rebar3/package.yml
packages/r/rebar3/pspec_x86_64.xml

**Summary**
Changelog: https://github.com/erlang/rebar3/releases/tag/3.25.0
**Test Plan**
* Created new project with `new` command.
* Compiled new project.
* Compiled existing project.
**Checklist**

rebar3: Update to v3.25.0

---

packages/g/gleam/abi_used_symbols
packages/g/gleam/package.yml
packages/g/gleam/pspec_x86_64.xml

**Summary**
Changelog: https://github.com/gleam-lang/gleam/blob/v1.11.0/CHANGELOG.md
Article: https://gleam.run/news/gleam-javascript-gets-30-percent-faster/
**Test Plan**
**Checklist**

gleam: Update to v1.11.0

---

packages/c/caja/abi_used_symbols
packages/c/caja/monitoring.yaml
packages/c/caja/package.yml
packages/c/caja/pspec_x86_64.xml

**Summary**
- Fix appstream data filename
**Test Plan**
See that the appstream data file has the correct name.
**Checklist**

caja: Fix appstream data filename

---

packages/g/gleam/package.yml
packages/g/gleam/pspec_x86_64.xml

**Summary**
Changelog: https://github.com/gleam-lang/gleam/blob/v1.11.1/CHANGELOG.md
**Test Plan**
**Checklist**

gleam: Update to v1.11.1

---

packages/s/spirv-cross/package.yml
packages/s/spirv-cross/pspec_x86_64.xml

**Summary**
Ref: https://github.com/getsolus/packages/pull/5764
**Test Plan**
- Built with tests passed
**Checklist**

spirv-cross: Remove python-nose, not needed

---

packages/b/borg/package.yml
packages/b/borg/pspec_x86_64.xml

**Summary**
- Fix tests
- Add Fish shell completions
**Test Plan**
**Checklist**

borg: Fix tests

---

packages/r/rdflib/monitoring.yaml
packages/r/rdflib/package.yml
packages/r/rdflib/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/RDFLib/rdflib/blob/7.1.4/CHANGELOG.md).
**Test Plan**
Build `lv2` against this version.
**Checklist**

rdflib: Update to v7.1.4

---

packages/c/cura/monitoring.yaml
packages/c/cura/package.yml
packages/c/cura/pspec_x86_64.xml
packages/py/python-uranium/files/Uranium-5.6.0-importlib.patch
packages/py/python-uranium/files/Uranium-5.6.0-pytest8.patch
packages/py/python-uranium/package.yml
packages/py/python-uranium/pspec_x86_64.xml

**Summary**
- **python-uranium: Add patch for Python 3.12**
- **cura: Re-enable tests**
**Test Plan**
See that the tests pass during build.
**Checklist**

cura fix ftbfs

---

packages/i/ibus-hangul/monitoring.yaml
packages/i/ibus-hangul/package.yml
packages/i/ibus-hangul/pspec_x86_64.xml

**Summary**
- Fix license
**Test Plan**
- Checked homepage and license was fixed.
**Checklist**

ibus-hangul: housekeeping

---

packages/py/pygraphviz/package.yml
packages/py/pygraphviz/pspec_x86_64.xml

**Summary**
- Fix build tests
**Test Plan**
See that the test suite passed during build.
**Checklist**

pygraphviz: Fix tests

---

packages/o/onionshare-cli/package.yml
packages/o/onionshare-cli/pspec_x86_64.xml
packages/py/python-engineio/monitoring.yaml
packages/py/python-engineio/package.yml
packages/py/python-engineio/pspec_x86_64.xml
packages/py/python-flask-socketio/package.yml
packages/py/python-flask-socketio/pspec_x86_64.xml
packages/py/python-simple-websocket/files/remove-net-access-requirement-in-tests.patch
packages/py/python-simple-websocket/package.yml
packages/py/python-simple-websocket/pspec_x86_64.xml
packages/py/python-socketio/package.yml
packages/py/python-socketio/pspec_x86_64.xml

**Summary**
Enable a bunch of test suites, and fix dependencies so everything works.
**Test Plan**
See that all tests pass, and run `onionshare-cli --help`.
**Checklist**

onionshare cli fix tests

---

packages/f/flask-cors/package.yml
packages/f/flask-cors/pspec_x86_64.xml

**Summary**
Changes:
- Invert regex sorting to make it correctly match the intent (sorting by specificity descending)
- Fix README file extension in pyproject.toml
**Test Plan**
Ran some examples from the project's documentation
**Checklist**

flask-cors: Update to v6.0.1

---

packages/u/unrar/abi_used_symbols
packages/u/unrar/package.yml
packages/u/unrar/pspec_x86_64.xml

**Summary**
**Test Plan**
- Un-archive a [sample file.](https://getsamplefiles.com/sample-archive-files/rar)
**Checklist**

unrar: Update to v7.1.7

---

packages/p/pinta/package.yml
packages/p/pinta/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/PintaProject/Pinta/releases/tag/3.0.1)
**Test Plan**
- Draw something
**Checklist**

pinta: Update to v3.0.1

---

packages/o/opensnitch/package.yml
packages/o/opensnitch/pspec_x86_64.xml

**Summary**
Test files were never removed due to hardcoding the path and removing a nonexistent dir.
**Test Plan**
verify the test dir is removed in pspec
**Checklist**

opensnitch: Remove test files

---

packages/py/python-astroid/package.yml
packages/py/python-astroid/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/pylint-dev/astroid/blob/v3.3.10/ChangeLog).
**Test Plan**
Run `pylint` on the `ypkg` source repository. Pretend I didn't see all of the problems it highlighted.
**Checklist**

python-astroid: Update to v3.3.10

---

packages/a/alacritty/package.yml
packages/a/alacritty/pspec_x86_64.xml

**Summary**
- Use cargo macro instead of make
- Add more comments
**Test Plan**
TBD
**Checklist**

alacritty: Housekeeping

---

packages/v/variety/package.yml
packages/v/variety/pspec_x86_64.xml

**Summary**
- Fix crash on start (https://github.com/getsolus/packages/issues/5824)
**Test Plan**
Start Variety and see that it does not crash.
**Checklist**

variety: Fix crash on start

---

repo_data/components.xml
repo_data/components.xml.in

**Summary**
All the hyprland packages use this component but it doesn't technically exist yet
**Checklist**

repo_data: Add desktop.hyprland component

---

packages/v/vim/abi_used_symbols
packages/v/vim/package.yml
packages/v/vim/pspec_x86_64.xml

**Summary**
Rebuild against python 3.12
**Test Plan**
TBD
**Checklist**

vim: Rebuild against python 3.12

---

packages/r/rawtherapee/abi_used_symbols
packages/r/rawtherapee/package.yml
packages/r/rawtherapee/pspec_x86_64.xml

**Summary**
- Release notes [here](https://rawtherapee.com/downloads/5.12/)
**Test Plan**
- Open a RAW image
**Checklist**

rawtherapee: Update to v5.12

---

packages/py/python-discid/package.yml
packages/py/python-discid/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-discid: Fix tests

---

packages/py/python-future/files/test_ftp.patch
packages/py/python-future/package.yml
packages/py/python-future/pspec_x86_64.xml

**Summary**
- Fix tests
**Test Plan**
**Checklist**

python-future: Fix tests

---

packages/n/nautilus-open-any-terminal/monitoring.yaml
packages/n/nautilus-open-any-terminal/package.yml
packages/n/nautilus-open-any-terminal/pspec_x86_64.xml

**Summary**
- Resolves https://github.com/getsolus/packages/issues/5357
**Test Plan**
- Changed terminal.
**Checklist**

nautilus-open-any-terminal: Add at v0.6.1

---

packages/py/python-seaborn/package.yml
packages/py/python-seaborn/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-seaborn: Fix tests

---

packages/py/python-pyhamcrest/files/248.patch
packages/py/python-pyhamcrest/package.yml
packages/py/python-pyhamcrest/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

python-pyhamcrest: Fix tests

---

packages/i/iperf/abi_symbols
packages/i/iperf/abi_used_symbols
packages/i/iperf/monitoring.yaml
packages/i/iperf/package.yml
packages/i/iperf/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/esnet/iperf/releases/tag/3.19).
**Test Plan**
- iperf3 -c speedtest.kamel.network
**Checklist**

iperf: Update to v3.19

---

common/CI/config.yaml

**Summary**
Follow up #5760 
**Test Plan**
**Checklist**

CI/config.yaml: Add packages from vulkan stack 

---

packages/j/jasper/abi_used_symbols
packages/j/jasper/package.yml
packages/j/jasper/pspec_x86_64.xml

**Summary**
- Made a change to a configuration header file in order to avoid undesirable compiler warnings when JasPer is used in C++ code
**Test Plan**
- jasper --input test.jpg --output test.jp2 --output-format jp2
**Checklist**

jasper: Update to v4.2.5

---

packages/s/soundconverter/monitoring.yaml
packages/s/soundconverter/package.yml
packages/s/soundconverter/pspec_x86_64.xml

**Summary**
- appdata: Update appdata
- Add tag to appdata
- Add WMA output
- Try to copy mtime, even if file properties copy didn't work
Full changelog can read [here](https://github.com/kassoulet/soundconverter/compare/4.0.4...4.0.6)
**Test Plan**
Launch app and convert some mp3
**Checklist**

soundconverter: Update to v4.0.6

---

packages/s/safeeyes/monitoring.yaml
packages/s/safeeyes/package.yml
packages/s/safeeyes/pspec_x86_64.xml

**Summary**
Full changelog can read [here](https://github.com/slgobinath/SafeEyes/blob/v2.2.3/debian/changelog)
**Test Plan**
Launch app form terminal
**Checklist**

safeeyes: Update to v2.2.3

---

packages/f/font-noto-emoji/package.yml
packages/f/font-noto-emoji/pspec_x86_64.xml

**Summary**
Changes:
- Update the Syrian flag
**Test Plan**
Pasted the Syrian flag emoji into LibreOffice and confirmed it used the updated one
**Checklist**

font-noto-emoji: Update to v2.048

---

packages/e/eza/abi_used_symbols
packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Fix excessive open file descriptors
- Implement desirable behaviour for unreadables
- Unreadables format style
**Test Plan**
**Checklist**

eza: Update to v0.21.5

---

packages/f/freeciv/abi_used_symbols
packages/f/freeciv/package.yml
packages/f/freeciv/pspec_x86_64.xml

**Summary**
Release notes available [here](https://freeciv.fandom.com/wiki/NEWS-3.1.5)
**Test Plan**
Played a few rounds of a new game against AI
**Checklist**

freeciv: Update to v3.1.5

---

packages/l/lollypop/package.yml
packages/l/lollypop/pspec_x86_64.xml

**Summary**
Changes:
- Fix a label length
**Test Plan**
Browsed through my music library and played a bunch of tracks
**Checklist**

lollypop: Update to v1.4.42

---

packages/u/unrar/package.yml
packages/u/unrar/pspec_x86_64.xml

**Summary**
**Test Plan**
- Use test files from [here](https://getsamplefiles.com/sample-archive-files/rar)
**Checklist**

unrar: Update to v7.1.8

---

packages/s/smplayer/abi_used_symbols
packages/s/smplayer/package.yml
packages/s/smplayer/pspec_x86_64.xml

**Summary**
Changes:
- Fix play/pause button.
- Some fixes to stop the screensaver on Linux.
- Fixed some issues related to disc playback.
- Various bug fixes and stability improvements.
**Test Plan**
- Played a bunch of video files
- Started playing a DVD
**Checklist**

smplayer: Update to v25.6.0

---

packages/d/deluge/monitoring.yaml
packages/e/easytag/monitoring.yaml
packages/g/gnome-pomodoro/monitoring.yaml
packages/py/python-pypng/monitoring.yaml
packages/py/python-pyproject-api/monitoring.yaml

**Summary**
n/a
**Test Plan**
n/a
**Checklist**
- [n/a] Package was built and tested against unstable

[NFC] repo-wide: Fixes for incorrect entry on monitoring.yaml

---

packages/w/waybar/abi_used_symbols
packages/w/waybar/package.yml
packages/w/waybar/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/Alexays/Waybar/releases/tag/0.13.0)
**Test Plan**
- Use waybar in a Sway session
**Checklist**

waybar: Update to v0.13.0

---

packages/w/waycheck/abi_used_libs
packages/w/waycheck/abi_used_symbols
packages/w/waycheck/package.yml
packages/w/waycheck/pspec_x86_64.xml

**Summary**
- Release notes [here](https://gitlab.freedesktop.org/serebit/waycheck/-/releases/v1.7.0)
**Test Plan**
- Check the Ways: Open waycheck and browse some protocols
**Checklist**

waycheck: Update to v1.7.0

---

packages/h/hut/abi_used_symbols
packages/h/hut/package.yml
packages/h/hut/pspec_x86_64.xml

**Summary**
Changelog: https://git.sr.ht/~xenrox/hut/refs/v0.7.0
**Test Plan**
* Built and installed locally.
* Configured for my own account.
* Used a few common commands.
* Checked man pages.
**Checklist**

hut: Update to v0.7.0

---

packages/p/pokeget/abi_used_symbols
packages/p/pokeget/package.yml
packages/p/pokeget/pspec_x86_64.xml

**Summary**
- correct comparison with pokeshell
- fix: handle exception on pokedex id index error
- feat: implement shiny chance
- feat: add region-based random pokemon selection
**Test Plan**
- Generated some Pokémon.
**Checklist**

pokeget: Update to v1.6.5

---

packages/d/davmail/package.yml
packages/d/davmail/pspec_x86_64.xml

**Summary**
- Fix homepage
**Test Plan**
**Checklist**

davmail: fix homepage

---

packages/c/curaengine/abi_used_symbols
packages/c/curaengine/package.yml
packages/c/curaengine/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

curaengine: change homepage

---

packages/a/atkmm/abi_used_symbols
packages/a/atkmm/package.yml
packages/a/atkmm/pspec_x86_64.xml

**Summary**
- Fix license and homepage.
**Test Plan**
- Check homepage and license was changed.
**Checklist**

atkmm: housekeeping

---

packages/d/dfu-util/abi_used_symbols
packages/d/dfu-util/package.yml
packages/d/dfu-util/pspec_x86_64.xml

**Summary**
- Update homepage
**Test Plan**
**Checklist**

dfu-util: update homepage

---

packages/s/sox_ng/package.yml
packages/s/sox_ng/pspec_x86_64.xml

**Summary**
- Don't include test/samples in the distro tarball
**Test Plan**
- Checked version.
**Checklist**

sox_ng: Update to v14.6.0.2

---

packages/b/blueman/package.yml
packages/b/blueman/pspec_x86_64.xml

**Summary**
Changes:
- Make connection notifications transient
- StatusNotifierItem: announce children-display
- Manager: Hide bt status switch when PowerManager is not available
- Fix: Handling for new StatusNotifierWatcher
**Test Plan**
- Disconnected and reconnected my Bluetooth headphones
- Switched audio profiles for my headphones
**Checklist**

blueman: Update to v2.4.6

---

packages/a/anki/package.yml
packages/a/anki/pspec_x86_64.xml

**Summary**
Changes:
- Fixed regression in editor font
- Rename: true retention > retention rate
**Test Plan**
- Played a couple of cards with images and sound from a Japanese learning deck
**Checklist**

anki: Update to v25.07.1

---

packages/o/onefetch/abi_used_symbols
packages/o/onefetch/package.yml
packages/o/onefetch/pspec_x86_64.xml

**Summary**
- add language support for Lean
- support repos "without source code"
- improve error handling
- remove extra line break
**Test Plan**
- Run onefetch on the packages repo.
**Checklist**

onefetch: Update to v2.25.0

---

packages/o/openrct2/abi_used_symbols
packages/o/openrct2/package.yml
packages/o/openrct2/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.24)
**Test Plan**
- Play a scenario
**Checklist**

openrct2: Update to v0.4.24

---

packages/r/rymdport/package.yml
packages/r/rymdport/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/Jacalz/rymdport/releases/tag/v3.9.0)
**Test Plan**
- Send and receive files between local machines
**Checklist**

rymdport: Update to v3.9.0

---

packages/py/python-maturin/package.yml
packages/py/python-maturin/pspec_x86_64.xml

**Summary**
Changes:
- Fix absolute license file path from `Cargo.toml`
**Test Plan**
**Checklist**

python-maturin: Update to v1.9.1

---

packages/l/libimagequant/abi_symbols
packages/l/libimagequant/abi_used_symbols
packages/l/libimagequant/package.yml
packages/l/libimagequant/pspec_x86_64.xml

**Summary**
- No upstream changelog provided
**Test Plan**
- Build tuxpaint and run it; tuxpaint is the only revdep
**Checklist**

libimagequant: Update to v4.4.0

---

packages/p/pinta/package.yml
packages/p/pinta/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/PintaProject/Pinta/releases/tag/3.0.2)
- Resolves https://github.com/getsolus/packages/issues/5988
**Test Plan**
- Draw a scribble
**Checklist**

pinta: Update to v3.0.2

---

common/Scripts/publish_series.py

**Summary**
Make the `publish_series.py` script skip existing builds on the build server unless they failed. This allows for resuming building a series (like a PR) when interrupted.
**Test Plan**
Dry-run against a merged PR:
```
$ common/Scripts/publish_series.py --dry-run --skip-push \
--base=9caf9e60c261df9ffa2703979c29f0725ea5c5b0 \
--head=d568aeb5f122e9c7790bbbed236face37d47e9e6
Skipping build: Build(source='linux-current', tag='linux-current-6.15.6-321', path='packages/l/linux-current', ref='4fcd9d21c294b874c5bfae4ee9b70608b41fdd9b', comment='BUILD 1/16')
Skipping build: Build(source='linux-lts', tag='linux-lts-6.12.37-271', path='packages/l/linux-lts', ref='d722aa7b72761f84396f0ea9162828be752dcf0a', comment='BUILD 2/16')
Skipping build: Build(source='nvidia-glx-driver', …
```

common/Scripts/publish_series.py: Skip existing builds

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/cli/cli/releases/tag/v2.75.0).
**Test Plan**
**Checklist**

github-cli: Update to v2.75.0

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- **[breaking]** Define -d/--treat-dirs-as-files behavior
- Refresh icon set with new glyphs and additions
**Test Plan**
**Checklist**

eza: Update to v0.22.1

---

packages/n/neovim/abi_symbols
packages/n/neovim/package.yml
packages/n/neovim/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/neovim/neovim/commit/b2684d9f6658544d75e2431a06bcf21fe80673f8).
**Test Plan**
Open a file, edit it, and save it.
**Checklist**

neovim: Update to v0.11.3

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/cli/cli/releases/tag/v2.76.0).
**Test Plan**
**Checklist**

github-cli: Update to v2.76.0

---

packages/y/yubico-authenticator/package.yml
packages/y/yubico-authenticator/pspec_x86_64.xml

**Summary**
Update yubico-authenticator to the latest upstream version
**Changelog:**
- UI: Improved language dialog.
- UI: Add help dialog for keyboard shortcuts.
- UI: Fixes to focus and keyboard navigation.
- Linux: Fixes to the tray and application icons.
- Binaries compiled with Flutter 3.32.1 and Python 3.13.4 (desktop).
- New translations: Chinese (Simplified and Traditional), Czech, Spanish, Swedish, Turkish.
Full release notes available [here](https://github.com/Yubico/yubico-flutter/releases)
**Test Plan**
- YubiKey Authenticator launches from the app menu
- YubiKey recognized
- Logged into an account with 2 factor auth successfully
**Checklist**

yubico-authenticator: Update to v7.2.3

---

packages/g/gamescope/abi_used_libs
packages/g/gamescope/abi_used_symbols
packages/g/gamescope/package.yml
packages/g/gamescope/pspec_x86_64.xml
packages/o/openvr/abi_used_symbols
packages/o/openvr/package.yml
packages/o/openvr/pspec_x86_64.xml

**Summary**
- Resolves https://github.com/getsolus/packages/issues/6028
**Test Plan**
- Checked it does not crash as before. Confirmed by Linux in a Bit 
**Checklist**

Update gamescope and openvr

---

packages/d/docker-buildx/package.yml
packages/d/docker-buildx/pspec_x86_64.xml

**Summary**
- bug fixes and improvements
**Test Plan**
Did run builds with docker buildx and docker-compose build
**Checklist**

docker-buildx: Update to v0.25.0

---

packages/t/thunar/abi_used_symbols
packages/t/thunar/package.yml
packages/t/thunar/pspec_x86_64.xml

**Summary**
- Improve file add/remove checks for ThunarFolder
- Properly update view after hidden file rename
- Always reload ThunarFiles on change notice
- Directly notify after file reload
- Set initial state of "Restore" button
- Fix quoting when running shell scripts in a terminal
- Avoid use-after-free in rename dialog when file is changed
- Fix a GFile leak in _thunar_io_jobs_rename
- Fix use-after-free in thunar_renamer_dialog_response
- Fix use-after-free on exit with search tabs open
**Test Plan**
View files and folders, change directories.
**Checklist**

thunar: Update to v4.20.4

---

packages/l/lf/package.yml
packages/l/lf/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/gokcehan/lf/releases/tag/r36)
**Test Plan**
- Browse through some directories
**Checklist**

lf: Update to v36

---

packages/j/just/abi_used_symbols
packages/j/just/package.yml
packages/j/just/pspec_x86_64.xml

**Summary**
- [1.42.3](https://github.com/casey/just/releases/tag/1.42.3)
- [1.42.2](https://github.com/casey/just/releases/tag/1.42.2)
- [1.42.1](https://github.com/casey/just/releases/tag/1.42.1)
- [1.42.0](https://github.com/casey/just/releases/tag/1.42.0)
**Test Plan**
- Run a simple justfile
**Checklist**

just: Update to v1.42.3

---

packages/s/svtplay-dl/package.yml
packages/s/svtplay-dl/pspec_x86_64.xml

**Summary**
- svtplay: improve detection on episode numbering
- svt: fix downloading videos
**Test Plan**
- Downloaded a video.
**Checklist**

svtplay-dl: Update to v4.131

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Make --grid work when not in TTY
- If data is piped into eza, eza will not ignore it
- Add icons for changelog and todo files
- Use CHANGES icon for CHANGELOG as well
**Test Plan**
**Checklist**

eza: Update to v0.23.0

---

packages/w/weechat/abi_used_symbols
packages/w/weechat/package.yml
packages/w/weechat/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/weechat/weechat/releases/tag/v4.7.0).
**Test Plan**
Connect to Libera, join a channel, send and receive messages.
**Checklist**

weechat: Update to v4.7.0

---

packages/f/freeplane/package.yml
packages/f/freeplane/pspec_x86_64.xml

**Summary**
- Release notes [here](https://www.freeplane.org/info/history/history_en.txt)
**Test Plan**
- Make a new mind map
**Checklist**

freeplane: Update to v1.12.11

---

packages/py/python-pyrate-limiter/package.yml
packages/py/python-pyrate-limiter/pspec_x86_64.xml

**Summary**
Changes:
- Add a FileLock option to SQLiteBucket
- Keep Retrying until Max Delay Has Expired
- Postgres performance turning
- Fix cursor leaks on SQLiteBucket
**Test Plan**
**Checklist**

python-pyrate-limiter: Update to v3.8.1

---

packages/l/lazarus/package.yml
packages/l/lazarus/pspec_x86_64.xml

**Summary**
- Release announcement [here](https://forum.lazarus.freepascal.org/index.php/topic,71826.0.html)
- Resolves https://github.com/getsolus/packages/issues/6095
**Test Plan**
- Start IDE, see "Setup OK, start a new project
**Checklist**

lazarus: Update to v4.2

---

packages/u/unrar/package.yml
packages/u/unrar/pspec_x86_64.xml

**Summary**
- No changelog provided
**Test Plan**
- Work on a test archive
**Checklist**

unrar: Update to v7.1.10

---

packages/s/sox_ng/package.yml
packages/s/sox_ng/pspec_x86_64.xml

**Summary**
Bug fixes:
o Really don't include test/samples and test/samples.o in the dist tarball
**Test Plan**
- Checked version.
**Checklist**

sox_ng: Update to v14.6.0.3

---

packages/h/hyprutils/abi_used_symbols
packages/h/hyprutils/package.yml
packages/h/hyprutils/pspec_x86_64.xml
packages/x/xdg-desktop-portal-hyprland/abi_used_symbols
packages/x/xdg-desktop-portal-hyprland/package.yml
packages/x/xdg-desktop-portal-hyprland/pspec_x86_64.xml

**Summary**
- Update some hyprland deps.
**Test Plan**
- Start a hyprland session, browse to a website
**Checklist**

xdg-desktop-portal-hyprland: Update to v1.3.10

---

packages/h/heroic-games-launcher/package.yml
packages/h/heroic-games-launcher/pspec_x86_64.xml

**Summary**
Changelog [here](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/tag/v2.18.0)
**Test Plan**
Logged in and browsed the library
**Checklist**

heroic-games-launcher: Update to v2.18.0

---

packages/a/anki/package.yml
packages/a/anki/pspec_x86_64.xml

**Summary**
Changes:
- Various minor launcher fixes
- Fix a link in the deck options to the manual
**Test Plan**
Played a bunch of cards with images and sound from a Japanese learning deck
**Checklist**

anki: Update to v25.07.5

---

packages/py/python-pyrate-limiter/package.yml
packages/py/python-pyrate-limiter/pspec_x86_64.xml

**Summary**
Changes:
- Introduce MultiProcessBucket
- Update documentation to include MultiProcessBucket
- Add delay configure
- Simplify lock interface for SQLFileLock & MultiProcessBucket
**Test Plan**
**Checklist**

python-pyrate-limiter: Update to v3.9.0

---

packages/s/sox_ng/package.yml
packages/s/sox_ng/pspec_x86_64.xml

**Summary**
o Make ogg output work again, broken in 14.6.0
**Test Plan**
- Installed and checked settings.
**Checklist**

sox_ng: Update to v14.6.0.4

---

packages/b/bottom/abi_used_symbols
packages/b/bottom/monitoring.yaml
packages/b/bottom/package.yml
packages/b/bottom/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/ClementTsang/bottom/releases/tag/0.11.0).
**Test Plan**
Run `btm` and see that all of the graphs show as expected.
**Checklist**

bottom: Update to v0.11.0

---

packages/m/mailnag/files/fix-imp.patch
packages/m/mailnag/package.yml
packages/m/mailnag/pspec_x86_64.xml

**Summary**
- Resolves https://github.com/getsolus/packages/issues/6149
**Test Plan**
- Made sure it started with this patch.
**Checklist**

mailnag: fix issue with python 3.12

---

packages/d/dvd_rw-tools/package.yml
packages/d/dvd_rw-tools/pspec_x86_64.xml

**Summary**
- Change to working source.
- Fix homepage
- Resolves https://github.com/getsolus/packages/issues/6054
**Test Plan**
- Made sure it builds with the new source.
**Checklist**

dvd_rw-tools: housekeeping

---

packages/s/shellcheck/package.yml
packages/s/shellcheck/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/koalaman/shellcheck/releases/tag/v0.11.0)
**Test Plan**
- Check one of my crusty shell scripts
**Checklist**

shellcheck: Update to v0.11.0

---

packages/o/openrct2/abi_used_symbols
packages/o/openrct2/package.yml
packages/o/openrct2/pspec_x86_64.xml

**Summary**
- "Peeps Falling from Buildings"
- Release notes [here](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.25)
**Test Plan**
- Play a scenario
**Checklist**

openrct2: Update to v0.4.25

---

packages/h/homebank/abi_used_symbols
packages/h/homebank/package.yml
packages/h/homebank/pspec_x86_64.xml

**Summary**
- Refer to changelog [here](https://www.gethomebank.org/ChangeLog)
**Test Plan**
- Start a test file
**Checklist**

homebank: Update to v5.9.4

---

packages/l/luanti/abi_used_symbols
packages/l/luanti/package.yml
packages/l/luanti/pspec_x86_64.xml

**Summary**
- Release notes [here](https://docs.luanti.org/about/changelog/#5120--5130)
- Resolves https://github.com/getsolus/packages/issues/6198
**Test Plan**
- Start a new single player world, get spawned underwater (!)
**Checklist**

luanti: Update to v5.13.0

---

packages/b/bottom/package.yml
packages/b/bottom/pspec_x86_64.xml

**Summary**
- Fix `disk.columns` being incorrectly interpreted as blank
- Fix issue with battery widget time and small widths
- Speed up time between startup and displaying data
**Test Plan**
Run `btm` and see that graphs and info displays correctly.
**Checklist**

bottom: Update to v0.11.1

---

packages/d/darkly/package.yml
packages/d/darkly/pspec_x86_64.xml

**Summary**
Seems to be a minor bugfix update. Release notes can be found [here](https://github.com/Bali10050/Darkly/releases/tag/v0.5.22).
**Test Plan**
Updated the package and checked to see if everything was still working.
**Checklist**

darkly: Update to v0.5.22

---

packages/w/weechat/package.yml
packages/w/weechat/pspec_x86_64.xml

**Summary**
- relay/api: fix crash when an invalid HTTP request is received from a client
**Test Plan**
**Checklist**

weechat: Update to v4.7.1

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- Refer to changelog [here](https://tailscale.com/changelog)
**Test Plan**
- Connect to a tail network
**Checklist**

tailscale: Update to v1.86.2

---

packages/d/deepin-icon-theme/package.yml
packages/d/deepin-icon-theme/pspec_x86_64.xml

**Summary**
- No changelog provided
**Test Plan**
- Swith to a deepin theme
**Checklist**

deepin-icon-theme: Update to v2025.8.14

---

packages/f/fcft/package.yml
packages/f/fcft/pspec_x86_64.xml
packages/f/fuzzel/abi_used_symbols
packages/f/fuzzel/package.yml
packages/f/fuzzel/pspec_x86_64.xml

**Summary**
- **fcft: Update to v3.3.2**
- **fuzzel: Update to v1.13.1**
**Test Plan**
Run `fuzzel`, and open Vivaldi via a text search
**Checklist**

fuzzel update

---

packages/n/neovim/package.yml
packages/n/neovim/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/neovim/neovim/commit/cec0ecabd8f47ff81dcb52e8fc9003e365563a84).
**Test Plan**
Open and edit a text file.
**Checklist**

neovim: Update to v0.11.4

---

packages/a/adw-gtk3-theme/package.yml
packages/a/adw-gtk3-theme/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/lassekongo83/adw-gtk3/compare/v6.2...v6.3).
**Test Plan**
Switch to the theme.
**Checklist**

adw-gtk3-theme: Update to v6.3

---

packages/i/iio-sensor-proxy/abi_used_symbols
packages/i/iio-sensor-proxy/package.yml
packages/i/iio-sensor-proxy/pspec_x86_64.xml

**Summary**
Changelog:
- Improve handling of buffer sensors which caused a regression in 3.7 for some corner cases.
**Test Plan**
Tested than screen rotation on Framework 12 and KDE Plasma now works as expected, where it didn't before
**Checklist**

iio-sensor-proxy: update to 3.8

---

packages/s/svtplay-dl/package.yml
packages/s/svtplay-dl/pspec_x86_64.xml

**Summary**
- resolv the main playlist
**Test Plan**
- Downoad a video.
**Checklist**

svtplay-dl: Update to v4.137

---

packages/l/lact/abi_used_symbols
packages/l/lact/files/0001-Solus-Adapt-to-our-amdgpu-kernel-argument.patch
packages/l/lact/package.yml
packages/l/lact/pspec_x86_64.xml

**Summary**
changelog can be found [here](https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.8.1)
**Test Plan**
Install on system and verify it launches and can see gpu stats
**Checklist**

lact: Update to v0.8.1

---

packages/t/thunar/package.yml
packages/t/thunar/pspec_x86_64.xml

**Summary**
- Update shortcut model asynchronously
- Clear selection before updating selection
**Test Plan**
Open Thunar.
**Checklist**

thunar: Update to v4.20.5

---

packages/f/font-noto-emoji/package.yml
packages/f/font-noto-emoji/pspec_x86_64.xml

**Summary**
Unicode 17 Update
For more information about new emojis, see [here](https://emojipedia.org/unicode-17.0)
**Test Plan**
Confirmed that the emojis on the Unicode 17 overview screen looked correct
**Checklist**

font-noto-emoji: Update to v2.051

---

packages/m/mir/package.yml
packages/m/mir/pspec_x86_64.xml

**Summary**
- Fix some memory leaks
- Changing cursor_scale causes weird cursors and crashes
- Check for WL_bind_wayland_display when probing eglstream-kms support platform
- Platform-specific options not passed through if platforms not probed
**Test Plan**
Start a Budgie Miriway session.
**Checklist**

mir: Update to v2.22.1

---

packages/a/amfora/package.yml
packages/a/amfora/pspec_x86_64.xml

**Summary**
Changes:
- Added: Search in pages
- Added: Support for custom commands
- Use preformatted_text color for rendering plain text files
- Fix building cview
**Test Plan**
Browse through a few Gemini pages
**Checklist**

amfora: Update to v1.11.0

---

packages/f/fooyin/abi_symbols
packages/f/fooyin/abi_used_symbols
packages/f/fooyin/package.yml
packages/f/fooyin/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/fooyin/fooyin/releases/tag/v0.9.2).
**Test Plan**
- Checked settings.
**Checklist**

fooyin: Update to v0.9.2

---

packages/z/zed/abi_used_symbols
packages/z/zed/package.yml
packages/z/zed/pspec_x86_64.xml

**Summary**
Changelog available [here](https://zed.dev/releases/stable/0.205.5).
**Test Plan**
Edited a Vala source file.
**Checklist**

zed: Update to v0.205.5

---

packages/l/libtelepathy-glib/files/telepathy-glib-pr3-test-cm-with-newer-glib.patch
packages/l/libtelepathy-glib/files/telepathy-glib-prXXX-function-type-cast.patch
packages/l/libtelepathy-glib/monitoring.yaml
packages/l/libtelepathy-glib/package.yml
packages/l/libtelepathy-glib/pspec_x86_64.xml

**Summary**
- Add patches from Fedora to fix build
**Test Plan**
**Checklist**

libtelepathy-glib: Fix build and housekeeping

---

packages/g/gnuplot/abi_used_symbols
packages/g/gnuplot/package.yml
packages/g/gnuplot/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://gnuplot.sourceforge.net/ReleaseNotes_6_0_3.html).
- Resolves https://github.com/getsolus/packages/issues/6146
**Test Plan**
- plot sin(x)
**Checklist**

gnuplot: Update to v6.0.3

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/cli/cli/releases/tag/v2.81.0).
**Test Plan**
**Checklist**

github-cli: Update to v2.81.0

---

packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
- Release notes [here](https://sw.kovidgoyal.net/kitty/changelog/#detailed-list-of-changes)
**Test Plan**
- Run Kitty terminal for a while
**Checklist**

kitty: Update to v0.43.1

---

packages/a/alsa-firmware/package.yml
packages/a/alsa-firmware/pspec_x86_64.xml

**Summary**
- Fix homepage
**Test Plan**
**Checklist**

alsa-firmware: fix homepage

---

packages/m/mutt/package.yml
packages/m/mutt/pspec_x86_64.xml

**Summary**
- Release notes [here](https://gitlab.com/muttmua/mutt/-/blob/mutt-2-2-15-rel/ChangeLog?ref_type=tags)
**Test Plan**
- Create an inbox
**Checklist**

mutt: Update to v2.2.15

---

packages/j/just/abi_used_libs
packages/j/just/abi_used_symbols
packages/j/just/package.yml
packages/j/just/pspec_x86_64.xml

**Summary**
- Release notes [here](https://github.com/casey/just/releases/tag/1.43.0)
- Packaging note: Completions have now been added directly to the source repo.
**Test Plan**
- Run a "Hello world" justfile
**Checklist**

just: Update to v1.43.0

---

packages/c/cve-check-tool/package.yml
packages/c/cve-check-tool/pspec_x86_64.xml

**Summary**
- Fix homepage
**Test Plan**
- Checked homepage
**Checklist**

cve-check-tool: fix homepage

---

packages/d/djvulibre/package.yml
packages/d/djvulibre/pspec_x86_64.xml

**Summary**
- Fix homepage
**Test Plan**
**Checklist**

djvulibre: fix homepage

---

packages/o/openbox/abi_used_symbols
packages/o/openbox/package.yml
packages/o/openbox/pspec_x86_64.xml

**Summary**
- Fix homepage
**Test Plan**
- Checked homepage
**Checklist**

openbox: fix homepage

---

packages/h/hwdata/package.yml
packages/h/hwdata/pspec_x86_64.xml

**Summary**
- Update usb and vendor ids
**Test Plan**
- Install, watch computer not explode
**Checklist**

hwdata: Update to v0.400

---

packages/l/luanti/abi_used_symbols
packages/l/luanti/package.yml
packages/l/luanti/pspec_x86_64.xml

**Summary**
- Changelog [here](https://docs.luanti.org/about/changelog/#5130--5140)
**Test Plan**
- Start a new world, punch trees
**Checklist**

luanti: Update to v5.14.0

---

packages/f/firejail/abi_used_symbols
packages/f/firejail/files/0001-solus-Support-a-stateless-configuration.patch
packages/f/firejail/files/0002-Fix-apparmor-profile.patch
packages/f/firejail/files/0003-Use-stateless-login.defs.patch
packages/f/firejail/files/fix-glycin.patch
packages/f/firejail/package.yml
packages/f/firejail/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/netblue30/firejail/releases/tag/0.9.76).
Fixes https://github.com/getsolus/packages/issues/6450
**Test Plan**
Run `firejail firefox`, see that Firefox opens, and I can browse webpages.
**Checklist**

firejail: Update to v0.9.76

---

packages/g/gnucash/abi_symbols
packages/g/gnucash/abi_used_symbols
packages/g/gnucash/package.yml
packages/g/gnucash/pspec_x86_64.xml

**Summary**
Release note can be read [here](https://github.com/Gnucash/gnucash/releases/tag/5.13)
**Test Plan**
Open old account
**Checklist**

gnucash: Update to v5.13

---

packages/u/usdx/abi_used_symbols
packages/u/usdx/package.yml
packages/u/usdx/pspec_x86_64.xml

**Summary**
Relesase note can be read [here](https://github.com/UltraStar-Deluxe/USDX/releases/tag/v2025.10.0)
**Test Plan**
Launch the app
**Checklist**

usdx: Update to v2025.10.0

---

packages/g/guake/monitoring.yaml
packages/g/guake/package.yml
packages/g/guake/pspec_x86_64.xml

**Summary**
- Fix build
- Replace homepage
**Test Plan**
Build app and checked homepage is changed
**Checklist**

guake: Fix build and housekeeping
