.gitignore
common/Scripts/new-package.sh
common/Taskfile.yml

Adds a new package command
Usage: `go-task new -- python-zzzbar https://www.nano-editor.org/dist/v7/nano-7.2.tar.xz`
Also removes unneeded switch-repo-domains from taskfile
`go-task new -- python-zzzbar https://www.nano-editor.org/dist/v7/nano-7.2.tar.xz`
`go-task new -- zzzbar https://www.nano-editor.org/dist/v7/nano-7.2.tar.xz`
Verify the package.yml was created in the correct directory.

Add a go task for creating new packages

---

packages/f/flask-cors/package.yml
packages/f/flask-cors/pspec_x86_64.xml

**Changes:**
- Remove support for Python versions older than 3.8
- Remove dependency on six
Ran some examples from the documentation

flask-cors: update to 4.0.0

---

.github/pull_request_template.md

Switches the PR template to asterisk bolding instead of H2. The (current) Software Center has no support for rendering H2 and this makes changelogs look worse (IMO at least)
H2:
Asterisk bolding:
Looked at changelogs with asterisk bolding and H2 formatting in SC and compared.

PR template: switch to asterisk bolding to fix SC changelogs

---

.gitignore
common/Taskfile.yml

Add infra name space as an optional include for infrastructure-tooling
This is currently needed for the tram file generator that has already been committed.
Generate tram file using `go-task infra:gen-tram`

Add infra namespace

---

packages/g/gnome-mahjongg/files/only-create-a-single-timer.patch
packages/g/gnome-mahjongg/package.yml
packages/g/gnome-mahjongg/pspec_x86_64.xml

**Summary**
Backport a patch to fix excessive resource usage over time
Should fix this issue: https://discuss.getsol.us/d/9774-has-anyone-else-noticed-bad-behavior-from-gnome-mahjongg
Packaging change: added homepage
**Test Plan**
- Played a couple of games
- Pressed the "Hint" button repeatedly to see if game increasingly slows down
**Checklist**

gnome-mahjongg: backport patch to fix excessive resource usage

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

- Added Characters
- Add variants for Cyrillic lower Ef (ф) with a split bowl
- Add Bulgarian local variants for Cyrillic Ef (Ф,ф)
- Fix serifs in U+01A6
- Improve serifs of Turn M (U+019C, U+026F) under quasi-proportional.
- Make Turn h (U+0265) and Turn M with Long Leg (U+0270) follow serif variants of u.
- Optimize geometry for U+A65A and U+A65B under extended width.
- Variants for π, τ and « are inserted into the main tag sequence.
- Reordered variants of Eszet.
- Change of variant names
- Add bottom-right and top-left bottom-right serifed variants of R.
- Add bottom-left motion serifed variants of Cyrillic Ya (Я,я).
- Add cursive variants for Cyrillic Capital/Small Zhe (Ж,ж)
- Allow R Rotunda (U+A75A, U+A75B) and Indian Rupee Sign (U+20B9) to have a bottom-right serif.
- Add OpenType …

font-iosevka-ttf: Update to 27.0.2

---

packages/b/bash/files/profile/profile
packages/b/bash/package.yml
packages/b/bash/pspec_x86_64.xml

**Summary**
Any files in `~/.bashrc.d/` are sourced after all other /usr/share/defaults/etc/profile.d/ and /etc/profile.d/ scripts are sourced.
This in effect makes it simple to perform per-user changes to override system settings, by copying changed files into `~/.bashrc.d/` and editing them there as per user requirements.
Additionally, this feature also has the nice side-effect that it becomes simpler and easier to save and restore user shell customisations across installs without having to edit the default `~/.bashrc` file.
**Test Plan**
Open a new shell and check that `~/.bashrc.d/*` were correctly sourced.
**Checklist**

bash: Support user ~/.bashrc.d/* script sourcing

---

packages/g/godot-cpp/package.yml
packages/g/godot-cpp/pspec_x86_64.xml
packages/g/godot-headers/package.yml
packages/g/godot-headers/pspec_x86_64.xml
packages/g/godot/abi_used_libs
packages/g/godot/package.yml
packages/g/godot/pspec_x86_64.xml

**Summary**
Release notes available [here](https://godotengine.org/article/maintenance-release-godot-3-5-3/)
**Test Plan**
- Opened and edited a test project with classic and mono version
**Checklist**

godot: update to 3.5.3

---

packages/g/gpxsee/abi_used_symbols
packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

- Fixed storing of WMTS tiles with file system incompatible tile matrix names.
- Improved/fixed TrekBuddy maps/atlases support.
- Improved ENC maps rendering style.
- open garmin map
- zoom in and out
-

gpxsee: Update to 13.9

---

packages/t/tailscale/abi_used_symbols
packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

- update to Go 1.21.1.
- tailscale ping now sends an ICMP Ping code of 0.
- UPnP falls back to a permanent lease if a limited lease fails, some servers only support permanent.
- Adds support for Wikimedia DNS using DNS-over-HTTPS.
- Unhide tailscale update CLI command on most platforms.
- tailscale web updated to use React and be more awesome.
- Add --log-http option to tailscale debug portmap.
- tailscale netcheck now works even if the OS platform lacks CA certificates.
- nftables support now interoperates with ufw

tailscale: Update to 1.50.0

---

packages/x/xpra/package.yml
packages/x/xpra/pspec_x86_64.xml

**Summary**
Bugfixes:
- missing x264 encoder in DEB packages
- unusable vsock module
- start-after-connect was broken
- Overflow error in MS Windows hooks + fixup
- notification packet errors due to missing icon
Enhancements:
- pactl improve detection of monitor devices
- microphone support for Chromium
- [5.0.2](https://github.com/Xpra-org/xpra/releases/tag/v5.0.2)
**Test Plan**
Command line tests used from https://wiki.archlinux.org/title/xpra
```
xpra shadow ssh:<some-client>:0
```
Start xpra server on your remote machine:
```
$ xpra start :4
```
Attach to xpra session on your local machine:
```
$ xpra attach ssh:<some-ip>:4
```
Start an application on your remote machine:
```
$ DISPLAY=:4 firefox
```
Firefox should appear on your local machine.
**Checklist**

xpra: Update to 5.0.2

---

packages/c/coreutils/abi_used_symbols
packages/c/coreutils/files/0001-Disable-tests-that-fail-in-chroot.patch
packages/c/coreutils/package.yml
packages/c/coreutils/pspec_x86_64.xml

**Summary**
[Changelog](https://lists.gnu.org/archive/html/info-gnu/2023-08/msg00007.html)
**Test Plan**
Use some common utilities as normal, e.g. cp, mv, etc.
**Checklist**

coreutils: Update to 9.4

---

packages/l/libinput/abi_used_symbols
packages/l/libinput/files/0001-quirks-Disable-quirk-removing-two-finger-scrolling-f.patch
packages/l/libinput/package.yml
packages/l/libinput/pspec_x86_64.xml

**Summary**
Personally affected by this quirk. Can't replicate the bug and i _hate_ _hate_ _hate_ edge scrolling.
**Test Plan**
Use two finger scrolling
**Checklist**

libinput: Disable quirk removing two-finger scrolling on HP Pavillion

---

packages/b/bluez/abi_symbols
packages/b/bluez/abi_used_symbols
packages/b/bluez/package.yml
packages/b/bluez/pspec_x86_64.xml

**Summary**
Changes:
- Fix issue with not sending GATT confirmations
- Fix issue with not handling initiator properly
- Fix issue with not checking PBAP counter length
- Add support for MICP profile and MICS service
- Fix issue with BAP enabling state correctly when resuming
- Fix issue with detaching source ASEs only after Stop Ready
- Fix issue with handling VCP audio location and descriptor
- Fix issue with generating IRK for adapter with privacy enabled
- Add support for BAP broadcast sink
Full commit log available [here](https://github.com/bluez/bluez/compare/5.68...5.70)
Packaging changes: added homepage, minor cleanups
**Test Plan**
- Connected both my Bluetooth headphones and earbuds
- Changed Bluetooth audio codecs
- Re-paired my earbuds using `bluetoothctl`
**Checklist**

bluez: update to 5.70

---

packages/c/cava/abi_used_symbols
packages/c/cava/package.yml
packages/c/cava/pspec_x86_64.xml

**Summary**
Changes:
- glsl shader output
- pipewire input support
- gradient support in sdl output
- some config options are now `0-100` instead of `0-1`
- fix default input wrongly being set to alsa instead of pulseaudio/pipewire
**Test Plan**
- Listened to some music while watching the visualizer
- Configured different colours and bar widths/sensitivities
**Checklist**

cava: update to 0.9.1

---

common/Scripts/package-publish-safety-catches.sh

**Summary**
Reworks `package-publish-safety-catches` for monorepo usage by diffing the last commit in the directory rather than HEAD and HEAD~1.
**Test Plan**
cd into various packages and run `go-task publish --dry` to ensure the checks parse.
Landed kde plasma stack upgrade with the change.
**Checklist**

common: Rework `package-publish-safety-catches.sh` for monorepo usage

---

packages/b/bdwgc/package.yml
packages/b/bdwgc/pspec_x86_64.xml

**Summary**
Don't move the man file for `bdwgc` into a weird and lonely `manman` folder
Also remove another leftover packaging instructions that's no longer necessary
**Test Plan**
Checked man file was put into correct place
**Checklist**

bdwgc: don't move man file to weird place

---

packages/v/veracrypt/abi_used_libs
packages/v/veracrypt/abi_used_symbols
packages/v/veracrypt/package.yml
packages/v/veracrypt/pspec_x86_64.xml

- Add `ayatana-appindicator3` as build dependency.
- Set `INDICATOR` build option.
Fixes #393
- Create a new file with an encrypted filesystem.
- Store files in the filesystem.
- Remount the filesystem to access the files.
- Use trayicon to hide and unhide the application.

veracrypt: Fix missing app indicator

---

packages/v/veracrypt/abi_used_symbols
packages/v/veracrypt/package.yml
packages/v/veracrypt/pspec_x86_64.xml

- Add pcsc-lite builddeb for smart card support.
- Update homepage and description of package.
- [1.26.7](https://github.com/veracrypt/VeraCrypt/releases/tag/VeraCrypt_1.26.7)
- Launched the application
- Encrypted and decrypted some files

veracrypt: Update to 1.26.7

---

packages/f/fftw/package.yml
packages/f/fftw/pspec_x86_64.xml

**Summary**
Upstream issue: https://github.com/FFTW/fftw3/issues/130
**Packaging Notes**
- Due to fakeroot only being allowed during the install step these days, rework the package a bit without resorting to enabling fatfakeroot.
**Test Plan**
Fixes finding fftw when building `krita`
**Checklist**

fftw: Ensure missing `FFTW3LibraryDepends.cmake` file is provided

---

packages/q/qemu/package.yml
packages/q/qemu/pspec_x86_64.xml

**Summary**
Release notes available [here](https://www.mail-archive.com/qemu-devel@nongnu.org/msg991183.html)
**Test Plan**
- Launched my Solus VMs
- Created and launched a number of VMs (x64, aarch64) in `gnome-boxes` and `virt-manager`
**Checklist**

qemu: update to 7.2.6

---

common/Taskfile.yml
packages/a/amule/abi_used_symbols
packages/a/amule/package.yml
packages/a/amule/pspec_x86_64.xml

**Summary**
- The inclusion of "homepage" to package.yml
**Test Plan**
- Launched the application
**Checklist**

amule: Inclusion of homepage

---

packages/m/man-pages/package.yml
packages/m/man-pages/pspec_x86_64.xml

**Summary**
Release notes:
- [6.05](https://www.spinics.net/lists/kernel/msg4883220.html)
- [6.05.01](https://www.spinics.net/lists/kernel/msg4885689.html)
Packaging changes: Added homepage, added pattern so `man3` folder isn't split off, fixed issue with redirection
**Test Plan**
- Looked at a number of man pages
**Checklist**

man-pages: update to 6.05.01

---

.flake8
.github/workflows/package_lint.yml
.github/workflows/script_lint.yml
common/CI/package_checks.py
common/Taskfile.yml

**Summary**
This PR adds some initial linters for for pull requests. Checks are mostly focussed on common packaging mistakes:
- `homepage` not set
- Incorrect directory
- `patch <` instead of `patch -i`
- Various unwanted files (including in incorrect directories)
- Inconsistent `package.yml` and `pspec_x86_64.yml`.
**Test Plan**
This PR!
**Checklist**

ci: Add PR and Python linters

---

common/CI/package_checks.py
common/Taskfile.yml

**Summary**
This PR adds linting for modified and untracked files and enables them by default for `go-task check`.
**Test Plan**
Modify `nginx` and run run `go-task check` in any directory.
**Checklist**

ci: Lint modified and untracked files

---

packages/py/python-maturin/package.yml
packages/py/python-maturin/pspec_x86_64.xml

**Summary**
Changes:
- Better cross-compilation interpreter error
- Refactor Cargo sdist generator to avoid rewriting local dependencie
- Ignore sdist output files when building sdist
- Don't require `uniffi-bindgen` to be installed for uniffi bindings
- Fix python 3.7 compatibility
- Added `--pip-path` argument to `develop`
- Disable user site when running `get_interpreter_metadata.py`
- Fix platform tag for graalpy
- Always set minor version to 0 when major version >= 11 for macOS
- Warn about incorrect version in `build-system.requires`
**Test Plan**
- Built `python-orjson`
**Checklist**

python-maturin: update to 1.3.0

---

packages/f/font-util/package.yml
packages/f/font-util/pspec_x86_64.xml

**Summary**
This release contains no functional changes, only license clarifications
Release notes available [here](https://lists.x.org/archives/xorg-announce/2023-September/003418.html)
Packaging change: Sorted licenses and added comments
**Test Plan**
- Truncated the GNU Unifont .bdf using `bdftruncate`
**Checklist**

font-util: update to 1.4.1

---

packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

- Shell integration: Automatically alias sudo to make the kitty terminfo files available in the sudo environment. Can be turned off via shell_integration
- ssh kitten: Fix a regression in 0.28.0 that caused using --kitten to override ssh.conf not inheriting settings from ssh.conf
- themes kitten: Allow absolute paths for --config-file-name
- Expand environment variables in the shell option
- X11: Fix a crash on startup when the ibus service returns errors and the GLFW_IM_MODULE env var is set to ibus
- run htop

kitty: Update to 0.30.1

---

common/Scripts/buildserver-notification.sh

**Summary**
This makes the notification script create a tag from `pspec.xml` if `package.yml` doesn't exist, so it works for legacy packages.
(one of the two is guaranteed to exist by the notify-complete go-task precondition
**Test Plan**
- Tested with a `package.yml`
- Tested with a `pspec.xml`
**Checklist**
- [N/A] Package was built and tested against unstable

buildserver-notification: also use tags from pspec.xml

---

packages/l/languagetool/package.yml
packages/l/languagetool/pspec_x86_64.xml

- added and improved Catalan rules
- added and improved Dutch rules
- added and improved English rules
- updated [en_GB spellchecker](https://github.com/marcoagpinto/aoo-mozilla-en-dict) to v.3.2.1
- added and improved French rules
- added and improved German rules
- extended German dictionary
- added and improved Portuguese rules
- added and improved Spanish rules
- Ukrainian tagging and disambiguation improvements
- new rules and words in Ukrainian POS dictionary
- [changelog](https://raw.githubusercontent.com/languagetool-org/languagetool/v6.3-branch/languagetool-standalone/CHANGES.md)
JAVA_HOME=/usr/lib64/openjdk-17 languagetool

languagetool: Update to 6.3

---

.github/workflows/package_lint.yml
.gitignore
common/CI/package_checks.py

**Summary**
- Perform an extensive cleanup of the package checks script
- Add a linter to check if a package has been bumped *once*. This is set as a warning, so it doesn't interfere with PRs that do not require rebuilds.
**Test Plan**
See [this test PR](https://github.com/silkeh/packages/pull/4/files#diff-fd36bdf870f06c81d1e087aca13513b1e87ec59e451f02eeee4e591e31a5992a).
**Checklist**

ci: cleanup and add check for bumped packages

---

packages/z/zsh-autosuggestions/package.yml
packages/z/zsh-autosuggestions/pspec_x86_64.xml

**Summary**
- Part of #411
**Test Plan**
**Checklist**

zsh-autosuggestions: Inclusion of homepage

---

packages/j/jet/package.yml
packages/j/jet/pspec_x86_64.xml

**Summary**
- Part of #411
**Test Plan**
- Run package
- Test with example:
- echo '{"a": 1}' | jet --from json --to edn 
- echo '{"a": "hello there"}' | jet --from json --keywordize -t ":a symbol" --to edn
**Checklist**

jet: Inclusion of homepage

---

packages/py/python-orjson/abi_used_symbols
packages/py/python-orjson/package.yml
packages/py/python-orjson/pspec_x86_64.xml

**Summary**
Changes:
- Drop support for Python 3.7
**Test Plan**
- Tested a number of examples from the project README
**Checklist**

python-orjson: update to 3.9.8

---

common/Scripts/helpers.fish

**Summary**
This adds a Fish-based implementation of [the helper scripts](https://help.getsol.us/docs/packaging/prepare-for-packaging#set-up-monorepo-helper-functions-optional).
Resolves #506
**Test Plan**
Symlink the configuration and start a new shell:
```fish
mkdir -p ~/.config/fish/conf.d
ln -s (git rev-parse --show-toplevel)/common/Scripts/helpers.fish ~/.config/fish/conf.d/solus.fish
exec fish
```
**Checklist**

common: Add Fish helper scripts

---

packages/l/libvirt/abi_used_symbols
packages/l/libvirt/package.yml
packages/l/libvirt/pspec_x86_64.xml

**Summary**
- Enables support for Firewalld
**Test Plan**
Create a new VM with virt-manager using the NAT network option
**Checklist**

libvirt: Enable firewalld support

---

common/Scripts/new-package.sh

**Summary**
Allows dots in package names when creating a new package
**Test Plan**
`go-task new cairomm-1.16 https://penisland.com/foobar.tar.gz`
**Checklist**

common: Allow dots in package names in new-package.sh

---

packages/f/font-fira-ttf/files/fira.metainfo.xml
packages/f/font-fira-ttf/package.yml
packages/f/font-fira-ttf/pspec_x86_64.xml

**Summary**
- Including metainfo.xml (Part of #449)
**Test Plan**
**Checklist**

font-fira-ttf: Inclusion of homepage and metainfo.xml

---

packages/f/font-freefont-ttf/files/freefont.metainfo.xml
packages/f/font-freefont-ttf/package.yml
packages/f/font-freefont-ttf/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

font-freefont-ttf: Inclusion of homepage and metainfo.xml

---

packages/f/font-hack-ttf/files/hack.metainfo.xml
packages/f/font-hack-ttf/package.yml
packages/f/font-hack-ttf/pspec_x86_64.xml

**Summary**
- Adding `homepage` key to `package.yml`( Part of getsolus#411)
- Including `metainfo.xml` (Part of getsolus#449)
**Test Plan**
**Checklist**

font-hack-ttf: Inclusion of homepage and metainfo.xml

---

packages/f/font-iosevka-ttf/files/iosevka.metainfo.xml
packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Add characters
* TELEPHONE RECORDER (`U+2315`) (#2020).
* COUNTERSINK (`U+2335`) (#2020).
* BROKEN CIRCLE WITH NORTHWEST ARROW (`U+238B`) (#2020).
* TRIPLE PLUS (`U+29FB`) (#2020).
- Correction of letter assignments for stylistic styles:
* Fix `cv10` and `cv30` for `ss14`.
* Fix `cv12`, `cv36`, and `cv82` for `ss16`.
* Fix `cv22`, `cv31`, `cv47`, and `cv91` for `ss07`.
* Fix `cv26` for `ss07`, `ss14`, and `ss15`.
* Fix `cv28`, `cv43`, and `cv70` for `ss01`, `ss04`, `ss05`, `ss06`, `ss07`, `ss13`, and `ss16`.
* Fix `cv55` for `ss03`, `ss09`, `cv12`, and `ss14`.
* Fix `cv53` and `cv84` for `ss10`.
* Fix `cv58` for `ss06` and `ss10`.
* Fix `cv59` for `ss09` and `ss18`.
* Fix `cv61` for `ss08` and `ss20`.
* Fix `cv62` for `ss01`.
* Fix `cv63` for `ss02`, `ss05`, and `ss12`.
* …

font-iosevka-ttf: Update to 27.2.0

---

common/Taskfile.yml

**Summary**
Add `go-task clean-all` action to remove _all_ eopkgs found in the monorepo
**Test Plan**
`go-task clean-all`
**Checklist**

common/Taskfile: Add clean-all action to remove _all_ eopkgs

---

packages/f/font-jetbrainsmono-ttf/files/jetbrainsmono.metainfo.xml
packages/f/font-jetbrainsmono-ttf/package.yml
packages/f/font-jetbrainsmono-ttf/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

font-jetbrainsmono-ttf: Inclusion of metainfo.xml

---

packages/f/font-lato-ttf/files/lato.metainfo.xml
packages/f/font-lato-ttf/package.yml
packages/f/font-lato-ttf/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

font-lato-ttf: Inclusion of homepage and metainfo.xml

---

packages/f/font-opendyslexic-otf/files/opendyslexic.metainfo.xml
packages/f/font-opendyslexic-otf/package.yml
packages/f/font-opendyslexic-otf/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

font-opendyslexic-otf: Inclusion of homepage and metainfo.xml

---

packages/f/font-roboto-ttf/files/roboto.metainfo.xml
packages/f/font-roboto-ttf/package.yml
packages/f/font-roboto-ttf/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

font-roboto-ttf: Inclusion of homepage and metainfo.xml

---

packages/f/font-tlwg-ttf/files/tlwg.metainfo.xml
packages/f/font-tlwg-ttf/package.yml
packages/f/font-tlwg-ttf/pspec_x86_64.xml

**Summary**
- 0.7.3 changelog: 
* Purisa, Sawasdee: now can be embeded as installable in PDF. 
* TlwgTypo, TlwgTypist: fix uneven widths of some glyphs.
* TlwgTypo, TlwgTypist, TlwgMono, TlwgTypewriter: clear PANOSE to use calculated values, so as to get listed in gvim. (Thanks Chaiwat Suttipongsakul for the report.) 
* Norasi: add 'onum' and 'smcp' OpenType features for access to old style figures and small caps glyphs. * LaTeX: Add old style figures and small caps supports for Norasi. 
* [changelog](https://github.com/tlwg/fonts-tlwg/releases/tag/v0.7.3)
**Test Plan**
- Render text with the font
- Check that …

font-tlwg-ttf: Update to 0.7.3

---

packages/p/powerline-fonts/files/powerline-fonts.metainfo.xml
packages/p/powerline-fonts/package.yml
packages/p/powerline-fonts/pspec_x86_64.xml

**Summary**
- Adding `homepage` key to `package.yml`( Part of getsolus#411)
- Including `metainfo.xml` (Part of getsolus#449)
**Test Plan**
**Checklist**

powerline-fonts: Inclusion of homepage and metainfo.xml

---

packages/py/python-orjson/package.yml
packages/py/python-orjson/pspec_x86_64.xml

**Summary**
Changes:
- `orjson` module metadata explicitly marks subinterpreters as not supported
**Test Plan**
Ran a number of examples from the project README
**Checklist**

python-orjson: update to 3.9.9

---

packages/w/wine/abi_symbols
packages/w/wine/abi_symbols32
packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
- Bundled FluidSynth library for DirectMusic
- More window management in the Wayland driver
- More effect support in Direct3D 10
Full release notes available [here](https://www.winehq.org/announce/8.18)
**Test Plan**
- Launched and used several Wine tools (`winefile`, `winecfg`, `wineconsole`,...)
- Played Age of Empires I demo
**Checklist**

wine: update to 8.18

---

packages/f/font-ubuntu-ttf/files/ubuntu.metainfo.xml
packages/f/font-ubuntu-ttf/package.yml
packages/f/font-ubuntu-ttf/pspec_x86_64.xml

**Summary**
- Change to new source (old one no longer works)
**Test Plan**
**Checklist**

font-ubuntu-ttf: Inclusion of homepage and metainfo.xml

---

packages/f/font-droid-ttf/files/droid.metainfo.xml
packages/f/font-droid-ttf/package.yml
packages/f/font-droid-ttf/pspec_x86_64.xml

**Summary**
- Change source to a new one (old one no longer works)
**Test Plan**
**Checklist**

font-droid-ttf: Inclusion of metainfo.xml

---

packages/y/yaru-theme/package.yml
packages/y/yaru-theme/pspec_x86_64.xml

**Summary**
Release notes available [here](https://raw.githubusercontent.com/ubuntu/yaru/23.10.0-0ubuntu2/debian/changelog)
**Test Plan**
Changed icon and gtk theme to Yaru and navigated around my system to check things were alright
**Checklist**

yaru-theme: update to 23.10.0

---

packages/c/czkawka/abi_used_symbols
packages/c/czkawka/package.yml
packages/c/czkawka/pspec_x86_64.xml

**Changelog**
- BREAKING CHANGE - Changed cache saving method, deduplicated, optimized and simplified procedure(all files needs to be hashed again)
- Remove up to 340ms of delay when waiting for results
- Added logger with useful info when debugging app (level can be adjusted via e.g. RUST_LOG=debug env)
- Core code cleanup
- Updated list of bad extensions and support for finding invalid jar files
- More default excluded items on Windows(like pagefile)
- Unified printing/saving method to files/terminal and fixed some differences/bugs
- Uses fun_time library to print how much functions take time
- Added exporting results into json file format
- Added new test/regression suite for CI
- Added ability to use relative paths
- Allowed removing similar images/videos/music from cli
- Added info …

czkawka: update to version 6.1.0

---

packages/b/budgie-calendar-applet/package.yml
packages/b/budgie-calendar-applet/pspec_x86_64.xml
packages/b/budgie-control-center/abi_used_symbols
packages/b/budgie-control-center/package.yml
packages/b/budgie-control-center/pspec_x86_64.xml
packages/b/budgie-cputemp-applet/package.yml
packages/b/budgie-cputemp-applet/pspec_x86_64.xml
packages/b/budgie-desktop-view/abi_used_symbols
packages/b/budgie-desktop-view/package.yml
packages/b/budgie-desktop-view/pspec_x86_64.xml
packages/b/budgie-desktop/abi_used_symbols
packages/b/budgie-desktop/package.yml
packages/b/budgie-desktop/pspec_x86_64.xml
packages/b/budgie-extras/package.yml
packages/b/budgie-extras/pspec_x86_64.xml
packages/b/budgie-haste-applet/package.yml
packages/b/budgie-haste-applet/pspec_x86_64.xml
packages/b/budgie-screensaver/package.yml
packages/b/budgie-screensaver/pspec_x86_64.xml
packages/b/budgie-screenshot-applet/package.yml
packages/b/budgie-screenshot-applet/pspec_x86_64.xml
packages/b/budgie-shutdown-timer/package.yml
packages/b/budgie-shutdown-timer/pspec_x86_64.xml
packages/b/budgie-user-indicator-redux-applet/package.yml
packages/b/budgie-user-indicator-redux-applet/pspec_x86_64.xml
packages/m/magpie/abi_used_symbols
packages/m/magpie/package.yml
packages/m/magpie/pspec_x86_64.xml

**Summary**
- magpie: Safety rebuild for GNOME 45
- budgie-screensaver: Safety rebuild for GNOME 45
- budgie-desktop-view: Update to 1.3
- budgie-desktop: Update to 10.8.2
- budgie-extras: Safety rebuild for GNOME 45
- budgie-haste-applet: Safety rebuild for GNOME 45
- budgie-screenshot-applet: Safety rebuild for GNOME 45
- budgie-user-indicator-redux-applet: Safety rebuild for GNOME 45
- budgie-calendar-applet: Safety rebuild for GNOME 45
- budgie-shutdown-timer: Safety rebuild for GNOME 45
- budgie-control-center: Safety rebuild for GNOME 45
- budgie-cputemp-applet: Safety rebuild for GNOME 45
**Test Plan**
Update fully and restart the system.
**Checklist**

budgie rebuilds for gnome 45

---

packages/d/devhelp/package.yml
packages/d/devhelp/pspec_x86_64.xml
packages/l/libgedit-amtk/package.yml
packages/l/libgedit-amtk/pspec_x86_64.xml

**Summary**
Removes dep from devhelp and causes libgedit-amtk to replace the amtk package
**Test Plan**
Ensured that libgedit-amtk removed amtk when it's installed.
**Checklist**

Fixes for amtk

---

packages/u/upx/abi_used_symbols
packages/u/upx/package.yml
packages/u/upx/pspec_x86_64.xml

**Summary**
- Changelog can be found [here](https://github.com/upx/upx/blob/master/NEWS)
**Test Plan**
- Install `upx` and try to use it on few executables
- Try build simple C and golang program into binary executable
- Compress it with `upx` and run it
**Checklist**

upx: Update to 4.1.0

---

packages/b/bandwhich/package.yml
packages/b/bandwhich/pspec_x86_64.xml

- Various codestyle changes
- Handle IPv4-mapped IPv6 addresses when resolving connection owner
- Bump dependencies to fix a memory leak
- Logging infrastructure added
- Version flag added
- [changelog](https://raw.githubusercontent.com/imsnif/bandwhich/v0.21.1/CHANGELOG.md)
- watch traffic on different network interfaces

bandwhich: Update to 0.21.1

---

common/Scripts/buildserver-notification.sh

**Summary**
Make use of the new json output from the build page in order to obtain more reliable results.
Additionally, get the tag from the package.yml stored in the latest commit instead potentially tagging from any unstaged changes.
Lastly, take this opportunity to cleanup the script a little.
**Test Plan**
go-task notify-complete
go-task bump
go-task notify-complete <- verify the correct tag is used.
**Checklist**

common: Parse build page json in buildserver-notification.sh

---

packages/j/jtreg/package.yml
packages/j/jtreg/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

jtreg: Inclusion of homepage

---

common/Scripts/helpers.sh

**Summary**
To match .fish and .zsh helpers. Plus, it was annoying having massive pushd stacks.
**Test Plan**
Use helpers as normal, verify cd was being used
**Checklist**

common/Scripts: replace annoying pushd usage with cd in helpers.sh

---

packages/i/intel-media-driver/package.yml
packages/l/libdispatch/package.yml

**Summary**
Updates two more (last?) %patch commands to the new preferred syntax.
They weren't caught in the mass conversion due to surrounding quotes.
**Test Plan**
Built the two affected packages (I didn't include the resulting changes to reduce scope of PR but can do so if desired)
**Checklist**

repo-wide: update two more %patch commands to preferred syntax

---

packages/f/fb2converter/package.yml
packages/f/fb2converter/pspec_x86_64.xml

**Summary**
- Extending "synccovers" command to support writing thumbnails into specified directory.
- Using go 1.21 toolchain and updating all dependencies
**Test Plan**
- fb2c convert in.fb2
- skim through epub file
**Checklist**

fb2converter: Update to 1.72.1

---

packages/u/urlscan/package.yml
packages/u/urlscan/pspec_x86_64.xml

**Summary**
- Changes can be found [here](https://github.com/firecat53/urlscan/releases)
**Test Plan**
- Ran it successufully on test file
**Checklist**

urlscan: Update to 1.0.1

---

packages/p/pisi/files/emit-downloading-event.patch
packages/p/pisi/pspec.xml

**Summary**
This is required by the latest packagekit work in order to get callbacks for which packages are currently downloading in an operation.
**Test Plan**
Dogfood the patch locally for a few days
**Checklist**

pisi: emit downloading event for packagekit

---

packages/py/python-moddb/package.yml
packages/py/python-moddb/pspec_x86_64.xml

**Summary**
Changes:
- Pinned major releases of all dependencies
- Fixed improper parsing of not yet released pages
- Fixed improper parsing of get_tags when page did not have more tags
- Documented more of the utility functions
- Some enum members have been renamed to better fit with the naming pattern of the website
- Tests now produce cassettes for easy re-use
**Test Plan**
Tested a number of examples from the documentation
**Checklist**

python-moddb: update to 0.10.0

---

packages/l/libheif/abi_symbols
packages/l/libheif/abi_used_symbols
packages/l/libheif/package.yml
packages/l/libheif/pspec_x86_64.xml

**Summary**
Release notes:
- [1.17.1](https://github.com/strukturag/libheif/releases/tag/v1.17.1)
- [1.17.0](https://github.com/strukturag/libheif/releases/tag/v1.17.0)
**Test Plan**
Encoded and converted a couple of images from and to HEIF and AVIF
**Checklist**

libheif: update to 1.17.1

---

packages/s/scrcpy/abi_used_symbols
packages/s/scrcpy/package.yml
packages/s/scrcpy/pspec_x86_64.xml

**Summary**
Bump scrcpy to new release version.
[2.0 -> 2.1 Changelog](https://github.com/Genymobile/scrcpy/releases/tag/v2.1)
[2.1 -> 2.1.1 Changelog](https://github.com/Genymobile/scrcpy/releases/tag/v2.1.1)
**Test Plan**
Connected to my Android phone with ADB enabled.
Started scrcpy and checked if i can control my phone from computer, using mouse and keyboard.
Checked that audio is also forwarded to computer.
**Checklist**

scrcpy: update to 2.1.1

---

packages/a/android-tools/abi_used_symbols
packages/a/android-tools/package.yml
packages/a/android-tools/pspec_x86_64.xml

**Summary**
Update android-tools to latest release 34.0.4
Changelog can be found [here](https://developer.android.com/tools/releases/platform-tools#3404_july_2023)
**Test Plan**
Tried few adb commands, like `adb shell` and `adb install`
**Checklist**

android-tools: update to 34.0.4

---

packages/py/python-maturin/abi_used_symbols
packages/py/python-maturin/package.yml
packages/py/python-maturin/pspec_x86_64.xml

**Summary**
Changes:
- Use external `uniffi-bindgen` if no root package is configured
- Fix wheel filename for GraalPy
- Pytest skeleton in mixed template
- Keep trailing newlines from templates
- Auto-detect Python 3.13
- Fix missing `workspace.members` in sdist
- Don't set `MACOSX_DEPLOYMENT_TARGET` for editable builds by default
- Dependency updates
**Test Plan**
**Checklist**

python-maturin: update to 1.3.1

---

packages/v/vis/abi_used_symbols
packages/v/vis/package.yml
packages/v/vis/pspec_x86_64.xml

**Summary**
- Full changelog can be found [here](https://github.com/martanne/vis/releases/tag/v0.8)
**Test Plan**
- Edit text file and try to get out
**Checklist**

vis: Update to 0.8

---

packages/u/udftools/abi_used_symbols
packages/u/udftools/package.yml
packages/u/udftools/pspec_x86_64.xml

**Summary**
- Changes in 2.3 
- mkudffs: 
- Added support for creating Multisession UDF disc images via new `--startblock` option 
- Added new options for specifying owner, organization and contact information 
- Added new option `--bootarea=mbr:sec-size` to allow specifying MBR sector size 
- Added udftools version string into Application Identifier 
- Fixed default value of Packet Length in Sparable Partition for UDF 1.50 and 2.00 rev to 32 blocks 
- Fixed detecting all 33 types of optical discs defined in all versions of SCSI MMC specifications 
- Fixed filling CHS sector number into MBR partition table 
- Fixed alignment of VAT block for CD-R, DVD-R and BD-R disc 
- Fixed alignment for CD-R discs 
- Fixed generating unclosed CD-R image with blocks more than 3072 
- udfinfo & udflabel: …

udftools: Update to 2.3

---

packages/f/font-sarasa-gothic/package.yml
packages/f/font-sarasa-gothic/pspec_x86_64.xml

**Summary**
Update to 0.42.3
**Test Plan**
- Installed locally
**Checklist**
- [v0.42.3](https://github.com/be5invis/Sarasa-Gothic/releases/tag/v0.42.3)

font-sarasa-gothic: Update to 0.42.3

---

packages/f/fontconfig/abi_used_symbols
packages/f/fontconfig/abi_used_symbols32
packages/f/fontconfig/files/0002-Enforce-sane-defaults-for-Solus.patch
packages/f/fontconfig/package.yml
packages/f/fontconfig/pspec_x86_64.xml

**Summary**
This PR updates our Solus fontconfig defaults patch to reflect the agreed-upon change from Clear Sans to Noto Sans. In addition, this changes the default Serifed font from Clear Sans to Noto Serif. 
**Test Plan**
1. Test `font-face: serif;` in a web browser on Solus, see that the displayed font is Sans Serif
2. Build fontconfig with the changes in this PR
3. Repeat the above test after restarting your browser, see that the displayed font is correctly serifed
**Checklist**

fontconfig: Fix defaults

---

packages/g/gpodder/package.yml
packages/g/gpodder/pspec_x86_64.xml

**Summary**
Changes:
- add setting to toggle sync filesize comparisons (disable if your device adds metadata)
- show remaining duration for each download in progress tab
- make file size units translatable
- add plural form of rename downloads translation string
- expand ~ and ~user in GPODDER_HOME and GPODDER_DOWNLOAD_DIR
- find channel ID in YouTube "watch" URLs
- replace deprecated Gdk.Screen methods
- update dependencies
- catch errors for directories inside sync device
- fix YouTube GDPR issues by setting consent cookie in get_channel_id_url()
**Packaging changes:** Use `checkdeps`
**Test Plan**
- Added a new podcast, downloaded and watched an episode
**Checklist**

gpodder: update to 3.11.4

---

packages/g/gnome-shell-extension-speedinator/package.yml
packages/g/gnome-shell-extension-speedinator/pspec_x86_64.xml

**Summary**
- Replacement for gnome-shell-extension-impatience, resolves #680.
**Test Plan**
- Install, relog, enable extension. Visibly see animation speedups.
**Checklist**

gnome-shell-extension-speedinator: Initial inclusion

---

packages/g/gnome-shell-extension-speedinator/files/0001-prefs.js-Add-a-0.75-option-in-animation-scale.patch
packages/g/gnome-shell-extension-speedinator/files/0001-schemas-Set-the-default-value-to-0.75-to-match-impat.patch
packages/g/gnome-shell-extension-speedinator/package.yml
packages/g/gnome-shell-extension-speedinator/pspec_x86_64.xml

**Summary**
- To provide a better seamless upgrade.
**Test Plan**
On a VM, install the extension and verify the new defaults took place.
**Checklist**

gnome-shell-extension-speedinator: Match impatience defaults

---

packages/g/gnome-desktop-branding/package.yml
packages/g/gnome-desktop-branding/pspec_x86_64.xml

**Functional Changelog**
- Enable speedinator by default to replace impatience
**Test Plan**
Verify changes took place in a gnome session.
**Checklist**

gnome-desktop-branding: Update to v18

---

packages/w/wine/abi_used_symbols
packages/w/wine/abi_used_symbols32
packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
- Mono engine updated to version 8.1.0
- More DirectMusic implementation
Full release notes available [here](https://www.winehq.org/announce/8.19)
**Test Plan**
- Used several Wine apps like `winecfg`, `winefile`, `wineconsole`
- Played Age of Empires 1 Demo using `wine`
**Checklist**

wine: Update to 8.19

---

packages/v/vkbasalt/abi_used_symbols
packages/v/vkbasalt/abi_used_symbols32
packages/v/vkbasalt/package.yml
packages/v/vkbasalt/pspec_x86_64.xml

**Summary**
- Fixed build with GCC 12
**Test Plan**
-  Test various effect with Borderlands 2 on AMD GPU (Polaris)
**Checklist**

vkbasalt: Update to 0.3.2.10

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

- Fix mark placement for U+024F.
- Make the tailed variants of i and l use the fully-tailed shape even when upright, as is consistent with t = bent-hook
- The old, slightly-curly variants for i, l, iota (ι) and tau (τ) are moved to semi-tailed variants.
- Make Cyrillic Yat to follow Yeri variants. Italic Yat will also respond to variants of n.
- Add short-tailed lowercase tau (τ)
- Fix tailed variants for U+02A0.
- Stylistic set fixes
- Refine shape of flat 5
- Add tailed lower lambda
- Add Chancery and Semi-Chancery variants for lowercase x and Greek Chi
- Add arrow-lr ligation group for C-like's spaceship operators
- Add raised cap-height cent sign (¢) variants to VSAM
- [changelog](https://raw.githubusercontent.com/be5invis/Iosevka/v27.3.1/CHANGELOG.md)

font-iosevka-ttf: Update to 27.3.1

---

packages/f/font-firacode-nerd/files/nerd-fonts.metainfo.xml
packages/f/font-firacode-nerd/package.yml
packages/f/font-firacode-nerd/pspec_x86_64.xml

Add appstream metainfo to nerd-fonts as part of #449
Installed font eopkg. Verified fonts appear in Font Management Ran `appstream-builder --packages-dir=. --include-failed -v`
**Checklist**

Add metadata to nerd-fonts

---

packages/w/wayland-utils/abi_used_symbols
packages/w/wayland-utils/package.yml
packages/w/wayland-utils/pspec_x86_64.xml

**Summary**
- Fix spurious tab/space
- Adds a command line option `--interface` (`-i`) which prints the information only for the given interface
- Full changelog can be found [here](https://gitlab.freedesktop.org/wayland/wayland-utils/-/compare/1.1...1.2?from_project_id=7032&straight=false)
**Test Plan**
- Run `wayland-info -i 'wl_compositor'`
**Checklist**

wayland-utils: Update to 1.2.0

---

packages/w/weechat/package.yml
packages/w/weechat/pspec_x86_64.xml

**Summary**
- Fix crash when a custom bar item name is already used by a default bar item
- Fix random timeouts when a lot of concurrent processes are launched with hook_process
- Revert compute of nick colors to case sensitive way, deprecate again infos `irc_nick_color` and `irc_nick_color_name`
**Test Plan**
- Connect irc.libera.chat
- Join #solus channel and chat to void
**Checklist**

weechat: Update 4.1.1

---

packages/f/font-sarasa-gothic/files/sarasa-gothic.metainfo.xml
packages/f/font-sarasa-gothic/package.yml
packages/f/font-sarasa-gothic/pspec_x86_64.xml

Add appstream metainfo to sarasa-gothic as part of #449
Installed font eopkg. Verified fonts appear in Font Management
Ran `appstream-builder --packages-dir=. --include-failed -v` and verified there are no errors
**Checklist**

sarasa-gothic font: add appstream metainfo

---

packages/w/whois/abi_used_symbols
packages/w/whois/package.yml
packages/w/whois/pspec_x86_64.xml

**Summary**
- Full changelog can be found [here](https://raw.githubusercontent.com/rfc1036/whois/v5.5.19/debian/changelog)
- Added `homepage` key to `package.yml` part of #411
**Test Plan**
- Run `whois getsol.us` and get expected information
**Checklist**

whois: Update to 5.5.19

---

packages/p/packagekit/abi_used_symbols
packages/p/packagekit/files/0001-data-Tweak-systemd-network-targets-to-get-offline-up.patch
packages/p/packagekit/package.yml
packages/p/packagekit/pspec_x86_64.xml

**Summary**
Depends on #549.
- Removing and installing packages in gnome-software now works reliably.
- Gnome-software now installs updates offline.
- Getting updates is now significantly quicker.
- Getting package details is now significantly quicker.
**Test Plan**
Tested by running pisibackend.py commands manually and dogfooding gnome-software
**Checklist**

packagekit: sync with git

---

packages/u/urw-core35-fonts/package.yml
packages/u/urw-core35-fonts/pspec_x86_64.xml

**Summary**
- Mainly to fix letter te (afii10084) in Nimbus Sans Bold(Italic)
- Adding `homepage` key to `package.yml`( Part of getsolus#411)
**Test Plan**
- Render text with the fonts
**Checklist**

urw-core35-fonts: Update to 20200910

---

packages/n/nvidia-vaapi-driver/abi_used_symbols
packages/n/nvidia-vaapi-driver/files/fix-issue-with-newer-545-driver.patch
packages/n/nvidia-vaapi-driver/package.yml
packages/n/nvidia-vaapi-driver/pspec_x86_64.xml

**Summary**
This patch adds support for the new 545.29.02 driver (and up).
**Test Plan**
Confirmed video acceleration in Firefox works with the new driver
**Checklist**

nvidia-vaapi-driver: Add compatibility patch for stable 545 driver

---

packages/s/sof-firmware/package.yml
packages/s/sof-firmware/pspec_x86_64.xml

**Summary**
The SOF v2.7.1 contains important fixes to Intel Meteor Lake platforms.
Full release notes [here](https://github.com/thesofproject/sof-bin/releases/tag/v2023.09.1)
**Test Plan**
Verified firmware files were installed to correct paths. Restarted pipewire.
**Checklist**

sof-firmware: update to 2.7.1

---

packages/n/noto-sans-ttf/files/noto-sans-ttf.metainfo.xml
packages/n/noto-sans-ttf/files/noto-serif-ttf.metainfo.xml
packages/n/noto-sans-ttf/package.yml
packages/n/noto-sans-ttf/pspec_x86_64.xml

Add appstream metainfo to noto-sans-ttf as part of #449
Installed font eopkgs. Verified fonts appear in Font Management - noto sans, noto serif, noto color emoji Verified /usr/share/fonts/conf.d/66-noto-color-emoji.conf created as valid symlink Ran `appstream-builder --packages-dir=. --include-failed -v`
**Checklist**

noto-sans-ttf: add appstream metainfo

---

packages/g/gpxsee/abi_used_symbols
packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- New GUI icons that fit the current platform styles.
- Added "Open directory" action for desktop systems.
- Fixed/improved vector maps path label layout algorithm.
**Test Plan**
**Checklist**

gpxsee: Update to 13.10

---

packages/v/vnstat/abi_libs
packages/v/vnstat/abi_symbols
packages/v/vnstat/abi_used_symbols
packages/v/vnstat/package.yml
packages/v/vnstat/pspec_x86_64.xml

**Summary**
- Full changelog can be found here:
- [2.11](https://github.com/vergoh/vnstat/releases/tag/v2.11)
- [2.10](https://github.com/vergoh/vnstat/releases/tag/v2.10)
- [2.9](https://github.com/vergoh/vnstat/releases/tag/v2.9) 
- Added `homepage` key to `package.yml` part of #411
**Test Plan**
- Monitor network speed and make log of it
**Checklist**

vnstat: Update 2.11

---

packages/w/wireguard-tools/abi_used_symbols
packages/w/wireguard-tools/package.yml
packages/w/wireguard-tools/pspec_x86_64.xml

**Summary**
- The `git` commit can be found [here](https://git.zx2c4.com/wireguard-tools/log/?h=v1.0.20210914)
**Test Plan**
- Start a connection using `wg-quick`
- Start connection using `gnome-control-center`
**Checklist**

wireguard-tools: Update to 1.0.20210914

---

packages/w/wireless-regdb/package.yml
packages/w/wireless-regdb/pspec_x86_64.xml

**Summary**
- Add support for US S1G channels
- Remove PTMP-ONLY from 5850-5895 MHz for US
- Update regulatory rules for: 
- Australia
- Turkiye
- Egypt 
- Philipines 
- Hong Kong 
- India 
- Russia 
- Japan 
- Switzerland 
- Brazil 
- Bulgaria 
- Israel 
- Netherlands
- Full `git` commit can be found [here](https://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git//log/?h=master-2023-09-01)
**Test Plan**
**Checklist**

wireless-regdb: Update to 2023.09.01

---

packages/p/papirus-icon-theme/package.yml

**Summary**
Release notes can be found [here](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/releases/tag/20231101)
**Test Plan**
- Set icon theme to Papirus, browsed through system folders and menu
- Checked icons in Software Center
**Checklist**

papirus-icon-theme: Update to 20231101

---

packages/m/msmtp/abi_used_symbols
packages/m/msmtp/package.yml
packages/m/msmtp/pspec_x86_64.xml

**Summary**
Bugfixes:
- Generation of Message-ID headers was improved to avoid problems with rspamd assigning SPAM points
- Documentation of ignored options was fixed
- The combination of envelope from addresses with wildcards and automatic account selection was fixed
- Fixes the allow_from_override command
- Fixes XOAUTH2 authentication with some servers
Enhancements:
- Add the from_full_name command
- msmtpq script updates
- [msmtp news](https://marlam.de/msmtp/news/)
**Test Plan**
Installed and sent a test email.
**Checklist**

Update msmtp to 1.8.25

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- tailscale cert command renews in the background. The current certificate only displays if it has expired.
- tailscale status command displays a message about client updates when newer versions are available
- tailscale up command displays a message about client updates when newer versions are available
- Taildrop now resumes file transfers after partial transfers are interrupted
- Taildrop prevents file duplication
- Taildrop detects conflicting file transfers and only proceeds with one transfer
- Wake on LAN (WoL) is now supported for peer node wake-ups
- TCP DNS queries are speculatively started if UDP hasn’t responded quickly enough
- Truncated UDP DNS results are properly retried using TCP
- Go is updated to version 1.21.3
- tailscale set command flag --auto-update is …

tailscale: Update to 1.52.1

---

packages/o/osinfo-db-tools/package.yml
packages/o/osinfo-db-tools/pspec_x86_64.xml

**Summary**
Changes:
- Added `--nightly` option to osinfo-db-import
- Several translation improvements
**Test Plan**
Built `osinfo-db`
**Checklist**

osinfo-db-tools: Update to 1.11.0

---

packages/o/osinfo-db/package.yml
packages/o/osinfo-db/pspec_x86_64.xml

**Summary**
Changes:
- Added Mageia 9
- Fixed incorrect kernel/initrd entries
- Fixed/updated ISO links
Full commit log available [here](https://gitlab.com/libosinfo/osinfo-db/-/compare/v20230719...v20231027?from_project_id=1414771&straight=false)
**Test Plan**
Checked "Mageia 9" was available as an option in `gnome-boxes`
**Checklist**

osinfo-db: Update to 20231027

---

packages/m/mu/abi_used_symbols
packages/m/mu/package.yml
packages/m/mu/pspec_x86_64.xml

**Summary**
- guile: fix module installation path
- infodir: allow passing absolute path
- mu4e-view: assign gnus-article-buffer
- mu4e: fix completion with non-quick keys
**Test Plan**
- mu index; search for and view message with mu4e
**Checklist**

mu: Update to 1.10.8

---

packages/k/kitty/abi_used_libs
packages/k/kitty/abi_used_symbols
packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
- Allow easily running arbitrarily complex remote control scripts without needing to turn on remote control
- A new escape code that can be used by programs running in the terminal to change the shape of the mouse pointer
- Graphics protocol: Support for positioning images relative to other images
- A new option single_window_padding_width to use a different padding when only a single window is visible
- A new mouse action mouse_selection word_and_line_from_point to select the current word under the mouse cursor and extend to end of line
- A new option underline_hyperlinks to control when hyperlinks are underlined
- Allow using the full range of standard mouse cursor shapes when customizing the mouse cursor
- kitten @ set-background-opacity --toggle - a new flag to easily …

kitty: Update to 0.31.0

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Disunify anonymous untagged variant selectors for Cyrillic Capital Yeri/Yery for consistency in style-driven configurations.
- Make LATIN CAPITAL LETTER Y WITH LOOP (U+1EFE) follow variants of capital Y (cv24) for a more balanced slab-italic form like that of Cyrillic Capital U.
- Remove base-serifed-only variants for CYRILLIC SMALL LETTER STRAIGHT U (U+04AF, U+04B1).
- Add characters: LEFTWARDS HARPOON WITH BARB UP TO BAR (U+2952) DOWNWARDS HARPOON WITH BARB LEFT FROM BAR (U+2961)
- Fix overlapping serifs of italic Yat
- Fix width of VERY MUCH GREATER-THAN (U+22D9)
- Remove duplicate variants for U+0181, U+018A, U+01A4, and U+2C64.
- Remove asymmetric variants for small capital B (U+0299, U+1D03) and Cyrillic Lower Ve (U+0432)
**Test Plan** …

font-iosevka-ttf: Update to 27.3.4

---

packages/m/mpd/abi_used_symbols
packages/m/mpd/package.yml
packages/m/mpd/pspec_x86_64.xml
packages/w/wildmidi/abi_libs
packages/w/wildmidi/abi_symbols
packages/w/wildmidi/abi_used_libs
packages/w/wildmidi/abi_used_symbols
packages/w/wildmidi/files/wildmidi.cfg
packages/w/wildmidi/package.yml
packages/w/wildmidi/pspec_x86_64.xml

**Summary**
- Changelog:
- 0.45: 
- Fixed MUS drum channels 9 and 15 being swapped if the same file is played twice from the same memory buffer 
- Player: Fixed save midi reading wrong argv if there are no paths separators
- 0.44:
- Fixed integer overflow in midi parser sample count calculation
- Fixed 8 bit ping pong GUS patch loaders - Fixed wrong variable use in reverb code - Reset block status of tty after playback - Fixed broken file name handling for 'save as midi' command during playback
- Clamp MUS volume commands - CMake project improvements - `cmake` version 3.1 or newer is now required
- Added `freepats` to `rundeps` and `pkgconfig(alsa)` to `builddeps`
**Test Plan**
- Run `wildimidi -t` to run sample midi
- Play several …

wildmidi: Update to 0.45

---

packages/a/allegro4/abi_used_symbols
packages/a/allegro4/package.yml
packages/a/allegro4/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**
**Comment**
Is there any reason we keep this package? it seems only `liberation-circuit` need this and already replaced by allegro5 (`allegro`)

allegro4: homepage inclusion

---

packages/s/syncthing/files/syncthing.metainfo.xml
packages/s/syncthing/package.yml
packages/s/syncthing/pspec_x86_64.xml

**Summary**
Bugfixes:
- Omitting %s from LDAP search filter results in corrupt search filter
- Posting config with invalid versioner type causes panic
- Deduplicated files on Windows aren't treated as regular files any more (Go 1.21)
- Syncthing Docker container fails to start if underlying filesystem doesn't support `chown`
- traefik no longer url escape X-Forwarded-Tls-Client-Cert header
- Favicon is stuck in notify state
Enhancements:
- Use a real login screen + sessions instead of HTTP basic auth
- [1.26.0](https://github.com/syncthing/syncthing/releases/tag/v1.26.0)
Solus:
- Add appdata metainfo file
**Test Plan**
- Loaded the syncthing web UI, verified I can see shares and UI works normally
- Exercised Syncthing-GTK
- Verified that a file shared between the …

syncthing: update to 1.26.0

---

packages/s/syncthing/package.yml
packages/s/syncthing/pspec_x86_64.xml

**Summary**
Bugfixes:
- Display error in 1.26 with login screen
- [1.26.1](https://github.com/syncthing/syncthing/releases/tag/v1.26.1)
**Test Plan**
- Loaded the syncthing web UI, verified I can see shares and UI works normally
- Exercised Syncthing-GTK
- Verified that a file shared between the local machine and a remote machine syncs
**Checklist**

syncthing: update to 1.26.1

---

packages/a/amtk/package.yml
packages/a/amtk/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**
**Comment**
Shouldn't this be deprecated? This package is replaced by `libgedit-amtk`. I also noticed that it doesn't show on `eopkg info amtk`.

amtk: homepage inclusion

---

packages/a/acpid2/abi_used_symbols
packages/a/acpid2/package.yml
packages/a/acpid2/pspec_x86_64.xml

**Summary**
- Add `MSG_CMSG_CLOEXEC` for systems that are missing it.
- Fix a bug with input layer event table not working on 32-bit builds with 64-bit time types.
- Use binary search to find input layer events in the table.
- Use AC_PROG_CC instead of the obsolete AC_PROG_CC_STDC.
- Add support for more input layer events.
**Test Plan**
- Question : How do I test this?
**Checklist**

acpid2: Update to 2.0.34

---

packages/s/sof-firmware/files/sof-firmware.metainfo.xml
packages/s/sof-firmware/package.yml
packages/s/sof-firmware/pspec_x86_64.xml

**Summary**
For v2.7 series, topologies from 2.7.2 release have been added, including following new/updated files:
v2.7.x/sof-ace-tplg-v2.7.2
├── sof-mtl-max98357a-rt5682-ssp2-ssp0-2ch-pdm1.tplg
├── sof-mtl-max98357a-rt5682-ssp2-ssp0.tplg
├── sof-mtl-max98357a-rt5682.tplg
├── sof-mtl-rt713-l0-rt1316-l12-rt1713-l3.tplg
└── sof-mtl-rt713-l0-rt1316-l12.tplg
Full release notes [here](https://github.com/thesofproject/sof-bin/releases/tag/v2023.09.2)
**Test Plan**
Verified firmware files were installed to correct paths. Restarted pipewire.
**Checklist**

sof-firmware: update to 2.7.2

---

packages/g/gpxsee/abi_used_symbols
packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- Added support for GPSDump WPT files.
- Added "Open recent" menu.
- Huge MBTiles maps now load in a "geologically short" time.
- Vector MBTiles maps now rendered asynchronous.
- Fixed map bounds limiting.
- [changelog](https://build.opensuse.org/package/view_file/home:tumic:GPXSee/gpxsee/gpxsee.changes)
**Test Plan**
**Checklist**

gpxsee: Update to 13.11

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- update to Go 1.21.4
- improve throughput substantially for UDP packets over TUN device with recent Linux kernels
**Test Plan**
**Checklist**

tailscale: Update to 1.54.0

---

packages/f/font-terminus-console/package.yml
packages/f/font-terminus-console/pspec_x86_64.xml

**Summary**
Add the console version of the terminus monospaced font.
The intent is for this to be used in the bootloader, the kernel and by default in the linux console (ter-vXXn), which will make things look particularly sleek.
**Test Plan**
Install font-terminus-console locally and use setfont to switch to ter-v32n and observe that it looks nice on a 32" 4K monitor.
**Checklist**

font-terminus-console: Initial inclusion

---

packages/g/guayadeque/abi_used_symbols
packages/g/guayadeque/package.yml
packages/g/guayadeque/pspec_x86_64.xml
packages/w/wxsqlite3/abi_symbols
packages/w/wxsqlite3/abi_used_symbols
packages/w/wxsqlite3/package.yml
packages/w/wxsqlite3/pspec_x86_64.xml

**Summary**
- Upgrade to SQLite3 Multiple Ciphers version 1.7.0 (SQLite version 3.43.1)
- [Changelog](https://github.com/utelle/wxsqlite3/blob/v4.9.6/readme.md)
- Added `homepage` key to `package.yml` (Part of https://github.com/getsolus/packages/issues/411)
**Test Plan**
- Rebulid `guayadeque` against this package
**Checklist**

wxsqlite3: Update to 4.9.5 

---

packages/a/apr-util/abi_used_symbols
packages/a/apr-util/package.yml
packages/a/apr-util/pspec_x86_64.xml
packages/h/httpd/abi_symbols
packages/h/httpd/abi_used_symbols
packages/h/httpd/package.yml
packages/h/httpd/pspec_x86_64.xml
packages/t/tomcat-connectors/abi_symbols
packages/t/tomcat-connectors/abi_used_symbols
packages/t/tomcat-connectors/package.yml
packages/t/tomcat-connectors/pspec_x86_64.xml

**Summary**
- Changelog can be found [here](https://downloads.apache.org/apr/CHANGES-APR-UTIL-1.6)
- Added `homepage` key to `package.yml` (Part of https://github.com/getsolus/packages/issues/411)
**Test Plan**
- Rebuild `httpd` against this package
**Checklist**

apr-util: Update to 1.6.3

---

packages/a/ansible/package.yml
packages/a/ansible/pspec_x86_64.xml
packages/py/python-jmespath/MAINTAINERS.md
packages/py/python-jmespath/package.yml
packages/py/python-jmespath/pspec_x86_64.xml

**Summary**
Add the JMESPath python package, which allows you to build queries for json-documents.
This is a dependency for the `json_query` method in Ansible.
**Test Plan**
- Ran successfully a ansible run using `json_query`
**Checklist**

JMESPath: initial inclusion in the repository

---

common/CI/package_checks.py

**Summary**
Exclude merge commits from the changelog generation. See, for example, [this changelog](https://github.com/getsolus/packages/actions/runs/6975160174), which includes an entry for the merge commit.
**Test Plan**
See [this changelog](https://github.com/silkeh/packages/actions/runs/6989475137).
**Checklist**

ci/package_checks: exclude merge commits from checks/changelog

---

common/CI/package_checks.py

**Summary**
Adds a check for commit messages ending in a `]`. The comment is added on the first file of the commit if there is any.
**Test Plan**
See [this test pull request](https://github.com/silkeh/packages/pull/5/files#diff-fd36bdf870f06c81d1e087aca13513b1e87ec59e451f02eeee4e591e31a5992aR1)
**Checklist**

ci/package_checks: add check for commit message ending in `]`

---

packages/a/archivemount/abi_used_symbols
packages/a/archivemount/package.yml
packages/a/archivemount/pspec_x86_64.xml

**Summary**
- Change source to working one
**Test Plan**
**Checklist**
**Comment**
Please put this tarball [archivemount-0.9.1.tar.gz](https://github.com/getsolus/packages/files/13473834/archivemount-0.9.1.tar.gz) in source repo, the [official](https://www.cybernoia.de/software/archivemount/archivemount-0.9.1.tar.gz) one doesn't work with `go-task`.

archivemount: homepage inclusion

---

packages/a/autofs/abi_symbols
packages/a/autofs/abi_used_symbols
packages/a/autofs/package.yml
packages/a/autofs/pspec_x86_64.xml

**Summary**
- Full changelog can be found [here](https://git.kernel.org/pub/scm/linux/storage/autofs/autofs.git/plain/CHANGELOG?h=release_5_1_9&id=8c348df3dc4509e87dff6615ba7d295ca28fab63)
**Test Plan**
- Set up simple autofs mount
**Checklist**

autofs: Update to 5.1.9

---

packages/b/bibtool/abi_libs
packages/b/bibtool/abi_symbols
packages/b/bibtool/abi_used_symbols
packages/b/bibtool/package.yml
packages/b/bibtool/pspec_x86_64.xml

**Summary**
- Handling of extracting by aux file improved.
- Record extended by attribute `lineno`. This attribute carries the line number of the initiating @.
- The format of the error messages has been slightly streamlined. Double spaces are avoided; two colons in one message are avoided.
- The format of the messages of `check_rule` include file and line number.
- Warning for double fields added.
- The empty output file is used to signal that the output should be suppressed.
- The resources `check.warning.rule` and `check.error.rule` have been introduced to allow semantic checks to be classified as warning or error.
- The behaviour of the resource `check.double` has been generalized. The requirement that double entries to be adjacent has been dropped. This has the impact that the …

bibtool: Update to 2.68

---

packages/b/blosc/package.yml
packages/b/blosc/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**
**Comment**
There is new version of this at [1.21.5](https://github.com/Blosc/c-blosc/releases/tag/v1.21.5). another sidenote `openvdb` (a revdep of this package) also has new release at [11.0.0](https://github.com/AcademySoftwareFoundation/openvdb/releases/tag/v11.0.0) but it removes `python2` support. Those touch many things, it scares me. Cheers!

blosc: homepage inclusion

---

packages/x/xfce4-panel/files/0001-Use-Solus-defaults.patch
packages/x/xfce4-panel/package.yml
packages/x/xfce4-panel/pspec_x86_64.xml

**Summary**
- Add the following launchers to the default layout:
- Web browser
- File manager
- Terminal
- Software Center
- App Finder
- Increase default panel size to 36
**Test Plan**
Install the package and create a new user to observe the new defaults.
**Checklist**

xfce4-panel: Update defaults patch

---

packages/b/budgie-desktop-branding/package.yml
packages/b/budgie-desktop-branding/pspec_x86_64.xml

**Summary**
- Switch installer to Calamares in the livecd panel
**Test Plan**
See Calamares icon on the livecd panel
**Checklist**

budgie-desktop-branding: Swap to Calamares

---

.github/workflows/script_lint.yml
common/Scripts/helpers.sh

**Summary**
Add shellcheck action to the GitHub workflow to reduce the amount of bugs in shell scripts.
Currently failing scripts (and one zsh script) have been excluded.
These can be removed from the ignored scripts when they have been fixed.
Resolves https://github.com/getsolus/packages/issues/968
**Test Plan**
This PR!
**Checklist**

ci: Check shell scripts in common with shellcheck

---

packages/s/syncthing/MAINTAINERS.md
packages/s/syncthing/package.yml
packages/s/syncthing/pspec_x86_64.xml

**Summary**
Bugfixes:
- spurious log file in $XDG_CONFIG_HOME
- Discovery Returns IP
- Display error in 1.26 with login screen
Enhancements:
- Default config (state) dir on Unixes should be ~/.local/state/syncthing ($XDG_STATE_HOME/syncthing)
- Login form: login button should have an id attribute
**Test Plan**
- Restart Syncthing-GTK and verify it can connect to the syncthing backend, all folders sync
**Checklist**

syncthing: update to 1.27.0

---

packages/g/grub2/files/conf/grub
packages/g/grub2/package.yml
packages/g/grub2/pspec_x86_64.xml

**Summary**
Increase default font size to 32px (terminus bold) to help with legibility on HiDPI displays.
Additionally, set GRUB_GFXMODE 1366x768, with a 1024x768 fallback, and auto for when VM gfx adapters are genuinely clueless. This will probably work in VMs and on (most) older laptops.
Shout out to @TraceyC77 and sheepman4267 for the suggestions and valuable QA work on this.
Part of #826
**Test Plan**
- Update grub2
- run `sudo mv /etc/default/grub.newconfig /etc/default/grub`
- run `sudo clr-update-wrapper`
- reboot and check that new font is displayed in grub bootloader menu
**Checklist**

grub2: Update default config to set font to ter-32b

---

packages/k/kinfocenter/abi_used_symbols
packages/k/kinfocenter/package.yml
packages/k/kinfocenter/pspec_x86_64.xml

**Summary**
Add dependency on fwupd. This enables the Firmware Security section to work.
Fixes https://github.com/getsolus/packages/issues/307
**Test Plan**
Install the updated package in a Plasma VM and see that the Info Center panel no longer complains about missing dependencies.
**Checklist**

kinfocenter: Add dependency on fwupd

---

packages/p/pam/files/faillock.conf
packages/p/pam/package.yml
packages/p/pam/pspec_x86_64.xml

**Summary**
This commit tweaks the defaults before an account is locked from:
3 unsuccessful tries within 15 minutes => 10 minute account lockout
To:
10 unsuccesful tries within 15 minutes => 10 minute account lockout
The goal is to make fat-finger typos less punishing and frustrating. The hope is that allowing more consecutive tries before locking the user out will not punish legimate mistakes, but will still punish an attacker trying to brute-force the user's password.
Note that the NIST recommends allowing at least 10 tries here:
https://pages.nist.gov/800-63-3/sp800-63b.html#sec10
**Test Plan**
- Install the package with the new defaults
- Make the required number of unsuccessful login attempts on a virtual console
- Note how `login` helpfully mentions that the account is now locked …

pam: Set more tolerable failed login defaults

---

packages/c/clr-boot-manager/abi_used_symbols
packages/c/clr-boot-manager/files/0001-grub2-Fix-loading-kernel-and-initramfs-on-BTRFS-subv.patch
packages/c/clr-boot-manager/files/series
packages/c/clr-boot-manager/package.yml
packages/c/clr-boot-manager/pspec_x86_64.xml

**Summary**
- Fix booting with Grub on BTRFS subvolumes
**Test Plan**
Built a fresh ISO and installed using Grub on a default BTRFS layout, and rebooted successfully post-installation.
**Checklist**

clr-boot-manager: Add patch for BTRFS subvolumes

---

packages/c/calamares/files/calamares-gui
packages/c/calamares/files/patches/downstream/0001-Don-t-spawn-a-new-shell-when-starting.patch
packages/c/calamares/package.yml
packages/c/calamares/pspec_x86_64.xml

**Summary**
- Fix opening from Budgie panel
**Test Plan**
Spin a new Budgie ISO and verify that Calamares starts from the panel
**Checklist**

calamares: Fix opening from Budgie panel

---

packages/g/gpxsee/abi_used_symbols
packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- Added support for overzoom in MVT vector maps (MBTiles/online).
- Vector (MVT) online maps now rendered asynchronous.
- Fixed vector MBTiles not loading in Qt6 builds issue.
- [changelog](https://build.opensuse.org/package/view_file/home:tumic:GPXSee/gpxsee/gpxsee.changes)
**Test Plan**
**Checklist**

gpxsee: Update to 13.12

---

packages/g/gnome-desktop-branding/package.yml
packages/g/gnome-desktop-branding/pspec_x86_64.xml

**Summary**
- Center new windows in mutter by default
- Enable solus logo distributor icon in GDM
- livecd: Pin calamares to default apps
Exception for ISO freeze due to regression where the installer was not pinned to the default apps.
**Test Plan**
**Checklist**

gnome-desktop-branding: Update to v19

---

packages/c/calamares/files/install/modules/partition.conf
packages/c/calamares/files/install/modules/shellprocess_postinstall.conf
packages/c/calamares/files/patches/downstream/0001-Solus-Skip-adding-boot-partition.patch
packages/c/calamares/files/series
packages/c/calamares/package.yml
packages/c/calamares/pspec_x86_64.xml

Changes:
- Name EFI partition "EFI", which matches the os-installer naming
- Use GPT as the default partition table type
- Disable automated LUKS partitioning as it is currently broken on BIOS systems
- Comment out /boot from fstab if present. Note that this breaks BIOS installs with a dedicated boot partition.

calamares: Fix for partitioning

---

common/Scripts/helpers.sh

**Summary**
So it doesn't exit the shell.
**Test Plan**
`gotopkg grub` (grub2) doesn't exit the shell anymore
**Checklist**

common/Scripts: return 1 instead of exit 1 on err in helper.sh

---

common/CI/package_checks.py

**Summary**
Ensure that package versions are always strings and not numbers, as might happen with versions like '1.2' and '20230102'.
**Test Plan**
Manually run check against repo:
```shell
$ ./common/CI/package_checks.py **/package.yml
Checking files: <snip>
Found 234 result(s), 234 error(s)
::error file=packages/a/a2jmidid/package.yml,line=2::Package version is not a string
::error file=packages/a/accounts-qml-module/package.yml,line=2::Package version is not a string
<etc>
```
**Checklist**

ci/package_checks: add check for package version being a string

---

common/CI/package_checks.py

**Summary**
SPDX license identifiers may be a 'simple' or 'compound' expression, meaning that the following formats are also allowed:
- A document reference instead of license identifier.
- `+` after the license identifier.
- License identifier followed `WITH` and an exception identifier.
- The above split by `AND` or `OR`.
- The above contained between `()`.
All but the first case should now be valid according to the package checks. The first case is still invalid, as we want license identifiers and not document references in our packages.
See: https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/
Resolves #956
**Test Plan**
Manually run the package checks against all packages with `WITH/AND/OR` in the license:
```console
> common/CI/package_checks.py (rg 'license *:.* …
```

ci/package_checks: fix SPDX license check for WITH/AND/OR

---

common/CI/package_checks.py

**Summary**
Fix `pkgconfig32` entries not being sorted in a separate section by sorting them *before* `pkgconfig` (as that is currently most common).
Resolves #921
**Test Plan**
- Run checks against `packages/a/avahi/package.yml`, see no dependency order violation.
- Run checks against `packages/c/cups/package.yml`, see dependency order violation (it has `pkgconfig` before `pkgconfig32`).
**Checklist**

ci/package_checks: fix dependency order for `pkgconfig32`

---

packages/c/calamares/files/install/modules/partition.conf
packages/c/calamares/files/install/modules/shellprocess_postinstall.conf
packages/c/calamares/files/install/modules/users.conf
packages/c/calamares/files/patches/downstream/0001-Solus-Create-boot-partition-for-BIOS-installs.patch
packages/c/calamares/files/series
packages/c/calamares/package.yml
packages/c/calamares/pspec_x86_64.xml

Changes:
- Create a boot partition even with BIOS installs when auto-partitioning
- Set the default system hostname to `${first}-solus` instead of pulling from the platform
- Set the install back to stable if the ISO was built from unstable

calamares: More fixes

---

packages/l/libxfce4ui/files/0001-libxfce4kbd-private-Add-shortcut-for-Whiskermenu.patch
packages/l/libxfce4ui/package.yml
packages/l/libxfce4ui/pspec_x86_64.xml

**Summary**
Add default shortcut to Whiskermenu
Ref https://github.com/getsolus/packages/issues/305
**Test Plan**
Create a new user and hit the Super key. Whiskermenu pops up.
**Checklist**

libxfce4ui: Add shortcut for Whiskermenu

---

packages/x/xfce4-panel/files/0001-Use-Solus-defaults.patch
packages/x/xfce4-panel/package.yml
packages/x/xfce4-panel/pspec_x86_64.xml

**Summary**
- Enable icon scaling in the system tray by default
Ref https://github.com/getsolus/packages/issues/305
**Test Plan**
Created a new user and saw that the network-manager-applet icon now scales with the other icons
**Checklist**

xfce4-panel: Enable icon scaling in the system tray by default

---

common/CI/package_checks.py

**Summary**
Fix the package check triggering on packages not in the ISO.
**Test Plan**
Run the checks on `font-ibm-plex` and see no warning. Run the check on `linux-current` and see a warning.
**Checklist**
n/a

ci/package_checks: fix check for frozen packages

---

packages/l/libxfce4ui/files/0001-libxfce4kbd-private-Add-shortcut-for-Whiskermenu.patch
packages/l/libxfce4ui/package.yml
packages/l/libxfce4ui/pspec_x86_64.xml

**Summary**
Fix a malformed XML tag which was keeping XFCE from recognizing any of the window manager keyboard shortcuts
**Test Plan**
1. Open XFCE Window Manager settings
2. Go to the "Keyboard" tab
3. Click "Reset to defaults"
4. See that there are no configured keyboard shortcuts
5. Rebuild `libxfce4ui` against unstable with changes from this PR
6. Install the new package to your XFCE system
7. Reset window manager shortcuts to default again
8. See that keyboard shortcuts are configured now
**Checklist**

libxfce4ui: Fix Keyboard Shortcuts

---

packages/f/font-ibm-plex/files/ibmplex.metainfo.xml
packages/f/font-ibm-plex/package.yml
packages/f/font-ibm-plex/pspec_x86_64.xml

**Summary**
IBM PLEX SERIF
- Added support for monotonic Greek (74 glyphs per font)
- Replaced commaaccent with cedilla in glyphs /Tcedilla /tcedilla
- Disabled bit 38 (Mathematical Operators) from OS/2 UnicodeRanges
- Improved hinting
- Fixed FamilyClass value in OS/2 table
- Fixed STAT table; Roman and Italic styles are correctly linked in various environments now
- Fixed incorrect behaviour in Adobe InDesign
- Fixed inconsistencies in vertical alignment
IBM PLEX SANS
- Added new glyphs
- Fixed FamilyClass value in OS/2 table
- Fixed STAT table; Roman and Italic styles are correctly linked in various environments now
- Fixed incorrect behaviour in Adobe InDesign
- Fixed inconsistencies in vertical alignment
- Replaced commaaccent with cedilla in glyphs /Tcedilla /tcedilla
- Disabled bit …

font-ibm-plex: Update to 6.3.0

---

packages/l/libwebkit-gtk/abi_used_symbols
packages/l/libwebkit-gtk/package.yml
packages/l/libwebkit-gtk/pspec_x86_64.xml
packages/l/libwebkit-gtk41/abi_used_symbols
packages/l/libwebkit-gtk41/package.yml
packages/l/libwebkit-gtk41/pspec_x86_64.xml

**Summary**
Update to 2.42.4 for https://seclists.org/oss-sec/2023/q4/290. @HarveyDevel updated `libwebkit-gtk5`.
**Test Plan**
Rebuilt, installs correctly
**Checklist**

Update libwebkit-gtk to 2.42.4

---

packages/g/gnome-desktop-branding/package.yml
packages/g/gnome-desktop-branding/pspec_x86_64.xml

**Summary**
- Change background to rivers and mountains
- Slightly increase mono font size
- Merge in defaults from gsettings-desktop-schemas
**Test Plan**
Spin a smoketest ISO with this package, verify changes
**Checklist**

gnome-desktop-branding: Sync with git

---

packages/t/thunar-shares-plugin/files/0001-tsp-page-Replace-gnome-fs-share-with-folder-publicsh.patch
packages/t/thunar-shares-plugin/package.yml
packages/t/thunar-shares-plugin/pspec_x86_64.xml

**Summary**
- As icon themes have begun to stop providing this icon
**Packager's Notes**
- This patch has been submitted upstream
**Test Plan**
- Verify icon gets picked from user theme
**Checklist**

thunar-shares-plugin: Replace gnome-fs-share with folder-publicshare

---

packages/s/slick-greeter/files/series
packages/s/slick-greeter/files/solus-change-greeter-box-opacity.patch
packages/s/slick-greeter/package.yml
packages/s/slick-greeter/pspec_x86_64.xml

**Summary**
This solves the issue where greeter text is hard to read when using bright backgrounds.
**Test Plan**
- Spun up an XFCE VM and took screenshots of the unmodified and the modified greeter.
- Saw that the modified greeter had a darker background as expected.
**Checklist**

slick-greeter: Make greeter box much more opaque

---

packages/x/xfce4-desktop-branding/package.yml
packages/x/xfce4-desktop-branding/pspec_x86_64.xml

**Summary**
- slick greeter overrides are now correctly applied.
**Test Plan**
- install, logout, verify slick greeter defaults were changed
**Checklist**

xfce4-desktop-branding: Sync with git

---

packages/b/brother-dcp135c/abi_libs
packages/b/brother-dcp135c/abi_symbols
packages/b/brother-dcp135c/abi_used_symbols
packages/b/brother-dcp135c/package.yml
packages/b/brother-dcp135c/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

brother-dcp135c: homepage inclusion

---

packages/x/xfce4-desktop-branding/package.yml
packages/x/xfce4-desktop-branding/pspec_x86_64.xml

**Summary**
- Update default bg image for desktop and greeter
- Move notifyd text boxes to bottom right
- Remove deprecated [SeatDefaults] config section
**Test Plan**
Build an ungodly number of XFCE smoketest ISOs and test that they work as advertised above.
**Checklist**

xfce4-desktop-branding: sync with latest git

---

packages/g/grub2/files/conf/grub
packages/g/grub2/package.yml
packages/g/grub2/pspec_x86_64.xml

**Summary**
On BIOS-based virt-manager VMs, the grub2 graphics mode defaults to VGA 640x480 if no configuration changes are made to the `GRUB_GFXMODE` stanza in `/etc/default/grub`.
However, it turns out that the BIOS on the emulated VGA card supports the 1280x800 mode, which makes the default ter-32b font we use much more usable compared to when it is used in 640x480.
At the same time, 1280x800 is a resolution that is so unusual, that almost no physical displays and almost no real world VGA BIOSes support it.
And if -- against expectations -- a physical GPU+Display combination turns out to support 1280x800, the resolution is large enough that the ter-32b font will still yield a 80x25 display and look nice in doing so.
**Test Plan**
This was tested in both a virt-manager VM and two …

grub2: Improve default resolution settings

---

packages/c/calamares/files/install/modules/displaymanager.conf
packages/c/calamares/files/install/settings.conf
packages/c/calamares/package.yml
packages/c/calamares/pspec_x86_64.xml

**Summary**
- Enable autologin support
**Test Plan**
Install the system with the user set to be automatically logged in on Budgie and XFCE.
**Checklist**

calamares: Enable the displaymanager module for autologin

---

packages/c/calamares/files/install/settings.conf
packages/c/calamares/package.yml
packages/c/calamares/pspec_x86_64.xml

Enables the hwclock and networkcfg modules by default. Both do not have configuration or UI and do the following:
hwclock: Synchronizes the hardware clock with the current live environment time. Helpful since we enable systemd-timesyncd by default, so if a user connects to a network they will end up with accurate time being persisted.
networkcfg: If the user has setup a custom network configuration in the live environment (for instance connecting to wifi) then that will be copied to the installed system.

calamares: Enable hwclock and networkcfg

---

packages/c/calamares/files/patches/downstream/0001-partition-Hide-Volume-Group-buttons.patch
packages/c/calamares/files/series
packages/c/calamares/package.yml
packages/c/calamares/pspec_x86_64.xml

**Summary**
- Hide LVM buttons to prevent crashes
**Test Plan**
Update Calamares in a live session and choose manual partitioning; observed that the LVM buttons are no longer shown.
**Checklist**

calamares: Hide LVM buttons

---

packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- Fixed broken map scale (ruler) on HiDPI maps.
- Limit the overzoom to not produce huge tiles which break map rendering.
**Test Plan**
- open map, zoom in and out
**Checklist**

gpxsee: Update to 13.13

---

packages/t/tailscale/abi_used_symbols
packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- Web interface redirects to the correct self IP known by source peer
- Usage of slices.Compact from app connector domains list
- improve responsiveness under load, especially with bidirectional traffic
- improve UPnP portmapping
- add tailscale whois subcommand to observe metadata associated with a Tailscale IP
- include tailnet name and profile ID in tailscale switch --list to disambiguate profiles with common login names
- make System policies beta
- improve tailscale web interface for configuring some device settings such as exit nodes, subnet routers, and Tailscale SSH
- improve containerboot to symlink its socket file if possible, making the tailscale CLI work without --socket=/tmp/tailscale.sock
**Test Plan**
**Checklist**

tailscale: Update to 1.56.1

---

.github/ISSUE_TEMPLATE/request-package-update.yml

This is meant to deter package update request with no specific reason other than "tHiS Is ThE nEwEst vErsIoN".

.github: Change wording in "Request Package Update"

---

packages/c/c-ares/abi_used_symbols
packages/c/c-ares/package.yml
packages/c/c-ares/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**
**Comment**
There is [newer version](https://c-ares.org/download/c-ares-1.24.0.tar.gz) of this. But it touches too many apps i am not familiar with. (bzflag, grpc,nodejs, wireshark)

c-ares: homepage inclusion

---

packages/c/cd-discid/package.yml
packages/c/cd-discid/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**
**Comment**
This is an old package, unmaintained since 2013. Still works though.

cd-discid: homepage inclusion

---

packages/c/cantarell-fonts/package.yml
packages/c/cantarell-fonts/pspec_x86_64.xml

**Summary**
Replaced homepage to more representative one
**Test Plan**
**Checklist**
**Comment**
This package is already include metainfo.xml but there is no preview in software center. Why?

 cantarell-fonts: Replace homepage to more representative one

---

packages/c/calamares/files/install/modules/partition.conf
packages/c/calamares/package.yml
packages/c/calamares/pspec_x86_64.xml

**Summary**
- It is now working again on BIOS since 5614c7fa149899998b28677eef76a94cd13a1a71 as we now always create a boot partition.
**Test Plan**
- GNOME, BIOS + LUKS + BTRFS + Swap partition <- OK (swap partition is encrypted as well)
- GNOME, BIOS + LUKS + EXT4 + Swapfile <- OK
(UEFI was known good working before disabling)
**Checklist**

calamares: Reenable automatic LUKS partitioning

---

packages/s/sshfs-fuse/abi_used_symbols
packages/s/sshfs-fuse/package.yml
packages/s/sshfs-fuse/pspec_x86_64.xml

**Summary**
This fixes an issue reported where browsing files via kdeconnect was no longer possible.
**Test Plan**
Browse files on phone from kdeconnect.
**Checklist**

sshfs-fuse: Fix PubkeyAcceptedKeyTypes

---

packages/f/fd/abi_used_libs
packages/f/fd/abi_used_symbols
packages/f/fd/package.yml
packages/f/fd/pspec_x86_64.xml

**Summary**
Bugfixes:
- 9.0.0
- Fix `NO_COLOR` support
- 8.7.1
- `-1` properly conflicts with the exec family of options.
- `--max-results` overrides `-1`
- `--quiet` properly conflicts with the exec family of options. This used to be the case, but broke during the switch to clap-derive
- `--changed-within` now accepts a space as well as a "T" as the separator between date and time (due to update of chrono dependency)
Enhancements:
- Performance has been significantly improved
- Support character and block device file types
- Breaking: `.git/` is now ignored by default when using `--hidden` / `-H`, use `--no-ignore` / `-I` or `--no-ignore-vcs` to override
- [Changelog](https://github.com/sharkdp/fd/blob/master/CHANGELOG.md)
**Test Plan**
Installed and executes some …

fd: Update to 9.0.0

---

packages/g/gpxsee/abi_used_symbols
packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- Removed 4Umaps map source (map service discontinued)
- Added mtbmap.cz map source.
- Multiple minor map formats fixes/improvements (TrekBuddy, IMG).
**Test Plan**
**Checklist**

gpxsee: Update to 13.14

---

packages/f/fb2converter/package.yml
packages/f/fb2converter/pspec_x86_64.xml

**Summary**
- Optimized PNGs will only be used if smaller in size
- Added debug level log
- Added some image size optimization
**Test Plan**
- convert fb2 file; view produced epub
**Checklist**

fb2converter: Update to 1.73.1

---

packages/c/compiz-bcop/package.yml
packages/c/compiz-bcop/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

compiz-bcop: homepage inclusion

---

packages/b/blender/abi_used_symbols
packages/b/blender/package.yml
packages/b/blender/pspec_x86_64.xml

**Summary**
Reverted Blender to v4.0.0 and ROCm 5.5 and compiled for more GPU arches.
**Test Plan**
Rendered the BMW27 example with HIP Cycles: `blender -b BMW27.blend -f 0 -- --cycles-device HIP`
**Checklist**

blender: revert to ROCm 5.5 and add more supported GPU arches

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Fix leaning marks of turned capital F/L
- Fix overlay bar placement of Z with Hook and Z with Swash Tail
- Fix attachment of descender parts of Cyrillic Lower Ha/X under x = cursive
- Make the Eng part in LATIN SMALL LETTER FENG DIGRAPH always connected to the f part
- Fix top bar shape in CYRILLIC CAPITAL LETTER DJE
- Fix leaning marks placement for reversed k/F/P
- Remove tailless variants for Latin Iota (U+0196, U+0269) and Cyrillic Iota (U+A646, U+A647).
- Fix slash ligations when frac feature is enabled
- Fix leaning marks of turned r
- Refine shape of Tshe and Cyrillic Capital Letter Te with Middle Hook (U+A68A)
- Remove bottom serif of Cyrillic Small Letter Ghe with Middle Hook (U+0495) under italics.
- Make serif variants of Cyrillic Small Letter …

font-iosevka-ttf: Update to 28.0.4

---

packages/c/cmus/abi_symbols
packages/c/cmus/abi_used_symbols
packages/c/cmus/package.yml
packages/c/cmus/pspec_x86_64.xml

**Summary**
- Changelog:
- Implement smart ReplayGain setting
- Start from end on player-prev with no current track
- Add reshuffle when current track has disappeared
- Make tracks hold shuffle info
- Use a direct album reference in AAA filter
- Add an album shuffle mode
- Add "player-next-album" and "player-prev-album" commands
- Rename "shuffle" command to "reshuffle"
- Reset position in shuffle list after a manual reshuffle
- Fixes channel map for multichannel flac files
- Replaces improper `fcntl` with `ioctl` in `op/oss`
- Removes unmaintained notice
- Initialize active to zero in `print_editable`
- Allow output plugins to have multiple mixer FD lists
- Preserve compatibility with `ABI v1` output plugins
- Implement `pause_on_output_change` option
- Implement `MIXER_FDS_OUTPUT` for …

cmus: Update to 2.10.0

---

packages/x/xfdesktop/abi_used_symbols
packages/x/xfdesktop/package.yml
packages/x/xfdesktop/pspec_x86_64.xml

**Summary**
- Add xfce4-screensaver as a runtime dependency
This ensures that the screensaver is installed on updating.
**Test Plan**
Install this updated and see that the screensaver package is also installed.
**Checklist**

xfdesktop: Add xfce4-screensaver as a runtime dependency

---

packages/a/autoconf-archive/package.yml
packages/a/autoconf-archive/pspec_x86_64.xml

**Summary**
- Full changelog can be found inside source [tarball](http://ftp.wayne.edu/gnu/autoconf-archive/autoconf-archive-2023.02.20.tar.xz)
**Test Plan**
- Rebuild `mate-desktop` against this package locally
**Checklist**

autoconf-archive: Update to 2023.02.20

---

packages/c/convmv/package.yml
packages/c/convmv/pspec_x86_64.xml

**Summary**
- Changelog :
- 2.05 : 
- allow NFC/NFD conversion on APFS volumes, add man page section for that filesystem 
- use case- and normalization-insensitivity workarounds also for parsable mode
- 2.04 :
- check for valid utf-8 also in `upperlower_checkenc()`
- fix parsable output, missed the path files to run utime() on - add `--run-parsable` option to blindly run what a file generated with `--parsable` tells us to do
- 2.03 : 
- fix man page build due to non-ASCII char
- 2.02 :
- add option `--caseful-sz` to optionally treat upper-/lowercasing of sz. This also fixes unwanted unidirectional lowercasing of U+1E9E
- 2.01 :
-  map : instead of / in SFU mapping tables
- Added `homepage` key to `package.yml` (Part of getsolus/packages/issues/411)
**Test Plan**
- Change encoding of a few …

convmv: Update to 2.05

---

packages/s/sof-firmware/package.yml
packages/s/sof-firmware/pspec_x86_64.xml

**Summary**
For v2.8 series, the following new topology files have been added since v2.7:
```
v2.8.x/sof-ace-tplg-v2.8
├── sof-mtl-cs42l43-l0-cs35l56-l12.tplg
├── sof-mtl-rt722-l0.tplg
```
Full release notes [here](https://github.com/thesofproject/sof-bin/releases/tag/v2023.12)
**Test Plan**
Verified firmware files were installed to correct paths. Restarted pipewire.
**Checklist**

sof-firmware: update to 2.8

---

packages/l/libuv/abi_used_symbols
packages/l/libuv/package.yml
packages/l/libuv/pspec_x86_64.xml
packages/l/libvterm/package.yml
packages/l/libvterm/pspec_x86_64.xml
packages/n/neovim-qt/package.yml
packages/n/neovim-qt/pspec_x86_64.xml
packages/n/neovim/abi_used_symbols
packages/n/neovim/package.yml
packages/n/neovim/pspec_x86_64.xml
packages/py/python-neovim/package.yml
packages/py/python-neovim/pspec_x86_64.xml

**Summary**
- libuv: Update to 1.47.0
- libvterm: Update to 0.3.3
- neovim: Update to 0.9.5
- neovim-qt: Safety rebuild for neovim
- python-neovim: Update to 5.0.0
**Note**
`libuv` is included in ISO images, so land this after Solus 4.5.
**Test Plan**
Install all packages, edit files with neovim, including changing text, saving, and re-opening.
**Checklist**

neovim update

---

packages/c/cracklib/abi_used_symbols
packages/c/cracklib/package.yml
packages/c/cracklib/pspec_x86_64.xml

**Summary**
- Full changelog can be found [here](https://raw.githubusercontent.com/cracklib/cracklib/v2.9.11/src/NEWS)
- Added `homepage` key to `package.yml` (Part of getsolus/packages/issues/411)
**Test Plan**
- Rebuild libpwquality and mariadb against this package
**Checklist**

cracklib: Update to 2.9.11

---

packages/e/epson-inkjet-printer-escpr/package.yml
packages/e/epson-inkjet-printer-escpr/pspec_x86_64.xml

**Summary**
- Support new epson printers
**Test Plan**
- N/A. I don't have a printer. 
**Packager notes:**
Just figured out a way to update this package to latest version. Upstream there are no more direct `.tar.gz` links.
**Checklist**

epson-inkjet-printer-escpr: Update to 1.8.3

---

packages/c/cmocka/abi_symbols
packages/c/cmocka/abi_used_libs
packages/c/cmocka/abi_used_symbols
packages/c/cmocka/package.yml
packages/c/cmocka/pspec_x86_64.xml

**Summary**
- Changelog can be found [here](https://git.cryptomilk.org/projects/cmocka.git/plain/ChangeLog?h=cmocka-1.1.7)
**Test Plan**
**Checklist**

cmocka: Update to 1.1.7

---

packages/c/cinnamon-translations/package.yml
packages/c/cinnamon-translations/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**
**Note**
There is new release version [6.0.1](https://github.com/linuxmint/cinnamon-translations/releases/tag/master.mint21)

cinnamon-translations: homepage inclusion

---

packages/g/gnome-desktop-branding/package.yml
packages/g/gnome-desktop-branding/pspec_x86_64.xml
packages/g/gnome-shell-extensions/package.yml
packages/g/gnome-shell-extensions/pspec_x86_64.xml

**Summary**
- To fix fault appstream-builder generation. Resolves #1. Part of #6.
**Test Plan**
- Build and run `appstream-builder --packages-dir=. --include-failed -v`
- Verify each extension gets their appstream data generated properly
**Checklist**

Subpackage default gnome shell extensions

---

packages/v/visidata/package.yml
packages/v/visidata/pspec_x86_64.xml

**Summary**
- add color_longname to use instead of color_keystrokes
- add displayer attribute to saved column state
- Enter executes first row, if partially typed out
- add sidebar for longname and aggregator palette
- add show-command-info to display command info for a keystroke
- add BtnUp pretty keys for BUTTON#_RELEASED
- dup-selected should unselect all rows in copied sheet
- fix KeyError crash with invalid inputs in expr for Python 3.12
- fix columns sheet sidebar
- ignore parsing exceptions on invalid urls
- limit end separators to rightmost visible column of sheet
- fix fmtstr on DirSheet sidebar for case where source is BaseSheet
- maintain ordering on sheet copies
- do not try to cancel already finished thread
- [changelog](https://raw.githubusercontent.com/saulpw/visidata/v3.0.1 …

visidata: Update to 3.0.1

---

.github/ISSUE_TEMPLATE/bug.yml

XFCE does not have a way to copy the information in About ... dialogs. This small change provides a way for users to get us system information from command line.
**Summary**
**Test Plan**
**Checklist**

Add inxi to bug report form

---

packages/c/cemu/abi_used_symbols
packages/c/cemu/package.yml
packages/c/cemu/pspec_x86_64.xml

**Summary**
- Update Cemu to 2.0-64. [Full changelog here](https://github.com/cemu-project/Cemu/compare/v2.0-59...v2.0-64).
- Fix an issue where Cemu did not appear in the Budgie menu because the executable name did not match the desktop file.
**Test Plan**
Verify that the app shows up in Budgie menu. Open Cemu and launch a game. Test that things generally work as expected.
**Checklist**

cemu: Update to 2.0-64

---

packages/i/imake/package.yml
packages/i/imake/pspec_x86_64.xml
packages/p/pixman/abi_symbols
packages/p/pixman/abi_symbols32
packages/p/pixman/abi_used_symbols
packages/p/pixman/abi_used_symbols32
packages/p/pixman/package.yml
packages/p/pixman/pspec_x86_64.xml
packages/t/tigervnc/package.yml
packages/t/tigervnc/pspec_x86_64.xml
packages/x/xorg-server/package.yml
packages/x/xorg-server/pspec_x86_64.xml
packages/x/xorg-xwayland/abi_used_symbols
packages/x/xorg-xwayland/package.yml
packages/x/xorg-xwayland/pspec_x86_64.xml
packages/x/xrdp/abi_used_symbols
packages/x/xrdp/package.yml
packages/x/xrdp/pspec_x86_64.xml

Updating to the latest security releases for Xorg-server and Xwayland while also flushing out all of the xorg-related projects in my updates list.
**Summary**
- Updates xorg-server to v21.1.11
- Including bundled build in tigervnc (adding a note to xorg-server just to make sure this always gets done in the future)
- Updates xorg-xwayland to v23.2.4
- Pixman 0.43.0
- Imake v1.0.10
- xrdp v0.9.24 (which technically isn't an xorg project but it was in my todo list and is tangentially related so in it goes)
Resolves the following CVEs:
- CVE-2023-6816
- CVE-2024-0229
- CVE-2024-21885
- CVE-2024-21886
- CVE-2024-0408
- CVE-2024-0409

Xorg Updates for January

---

packages/f/fb2converter/package.yml
packages/f/fb2converter/pspec_x86_64.xml

**Summary**
- Fixed notes body processing in float-new-XXXX modes
- Now notes bodies could have images and cross-links
- epub:type attributes now will only be set on "anchor" tags
- Added new notes type: "float-new-more"
**Test Plan**
- fb2c convert in.fb2; then skim through epub
**Checklist**

fb2converter: Update to 1.74.1

---

packages/v/visidata/package.yml
packages/v/visidata/pspec_x86_64.xml

**Summary**
- [cli] add --guides to open the guide index
- [cmdpalette] only first 10 suggestions should have shortcut keys
- [draw] use default bg on col hdr sep
- [input] draw help sidebar on top of sheet/updater
- [graph] sort by x and y columns when diving
- [guides] improve formatting of command and options in sidebar + guides
- [replay] stop stderr batch progress when entering interactive mode
- [shell] clean up DirSheet sidebar
- [sidebar] grab user's keystroke of sidebar-toggle for helpstring
- [sort] a better fix for maintaining sort ordering on sheet copies
- [tests] add "test" extras for installing PyPI packages needed to run tests
**Test Plan**
- open, filter and sort tsv
**Checklist**

visidata: Update to 3.0.2

---

packages/t/tailscale/abi_used_symbols
packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- portmap: check the epoch from NAT-PMP & PCP, establish new portmapping if it changes
- portmap: better handle multiple interfaces
- portmap: handle multiple UPnP discovery responses
- increase the number of 4via6 site IDs from 256 to 65,536
- taildrop: allow category Z unicode characters
- increased binary size with 1.56 is resolved in 1.58
- Reduce home DERP flapping when there's still an active connection
- device web ui: fixed issue when accessing shared devices
- device web ui: fixed login issue when accessed over https
- add shell shebang in postinstall script
**Test Plan**
- systemctl restart tailscaled
- tailscale status; tailscale netcheck
- tailscale web and visit http://localhost:8088
**Checklist**

tailscale: Update to 1.58.0

---

packages/k/kitty/abi_symbols
packages/k/kitty/abi_used_symbols
packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
- Conditional mappings depending on the state of the focused window
- Support for Modal mappings such as in modal editors like vim
- A new option notify_on_cmd_finish to show a desktop notification when a long running command finishes
- A new action send_key to simplify mapping key presses to other keys without needing send_text
- Allow focusing previously active OS windows via nth_os_window
- Wayland: Fix copying to clipboard under wl-roots based compositors in some circumstances
- Font fallback: Fix the font used to render a character sometimes dependent on their order on screen
- panel kitten: Fix rendering with non-zero margin/padding in kitty.conf
- kitty keyboard protocol: Specify the behavior of the modifier bits during modifier key events
- Wayland: support new …

kitty: Update to 0.32.0

---

packages/a/appstream-data/package.yml
packages/a/appstream-data/pspec_x86_64.xml

**Summary**
KDE Discover and Gnome Software expect different paths to appstream data than legacy Solus SC does.
Use the modern paths and set up + verify compat symlinks for Solus SC.
**Test Plan**
Test that the paths added work with both GNOME Software, KDE Discover and Solus SC.
**Checklist**

appstream-data: Add compat symlinks for Solus SC

---

common/Scripts/helpers.fish
common/Scripts/helpers.sh
common/Scripts/helpers.zsh

**Summary**
We have no convenient way to re-index our local repo.
Since it is quite a long command, why not add a convenience function to do it correctly that is maintained by Solus Staff?
This commit does just that for all helper scripts.
**Test Plan**
Test helper function with bash, fish and zsh.
**Checklist**

helpers.*sh: Add reindex-localrepo convenience function

---

packages/w/wxmaxima/MAINTAINERS.md
packages/w/wxmaxima/abi_used_symbols
packages/w/wxmaxima/package.yml
packages/w/wxmaxima/pspec_x86_64.xml

**Summary**
- Input text selection was cleared when right-clicking on it
- Pressing both mouse buttons simultaneously caused an assert
- Corrected the cursor position after unsuccessful autocompletes
- Corrected the handling of question prompts from `maxima`
- Bug corrections in the search functionality
- RegEx search works again
- Clicking on the notification now is more likely to focus the worksheet
- Corrected the cell folding logic
- Folded cells are no more evaluated
- Now we try to generate a backtrace on crashes
- Corrected the position of integral limits
- Nicer product, sum and integral signs
- Hidden cells weren't restored from wxm files
- `diff()` no longer causes spurious multiplication dots
**Test Plan**
- Open example files and make sure everything looks right
**Checklist**

wxmaxima: Update to 23.12.0

---

packages/a/allegro/abi_symbols
packages/a/allegro/abi_used_libs
packages/a/allegro/abi_used_symbols
packages/a/allegro/package.yml
packages/a/allegro/pspec_x86_64.xml
packages/l/liberation-circuit/package.yml
packages/l/liberation-circuit/pspec_x86_64.xml

**Summary**
- 5.2.9.1 :
- Fix a regression where toggling fullscreen window when menus are used stopped working
- 5.2.9.0 :
- Fix fullscreen window creation
- Fix some X11 + fullscreen window interaction
- Allow setting higher quality icons
- Improve `DISPLAY_SWITCH_IN/OUT` events
- Work on improving Window positioning
- Fix creating an initially maximized window
- Enable toggling and setting maximized/frameless modes when menus are used
- Fix popup menu
- Make AltGr (right Alt) toggle the `ALLEGRO_KEYMOD_ALTGR` modifier
- Full changelog can be found [here](https://github.com/liballeg/allegro5/releases/tag/5.2.9.0)
**Test Plan**
Rebuild `liberation-circuit` against this package
**Checklist**

allegro: Update to 5.2.9.1

---

packages/f/font-clear-sans-ttf/package.yml
packages/f/font-clear-sans-ttf/pspec_x86_64.xml

**Summary**
Move appstream metadata out of legacy path

font-clear-sans-ttf: Move appstream metadata out of legacy path

---

packages/g/gedit-plugins/package.yml
packages/g/gedit-plugins/pspec_x86_64.xml

**Summary**
- Split plugins into subpackages
Ref https://github.com/getsolus/packages/issues/1389
Fixes https://github.com/getsolus/packages/issues/4
**Test Plan**
Install the updated gedit-plugins package, see that the split packages were all installed, verify that the plugins appeared in the Plugins page of the gedit settings.
**Checklist**

gedit-plugins: Split plugins into subpackages

---

packages/p/perl-sdl/abi_used_symbols
packages/p/perl-sdl/files/Adapt-to-perl-5.37.1.patch
packages/p/perl-sdl/package.yml
packages/p/perl-sdl/pspec_x86_64.xml

**Summary**
Packager notes:
- sv_nv() is deprecated use SvNVx() instead.
Resolves getsolus/packages#1410
**Test Plan**
Play frozen-bubble
**Checklist**

perl-sdl: Work with newer perl versions

---

packages/k/kdeconnect/abi_used_symbols
packages/k/kdeconnect/package.yml
packages/k/kdeconnect/pspec_x86_64.xml

**Summary**
- Fix starting on systems that don't have `kirigami2` installed
Fixes https://github.com/getsolus/packages/issues/1387
**Test Plan**
Install KDE Connect on Budgie and see that it works.
**Checklist**

kdeconnect: Add rundep on kirigami2

---

packages/f/fceux/files/org.TasEmulators.fceux.metainfo.xml
packages/f/fceux/package.yml
packages/f/fceux/pspec_x86_64.xml

**Summary**
Added appstream metadata (Part of getsolus/packages#1389)
**Test Plan**
**Checklist**

fceux: Add appstream metadata

---

packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
- Fix a regression that caused multi-key sequences to not abort when pressing an unknown key
- Fix a regression that caused kitten @ launch --cwd=current to fail over SSH
- Fix a regression that caused kitten @ send-text with a match tab parameter to send text twice to the active window
- Fix a regression that caused overriding of existing multi-key mappings to fail
- Wayland+NVIDIA: Do not request an sRGB output buffer as a bug in Wayland causes kitty to not start
**Test Plan**
- run cli command; redirect output to pager
**Checklist**

kitty: Update to 0.32.1

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- App connectors have improved scheduling and merging of route changes under some conditions
- Fixed crash when performing UPnP portmapping on older routers with no supported portmapping services
**Test Plan**
**Checklist**

tailscale: Update to 1.58.2

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Fix application of APLF for several Uiua operators.
- Adjust serif shapes for lowercase italic Yeri glyphs with corner body shape
- Make a (cv26) use single-storey-tailed under slab italic by default
- Make b (cv27) use toothed-motion-serifed under slab italic by default
- Make g (cv32) use single-storey-serifless under slab italic by default
- Make q (cv41) use straight-bottom-serifed under slab italic by default
**Test Plan**
**Checklist**

font-iosevka-ttf: Update to 28.0.6

---

common/Scripts/helpers.sh

This can be useful when looking up the correct CPE $PRODUCT:$VENDOR pair for monitoring.yml purpurses and for manually searching for known CVEs.
This commit only adds a PoC bash script helper.
Example output:
```
$ cpesearch zlib
[
[
109789,
"cpe:2.3:a:zlib:pigz"
],
[
111701,
"cpe:2.3:a:gnu:zlib"
],
[
117793,
"cpe:2.3:a:zlib:zlib"
]
]
Verify successful hits by visiting https://cve.circl.lu/search/$VENDOR/$PRODUCT
- CPE entries for software applications have the form 'cpe:2.3:a:$VENDOR:$PRODUCT'
```

helpers*sh: Add a primitive cpesearch function

---

common/Scripts/helpers.fish
common/Scripts/helpers.sh
common/Scripts/helpers.zsh

Now supports showing usage if '-h' and '--help' are supplied as arguments

helpers*sh: Update/add cpesearch for bash/fish/zsh

---

packages/e/eopkg4-bin/package.yml
packages/e/eopkg4-bin/pspec_x86_64.xml

**Summary**
This moves eopkg4-bin out of system.base. It'll belong there once it's ready for primetime.
**Summary**
eopkg4-bin doesn't belong in system.base yet. We don't want it getting installed for everyone until we're ready!
**Test Plan**
Built. Still works. No changes to the package other than component and relnum.
**Checklist**

eopkg4-bin: Move out of system.base

---

packages/g/geonkick/abi_symbols
packages/g/geonkick/files/org.geonkick.geonkick.metainfo.xml
packages/g/geonkick/package.yml
packages/g/geonkick/pspec_x86_64.xml

**Summary**
- Changelog:
- 3.3.2 : 
- Fix high CPU usage by DSP 
- Fix limiter for the audition channel, use a separate audition channel for samples preview 
- Fix instrument leveler value 
- 3.3.1 : 
- Fix out of bound index in KitModel 
- Fix warning related to clang 
- Fix not running Geonkick standalone if can't lock memory 
**Test Plan**
Run application and make noise
**Checklist**

geonkick: Update to 3.3.2

---

packages/s/snapd/abi_used_symbols
packages/s/snapd/package.yml
packages/s/snapd/pspec_x86_64.xml

**Summary**
Update snapd to 2.61.1
- Stop requiring default provider snaps on image building and first  boot if alternative providers are included and available
- Fix auth.json access for login as non-root group ID
- Fix incorrect remodelling conflict when changing track to older snapd version
- Improved check-rerefresh message
- Fix UC16/18 kernel/gadget update failure due volume mismatch with installed disk
- Stop auto-import of assertions during install modes
- Desktop interface exposes GetIdletime
- Polkit interface support for new polkit versions
- Fix not applying snapd snap changes in tracked channel when remodelling
**Test Plan**
I've tested this on a virtual machine running unstable.
I've installed and played with the snaps "ohmygiraffe" and "okular".
**Checklist**

Update snapd to 2.61.1

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Make superscript/subscript/overscript Cyrillic characters obey localization forms of base letters
- Add IPA localization forms for Greek Lower Beta (β) and Chi (χ)
- Add APLF variants for U+25F0, U+25F3, and U+25F4.
- Make Ezh follow variants of Z/z
- Fix serif form for Cyrillic Lower Tall / Iotified Yat
- Make top serifs of Cyrillic Lower Straight U (ү, ұ) and Latin Lower Gamma (ɣ) respond to italics.
- Fix leaning marks of Capital Turned/Half H (U+2C75, U+2C76, U+A78D, U+A7F5, U+A7F6).
- Fix leaning marks of Wynn (U+01BF, U+01F7)
- Fix leaning marks of Insular R (U+A782, U+A783)
- Fix leaning marks of Greek/Latin Beta (U+03B2, U+A7B4, U+A7B5)
- Fix leaning marks of Greek Lower San (U+03FB)
**Test Plan**
**Checklist**

font-iosevka-ttf: Update to 28.0.7

---

packages/g/gajim/package.yml
packages/g/gajim/pspec_x86_64.xml

**Summary**
- With fresh install gajim won't start
- Install libgtksourceview4 as a manual workaround
**Test Plan**
- gajim starts on fresh and updated system
**Checklist**

gajim: Add missing rundep

---

packages/u/unknown-horizons/package.yml
packages/u/unknown-horizons/pspec_x86_64.xml

**Summary**
- Update to latest commit
- Install appstream metainfo (Part of getsolus/packages#1389)
- Install scalable icon
- Resolves getsolus/packages#1442
**Test Plan**
- Play tutorial
- Verify metadata with `appstream-builder --packages-dir=. --include-failed -v`
**Checklist**

unknown-horizons: Housekeeping

---

packages/b/bandwhich/abi_used_symbols
packages/b/bandwhich/package.yml
packages/b/bandwhich/pspec_x86_64.xml

**Summary**
- Generate completion & manpage
- Log unresolved processes in more detail + general refactor
- Display bandwidth in different unit families
- Show interface names
- Table formatting logic overhaul
- Make logging race-free using a global lock & macro
- Use once_cell::sync::Lazy to make regex usage more ergonomic
- Fix vague CLI option documentation
**Test Plan**
- watch IP connections on network interface
**Checklist**

bandwhich: Update to 0.22.2

---

packages/s/scrcpy/abi_used_symbols
packages/s/scrcpy/package.yml
packages/s/scrcpy/pspec_x86_64.xml

**Summary**
- Camera capture option
- Android 14 support
- Orientation option
- [2.2](https://github.com/Genymobile/scrcpy/releases/tag/v2.2)
- [2.3](https://github.com/Genymobile/scrcpy/releases/tag/v2.3)
- [2.3.1](https://github.com/Genymobile/scrcpy/releases/tag/v2.3.1)
**Test Plan**
Mirrored my phone screen to my PC; used it with mouse and keyboard
**Checklist**

scrcpy: update to 2.3.1

---

packages/t/transmission/abi_used_symbols
packages/t/transmission/package.yml
packages/t/transmission/pspec_x86_64.xml

**Summary**
- Fixed `4.0.0` bug where the IP address field in UDP announces were not encoded in network byte order
- Fixed a bug that incorrectly escaped JSON strings in some locales.
- Fixed `4.0.4` decreased download speeds for people who set a low upload bandwidth limit.
Full release notes available [here](https://github.com/transmission/transmission/releases/tag/4.0.5)
**Test Plan**
- Added, downloaded, and seeded a torrent
**Checklist**

transmission: Update to 4.0.5

---

packages/py/python-toolz/package.yml
packages/py/python-toolz/pspec_x86_64.xml

**Summary**
Changes:
- Add support for Python 3.12 and PyPy 3.10
- Drop support for Python 3.5 and 3.6
- Fix typos
- Use codecov for coverage instead of coveralls
**Test Plan**
Tested a couple of examples from the documentation
**Checklist**

python-toolz: Update to 0.12.1

---

packages/m/mupen64plus/abi_symbols
packages/m/mupen64plus/abi_used_symbols
packages/m/mupen64plus/package.yml
packages/m/mupen64plus/pspec_x86_64.xml

**Summary**
This updates the mupen64plus core app plus all plugins with relevant changes to the latest git source
Commit logs:
- [Core](https://github.com/mupen64plus/mupen64plus-core/compare/f82b37bf63066190e2b41d74deb17846af017a90...860fac3fbae94194a392c1d9857e185eda6d083e)
- [Input-SDL](https://github.com/mupen64plus/mupen64plus-input-sdl/compare/2129e942fdc2ee74d4d5f9c815dd204c45d9f4c1...fd7ffe63606b6cc4de7dab4e684c5aee68210681)
- [RSP-HLE](https://github.com/mupen64plus/mupen64plus-rsp-hle/compare/aa0ea78030d3c2b80184a35bbb36909fd7a28e70...f01be76948d9105bc56635f8e83a89d167328819)
- [UI-console](https://github.com/mupen64plus/mupen64plus-ui-console/compare/42546ab00b23a8052b9c974882628912609990c2...335e826aead146bd6a47d557d78b746e77f337c8)
**Test Plan**
Changed some emulator settings …

mupen64plus: Update core and plugins to latest git sources

---

packages/m/m64py/package.yml
packages/m/m64py/pspec_x86_64.xml

**Summary**
Changes:
- Fix import error when using setuptools 69 or newer
- Search for `lrelease` in the system's Qt binary directory
- Resize game to keep aspect ratio, rather than resizing window itself
- Size game properly even if user doesn't manually resize window
**Test Plan**
Navigated the menus, changed plugins, and played Banjo-Kazooie
**Checklist**

m64py: Update to latest git source

---

packages/w/wxmaxima/abi_used_symbols
packages/w/wxmaxima/package.yml
packages/w/wxmaxima/pspec_x86_64.xml

**Summary**
- Faster start-up
- Better performance directly after startup
- Faster loading of files
- Better button placement in sidebars
- Clear wxMaxima's input buffer on starting a new maxima process
- A nicer ChangeLog dialogue
- Corrected for swapped row and columns in wizard enter matrix
- Fixed a few bugs in the XML saving code
- Zooming did cause recalculation only for the 1st cell
- Many config changes now have immediately effect on the worksheet
- Added the unicode-enhanced ASCII art from maxima to the menus
- Steamlined the cell size calculation stuff
- Completely overhauled the printing functionality
- Moved more of the help file indexing to the background
- Better event handling in the unicode sidebars
- Reading out the values of maxima variables for the GUI was broken
- Many …

wxmaxima: Update to 24.02.0

---

packages/m/m64py/files/net.sourceforge.m64py.metainfo.xml
packages/m/m64py/package.yml
packages/m/m64py/pspec_x86_64.xml

**Summary**
Added appstream metadata (Part of getsolus/packages#1389)
**Test Plan**
**Checklist**

m64py: Add appstream metadata

---

packages/m/mupen64plus-qt/files/io.github.dh4.mupen64plus_qt.metainfo.xml
packages/m/mupen64plus-qt/package.yml
packages/m/mupen64plus-qt/pspec_x86_64.xml

**Summary**
Add appstream metadata (Part of getsolus/packages#1389)
**Test Plan**
**Checklist**

mupen64plus-qt: Add appstream metadata

---

packages/p/protonmail-bridge/package.yml
packages/p/protonmail-bridge/pspec_x86_64.xml

**Summary**
**Changelog**:
- Resolved an issue that prevented Windows and Linux users to auto update to newer versions of Bridge, and in some cases reverted to a previous version of Bridge. NOTE: All Bridge versions that are between v3.2.0 and v3.8.1 (inclusive) need to be update to the latest Bridge version manually.
Link to release notes: https://proton.me/download/bridge/stable_releases.html
**Test Plan**
Synced mail through thunderbird.
**Checklist**

protonmail-bridge: update to 3.8.2

---

packages/t/torbrowser-launcher/package.yml
packages/t/torbrowser-launcher/pspec_x86_64.xml

**Summary**
This updates torbrowser-launcher to version 0.3.7 and adds the missing `python-packaging` dependency (thanks to @clivej for the hint in https://github.com/getsolus/packages/pull/1148)
Changes:
- Use Tor Browser 13.0 new filenames
- Adapt AppArmor profile for Tor Browser 13.0
- Set the `TORBROWSER_LAUNCHER` environment variable to make it easier for Tor Browser to see that it is being run by `torbrowser-launcher`
- Use a proper rDNS ID in AppStream metainfo
- Update to latest version of the Tor Browser OpenPGP signing key
- Remove some unused code to fix a warning
Note: this also changes to the new upstream repository on gitlab, managed by the Tor Project
**Test Plan**
Let `torbrowser-launcher` download and launch Tor Browser
**Checklist**

torbrowser-launcher: Update to 0.3.7 and add dependency

---

packages/p/ppsspp/abi_used_symbols
packages/p/ppsspp/files/org.ppsspp.PPSSPP.metainfo.xml
packages/p/ppsspp/package.yml
packages/p/ppsspp/pspec_x86_64.xml

**Summary**
- Changelog: 
- Fixed green rendering errors on some PowerVR GPUs 
- Release all held keys on pause to avoid "stuck keys" after unpausing or in run-behind-pause 
- UI fixes - Update `libchdr` with `zstd` support, warn the user about bad CHDs 
- Add workaround for AdHoc mode in Resistance 
- Fix graphics in Tokimeki Memorial 4 
- Fix crash in UFC 2010 on Mali GPUs 
- Temporarily disable MSAA on Adreno GPUs due to crashing 
- Fixed some crashes and optimized the game metadata cache 
- Additional crashfixes and similar 
- Fixed playback of frame dumps with Vulkan 
- Volume slider added for RetroAchievements sounds
- Added appstream metadata (Part of getsolus/packages#1389)
**Test Plan**
- Play "Crash Tag Team Racing"
- Verify metadata with `appstream-builder --packages-dir=. …

ppsspp: Update to 1.17.1

---

packages/c/citra/abi_used_symbols
packages/c/citra/package.yml
packages/c/citra/pspec_x86_64.xml

**Summary**
Update citra to release 2090
Major changes: 
- Add several new hotkeys for configuring emulation settings
- Many small tweaks to improve emulator accuracy
Full changelog [here](https://github.com/citra-emu/citra-nightly/compare/nightly-2044...nightly-2090)
**Test Plan**
Launch citra and configure a controller. Launch a game. Make sure things work as expected.
**Checklist**

citra: Update to 2090

---

packages/p/papirus-icon-theme/package.yml

**Summary**
Release notes available [here](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/releases/tag/20240201)
Note: Also removes some outdated Third Party Repo icons from `solus-sc-icons`
**Test Plan**
Looked at icons in my menu and `solus-sc` and confirmed everything was alright
**Checklist**

papirus-icon-theme: Update to 20240201

---

packages/py/python-waitress/package.yml
packages/py/python-waitress/pspec_x86_64.xml

**Summary**
Changes:
- Fixed testing of vendored asyncore code to not rely on particular naming for errno's
- HTTP Request methods and versions are now validated to meet the HTTP standards thereby dropping invalid requests on the floor
- No longer close the connection when sending a HEAD request response
- Always attempt to send the `Connection: close` response header when we are going to close the connection to let the remote know in more instances
- Python 3.7 is no longer supported. Add support for Python 3.11, 3.12 and PyPy 3.9, 3.10
- `clear_untrusted_proxy_headers` is set to `True` by default
**Test Plan**
- Ran through some examples from the documentation
- Confirmed `anki` still works correctly
**Checklist**

python-waitress: Update to 3.0.0

---

packages/py/python-maturin/package.yml
packages/py/python-maturin/pspec_x86_64.xml

**Summary**
Changes:
- Un-deprecate `MATURIN_PEP517_ARGS` env var
- Add support for uniffi library mode
- Fix missing member in Cargo.toml for sdist of nested workspace layout
- Metadata: escape display name in email addresses
- Fix glob workspace members matching in sdist
- Add support for cross compiling with `cross`
- Updated dependencies
**Test Plan**
Built `python-orjson`
**Checklist**

python-maturin: Update to 1.4.0

---

packages/py/python-orjson/abi_used_symbols
packages/py/python-orjson/package.yml
packages/py/python-orjson/pspec_x86_64.xml

**Summary**
Changes:
- Fixed debug assert failure on 3.12 `--profile=dev` build
- Improved performance of serializing
- Fixed: Serialization `str` escape uses only 128-bit SIMD
- Fixed compatibility with CPython 3.13 alpha 3
- Serialization uses small integer optimization in CPython 3.12 or later
**Test Plan**
Ran through the examples in the README
**Checklist**

python-orjson: Update to 3.9.13

---

packages/s/steam/package.yml
packages/s/steam/pspec_x86_64.xml

**Summary**
Changes:
- `bin_steam.sh`: When running in a Gamescope session, only write messages to the log. Don't pop up a zenity or xterm window, which would not be shown by the Gamescope session
- `bin_steam.sh`: If `~/.steam/steam` is a dangling symlink, don't prompt users to browse for the correct location or reinstall. Instead, just reinstall non-interactively.
- Updated client timestamp 1705108172 (2023-01-13)
- Updated Steam Runtime (scout) version 0.20231127.68515
**Test Plan**
Launched Steam, played a game and sent a message to a friend
**Checklist**

steam: Update to 1.0.0.79

---

packages/l/libheif/abi_used_symbols
packages/l/libheif/monitoring.yml
packages/l/libheif/package.yml
packages/l/libheif/pspec_x86_64.xml

**Summary**
Changes:
- Fixed loading of HEIF files with extra zero bytes at the end
- Default nclx values now match sRGB
- Support JPEG2000 images with alpha channel
- Corrected transform box generation for `heif_orientation_flip_vertically` and `heif_orientation_rotate_90_cw_then_flip_vertically`
- Fixed: ispe boxes in AVIF images with clap boxes were written with the wrong size
- Always output MIAF brand for AVIF images
- Fix kvazaar encoding with odd image sizes and encodings with non-4:2:0 chroma
**Security**
- CVE-2023-49462
- CVE-2023-49463
**Test Plan**
Encoded and viewed a couple of heif images
**Checklist**

libheif: Update to 1.17.6 and add monitoring.yml

---

packages/f/fritzing-parts/package.yml
packages/f/fritzing-parts/pspec_x86_64.xml

**Summary**
Depends on #1529
Align parts with latest app release.
Changelog:
- [Commit log v1.0.2](https://github.com/fritzing/fritzing-parts/commits/1.0.2)
**Test Plan**
- Installed and tested with Fritzing v1.0.2
**Checklist**

fritzing-parts: Update to 1.0.2

---

packages/p/protontricks/monitoring.yml
packages/p/protontricks/package.yml
packages/p/protontricks/pspec_x86_64.xml

**Summary**
Changes:
- Fix crash caused by the Steam shortcut configuration file containing extra data after the VDF section
- Fix differently sized custom app icons breaking the layout in the app selector
- Fix crash caused by custom app icons with non-RGB mode
- Show app icons for custom shortcuts in the app selector
- Verbose flag can be enabled with `-vv` for additional debug logging
- Fix Protontricks not recognizing supported Steam Runtime installation due to changed name
- Fix Protontricks not recognizing default Proton installation for games with different Proton preselected by Valve testing
- Fix Protontricks crash when app has an unidentifiable app icon
**Test Plan**
Used `protontricks` to install a missing runtime into a game prefix
**Checklist**

protontricks: Update to 1.11.0

---

packages/w/wine/abi_symbols
packages/w/wine/abi_symbols32
packages/w/wine/abi_used_symbols
packages/w/wine/abi_used_symbols32
packages/w/wine/monitoring.yml
packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
- Mono engine updated to version 9.0.0
- A number of system tray fixes
- Exception handling improvements on ARM platforms
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.2)
**Test Plan**
- Ran wineconsole, winecfg, winefile, winemine
- Played Age of Empires I
**Checklist**

wine: Update to 9.2

---

packages/e/efl/abi_libs
packages/e/efl/abi_symbols
packages/e/efl/abi_used_symbols
packages/e/efl/monitoring.yml
packages/e/efl/package.yml
packages/e/efl/pspec_x86_64.xml
packages/r/rage/monitoring.yml
packages/r/rage/package.yml
packages/r/rage/pspec_x86_64.xml
packages/t/terminology/abi_used_symbols
packages/t/terminology/monitoring.yml
packages/t/terminology/package.yml
packages/t/terminology/pspec_x86_64.xml

**Summary**
Update efl to 1.27.0, rebuild reverse dependencies for safety and add `monitoring.yml`s to all packages
Changes:
- Lots of minor bug fixes
- New eina APIS (releative path and sha1)
- Add URI List to elm cnp
- Add JXL Evas loader/saver
- Add Eet fs sync call to force writes to disk
- Add support for LibreSSL 3.5.x
- Removed GNUTLS support now openssl3 is out
- Elementary icons - policy change to use theme icons for std icons
- Elementary entry - allow past into password entries
- Add QOI Evas image loader/saver
**Test Plan**
Built and used `terminology` and `rage`
**Checklist**

Update efl to 1.27.0

---

packages/l/libgsf/abi_symbols
packages/l/libgsf/monitoring.yml
packages/l/libgsf/package.yml
packages/l/libgsf/pspec_x86_64.xml

**Summary**
Changes:
- Export gsf_value_get_docprop_array
- xml: Fix build with libxml2 2.12
Packaging note: Upstream project has clarified their license to be LGPL-2.1-only, see discussion [here](https://gitlab.gnome.org/GNOME/libgsf/-/issues/28)
**Test Plan**
- Used `gnumeric`, `abiword`
- Did a test rebuild of `libgoffice`
**Checklist**

libgsf: Update to 1.4.52 and fix license

---

packages/w/wxmaxima/abi_used_symbols
packages/w/wxmaxima/package.yml
packages/w/wxmaxima/pspec_x86_64.xml

**Summary**
- wxMaxima now correctly installs its icons
- A race condition on closing Maxima
- Update the autocompletion only in idle state
- Fixed a race condition on dropping the log target
- Alt+Up at startup no more crashes
- Resolved a compilation error on old wxWidgets versions
- Resolved GCC errors about too long functions
- Resolved an assert if no history file exists
**Test Plan**
Open test file and do calculations
**Checklist**

wxmaxima: Update to 24.02.1

---

packages/d/dotnet/package.yml
packages/d/dotnet/pspec_x86_64.xml

**Summary**
De-bootstrapping .net
**Test Plan**
1. With the sdk installed, create the following default templates
- native AOT web api
- web api
- hello world console app
2. Run the web api with `dotnet run` and make a get request
3. run the hello world console app with `dotnet run`
5. build each test as a DLL, also publish each app as self-contained single file apps
4. uninstall the .net SDK, and run the apps again with only the runtime installed
5. uninstall the runtime and run the native apps
**Checklist**

dotnet: debootstrap

---

packages/f/fb2converter/package.yml
packages/f/fb2converter/pspec_x86_64.xml

**Summary**
- Switch from cmake to taskfile
- Updated dependencies
**Test Plan**
- fb2c convert file
**Checklist**

fb2converter: Update to 1.74.4

---

packages/l/libgtk-3/monitoring.yml
packages/l/libgtk-3/package.yml
packages/l/libgtk-3/pspec_x86_64.xml

**Summary**
Changes:
- GtkEmojiChooser: Update to CLDR v44
- GtkGestures: Preserve accuracy when translating events
- X11: Support 'virtual' XRANDR monitors
- Build fixes
- Wayland: Fix interpretation of gtk-shell protocol
**Test Plan**
- Launched and used a couple of gtk3 apps
- Built a few gtk3 apps to test `-devel`
- Used the emoji picker
**Checklist**

libgtk-3: Update to 3.24.41

---

packages/l/libgtk-4/monitoring.yml
packages/l/libgtk-4/package.yml
packages/l/libgtk-4/pspec_x86_64.xml

**Summary**
Changes:
- GtkColumnView: Fix a crash on dispose
- GtkEmojiChooser: Update to CLDR v44
- GtkEmojiChooser: Add more translations
- GtkFileDialog: Return an error if no file is selected
- GtkFileDialog: Make closing the portal file chooser work
- GtkDropDown: Fix display of the initial checkmark
- GtkShortcutsWindow: Reduce the minimum width
- GDK: Make the png loader safer against overflow
- Wayland: Fix cursor handling with graphics tablets
**Test Plan**
- Opened and used a bunch of gtk4 apps
- Built a couple of gtk4 apps to test -devel
- Used emoji picker in gtk4 app
**Checklist**

libgtk-4: Update to 4.12.5

---

packages/h/hplip/abi_used_symbols
packages/h/hplip/files/hplip-fix-Wreturn-type-warning.patch
packages/h/hplip/files/hplip.metainfo.xml
packages/h/hplip/package.yml
packages/h/hplip/pspec_x86_64.xml

After installing or updating this package, run `hp-plugin` on command line before attempting to add a printer, print or scan.
**Summary**
Added support for new devices.
Solus:
- Updated release notes URL, added homepage.
- Updated patch after upstream code update.
- Added metainfo file.
**Test Plan**
Verified
- plugin was installed successfully by `hp-plugin`
- previously installed HP Printer is still configurable in Print Settings
- hp-toolbox launches HP Device Manager successfully
- ability to remove and re-add printer / fax in hp-toolbox (Note: must first run hp-plugin)
- can start Simple Scan
- scanning works
- printing works
**Known Issue**
The HP Device Manager UI may display an error on the status tab of the printer 'Device is busy, powered down or unplugged (5002)'
Workaround: …

hplip: update to 3.23.12

---

packages/s/svtplay-dl/MAINTAINERS.md
packages/s/svtplay-dl/package.yml
packages/s/svtplay-dl/pspec_x86_64.xml

**Summary**
Release notes can be found [here](https://github.com/spaam/svtplay-dl/releases/tag/4.69).
**Test Plan**
Installed new package and downloaded a movie.
**Checklist**

svtplay-dl: Update to 4.69

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/request-new-package.yml
.github/ISSUE_TEMPLATE/request-package-update.yml

**Summary**
Add text asking the user to search existing issues before filing a new one, for each template. Also add a link to the appropriate search.
**Test Plan**
Visually verified that the text looks good, and that links open the appropriate search.
**Checklist**

Add section to issue templates for searching existing issues

---

packages/e/eopkg4-bin/package.yml
packages/e/eopkg4-bin/pspec_x86_64.xml

**Summary**
Update eopkg4-bin to the latest git version.
Also rebuild to fix errors introduced by glibc update.
**Test Plan**
- Install eopkg4-bin as built from this PR
- Make sure `eopkg` operations still work
- Make sure PackageKit still works (test an operation or two in Discover, Gnome Software, or with `pkcon` on the command line
**Checklist**

eopkg4-bin: Sync with git

---

packages/j/jags/abi_used_symbols
packages/j/jags/package.yml
packages/j/jags/pspec_x86_64.xml

**Summary**
Release notes can be found [here](https://martynplummer.wordpress.com/2023/03/04/jags-4-3-2-is-released/).
**Test Plan**
Installed and started application, checked man pages.
**Checklist**

jags: Update to 4.3.2

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- authentication: present users with a valid login page when attempting to login even after leaving device unattended for several days
- networking: mute noisy peer mtu discovery errors
- networking: expose gVisor metrics in debug mode
- port mapper: support legacy "urn:dslforum-org" port mapping services
- port mapper: fix crash when no support mapping services found
- ssh: log warning when unable to find SSH host keys
- serve: improve error message when running as non-root
- cloud servers: Detect when Tailscale is running on Digital Ocean and automatically use Digital Ocean's DNS resolvers
- app connectors: enable app connectors to install routes for domains that resolve to CNAME records
- app connectors: support pre-configured routes from control server
- web client: add …

tailscale: Update to 1.60.0

---

packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
- kitten @ load-config: Allow (re)loading kitty.conf via remote control
- Remote control: Allow running mappable actions via remote control (kitten @ action)
- kitten @ send-text: Add a new option to automatically wrap the sent text in bracketed paste escape codes if the program in the destination window has turned on bracketed paste.
- Fix a single key mapping not overriding a previously defined multi-key mapping
- Graphics protocol: Improve display of images using Unicode placeholders or row/column boxes by resizing them using linear instead of nearest neighbor interpolation on the GPU
- When matching URLs use the definition of legal characters in URLs from the WHATWG spec rather than older standards
- hints kitten: Respect the kitty url_excluded_characters option
- Special …

kitty: Update to 0.32.2

---

packages/g/gpxsee/abi_used_symbols
packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- Improved vector maps rendering.
- Minor fixes.
- [changelog](https://build.opensuse.org/package/view_file/home:tumic:GPXSee/gpxsee/gpxsee.changes)
**Test Plan**
- view map
**Checklist**

gpxsee: Update to 13.16

---

packages/f/fb2converter/package.yml
packages/f/fb2converter/pspec_x86_64.xml

**Summary**
- Added "#series_first_word" to "title_format" and "file_name_format" configuration options.
- There is also "series_first_word_length" (default is set to 4) to set cut off length.
**Test Plan**
- fb2c convert infile
**Checklist**

fb2converter: Update to 1.75.0

---

packages/s/snapd/package.yml
packages/s/snapd/pspec_x86_64.xml

**Summary**
New upstream release.
- Fix to enable plug/slot sanitization for prepare-image
- Fix panic when device-service.access=offline
- Support offline remodeling
- Allow offline update only remodels without serial
- Fail early when remodeling to old model revision
- Fix to enable plug/slot sanitization for validate-seed
- Allow removal of core snap on classic systems
- Fix network-control interface denial for file lock on /run/netns
- Add well-known core24 snap-id
- Fix remodel snap installation order
- Prevent remodeling from UC18+ to UC16
- Fix cups auto-connect on classic with cups snap installed
- u2f-devices interface support for GoTrust Idem Key with USB-C
- Fix to restore services after unlink failure
- Add libcudnn.so to Nvidia libraries
- Fix skipping base snap download due …

snapd: Update to 2.61.2

---

packages/h/hugo/package.yml
packages/h/hugo/pspec_x86_64.xml

**Changelog**
- This release is a rewrite of the Hugo core, fixing lots of long-lived bugs and adding some other exciting improvements.
- There are some breaking changes that have been announced for a long time. Most sites will not be affected by this, but we recommend that you test your site with the new Hugo version before you set it up to build to production.
Full changelog [here](https://github.com/gohugoio/hugo/releases/tag/v0.123.0)
**Test Plan**
- Build a local site
**Checklist**

hugo: Update to 0.123.0

---

packages/r/ripgrep/abi_used_symbols
packages/r/ripgrep/package.yml
packages/r/ripgrep/pspec_x86_64.xml

Bugfix release, changelog [here](https://github.com/BurntSushi/ripgrep/releases/tag/14.1.0)
**Test Plan**
Tested against text files in the repo
**Checklist**

ripgrep: Update to 14.1.0

---

packages/h/hplip/files/0001-Fix-desktop-files.patch
packages/h/hplip/files/fix-hp-uiscan-icon-path.patch
packages/h/hplip/files/series
packages/h/hplip/package.yml
packages/h/hplip/pspec_x86_64.xml

**Summary**
- Install appstream metadata (Part of getsolus/packages#1389)
- Consolidate all patches to fix desktop files into one
- Make symlink of icons to hicolor
**Test Plan**
- Verify metadata with `appstream-builder --packages-dir=. --include-failed -v`
- Launch "HP Device Manager" and "hp-uiscan" from desktop
**Checklist**

hplip: Housekeeping

---

packages/o/opentyrian/MAINTAINERS.md
packages/o/opentyrian/abi_libs
packages/o/opentyrian/abi_symbols
packages/o/opentyrian/files/opentyrian.appdata.xml
packages/o/opentyrian/package.yml
packages/o/opentyrian/pspec_x86_64.xml

**Summary**
Add appstream metadata (Part of https://github.com/getsolus/packages/issues/1389)
**Test Plan**
**Checklist**

opentyrian: Add appstream metainfo

---

packages/e/espeak-ng/package.yml
packages/e/espeak-ng/pspec_x86_64.xml

**Summary**
- Added Apache 2.0 license to package.yml
**Test plan**
- Installed and played some text
**Checklist**

espeak-ng: inclusion of homepage

---

common/Scripts/worklog.py

**Summary**
Without specifying the -s/--sort option, worklog.py will output the latest build or commit last.
This enables the ability to trivially keep an eye on large PR (re)builds with something like:
while true; do
date
./worklog.py --format md builds 2024-02-24 now |tail -n5
echo "----"
sleep 30
done
**Test Plan**
Test the output of worklog.py with and without -s/--sort options.
**Checklist**

worklog.py: Add a -s/--sort option that sorts output

---

packages/f/firewalld/monitoring.yml
packages/f/firewalld/package.yml
packages/f/firewalld/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/firewalld/firewalld/releases/tag/v2.1.1).
**Test Plan**
Restart the computer and verify that the applet appears in the tray and that the firewall appears to be active.
**Checklist**

firewalld: Update to 2.1.1

---

common/Scripts/helpers.sh

**Summary**
- When no args are passed to cpesearch() it'll use the current directory name. Useful in combination with gotopkg().
**Test Plan**
`gotopkg systemd; cpesearch`
`goroot; cpesearch systemd`
**Checklist**

common/Scripts: Allow no args usage of cpesearch()

---

packages/d/discover/abi_used_symbols
packages/d/discover/files/0001-PackageKitBackend-Add-the-Drivers-menu-filtered-by-t.patch
packages/d/discover/package.yml
packages/d/discover/pspec_x86_64.xml

**Summary**
Add livingsilver94's patch to Discover enabling GUI driver installation. There is a category showing all hardware drivers, and also one showing only drivers applicable to the device.
**Test Plan**
1. Build Discover from this PR, then install it.
2. Follow the test plan [here](https://github.com/getsolus/discover/issues/1), starting from step 3.
**Checklist**

discover: Use livingsilver94's patch to enable driver installation

---

packages/s/syncthing/package.yml
packages/s/syncthing/pspec_x86_64.xml

**Summary**
Bugfixes:
- Panic in ignore matching on invalid UTF-8 from filesystem watcher
- syncthing should be cgroup aware
Enhancements:
- File system watcher should skip ignored directories in more cases
- Set `GOMAXPROCS` quota aware in Linux containers
Other issues:
- typo in folder_sendrecv.go refrences nonexistent type `dbUpdateShourtcutFile`
- typo: `Complection` → `Completion` ?
**Test Plan**
- Restart Syncthing-GTK and verify it can connect to the syncthing backend, all folders sync
**Checklist**

syncthing: update to 1.27.4

---

packages/s/sof-firmware/MAINTAINERS.md
packages/s/sof-firmware/package.yml
packages/s/sof-firmware/pspec_x86_64.xml

**Summary**
For v2.8 series, the following new topology files have been added since v2.8:
v2.8.x/sof-ace-tplg-v2.8
├── sof-ace-tplg
│   ├── sof-hda-generic-ace1-2ch.tplg
│   ├── sof-hda-generic-ace1-4ch.tplg
│   ├── sof-hda-generic-cavs25-2ch.tplg
│   ├── sof-hda-generic-cavs25-4ch.tplg
│   ├── sof-mtl-es83x6-ssp1-hdmi-ssp02.tplg
│   ├── sof-mtl-hdmi-ssp02.tplg
Full release notes [here](https://github.com/thesofproject/sof-bin/releases)
**Test Plan**
Verified firmware files were installed to correct paths. Restarted pipewire.
**Checklist**

sof-firmware: update to 2.8.1

---

packages/e/eopkg4-bin/package.yml
packages/e/eopkg4-bin/pspec_x86_64.xml

**Summary**
Set GLIBC_TUNABLES to prevent Nuitka from picking up glibc-hwcaps libraries which won't work on older systems. Credit to Reilly Brogan for finding the fix.
**Test Plan**
1. Build from this PR
2. Install package on a Core 2 Duo (just about the oldest platform we support)
3. Check that eopkg4-bin works
4. Check that the packagekit backend works
**Checklist**

eopkg4-bin: Fix compatibility with older x86_64 systems

---

packages/g/gnome-clocks/package.yml
packages/g/gnome-clocks/pspec_x86_64.xml

It was 18 on https://phab.getsol.us/source/gnome-clocks/browse/master/package.yml
Undperecation PR : https://github.com/getsolus/solus-sc/pull/307

gnome-clocks: Bump release number to match old repo

---

packages/d/deadbeef/files/io.sourceforge.deadbeef.deadbeef.metainfo.xml
packages/d/deadbeef/package.yml
packages/d/deadbeef/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

deadbeef: Add appstream metainfo 

---

packages/a/audacious/package.yml
packages/a/audacious/pspec_x86_64.xml

**Summary**
Install appstream metainfo (Part of getsolus/packages#1389)
**Test Plan**
**Checklist**

audacious: Install appstream metainfo

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
- Resolve go compiler regression
- Fixed the msg returned for patching a repo variable
- Fix regression around commas in commit titles during `pr create`
- Add `ref` option to `gh cache list`
- Make comments in the default config file more informative
- Link Project to Repository or Team Command
- Clarify helptext for search PRs regarding archived repos
- Support `project view --web` with TTY
**Test Plan**
Ran `gh status`, and in a repository ran `gh pr list` and `gh pr view #number`. Also created this PR.
**Checklist**

github-cli: Update to 2.45.0

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- Exposing port 8080 to other devices on your tailnet works as expected
**Test Plan**
**Checklist**

tailscale: Update to 1.60.1

---

packages/f/fb2converter/package.yml
packages/f/fb2converter/pspec_x86_64.xml

**Summary**
- Added "#series_first_word" to "title_format" and "file_name_format" configuration options.
- There is also "series_first_word_length" (default is set to 4) to set cut off length
**Test Plan**
- fb2c convert infile
**Checklist**

fb2converter: Update to 1.75.1

---

packages/y/yubico-authenticator/abi_used_symbols
packages/y/yubico-authenticator/package.yml
packages/y/yubico-authenticator/pspec_x86_64.xml

**Changelog:**
- UI: Major UI overhaul, with improvements including:
- Add new UI layouts for wider windows to better utilize screen space.
- Add YubiKey personalization through custom naming and theme color.
- Split FIDO/WebAuthn into multiple sections.
- Move factory reset functionality into a single dialog, from the individual sections.
- Add support for Yubico OTP provisioning.
- PIV: Display more information about keys and certificates.
- PIV: Add output format for public key when generating keys.
- Desktop: Window hidden/shown state no longer saved when closing the app, use --hidden to start the app in a hidden to systray state.
- Desktop: Fix FIDO reset over NFC.
- Windows: Add option to launch Windows Settings for FIDO management.
- Android: Increase read timeout for NFC, …

yubico-authenticator: update to 6.4.0

---

common/Scripts/worklog.py

**Summary**
Change the output of the `update` subcommand with:
- A Markdown format that can be used for publishing.
- Multiple authors (one for each commit).
- The GitHub author that made the change.
**Test Plan**
```console
./common/Scripts/worklog.py -s updates "1 week ago" "now" --format=md |\
pandoc --from=commonmark --to=html > /tmp/worklog.html
```
**Checklist**

worklog: Improve output of `update` subcommand

---

packages/g/gajim/package.yml
packages/g/gajim/pspec_x86_64.xml

**Summary**
Add missing runtime dependency to `gajim`.
**Test Plan**
Install the package and see that it launches successfully.
**Checklist**

gajim: Add missing runtime dependency on python-pillow

---

packages/p/pencil/files/vn.evolus.pencil.pencil.metainfo.xml
packages/p/pencil/package.yml
packages/p/pencil/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

pencil: Add appstream metainfo

---

packages/c/cantata/files/io.github.cdrummond.cantata.metainfo.xml
packages/c/cantata/package.yml
packages/c/cantata/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

cantata: Add appstream metainfo

---

packages/g/gpxsee/abi_used_symbols
packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- Added support for hillshading (IMG & Mapsforge maps).
- Fixed broken "recent files" under KDE/Plasma 6 style.
- Minor fixes (Mapsforge, IMG and ENC maps).
**Test Plan**
- open map file, zoom in and out
**Checklist**

gpxsee: Update to 13.17

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Added separate serifed variants for digits 2 through 5, current variants are renamed and reordered
- Reorder of glyph variants: I, U, Z, i, l, u, z, Greek Lower Mu (μ), Micro Sign (µ).
- Quasi-proportional will now use a six-unit system instead of four. Metrics of various letters (f, t, r, m, w, etc.) are adjusted
- Add new characters
- Fix a disjoint stroke of Outlined Curly Z under some weights
- Unify diagonal box drawings' angles
- Fix Large Type Piece U+1CE3B
- Added a MOSC feature that turns certain geometric shapes into mosaics
- Fix frac feature for better recognizing fraction patterns
- Fix broken shape of U+1FB95, U+1FB96 and U+1FB97
- Increase weight for U+276E/U+276F
- Fixed ligation for [|]
- [changelog](https://raw.githubusercontent.com/be5invis/Iosevka/main/cha …

font-iosevka-ttf: Update to 29.0.0

---

packages/h/handbrake/abi_used_symbols
packages/h/handbrake/package.yml
packages/h/handbrake/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/HandBrake/HandBrake/releases/tag/1.7.3).
- Fixes https://github.com/getsolus/packages/issues/1795
**Test plan**
- Encoded a movie.
**Checklist**

handbrake: update to 1.7.3

---

packages/m/mpc-qt/files/io.github.mpc_qt.mpc_qt.metainfo.xml
packages/m/mpc-qt/package.yml
packages/m/mpc-qt/pspec_x86_64.xml

**Summary**
Add appstream metainfo (Part of #1389)
**Test Plan**
**Checklist**

mpc-qt: Add appstream metainfo

---

packages/m/musescore/files/musescore-appdata.diff
packages/m/musescore/package.yml
packages/m/musescore/pspec_x86_64.xml

**Summary**
Fix icon generation on appstream metainfo with patch taken from [Flathub manifest](https://github.com/flathub/org.musescore.MuseScore/blob/master/patches/musescore-appdata.diff)

musescore: Fix icon generation on appstream metainfo

---

packages/c/clj-kondo/package.yml
packages/c/clj-kondo/pspec_x86_64.xml

**Summary**
- Changelog can be found [here](https://github.com/clj-kondo/clj-kondo/blob/v2024.03.05/CHANGELOG.md)
**Test Plan**
- Installed locally and ran clj-kondo --version to check updated version returned
**Checklist**

clj-kondo: Update to 2024.03.05

---

packages/n/nushell/abi_used_symbols
packages/n/nushell/package.yml
packages/n/nushell/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://www.nushell.sh/blog/2024-03-05-nushell_0_91_0.html#full-changelog-toc).
**Test plan**
- Built installed locally ran nu --version to check version then launched the shell and ran a few commands.
**Checklist**

nushell: Update to 0.91.0

---

packages/l/libxfce4ui/monitoring.yml
packages/l/libxfce4ui/package.yml
packages/l/libxfce4ui/pspec_x86_64.xml

**Summary**
- shortcuts-grabber: Remove filtering by level
**Test Plan**
Updated in a VM and observe that the desktop does not crash upon logging in.
**Checklist**

libxfce4ui: Update to 4.18.6

---

packages/py/pygal/package.yml
packages/py/pygal/pspec_x86_64.xml

**Summary**
- Bump 3.0.4
- No release notes.
**Test plan**
- Verified that it installed correctly.
**Checklist**

pygal: update to 3.0.4

---

packages/l/linux-steam-integration/package.yml
packages/l/linux-steam-integration/pspec_x86_64.xml
packages/s/steam/package.yml
packages/s/steam/pspec_x86_64.xml

**Summary**
- Blacklist libtcmalloc_minimal.so, in LSI intercept. It's bork
- Add missing rundep on curl-32bit
**Test Plan**
- TF2 now launches, should also fix HL2 DM and others.
**Checklist**

steam: Fix source 1 games when using native runtime

---

packages/q/qutebrowser/package.yml
packages/q/qutebrowser/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/qutebrowser/qutebrowser/blob/main/doc/changelog.asciidoc).
- Change from QT5 to QT6.
**Test plan**
- Installed, started and checked that it used QT6.
**Checklist**

qutebrowser: update to 3.1.0

---

packages/p/perl-locale-codes/monitoring.yml
packages/p/perl-locale-codes/package.yml
packages/p/perl-locale-codes/pspec_x86_64.xml

**Changelog:**
New code(s)
Full changelog available [here](https://metacpan.org/dist/Locale-Codes/view/lib/Locale/Codes/Changes.pod)
Solus:
Add monitoring.yml
**Test Plan**
Installed the module. Verified perl can load it.
```
perl -MLocale::Codes -e 'print $Locale::Codes::VERSION ."\n";'
```

perl-locale-codes:  update to 3.78

---

packages/b/budgie-desktop/files/fix-run-dialog-in-tasklist.patch
packages/b/budgie-desktop/files/workspace-switcher-fix.patch
packages/b/budgie-desktop/package.yml
packages/b/budgie-desktop/pspec_x86_64.xml

**Summary**
- Fix Budgie Run Dialog appearing in the tasklist
- Fix window icons not switching workspace when clicked in the workspace switcher
**Test Plan**
I've been running Budgie Desktop with these patches for a few weeks now.
**Checklist**

budgie-desktop: Fix regressions from 10.9

---

packages/q/quodlibet/package.yml
packages/q/quodlibet/pspec_x86_64.xml

**Summary**
-  Release notes can be found [here](https://quodlibet.readthedocs.io/en/latest/changelog.html#release-4-6-0).
**Test plan**
- Installed and added some music.
**Checklist**

quodlibet: update to 2.6.0

---

packages/e/eopkg4-bin/README.md

**Summary**
eopkg4-bin has now landed in the repository, so we don't need build instructions in the README for it.
**Test Plan**
No testing needed, this is a docs update only. No rebuild.
**Checklist**

eopkg4-bin: Update package README to reflect current testing situation

---

packages/e/eopkg4-bin/package.yml
packages/e/eopkg4-bin/pspec_x86_64.xml

**Summary**
Revert progress bar work in packagekit backend, as it was breaking package installation
**Test Plan**
- Build the package.
- Install the package. 
- See that PackageKit install operations work using the eopkg4-bin backend.
**Checklist**

eopkg4-bin: Revert progress bar work in packagekit backend

---

packages/p/packagekit/files/0001-policy-Change-group-to-sudo-and-allow-package-remove.patch
packages/p/packagekit/package.yml
packages/p/packagekit/pspec_x86_64.xml

**Summary**
- Allow users in sudo group to remove/install pkgs without prompt
**Test Plan**
`pkcon install pkg; pkcon remove pkg` <- no password prompt if i'm part of sudo group
**Checklist**

packagekit: Adjust policy rules for package installation/remove

---

packages/k/kitty/abi_symbols
packages/k/kitty/abi_used_symbols
packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
- Cheetah speed with a redesigned render loop and a 2x faster escape code parser that uses SIMD CPU vector instruction to parse data in parallel
- A new benchmark kitten (kitten __benchmark__) to measure terminal throughput performance
- Graphics protocol: Add a new delete mode for deleting images whose ids fall within a range. Useful for bulk deletion
- Keyboard protocol: Fix the Enter, Tab and Backspace keys generating spurious release events even when report all keys as escape codes is not set
- Allow specifying where the new tab is created for detach_window
- hints kitten: The option to set the text color for hints now allows arbitrary colors
- icat kitten: Add a command line argument to override terminal window size detection
- A new action toggle_tab to easily switch to …

kitty: Update to 0.33.0

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- New: Web interface now uses ACL grants to manage access on tagged devices
- Changed: Tailscale SSH connections now disable unnecessary hostname canonicalization
- Changed: tailscale bugreport command for generating diagnostic logs now contain ethtool information
- Changed: Mullvad's family-friendly server is added to the list of well known DNS over HTTPS (DoH) servers
- Changed: DNS over HTTP requests now contain a timeout
- Changed: TCP forwarding attempts in userspace mode now have a per-client limit
- Changed: Endpoints with link-local IPv6 addresses is preferred over private addresses
- Changed: WireGuard logs are less verbose
- Fixed: DERP server region no longer changes if connectivity to the new DERP region is degraded
- Changed: Auto-update version detection on …

tailscale: Update to 1.62.0

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Added new characters
- Fix broken s/t variants for U+01BE
- Fix precomposed iota with double marks
- Fix leaning mark placement on letters around i/l
- Fix sans-serif linking for U+2781..U+2784 and U+278B..U+278E
**Test Plan**
**Checklist**

font-iosevka-ttf: Update to 29.0.2

---

packages/g/git-cola/package.yml
packages/g/git-cola/pspec_x86_64.xml
packages/py/python-polib/package.yml
packages/py/python-polib/pspec_x86_64.xml

**Summary**
- Reintroduce `python-polib`. This is a dependency for `git-cola` 
**Test Plan**
- Run `git-cola` to view changes.
- Run `pip3 check` to check broken requirements.
**Checklist**

python-polib: Reintroduce for git-cola

---

packages/e/eopkg4-bin/package.yml
packages/e/eopkg4-bin/pspec_x86_64.xml

**Summary**
Sync eopkg4-bin's PackageKit backend with latest git, which includes a fix for [broken quick successive operations](https://github.com/getsolus/PackageKit/issues/3).
**Test Plan**
1. Install eopkg4-bin (rel 10) from the repo
2. Install PackageKit
3. Install a package for testing (I'm partial to `0ad`, but use anything)
4. Attempt to remove and quickly reinstall a package with PackageKit: `pkcon remove 0ad; pkcon install 0ad`
5. See that no packages are found on attempted reinstall
6. Build and install the PRed `eopkg4-bin` package
7. Attempt to remove and quickly reinstall the package again: `pkcon remove 0ad; pkcon install 0ad`
8. See that it works now
9. Celebrate!
**Checklist**

eopkg4-bin: Sync PackageKit Backend with git

---

Taskfile.yml

**Summary**
Part of #1496 
This changes the `Taskfile.yml` so the `publish` and `republish` tasks run the safety catches script as a task, instead of having it as a precondition. As far as I could learn there is no way to get full output from a precondition in `go-task`, so this is a workaround to get full command output plus the ability to force-through, like in the standalone script.
Old behaviour:
```
λ go-task publish
task: Failed to pass safety catches
task: precondition not met
```
New behaviour:
```
λ go-task publish
task: [run-safety-catches] "/home/thomas/Projects/go-task-test/common/Scripts/package-publish-safety-catches.sh"
Warning: Cannot determine that the release has been bumped
Press y to force-through. If unsure press any other key to abort.n
task: Failed to run task …
```

Taskfile: Call safety catches as a task instead of precondition

---

common/Scripts/worklog.py

**Summary**
Add an option that prints build log entries as soon as they are available. This works similarly to the familiar options in `tail`.
**Test Plan**
```sh
./worklog.py builds -F now
```
**Checklist**
- (N/A) ~~Package was built and tested against unstable~~

worklog.py: add -F/--follow option that follows the log

---

packages/p/protonmail-bridge/package.yml
packages/p/protonmail-bridge/pspec_x86_64.xml

**Summary**
**Summarized Changelog**:
- 3.10.0
- Preserve attachment encoding.
- Encrypt only with primary key.
- 3.9.1
- Updated Go version to 1.21.6 and couple of golang libraries.
- Updated keychain access library.
- Improved log format and content.
- Prevented various startup and sync issues.
Link to release notes: https://proton.me/download/bridge/stable_releases.html (not updated for 3.10.0 yet)
**Test Plan**
Synced and sent mail through Thunderbird.
**Checklist**

protonmail-bridge: update to 3.10.0

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Add fennel lang icon and associations
- Bugfix to resolve absolute paths that are not symlinks
- Add filetype and icon for .hh extension
- Fix total-size option
- Add fortran to source filetypes
- Fix `absolute_path()` for broken symlinks
- Add filetype and icon for age
- Adding icons for graphql extensions
- Add nim icons
- Use fsharp icon for fsproj files
- Add new icons, diverse selection
- Add `--absolute` flag
- Classification width should be taken into account with `-F=auto`
**Test Plan**
Run eza to view files in a directory.
**Checklist**

eza: Update to 0.18.8

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
- Draft issue IDs are included in project `item-list` output
- New `--dry-run` option for `pr create`
- Bump go-keyring to fix race condition
- PR numbers are prefixed with owner/repo for context
- Extra word removed in `codespaces` code comments
- Clarified description of the `-u`, `--user` option for `gh auth token`
- Fixed formatting for the description of `release upload`
- Clarified the usage of `auth status` to list all authenticated accounts
- Document auth switch behavior for two or more accounts
- Document run watch and view not supporting fine grained PATs
**Test Plan**
Run `gh status`, `gh pr list`, `gh pr view 1944` (while in the packages git repo), create this pull request.
**Checklist**

github-cli: Update to 2.46.0

---

packages/s/shim-signed/package.yml
packages/s/shim-signed/pspec_x86_64.xml

**Summary**
[15.8](https://github.com/rhboot/shim/releases/tag/15.8) [15.7](https://github.com/rhboot/shim/releases/tag/15.7)
**Security**
- CVE-2023-40546
- CVE-2023-40547
- CVE-2023-40548
- CVE-2023-40549
- CVE-2023-40550
- CVE-2023-40551
**Test Plan**
- Install, verify `clr-boot-manager update` is ran as part of usysconf
- Verify sha256sums match
- /usr/lib64/shim/fbx64.efi /boot/EFI/BOOT/fbx64.efi 2a437f086400b98534aa1d5c8d6d51c78cd20128667481abdbfd83b80e85e151
- /usr/lib64/shim/mmx64.efi /boot/EFI/com.solus-project/mmx64.efi b22a6c72a83553f5e9a2d40f384a61c1fd122f6363dcfd633234ad8c8fcb94b0
- /usr/lib64/shim/shimx64.efi /boot/EFI/com.solus-project/bootloaderx64.efi 4773d74d87c2371a25883b59a3b6d98d157de46933676706d215015b1130f2d1
- Reboot successfully, verify secureboot is enabled …

shim-signed: Update to 15.8

---

packages/u/usysconf/files/handlers-kernel-trigger-cbm-on-shim-changes.patch
packages/u/usysconf/package.yml
packages/u/usysconf/pspec_x86_64.xml

**Summary**
- So the updated shim files actually get copied to the ESP.
**Test Plan**
- Install, reinstall shim-signed, verify CBM gets triggered
**Checklist**

usysconf: Backport patch to trigger CBM on shim changes

---

packages/g/gnome-remote-desktop/package.yml
packages/k/krdc/package.yml
packages/v/vinagre/package.yml
packages/w/weston/package.yml

**Summary**
- Now freerdp(3) and freerdp2 are indexed into the repo it's safe
to switch back to the pkgconfig after the conflict.
- Depends on #1953 
**Test Plan**
N/A
**Checklist**

repo-wide: Switch back to pkgconfig builddep for freerdp2

---

packages/s/starship/package.yml
packages/s/starship/pspec_x86_64.xml

**Summary**
Features:
- `$gemset` variable for Ruby module
- bash: Support right prompt and transience
- bash: use PS0 for preexec hook
- quarto: Add Quarto module
- username: add detect_env_vars as option
Fixes:
- bash: Handle Unbound Variables Errors in Bash
- bash: improve integration with bash-preexec
- character: also handle vi edit mode in pwsh
- git_branch: fall back to "HEAD" when there is no current branch
- nu: continuation prompt not being displayed correctly
- status: fix pipestatus width calculation
- zsh: improve starship binary path escaping
**Test Plan**
Start a new shell running Starship, navigate to directories, navigate to a git directory.
**Checklist**

starship: Update to 1.18.0

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Fix height of block quadrants (U+2596..U+259F)
- Fix the design of the ESTIMATED SYMBOL (U+212E) to match its spec
- Refine design of POWER SYMBOL (U+23FB) and HEAVY CHECK MARK (U+2714)
- Make U+1FBBD..U+1FBBF narrow by default.
- Make LATIN {CAPITAL|SMALL} LETTER GHA (U+01A2..U+01A3) respond to variants of q (cv41).
- Make the behavior of serifs of U+027F automatic.
- Fix side bearings of U+29E2 under Quasi-Proportional.
- Fix width of PUNCTUATION SPACE (U+2008) under Quasi-Proportional.
- Fix percent=dots glyphs for PER {MILLE|TEN THOUSAND} SIGN (U+2030..U+2031) under Quasi-Proportional when NWID is enabled.
- Remove untagged variant selector for Cyrillic Capital Ef (Ф).
- Fix glyph visual for COMBINING DOUBLE CIRCUMFLEX ABOVE (U+1DCD).
- Fix variant assignment of cv92 for …

font-iosevka-ttf: Update to 29.0.3

---

packages/g/gpxsee/abi_used_symbols
packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- Added support for arbitrary CRSs in GeoJSON files.
- Added support for GeoJSON Coordinate Properties extension.
- CRS database consolidation.
**Test Plan**
- open map file, zoom in and out
**Checklist**

gpxsee: Update to 13.18

---

packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
- Fix requesting data via OSC 52 to instead return data from the primary selection
- Allow resizing until one of the halves in a split is minimally sized
**Test Plan**
- run cli command; view output in pager;
**Checklist**

kitty: Update to 0.33.1

---

packages/a/avahi/files/0001-Reduce-resolution-timeout-to-1s.patch
packages/a/avahi/files/series
packages/a/avahi/package.yml
packages/a/avahi/pspec_x86_64.xml
packages/b/baselayout/files/nsswitch.conf
packages/b/baselayout/pspec.xml

**Summary**
Enable mDNS lookups for IPv6 to ensure that mDNS hosts and addresses can be resolved for both IPv4 and IPv6.
**Test Plan**
| Test            | Before | After | 
|-----------------|:------:|:-----:|
| IPv4-only host  | IPv4   | IPv4  |
| IPv6-only host  | :x:    | IPv6  |
| Dual-stack host | IPv4   | IPv6  |
**Checklist**

baselayout: Enable IPv6 mDNS lookups

---

packages/l/libhtp/abi_symbols
packages/l/libhtp/abi_used_symbols
packages/l/libhtp/package.yml
packages/l/libhtp/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/OISF/libhtp/blob/0.5.47/ChangeLog).
**Test plan**
- Built suricata against this.
**Checklist**

libhtp: update to 0.5.47

---

packages/t/transmission/abi_used_libs
packages/t/transmission/abi_used_symbols
packages/t/transmission/monitoring.yml
packages/t/transmission/package.yml
packages/t/transmission/pspec_x86_64.xml

**Summary**
This adds a dependency on ayatana-appindicator to add support for StatusNotifier trays (like Budgie)
Resolves #1961
**Test Plan**
Confirmed the tray icon now shows up on Budgie
**Checklist**

transmission: Fix tray icon and add monitoring.yml

---

packages/c/cve-check-tool/abi_used_symbols
packages/c/cve-check-tool/package.yml
packages/c/cve-check-tool/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

cve-check-tool: Add homepage

---

packages/n/newsboat/abi_used_symbols
packages/n/newsboat/monitoring.yml
packages/n/newsboat/package.yml
packages/n/newsboat/pspec_x86_64.xml

**Summary**
Full changelog can be found [here](https://raw.githubusercontent.com/newsboat/newsboat/r2.35/CHANGELOG.md)
**Test Plan**
Open the app and check news feeds
**Checklist**

newsboat: Update to 2.35

---

common/Scripts/worklog.py

**Summary**
Improve the worklog build output with:
- An emoji indicating the job status.
- The build duration when the job is finished.
- The comment given to the bulid.
Depends on #1737 and updates to the build server.
**Test Plan**
Against a local build log:
**Checklist**

worklog.py: Add emoji, build time and comment to the worklog build output

---

packages/d/diffstat/package.yml
packages/d/diffstat/pspec_x86_64.xml

**Summary**
- Changelog can be found [here](https://invisible-island.net/diffstat/CHANGES)
**Test Plan**
- Use `diffstat` on patch file
**Checklist**

diffstat: Update to 1.66

---

packages/m/mtr/abi_used_symbols
packages/m/mtr/package.yml
packages/m/mtr/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/traviscross/mtr/blob/master/NEWS).
**Test plan**
- Installed and did som trace routes
**Check list**

mtr: update to 0.95

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- Send load balancing hint HTTP request header
- [changelog](https://github.com/tailscale/tailscale/releases/tag/v1.62.1)
**Test Plan**
- tailscale web
**Checklist**

tailscale: Update to 1.62.1

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Make U+2980 respond to VSAM.
- U+2AFC will no longer respond to VSAM.
- [changelog](https://github.com/be5invis/Iosevka/releases/tag/v29.0.4)
**Test Plan**
**Checklist**

font-iosevka-ttf: Update to 29.0.4

---

packages/f/font-ibm-plex/package.yml
packages/f/font-ibm-plex/pspec_x86_64.xml

**Summary**
- Added old-style numerals, Bulgarian Cyrillic forms, support for Abkhaz and pre-1918 Cyrillic
- Fixed Rendering of certain Cyrillic glyphs
- Fixed Difference in lineheight for SemiBold weight in some situations
- Improved shapes for U+0473 CYRILLIC SMALL LETTER FITA and U+0472 CYRILLIC CAPITAL LETTER FITA
- Changed U+00AD SOFT HYPHEN to empty non-spacing character
- Improved shapes for U+04AA CYRILLIC CAPITAL ES WITH DESCENDER and U+04AB CYRILLIC LOWERCASE ES WITH DESCENDER
- Added Kerning for glyph /rreh-ar.fina (U+FB8D)
- Removed substitutions to glyph /allah-ar (U+FDF2) in rlig feature
- Changed /softhyphen (U+00AD) to empty non-spacing character
- [changelog](https://github.com/IBM/plex/releases/tag/v6.4.0)
**Test Plan**
**Checklist**

font-ibm-plex: Update to 6.4.0

---

packages/d/devedeng/package.yml
packages/d/devedeng/pspec_x86_64.xml

**Summary**
- Changelog can be found [here](https://gitlab.com/rastersoft/devedeng/-/raw/4.18.0/HISTORY.md?ref_type=tags)
**Test Plan**
**Checklist**

devedeng: Update to 4.18.0

---

packages/py/pyenchant/package.yml
packages/py/pyenchant/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://pyenchant.github.io/pyenchant/changelog.html).
**Test plan**
- Installed and loaded rednotebook that is dependant on this and checked spell checking.
**Check list**

pyenchant: update to 3.2.2

---

Taskfile.yml

**Summary**
- Use `git rev-parse --git-path hooks` to find the hooks directory
- Use `git rev-parse --is-inside-work-tree` to find out if we're in an active git repo or not (despite the name this works for the "normal" repo as well as worktrees).

Taskfile: Fix several tasks that failed when in a worktree

---

packages/m/mate-desktop/package.yml
packages/m/mate-desktop/pspec_x86_64.xml

**Summary**
Changes:
- Make MateImageMenuItem subclassable
- MateImageMenuItem: Remove unnecessary label field
Resolves #1972
**Test Plan**
Launched a MATE session in a VM and on my laptop, used it for a while
**Checklist**

mate-desktop: Update to 1.28.2

---

packages/l/languagetool/files/git.properties
packages/l/languagetool/package.yml
packages/l/languagetool/pspec_x86_64.xml

**Summary**
- Asturian tagger and spelling dictionaries have been moved to an external dependency
- added and improved rules for Catalan and updated dictionary (spanish-pos-dict-2.25)
- added and improved Dutch rules
- English tagger and spelling dictionaries have been moved to an external dependency (english-pos-dict v 0.3)
- added and improved French rules
- added and improved German rules, extended dictionary
- small Polish rule improvements
- added and improved Portuguese rules
- added and improved Spanish rules and updated dictionary (spanish-pos-dict-2.2)
- new rules and words in Ukrainian POS dictionary, tagging and disambiguation improvements
- [changelog](https://raw.githubusercontent.com/languagetool-org/languagetool/v6.4/languagetool-standalone/CHANGES.md)
**Test Plan**
- …

languagetool: Update to 6.4

---

packages/n/nvtop/abi_used_symbols
packages/n/nvtop/monitoring.yml
packages/n/nvtop/package.yml
packages/n/nvtop/pspec_x86_64.xml

**Changelog:**
Added support for the following hardware accelerators/GPUs:
- More `Adreno GPUs` thanks to the panfrost linux driver
- `Mac GPUs` (tested on M1 and M2 by the community)
- `Huawei Ascend accelerators`
Bugfixes and improvements:
- Don't call handlers for GPUs that are marked as not to be monitored
- Fix crash when the configuration file path could not be discovered through user environment variables (XDG_HOME etc)
Full release notes available [here](https://github.com/Syllo/nvtop/releases)
Solus: Add monitoring.yml
**Test Plan**
Tested with:
Device 0 [TigerLake-H GT1 (UHD Graphics)]
Device 1 [NVIDIA GeForce RTX 3060 Laptop GPU]
- Open `nvtop` and run `glxgears`, also play a video file.
- Make sure the processes are shown and there is activity in `nvtop`
**Summary**
**Test …

nvtop: update to 3.1.0

---

packages/h/hunspell-pt-br/package.yml
packages/h/hunspell-pt-br/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://pt-br.libreoffice.org/projetos/vero).
**Test plan**
- Loaded in Libre Office and did some spell checking.
**Check list**

hunspell-pt-br: update to 3.2.15

---

packages/py/pycups/abi_used_symbols
packages/py/pycups/package.yml
packages/py/pycups/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/OpenPrinting/pycups/blob/master/NEWS).
**Test plan**
- Built system-config-printer against this.
**Check list**

pycups: update to 2.0.1

---

packages/u/umockdev/abi_symbols
packages/u/umockdev/abi_used_symbols
packages/u/umockdev/package.yml
packages/u/umockdev/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/martinpitt/umockdev/releases).
- Added homepage to package.yml, part of https://github.com/getsolus/packages/issues/411
**Test plan**
- Did a recording with umockdev-record
**Checklist**

umockdev: update to 0.18.1

---

packages/l/libopenshot/package.yml
packages/l/libopenshot/pspec_x86_64.xml

**Summary**
- Switch unit testing framework to Catch2
Upstream migrated tests from UnitTest++ to Catch2 about three years ago. Once this is merged, `unittest-cpp` can be deprecated.
Ref https://github.com/getsolus/packages/issues/2045
**Test Plan**
Build the package and verify that the tests run.
**Checklist**

libopenshot: Switch testing framework to Catch2

---

common/CI/package_checks.py
common/Hooks/pre-commit.py

**Summary**
This PR:
- Improves the output format when not running in CI.
- Shows this output when being called via a hook.
- Extends the package bump check so that pspec files must always be bumped.
Resolves #1888.
**Test Plan**
Run CI checks locally using `go-task check` in a fairly dirty working directory:
Try to commit a changed pspec file:
```
$ gotopkg nano
$ go-task build
$ git add pspec_x86_64.xml
$ git commit
ERR packages/n/nano/pspec_x86_64.xml:1: Package release is not incremented by 1
Package checks failed: <snip>/packages/common/CI/package_checks.py packages/n/nano/pspec_x86_64.xml
```
**Checklist**

ci/package_checks: Improve linter feedback and bump check

---

packages/t/tlp/package.yml
packages/t/tlp/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/linrunner/TLP/releases/tag/1.6.1).
- Fixes getsolus/packages/issues/983
**Test plan**
- Installed and checked that it loaded.
**Checklist**

tlp: update to 1.6.1

---

packages/i/iksemel/abi_used_symbols
packages/i/iksemel/files/0001-Escape-non-ASCII-characters.patch
packages/i/iksemel/files/0002-Escape-non-printable-ASCII-characters.patch
packages/i/iksemel/files/series
packages/i/iksemel/package.yml
packages/i/iksemel/pspec_x86_64.xml
packages/y/ypkg/package.yml
packages/y/ypkg/pspec_x86_64.xml

**Summary**
Add a patch to escape non-ASCII characters.
**Test Plan**
Build this stack and run solbuild with history and verify that polari now includes an encoded emoji:
```
$ gotopkg polari
$ sudo solbuild build -h -d -p local-unstable-x86_64
$ grep Remove pspec_x86_64.xml
* Remove GNOME from networks list &#x1f622; [Jeremy]
```
**Checklist**

iksemel: Fix encoding of emoji

---

packages/y/yubikey-manager/package.yml
packages/y/yubikey-manager/pspec_x86_64.xml

**Changelog:**
- Support for YubiKey Bio Multi-protocol Edition.
- CLI: Improve error messages for several failures.
- Attempt to send SIGHUP to yubikey-agent if it is blocking the connection.
- Bugfix: Allow "fido config" to work when no PIN is set on the YubiKey.
- Bugfix: Linux - Fix error when listing OTP devices when no YubiKeys are attached.
- Bugfix: OpenPGP - Fix RSA key generation on YubiKey NEO.
Full release notes available [here](https://github.com/Yubico/yubikey-manager/releases)
**Test Plan**
- YubiKey Manager can be run with `ykman`
- Program behaves as expected

yubikey-manager: update to 5.4.0

---

packages/y/yubikey-manager-qt/abi_used_symbols
packages/y/yubikey-manager-qt/monitoring.yml
packages/y/yubikey-manager-qt/package.yml
packages/y/yubikey-manager-qt/pspec_x86_64.xml

**Changelog:**
- Windows-only security fix, see advisory: [https://www.yubico.com/support/security-advisories/ysa-2024-01/](https://www.yubico.com/support/security-advisories/ysa-2024-01/)
Full release notes available [here](https://github.com/Yubico/yubikey-manager-qt/releases)
Solus: Add metainfo and monitoring files. Change to build with clang.
**Test Plan**
- YubiKey Manager GUI can be run via menu / ykman-gui
- Program behaves as expected

yubikey-manager-qt: update to 1.2.6

---

packages/e/exercism-cli/abi_used_symbols
packages/e/exercism-cli/package.yml
packages/e/exercism-cli/pspec_x86_64.xml

**Summary**
- This release fixes the exercism test command not working for the 8th and emacs-lisp tracks. The root command description is also simplified and the correct domain is used for the FAQ link.
- Full release notes can be found [here](https://github.com/exercism/cli/releases).
**Test Plan**
**Checklist**

exercism-cli: update to 3.3.0

---

packages/x/xorg-server/abi_symbols
packages/x/xorg-server/package.yml
packages/x/xorg-server/pspec_x86_64.xml
packages/x/xorg-xwayland/package.yml
packages/x/xorg-xwayland/pspec_x86_64.xml

**Summary**
- **xorg-xwayland: Update to 23.2.5**
- **xorg-server: Update to 21.1.12**
**Test Plan**
Restart my system running Budgie Desktop and see that nothing explodes.
**Checklist**

Update xorg-server and xorg-xwayland

---

packages/f/foliate/package.yml
packages/f/foliate/pspec_x86_64.xml

**Summary**
Bugfixes:
- Fixed end of chapter cut off when chapter starts with page break
- Fixed incorrect text wrapping in tables
- Fixed a performance issue with OPDS catalogs
- [3.1.1](https://github.com/johnfactotum/foliate/releases/tag/3.1.1)
**Test Plan**
- Launched the application
- Tried opening and reading a few books
- Tried changing themes, fonts and other settings
- Tried downloading books from the OPDS catalog
**Checklist**

foliate: Update to 3.1.1

---

packages/y/ypkg/package.yml
packages/y/ypkg/pspec_x86_64.xml

**Summary**
This commit renames the pure python executables to name.py and then names the nuitka-compiled binaries name.bin.
In turn, it symlinks name to name.bin as a matter of packaging policy, which in turns enables us to trivially test and/or switch to/from the pure python implementations by default via a simple release bump.
This has the benefit of always giving people the ability to inspect the source code of the current version of ypkg residing on their systems, and enables Solus to trivially do performance tests of the pure python versions vs. the nuitka compiled versions for any given package release.
**Test Plan**
Build eopkg4-bin with the updated ypkg in an enabled local repo and see that the build completes.
**Checklist**

ypkg: Control which binaries to use via symlinks

---

packages/b/bolt/abi_used_symbols
packages/b/bolt/package.yml
packages/b/bolt/pspec_x86_64.xml

**Summary**
- Add a nopcie security level since some devices report nopcie when Thunderbolt
is disabled through BIOS setting.
- Markdown lint styling is used for documents.
- Release notes can be found [here](https://gitlab.freedesktop.org/bolt/bolt/-/blob/master/CHANGELOG.md).
**Test plan**
- Installled and checked that it could see devices.
**Checklist**

bolt: update to 0.9.7

---

common/Legacy/Scripts/dep_check.py
common/Legacy/Scripts/find-old-packages.py
common/Scripts/dloader.py
common/Scripts/ep-update.py
common/Scripts/epcsearch.py
common/Scripts/find_deps.py
common/Scripts/gettag.py
common/Scripts/latent-rebuilds.py
common/Scripts/pbump.py
common/Scripts/yauto.py
common/Scripts/yconvert.py

**Summary**
Fixes #2091.
**Test Plan**
I launched all the scripts I ported and made sure the output is meaningful. Where arguments are required, I used `mame` for package.yml-based packages and pisi for pspec.xml-based packages.
Downloaded the `pspec.xml` file for `sublime-text` from 3rd-party and ran `yconvert.py` on it, and verified that the generated `package.yml` was filled out as expected. Ran `pbump.py` on the same `pspec.xml` and verified that there was a new history entry generated. Ran `yauto.py` with a tarball for `budgie-desktop` and verified that it generated and filled out a `package.yml` as expected.

Convert py2 scripts in common/ to py3

---

.github/workflows/script_lint.yml
common/Scripts/yauto.py

**Summary**
1st attempt at ensuring that all available common/Scripts/*.py files get linted as part of commits.
**Test Plan**
Run `go-task init && go-task check` and observe that nothing blows up when git hooks are run.
**Checklist**
~~- [x] Package was built and tested against unstable~~

CI/hooks: Bring py3 scripts under test per request

---

packages/l/lbreakouthd/monitoring.yml
packages/l/lbreakouthd/package.yml
packages/l/lbreakouthd/pspec_x86_64.xml

**Summary**
- Added new levelset JustGoForIt by unknown
- Workaround: return ball to paddle for illegal targets
- Fixed mini game Invaders
- Workaround: reset ball if in brick before getting target
- Show trajectory of balls with debugging enabled
- Reenabled bug report as configureable option
- Properly handle \r for levelsets made in windows
- Added xgettext comment to prevent wrong c-format
**Test Plan**
Play a few rounds
**Checklist**

lbreakouthd: Update to 1.1.7

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Add support for naming override
- Fix broken glyphs for serifed variants of LATIN SMALL LETTER S WITH CURL (U+1DF1E).
- Improve glyph visual for Bulgarian localization form for CYRILLIC CAPITAL LETTER EF (U+0424) under slab.
- Make descender serif of CYRILLIC {CAPITAL|SMALL} LETTER KOPPA (U+0480..U+0481) appear under any serifed variants for C/c.
- Make presence of descender serif automatic for LATIN CAPTITAL LETTER BETA (U+A7B4).
- Remove tailless variants for TURNED GREEK SMALL LETTER IOTA (U+2129).
- Make presence of top-right serif automatic for CYRILLIC SMALL LIGATURE EN GHE (U+04A5) under cyrl/en=tailed-top-left-serifed.
- Fix broken geometry of tailed i/l under heavy oblique quasi-proportional.
- Make Cyrillic Lower Em (cv74) use flat-bottom-serifless for sans and …

font-iosevka-ttf: Update to 29.1.0

---

packages/e/editorconfig-core-c/abi_used_symbols
packages/e/editorconfig-core-c/package.yml
packages/e/editorconfig-core-c/pspec_x86_64.xml

**Summary**
- Fix pointer overflow in STRING_CAT.
- Fix a few more stack buffer overflows.
- Add license for FindPcre2 from LuaDist.
- Document and CI fixes.
- Release notes can be found [here](https://github.com/editorconfig/editorconfig-core-c/releases).
**Test Plan**
- Installed and checked it with gnome-text-editor
**Checklist**

editorconfig-core-c: update to 0.12.7

---

packages/m/mu/abi_used_symbols
packages/m/mu/package.yml
packages/m/mu/pspec_x86_64.xml

**Summary**
- improve documentation / manpages
- add --reindex option to 'mu index'
- split off mu4e-complete-contact (for wider use)
- work around some mail rendering issues with some emacs version
- update some dependencies
- fix some build warnings on older emacsen
- fix musl build
**Test Plan**
- search and view message
**Checklist**

mu: Update to 1.12.3

---

packages/a/appstream-data/package.yml
packages/a/appstream-data/pspec_x86_64.xml

**Summary**
Update Appstream Metainfo to v37
**Test Plan**
1. Install package built per PR
2. See that deprecated packages no longer appear in Discover search
**Checklist**

appstream-data: Update Appstream Metainfo to v37

---

packages/z/zstd/abi_symbols
packages/z/zstd/abi_symbols32
packages/z/zstd/abi_used_symbols
packages/z/zstd/monitoring.yml
packages/z/zstd/package.yml
packages/z/zstd/pspec_x86_64.xml

Release notes available [here](https://github.com/facebook/zstd/releases/tag/v1.5.6)
Note that I had a build failure during the emul32 build in `make zstd-dll -C programs`. Rather than figure this out I opted to just skip that during the emul32 build since it's not needed anyway (we only care about the 32bit shared libs).

zstd: Update to v1.5.6

---

packages/t/tailscale/files/defaults.patch
packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- Changed: tailscale serve headers are now RFC 2047 Q-encoded
**Test Plan**
- tailscale web
**Checklist**

tailscale: Update to 1.64.0

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Drop NWID glyphs for ligatures in quasi-proportionals
- Make presence of descender serif automatic for GREEK CAPITAL KAI SYMBOL
- Make presence of top-left serif automatic for CYRILLIC LETTER BASHKIR KA
- Make GREEK SMALL LETTER DIGAMMA respond to top-right serif variants of Greek Capital Gamma
- Make GREEK SMALL LETTER HETA respond to top-left serif variants of H
- Make CYRILLIC LIGATURE EN GHE respond to top-right serif variants of Greek Capital Gamma
- Make CYRILLIC LETTER STRAIGHT U follow variants of Cyrillic U
- Make the terminal of LETTER SCHWA a full hook under italics
**Test Plan**
**Checklist**

font-iosevka-ttf: Update to 29.2.0

---

packages/w/weechat/abi_used_symbols
packages/w/weechat/monitoring.yml
packages/w/weechat/package.yml
packages/w/weechat/pspec_x86_64.xml

**Summary**
- core: fix reset to initial scroll position after search of text in buffer
- core: add missing mouse events "alt-ctrl-button2" and "alt-ctrl-button3"
- exec: remove trailing space on buffers with free content when line numbers are not displayed
- exec: add missing exec tags in lines of buffers with free content
- irc: fix random date displayed when a received message contains tags but no "time"
- irc: add missing tags on self action messages when capability echo-message is enabled
- python: fix truncation of unsigned long long integer returned by function string_parse_size
- relay: set the last IRC client disconnection time only after a successful connection
- script: always display list of scripts when searching scripts with `/script search`
- script: fix default mouse keys …

weechat: Update to 4.2.2

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
- Fix typo in `auth switch` help example
- gh-attestation cmd integration
- Fix segfault in error handling of `gh repo rename`
**Test Plan**
Run `gh status`, `gh pr list` in the packages repo, and create this Pull Request.
**Checklist**

github-cli: Update to 2.47.0

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Switch out `ansiterm` crate for `nu_ansi_term`
- Bump `trycmd` from 0.15.0 to 0.15.1
**Test Plan**
Run `eza` without options, with the list option, and with the color option.
**Checklist**

eza: Update to 0.18.10

---

packages/s/svtplay-dl/package.yml
packages/s/svtplay-dl/pspec_x86_64.xml

**Summary**
- tv4play and svtplay will have the corret order in -A again
- support for regeringen.se
- support for vasaloppet.se
- postprocessing should work better with dolby vision HDR
- removed support for subtitles for pluto.tv because their ads makes their mess up with timecodes..
- tv4play handle upcoming videos better so it wont show a error message
- svtplay improved support for syntolkat (sv-x-ad language)
**Test Plan**
- Installed, downloaded a video and watched it.
**Checklist**

svtplay-dl: update to 4.72

---

packages/f/fdk-aac/monitoring.yml
packages/f/fdk-aac/package.yml
packages/f/fdk-aac/pspec_x86_64.xml

**Summary**
- Fixed one case of a failed assert in SBR encoding
- Added build support for s390x
- Full changelog can be found [here](https://raw.githubusercontent.com/mstorsjo/fdk-aac/v2.0.3/ChangeLog)
**Test Plan**
- Rebuild `gnome-remote-dekstop` and `gstreamer-1.0-plugins-bad` against this package
**Checklist**

fdk-aac: Update to 2.0.3

---

common/Scripts/worklog.py

**Summary**
- Add links to CVEs mentioned in the commits to the update output.
- Add a command for listing all updates that include security fixes.
**Test Plan**
```
$ ./common/Scripts/worklog.py security-updates "2024-03-29T17:45:11Z" --format=tty
5 security-updates:
wireshark 4.2.4-85 [@silkeh] [CVE-2024-2955]
capnproto 1.0.2-6 [@algent-al] [CVE-2023-48230]
golang 1.22.2-112 [@silkeh] [CVE-2023-45288]
xorg-server 21.1.12-100 [@EbonJaeger] [CVE-2024-31080, CVE-2024-31081, CVE-2024-31082, CVE-2024-31083]
xorg-xwayland 23.2.5-24 [@EbonJaeger] [CVE-2024-31080, CVE-2024-31081, CVE-2024-31083]
```
```
$ ./common/Scripts/worklog.py security-updates "2024-03-29T17:45:11Z" --format=md
5 security-updates:
- **wireshark** was updated to **4.2.4-85** …
```

worklog.py: Add CVE links and a `security-updates` command.

---

packages/k/kodi/package.yml
packages/k/kodi/pspec_x86_64.xml

**Summary**
- Kodi will not start unless crossguid lib installed
**Test Plan**
- remove crossguid
- reinstall and start kodi
**Checklist**

kodi: Add required rundep

---

packages/f/fakeroot/abi_symbols
packages/f/fakeroot/abi_symbols32
packages/f/fakeroot/abi_used_symbols
packages/f/fakeroot/abi_used_symbols32
packages/f/fakeroot/monitoring.yml
packages/f/fakeroot/package.yml
packages/f/fakeroot/pspec_x86_64.xml

**Summary**
- Changelog : 
- 1.34 : faked now ignores SIGWINCH. 
- 1.33 : Add renameat2 support. 
- 1.32.2 : 
- Romanian man page translation 
- add missing wrapped.h dependency.
- Full changelog is [here](https://salsa.debian.org/clint/fakeroot/-/raw/51aafce59afeb0852805f3abf2926deb95c2172b/debian/changelog)
**Test Plan**
- Run `ypkg` to build packages
**Checklist**

fakeroot: Update to 1.34

---

packages/s/snapd/package.yml
packages/s/snapd/pspec_x86_64.xml

**Summary**
New upstream release.
* Aspects based configuration schema support (experimental)
* Refresh app awareness support for UI (experimental)
* Support for user daemons by introducing new control switches --user/--system/--users for service start/stop/restart (experimental)
* Add AppArmor prompting experimental flag (feature currently unsupported)
* Installation of local snap components of type test
* Packaging of components with snap pack
* Expose experimental features supported/enabled in snapd REST API endpoint /v2/system-info
* Support creating and removing recovery systems for use by factory reset
* Enable API route for creating and removing recovery systems using /v2/systems with action create and /v2/systems/{label} with action remove
* Lift requirements for fde-setup hook …

snapd: Update to 2.62

---

packages/g/google-api-python-client/package.yml
packages/g/google-api-python-client/pspec_x86_64.xml
packages/py/python-pydrive2/package.yml
packages/py/python-pydrive2/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/googleapis/google-api-python-client/releases/tag/v2.125.0).
**Test Plan**
- Updated python-pydrive2 against this
**Checklist**

 google-api-python-client: update to 2.125.0 

---

.github/workflows/script_lint.yml
Taskfile.yml
common/CI/package_checks.py
common/Scripts/package-publish-safety-catches.sh

**Summary**
Run the CI checks in the safety catches instead of using a separate implementation.
Depends on #2038. Resolves #1496.
**Test Plan**
Run `go-task run-safety-catches` on a branch that is ahead of main (with these changes checked out):
**Checklist**

common: Rework `package-publish-safety-catches.sh` to use the CI checks

---

packages/k/kitty/abi_symbols
packages/k/kitty/abi_used_symbols
packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
- Show a small scrollback indicator along the right window edge when viewing the scrollback to keep track of scroll position
- A new option terminfo_type to allow passing the terminfo database embedded into the TERMINFO env var directly instead of via a file
- Mouse reporting: Fix drag release event outside the window not being reported in legacy mouse reporting modes
- Fix handling of tab character when cursor is at end of line and wrapping is enabled
- Splits layout: Fix move_window_forward not working
- fish shell integration: Fix clicking at the prompt causing autosuggestions to be accepted, needs fish >= 3.8.0
- Fix for a regression in 0.32.0 that caused some CJK fonts to not render glyphs
- When asking for quit confirmation because of a running program, mention the …

kitty: Update to 0.34.0

---

packages/m/mu/package.yml
packages/m/mu/pspec_x86_64.xml

**Summary**
- query when quitting emacs with unhandled marks in a headers buffer
- fix mime-handling
- update sent handling (simplifying it)
- some internal improvements
- number of small fixes / updates
- documentation updates
- re-enable a specific database lock; this makes indexing a bit slower, but hopefully avoids some db corruption.
**Test Plan**
- reindex inbox with mu; search for and view message with mu4e
**Checklist**

mu: Update to 1.12.4

---

packages/n/nautilus-dropbox/abi_used_symbols
packages/n/nautilus-dropbox/package.yml
packages/n/nautilus-dropbox/pspec_x86_64.xml

**Summary**
Changelog can be found [here](https://raw.githubusercontent.com/dropbox/nautilus-dropbox/v2024.04.17/ChangeLog)
**Test Plan**
Sync file from pc to cloud
**Checklist**

nautilus-dropbox: Update to 2024.04.17

---

packages/g/gptfdisk/abi_used_symbols
packages/g/gptfdisk/package.yml
packages/g/gptfdisk/pspec_x86_64.xml

**Summary**
- Fixed problem that caused sgdisk to crash with errors about being unable to read the disk's partition table when compiled with the latest popt (commit 740, which is pre-release as I type; presumably version 1.19 and later once released).
- Updated guid.cc to deal with minor change in libuuid.
- Fixed potential NULL derefernce bug in sgdisk. Thanks to Damian Kurek for this fix.
- The partition number of "0" can now be used to reference newly-created partitions when the --largest-new=0 option to sgdisk is used. Thanks to David Joaquín Shourabi Porcel for this improvement.
- Make explicit casts in gptcurses.cc to eliminate compiler warnings about mis-matched types in printw() statements.
- Minor code cleanup based on valgrind analysis.
- In previous versions, GPT fdisk accepted …

gptfdisk: update to 1.0.10

---

packages/y/yaru-theme/monitoring.yml
packages/y/yaru-theme/package.yml
packages/y/yaru-theme/pspec_x86_64.xml

**Summary**
Changelog available [here](https://github.com/ubuntu/yaru/blob/24.04.2-0ubuntu1/debian/changelog)
**Test Plan**
Switched widget/icon theme to several Yaru variants and looked at the result
**Checklist**

yaru-theme: Update to 24.04.2 and add monitoring.yml

---

packages/m/mate-panel/abi_used_symbols
packages/m/mate-panel/package.yml
packages/m/mate-panel/pspec_x86_64.xml

**Summary**
This release makes use of the fixes in mate-desktop 1.28.2
Changes:
- Build: require mate-desktop 1.28.2
- Use MateImageMenuItem properly
**Test Plan**
Launched MATE session and confirmed panel plus applets were still working correctly
**Checklist**

mate-panel: Update to 1.28.2

---

packages/w/wine/abi_symbols
packages/w/wine/abi_symbols32
packages/w/wine/abi_used_symbols
packages/w/wine/abi_used_symbols32
packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
- Initial SLTG-format typelib support in widl
- Exception handling on ARM64EC
- Improvements to Minidump support
- Support for advanced AVX features in register contexts
- More Direct2D effects work
- Support for RSA OAEP padding in BCrypt
- Interpreted mode fixes in WIDL
- Build system support for ARM64X
- Some restructuration of the Vulkan driver interface
- WIDL improvements for ARM support as well as SLTG typelibs
- [9.5](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.5)
- [9.6](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.6)
- [9.7](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.7)
**Test Plan**
- Ran `winecfg`, `wineconsole`, `winemine`, `winefile`
**Checklist**

wine: Update to 9.7

---

Taskfile.yml

**Summary**
This adds a go-task command to create a monitoring.yml skeleton file that can then be manually filled in
**Test Plan**
Created a new `monitoring.yml` using `go-task add-monitoring`

Taskfile: Add go-task command to create monitoring.yml skeleton

---

packages/py/python-maturin/package.yml
packages/py/python-maturin/pspec_x86_64.xml

**Summary**
Changes:
- In pep517 build default compatibility to off instead of always specifying
- Fix upload returning `malformed summary` error
**Test Plan**
Built `python-orjson`
**Checklist**

python-maturin: Update to 1.5.1

---

packages/py/python-orjson/abi_used_symbols
packages/py/python-orjson/package.yml
packages/py/python-orjson/pspec_x86_64.xml

**Summary**
Changes:
- Support serializing `numpy.float16` (`numpy.half`)
- sdist uses metadata 2.3 instead of 2.1
- Fix: Serializing `numpy.ndarray` with non-native endianness raises `orjson.JSONEncodeError`
- Improve performance of serializing
**Test Plan**
Ran through the examples in the project README
**Checklist**

python-orjson: Update to 3.10.1

---

packages/py/python-moddb/monitoring.yml
packages/py/python-moddb/package.yml
packages/py/python-moddb/pspec_x86_64.xml

**Summary**
Changes:
- Fixed an edge case in comment parsing
- Added `FrontPage.get_poll` to get the poll on the front page
- Ratelimiting login request to to 1/5s
- Ratelimited requests that are asked to raise will now raise `moddb.errors.Ratelimited`
- Profiles now display the aggregated download count of mods and games (if they have one) under `download_count`
- Removed `FrontPage.poll` to reduce the number of requests used when calling `front_page()`
**Test Plan**
Executed some examples from the project documentation
**Checklist**

python-moddb: Update to 0.11.0

---

packages/i/imath/abi_used_symbols
packages/i/imath/package.yml
packages/i/imath/pspec_x86_64.xml

**Summary**
Patch release with two small build fixes/features:
- Add explicit `std::` namespace for `isfinite` in `ImathFun.cpp`
- Add `uninstall` target
This release also introduces the practice of signing release artifacts via [sigstore](https://www.sigstore.dev).
**Test Plan**
- Installed and started Krita which is dependant on this.
**Checklist**

imath: update to 3.1.11

---

packages/w/webp-pixbuf-loader/MAINTAINERS.md
packages/w/webp-pixbuf-loader/abi_used_symbols
packages/w/webp-pixbuf-loader/monitoring.yml
packages/w/webp-pixbuf-loader/package.yml
packages/w/webp-pixbuf-loader/pspec_x86_64.xml

**Summary**
Changes:
- libwebp 1.3.2 onwards is a requirement now due to security vulnerability
- Update signal emissions and support for 0ms frames
Note: Added myself as maintainer as old one is no longer active
**Test Plan**
Checked thumbnails for .webp images in file manager
**Checklist**

webp-pixbuf-loader: Update to 0.2.7 and add monitoring.yml

---

packages/a/anki/abi_used_symbols
packages/a/anki/monitoring.yml
packages/a/anki/package.yml
packages/a/anki/pspec_x86_64.xml

**Summary**
Release notes:
- [24.04](https://github.com/ankitects/anki/releases/tag/24.04)
- [24.04.1](https://github.com/ankitects/anki/releases/tag/24.04.1)
**Test Plan**
Played through a couple of cards in a Japanese deck, with audio and images
**Checklist**

anki: Update to 24.04.1 and add monitoring.yml

---

packages/i/i2c-tools/abi_used_symbols
packages/i/i2c-tools/package.yml
packages/i/i2c-tools/pspec_x86_64.xml

**Summary**
- decode-dimms: Attempt to decode LPDDR3 modules
- eeprom, eepromer: Removed the tools in favor of eeprog
-  i2cdetect: Sort the bus list by number
-  i2cdump: Add range support to I2C block mode
-  Deprecate SMBus block mode
-  i2cget: Add support for I2C block read 
- Add support for SMBus block read
- i2ctransfer: Reverted check for returned length from driver
**Test Plan**
**Checklist**

i2c-tools: update to 4.3

---

packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
- Fix window background blur not adapting when window is grown. Also fix turning it on and off not working
- Draw the titlebar buttons without using a font
- Fix a regression in the previous release that caused incorrect font selection when using variable fonts
**Test Plan**
- open TERM, run htop
**Checklist**

kitty: Update to 0.34.1

---

packages/g/gpxsee/abi_used_symbols
packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- Added support for FIT course icons.
- Added support for GPX water temperature extension.
- Multiple minor map fixes (IMG & Mapsforge).
**Test Plan**
- open map file, zoom in and out
**Checklist**

gpxsee: Update to 13.19

---

packages/o/obs-vkcapture/MAINTAINERS.md
packages/o/obs-vkcapture/abi_symbols
packages/o/obs-vkcapture/abi_used_symbols
packages/o/obs-vkcapture/monitoring.yml
packages/o/obs-vkcapture/package.yml
packages/o/obs-vkcapture/pspec_x86_64.xml

**Summary**
Changes:
- Dropped support for OBS 27
- Added initial support for HDR
**Test Plan**
Captured footage of the game "b"
**Checklist**

obs-vkcapture: Update to 1.5.0 and add monitoring.yml

---

packages/k/kildclient/abi_symbols
packages/k/kildclient/abi_used_libs
packages/k/kildclient/abi_used_symbols
packages/k/kildclient/package.yml
packages/k/kildclient/pspec_x86_64.xml

**Summary**
- Bug fixed: $world->hookenabled now works correctly when checking status of hook 0.
- Bug fixed: KCWin's are again scrolled when text is added to them.
- Bug fixed: if called with a command-line argument that is not the  name of a saved world, KildClient tries to interpret that as a  hostname, instead of crashing.
- Bug fixed: it is now possible to copy text via the output area context menu again.
**Test Plan**
**Checklist**

kildclient: update to 3.2.1

---

packages/s/solus-mate-transition-tool/package.yml
packages/s/solus-mate-transition-tool/pspec_x86_64.xml

**Summary**
- Provides an upgrade path for existing MATE installs
- Resolves #1134.
**Test Plan**
- Run tool on MATE vm and install XFCE in non US locale
- Run tool on MATE vm and install Budgie in non US locale
**Checklist**

solus-mate-transition-tool: Initial inclusion at v0.4

---

packages/s/svtplay-dl/package.yml
packages/s/svtplay-dl/pspec_x86_64.xml

**Summary**
- svtplay: fix crash on some clips
- removed –audio-role (all the interesting audio is in the –audio-language)
- added –video-role. works like –audio-role. but with some improvement. for example alternate-sign role for teckenspråkstolkat. some downloaded videos in 4.71 and 4.72 might have gotten the wrong video because of this….
- added -R for reversed download order with -A.
**Test Plan**
- Downloaded a movie and played it.
**Checklist**

svtplay-dl: update to 4.73

---

common/CI/package_checks.py

**Summary**
Add an exception for `EULA`, as that is used by the following packages:
```
hsa-amd-aqlprofile
intel-microcode
nvidia-470-glx-driver
nvidia-beta-driver
nvidia-developer-driver
nvidia-glx-driver
opencv
```
This is not a valid SPDX license identifier, but there is no valid alternative.
Resolves #2423
**Test Plan**
Verify the warning is no longer there:
```
$ ./common/CI/package_checks.py packages/i/intel-microcode/package.yml
Checking files: packages/i/intel-microcode/package.yml
Found 2 result(s), 1 warnings and 0 error(s)
INF packages/i/intel-microcode/package.yml:1: This package is included in the ISO. Consider validating the functionality in a newly built ISO.
WRN packages/i/intel-microcode/package.yml:1: Package release is not incremented by 1
```

ci/package_checks: Add exception for `EULA` as a package license

---

packages/u/upx/abi_used_symbols
packages/u/upx/package.yml
packages/u/upx/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/upx/upx/blob/master/NEWS).
**Test Plan**
**Checklist**

upx: update to 4.2.3

---

packages/e/element/files/0001-Unpack-package.json.patch
packages/e/element/files/Element.desktop
packages/e/element/files/autolaunch.patch
packages/e/element/files/electron-desktop.sh
packages/e/element/files/element.appdata.xml
packages/e/element/package.yml
packages/e/element/pspec_x86_64.xml

Changes:
- Remove `MESA_SHADER_CACHE_DISABLE` which I assume is a workaround for that issue
- Syncs some changes from the flathub .desktop file to our one (keywords and categories mostly)
- Add a wrapper script to pick up user-configured flags
- Re-try enabling Wayland by default (newer Electron and all that)
- Fix an issue where selecting "launch on startup" would create a .desktop file with the wrong binary path (which is problematic with the wrapper script)

element: Use Wayland by default

---

common/autobuild-ignore-doxygen.yml
common/autobuild-ignore-python-pytest.yml
packages/l/llvm-bolt/autobuild.yml
packages/l/llvm/autobuild.yml
packages/m/mesalib/autobuild.yml
packages/o/openjdk-17/autobuild.yml
packages/p/pulseaudio/autobuild.yml
packages/py/python-chardet/autobuild.yml
packages/py/python-jinja/autobuild.yml
packages/py/python-requests/autobuild.yml
packages/py/python-wheel/autobuild.yml
packages/t/tpm2-tss/autobuild.yml

**Summary**
This is the initial attempt at showing how to use the power of autobuild for getting the Solus monorepo under control re. dependency cycles. It is based on [this gist](https://gist.github.com/GZGavinZhao/4981fb5ba874ac82364b18b039e3f495).
The purely additive nature of the autobuild.yml configuration files added with this commit, should make it trivial to modify and extend the ignored set of dependencies for a package as our cycle-discovery journey advances.
To gain an appreciation of just how useful this tool might become for us, consider the following:
```
ermo@solbox:~/repos/getsolus/soluspkgs
$ autobuild -q query src:packages/ samba ldb tdb talloc tevent
talloc tdb cifs-utils notmuch tevent ldb samba acccheck ffmpeg python-pysmbc gvfs kio-extras kodi mpd rhythmbox vlc …
```

samba: Add autobuild.yml files for dep resolution

---

packages/py/python-orjson/package.yml
packages/py/python-orjson/pspec_x86_64.xml

**Summary**
Changes:
- Fix crash serializing `str` introduced in 3.10.1
- Drop support for arm7
**Test Plan**
Ran through the examples in the project README
**Checklist**

python-orjson: Update to 3.10.2

---

packages/f/freerdp/abi_symbols
packages/f/freerdp/abi_used_symbols
packages/f/freerdp/package.yml
packages/f/freerdp/pspec_x86_64.xml

**Summary**
This release eliminates a bunch of issues detected during oss-fuzz runs. The test coverage was increased and detected issues eliminates, so an update is highly recommended.
Noteworthy changes:
- Lots of fixes for oss-fuzz reports
- Timezone detection fixes
- SDL key remapping support
- Improved help
- FreeBSD epoll detection fix
**Test Plan**
- Started remmina and made an connection.
**Checklist**

freerdp: update to 3.5.1

---

packages/z/zellij/package.yml
packages/z/zellij/pspec_x86_64.xml

**Summary**
- fix(sessions): issue where sessions would occasionally become unresponsive
- fix(cli): respect all options (eg. `default-layout`) when creating a session in the background from the CLI
- fix(cli): rename tab and pane from cli
- fix(plugins): respect `$SHELL` when opening a terminal from plugins
- fix(tabs): closing a tab no longer breaks tab movement
- feat(plugins): add API to open new tabs with a LayoutInfo
- feat(cli): add zellij action `list-clients` to allow listing the connected clients as well as their `pane_id` and running command
- feat(cli): allow binding Ctrl J
**Test Plan**
Start a new session with Zellij, create a new tab, move them around.
**Checklist**

zellij: Update to 0.40.1

---

packages/m/mate-themes/package.yml
packages/m/mate-themes/pspec_x86_64.xml

**Summary**
- Changelog [here](https://github.com/mate-desktop/mate-themes/releases/tag/v3.22.26)
- Part of getsolus/packages#2124
**Test Plan**
Apply theme on mate install
**Checklist**

mate-themes: Update to 3.22.26

---

packages/m/mate-calc/abi_used_symbols
packages/m/mate-calc/package.yml
packages/m/mate-calc/pspec_x86_64.xml

**Summary**
- Translations update
- Fix implicit function declarations with `libxml2` 2.12
- tx: fix warning in Japanese translations
- Part of getsolus/packages#2124
**Test Plan**
Do some calculations
**Checklist**

mate-calc: Update to 1.28.0

---

packages/m/mu/abi_used_symbols
packages/m/mu/package.yml
packages/m/mu/pspec_x86_64.xml

**Summary**
- Split off parts into mu4e-draft.el to maintain the current buffer as expected
- New hook mu4e-compose-post-hook for tweaking what mu4e does when we're done with a message
- Better handle forwarding of encoded messages
- Don't remove non-mu4e completion in composer
- Integrate iCalendar support with message-composition
- Handle mu4e-sent-messages-behavior correctly when it's a function
- Support some file systems that don't put the file type in d_type
- Improve documentation
**Test Plan**
- index mailbox; search for and view message
**Checklist**

mu: Update to 1.12.5

---

packages/w/wine/abi_libs
packages/w/wine/abi_libs32
packages/w/wine/abi_symbols
packages/w/wine/abi_symbols32
packages/w/wine/abi_used_symbols
packages/w/wine/abi_used_symbols32
packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
- Mono engine updated to version 9.1.0
- IDL-generated files use fully interpreted stubs
- Improved RPC/COM support on ARM platforms
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.8)
**Test Plan**
- Ran `winefile`, `wineconsole`, `winecfg`, `winemine`
- Played Age of Empires I trial version
**Checklist**

wine: Update to 9.8

---

packages/m/man-pages/monitoring.yml
packages/m/man-pages/package.yml
packages/m/man-pages/pspec_x86_64.xml

**Summary**
New and rewritten pages:
- TIMEVAL_TO_TIMESPEC.3
Newly documented interfaces in existing pages:
- process_madvise() glibc wrapper
New and changed links:
- TIMESPEC_TO_TIMEVAL.3 (TIMEVAL_TO_TIMESPEC(3))
Global changes:
- Updated and reorganized build system
Full release notes available [here](https://lwn.net/ml/linux-kernel/Zfna9TOEMqQdI88n@debian/)
**Test Plan**
Looked at a number of man pages (new and old)
**Checklist**

man-pages: Update to 6.7

---

packages/b/baselayout/package.yml
packages/b/baselayout/pspec_x86_64.xml
packages/b/bash/files/profile/10-path.sh
packages/b/bash/package.yml
packages/b/bash/pspec_x86_64.xml

**Summary**
- Symlink {/bin,/sbin} to {/usr/bin,/usr/sbin}
- Any existing binaries in /bin or /sbin will be seemlessly moved over.
- Drop /bin and /sbin from default $PATH
Part of #293.
Note: that /lib will be merged to /usr in a follow up PR as `kernel-glue` and CBM will have to be investigated.
Note: this is a forward change only as our current baselayout never managed /bin or /sbin paths as they were created ad-hoc by packages.
**Test Plan**
- Create a new rootfs from scratch from this baselayout
- Create a new solbuild image from this baselayout and use it
- Build and launch ISOs from this baselayout
- Create custom binaries in `/bin` and `/sbin` and verify they get moved over to `/usr/bin` and `/usr/sbin` respectively
- `realpath /bin` -> `/usr/bin`
- `realpath /sbin` -> `/usr/sbin` …

Merge /bin and /sbin into /usr

---

packages/x/xfce4-panel-profiles/monitoring.yml
packages/x/xfce4-panel-profiles/package.yml
packages/x/xfce4-panel-profiles/pspec_x86_64.xml

**Summary**
This adds the `python-psutil` dependency without which the app fails to start.
Thanks to @celiopy for the hint [here](https://discuss.getsol.us/d/10580-few-issues-with-xfce)
**Test Plan**
Confirmed app now launches on a fresh install
**Checklist**

xfce4-panel-profiles: Add missing rundep and monitoring.yml

---

packages/n/nvidia-vaapi-driver/abi_used_symbols
packages/n/nvidia-vaapi-driver/monitoring.yml
packages/n/nvidia-vaapi-driver/package.yml
packages/n/nvidia-vaapi-driver/pspec_x86_64.xml

**Summary**
Changes:
- Single buffer export
- direct: Fix drm index loop condition
- Fix building with musl
- Unbreak build on FreeBSD
- src: Increase num_render_targets to 32 for Chromium
- Fix undefined reference to 'gettid'
**Test Plan**
Confirmed video acceleration in `firefox` on a bunch of different websites, using `nvidia-smi`
**Checklist**

nvidia-vaapi-driver: Update to 0.0.12 and add monitoring.yml

---

packages/c/clojure-tools/package.yml
packages/c/clojure-tools/pspec_x86_64.xml

**Summary**
Release notes can be found [here](https://github.com/clojure/brew-install/blob/1.11.3/CHANGELOG.md)
**Test Plan**
Installed and ran clojure --version followed by clojure running a basic print statement in the repl.
**Checklist**

clojure-tools: Update to clojure CLI 1.11.3.1463

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
- Do not mutate headers when initialising tableprinter
- Document relationship between host and active account
- Added support for jobs with long filenames
- Fix `attestation verify` source repository check bug
**Test Plan**
Run `gh status`, `gh pr list`, and create this pull request.
**Checklist**

github-cli: Update to 2.49.1

---

packages/s/strongswan/abi_symbols
packages/s/strongswan/abi_used_symbols
packages/s/strongswan/monitoring.yml
packages/s/strongswan/package.yml
packages/s/strongswan/pspec_x86_64.xml

**Summary**
- [5.9.14](https://github.com/strongswan/strongswan/releases/tag/5.9.14)
- [5.9.13](https://github.com/strongswan/strongswan/releases/tag/5.9.13)
- [5.9.12](https://github.com/strongswan/strongswan/releases/tag/5.9.12)
**Security**
- CVE-2023-41913
**Test Plan**
- *TBD*
**Checklist**

strongswan: Update to 5.9.13

---

packages/w/wget/package.yml
packages/w/wget/pspec_x86_64.xml

**Summary**
- Fix how subdomain matches are checked for HSTS.
- Fixes a minor issue where cookies may be leaked to the wrong domain
- Wget will now also parse the srcset attribute in <source> HTML tags
- Support reading fetchmail style "user" and "passwd" fields from netrc
- In some cases, prevent the confusing "Cannot write to... (success)" error messages
- Support extremely fast download speeds (TB/s).
- Previously this would cause Wget to crash when printing the speed
- Improve portability on OpenBSD to run the test suite
- Ensure that CSS URLs are corectly quoted
**Test Plan**
- Installed and downloaded a file.
**Checklist**

wget: update to 1.24.5 

---

packages/w/wxmaxima/abi_used_symbols
packages/w/wxmaxima/package.yml
packages/w/wxmaxima/pspec_x86_64.xml

**Summary**
- Faster discarding of maths that is too long to read
- Resolved a crash on closing the last window
- Now only wxWidgets builds with Unicode support (default) are allowed.
- Full changelog can be found [here](https://github.com/wxMaxima-developers/wxmaxima/releases/tag/Version-24.05.0)
**Test Plan**
- Load example file
- Do some calculation
**Checklist**

wxmaxima: Update to 24.05.0

---

packages/f/font-noto-cjk/files/70-noto-cjk.conf
packages/f/font-noto-cjk/files/font-noto-cjk.metainfo.xml
packages/f/font-noto-cjk/package.yml
packages/f/font-noto-cjk/pspec_x86_64.xml

**Summary**
- Sync recipe with Archlinux
- Add appstream metainfo to font packages (Part of getsolus/packages#449)
**Test Plan**
- Verify metainfo with `appstream-builder --packages-dir=. --include-failed -v`
**Checklist**

font-noto-cjk: Update to 20230817

---

packages/a/a2ps/abi_used_symbols
packages/a/a2ps/package.yml
packages/a/a2ps/pspec_x86_64.xml

**Summary**
- Fix a2ps-lpr-wrapper to work with no arguments, as a2ps requires.
- Minor fixes & improvements to sheets.map for image types and PDF.
- Minor fixes and improvements.
**Test Plan**
**Checklist**

a2ps: update to 4.15.6

---

packages/i/ibus-m17n/abi_used_symbols
packages/i/ibus-m17n/package.yml
packages/i/ibus-m17n/pspec_x86_64.xml
packages/m/m17n-lib/abi_used_symbols
packages/m/m17n-lib/package.yml
packages/m/m17n-lib/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](http://git.savannah.nongnu.org/cgit/m17n/m17n-lib.git/tree/ChangeLog?h=REL-1-8-4).
**Test Plan**
- Rebuilt ibus-m17n against this.
**Checklist**

m17n-lib: update to 1.8.3

---

packages/m/m17n-db/files/0001-Add-support-for-zstd-compressed-charmaps.patch
packages/m/m17n-db/package.yml
packages/m/m17n-db/pspec_x86_64.xml

**Summary**
- configure.ac: Version changed to 1.8.5
- NEWS: Update for the 1.8.5 release
- MIM/new-newa-traditional-extended.mim: New input method
- icons/new-newa-traditional-extended.png: icon for new input method
- MIM/{en-pn-eqf,ml-pn-c}.mim: New input method for Malayalam
- icons/{en-pn-eqf,ml-pn-c}.png: icons for the new input method for Malayalam
**Test Plan**
- Checked it installed correctly.
**Checklist**

m17n-db: update to 1.8.5

---

packages/a/aisleriot/abi_used_symbols
packages/a/aisleriot/package.yml
packages/a/aisleriot/pspec_x86_64.xml

**Summary**
The PySol cardsets use a different style and thus don't really fit in with the rest.
Additionally this saves more than 100 MB in combined install size, if you only install `aisleriot`
Resolves https://github.com/getsolus/packages/issues/2516
**Test Plan**
Switched through the remaining card styles; played a round of Klondike
**Checklist**

aisleriot: Remove dependency on pysolfc(-cardsets)

---

packages/n/noto-sans-ttf/monitoring.yml
packages/n/noto-sans-ttf/package.yml
packages/n/noto-sans-ttf/pspec_x86_64.xml

**Summary**
Changes:
- Remove duplicated NotoSansPhags-Pa-Regular font
Full commit log available [here](https://github.com/notofonts/notofonts.github.io/compare/noto-monthly-release-24.4.1...noto-monthly-release-24.5.1)
**Test Plan**
- Confirmed my system font still looked okay
- Tested a number of Noto fonts in LibreOffice Writer
**Checklist**

noto-sans-ttf: Update to 24.5.1 and add monitoring.yml

---

packages/f/font-intel-one-mono-ttf/package.yml
packages/f/font-intel-one-mono-ttf/pspec_x86_64.xml

**Summary**
Add the intel-one-mono font, which is font intended for programmers
**Test Plan**
- Set font in terminal, your favorite text editor, or in all applications.
**Checklist**
Resolves https://github.com/getsolus/packages/issues/2580

font-intel-one-mono : Add at v1.3.0

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
- Improve `run list` doc with available `--json` fields
- Fix typos
- Move config interfaces into gh package
- Creating doc to capture Codespace usage guidance
- Fix repo fork regression
- Add `--latest=false` to `gh release create` docs
**Test Plan**
Run `gh status`, `gh pr list`, and create this pull request.
**Checklist**

github-cli: Update to 2.49.2

---

packages/f/fltk/abi_used_symbols
packages/f/fltk/monitoring.yml
packages/f/fltk/package.yml
packages/f/fltk/pspec_x86_64.xml

**Summary**
- Update bundled libraries to current versions (README.bundled-libs.txt).
- Introduce bundled image library "prefixing" to avoid conflicts with system libraries.
Full release notes [here](https://www.fltk.org/articles.php?L1898) and [here](https://github.com/fltk/fltk/blob/a66273e72621887fcbd0ee5dca2dd133356d5d8a/CHANGES)
**Test Plan**
- Rev deps work still (octave, tigervnc, carla)
**Checklist**

fltk: Update to 1.3.9

---

packages/e/eza/package.yml
packages/e/eza/pspec_x86_64.xml

**Summary**
- Replace decay with color-scale
- Add how to find man pages in terminal and online
**Test Plan**
Run `eza`, `eza -l`, and `eza -la`.
**Checklist**

eza: Update to 0.18.16

---

packages/l/libreoffice/abi_used_symbols
packages/l/libreoffice/files/0001-Use-the-Elementary-icons-by-default.patch
packages/l/libreoffice/package.yml
packages/l/libreoffice/pspec_x86_64.xml

**Summary**
- Use the Elementary icon theme by default
Fixes https://github.com/getsolus/packages/issues/311
**Test Plan**
Open Writer and switch the GTK theme on Budgie between different light and dark themes.
**Checklist**

libreoffice: Use the Elementary icon theme by default

---

packages/g/glib2/files/0001-gmenuexporter-Fix-a-NULL-pointer-dereference.patch
packages/g/glib2/files/series
packages/g/glib2/package.yml
packages/g/glib2/pspec_x86_64.xml

**Summary**
- Backport patch for a NULL dereference in gmenuexporter
Fixes https://github.com/getsolus/packages/issues/2532
**Test Plan**
Install this and `vala-panel-appmenu-budgie-desktop` and successfully open Inkscape.
**Checklist**

glib2: Backport patch for gmenuexporter

---

packages/m/minikube/abi_used_symbols
packages/m/minikube/monitoring.yml
packages/m/minikube/package.yml
packages/m/minikube/pspec_x86_64.xml

**Summary**
Simplified build (removed GOPATH)
Changed to tarball sources.
Added homepage
- Resolves #2598
Release notes can be found [here](https://github.com/kubernetes/minikube/blob/v1.33.1/CHANGELOG.md).
**Test Plan**
Run few minikube commands:
- `minikube start`
- list pods using kubectl: `kubectl get pods --all-namespaces`
- `minikube dashboard`
- `minikube stop`
- `minikube delete`
**Checklist**

minikube: Update to 1.33.1

---

packages/z/zim-tools/abi_used_symbols
packages/z/zim-tools/package.yml
packages/z/zim-tools/pspec_x86_64.xml

**Summary**
- zimsplit: stop creating trailing empty chunk
- zimdump: Respecting the --ns option in zimdump show
- Introduce max libzim version check in compilation
**Test Plan**
- zimwriterfs -j -J 12 -w index.html -I logo.png -l ukr -n "${desc}" -t "${desc}" -d "${desc}" -L "${desc}" -c "${desc}" -p "${desc}" ./texts ./texts.zim
**Checklist**

zim-tools: Update to 3.4.1

---

packages/p/pangox-compat/abi_used_symbols
packages/p/pangox-compat/monitoring.yml
packages/p/pangox-compat/package.yml
packages/p/pangox-compat/pspec_x86_64.xml

**Summary**
- Added `monitoring.yml` file with `Anitya ID` (no other key found)
**Test Plan**
Built, used it to build only reverse depency `gtkglext`, used it with
package `celestia` without notable issue.
**Checklist**

pangox-compat: Add homepage & monitoring.yml

---

packages/f/freeimage/package.yml
packages/f/freeimage/pspec_x86_64.xml

**Summary**
Without this `ypkg` option the resulting symlinks get mangled
Issue found by @cmarincia:matrix.org during `freecad` build
tree view before:
```
/home/build/YPKG/root/freeimage/install
└── usr
├── include
│   ├── FreeImage.h
│   └── FreeImagePlus.h
└── lib
├── libfreeimage-3.18.0.so
├── libfreeimage.a
├── libfreeimageplus-3.18.0.so
├── libfreeimageplus.a
├── libfreeimageplus.so
├── libfreeimageplus.so.3
├── libfreeimage.so
└── libfreeimage.so.3 -> libfreeimage-3.18.0.so
```
tree view after:
```
/home/build/YPKG/root/freeimage/install
└── usr
├── include
│   ├── FreeImage.h
│   └── FreeImagePlus.h
└── lib64
├── libfreeimage-3.18.0.so
├── libfreeimage.a
├── libfreeimageplus-3.18.0.so
├── libfreeimageplus.a
├── libfreeimageplus.so -> libfreeimageplus-3.18.0.so
├── …
```

freeimage: Build with fatfakeroot to fix symlinks

---

packages/n/nethogs/abi_used_symbols
packages/n/nethogs/monitoring.yml
packages/n/nethogs/package.yml
packages/n/nethogs/pspec_x86_64.xml

**Summary**
- Full release note can be found [here](https://github.com/raboof/nethogs/releases/tag/v0.8.7)
**Test Plan**
Run `sudo nethogs -a enp2s0`
**Checklist**

nethogs: Update to 0.8.7

---

packages/b/bash/abi_used_symbols
packages/b/bash/package.yml
packages/b/bash/pspec_x86_64.xml

**Package Size**
- Before: 9.68 MB | Now: 9.82 MB
**Benchmarks**
1. Startup speed
```
for i in $(seq 1 1000); do bash -c ":" ; done
```
Before: 1.409 s | Now: 1.366 s
2. [Shellbench](https://github.com/shellspec/shellbench/tree/master)
```
Before  Now
assign.sh: positional params      316,022 507,648
assign.sh: variable               451,756 725,583
assign.sh: local var              446,787 701,773
assign.sh: local var (typeset)    439,330 702,822
cmp.sh: [ ]                       250,852 395,695
cmp.sh: [[ ]]                     338,354 554,369
cmp.sh: case                      436,122 711,621
count.sh: posix                   332,163 527,900
count.sh: typeset -i              316,652 496,712
count.sh: increment               407,441 661,571
eval.sh: direct assign            226,263 …
```

bash: Build with PGO, don't build with Os

---

Taskfile.yml

**Summary**
To give people a chance to see exactly which .eopkgs would be deleted in the tree if they run `go-task clean-all`, the clean-all task is now composed of two subtasks (list-all-eopkgs and delete-all-eopkgs), with the latter being gated behind a prompt for safety to help avoid losing potentially many hours of work due to being too quick on the trigger.
Output:
$ go-task clean-all
task: [list-all-eopkgs] find $(git rev-parse --show-toplevel) -type f -name '*.eopkg' -print
(... list of all .eopkgs found in the repo ...)
This will delete ALL .eopkgs found in the monorepo. Do you wish to continue? [y/N]
y
task: [delete-all-eopkgs] find $(git rev-parse --show-toplevel) -type f -name '*.eopkg' -delete
**Summary**
**Test Plan**
**Checklist**

Taskfile: List *.eopkg files in tree before removal

---

packages/l/libfprint/abi_used_symbols
packages/l/libfprint/monitoring.yml
packages/l/libfprint/package.yml
packages/l/libfprint/pspec_x86_64.xml

**Summary**
[Changelog 1.94.7](https://gitlab.freedesktop.org/libfprint/libfprint/-/releases/v1.94.7)
[Changelog 1.94.6](https://gitlab.freedesktop.org/libfprint/libfprint/-/releases/v1.94.6)
[Changelog 1.94.5](https://gitlab.freedesktop.org/libfprint/libfprint/-/releases/v1.94.5)
[Changelog 1.94.4](https://gitlab.freedesktop.org/libfprint/libfprint/-/releases/v1.94.4)
**Test Plan**
fprintd-enroll
**Checklist**

libfprint: Update to 1.94.7

---

packages/l/libfprint/monitoring.yml

**Summary**
Fix wrong rss url in monitoring.yml

libfprint: Fix wrong rss url in monitoring.yml

---

packages/a/amfora/monitoring.yml
packages/a/amfora/package.yml
packages/a/amfora/pspec_x86_64.xml

**Summary**
Release notes available [here](https://github.com/makew0rld/amfora/releases/tag/v1.10.0)
Note: This will likely be the final release. See release notes for more info.
**Test Plan**
Openend a couple of Gemini pages
**Checklist**

amfora: Update to 1.10.0 and add monitoring.yml

---

packages/s/syncthing/package.yml
packages/s/syncthing/pspec_x86_64.xml

**Summary**
Bugfixes:
- lib/nat: panic: runtime error: index out of range
**Test Plan**
- Restart Syncthing-GTK and verify it can connect to the syncthing backend, all folders sync
**Checklist**

syncthing: update to 1.27.7

---

packages/p/pavucontrol/abi_used_symbols
packages/p/pavucontrol/monitoring.yml
packages/p/pavucontrol/package.yml
packages/p/pavucontrol/pspec_x86_64.xml

**Summary**
- Added `monitoring.yml` file (no CPE found)
**Test Plan**
Built, installed, used software
**Checklist**

pavucontrol: Add homepage & monitoring.yml

---

packages/b/blender/abi_used_symbols
packages/b/blender/package.yml
packages/b/blender/pspec_x86_64.xml

**Summary**
- Add CUDA as a source to avoid redistributing CUDA in a separate package.
- Add OptiX headers as a source to avoid redistributing in a separate package.
**Test Plan**
- Run classroom with CUDA cycles renderer enabled. Verify the GPU is being used.
- Run classroom with OptiX cycles renderer enabled. Verify the GPU is being used.
**Checklist**

blender: Enable CUDA and OptiX support

---

packages/p/pcsc-lite/abi_used_symbols
packages/p/pcsc-lite/monitoring.yml
packages/p/pcsc-lite/package.yml
packages/p/pcsc-lite/pspec_x86_64.xml

**Summary**
- Added `monitoring.yml` file (no CPE name found)
**Test Plan**
Built, installed
**Checklist**

pcsc-lite: Add homepage & monitoring.yml

---

packages/p/pciutils/abi_used_symbols
packages/p/pciutils/abi_used_symbols32
packages/p/pciutils/monitoring.yml
packages/p/pciutils/package.yml
packages/p/pciutils/pspec_x86_64.xml

**Summary**
- Added `monitoring.yml` file (no CPE name found)
**Test Plan**
Built, installed, used `lspci` command line utility
**Checklist**

pciutils: Add homepage & monitoring.yml

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Remove top-left serifs of z-parts of phonetic digraphs involving d
- Fix stroke width of hook part of LATIN CAPITAL LETTER ENG under heavy weight
- Add new characters
- [changelog](https://github.com/be5invis/Iosevka/blob/v30.0.1/CHANGELOG.md)
**Test Plan**
**Checklist**

font-iosevka-ttf: Update to 30.0.1

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- Fixed: Restored UDP connectivity through Mullvad exit nodes.
- Changed: Stateful filtering is now off by default
- [changelog](https://tailscale.com/changelog/#2024-05-20-client)
**Test Plan**
**Checklist**

tailscale: Update to 1.66.4

---

packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- Improved hillshading rendering.
- Use the map DEM data for hillshading on IMG maps.
- Added support for TCX course points icons.
- Various DEM related fixes.
**Test Plan**
**Checklist**

gpxsee: Update to 13.20

---

packages/m/mate-user-admin/abi_used_symbols
packages/m/mate-user-admin/files/nuconfig
packages/m/mate-user-admin/monitoring.yml
packages/m/mate-user-admin/package.yml
packages/m/mate-user-admin/pspec_x86_64.xml

**Summary**
The project has changed their config structure to differentiate between admin users and regular users.
See [this commit](https://github.com/zhuyaliang/user-admin/commit/7011404a23ea3d54b43d1b3a9e8ae24501a0b205)
Additionally some of the user groups were no longer up-to-date with our `accountsservice` config.
Simply remove the `mate-user-admin`-specific config, so it grabs the defaults from `accountsservice`. This way we don't have to update this file when changes to our defaults happen.
**Test Plan**
- Created new admin and standard users and observed that there were no more error messages
- Confirmed users were in the correct groups
**Checklist**

mate-user-admin: Update config and add monitoring.yml

---

packages/l/libslirp/abi_used_symbols
packages/l/libslirp/monitoring.yml
packages/l/libslirp/package.yml
packages/l/libslirp/pspec_x86_64.xml

**Summary**
Added homepage
Release notes can be found [here](https://gitlab.freedesktop.org/slirp/libslirp/-/blob/v4.8.0/CHANGELOG.md).
**Test Plan**
Rebuilt one of reverse-dependencies (e.g. qemu)
**Checklist**

libslirp: Update to 4.8.0

---

packages/s/snapd/abi_used_symbols
packages/s/snapd/package.yml
packages/s/snapd/pspec_x86_64.xml

**Summary**
New in snapd 2.63:
* Support for snap services to show the current status of user services (experimental)
* Refresh app awareness: record snap-run-inhibit notice when starting app from snap that is busy with refresh (experimental)
* Refresh app awareness: use warnings as fallback for desktop notifications (experimental)
* Aspect based configuration: make request fields in the aspect-bundle's rules optional (experimental)
* Aspect based configuration: make map keys conform to the same format as path sub-keys (experimental)
* Aspect based configuration: make unset and set behaviour similar to configuration options (experimental)
* Aspect based configuration: limit nesting level for setting value (experimental)
* Components: use symlinks to point active snap component revisions
* …

snapd: update to 2.63

---

packages/o/openfortivpn/abi_used_symbols
packages/o/openfortivpn/package.yml
packages/o/openfortivpn/pspec_x86_64.xml

**Summary**
* [~] do not print TLS socket options in log (revert change from 1.16.0)
* [+] add option to specify SNI
* [~] change most occurrences of "SSL" to "TLS" in user-visible text
**Test Plan**
**Checklist**

openfortivpn: update to 1.22.0

---

packages/g/google-cloud-sdk/package.yml

**Summary**
Added gke-gcloud-auth-plugin
Release notes can be found [here](https://cloud.google.com/sdk/docs/release-notes#47700_2024-05-21).
**Test Plan**
Run few gcs commands and check that they work:
- `gsutil cp gs://cloud-sdk-release/for_packagers/linux/google-cloud-cli_477.0.0.orig_amd64.tar.gz .`
- `gcloud auth login`
- `gcloud config set project <PROJECT_ID>`
**Checklist**

google-cloud-sdk: Update to 477.0.0

---

packages/c/cf-cli/package.yml
packages/c/cf-cli/pspec_x86_64.xml

**Summary**
- Full changelog [here](https://github.com/cloudfoundry/cli/compare/v6.51.0...v8.7.10)
- Add homepage key
Resolves #2566
**Test Plan**
Run some simple commands such as `cf --help` and `cf -v`.
Need help for more tests by someone who uses this package.
**Checklist**

cf-cli: Update to 8.7.10

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
- Refactor git credential flow code
- Add json output for `gh pr checks`
- List the various alias permutations for the command and subcommands
- Removed tty message when checking for extension upgrades
- Fix doc bug for `gh run watch`
- Add support for `stateReason` in `gh pr view`
- Rename the `Attempts` field to `Attempt`; expose in `gh run view` and `gh run ls`
- Update regex in `changedFilesNames` to handle quoted paths
- Add a `gh variable get FOO` command
**Test Plan**
**Checklist**

github-cli: Update to 2.50.0

---

packages/g/grub2/files/0001-Allow-Solus-to-remain-named-Solus.patch
packages/g/grub2/files/0002-Enable-os-prober-by-default.patch
packages/g/grub2/files/series
packages/g/grub2/package.yml
packages/g/grub2/pspec_x86_64.xml

**Summary**
Enable os-prober by default to restore the behaviour from Grub 2.0.4.
Resolves #2797
**Test Plan**
Install on dual boot system and run `clr-boot-manager update`.
**Checklist**

grub2: Enable os-prober by default

---

packages/c/caddy/monitoring.yml
packages/c/caddy/package.yml
packages/c/caddy/pspec_x86_64.xml

**Summary**
Release notes available [here](https://github.com/caddyserver/caddy/releases/tag/v2.8.0).
**Test Plan**
Start a Caddy server, send HTTP requests, and see that they were received
**Checklist**

caddy: Update to 2.8.1

---

packages/l/libexttextcat/monitoring.yml
packages/l/libexttextcat/package.yml
packages/l/libexttextcat/pspec_x86_64.xml

**Summary**
- No upstream changelog
**Test Plan**
TBD
**Checklist**

libexttextcat: Update to 3.4.6

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
- Fix Te bar terminal for Cyrillic TeTse and Tche under sans italic/oblique when T is serifed
- Make presence of non-Te serifs of Cyrillic TeTse automatic.
- Fix mark placement of Sideways U with Diaeresis when a CV/SS is applied to it
- Fix broken Cyrillic Ef
- Reduce fully-serifed variants of turned m and Cyrillic Italic Lower Sha, Scha under monospace
- [changelog](https://raw.githubusercontent.com/be5invis/Iosevka/v30.1.2/CHANGELOG.md)
**Test Plan**
**Checklist**

font-iosevka-ttf: Update to 30.1.2

---

packages/g/gpxsee/abi_used_symbols
packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- Added hillshading settings
- Fixed render issues with Qt 6.7
- Fixed issues with dates not respecting the system format
**Test Plan**
- open map file, zoom in and out
**Checklist**

gpxsee: Update to 13.21

---

packages/k/kitty/package.yml
packages/k/kitty/pspec_x86_64.xml

**Summary**
- Fix tab bar to not render in second and subsequent wayland windows
- Fix horizontal scrolling via touchpad in fullscreen applications to be reversed
- Fix an error when setting background_opacity to zero
- Fix cursor movement for image placements that specify only rows or columns
**Test Plan**
- kitty -v
**Checklist**

kitty: Update to 0.35.1

---

packages/s/sc-im/abi_used_symbols
packages/s/sc-im/package.yml
packages/s/sc-im/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/andmarti1424/sc-im/releases/tag/v0.8.3).
**Test Plan**
- Installed and edited a spreadsheet.
**Checklist**

sc-im: update to 0.8.3

---

packages/w/wine/abi_symbols
packages/w/wine/abi_symbols32
packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
- Bundled vkd3d upgraded to version 1.12
- DPI Awareness support improvements
- C++ RTTI support on ARM platforms
- More obsolete features removed in WineD3D
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.10)
**Test Plan**
- Ran `winefile`, `winemine`, `winecfg`, `wineconsole`
**Checklist**

wine: Update to 9.10

---

packages/s/sdl1/abi_symbols
packages/s/sdl1/abi_symbols32
packages/s/sdl1/abi_used_libs
packages/s/sdl1/abi_used_symbols
packages/s/sdl1/abi_used_symbols32
packages/s/sdl1/package.yml
packages/s/sdl1/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

sdl1: include homepage

---

packages/q/qutebrowser/package.yml
packages/q/qutebrowser/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/qutebrowser/qutebrowser/blob/main/doc/changelog.asciidoc).
**Test Plan**
- Installed and surfed the web.
**Checklist**

qutebrowser: update to 3.2.0

---

packages/py/python-orjson/abi_used_symbols
packages/py/python-orjson/package.yml
packages/py/python-orjson/pspec_x86_64.xml

**Summary**
Changes:
- `manylinux` amd64 builds include runtime-detected AVX-512 `str` implementation
- Tests now compatible with numpy v2
**Test Plan**
- Ran the examples from the project README
**Checklist**

python-orjson: Update to 3.10.3

---

packages/c/caddy/package.yml
packages/c/caddy/pspec_x86_64.xml

**Summary**
- caddyhttp: properly sanitize requests for root path
- caddytls: Implement `certmagic.RenewalInfoGetter`
- cmd: fix auto-detetction of .caddyfile extension
- cmd: fix regression in auto-detect of Caddyfile
**Test Plan**
Start a webserver with Caddy, use curl to make requests to the server endpoints
**Checklist**

caddy: Update to 2.8.4

---

packages/g/glibc/package.yml
packages/g/glibc/pspec_x86_64.xml

**Summary**
Recently package builds have started showing ld linker issues of the form `undefined reference to __pthread_timedjoin_np64` and similar. Examples of affected packages: `open-vm-tools`, `transmission`, `fastfetch`
The workaround was switching the build to clang tooling, but the actual cause seems to be this `glibc` commit: https://sourceware.org/git/?p=glibc.git;a=commit;h=dd535f4f19ef2b5c367a362af445ecadcf45401e
This patch changes our `glibc` build from the latest commit to the one right before the affected one, fixing the other package builds.
**Test Plan**
Built `fastfetch` and `transmission` against this version
**Checklist**

glibc: Revert to fix ld linker issues

---

packages/a/antlr4-cpp-runtime/package.yml
packages/a/antlr4-cpp-runtime/pspec_x86_64.xml

**Summary**
The build previously downloaded its own copy of googletest and installed its pkgconfigs/includes. This removes the fetching part, so it uses the system `gtest` instead, thus also no longer requiring networking.
**Test Plan**
Confirmed gtest/gmock files are no longer installed.
**Checklist**

antlr4-cpp-runtime: Remove additional gtest pkconfigs/includes

---

packages/w/weechat/abi_symbols
packages/w/weechat/package.yml
packages/w/weechat/pspec_x86_64.xml

**Summary**
- relay: enable websocket extension "permessage-deflate" with "api" relay only
- relay: add option `relay.look.raw_messages_max_length`
- irc, xfer: fix display of input prompt in IRC private buffers and DCC chat buffers
- irc: don't return pointer to irc server if the channel or nick is not found in info "irc_buffer"
- relay: fix websocket permessage-deflate extension when the client doesn't send the max window bits parameters
- relay: fix allocation and reinit of field "client_context_takeover" in websocket deflate structure
**Test Plan**
Connect to Libera, join a channel, send and receive messages.
**Checklist**

weechat: Update to 4.3.2

---

packages/py/python-maturin/abi_used_symbols
packages/py/python-maturin/package.yml
packages/py/python-maturin/pspec_x86_64.xml

**Summary**
Release notes available [here](https://github.com/PyO3/maturin/releases/tag/v1.6.0)
**Test Plan**
Built `python-orjson` with this version
**Checklist**

python-maturin: Update to 1.6.0

---

packages/j/just/abi_used_symbols
packages/j/just/package.yml
packages/j/just/pspec_x86_64.xml

**Summary**
- Add --no-aliases to hide aliases in --list
- Add -E as alias for --dotenv-path
Full release notes
[here](https://github.com/casey/just/releases/tag/1.26.0)
**Test plan**
- Run just, see changelog
**Checklist**

just: Update to 1.26.0

---

packages/b/blueprint-compiler/monitoring.yml
packages/b/blueprint-compiler/package.yml
packages/b/blueprint-compiler/pspec_x86_64.xml

**Summary**
Release notes available [here](https://gitlab.gnome.org/jwestman/blueprint-compiler/-/releases/v0.12.0)
**Test Plan**
Built `gradience` using this version
**Checklist**

blueprint-compiler: Update to 0.12.0 and add monitoring.yml

---

packages/m/miniupnpc/abi_symbols
packages/m/miniupnpc/abi_used_symbols
packages/m/miniupnpc/monitoring.yml
packages/m/miniupnpc/package.yml
packages/m/miniupnpc/pspec_x86_64.xml

**Summary**
Changelog available [here](https://raw.githubusercontent.com/miniupnp/miniupnp/miniupnpc_2_2_7/miniupnpc/Changelog.txt)
**Test Plan**
Rebuilt and used transmission and dolphin-emu with this version
**Checklist**

miniupnpc: Update to 2.2.7 and add monitoring.yml

---

packages/s/skaffold/package.yml
packages/s/skaffold/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/GoogleContainerTools/skaffold/releases).
**Test Plan**
- Ran some commands.
**Checklist**

skaffold: update to 2.12.0

---

packages/s/setbfree/abi_used_symbols
packages/s/setbfree/package.yml
packages/s/setbfree/pspec_x86_64.xml

**Summary**
* Fix upper manual key-split
* Fix MIDNAM (pedal CC, PC)
* Add UI scaling for leslie plugin
* Add compatibility with zita-convolver v4
* Minor build-system tweaks
**Test Plan**
**Checklist**

setbfree: update to 0.8.12

---

packages/s/semantik/abi_symbols
packages/s/semantik/package.yml
packages/s/semantik/pspec_x86_64.xml

**Summary**
* Fix a Sonnet-related crash
* Cosmetic changes
* Update the build file so that generated LaTeX documents are easier to work with
**Test Plan**
- Installed and created a mindmap.
**Checklist**

semantik: update to 1.2.11

---

packages/k/keepass/package.yml
packages/k/keepass/pspec_x86_64.xml

**Summary**
Release notes available [here](https://keepass.info/news/n240601_2.57.html)
**Test Plan**
- Open my password database
- Edited and saved a password
- Used auto-type to enter a password into browser window
**Checklist**

keepass: Update to 2.57

---

packages/p/protontricks/package.yml
packages/p/protontricks/pspec_x86_64.xml

**Summary**
Changes:
- Ignore empty compatibilitytool.vdf
- Fix crash w/ GUI if Proton install is incomplete
- CLI Launch: Shlex executable path
- Fix tests for new pytest
- Refactor subprocess mocking in tests
- Check for successful steam-runtime-launcher launch
- Tolerate compatibilitytool.vdf parsing issues
**Test Plan**
Used `protontricks --gui` to configure a game's Proton environment
**Checklist**

protontricks: Update to 1.11.1

---

packages/l/libvips/abi_used_symbols
packages/l/libvips/monitoring.yml
packages/l/libvips/package.yml
packages/l/libvips/pspec_x86_64.xml

**Summary**
Changes:
- fix deflate compression of tiff pyramids
- thumbnail always writes 8-bit thumbnails
- lower min scale factor to 0.0 in svgload and pdfload
- heifload: don't warn on images with nclx profiles
- ppmload: ensure multi-line comments are skipped
- fix arrayjoin with some pipelines
- fix high Q mono JPEG TIFF write with mozjpeg
- check linker for target_clones support
**Test Plan**
Changed a view image properties with `vips`
**Checklist**

libvips: Update to 8.15.2 and add monitoring.yml

---

packages/t/transmission/abi_used_libs
packages/t/transmission/abi_used_symbols
packages/t/transmission/package.yml
packages/t/transmission/pspec_x86_64.xml

**Summary**
Release notes available [here](https://github.com/transmission/transmission/releases/tag/4.0.6)
**Packager's notes:** Not using gtkmm-4.0 yet as it caused the tray icon to disappear
Depends on https://github.com/getsolus/packages/pull/2840
**Test Plan**
- Checked my active torrents
- Added and removed a torrent 
**Checklist**

transmission: Update to 4.0.6

---

packages/t/tailscale/package.yml
packages/t/tailscale/pspec_x86_64.xml

**Summary**
- [changelog](https://tailscale.com/changelog#2024-06-12)
**Test Plan**
**Checklist**

tailscale: Update to 1.68.0

---

packages/a/anki/package.yml
packages/a/anki/pspec_x86_64.xml

**Summary**
Changes:
- Fix image occlusion errors in previewer and card template editor
**Test Plan**
Played through a few cards of a Japanese deck, with audio and images
**Checklist**

anki: Update to 24.06.2

---

packages/g/gaupol/package.yml
packages/g/gaupol/pspec_x86_64.xml

**Summary**
Changes:
- Don't merge font tags with different values
- Drop dependency on chardet
- Add dependency on charset-normalizer
- Raise Python dependency to >= 3.5
**Test Plan**
Edited some subtitles for the film The Fifth Element
**Checklist**

gaupol: Update to 1.15

---

packages/c/calamares/abi_used_symbols
packages/c/calamares/files/patches/downstream/0001-bootloader-Fix-clr-boot-manager-cmdline-parameters.patch
packages/c/calamares/files/series
packages/c/calamares/package.yml
packages/c/calamares/pspec_x86_64.xml

**Summary**
Add a patch to only write add hibernation parameters to the kernel cmdline, instead of various settings already managed by clr-boot-manager.
Resolves #2813.
**Test Plan**
Generate an ISO that includes the patched Calamares and install with the following parameters:
- desktop=budgie
- firmware=uefi 
- swap=swap_hibernate 
- fs=ext4 
- lvm=False
- luks=True
**Checklist**

calamares: Fix generation of kernel parameters

---

packages/a/arc-gtk-theme/package.yml
packages/a/arc-gtk-theme/pspec_x86_64.xml

**Summary**
- Many fixes and updates for newer desktop environement versions
This theme hasn't had a tagged release in a couple of years, but is still actively worked on; thus I chose to use the latest commit instead of the last tagged release for support for newer desktops like GNOME 45, etc.
**Test Plan**
Switched to the themes on Budgie and see that the stylesheets load.
**Checklist**

arc-gtk-theme: Sync with git

---

packages/g/github-cli/package.yml
packages/g/github-cli/pspec_x86_64.xml

**Summary**
- Add `signer-repo` and `signer-workflow` flags to `gh attestation verify`
- Replace `--json-result` flag with `--format=json` in the attestation cmd
- Bump go-keyring to fix keepassxc prompt confirmation
- watch - handle annotation errors gracefully
**Test Plan**
Run `gh status`, `gh pr list` in the packages repository, and make this pull request.
**Checklist**

github-cli: Update to 2.51.0

---

packages/g/gdb/abi_used_libs
packages/g/gdb/abi_used_symbols
packages/g/gdb/package.yml
packages/g/gdb/pspec_x86_64.xml

**Summary**
Adds debuginfod support to gdb
**Test Plan**
Tested by using the in-testing debuginfod server to download symbols that were missing from a crash.
**Checklist**

packages: Enable debuginfod

---

packages/s/sdl2-ttf/package.yml
packages/s/sdl2-ttf/pspec_x86_64.xml

**Summary**
In addition to bug fixes, here are the major changes in this release:
- Updated to FreeType version 2.13.2 and HarfBuzz version 8.1.1
**Test Plan**
- Installed and started Solarus which is dependent on this.
**Checklist**

sdl2-ttf: update to 2.22.0

---

common/Scripts/check_appstream_progress.py

**Summary**
Adds a script to `common` which generates a report of packages shipping .desktop files, and how many of those are missing appstream metadata. The script can also scan a single pspec.xml. In this usage, it returns 0 if the package is correct (either ships no .desktop file or both a .desktop and appstream metadata), and returns 1 if the package ships only a .desktop file.
Fixes #2394
**Test Plan**
Test both use cases of the script. The full report is `./check_appstream_progress.py ../../packages` (assuming you are in `common/Scripts`. An example of (at this time) packages to test the single-package use case are `vlc` (correct) and `puddletag` (incorrect).
**Checklist**

common/Scripts: Add a tool to check appstream metainfo progress

---

packages/py/python-docutils/monitoring.yml
packages/py/python-docutils/package.yml
packages/py/python-docutils/pspec_x86_64.xml

**Summary**
Replace `python-recommonmark` builddeps with `python-myst-parser` as checkdeps. `python-recommonmark` has been deprecated in upstream, more details on getsolus/packages#2971
Unblocks getsolus/packages#2971
**Packager's Notes**
There is a little difference between `python-recommonmark` and `python-myst-parser` as checking tools, each one has different number of test ran. With `python-recommonmark`, there are 1727 tests but with `python-myst-parser`, there are only 1603 tests.

python-docutils: Replace python-recommonmark builddeps

---

Taskfile.yml

Add a new go-task command that nukes eopkgs from local repository and then rebuilds the local repository.

Taskfile.yml: Add clean-local command

---

packages/s/socat/abi_used_symbols
packages/s/socat/package.yml
packages/s/socat/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](http://www.dest-unreach.org/socat/CHANGES).
**Test Plan**
- Ran some commands.
**Checklist**

socat: update to 1.8.0.0

---

packages/l/libwebp/abi_symbols
packages/l/libwebp/abi_symbols32
packages/l/libwebp/abi_used_symbols
packages/l/libwebp/abi_used_symbols32
packages/l/libwebp/package.yml
packages/l/libwebp/pspec_x86_64.xml

**Summary**
Changes:
- API changes:
- libwebpmux: WebPAnimEncoderSetChunk, WebPAnimEncoderGetChunk, WebPAnimEncoderDeleteChunk
- libsharpyuv: SharpYuvOptionsInit, SharpYuvConvertWithOptions
- extras: SharpYuvEstimate420Risk
- further security related hardening in libwebp & examples
- some minor optimizations in the lossless encoder
- added WEBP_NODISCARD to report unused result warnings
- improvements and corrections in webp-container-spec.txt and webp-lossless-bitstream-spec.txt
- miscellaneous warning, bug & build fixes
**Test Plan**
Converted a bunch of images and gif animations to webp format and viewed them
**Checklist**

libwebp: Update to 1.4.0

---

packages/m/mbedtls/abi_symbols
packages/m/mbedtls/files/revert-unconditional-third-party.patch
packages/m/mbedtls/package.yml
packages/m/mbedtls/pspec_x86_64.xml

**Summary**
Release notes available [here](https://github.com/Mbed-TLS/mbedtls/releases/tag/v2.28.8)
Fixes CVE-2024-28960
**Test Plan**
Rebuilt and used `dolphin-emu` with this version
**Checklist**

mbedtls: Update to 2.28.2

---

packages/py/pyg3t/package.yml
packages/py/pyg3t/pspec_x86_64.xml

**Summary**
- No upstream changelog, [here](https://gitlab.com/pyg3t/pyg3t/-/compare/0.5.0...0.6.0?from_project_id=15129414&straight=false) is git history
**Test Plan**
TBD
**Checklist**

pyg3t: Update to 0.6.0

---

packages/py/pytest-subtests/monitoring.yml
packages/py/pytest-subtests/package.yml
packages/py/pytest-subtests/pspec_x86_64.xml

**Summary**
- Changelog can be found [here](https://github.com/pytest-dev/pytest-subtests/blob/v0.12.1/CHANGELOG.rst)
**Test Plan**
Rebuild python-cryptography against this package (Passed test suite)
**Checklist**
-  [x] Package was built and tested against unstable

pytest-subtests: Update to 0.12.1

---

packages/g/gpxsee/abi_used_symbols
packages/g/gpxsee/package.yml
packages/g/gpxsee/pspec_x86_64.xml

**Summary**
- Improved marine maps (ENC & IMG) rendering.
- Fixed multiple IMG DEM/hilshading issues.
- Added (zoomed) graph scrolling using the mouse.
**Test Plan**
- open map, zoom in and out
**Checklist**

gpxsee: Update to 13.22

---

Taskfile.yml

**Summary**
In addition, list files in long form in local repo before asking to clean it out, as it can be useful to be able to see sizes and dates before they get removed (to avoid losing hours of work).
**Test Plan**
- `go-task -l` (to ensure aliases show up) 
-  `go-task clean-all` (to clean my tree of .eopkgs)
- `go-task clean-local` (to clean my local repo)
**Checklist**

Taskfile: Improve ergonomics by adding aliases

---

Taskfile.yml

**Summary**
Now that we have a script to check which packages need to have appstream data added, it seems prudent to have a task to trigger it.
**Test Plan**
Run `go-task check-appstream-progress` and make sure a list of packages is printed.
**Checklist**

Taskfile.yml: Add a task which runs the appstream progress report

---

packages/py/python-betamax/monitoring.yml
packages/py/python-betamax/package.yml
packages/py/python-betamax/pspec_x86_64.xml

**Summary**
- Full changelog can be found [here](https://raw.githubusercontent.com/betamaxpy/betamax/0.9.0/HISTORY.rst)
**Test Plan**
TBD
**Checklist**

python-betamax: Update to 0.9.0

---

packages/s/svtplay-dl/package.yml
packages/s/svtplay-dl/pspec_x86_64.xml

**Summary**
- svtplay: fix a crash getting season / episode info
- svtplay: fix a special case not finding newly released news videos
- plutotv: fix getting movies
**Test Plan**
- Installed and downloaded a video.
**Checklist**

svtplay-dl: update to 4.83

---

packages/a/anki/files/anki.svg
packages/a/anki/files/net.ankiweb.Anki.appdata.xml
packages/a/anki/package.yml
packages/a/anki/pspec_x86_64.xml

**Summary**
- Add app icon
**Test Plan**
Install and run the app
**Checklist**

anki: Add appstream metainfo

---

packages/o/opentabletdriver/files/use-dotnet-8.patch
packages/o/opentabletdriver/package.yml
packages/o/opentabletdriver/pspec_x86_64.xml

**Summary**
Previously built binaries are corrupted. Attempting to build against newest .net to fix.
**Test Plan**
- use tablet
- ensure GUI works
- keymap using tablet button
**Checklist**

opentabletdriver: Rebuild against 8.0.6

---

packages/s/sshguard/abi_used_symbols
packages/s/sshguard/package.yml
packages/s/sshguard/pspec_x86_64.xml

**Summary**
- Add signature for BIND
- Add signature for Gitea
- Add signature for Microsoft SQL Server for Linux
- Add signature for OpenVPN Portshare
- Add signature for user-defined HTTP attacks
- Update signatures for Dovecot
- Update signatures for Postfix
- Fix memset off-by-one
- Resolve DNS names in capability mode using casper
**Test Plan**
- Checked it installed correctly.
**Checklist**
-  [X] Package was built and tested against unstable

sshguard: update to 2.3.4

---

packages/t/teckit/abi_used_symbols
packages/t/teckit/package.yml
packages/t/teckit/pspec_x86_64.xml

**Summary**
- Updated Unicode character names and normalization data to 15.0.0
- Updated zlib to version 1.2.13
- Updated documentation
**Test Plan**
- Checked texlive worked that is dependent on this.
**Checklist**

teckit: update to 2.5.12

---

packages/s/steam/package.yml
packages/s/steam/pspec_x86_64.xml

**Summary**
Split out the udev rules into `steam-udev-rules` so they can be installed separately.
Resolves #2805.
**Test Plan**
Install udev rules without Steam.
**Checklist**

steam: Split udev rules into a separate package

---

packages/t/tuxpaint-stamps/package.yml
packages/t/tuxpaint-stamps/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://sourceforge.net/p/tuxpaint/tuxpaint-stamps/ci/master/tree/docs/CHANGES.txt).
**Summary**
- Started Tux Paint and checked it loaded the stamps.
**Checklist**

tuxpaint-stamps: update to 2024.01.29

---

packages/f/font-inter-ttf/files/inter.metainfo.xml
packages/f/font-inter-ttf/package.yml
packages/f/font-inter-ttf/pspec_x86_64.xml

**Summary**
- Add `font-inter-ttf` at 4.0
- Resolves getsolus/packages#2980
**Test plan**
- Change GNOME's interface font via GNOME Tweaks
- Change Budgie's interface font via Budgie desktop settings
**Checklist**

font-inter-ttf: Initial inclusion at 4.0

---

packages/py/python2-ordered-set/package.yml
packages/py/python2-ordered-set/pspec_x86_64.xml

**Summary**
This is an old version of the PyPI ordered-set which works with python2. It is required to enable a deterministic install order for some packages in eopkg py2.
**Test Plan**
1. Build package from this PR.
2. Install it.
3. Run a `python` REPL.
4. Type `import ordered_set` and see that the module is available, even in python2.
**Checklist**

python2-ordered-set: Add at 3.1.1

---

packages/b/blueman/package.yml
packages/b/blueman/pspec_x86_64.xml

**Summary**
Changes:
- Added an option to toggle the manager window with the tray icon
- Only a single battery notification
- Renamed recent connections header in applet menu
- Fixed: Broken audio profile applet menu items
- Fixed: Missing manager window title
- Fixed: Teardown of DBus mock server in tests
**Test Plan**
- Connected and disconnected my headphones
- Switched Bluetooth audio profiles
**Checklist**

blueman: Update to 2.4.2

---

Taskfile.yml

**Summary**
Make `go-task -l` output easier to read.
Tweak cmd syntax to be more uniform and only use multi-line syntax when necessary.
**Test Plan**
Run different go-task tasks successfully.
**Checklist**

Taskfile: Use more uniform syntax and tweak output

---

packages/q/qutebrowser/package.yml
packages/q/qutebrowser/pspec_x86_64.xml

**Summary**
- When the selected Qt wrapper is unavailable, qutebrowser now again shows a GUI error message instead of only an exception in the terminal.
**Test Plan**
- Surfed the web.
**Checklist**

 qutebrowser: update to 3.2.1 

---

packages/d/distrobox/MAINTAINERS.md
packages/d/distrobox/package.yml
packages/d/distrobox/pspec_x86_64.xml

**Summary**
Add the distrobox package, which allows users to create containers for other Linux distros.
**Test Plan**
Create a box and run software not available in the Solus repos.
**Checklist**
Resolves https://github.com/getsolus/packages/issues/2811
Users might need to create subuid and subgid files.

distrobox: Add at v1.7.2.1

---

packages/b/budgie-desktop-branding/package.yml
packages/b/budgie-desktop-branding/pspec_x86_64.xml
packages/x/xfce4-desktop-branding/package.yml
packages/x/xfce4-desktop-branding/pspec_x86_64.xml

**Summary**
- **xfce4-desktop-branding: Sync with git**
- **budgie-desktop-branding: Sync with git**
Fixes https://github.com/getsolus/xfce4-desktop-branding/issues/9
**Test Plan**
Update the packages and see that the mimeapps.list files changed.
**Checklist**

update desktop brandings for xapps

---

packages/w/wireplumber/files/fix-linking.patch
packages/w/wireplumber/package.yml
packages/w/wireplumber/pspec_x86_64.xml

…devices
**Summary**
Version 0.5.4 introduced an issue causing `wireplumber` to crash during certain Bluetooth device operations, for example profile switching.
This backports the patches to the linking system that fix those crashes.
**Test Plan**
Switched audio profiles, launched games, played audio in browser, and confirmed `wireplumber` didn't crash
**Checklist**

wireplumber: Include patches to fix crashes in device linking system

---

packages/a/apparmor/files/0001-Update-paths-in-service-file.patch
packages/a/apparmor/package.yml
packages/a/apparmor/pspec_x86_64.xml

**Summary**
After the recent preparation work for the usr-merge script the apparmor service caused errors during boot due to the path `/lib/apparmor/apparmor.systemd` no longer existing. This patches the path in the service file to use the new lib64 path
Also switch to the launchpad tarball and use `%configure` again as mentioned in the TODO
**Test Plan**
Rebooted and confirmed there were no more AppArmor errors in journal and `dmesg`
**Checklist**

apparmor: Fix service path error and switch to launchpad tarball

---

packages/e/eopkg/package.yml
packages/e/eopkg/pspec_x86_64.xml

**Summary**
Error handling bugfixes in the PK eopkg backend
**Test Plan**
Successfully use KDE Discover to refresh the repo and install upgrades.
**Checklist**

eopkg: sync packagekit backend w/ git for eopkg.bin

---

packages/w/wine/abi_symbols
packages/w/wine/abi_symbols32
packages/w/wine/abi_used_symbols
packages/w/wine/abi_used_symbols32
packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
- Initial support for user32 data structures in shared memory
- Mono engine updated to version 9.2.0
- Rewrite of the CMD.EXE engine
- Fixed handling of async I/O status in new WoW64 mode
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.12)
**Test Plan**
- Used `winemine`, `winecfg`, `wineconsole`, `winefile`
**Checklist**

wine: Update to 9.12

---

packages/e/eopkg/package.yml
packages/e/eopkg/pspec_x86_64.xml
packages/p/pisi/files/baselayout-first-no-eopkg-reordering.patch
packages/p/pisi/pspec.xml

**Summary**
This should fix issues with eopkg being uninstallable because glibc was not installed first.
**Test Plan**
- VM testing
- Installed 4.5 ISO in VM
- Updated to newest stable (eopkg4 r7)
- Sideloaded pisi from this PR
- Switched to unstable using sideloaded pisi
- Upgraded to latest unstable using sideloaded pisi
- ISO testing
- Successfully built an Xfce smoketest ISO with the new pisi/eopkg versions installed and in my local repo
- chroot builds
- Successfully built multiple chroots with `eopkg.py3 it -c system.base -D <the outputdir>` and saw first baselayout then fairly close after (directly after or after iso-codes) saw glibc being installed, implying that the topological_sort order is now not being scrambled by set operations.
**Checklist**

eopkg/pisi: Order baselayout first, don't reorder eopkg

---

packages/x/xmlto/abi_used_symbols
packages/x/xmlto/package.yml
packages/x/xmlto/pspec_x86_64.xml

**Summary**
- Rename variable BASH to XMLTO_BASH_PATH
- Regenerate xmlif to use new version of gcc
- Rename and format markdown files
- Skip validating xmlto man page during build
**Test Plan**
**Checklist**
- Changed to reconfigure macro as no makefile was found.

xmlto: update to 0.0.29

---

common/Scripts/appstream_ignored_packages.txt
common/Scripts/check_appstream_progress.py

**Summary**
This PR gives the appstream progress checker the ability to ignore a list of packages, which is provided by common/Scripts/appstream_ignored_packages.txt. It also contains a starting point for that list of ignored packages.
**Test Plan**
1. Run `go-task check-appstream-progress` within the repo.
2. Make note of how many packages are reported as needing appstream data.
3. Check out this PR.
4. Run `go-task check-appstream-progress` again.
5. Note the abrupt decrease in packages reported as needing appstream data.

Add an ignore list to the appstream checker script

---

packages/py/python-wheel/package.yml
packages/py/python-wheel/pspec_x86_64.xml

**Summary**
- ruamel-yaml was the last pkg to require this
**Test Plan**
n/a
**Checklist**

python-wheel: Drop python 2 support

---

packages/b/broot/abi_used_symbols
packages/b/broot/package.yml
packages/b/broot/pspec_x86_64.xml

**Summary**
- :open_trash shows the content of the trash. Other new internals & verbs: :delete_trashed_file, :restore_trashed_file, :purge_trash
- it's now possible to remove a default keybinding by defining a verb with no execution
**Test Plan**
- Ran it and opened a file. 
**Checklist**
- Switched to new cargo macros.

broot: update to 1.39.0

---

packages/p/pisi/files/baselayout-first-no-eopkg-reordering.patch
packages/p/pisi/pspec.xml

**Summary**
The install order reordering code now puts baselayout first and doesn't attempt to reorder eopkg.
In addition, a cosmetic tweak was added which doesn't show the "reordering system.base packages" warning when `--ignore-safety` is specified.
**Test Plan**
Run `eopkg.py2 it --reinstall eopkg` with and without `--ignore-safety` flag and check that the warning output differs.
**Checklist**

pisi: Update to v3.12.2, tweak reordering code

---

packages/d/deepfilternet/abi_used_symbols
packages/d/deepfilternet/package.yml
packages/d/deepfilternet/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**
- Seemed to be only libraries so did not use %cargo_install

deepfilternet: use new cargo macros

---

packages/d/deluge/package.yml
packages/d/deluge/pspec_x86_64.xml

**Summary**
- Removed python-geoip as run dependency
- Part of https://github.com/getsolus/packages/issues/3027
**Test Plan**
- Installed downloaded a torrent and checked peers, installed python-geoip and saw no difference.
**Checklist**

deluge: remove unneeded dependency

---

packages/py/python-colour/files/drop-d2to1-requirement.patch
packages/py/python-colour/package.yml
packages/py/python-colour/pspec_x86_64.xml

**Summary**
- Drop python-d2to1 dependency
- Add homepage
- Resolves #2969
- Part of #2973
**Test Plan**
- Run `rapid-photo-downloader` and check some photos
**Checklist**

python-colour: Fix build and drop python-d2to1 dependency

---

packages/n/nemo-extensions/package.yml
packages/n/nemo-extensions/pspec_x86_64.xml
packages/py/python-pypdf/monitoring.yml
packages/py/python-pypdf/package.yml
packages/py/python-pypdf/pspec_x86_64.xml

**Summary**
- **python-pypdf: Add at 4.2.0**
- **nemo-extensions: Fix nemo-media-columns extension**
This adds an updated version of `python-pypdf2` that underwent a significant refactor. One of the Nemo extensions has updated to this version of PyPDF, but the other application in the repository that uses it, Kraft, is still on the old version. Luckily, they appear to be co-installable.
**Test Plan**
Add and enable the `nemo-media-columns` extension in Nemo.
**Checklist**

Add python-pypdf to fix nemo-media-columns

---

packages/f/font-iosevka-ttf/package.yml
packages/f/font-iosevka-ttf/pspec_x86_64.xml

**Summary**
* Add Capital Eszet (`VXAC`) variants with top-left corner.
* Add square-dotted variant for brailles
* Fix leaning mark anchors for `U+0195`, `U+019E`, `U+01A6`, and `U+0220`.
* Optimize glyph shape for `U+01A6`, `U+A68A`, and `U+A68B`.
* Make `ss20` use `seven`.`curly-serifless` by default.
* Adjust balancing of r with corner hooks
* Fix side bearings of Latin-1 Macron (`U+00AF`) under Quasi-Proportional.
* Make `U+050F`, `U+A68B`, `U+FB03`, and `U+FB04` slightly wider under Quasi-Proportional.
**Test Plan**
- render text
**Checklist**

font-iosevka-ttf: Update to 30.3.1

---

packages/py/python-txtorcon/package.yml
packages/py/python-txtorcon/pspec_x86_64.xml

**Summary**
* Fix test-failures on Python 3.12
* Particular GETINFO hanging (ultra-long lines over 16KiB caused problems in the protocol)
* Use built-in `mock` only
* Remove `incremental`
**Test Plan**
- Started magic-wormhole who is dependent on this and sent a file.
**Checklist**
- Removed python-geoip as run dependency
- Part of https://github.com/getsolus/packages/issues/3027

python-txtorcon: update to 23.11.0

---

packages/py/python-maturin/abi_used_symbols
packages/py/python-maturin/package.yml
packages/py/python-maturin/pspec_x86_64.xml

**Summary**
Changes:
- Expose env variable to suppress build backend warning
- Canonicalize base executable path in PEP 517 build
- Initial iOS support
- Remove old import hook
- Bump MSRV to 1.74.0
- Override wheel tag with `_PYTHON_HOST_PLATFORM`
- Don't add duplicate files
- pep517: only use base python when `MATURIN_PEP517_USE_BASE_PYTHON` env var is set
**Test Plan**
Built `python-orjson` against this version
**Checklist**

python-maturin: Update to 1.7.0

---

packages/t/tslib/abi_libs
packages/t/tslib/abi_symbols
packages/t/tslib/abi_used_symbols
packages/t/tslib/package.yml
packages/t/tslib/pspec_x86_64.xml

**Summary**
This release includes libts version 0.10.5 and the following changes:
- new filter module: module crop
- some build and security fixes
- improved release procedure
**Test Plan**
**Checklist**
- Dependency of qt6-base.

tslib: update to 1.23

---

packages/o/opentabletdriver/package.yml
packages/o/opentabletdriver/pspec_x86_64.xml

**Summary**
This update will enable the opentabletdriver.service by default.
**Test Plan**
- check service status is enabled and running
- check OpenTabletDriver opens and maps tablet keys
**Checklist**

opentabletdriver: Enable service by default

---

packages/w/wine/abi_libs
packages/w/wine/abi_libs32
packages/w/wine/abi_symbols
packages/w/wine/abi_symbols32
packages/w/wine/package.yml
packages/w/wine/pspec_x86_64.xml

**Summary**
This fixes issues with SSL connections in wine iexplore and other apps
**Test Plan**
Confirmed `wine iexplore google.com` actually loaded the page
**Checklist**

wine: Add gnutls dependency to enable SSL

---

packages/t/tree/abi_used_symbols
packages/t/tree/package.yml
packages/t/tree/pspec_x86_64.xml

**Summary**
- 2.1.3
- Fix regression in `search()` function that broke `--fromfile`
- Allow the `-L` option to accept its parameter immediately (with no space)
- 2.1.2
- Fix issue where `--gitignore` does not think a pattern with a singular terminal '/'
- Don't emit the error 'recursive, not followed' if when using `-L`, the depth would prevent descending anyway
- Don't prematurely sort files/directories with `--from*file`
**Test Plan**
- See that `tree` makes a tree
**Checklist**

tree: Update to 2.1.3

---

packages/s/snapd/files/wrapper.sh
packages/s/snapd/package.yml
packages/s/snapd/pspec_x86_64.xml

**Summary**
Add a warning when starting snap applications. The warning is shown on the CLI when invoking `snap` there, and as a notification when starting a GUI application.
**Test Plan**
Run a `snap` command on the CLI:
Run a GUI application:
**Checklist**

snapd: Add confinement warning

---

packages/u/unsnap/files/0001-Check-for-package-managers-not-distros.patch
packages/u/unsnap/files/0002-Add-color-to-output.patch
packages/u/unsnap/files/0003-Remove-mentions-of-supporting-specific-distros.patch
packages/u/unsnap/files/0004-Remove-snapd-when-there-are-no-missing-snaps.patch
packages/u/unsnap/files/0005-Add-gnome-42-2204-to-excluded-snaps.patch
packages/u/unsnap/files/0006-Load-lists-from-usr-share-unsnap.patch
packages/u/unsnap/files/0007-Fix-grep-errors-when-MISSINGFLATPAK-is-empty.patch
packages/u/unsnap/files/0008-Disable-systemd-units-on-snapd-removal.patch
packages/u/unsnap/files/0009-Log-to-var-log.patch
packages/u/unsnap/files/0010-Add-unwrapped-snap-to-PATH.patch
packages/u/unsnap/files/0011-Extend-usage-info-when-running-without-arguments.patch
packages/u/unsnap/files/series
packages/u/unsnap/package.yml
packages/u/unsnap/pspec_x86_64.xml

**Summary**
Initial inclusion of `unsnap` at the last upstream commit. It includes a patchset that adds support for `eopkg`.
Resolves #323
**Test Plan**
Run `sudo unsnap auto` to automatically migrate snaps to flatpak.
**Checklist**

unsnap: Add at 2023.03.11

---

packages/z/zim-tools/package.yml
packages/z/zim-tools/pspec_x86_64.xml

**Summary**
- zimwriterfs: Support short option `-a` (tags)
- zimwriterfs: "Name", "Title" and "LongDescription" are mandatory metadata
- zimcheck: Do not run check on content if zim integrity test is failing
- zimrecreate: Do not try to add twice metadata (and fix return code)
**Test Plan**
- zimcheck file.zim
**Checklist**

zim-tools: Update to 3.4.2

---

packages/r/rust-bindgen/abi_used_symbols
packages/r/rust-bindgen/package.yml
packages/r/rust-bindgen/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

rust-bindgen: use new cargo macros

---

packages/o/onefetch/abi_used_libs
packages/o/onefetch/abi_used_symbols
packages/o/onefetch/package.yml
packages/o/onefetch/pspec_x86_64.xml

**Summary**
**Test Plan**
**Checklist**

onefetch: use new cargo macros

---

packages/h/hplip/abi_used_symbols
packages/h/hplip/monitoring.yml
packages/h/hplip/package.yml
packages/h/hplip/pspec_x86_64.xml

After installing or updating this package, run `hp-plugin` on command line before attempting to add a printer, print or scan.
**Summary**
Added support for new printers:
HP OfficeJet 8120 All-in-One series
HP OfficeJet Pro 8120 All-in-One series
HP OfficeJet 8130 All-in-One series
HP OfficeJet Pro 8130 All-in-One series
HP OfficeJet Pro 9720 Series
HP OfficeJet Pro 9730 Series
Solus:
**Test Plan**
Verified
- plugin was installed successfully by `hp-plugin`
- previously installed HP Printer is still configurable in Print Settings
- hp-toolbox launches HP Device Manager successfully
- ability to remove and re-add printer / fax in hp-toolbox (Note: must first run hp-plugin)
- scanning works with Simple Scan
- printing works
**Checklist**

hplip: update to 3.24.4

---

packages/p/phinger-cursors/package.yml
packages/p/phinger-cursors/pspec_x86_64.xml

**Summary**
[Release notes](https://github.com/phisch/phinger-cursors/releases/tag/v2.1)
**Test Plan**
Set cursor theme on xfce 
**Checklist**

phinger-cursors: Update to 2.1

---

packages/t/typst/abi_used_symbols
packages/t/typst/package.yml
packages/t/typst/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/typst/typst/releases/tag/v0.11.1).
**Test Plan**
- Created a pdf.
**Checklist**

typst: update to 0.11.1

---

packages/c/conky/package.yml
packages/c/conky/pspec_x86_64.xml

**Summary**
- Release notes can be found [here](https://github.com/brndnmtthws/conky/releases/tag/v1.21.4).
**Test Plan**
- Checked it started.
**Checklist**

conky: update to 1.21.4

---

packages/h/htop/abi_used_symbols
packages/h/htop/files/htop.metainfo.xml
packages/h/htop/package.yml
packages/h/htop/pspec_x86_64.xml

**Summary**
- add metainfo
-  part of https://github.com/getsolus/packages/issues/1389

htop: add appstream metainfo

---

packages/n/neovide/package.yml
packages/n/neovide/pspec_x86_64.xml

**Summary**
Buxfix:
- Use predifined font weights only if user does not specify one
- [0.13.3](https://github.com/neovide/neovide/releases/tag/0.13.3)
**Test Plan**
- Edited and saved a file
**Checklist**

neovide: Update to 0.13.3
