getsolus/packages

- .github/ISSUE_TEMPLATE/bug.yaml
- .github/ISSUE_TEMPLATE/request-package-update.yaml
- README.md
Add templates for bugs, package requests and package update requests based on the templates on Phabricator.
> Add issue templates

- .github/pull_request_template.md
- .gitignore
Headers in the PR template were H3, changed to H2. Added vscode and temp files to gitignore.
Viewed tempalte file in preview mode
> Change PR template headers to H2. Add vscode and temp files to gitignore

- common/Taskfile.yml
Adds the following targets:
- create: Create a new package.yml using yauto.py
- pkgconfig: Search for packages providing pkgconfig names
- update: Update an existing package.yml using yupdate.py
Heavily inspired by work done by @HarveyDevel
Summon Harvey and make him fix it.
> Taskfile: Update to replace packaging docs aliases

- common/Scripts/buildserver-notification.sh
- common/Taskfile.yml
**Summary**
Some misc go-task fixes for monorepo, read commits for details.
Required by #359.
**Test Plan**
`go-task notify-complete`
`go-task publish`
**Checklist**
> common: Misc. go-task fixes for monorepo

- packages/p/papirus-icon-theme/package.yml
**Summary**
Release notes available [here](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/releases/tag/20230901)
**Test Plan**
Checked icons in application menu, file explorer, and SC
**Checklist**
> papirus-icon-theme: update to 20230901

- common/Scripts/rebuild-template-script.sh
**Summary**
Updates the rebuild script so it can work with the monorepo
Still a draft for now due to `package-publish-safety-catches.sh` needing to be disabled locally first.
**Test Plan**
Published KF5 stack upgrade with script.
**Checklist**
> common/Scripts: rework rebuild-template-script for monorepo

- packages/s/solaar/package.yml
- packages/s/solaar/pspec_x86_64.xml
**Summary**
Update solaar to new version v1.1.10
Changelog can be found [here](https://github.com/pwr-Solaar/Solaar/blob/1.1.10/ChangeLog.md)
**Test Plan**
- restart solaar
- unpair mouse from unifying receiver
- pair mouse to unifying receiver
- change mouse settings for scroll wheel
- change mouse dpi setting
- change mouse button mapping
**Checklist**
> solaar: Update to 1.1.10

- packages/w/wine/abi_used_symbols
- packages/w/wine/abi_used_symbols32
- packages/w/wine/package.yml
- packages/w/wine/pspec_x86_64.xml
**Summary**
- Bundled vkd3d upgraded to version 1.9
- Initial window management in the Wayland driver
- SoundFont support in DirectMusic
Full release notes available [here](https://www.winehq.org/announce/8.17)
**Test Plan**
- Tested winecfg, winefile, wineconsole
- Launched and played Age of Empires I Demo
**Checklist**
> wine: update to 8.17

- common/Taskfile.yml
- common/Tasks/Taskfile.qt5.yml
Adds a function I've been using for a while that updates the commit on the qt5 packages to the latest KDE source
Used it to update the qt5 libraries
> tasks: Add qt5-update task

- common/Scripts/helpers.sh
**Summary**
Provides helpers that can be sourced to provide common functionality 
**Test Plan**
Test the helpers work as expected.
**Checklist**
> common: Initial helpers script to provide common functionality

- packages/h/hunspell-it/package.yml
- packages/h/hunspell-it/pspec_x86_64.xml
**Summary**
- The inclusion of "homepage" to package.yml
- New source because the old one is not online
**Test Plan**
- Launched the hunspell -d it_IT on the terminal
**Checklist**
> hunspell-it: Inclusion of homepage and of a new source

- packages/0/0ad-data/package.yml
- packages/0/0ad-data/pspec_x86_64.xml
> 0ad-data: Add homepage

- packages/b/bdwgc/package.yml
- packages/b/bdwgc/pspec_x86_64.xml
**Summary**
Fix the bdwgc homepage. The old link no longer works.
**Test Plan**
- Checked correct homepage info is now part of the pspec
**Checklist**
> bdwgc: fix homepage

- packages/t/tailscale/package.yml
- packages/t/tailscale/pspec_x86_64.xml
**Summary**
- Fixed tailscale serve config lost in container
- Fixed tailnet lock failed to sign node in container
- Fixed Funnel support for tsnet apps
- Fixed potential crash with UPnP
**Test Plan**
**Checklist**
> tailscale: Update to 1.50.1

- packages/f/font-iosevka-ttf/package.yml
- packages/f/font-iosevka-ttf/pspec_x86_64.xml
- Changed variant names
- Add separate variant selector VXAA for Cyrillic Lower Er
- Add separate variant selector VXAB for Cyrillic Lower U
- Add flat middle stroke variant for 5
- Fix variants for Serbian Cyrillic Lower Pe
- [changelog](https://raw.githubusercontent.com/be5invis/Iosevka/v27.1.0/CHANGELOG.md)
> font-iosevka-ttf: Update to 27.1.0

- common/CI/package_checks.py
**Summary**
Extend the pspec consistency checks to catch a mismatched homepage. This can be caused when adding it without rebuilding the package, which is likely when new packagers are asked to add it.
**Test Plan**
Add a homepage to `nginx` without rebuild and run `go-task check -- packages/n/nginx/*`.
**Checklist**
> ci: ensure homepage is consistent in packages

- .github/workflows/script_lint.yml
- .gitignore
- .mypy.ini
- common/CI/package_checks.py
**Summary**
Add mypy to the linting workflow to catch any typing errors.
**Test Plan**
This PR!
**Checklist**
> ci: Add mypy linting for CI scripts

- packages/g/ghostscript/package.yml
- packages/g/ghostscript/pspec_x86_64.xml
**Summary**
- The inclusion of "homepage" to package.yml
**Test Plan**
- Launched the application on terminal
**Checklist**
> ghostscript: Inclusion of homepage

- packages/z/zuluCrypt/package.yml
- packages/z/zuluCrypt/pspec_x86_64.xml
**Summary**
**Test Plan**
- Build successful
**Checklist**
> zuluCrypt: Inclusion of homepage

- packages/z/zsxd/package.yml
- packages/z/zsxd/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
- Install the package
- Run the game
- Create new save file
**Checklist**
>  zsxd: Inclusion of homepage

- packages/z/zsh-syntax-highlighting/package.yml
- packages/z/zsh-syntax-highlighting/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
> zsh-sytax-highlighting: Inclusion of homepage

- packages/z/zsh/package.yml
- packages/z/zsh/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
>  zsh: Inclusion of homepage

- packages/s/source-code-pro/files/source-code-pro.metainfo.xml
- packages/s/source-code-pro/package.yml
- packages/s/source-code-pro/pspec_x86_64.xml
part of #449
- add homepage
- add appstream metainfo
- built package
- built appstream data and checked example-failed.xml.gz
**Checklist**
> source-code-pro: update homepage and metainfo xml

- packages/z/zsdx/package.yml
- packages/z/zsdx/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
- Run package
- Start new game
**Checklist**
> zsdx: Inclusion of homepage

- packages/z/zram-generator/abi_used_symbols
- packages/z/zram-generator/package.yml
- packages/z/zram-generator/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
> zram-generator: Inclusion of homepage

- packages/z/zip/abi_libs
- packages/z/zip/abi_symbols
- packages/z/zip/package.yml
- packages/z/zip/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
> zip: Inclusion of homepage

- packages/z/zim-tools/package.yml
- packages/z/zim-tools/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
> zim-tools: Inclusion of homepage

- packages/z/zimg/package.yml
- packages/z/zimg/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
> zimg: Inclusion of homepage

- packages/z/zeromq/abi_used_symbols
- packages/z/zeromq/package.yml
- packages/z/zeromq/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
> zeromq: Inclusion of homepage

- packages/c/cppzmq/package.yml
- packages/c/cppzmq/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
>  cppzmq: Inclusion of homepage

- packages/z/zelda-roth-se/package.yml
- packages/z/zelda-roth-se/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
- Run package
- Start new game
**Checklist**
> zelda-roth-se: Inclusion of homepage

- packages/z/zanshin/package.yml
- packages/z/zanshin/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
- Run program
- Create task
**Checklist**
> zanshin: Inclusion of homepage

- packages/y/yubikey-personalization/abi_used_libs
- packages/y/yubikey-personalization/abi_used_symbols
- packages/y/yubikey-personalization/package.yml
- packages/y/yubikey-personalization/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
> yubikey-personalization: Inclusion of homepage

- packages/j/jack-capture/package.yml
- packages/j/jack-capture/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
> jack-capture: Inclusion of homepage

- packages/y/yubikey-personalization-gui/abi_used_symbols
- packages/y/yubikey-personalization-gui/package.yml
- packages/y/yubikey-personalization-gui/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
> yubikey-personalization-gui: Inclusion of homepage

- packages/j/jp2a/package.yml
- packages/j/jp2a/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
- Run the  program
- Convert small `.jpg` file
**Checklist**
> jp2a: Inclusion of homepage

- packages/j/josm/package.yml
- packages/j/josm/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
- Run the  program
- Download map file
- Create save file `.osm`
**Checklist**
> josm: Inclusion of homepage

- packages/z/zinnia/abi_used_symbols
- packages/z/zinnia/package.yml
- packages/z/zinnia/pspec_x86_64.xml
**Summary**
- Replace `%configure` with `%reconfigure` to build successfully
- Part of #411
**Test Plan**
**Checklist**
> zinnia: Inclusion of homepage

- packages/z/zita-convolver/package.yml
- packages/z/zita-convolver/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
> zita-convolver: Inclusion of homepage

- packages/j/joe/abi_used_symbols
- packages/j/joe/package.yml
- packages/j/joe/pspec_x86_64.xml
**Summary**
- change `%configure` to `%reconfigure` to build successfully
- Part of #411
**Test Plan**
- Run package
- Create text file
**Checklist**
> joe: Inclusion of homepage

- packages/j/jansson/abi_used_symbols
- packages/j/jansson/abi_used_symbols32
- packages/j/jansson/package.yml
- packages/j/jansson/pspec_x86_64.xml
**Summary**
- Part of #411
**Test Plan**
**Checklist**
> jansson: Inclusion of homepage

- common/CI/package_checks.py
**Summary**
Render commits as notice messages in the diff.
**Test Plan**
See [this test PR](https://github.com/silkeh/packages/pull/3).
**Checklist**
> ci: Render commits as comments

- packages/f/font-tt2020-ttf/files/tt2020.metainfo.xml
- packages/f/font-tt2020-ttf/package.yml
- packages/f/font-tt2020-ttf/pspec_x86_64.xml
**Summary**
- Adding `homepage` key to `package.yml`( Part of getsolus#411)
- Including `metainfo.xml` (Part of getsolus#449)
- Change `license` info
**Test Plan**
**Checklist**
> font-tt2020-ttf: Inclusion of homepage and metainfo.xml

- packages/j/jsoncpp/abi_used_symbols
- packages/j/jsoncpp/package.yml
- packages/j/jsoncpp/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> jsoncpp: Inclusion of homepage

- .github/workflows/script_lint.yml
- Taskfile.yml
- common/CI/package_checks.py
- common/Hooks/post-merge.sh
- common/Hooks/post-rewrite.sh
- common/Hooks/pre-commit.py
- common/Hooks/prepare-commit-msg.py
**Summary**
Add Git hooks and initialisation:
- Task for initializing the hooks.
- Pre-commit hook that runs the package checks for the files to be committed.
- Post-checkout hook that runs `go-task init`.
**Test Plan**
- Check out this PR, eg: `git pr 466` (from `git-extras`).
- Run `go-task init`.
- Switch to main or any other branch and continue working normally.
**Checklist**
> repo: add Git hooks

- packages/v/vdpauinfo/abi_used_symbols
- packages/v/vdpauinfo/package.yml
- packages/v/vdpauinfo/pspec_x86_64.xml
**Summary**
- Added AV1 support
**Test Plan**
- Ran `vdpauinfo --screen 0`and saw expedted result
**Checklist**
> vdpauinfo: Update to 1.5

- packages/v/vidcutter/package.yml
- packages/v/vidcutter/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> vidcutter: Inclusion of homepage

- packages/v/vimix-cursors/package.yml
- packages/v/vimix-cursors/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> vimix-cursors: Inclusion of homepage

- packages/v/vcdimager/abi_used_symbols
- packages/v/vcdimager/package.yml
- packages/v/vcdimager/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> vcdimager: Inclusion of homepage

- packages/v/vapoursynth/abi_used_symbols
- packages/v/vapoursynth/package.yml
- packages/v/vapoursynth/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> vapoursynth: Inclusion of homepage

- packages/u/uthash/package.yml
- packages/u/uthash/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> uthash: Inclusion of homepage

- packages/u/usysconf/package.yml
- packages/u/usysconf/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> usysconf: Inclusion of homepage

- packages/u/usdx/package.yml
- packages/u/usdx/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> usdx: Inclusion of homepage

- packages/u/usbredir/abi_used_symbols
- packages/u/usbredir/package.yml
- packages/u/usbredir/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> usbredir: Inclusion of homepage

- packages/u/usbmuxd/abi_used_symbols
- packages/u/usbmuxd/package.yml
- packages/u/usbmuxd/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> usbmuxd: Inclusion of homepage

- packages/u/usb-modeswitch/package.yml
- packages/u/usb-modeswitch/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> usb-modeswitch: Inclusion of homepage

- packages/u/usbguard/abi_used_symbols
- packages/u/usbguard/files/0001-fix-gcc-13.patch
- packages/u/usbguard/package.yml
- packages/u/usbguard/pspec_x86_64.xml
**Summary**
- Added patch file to build against gcc 13
**Test Plan**
**Checklist**
> usbguard: Inclusion of homepage

- packages/u/unshield/package.yml
- packages/u/unshield/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> unshield: Inclusion of homepage

- packages/u/unrtf/package.yml
- packages/u/unrtf/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> unrtf: Inclusion of homepage

- packages/u/unpaper/abi_libs
- packages/u/unpaper/abi_symbols
- packages/u/unpaper/abi_used_symbols
- packages/u/unpaper/package.yml
- packages/u/unpaper/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> unpaper: Inclusion of homepage

- packages/u/unifdef/package.yml
- packages/u/unifdef/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> unifdef: Inclusion of homepage

- packages/u/unibilium/package.yml
- packages/u/unibilium/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> unibilium: Inclusion of homepage

- packages/u/unbound/abi_used_symbols
- packages/u/unbound/package.yml
- packages/u/unbound/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> unbound: Inclusion of homepage

- packages/u/udunits/abi_used_symbols
- packages/u/udunits/package.yml
- packages/u/udunits/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> udunits: Inclusion of homepage

- packages/u/uchardet/abi_libs
- packages/u/uchardet/abi_symbols
- packages/u/uchardet/abi_used_symbols
- packages/u/uchardet/package.yml
- packages/u/uchardet/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> uchardet: Inclusion of homepage

- packages/y/yubikey-manager-qt/package.yml
- packages/y/yubikey-manager-qt/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> yubikey-manager-qt: Inclusion of homepage

- packages/y/yubico-pam/package.yml
- packages/y/yubico-pam/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> yubico-pam: Inclusion of homepage

- packages/y/yq/package.yml
- packages/y/yq/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> yq: Inclusion of homepage

- packages/y/yelp-xsl/package.yml
- packages/y/yelp-xsl/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> yelp-xsl: Inclusion of homepage

- packages/y/yelp-tools/package.yml
- packages/y/yelp-tools/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> yelp-tools: Inclusion of homepage

- packages/y/yelp/package.yml
- packages/y/yelp/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> yelp: Inclusion of homepage

- packages/y/yaml/package.yml
- packages/y/yaml/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> yaml: Inclusion of homepage

- packages/y/yajl/package.yml
- packages/y/yajl/pspec_x86_64.xml
**Summary**
- Changed to new source
**Test Plan**
**Checklist**
> yajl: Inclusion of homepage

- packages/j/jsonrpc-glib/package.yml
- packages/j/jsonrpc-glib/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> jsonrpc-glib: Inclusion of homepage

- packages/j/json-c/package.yml
- packages/j/json-c/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> json-c: Inclusion of homepage

- packages/f/fio/abi_symbols
- packages/f/fio/abi_used_symbols
- packages/f/fio/package.yml
- packages/f/fio/pspec_x86_64.xml
**Summary**
- [changelog](https://git.kernel.dk/cgit/fio/log/?h=fio-3.36)
**Test Plan**
- fio write.ini
- fio read.ini
**Checklist**
> fio: Update to 3.36

- packages/f/font-firacode-nerd/MAINTAINERS.md
- packages/f/font-firacode-nerd/package.yml
- packages/f/font-firacode-nerd/pspec_x86_64.xml
**Summary**
Initial packaging of FiraCode fonts with nerdfonts patcher.
**Test Plan**
- Installed locally
**Checklist**
> Summary: Initial packaging of FiraCode fonts with nerdfonts patcher.

- packages/a/aisleriot/abi_used_symbols
- packages/a/aisleriot/package.yml
- packages/a/aisleriot/pspec_x86_64.xml
**Summary**
Changes:
- Fix scheme exception
- metainfo: Add launchable info
Packaging changes: added homepage and better description
**Test Plan**
Played a bit of Solitaire
**Checklist**
> aisleriot: update to 3.22.30

- packages/v/virglrenderer/abi_used_symbols
- packages/v/virglrenderer/package.yml
- packages/v/virglrenderer/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> virglrenderer: Inclusion of homepage

- packages/v/virt-manager/package.yml
- packages/v/virt-manager/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> virt-manager: Inclusion of homepage

- packages/v/vc-intrinsics/package.yml
- packages/v/vc-intrinsics/pspec_x86_64.xml
**Summary**
- Changelog can be found [here](https://github.com/intel/vc-intrinsics/compare/v0.12.3...v0.13.0)
**Test Plan**
**Checklist**
> vc-intrinsics: Update to 0.13.0

- packages/f/font-sarasa-gothic/MAINTAINERS.md
- packages/f/font-sarasa-gothic/package.yml
- packages/f/font-sarasa-gothic/pspec_x86_64.xml
**Summary**
Initial packaging of Sarasa-Gothic fonts.
**Test Plan**
- Installed locally
**Checklist**
> Summary: Initial packaging of Sarasa-Gothic fonts.

- common/Scripts/helpers.zsh
**Summary**
Add helper script for zsh for working with the monorepo
**Test Plan**
Exercised all functions in script with a fresh shell. Exercised package name completions.
**Checklist**
fixes #486
> Add zsh monorepo helper script

- packages/v/virt-viewer/abi_used_symbols
- packages/v/virt-viewer/package.yml
- packages/v/virt-viewer/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> virt-viewer: Inclusion of homepage

- packages/v/virtualenv-clone/package.yml
- packages/v/virtualenv-clone/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> virtualenv-clone: Inclusion of homepage

- packages/v/virtualenvwrapper/package.yml
- packages/v/virtualenvwrapper/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> virtualenvwrapper: Inclusion of homepage

- packages/w/wayland/abi_used_symbols
- packages/w/wayland/abi_used_symbols32
- packages/w/wayland/package.yml
- packages/w/wayland/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> wayland: Inclusion of homepage

- packages/w/w3m/abi_used_symbols
- packages/w/w3m/package.yml
- packages/w/w3m/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> w3m: Inclusion of homepage

- packages/v/vpnc/abi_used_symbols
- packages/v/vpnc/package.yml
- packages/v/vpnc/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> vpnc: Inclusion of homepage

- packages/v/vorbisgain/abi_used_symbols
- packages/v/vorbisgain/package.yml
- packages/v/vorbisgain/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> vorbisgain: Inclusion of homepage

- packages/v/volume_key/package.yml
- packages/v/volume_key/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> volume_key: Inclusion of homepage

- packages/v/vscode/package.yml
- packages/v/vscode/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> vscode: Inclusion of homepage

- packages/w/wiiuse/package.yml
- packages/w/wiiuse/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> wiiuse: Inclusion of homepage

- packages/l/libreoffice-voikko/package.yml
- packages/l/libreoffice-voikko/pspec_x86_64.xml
- packages/l/libvoikko/abi_symbols
- packages/l/libvoikko/abi_used_symbols
- packages/l/libvoikko/package.yml
- packages/l/libvoikko/pspec_x86_64.xml
- packages/v/voikko-fi/package.yml
- packages/v/voikko-fi/pspec_x86_64.xml
**Summary**
- Update `libvoikko`, `voiko-fi` and rebuild `libreoffice-voikko`
-  Full changelog can be found [here](https://voikko.puimula.org/releases.html)
- Added `homepage` key to `package.yml` part of https://github.com/getsolus/packages/issues/411
**Test Plan**
- Write some finnish word in libreoffice and see if it correctly spellcheck it
**Checklist**
-  [ ] Finnish speaker to actually test it
> voikko stack update

- packages/x/xfce4-desktop-branding/files/56solus-session
- packages/x/xfce4-desktop-branding/files/60-solusxfce.conf
- packages/x/xfce4-desktop-branding/files/solus-xfce.desktop
- packages/x/xfce4-desktop-branding/package.yml
- packages/x/xfce4-desktop-branding/pspec_x86_64.xml
- packages/x/xfce4-session/package.yml
- packages/x/xfce4-session/pspec_x86_64.xml
**Summary**
Fix up xfce4-session to include xdg-user-dirs-gtk to help populate folders, also finish up the desktop branding package
**Test Plan**
The test plan was to ensure theming and changes took for both live and installed environments
**Checklist**
> Xfce branding

- packages/f/fb2converter/package.yml
- packages/f/fb2converter/pspec_x86_64.xml
**Summary**
- Change "usage" text and command line switches
**Test Plan**
- display "usage" text
**Checklist**
> fb2converter: Update to 1.72.2

- packages/y/yuzu/abi_used_symbols
- packages/y/yuzu/package.yml
- packages/y/yuzu/pspec_x86_64.xml
**Summary**
- Full changelog can be found [here](https://github.com/yuzu-emu/yuzu-mainline/compare/mainline-0-1559...mainline-0-1605)
- Added `homepage` key to `package.yml` part of #411
**Test Plan**
- Launch a game, make sure everything ok
**Checklist**
> yuzu: Update to 1605

- packages/w/webrtc-audio-processing/abi_used_symbols
- packages/w/webrtc-audio-processing/abi_used_symbols32
- packages/w/webrtc-audio-processing/package.yml
- packages/w/webrtc-audio-processing/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> webrtc-audio-processing: Inclusion of homepage

- packages/w/winetricks/package.yml
- packages/w/winetricks/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> winetricks: Homepage inclusion

- packages/w/witchblast/abi_used_symbols
- packages/w/witchblast/package.yml
- packages/w/witchblast/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> witchblast: Homepage inclusion

- packages/w/woeusb/package.yml
- packages/w/woeusb/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> woeusb: Homepage inclusion

- packages/w/woff-tools/abi_used_symbols
- packages/w/woff-tools/package.yml
- packages/w/woff-tools/pspec_x86_64.xml
**Summary**
- Replaced old source with new one
**Test Plan**
**Checklist**
> woff-tools: Homepage inclusion

- packages/w/wpa_supplicant/package.yml
- packages/w/wpa_supplicant/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> wpa_supplicant: Homepage inclusion

- packages/w/wxmaxima/abi_used_symbols
- packages/w/wxmaxima/package.yml
- packages/w/wxmaxima/pspec_x86_64.xml
**Summary**
- Full changelog can be found [here](https://raw.githubusercontent.com/wxMaxima-developers/wxmaxima/Version-23.10.0/NEWS.md)
**Test Plan**
- Open example files and check everything look good
**Checklist**
> wxmaxima: Update to 23.10.0

- packages/p/pipes-sh/package.yml
- packages/p/pipes-sh/pspec_x86_64.xml
**Summary**
Added homepage to package
**Test Plan**
- ![](https://i.imgur.com/Rdx16LK.png)
- Confirmed homepage was listed in pspec
**Checklist**
> pipes-sh: Add homepage

- .github/ISSUE_TEMPLATE/request-new-package.yml
GitHub workflow change: Harmonize wording of the "Request new package" template with the corresponding Help center page.
Corresponding Help Center PR: https://github.com/getsolus/help-center-docs/pull/433
> .github: Edit "Request new package" template

- packages/a/abcm2ps/package.yml
- packages/a/abcm2ps/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> abcm2ps: homepage inclusion

- packages/a/abi-wizard/package.yml
- packages/a/abi-wizard/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> abi-wizard: homepage inclusion

- packages/a/acccheck/package.yml
- packages/a/acccheck/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> acccheck: homepage inclusion

- packages/a/acl/abi_used_symbols
- packages/a/acl/abi_used_symbols32
- packages/a/acl/package.yml
- packages/a/acl/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> acl: homepage inclusion

- packages/a/acpi/package.yml
- packages/a/acpi/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> acpi: homepage inclusion

- packages/a/aegisub/abi_used_symbols
- packages/a/aegisub/package.yml
- packages/a/aegisub/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> aegisub: homepage inclusion

- packages/a/ajour/package.yml
- packages/a/ajour/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> ajour: homepage inclusion

- packages/a/a2jmidid/abi_used_symbols
- packages/a/a2jmidid/package.yml
- packages/a/a2jmidid/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> a2jmidid: Homepage inclusion

- packages/a/aa-lsm-hook/package.yml
- packages/a/aa-lsm-hook/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> aa-lsm-hook: Homepage inclusion

- packages/a/akonadiconsole/package.yml
- packages/a/akonadiconsole/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> akonadiconsole: homepage inclusion

- common/CI/package_checks.py
**Summary**
This adds a CI check for the order of build dependencies.
**Test Plan**
See [this test PR](https://github.com/silkeh/packages/pull/3/files).
**Checklist**
- ~~Package was built and tested against unstable~~
> ci/package_checks: Add check for order of `{build,check,run}deps`

- packages/a/ant-gtk-theme/package.yml
- packages/a/ant-gtk-theme/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> ant-gtk-theme: homepage inclusion

- packages/a/ant-bloody-gtk-theme/package.yml
- packages/a/ant-bloody-gtk-theme/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> ant-bloody-gtk-theme: homepage inclusion

- packages/a/amfora/package.yml
- packages/a/amfora/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> amfora: homepage inclusion

- packages/a/alpine/package.yml
- packages/a/alpine/pspec_x86_64.xml
**Summary**
**Test Plan**
- Set up mail account with imap and smtp
**Checklist**
> alpine: homepage inclusion

- packages/a/alsa-utils/package.yml
- packages/a/alsa-utils/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> alsa-utils: homepage inclusion

- packages/a/alsa-plugins/abi_used_symbols
- packages/a/alsa-plugins/abi_used_symbols32
- packages/a/alsa-plugins/package.yml
- packages/a/alsa-plugins/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> alsa-plugins: homepage inclusion

- packages/a/alsa-lib/package.yml
- packages/a/alsa-lib/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> alsa-lib: homepage inclusion

- packages/w/wxwidgets30/abi_used_symbols
- packages/w/wxwidgets30/package.yml
- packages/w/wxwidgets30/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> wxwidgets30: Homepage inclusion

- packages/a/anthy/package.yml
- packages/a/anthy/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> anthy: homepage inclusion

- packages/a/arc-gtk-theme/package.yml
- packages/a/arc-gtk-theme/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> arc-gtk-theme: homepage inclusion

- packages/a/arcanist/package.yml
- packages/a/arcanist/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> arcanist: homepage inclusion

- packages/a/apcupsd/abi_used_symbols
- packages/a/apcupsd/package.yml
- packages/a/apcupsd/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> apcupsd: homepage inclusion

- packages/a/arc-icon-theme/package.yml
- packages/a/arc-icon-theme/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> arc-icon-theme: homepage inclusion

- packages/a/atril/abi_used_symbols
- packages/a/atril/package.yml
- packages/a/atril/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> atril: homepage inclusion

- packages/a/atool/package.yml
- packages/a/atool/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> atool: homepage inclusion

- packages/w/wxsvg/abi_used_symbols
- packages/w/wxsvg/files/fix-build.patch
- packages/w/wxsvg/package.yml
- packages/w/wxsvg/pspec_x86_64.xml
**Summary**
**Test Plan**
- Run `svgview [file]` to open `.svg` images
**Checklist**
> wxsvg: Homepage inclusion

- packages/a/arx-libertatis/abi_used_symbols
- packages/a/arx-libertatis/files/org.arx.ArxLibertatis.metainfo.xml
- packages/a/arx-libertatis/package.yml
- packages/a/arx-libertatis/pspec_x86_64.xml
**Summary**
- Added `metainfo.xml`
**Test Plan**
**Checklist**
> arx-libertatis: homepage inclusion

- packages/a/asciinema/package.yml
- packages/a/asciinema/pspec_x86_64.xml
**Summary**
- [Full Changelog](https://raw.githubusercontent.com/asciinema/asciinema/v2.4.0/CHANGELOG.md)
**Test Plan**
- Run `asciinema rec` and `asciinema play` and see expected result
**Checklist**
> asciinema: Update to 2.4.0

- common/CI/package_checks.py
**Summary**
Add a linter for valid SPDX license identifiers.
**Test Plan**
See [this diff](https://github.com/silkeh/packages/pull/4/files#diff-6e0c2af98ca9c3a4a84deb358617e7381a0b77b836f9053bf9ed7ef4943964acR7).
**Checklist**
>  ci/package_checks: add check for SPDX license identifiers

- packages/a/attract/abi_used_symbols
- packages/a/attract/package.yml
- packages/a/attract/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> attract: homepage inclusion

- packages/a/attr/package.yml
- packages/a/attr/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> attr: homepage inclusion

- packages/a/audiofile/abi_used_symbols
- packages/a/audiofile/package.yml
- packages/a/audiofile/pspec_x86_64.xml
**Summary**
- fix typo in package.yml
**Checklist**
> audiofile: fix typo in package.yml

- packages/a/autojump/package.yml
- packages/a/autojump/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> autojump: homepage inclusion

- packages/b/babl/abi_used_symbols
- packages/b/babl/package.yml
- packages/b/babl/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> babl: homepage inclusion

- packages/b/bamf/abi_used_symbols
- packages/b/bamf/package.yml
- packages/b/bamf/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> bamf: homepage inclusion

- packages/b/bam/package.yml
- packages/b/bam/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> bam: homepage inclusion

- packages/b/bash-completion/package.yml
- packages/b/bash-completion/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> bash-completion: homepage inclusion

- packages/a/avahi/package.yml
- packages/a/avahi/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> avahi: homepage inclusion

- packages/b/bc/abi_used_symbols
- packages/b/bc/package.yml
- packages/b/bc/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> bc: homepage inclusion

- packages/b/basis-universal/abi_used_symbols
- packages/b/basis-universal/package.yml
- packages/b/basis-universal/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> basis-universal: homepage inclusion

- packages/b/bottom/abi_used_symbols
- packages/b/bottom/package.yml
- packages/b/bottom/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> bottom: homepage inclusion

- packages/b/bookworm/package.yml
- packages/b/bookworm/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> bookworm: homepage inclusion

- packages/b/brasero/abi_used_symbols
- packages/b/brasero/package.yml
- packages/b/brasero/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> brasero: homepage inclusion

- packages/c/calamares/files/shellprocess_postinstall.conf
- packages/c/calamares/package.yml
- packages/c/calamares/pspec_x86_64.xml
**Summary**
- Set vconsole font during install
Ref https://github.com/getsolus/packages/issues/826
**Test Plan**
Create a new ISO with this package, install in a VM, and see that the line was written to /etc/vconsole.conf after a reboot.
**Checklist**
> calamares: Set vconsole font during install

- packages/t/tailscale/package.yml
- packages/t/tailscale/pspec_x86_64.xml
**Summary**
- bugfix release
- [changelog](https://tailscale.com/changelog/)
**Test Plan**
**Checklist**
> tailscale: Update to 1.54.1

- packages/f/font-iosevka-ttf/package.yml
- packages/f/font-iosevka-ttf/pspec_x86_64.xml
**Summary**
- Add italic form of CYRILLIC SMALL LETTER THREE-LEGGED TE
- Add top-right serif to fully serifed form for CYRILLIC SMALL LETTER TALL TE
- Fix serifs of GREEK LETTER DIGAMMA (U+03DC) under ss12.
- Improve crossbar position of GREEK SMALL LETTER DIGAMMA (U+03DD) and add a middle serif under slab.
- Refine Greek Capital Sho (U+03F7) glyph
- Make SYMBOL FOR DELETE FORM TWO (U+2425) narrow by default, align with other Control Pictures characters
- Make APL FUNCTIONAL SYMBOL CIRCLE STAR (U+235F) always be five-pointed and upright, to align its pentagram history
**Test Plan**
**Checklist**
> font-iosevka-ttf: Update to 27.3.5

- packages/a/autossh/abi_libs
- packages/a/autossh/abi_symbols
- packages/a/autossh/abi_used_symbols
- packages/a/autossh/package.yml
- packages/a/autossh/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
**Comment**
Please put this [tarball](https://fossies.org/linux/privat/autossh-1.4g.tgz) on sources.getsol.us, their [source](https://www.harding.motd.ca/autossh/autossh-1.4g.tgz) doesn't work for me
> autossh: homepage inclusion

- packages/c/calamares/files/install/branding/solus/branding.desc
- packages/c/calamares/package.yml
- packages/c/calamares/pspec_x86_64.xml
**Summary**
- Update Solus version and codename
Ref https://github.com/getsolus/packages/issues/929
**Test Plan**
Update Calamares in a live environment and note the string change
**Checklist**
> calamares: Update Solus version and codename

- packages/c/calamares/files/patches/downstream/0001-bootloader-Add-clr-boot-manager-support.patch
- packages/c/calamares/package.yml
- packages/c/calamares/pspec_x86_64.xml
**Summary**
- Fix bootloader installation with swap partition
**Test Plan**
Install the updated package in a live session and successfully installed and rebooted with the following configurations:
- UEFI + Swap partition
- UEFI + Swap file
- BIOS + Swap Partition
**Checklist**
> calamares: Fix bootloader installation with swap

- packages/m/mugshot/package.yml
- packages/m/mugshot/pspec_x86_64.xml
- packages/w/whiskermenu/package.yml
- packages/w/whiskermenu/pspec_x86_64.xml
**Summary**
- mugshot: Initial inclusion of mugshot
- whiskermenu: Add missing mugshot dependency
Ref https://github.com/getsolus/packages/issues/305
**Test Plan**
Install the mugshot package and click the user icon in Whiskermenu to open mugshot.
**Checklist**
> add mugshot for whiskermenu

- packages/x/xfce4-desktop-branding/package.yml
- packages/x/xfce4-desktop-branding/pspec_x86_64.xml
**Summary**
Includes [this PR](https://github.com/getsolus/xfce4-desktop-branding/pull/4) from getsolus/xfce4-desktop-branding
**Test Plan**
1. Rebuilt against unstable
2. Built a smoketest ISO with this package in the local repo
3. Booted smoketest ISO in a VM
4. Autologin worked.
**Checklist**
> xfce4-desktop-branding: Update Solus Defaults

- packages/h/hunspell-uk/package.yml
- packages/h/hunspell-uk/pspec_x86_64.xml
**Summary**
- Updates related to improvements of Ukrainian language corpus
**Test Plan**
- proofread Ukrainian text
**Checklist**
> hunspell-uk: Update to 6.3.1

- packages/a/adw-gtk3-theme/package.yml
- packages/a/adw-gtk3-theme/pspec_x86_64.xml
**Summary**
[Changelog](https://github.com/lassekongo83/adw-gtk3/compare/v5.1...v5.2)
**Test Plan**
Install on GNOME, verify things look as normal
**Checklist**
> adw-gtk3-theme: Update to 5.2

- packages/b/brother-dcp7010/abi_libs
- packages/b/brother-dcp7010/abi_symbols
- packages/b/brother-dcp7010/abi_used_symbols
- packages/b/brother-dcp7010/package.yml
- packages/b/brother-dcp7010/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> brother-dcp7010: homepage inclusion

- packages/b/brother-dcp7060d/abi_libs
- packages/b/brother-dcp7060d/abi_symbols
- packages/b/brother-dcp7060d/abi_used_symbols
- packages/b/brother-dcp7060d/package.yml
- packages/b/brother-dcp7060d/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> brother-dcp7060d: homepage inclusion

- packages/b/brother-hl2220/abi_libs
- packages/b/brother-hl2220/abi_symbols
- packages/b/brother-hl2220/abi_used_symbols
- packages/b/brother-hl2220/package.yml
- packages/b/brother-hl2220/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> brother-hl2220: homepage inclusion

- packages/f/fb2converter/package.yml
- packages/f/fb2converter/pspec_x86_64.xml
**Summary**
- dependency updates
**Test Plan**
- fb2c convert input.fb2
- skim through generated epub
**Checklist**
> fb2converter: Update to 1.72.3

- packages/f/font-iosevka-ttf/package.yml
- packages/f/font-iosevka-ttf/pspec_x86_64.xml
**Summary**
- Added Characters
- Stylistic set fixes
- [changelog](https://raw.githubusercontent.com/be5invis/Iosevka/v28.0.1/CHANGELOG.md)
**Test Plan**
**Checklist**
> font-iosevka-ttf: Update to 28.0.1

- packages/b/brother-hll2375dw/package.yml
- packages/b/brother-hll2375dw/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> brother-hll2375dw: homepage inclusion

- packages/b/brother-hll2390dw/package.yml
- packages/b/brother-hll2390dw/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> brother-hll2390dw: homepage inclusion

- packages/b/brother-mfcj480dw/abi_libs
- packages/b/brother-mfcj480dw/abi_symbols
- packages/b/brother-mfcj480dw/abi_used_symbols
- packages/b/brother-mfcj480dw/package.yml
- packages/b/brother-mfcj480dw/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> brother-mfcj480dw: homepage inclusion

- packages/b/brother-mfcj220/abi_libs
- packages/b/brother-mfcj220/abi_symbols
- packages/b/brother-mfcj220/abi_used_symbols
- packages/b/brother-mfcj220/package.yml
- packages/b/brother-mfcj220/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> brother-mfcj220: homepage inclusion

- packages/b/brother-mfc9330cdw/abi_libs
- packages/b/brother-mfc9330cdw/abi_symbols
- packages/b/brother-mfc9330cdw/abi_used_symbols
- packages/b/brother-mfc9330cdw/package.yml
- packages/b/brother-mfc9330cdw/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> brother-mfc9330cdw: homepage inclusion

- packages/b/brother-mfc440cn/abi_libs
- packages/b/brother-mfc440cn/abi_symbols
- packages/b/brother-mfc440cn/abi_used_symbols
- packages/b/brother-mfc440cn/package.yml
- packages/b/brother-mfc440cn/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> brother-mfc440cn: homepage inclusion

- packages/b/bsdiff/abi_used_symbols
- packages/b/bsdiff/package.yml
- packages/b/bsdiff/pspec_x86_64.xml
**Summary**
- Write to a unique-ish file and then rename at the end to avoid clashes
- Deal with two error cases
**Test Plan**
- Diff two version of binaries to produce delta files
**Checklist**
> bsdiff: Update to 1.0.6

- packages/b/brscan4/package.yml
- packages/b/brscan4/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> brscan4: homepage inclusion

- packages/b/btop/abi_used_symbols
- packages/b/btop/package.yml
- packages/b/btop/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> btop: homepage inclusion

- packages/c/camlp4/package.yml
- packages/c/camlp4/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> camlp4: homepage inclusion

- packages/c/cabextract/package.yml
- packages/c/cabextract/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cabextract: homepage inclusion

- packages/b/byobu/package.yml
- packages/b/byobu/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> byobu: homepage inclusion

- packages/b/busybox/package.yml
- packages/b/busybox/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> busybox: homepage inclusion

- packages/b/burp/abi_used_symbols
- packages/b/burp/package.yml
- packages/b/burp/pspec_x86_64.xml
**Summary**
- Updated to latest stable based on 2.3.38
- Fix changelog date, and tweak manpage
**Test Plan**
**Checklist**
> burp: Update to 2.4.0

- packages/b/budgie-restart-applet/package.yml
- packages/b/budgie-restart-applet/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> budgie-restart-applet: homepage inclusion

- packages/b/btrbk/package.yml
- packages/b/btrbk/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> btrbk: homepage inclusion

- packages/b/bspwm/abi_libs
- packages/b/bspwm/abi_symbols
- packages/b/bspwm/abi_used_symbols
- packages/b/bspwm/package.yml
- packages/b/bspwm/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> bspwm: homepage inclusion

- packages/m/mate-tweak/package.yml
- packages/m/mate-tweak/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> mate-tweak: homepage inclusion

- packages/c/ccsm/package.yml
- packages/c/ccsm/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> ccsm: homepage inclusion

- packages/b/bullet3/abi_used_symbols
- packages/b/bullet3/package.yml
- packages/b/bullet3/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> bullet3: homepage inclusion

- packages/b/budgie-backgrounds/package.yml
- packages/b/budgie-backgrounds/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> budgie-backgrounds: homepage inclusion

- packages/c/cdrdao/abi_used_symbols
- packages/c/cdrdao/package.yml
- packages/c/cdrdao/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cdrdao: homepage inclusion

- packages/c/ceres-solver/abi_used_symbols
- packages/c/ceres-solver/package.yml
- packages/c/ceres-solver/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
**Notes**
The `https` website didn't work, used `http` instead
> ceres-solver: homepage inclusion

- packages/c/calamares/files/install/modules/partition.conf
- packages/c/calamares/package.yml
- packages/c/calamares/pspec_x86_64.xml
**Summary**
- Disable swapfile option
Closes https://github.com/getsolus/packages/issues/1077
**Test Plan**
Ran installer, saw that option to create a swapfile does not appear
**Checklist**
> calamares: Disable swapfile option

- packages/c/cgal/package.yml
- packages/c/cgal/pspec_x86_64.xml
- packages/o/openscad/package.yml
- packages/o/openscad/pspec_x86_64.xml
**Summary**
- Bug fixes release
- Release notes:
- [5.2](https://www.cgal.org/2020/12/22/cgal52/)
- [5.1](https://www.cgal.org/2020/09/08/cgal51/)
- Added `homepage` key to `package.yml` (Part of https://github.com/getsolus/packages/issues/411)
**Test Plan**
- Rebuild  `openscad` against this package
**Checklist**
> cgal: Update to 5.2.4

- packages/c/cifs-utils/abi_libs
- packages/c/cifs-utils/abi_symbols
- packages/c/cifs-utils/abi_used_symbols
- packages/c/cifs-utils/package.yml
- packages/c/cifs-utils/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cifs-utils: homepage inclusion

- packages/c/chocolate-doom/abi_libs
- packages/c/chocolate-doom/abi_symbols
- packages/c/chocolate-doom/package.yml
- packages/c/chocolate-doom/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> chocolate-doom: homepage inclusion

- packages/c/chrono-date/abi_used_symbols
- packages/c/chrono-date/package.yml
- packages/c/chrono-date/pspec_x86_64.xml
**Summary**
Added `homepage` key to `package.yml` (Part of https://github.com/getsolus/packages/issues/411)
**Test Plan**
**Checklist**
> chrono-date: homepage inclusion

- packages/c/clojure-tools/package.yml
- packages/c/clojure-tools/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> clojure-tools: homepage inclusion

- packages/c/colord/abi_used_symbols
- packages/c/colord/package.yml
- packages/c/colord/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> colord: homepage inclusion

- packages/c/compsize/package.yml
- packages/c/compsize/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> compsize: homepage inclusion

- packages/c/compiz-plugins-main/abi_symbols
- packages/c/compiz-plugins-main/abi_used_symbols
- packages/c/compiz-plugins-main/package.yml
- packages/c/compiz-plugins-main/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> compiz-plugins-main: homepage inclusion

- packages/c/compiz-plugins-extra/abi_symbols
- packages/c/compiz-plugins-extra/abi_used_symbols
- packages/c/compiz-plugins-extra/package.yml
- packages/c/compiz-plugins-extra/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> compiz-plugins-extra: homepage inclusion

- packages/c/compiz/abi_used_symbols
- packages/c/compiz/package.yml
- packages/c/compiz/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> compiz: homepage inclusion

- packages/c/compizconfig-python/abi_used_symbols
- packages/c/compizconfig-python/package.yml
- packages/c/compizconfig-python/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> compizconfig-python: homepage inclusion

- packages/c/cockatrice/abi_used_symbols
- packages/c/cockatrice/package.yml
- packages/c/cockatrice/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cockatrice: homepage inclusion

- packages/c/clj-kondo/package.yml
- packages/c/clj-kondo/pspec_x86_64.xml
**Summary**
- Changelog can be found [here](https://github.com/clj-kondo/clj-kondo/blob/v2023.12.15/CHANGELOG.md)
**Test Plan**
- Run example command found in [README](https://github.com/clj-kondo/clj-kondo/blob/master/README.md)
- Make sure it behaves as expected
**Checklist**
**Note**
This is part of my homepage _mission_ . I see that it has new version and easy to test, so eeeh why not update it? Sorry @olymk2 if I step on your toes. You might wanna take a look at this. Cheers!
> clj-kondo: Update to 2023.12.15

- packages/a/acsccid/abi_symbols
- packages/a/acsccid/abi_used_symbols
- packages/a/acsccid/package.yml
- packages/a/acsccid/pspec_x86_64.xml
**Summary**
- Changelog can be found on the bottom of [README](https://raw.githubusercontent.com/acshk/acsccid/v1.1.10/README)
**Test Plan**
**Checklist**
**Comment**
Anybody with ACS smartcard can help test this?
> acsccid: Update to 1.1.10

- packages/p/plasma-workspace-wallpapers/MAINTAINERS.md
- packages/p/plasma-workspace-wallpapers/package.yml
- packages/p/plasma-workspace-wallpapers/pspec_x86_64.xml
**Summary**
New package
**Test Plan**
Installed and applied wallpapers
**Checklist**
Resolves #1222
> Initial commit of plasma-workspace-wallpapers

- packages/c/cppcodec/package.yml
- packages/c/cppcodec/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cppcodec: homepage inclusion

- packages/a/audit/abi_symbols
- packages/a/audit/abi_used_symbols
- packages/a/audit/package.yml
- packages/a/audit/pspec_x86_64.xml
**Summary**
- Full changelog can be found [here](https://raw.githubusercontent.com/linux-audit/audit-userspace/v3.1.2/ChangeLog)
- Added `homepage` key to `package.yml` (Part of https://github.com/getsolus/packages/issues/411)
**Test Plan**
- Rebuild `dbus-broker` against this package
**Checklist**
> audit: Update to 3.1.2

- packages/c/ctpl/abi_used_symbols
- packages/c/ctpl/package.yml
- packages/c/ctpl/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> ctpl: homepage inclusion

- packages/c/cubicsdr/abi_used_symbols
- packages/c/cubicsdr/files/com.cubicsdr.cubicsdr.metainfo.xml
- packages/c/cubicsdr/package.yml
- packages/c/cubicsdr/pspec_x86_64.xml
**Summary**
- Added `homepage` key to `package.yml` (Part of getsolus/packages/issues/411)
- Added metainfo
**Test Plan**
**Checklist**
> cubicsdr: homepage inclusion

- packages/c/cuetools/abi_used_symbols
- packages/c/cuetools/package.yml
- packages/c/cuetools/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cuetools: homepage inclusion

- packages/c/comar-api/package.yml
- packages/c/comar-api/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> comar-api: homepage inclusion

- packages/c/cryptsetup/abi_used_symbols
- packages/c/cryptsetup/package.yml
- packages/c/cryptsetup/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cryptsetup: homepage inclusion

- packages/c/cubicsdr/package.yml
- packages/c/cubicsdr/pspec_x86_64.xml
Install icon and fix desktop file
> cubicsdr: Install icon and fix desktop file

- packages/g/g4music/package.yml
- packages/g/g4music/pspec_x86_64.xml
**Summary**
- 3.5.1 :
- Fix "playing" state when playing music changed.
- Use Overlay to avoid changing list's width.
- 3.5.0 :
- Fix "playing" state for music entries.
- Sorting albums by Disc Number.
- Add translation: Romanian, Danish, Slovenian.
- Update translation: Belarusian, Occitan.
**Test Plan**
Play an album : Facing Giants by AllttA
**Checklist**
> g4music: Update to 3.5.1

- packages/c/catbox/package.yml
- packages/c/catbox/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> catbox: homepage inclusion

- packages/f/font-iosevka-ttf/package.yml
- packages/f/font-iosevka-ttf/pspec_x86_64.xml
**Summary**
- Add untagged variant selector for Cyrillic Capital Ef (Ф) for style-driven variation
- Allow turned h (ɥ) and turned m with long leg (ɰ) to use toothless-corner variants
- Fix leaning marks of Turned/Reversed Sans-Serif Capital L
- Fix leaning marks of Cyrillic Tall Te
- Fix leaning marks of Greek Lower Mu/Rho
- APLF feature will apply to all Uiua operators
**Test Plan**
**Checklist**
> font-iosevka-ttf: Update to 28.0.5

- packages/v/visualboyadvance-m/MAINTAINERS.md
- packages/v/visualboyadvance-m/abi_used_symbols
- packages/v/visualboyadvance-m/package.yml
- packages/v/visualboyadvance-m/pspec_x86_64.xml
**Summary**
- Store the PC register at the appropriate offset
- Resize GameArea after MainFrame initialization
- Properly hide the status bar at startup
- Fix reading joystick hat config values
- Link: Fix menu not refreshing correctly
**Test Plan**
Play some games
**Checklist**
> visualboyadvance-m: Update to 2.1.8

- packages/a/aqbanking/package.yml
- packages/a/aqbanking/pspec_x86_64.xml
- packages/g/gwenhywfar/abi_symbols
- packages/g/gwenhywfar/package.yml
- packages/g/gwenhywfar/pspec_x86_64.xml
**Summary**
Full changelog is available inside [tarball](https://www.aquamaniac.de/rdm/attachments/download/501/gwenhywfar-5.10.2.tar.gz)
**Test Plan**
Rebuild `aqbanking` against this package
**Checklist**
> gwenhywfar: Update to 5.10.2

- packages/o/onedrive-gui/MAINTAINERS.md
- packages/o/onedrive-gui/files/0001-make-project-buildable.patch
- packages/o/onedrive-gui/files/0002-create-package-directory.patch
- packages/o/onedrive-gui/files/series
- packages/o/onedrive-gui/package.yml
- packages/o/onedrive-gui/pspec_x86_64.xml
The inclusion of onedrive-gui resolves https://github.com/getsolus/packages/issues/329
**Summary**
Add the onedrive-gui package, which provides a gui for package onedrive.
**Test Plan**
- Launched application
- Created profile
- Onedrive daemon was detected
- Exercised settings dialogs
**Checklist**
> onedrive-gui: initial inclusion in the repository

- packages/n/nvtop/package.yml
- packages/n/nvtop/pspec_x86_64.xml
> nvtop: Move desktop icon to hicolor

- packages/d/dbus-broker/package.yml
- packages/d/dbus-broker/pspec_x86_64.xml
**Summary**
- Add homepage, part of https://github.com/getsolus/packages/issues/411
**Test Plan**
- Things look normal on `busctl`
**Checklist**
> dbus-broker: Add homepage

- packages/b/bzflag/abi_used_symbols
- packages/b/bzflag/package.yml
- packages/b/bzflag/pspec_x86_64.xml
**Summary**
- Added appdata.xml
- Move icon file to hicolor
**Test Plan**
- Verify with `appstream-builder --packages-dir=. --include-failed -v`
**Checklist**
> bzflag: Add appdata.xml

- packages/b/bombermaaan/package.yml
- packages/b/bombermaaan/pspec_x86_64.xml
**Summary**
- Install appdata.xml
- Move icon install directory to hicolor
- Part of https://github.com/getsolus/packages/issues/1389
**Test Plan**
- Rebuild package
- Verify metadata with `appstream-builder --packages-dir=. --include-failed -v`
**Checklist**
> bombermaaan: Install appdata.xml

- packages/c/clustershell/MAINTAINERS.md
- packages/c/clustershell/package.yml
- packages/c/clustershell/pspec_x86_64.xml
**Summary**
Initial commit
**Test Plan**
Installed and used on a fleet of servers
**Checklist**
Resolves getsolus/packages#1232
> clustershell: Initial commit

- packages/g/gparted/abi_used_symbols
- packages/g/gparted/package.yml
- packages/g/gparted/pspec_x86_64.xml
**Summary**
- Added homepage (Part of https://github.com/getsolus/packages/issues/411)
- Move appstream metadata out of legacy path
**Test Plan**
Verified that homepage loads the correct website
**Checklist**
> gparted: Housekeeping

- packages/l/lutris/files/0001-Fix-metainfo.xml.patch
- packages/l/lutris/files/0002-One-more-update-to-metainfo.patch
- packages/l/lutris/files/series
- packages/l/lutris/package.yml
- packages/l/lutris/pspec_x86_64.xml
Fix appstream metadata (already fixed upstream)
> lutris: Fix appstream metadata

- packages/c/clustershell/package.yml
- packages/c/clustershell/pspec_x86_64.xml
**Summary**
- Bump rel num to 5 as package was undeprecated.
**Test Plan**
N/A
**Checklist**
> clustershell: Bump

- packages/u/usdx/package.yml
- packages/u/usdx/pspec_x86_64.xml
**Summary**
Install appstream metadata (Part of getsolus/packages#1389)
**Test Plan**
**Checklist**
> usdx: Install appstream metadata

- packages/g/gamehub/package.yml
- packages/g/gamehub/pspec_x86_64.xml
**Summary**
Added homepage key (Part of getsolus/packages#411)
**Test Plan**
Verified homepage loads relevant information
**Checklist**
> gamehub: Homepage inclusion

- packages/n/numix-icon-theme-circle/package.yml
- packages/n/numix-icon-theme-circle/pspec_x86_64.xml
- packages/n/numix-icon-theme-square/package.yml
- packages/n/numix-icon-theme-square/pspec_x86_64.xml
- packages/n/numix-icon-theme/package.yml
- packages/n/numix-icon-theme/pspec_x86_64.xml
**Summary**
- numix-icon-theme: Update to 23.12.02
- numix-icon-theme-circle: Update to 23.12.10
- numix-icon-theme-square: Update to 23.12.10
**Test Plan**
Install the themes and switch to each one.
**Checklist**
> update numix themes

- packages/f/frozen-bubble/abi_used_symbols
- packages/f/frozen-bubble/files/frozen-bubble.appdata.xml
- packages/f/frozen-bubble/files/frozen-bubble.desktop
- packages/f/frozen-bubble/package.yml
- packages/f/frozen-bubble/pspec_x86_64.xml
**Summary**
- Added appstream metadata (Part of getsolus/packages#1389)
- Added StartupWMClass to desktop file
**Test Plan**
**Checklist**
> frozen-bubble: Add appstream metadata

- packages/a/alacritty/monitoring.yml
- packages/b/btop/monitoring.yml
- packages/h/htop/monitoring.yml
- packages/k/kid3/monitoring.yml
- packages/m/minigalaxy/monitoring.yml
- packages/m/mkvtoolnix/monitoring.yml
- packages/o/opera-stable/monitoring.yml
- packages/r/rclone/monitoring.yml
- packages/r/restic/monitoring.yml
- packages/r/rpi-imager/monitoring.yml
- packages/s/strawberry/monitoring.yml
- packages/v/vivaldi-stable/monitoring.yml
- packages/x/xkcdpass/monitoring.yml
**Summary**
Add monitoring.yml for [release-monitoring](https://release-monitoring.org/) tracking
**Test Plan**
N/A
**Checklist**
> repo-wide: Add monitoring.yml

- packages/a/appstream-data/package.yml
- packages/a/appstream-data/pspec_x86_64.xml
**Summary**
Temporarily removed appstream data for Discover and Gnome Software
**Test Plan**
Built it. Installed it. SC still works.
**Checklist**
> appstream-data: Refresh Appstream Data

- packages/s/s-tui/package.yml
- packages/s/s-tui/pspec_x86_64.xml
**Summary**
- Fix setuptools warning
- Fix for issue
- Fix typos
**Test Plan**
- monitor temps and cpu
**Checklist**
> s-tui: Update to 1.1.6

- packages/m/maxima/package.yml
- packages/m/maxima/pspec_x86_64.xml
- packages/w/wxmaxima/package.yml
- packages/w/wxmaxima/pspec_x86_64.xml
**Summary**
- Make `xmaxima` as subpackage, so other frontend like `wxmaxima` only pull cli component
- Added homepage key to `package.yml` (Part of https://github.com/getsolus/packages/issues/411)
**Test Plan**
- Install maxima, xmaxima, and wxmaxima. Make sure everythinng works.
- Verified added homepage loads relevant informations.
**Checklist**
> maxima: Housekeeping

- packages/w/wine/abi_symbols
- packages/w/wine/abi_symbols32
- packages/w/wine/package.yml
- packages/w/wine/pspec_x86_64.xml
**Summary**
- A number of Input Method improvements.
- Improved Diffie-Hellman key support.
- Better Dvorak keyboard detection.
- Various bug fixes.
- [9.0](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.0)
- [9.1](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.1)
**Test Plan**
- Played Age of Empires 1 Trial
- Used `winefile`, `winecfg`, `wineconsole`, `winemine`
**Checklist**
> wine: Update to 9.1

- packages/w/winetricks/package.yml
- packages/w/winetricks/pspec_x86_64.xml
**Summary**
Commit log available [here](https://github.com/Winetricks/winetricks/compare/20230212...20240105)
**Test Plan**
Installed a couple components into a Wine prefix
**Checklist**
> winetricks: Update to 20240105

- packages/v/visualboyadvance-m/package.yml
- packages/v/visualboyadvance-m/pspec_x86_64.xml
**Summary**
- Remove SDL sound driver
- Fix wav audio recording
- Dialog appearance improvements + link warning
- build: don't `fseeko64()`/`ftello64()` on `musl libc`
- visualboyadvance-m.metainfo.xml: add screenshots to the metainfo
**Test Plan**
Play game
**Checklist**
> visualboyadvance-m: Update to 2.1.9

- packages/h/heroic-games-launcher/package.yml
- packages/h/heroic-games-launcher/pspec_x86_64.xml
**Summary**
Update Heroic to 2.12.1
Fixes some log spam and a few other such small bugs. Full changelog [here](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/compare/v2.11.0...v2.12.1)
**Test Plan**
Launch Heroic. Fiddle with settings, navigate pages, and make sure things check out.
**Checklist**
> heroic-games-launcher: Update to 2.12.1

- packages/p/polylith/files/poly
- packages/p/polylith/package.yml
- packages/p/polylith/pspec_x86_64.xml
**Summary**
Inclusion of poly cmd tool, used to manage projects using the polylith architecture
**Test Plan**
Built installed the ran poly to may sure it entered the interactive interface.
**Checklist**
> polylith: Initial inclusion of polylith tooling

- packages/s/solbuild/package.yml
- packages/s/solbuild/pspec_x86_64.xml
**Summary**
This updates the solbuild homepage to the new GitHub org
**Test Plan**
Checked the package referenced the correct homepage
**Checklist**
> solbuild: Fix homepage

- packages/s/skanpage/package.yml
- packages/s/skanpage/pspec_x86_64.xml
**Summary**
Fix runtime issue
**Checklist**
> skanpage: Add kquickimageeditor runtime dependency

- packages/s/shards/abi_symbols
- packages/s/shards/abi_used_libs
- packages/s/shards/abi_used_symbols
- packages/s/shards/package.yml
- packages/s/shards/pspec_x86_64.xml
**Summary**
- Update `shards`  to 0.17.4
> shards: Update to 0.17.4

- packages/i/isync/abi_used_symbols
- packages/i/isync/package.yml
- packages/i/isync/pspec_x86_64.xml
**Summary**
- add homepage
**Test Plan**
- sync inbox
**Checklist**
> isync: Add homepage

- packages/s/solus-sc/package.yml
- packages/s/solus-sc/pspec_x86_64.xml
**Summary**
Deprecate Skype as it can no longer be supported by third party see getsolus/3rd-party#76
**Test Plan**
- Make sure Skype does not appear in Third Party section.
**Checklist**
> solus-sc: Sync with git

- packages/h/heroic-games-launcher/abi_used_symbols
- packages/h/heroic-games-launcher/package.yml
- packages/h/heroic-games-launcher/pspec_x86_64.xml
**Summary**
Update Heroic to 2.13.0
GOG Changes
* As part of Heroic's new partnership with GOG, buying games from GOG within Heroic will now give Heroic a small commission
* Reworked downloading module
* Add ability to install/uninstall DLCs at any point*
* Add ability to change game language at any point*
* Automatic installation of Windows game dependencies (when provided by GOG)
* Faster downloads and updates for native Linux games
* Beta channel support for Windows games (including password-protected beta channels)
* Version rollback for Windows games
* Add ability to view changelogs on game page
* REDMod integration for Cyberpunk 2077
(*) Works on Linux when installing Windows games, but not for linux builds since it is not supported by GOG.
General Changes
* The library will show a …
> heroic-games-launcher: Update to 2.13.0

- packages/p/pinta/files/0001-use-net8.patch
- packages/p/pinta/files/0002-force-x11-compat.patch
- packages/p/pinta/package.yml
- packages/p/pinta/pspec_x86_64.xml
**Summary**
Fixes the greyed out options in title menu
**Test Plan**
- check menus, painting, and screenshot on an x11 DE
- repeat on Wayland
**Checklist**
> pinta: Title Menu Fix

- packages/a/alglib/abi_used_symbols
- packages/a/alglib/package.yml
- packages/a/alglib/pspec_x86_64.xml
**Summary**
**Test plan**
Installed application.
**Checklist**
> alglib: inclusion of homepage

- packages/e/ebook-tools/abi_libs
- packages/e/ebook-tools/abi_symbols
- packages/e/ebook-tools/abi_used_symbols
- packages/e/ebook-tools/package.yml
- packages/e/ebook-tools/pspec_x86_64.xml
**Summary**
**Test Plan**
Installed application and tested some commands.
**Checklist**
> ebook-tools: inclusion of homepage

- packages/b/broadcom-sta/files/broadcom-sta-current.metainfo.xml
- packages/b/broadcom-sta/files/broadcom-sta-lts.metainfo.xml
- packages/b/broadcom-sta/package.yml
- packages/b/broadcom-sta/pspec_x86_64.xml
**Summary**
- For this driver to show up in G-S/discover
**Test Plan**
- Modaliases show up in xml file
**Checklist**
> broadcom-sta: Add appstream metainfo

- packages/f/font-iosevka-ttf/package.yml
- packages/f/font-iosevka-ttf/pspec_x86_64.xml
**Summary**
- Fix metrics of Cyrillic Yery
- Fix Italic/Upright localization forms for Serbian/Macedonian Cyrillic.
- Add Bosnian Cyrillic localization forms based on Serbian/Macedonian.
- Add italic form for Combining Cyrillic Letter Es-Te (U+2DF5)
- Added new characters
**Test Plan**
**Checklist**
> font-iosevka-ttf: Update to 28.1.0

- packages/c/celestia/package.yml
- packages/c/celestia/pspec_x86_64.xml
> celestia: Install scalable icon

- packages/c/convertall/files/org.bellz.convertall.convertall.metainfo.xml
- packages/c/convertall/package.yml
- packages/c/convertall/pspec_x86_64.xml
**Summary**
- Added appstream metadata (Part of getsolus/packages#1389)
- Install more icon sizes
**Test Plan**
**Checklist**
> convertall: Housekeeping

- packages/k/kamoso/package.yml
- packages/k/kamoso/pspec_x86_64.xml
- packages/k/kasts/package.yml
- packages/k/kasts/pspec_x86_64.xml
- packages/k/kclock/package.yml
- packages/k/kclock/pspec_x86_64.xml
- packages/k/keysmith/package.yml
- packages/k/keysmith/pspec_x86_64.xml
- packages/s/skanpage/package.yml
- packages/s/skanpage/pspec_x86_64.xml
- packages/t/tokodon/package.yml
- packages/t/tokodon/pspec_x86_64.xml
**Summary**
Update some stragglers from 23.08.4 to 23.08.5, have added these to my gear list
**Checklist**
> KDE Gear 23.08.5 (Group 2)

- packages/i/icdiff/package.yml
- packages/i/icdiff/pspec_x86_64.xml
**Summary**
Fixes #1519
**Test Plan**
Installed and used
**Checklist**
> icdiff: Initial commit at 2.0.7

- packages/f/foliate/MAINTAINERS.md
- packages/f/foliate/package.yml
- packages/f/foliate/pspec_x86_64.xml
**Summary**
Add the foliate e-book reader. Its a clean and modern application for reading books that supports multiple file formats.
**Test Plan**
- Launched the application
- Tried opening and reading a few epub, pdf and cbz files
- Tried changing themes, fonts and other settings
- Tried downloading books from the OPDS catalog
**Checklist**
The inclusion of foliate resolves https://github.com/getsolus/packages/issues/1688
> foliate: initial inclusion in the repository

- packages/r/rocksndiamonds/files/rocksndiamonds.metainfo.xml
- packages/r/rocksndiamonds/package.yml
- packages/r/rocksndiamonds/pspec_x86_64.xml
**Summary**
- Install appstream metainfo (Part of getsolus/packages#1389)
- Fix icon
**Test Plan**
**Checklist**
> rocksndiamonds: Add appstream metainfo

- packages/m/mc/abi_used_symbols
- packages/m/mc/package.yml
- packages/m/mc/pspec_x86_64.xml
**Summary**
- Part of [#411](https://github.com/getsolus/packages/issues/411).
**Test Plan**
Installed and browsed some folders.
**Checklist**
> mc: inclusion of homepage

- packages/o/openttd/files/org.openttd.OpenTTD.metainfo.xml
- packages/o/openttd/package.yml
- packages/o/openttd/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> openttd: Add appstream metainfo

- packages/e/easyssh/package.yml
- packages/e/easyssh/pspec_x86_64.xml
**Summary**
**Test plan**
- Installed and made an SSH-connection
**Checklist**
> easyssh: include homepage

- packages/g/gnugo/abi_used_symbols
- packages/g/gnugo/package.yml
- packages/g/gnugo/pspec_x86_64.xml
**Summary**
Added homepage key (Part of getsolus/packages#411)
**Test Plan**
Verified homepage loads relevant information
**Checklist**
> gnugo: Homepage inclusion

- packages/t/taskwarrior/abi_used_symbols
- packages/t/taskwarrior/package.yml
- packages/t/taskwarrior/pspec_x86_64.xml
**Summary**
- Inclusion of "hompage" to package.yml
**Test plan**
- Installed, checked some commands and man pages.
**Check list**
> taskwarrior: include homepage

- packages/o/openspades/abi_used_symbols
- packages/o/openspades/package.yml
- packages/o/openspades/pspec_x86_64.xml
**Summary**
**Test plan**
- Installed and started a game
**Check list**
> openspades: inclusion of homepage

- packages/t/t1utils/abi_libs
- packages/t/t1utils/abi_symbols
- packages/t/t1utils/abi_used_symbols
- packages/t/t1utils/package.yml
- packages/t/t1utils/pspec_x86_64.xml
**Summary**
- Inclusion of "hompage" to package.yml
**Test plan**
- Installed, checked some commands and man pages.
**Check list**
> t1utils: include homepage

- packages/t/totem/package.yml
- packages/t/totem/pspec_x86_64.xml
**Summary**
**Test plan**
- Installed and played a video
**Check list**
> totem: include homepage

- packages/s/sdcv/abi_used_symbols
- packages/s/sdcv/package.yml
- packages/s/sdcv/pspec_x86_64.xml
**Summary**
- add homepage
**Test Plan**
- look up dictionary article
**Checklist**
> sdcv: Add homepage

- packages/p/pidgin/MAINTAINERS.md
- packages/p/pidgin/abi_used_symbols
- packages/p/pidgin/package.yml
- packages/p/pidgin/pspec_x86_64.xml
**Changelog:**
General:
- Bug fixes
Full changelog available [here](https://pidgin.im/posts/)
**Test Plan**
- Launched pidgin
- Verified connection to an existing jabber account, successful message exchange.
**Checklist**
- [ x] Package was built and tested against unstable
> pidgin: Update to 2.14.13

- packages/k/keysmith/package.yml
- packages/k/keysmith/pspec_x86_64.xml
**Summary**
Fixes https://discuss.getsol.us/d/10377-keysmith-dependencies
**Checklist**
> keysmith: Add runtime dependency

- packages/x/x11vnc/package.yml
- packages/x/x11vnc/pspec_x86_64.xml
**Summary**
**Test plan**
- Checked that homepage was added correctly 
**Check list**
> x11vnc: include homepage

- packages/l/lftp/package.yml
- packages/l/lftp/pspec_x86_64.xml
**Summary**
**Test plan**
- Checked that homepage was added correctly 
**Check list**
> lftp: include homepage

- packages/py/pysolfc/files/io.sourceforge.pysolfc.PySolFC.appdata.xml
- packages/py/pysolfc/package.yml
- packages/py/pysolfc/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> pysolfc: Add appstream metadata

- packages/c/cef-minimal/package.yml
- packages/c/cef-minimal/pspec_x86_64.xml
**Summary**
**Test plan**
**Checklist**
> cef-minimal: include homepage

- packages/k/krita/files/AppData.patch
- packages/k/krita/package.yml
- packages/k/krita/pspec_x86_64.xml
**Summary**
Add patch for metainfo so appstream generation succeed
> krita: Add patch for metainfo

- packages/w/wxmaxima/abi_used_symbols
- packages/w/wxmaxima/package.yml
- packages/w/wxmaxima/pspec_x86_64.xml
**Summary**
- Set maxima's `LANG` variable, not wxMaxima's `LANG`
- Sped up the communication between maxima and wxMaxima
- Sometimes newlines in misc text from maxima got lost
**Test Plan**
Open example files
**Checklist**
> wxmaxima: Update to 24.02.2

- packages/f/fb2converter/package.yml
- packages/f/fb2converter/pspec_x86_64.xml
**Summary**
- set TERM env variable
**Test Plan**
- The error is reproducible on build server
**Checklist**
> fb2converter: Fix build server failure

- packages/a/avr-binutils/abi_used_libs
- packages/a/avr-binutils/abi_used_symbols
- packages/a/avr-binutils/package.yml
- packages/a/avr-binutils/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> avr-binutils: include homepage

- packages/a/avr-libc/package.yml
- packages/a/avr-libc/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> avr-libc: include homepage

- packages/m/mu/package.yml
- packages/m/mu/pspec_x86_64.xml
**Summary**
- ensure CLD2 is actually used
- insist --maildir is absolute
- tweak mu4e-compose
- add 'display-buffer option for mu4e-compose-switch
- fix typos, update mu4e documentation
**Test Plan**
- search and view message
**Checklist**
> mu: Update to 1.12.1

- packages/g/guake/package.yml
- packages/g/guake/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> guake: include homepage

- packages/i/iptables/abi_used_symbols
- packages/i/iptables/abi_used_symbols32
- packages/i/iptables/package.yml
- packages/i/iptables/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> iptables: include homepage

- packages/n/nmap/package.yml
- packages/n/nmap/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> nmap: include homepage

- packages/py/pyaudio/package.yml
- packages/py/pyaudio/pspec_x86_64.xml
**Summary**
- PyAudio 0.2.14 is a new release that fixes a build issue.
**Test plan**
- Verified that it installed correctly.
**Checklist**
> pyaudio: update to 0.2.14

- packages/q/qutebrowser/MAINTAINERS.md
- packages/q/qutebrowser/package.yml
- packages/q/qutebrowser/pspec_x86_64.xml
**Summary**
- Added rundeps for pygments
- Added MAINTAINERS.md
**Test plan**
- Checked that the new dependency got installed
**Check list**
> qutebrowser: added new rundeps

- packages/q/quassel/abi_libs
- packages/q/quassel/abi_symbols
- packages/q/quassel/package.yml
- packages/q/quassel/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> quassel: include homepage

- packages/w/wlroots/abi_used_symbols
- packages/w/wlroots/monitoring.yml
- packages/w/wlroots/package.yml
- packages/w/wlroots/pspec_x86_64.xml
**Changelog**
- [0.17.2](https://gitlab.freedesktop.org/wlroots/wlroots/-/tags/0.17.2)
**Test plan**
- Run rev-dep applications: sway, gamescope, labwc
**Checklist**
> wlroots: Update to 0.17.2

- packages/m/mosh/abi_used_symbols
- packages/m/mosh/package.yml
- packages/m/mosh/pspec_x86_64.xml
**Summary**
- Part of #411
**Test plan**
**Check list**
> mosh: include homepage

- packages/i/ipcalc/MAINTAINERS.md
- packages/i/ipcalc/package.yml
- packages/i/ipcalc/pspec_x86_64.xml
**Summary**
- Fixes https://github.com/getsolus/packages/issues/1843
**Test plan**
- Installed and did some IP calculations.
**Check list**
> ipcalc: initial inclusion at 0.51

- packages/l/labwc/MAINTAINERS.md
- packages/l/labwc/abi_used_libs
- packages/l/labwc/abi_used_symbols
- packages/l/labwc/package.yml
- packages/l/labwc/pspec_x86_64.xml
**Summary**
Enhancements:
- add rundeps
- [0.7.1](https://github.com/labwc/labwc/releases/tag/0.7.1)
**Test Plan**
It was updated, and it loads the previous configuration with zero issues
**Checklist**
> labwc: update to 0.7.1

- packages/h/hunspell-en/package.yml
- packages/h/hunspell-en/pspec_x86_64.xml
**Summary**
**Test plan**
- Installed and loaded in LibreOffice
**Check list**
> hunspell-en: update to 2020.12.07

- packages/y/yarn/monitoring.yml
- packages/y/yarn/package.yml
- packages/y/yarn/pspec_x86_64.xml
**Summary**
- [1.22.22](https://github.com/yarnpkg/yarn/releases/tag/v1.22.22)
- [1.22.21](https://github.com/yarnpkg/yarn/releases/tag/v1.22.21)
- [1.22.20](https://github.com/yarnpkg/yarn/releases/tag/v1.22.20)
**Test Plan**
- Build the help center site locally
**Checklist**
> yarn: Update to 1.22.22

- packages/h/hunspell-de/package.yml
- packages/h/hunspell-de/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> hunspell-de: include homepage

- packages/h/hunspell-da/package.yml
- packages/h/hunspell-da/pspec_x86_64.xml
**Summary**
- Fixed licenses
**Test plan**
- Installed and loaded in LibreOffice
**Check list**
> hunspell-da: update to 2.8

- packages/l/linux-current/files/cmdline
- packages/l/linux-lts/files/cmdline
**Summary**
Resolves #1602
**Test Plan**
N/A
**Checklist**
- [] Package was built and tested against unstable n/a
> Don't hide systemd status

- packages/h/hunspell-el/package.yml
- packages/h/hunspell-el/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> hunspell-el: include homepage

- packages/h/haruna/abi_used_symbols
- packages/h/haruna/package.yml
- packages/h/haruna/pspec_x86_64.xml
**Summary**
Bugfix release:
* Hiding/showing Playlist toolbar setting
* Track sub-menus in Audio and Subtiles global menus being empty
* Freeze when opening HamburgerMenu
**Test Plan**
Played a few sample videos and used some of the video/audio alteration functions
**Checklist**
> haruna: Update to 1.0.2

- packages/c/cubeb/abi_used_symbols
- packages/c/cubeb/package.yml
- packages/c/cubeb/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cubeb: Add homepage

- packages/c/cuppa/MAINTAINERS.md
- packages/c/cuppa/abi_used_symbols
- packages/c/cuppa/package.yml
- packages/c/cuppa/pspec_x86_64.xml
**Summary**
- Sync source to latest commit
**Test Plan**
**Checklist**
> cuppa: Sync with git

- packages/c/cups-pk-helper/abi_used_symbols
- packages/c/cups-pk-helper/monitoring.yml
- packages/c/cups-pk-helper/package.yml
- packages/c/cups-pk-helper/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cups-pk-helper: Housekeeping

- packages/w/warpinator/MAINTAINERS.md
- packages/w/warpinator/files/fix-launch-script-path.patch
- packages/w/warpinator/monitoring.yml
- packages/w/warpinator/package.yml
- packages/w/warpinator/pspec_x86_64.xml
**Summary**
- Add warpinator at 1.8.3
- Resolves getsolus/packages#1863
**Test Plan**
Transfer and recieve files from phone
**Checklist**
> warpinator: Add at 1.8.3

- packages/d/dcraw/abi_used_symbols
- packages/d/dcraw/package.yml
- packages/d/dcraw/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> dcraw: Add homepage

- packages/d/dconf/abi_used_symbols
- packages/d/dconf/abi_used_symbols32
- packages/d/dconf/package.yml
- packages/d/dconf/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> dconf: Add homepage

- packages/py/pycangjie/package.yml
- packages/py/pycangjie/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> pycangjie: include homepage

- packages/py/pycanberra/package.yml
- packages/py/pycanberra/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> pycanberra: include homepage

- packages/x/xtitle/package.yml
- packages/x/xtitle/pspec_x86_64.xml
**Summary**
- Fixed license
**Test plan**
**Check list**
> xtitle: include homepage

- packages/f/fio/abi_symbols
- packages/f/fio/package.yml
- packages/f/fio/pspec_x86_64.xml
**Summary**
- Bugfix release
- [changelog](https://github.com/axboe/fio/compare/fio-3.36...fio-3.37)
**Test Plan**
- fio read.ini | grep READ | awk '{print $2}'
- fio write.ini | grep WRITE | awk '{print $2}'
**Checklist**
> fio: Update to 3.37

- packages/d/dmg2img/monitoring.yml
- packages/d/dmg2img/package.yml
- packages/d/dmg2img/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> dmg2img: Housekeeping

- packages/c/cython/monitoring.yml
- packages/c/cython/package.yml
- packages/c/cython/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cython: Housekeeping

- packages/d/dbus/abi_used_symbols
- packages/d/dbus/abi_used_symbols32
- packages/d/dbus/package.yml
- packages/d/dbus/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> dbus: Add homepage

- packages/d/dejavu-fonts-ttf/package.yml
- packages/d/dejavu-fonts-ttf/pspec_x86_64.xml
**Summary**
- Correct the license key
**Test Plan**
**Checklist**
> dejavu-fonts-ttf: Housekeeping

- packages/d/dmz-cursor-theme/monitoring.yml
- packages/d/dmz-cursor-theme/package.yml
- packages/d/dmz-cursor-theme/pspec_x86_64.xml
**Summary**
- No upstream changelog
**Test Plan**
- Install and use cursor (Tested on GNOME-Wayland)
**Checklist**
> dmz-cursor-theme: Update to 0.4.5.1

- packages/d/docbook-xml/monitoring.yml
- packages/d/docbook-xml/package.yml
- packages/d/docbook-xml/pspec_x86_64.xml
**Summary**
- Add `homepage` key to `package.yml` (Part of https://github.com/getsolus/packages/issues/411)
**Test Plan**
**Checklist**
> docbook-xml: Housekeeping

- packages/p/powerlevel10k/MAINTAINERS.md
- packages/p/powerlevel10k/package.yml
- packages/p/powerlevel10k/pspec_x86_64.xml
**Summary**
Add the powerlevel10k package
**Changelog:**
Bug fixes and improvements.
Full release notes available [here](https://github.com/romkatv/powerlevel10k/releases)
**Test Plan**
- Added powerline10k as a zsh style in zpreztorc. Started a new zsh terminal session and configured the prompt. Verified prompt displayed correctly.
**Checklist**
Resolves #1959
> powerlevel10k: Add at 1.20.0

- packages/d/docker-buildx/package.yml
- packages/d/docker-buildx/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> docker-buildx: Add homepage

- packages/d/docker-compose/package.yml
- packages/d/docker-compose/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> docker-compose: Add homepage

- packages/h/hunspell-fr/package.yml
- packages/h/hunspell-fr/pspec_x86_64.xml
**Summary**
- Changed to new source
**Test plan**
- Installed and loaded in Libre Office to verify the new source
**Check list**
> hunspell-fr: include homepage

- packages/h/hunspell-nl/package.yml
- packages/h/hunspell-nl/pspec_x86_64.xml
**Summary**
**Test plan**
- Loaded in Libre Office and did some spell checking.
**Check list**
> hunspell-nl: update to 2.20.19

- packages/h/hunspell-pl/package.yml
- packages/h/hunspell-pl/pspec_x86_64.xml
**Summary**
**Test plan**
- Loaded in Libre Office and did some spell checking.
**Check list**
> hunspell-pl: update to 20240301

- packages/h/hunspell-sr/package.yml
- packages/h/hunspell-sr/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> hunspell-sr: include homepage

- packages/h/haskell-base16-bytestring/package.yml
- packages/h/haskell-base16-bytestring/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> haskell-base16-bytestring: include homepage

- packages/h/hunspell-id/package.yml
- packages/h/hunspell-id/pspec_x86_64.xml
**Summary**
- Fixed license
**Test plan**
**Check list**
> hunspell-id: include homepage

- common/Scripts/worklog.py
**Summary**
Add an HTML output format to help the creation of update notes.
**Test Plan**
```
./common/Scripts/worklog.py builds "1 day ago" --format=html
./common/Scripts/worklog.py updates "1 day ago" --format=html
./common/Scripts/worklog.py commits "1 day ago" --format=html
```
**Checklist**
> worklog.py: Add `html` output format

- packages/d/dfc/monitoring.yml
- packages/d/dfc/package.yml
- packages/d/dfc/pspec_x86_64.xml
**Summary**
- Add `homepage` key to `package.yml` (Part of #411)
**Test Plan**
**Checklist**
> dfc: Housekeeping

- packages/d/dia/abi_used_symbols
- packages/d/dia/files/org.gnome.wiki.dia.metainfo.xml
- packages/d/dia/package.yml
- packages/d/dia/pspec_x86_64.xml
**Summary**
**Test Plan**
- Verify metainfo with `appstream-builder --packages-dir=. --include-failed -v`
**Checklist**
> dia: Housekeeping

- packages/u/util-macros/package.yml
- packages/u/util-macros/pspec_x86_64.xml
**Summary**
**Test plan**
**Check list**
> util-macros: include homepage

- packages/x/xfce4-desktop-branding/package.yml
- packages/x/xfce4-desktop-branding/pspec_x86_64.xml
- packages/x/xfce4-panel/files/0001-Use-Solus-defaults.patch
- packages/x/xfce4-panel/package.yml
- packages/x/xfce4-panel/pspec_x86_64.xml
- packages/x/xfce4-settings/files/0001-Use-Solus-defaults.patch
- packages/x/xfce4-settings/package.yml
- packages/x/xfce4-settings/pspec_x86_64.xml
**Summary**
- **xfce4-desktop-branding: Add dependency on sound-theme-freedesktop**
- **xfce4-settings: Set sound theme by default**
- **xfce4-panel: Enable playing sound on volume change**
Fixes #1801 
**Test Plan**
Create a new user and change the volume using the keyboard; hear sound play.
**Checklist**
> Fix sounds in XFCE4

- packages/d/docbook2x/abi_used_symbols
- packages/d/docbook2x/monitoring.yml
- packages/d/docbook2x/package.yml
- packages/d/docbook2x/pspec_x86_64.xml
**Summary**
- Add `homepage` key to `package.yml` (Part of #411)
**Test Plan**
**Checklist**
> docbook2x: Housekeeping

- packages/q/qogir-icon-theme/package.yml
- packages/q/qogir-icon-theme/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked that homepage was added.
**Checklist**
> qogir-icon-theme: include homepage

- packages/q/qgit/package.yml
- packages/q/qgit/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> qgit: include homepage

- packages/q/qca/package.yml
- packages/q/qca/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked homepage was added correctly
**Checklist**
> qca: include homepage

- packages/d/drawing/monitoring.yml
- packages/d/drawing/package.yml
- packages/d/drawing/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> drawing: Housekeeping

- packages/g/gnucash/abi_symbols
- packages/g/gnucash/abi_used_symbols
- packages/g/gnucash/monitoring.yml
- packages/g/gnucash/package.yml
- packages/g/gnucash/pspec_x86_64.xml
**Summary**
- Release note can be found [here](https://github.com/Gnucash/gnucash/releases/tag/5.6)
**Test Plan**
Open existing file
**Checklist**
> gnucash: Update to 5.6

- packages/c/cryptomator/package.yml
- packages/c/cryptomator/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked that homepage was added.
**Checklist**
> cryptomator: include homepage

- packages/f/font-iosevka-ttf/package.yml
- packages/f/font-iosevka-ttf/pspec_x86_64.xml
**Summary**
- Fix side bearings of multi-dot punctuation (U+10FB, U+2056, U+2058..205B, U+2E2A..U+2E2D) under Quasi-Proportional
- Fix mapping of DENSE VERTICAL FILL (U+1CC44) and DENSE HORIZONTAL FILL (U+1CC45)
- Fix glyph visuals
- Add characters
- [changelog](https://raw.githubusercontent.com/be5invis/Iosevka/v29.0.5/CHANGELOG.md)
**Test Plan**
**Checklist**
> font-iosevka-ttf: Update to 29.0.5

- packages/d/docker/package.yml
- packages/d/docker/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> docker: Add homepage

- packages/d/devilspie2/package.yml
- packages/d/devilspie2/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> devilspie2: include homepage

- packages/q/quadrapassel/package.yml
- packages/q/quadrapassel/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> quadrapassel: include homepage

- packages/d/dosfstools/monitoring.yml
- packages/d/dosfstools/package.yml
- packages/d/dosfstools/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> dosfstools: Housekeeping

- packages/d/dotconf/monitoring.yml
- packages/d/dotconf/package.yml
- packages/d/dotconf/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> dotconf: Housekeeping

- packages/q/qqwing/abi_used_symbols
- packages/q/qqwing/package.yml
- packages/q/qqwing/pspec_x86_64.xml
**Summary**
- Removed %configure as it would not build with that
**Test Plan**
- Started and created a game
**Checklist**
> qqwing: include homepage

- packages/d/dfu-programmer/abi_used_symbols
- packages/d/dfu-programmer/package.yml
- packages/d/dfu-programmer/pspec_x86_64.xml
**Summary**
- Add --erase-first option
- Fix missing update-bash-completion.sh
- Fix missing header files
**Test Plan**
- Installed and checked that the commands worked, not tested against real hardware.
**Checklist**
> dfu-programmer: update to 1.1.0

- packages/c/coreutils/package.yml
- packages/c/coreutils/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> coreutils: include homepage

- packages/e/expect/package.yml
- packages/e/expect/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> expect: include homepage

- packages/e/exo/package.yml
- packages/e/exo/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> exo: include homepage

- packages/e/evopop-icon-theme/package.yml
- packages/e/evopop-icon-theme/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> evopop-icon-theme: include homepage

- packages/d/docopt-cpp/abi_used_symbols
- packages/d/docopt-cpp/monitoring.yml
- packages/d/docopt-cpp/package.yml
- packages/d/docopt-cpp/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> docopt-cpp: Housekeeping

- packages/q/qomui/package.yml
- packages/q/qomui/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> qomui: include homepage

- packages/e/enca/package.yml
- packages/e/enca/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> enca: include homepage

- packages/g/gdl/abi_symbols
- packages/g/gdl/abi_used_symbols
- packages/g/gdl/package.yml
- packages/g/gdl/pspec_x86_64.xml
**Summary**
- Changed license
**Test Plan**
- Checked that homepage was added.
**Checklist**
> gdl: include homepage

- packages/g/gcolor3/package.yml
- packages/g/gcolor3/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gcolor3: include homepage

- packages/g/gengetopt/abi_used_symbols
- packages/g/gengetopt/package.yml
- packages/g/gengetopt/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gengetopt: include homepage

- packages/g/geany-themes/package.yml
- packages/g/geany-themes/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> geany-themes: include homepage

- packages/f/faba-icon-theme-mono/package.yml
- packages/f/faba-icon-theme-mono/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> faba-icon-theme-mono: Add homepage

- packages/f/faba-icon-theme/package.yml
- packages/f/faba-icon-theme/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> faba-icon-theme: Add homepage

- packages/k/keybase/monitoring.yml
- packages/k/keybase/package.yml
- packages/k/keybase/pspec_x86_64.xml
**Summary**
- Resolves getsolus/packages#2177
**Test Plan**
Launch the app succsesfully from terminal and desktop
**Checklist**
> keybase: Set correct permission for run_keybase

- packages/p/polylith/MAINTAINERS.md
- packages/p/polylith/package.yml
- packages/p/polylith/pspec_x86_64.xml
**Summary**
Update to latest release
Changelog available [here](https://github.com/polyfy/polylith/releases/tag/v0.2.19)
**Test Plan**
Built and installed locally, ran poly version to check new version is returned.
**Checklist**
> polylith: Update to version 0.2.19

- packages/e/efibootmgr/abi_used_symbols
- packages/e/efibootmgr/package.yml
- packages/e/efibootmgr/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> efibootmgr: include homepage

- packages/e/eiskaltdcpp/abi_used_symbols
- packages/e/eiskaltdcpp/package.yml
- packages/e/eiskaltdcpp/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> eiskaltdcpp: include homepage

- packages/e/egl-wayland/abi_used_symbols
- packages/e/egl-wayland/package.yml
- packages/e/egl-wayland/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> egl-wayland: include homepage

- packages/e/enblend-enfuse/abi_used_symbols
- packages/e/enblend-enfuse/package.yml
- packages/e/enblend-enfuse/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> enblend-enfuse: include homepage

- packages/f/f2fs-tools/monitoring.yml
- packages/f/f2fs-tools/package.yml
- packages/f/f2fs-tools/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> f2fs-tools: Housekeeping

- packages/g/glava/package.yml
- packages/g/glava/pspec_x86_64.xml
**Summary**
- Change source
**Test Plan**
- Checked it built with new source
**Checklist**
> glava: include homepage

- packages/f/fcgi/abi_used_symbols
- packages/f/fcgi/monitoring.yml
- packages/f/fcgi/package.yml
- packages/f/fcgi/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> fcgi: Housekeeping

- packages/g/glew110/package.yml
- packages/g/glew110/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> glew110: include homepage

- packages/g/glpk/package.yml
- packages/g/glpk/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> glpk: include homepage

- packages/g/gmusicbrowser/package.yml
- packages/g/gmusicbrowser/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gmusicbrowser: include homepage

- packages/g/global/abi_symbols
- packages/g/global/abi_used_symbols
- packages/g/global/package.yml
- packages/g/global/pspec_x86_64.xml
**Summary**
- Release notes can be found [here](https://lists.gnu.org/archive/html/info-global/2024-03/msg00000.html).
**Test Plan**
- Installed, created tags.
**Checklist**
> global: update to 6.6.12

- packages/g/glew/package.yml
- packages/g/glew/pspec_x86_64.xml
**Summary**
- Include homepage to package.yml
**Test Plan**
**Checklist**
> glew: include homepage

- packages/g/go-md2man/package.yml
- packages/g/go-md2man/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> go-md2man: include homepage

- packages/s/solaar/package.yml
- packages/s/solaar/pspec_x86_64.xml
**Summary**
Not every user wants this to automatically start
**Test Plan**
Confirmed autostart file no longer exists
**Checklist**
> solaar: Remove autostart file

- packages/m/megaglest/files/megaglest-fix-lua-version-ordering.patch
- packages/m/megaglest/package.yml
- packages/m/megaglest/pspec_x86_64.xml
**Summary**
- Build with Lua 5.4
**Test Plan**
Play through the first tutorial mission.
**Checklist**
> megaglest: Build with Lua 5.4

- packages/g/gob2/abi_used_symbols
- packages/g/gob2/package.yml
- packages/g/gob2/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gob2: include homepage

- packages/s/starship/monitoring.yml
- packages/s/starship/package.yml
- packages/s/starship/pspec_x86_64.xml
**Summary**
- Replace all remaining paths referring to vuepress
- replace unmaintained crates `yaml-rust`, `dirs-next`
**Test Plan**
Open a new shell, and navigate to different folders, including git repositories.
**Checklist**
> starship: Update to 1.18.2

- packages/f/filezilla/abi_used_symbols
- packages/f/filezilla/monitoring.yml
- packages/f/filezilla/package.yml
- packages/f/filezilla/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> filezilla: Housekeeping

- packages/f/fifechan/MAINTAINERS.md
- packages/f/fifechan/abi_used_symbols
- packages/f/fifechan/monitoring.yml
- packages/f/fifechan/package.yml
- packages/f/fifechan/pspec_x86_64.xml
**Summary**
- Add monitroing.yml
**Test Plan**
**Checklist**
> fifechan: Housekeeping

- packages/g/gpart/abi_used_symbols
- packages/g/gpart/package.yml
- packages/g/gpart/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gpart: include homepage

- common/iso_packages.txt
**Summary**
Update the ISO package list following the sync on 04/13/2024.
**Test Plan**
n/a
**Checklist**
> common: Update ISO packages list

- packages/f/flacon/abi_used_symbols
- packages/f/flacon/monitoring.yml
- packages/f/flacon/package.yml
- packages/f/flacon/pspec_x86_64.xml
**Summary**
- Full changelog can be found [here](https://flacon.github.io/changelog/)
**Test Plan**
- Launch the app
**Checklist**
> flacon: Update to 11.3.0

- packages/g/grep/abi_used_symbols
- packages/g/grep/package.yml
- packages/g/grep/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> grep: include homepage

- packages/g/grantlee/package.yml
- packages/g/grantlee/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> grantlee: include homepage

- packages/g/gsm/package.yml
- packages/g/gsm/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gsm: include homepage

- packages/g/gsound/package.yml
- packages/g/gsound/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gsound: include homepage

- packages/g/gtkspellmm/package.yml
- packages/g/gtkspellmm/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gtkspellmm: include homepage

- packages/t/tailscale/package.yml
- packages/t/tailscale/pspec_x86_64.xml
**Summary**
- bugfix release
- [changelog](https://tailscale.com/changelog)
**Test Plan**
**Checklist**
> tailscale: Update to 1.64.2

- packages/i/i3/abi_used_symbols
- packages/i/i3/package.yml
- packages/i/i3/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> i3: include homepage

- packages/g/group-service/abi_used_symbols
- packages/g/group-service/package.yml
- packages/g/group-service/pspec_x86_64.xml
**Summary**
- Initial deb-package support
- Fix Function does not take positional arguments
**Test Plan**
- Installed and started systemd service.
**Checklist**
> group-service: update to 1.4.0

- packages/g/gtkhtml/package.yml
- packages/g/gtkhtml/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gtkhtml: include homepage

- packages/g/gtksourceviewmm/package.yml
- packages/g/gtksourceviewmm/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gtksourceviewmm: include homepage

- packages/g/gtkspell/package.yml
- packages/g/gtkspell/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gtkspell: include homepage

- packages/g/gucharmap/abi_used_symbols
- packages/g/gucharmap/package.yml
- packages/g/gucharmap/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gucharmap: include homepage

- packages/g/gtk-sharp/package.yml
- packages/g/gtk-sharp/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gtk-sharp: include homepage

- packages/g/gtypist/abi_used_symbols
- packages/g/gtypist/package.yml
- packages/g/gtypist/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gtypist: include homepage

- packages/g/gts/package.yml
- packages/g/gts/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gts: include homepage

- packages/g/gnome-mime-data/package.yml
- packages/g/gnome-mime-data/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gnome-mime-data: include homepage

- packages/g/gweled/package.yml
- packages/g/gweled/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gweled: include homepage

- packages/g/gnome-multi-writer/package.yml
- packages/g/gnome-multi-writer/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gnome-multi-writer: include homepage

- packages/i/i3status/abi_used_symbols
- packages/i/i3status/package.yml
- packages/i/i3status/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> i3status: include homepage

- packages/i/i3-style/abi_used_symbols
- packages/i/i3-style/package.yml
- packages/i/i3-style/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> i3-style: include homepage

- packages/i/icoutils/abi_libs
- packages/i/icoutils/abi_symbols
- packages/i/icoutils/abi_used_symbols
- packages/i/icoutils/package.yml
- packages/i/icoutils/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> icoutils: include homepage

- packages/i/ideviceinstaller/package.yml
- packages/i/ideviceinstaller/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> ideviceinstaller: include homepage

- packages/i/ifuse/package.yml
- packages/i/ifuse/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> ifuse: include homepage

- packages/i/igsc/package.yml
- packages/i/igsc/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> igsc: include homepage

- packages/i/intltool/package.yml
- packages/i/intltool/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> intltool: include homepage

- packages/i/inih/abi_used_symbols
- packages/i/inih/abi_used_symbols32
- packages/i/inih/package.yml
- packages/i/inih/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> inih: include homepage

- packages/g/gnome-icon-theme/package.yml
- packages/g/gnome-icon-theme/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gnome-icon-theme: include homepage

- packages/g/gnome-epub-thumbnailer/package.yml
- packages/g/gnome-epub-thumbnailer/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gnome-epub-thumbnailer: include homepage

- packages/i/intel-undervolt/abi_libs
- packages/i/intel-undervolt/abi_symbols
- packages/i/intel-undervolt/abi_used_symbols
- packages/i/intel-undervolt/package.yml
- packages/i/intel-undervolt/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> intel-undervolt: include homepage

- packages/py/python-pyrate-limiter/monitoring.yml
- packages/py/python-pyrate-limiter/package.yml
- packages/py/python-pyrate-limiter/pspec_x86_64.xml
**Summary**
Release notes:
- [3.0.0](https://github.com/vutran1710/PyrateLimiter/releases/tag/v3.0.0)
- [3.0.2](https://github.com/vutran1710/PyrateLimiter/releases/tag/v3.0.2)
- [3.1.0](https://github.com/vutran1710/PyrateLimiter/releases/tag/v3.1.0)
- [3.1.1](https://github.com/vutran1710/PyrateLimiter/releases/tag/v3.1.1)
- [3.2.0](https://github.com/vutran1710/PyrateLimiter/releases/tag/v3.2.0)
- [3.2.1](https://github.com/vutran1710/PyrateLimiter/releases/tag/v3.2.1)
- [3.3.0](https://github.com/vutran1710/PyrateLimiter/releases/tag/v3.3.0)
- [3.4.0](https://github.com/vutran1710/PyrateLimiter/releases/tag/v3.4.0)
- [3.4.1](https://github.com/vutran1710/PyrateLimiter/releases/tag/v3.4.1)
- [3.5.0](https://github.com/vutran1710/PyrateLimiter/releases/tag/v3.5.0)
- …
> python-pyrate-limiter: Update to 3.6.0 and add monitoring.yml

- packages/i/imap/package.yml
- packages/i/imap/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> imap: include homepage

- packages/a/aisleriot/abi_used_symbols
- packages/a/aisleriot/files/0001-Rename-non-latin1-files.patch
- packages/a/aisleriot/monitoring.yml
- packages/a/aisleriot/package.yml
- packages/a/aisleriot/pspec_x86_64.xml
**Summary**
Full commit log available [here](https://gitlab.gnome.org/GNOME/aisleriot/-/compare/3.22.30...3.22.32)
**Test Plan**
Played a few games of Klondike
**Checklist**
> aisleriot: Update to 3.22.32 and add monitoring.yml

- packages/g/gnome-screenshot/abi_used_symbols
- packages/g/gnome-screenshot/package.yml
- packages/g/gnome-screenshot/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gnome-screenshot: include homepage

- packages/i/icon-naming-utils/package.yml
- packages/i/icon-naming-utils/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> icon-naming-utils: include homepage

- packages/i/isl/package.yml
- packages/i/isl/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> isl: include homepage

- packages/i/iw/abi_used_symbols
- packages/i/iw/package.yml
- packages/i/iw/pspec_x86_64.xml
**Summary**
- Update to 6.7
**Test Plan**
- Installed checked commands ran.
**Checklist**
> iw: update to 6.7

- packages/k/keychain/package.yml
- packages/k/keychain/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> keychain: include homepage

- packages/k/keyutils/abi_used_symbols
- packages/k/keyutils/package.yml
- packages/k/keyutils/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> keyutils: include homepage

- packages/k/keybinder/abi_used_symbols
- packages/k/keybinder/package.yml
- packages/k/keybinder/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> keybinder: include homepage

- packages/g/gnome-tetravex/abi_used_libs
- packages/g/gnome-tetravex/abi_used_symbols
- packages/g/gnome-tetravex/files/20.patch
- packages/g/gnome-tetravex/package.yml
- packages/g/gnome-tetravex/pspec_x86_64.xml
**Summary**
- Add homepage to packaging.yml
- Added new patch to fix build errors.
**Test Plan**
**Checklist**
> gnome-tetravex: include homepage

- packages/f/font-iosevka-ttf/package.yml
- packages/f/font-iosevka-ttf/pspec_x86_64.xml
**Summary**
- Refine shape of U+1CC09, U+1CC0A, U+1CC10 and U+1CC11
- Refine terminal shape of Schwa and Reversed Lower E under italics
- Make CYRILLIC CAPITAL LETTER SHHA follow variants of Capital H
- [changelog](https://raw.githubusercontent.com/be5invis/Iosevka/v29.2.1/CHANGELOG.md)
**Test Plan**
**Checklist**
> font-iosevka-ttf: Update to 29.2.1

- packages/g/g4music/abi_used_symbols
- packages/g/g4music/package.yml
- packages/g/g4music/pspec_x86_64.xml
**Summary**
- Update current item when items changed.
- Free memory when music be removed.
- Add translation: Georgian, Hindi.
- Update translation: Spanish, Slovenian.
**Test Plan**
Play an album : Self-titled album of Oh Wonder
**Checklist**
> g4music: Update to 3.5.2

- packages/k/kuserfeedback/package.yml
- packages/k/kuserfeedback/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> kuserfeedback: include homepage

- packages/k/kpeoplevcard/abi_symbols
- packages/k/kpeoplevcard/package.yml
- packages/k/kpeoplevcard/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> kpeoplevcard: include homepage

- packages/k/kio-fuse/package.yml
- packages/k/kio-fuse/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> kio-fuse: include homepage

- packages/g/gnome-themes-extra/package.yml
- packages/g/gnome-themes-extra/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gnome-themes-extra: include homepage

- packages/i/intel-microcode/package.yml
- packages/i/intel-microcode/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> intel-microcode: include homepage

- packages/q/qt5ct/monitoring.yml
- packages/q/qt5ct/package.yml
- packages/q/qt5ct/pspec_x86_64.xml
**Summary**
- Switch `qt5-svg` from builddeps to rundeps per [documentation](https://sourceforge.net/p/qt5ct/code/HEAD/tree/trunk/qt5ct/)
**Test Plan**
Set theme on Qt5 app (Citra)
**Checklist**
> qt5ct: Housekeeping

- packages/g/gnome-vfs/abi_used_symbols
- packages/g/gnome-vfs/package.yml
- packages/g/gnome-vfs/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> gnome-vfs: include homepage

- packages/s/svtplay-dl/monitoring.yml
**Summary**
**Test Plan**
- Checked file was added.
**Checklist**
> svtplay-dl: include monitoring.yml

- packages/g/gum/package.yml
- packages/g/gum/pspec_x86_64.xml
**Summary**
Changelog available [here](https://github.com/charmbracelet/gum/releases/tag/v0.14.0)
**Test Plan**
Tested out some gum functions
**Checklist**
> gum: Update to 0.14.0

- packages/d/diffoscope/monitoring.yml
- packages/d/diffoscope/package.yml
- packages/d/diffoscope/pspec_x86_64.xml
- packages/py/python-libarchive-c/monitoring.yml
- packages/py/python-libarchive-c/package.yml
- packages/py/python-libarchive-c/pspec_x86_64.xml
**Summary**
- Add diffoscope at 264 (Resolves #2247 )
- Add python-libarchive-c at 5.1
> Add diffoscope

- packages/b/budgie-backgrounds/monitoring.yml
- packages/b/budgie-desktop-view/monitoring.yml
- packages/b/budgie-desktop/monitoring.yml
- packages/b/budgie-extras/monitoring.yml
- packages/b/budgie-screensaver/monitoring.yml
- packages/b/budgie-session/monitoring.yml
- packages/m/magpie/monitoring.yml
**Summary**
Add `monitoring.yml` to Budgie packages
- **budgie-desktop: Add monitoring.yml**
- **budgie-desktop-view: Add monitoring.yml**
- **budgie-session: Add monitoring.yml**
- **magpie: Add monitoring.yml**
- **budgie-screensaver: Add monitoring.yml**
- **budgie-extras: Add monitoring.yml**
- **budgie-backgrounds: Add monitoring.yml**
**Test Plan**
n/a
**Checklist**
> Budgie housekeeping

- packages/f/fontcustom/package.yml
- packages/f/fontcustom/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> fontcustom: Add homepage

- packages/f/font-adobe-75dpi/monitoring.yml
- packages/f/font-adobe-75dpi/package.yml
- packages/f/font-adobe-75dpi/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> font-adobe-75dpi: Add homepage

- packages/f/font-adobe-100dpi/monitoring.yml
- packages/f/font-adobe-100dpi/package.yml
- packages/f/font-adobe-100dpi/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> font-adobe-100dpi: Add homepage

- packages/f/fluid-soundfont/monitoring.yml
- packages/f/fluid-soundfont/package.yml
- packages/f/fluid-soundfont/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> fluid-soundfont: Add homepage

- packages/f/foma/package.yml
- packages/f/foma/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> foma: Add homepage

- packages/i/iksemel/package.yml
- packages/i/iksemel/pspec_x86_64.xml
**Summary**
- Resolves #2263.
**Test Plan**
- Verify pip3 check is now happy
**Checklist**
> iksemel: Include python metadata

- packages/f/font-iosevka-ttf/package.yml
- packages/f/font-iosevka-ttf/pspec_x86_64.xml
**Summary**
- Added characters and other improvements
- [changelog](https://raw.githubusercontent.com/be5invis/Iosevka/v30.0.0/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**
> font-iosevka-ttf: Update to 30.0.0

- packages/f/font-droid-ttf/package.yml
- packages/f/font-droid-ttf/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> font-droid-ttf: Add homepage

- packages/s/steam/monitoring.yml
- packages/s/steam/package.yml
- packages/s/steam/pspec_x86_64.xml
**Summary**
Some Steam games seem to require `libbsd` to launch
See for example this [thread](https://discuss.getsol.us/d/10552-steam-games-dont-start)
**Test Plan**
Confirmed "Dead Cells" launches correctly (then requested a refund)
**Checklist**
> steam: Add missing libbsd dependency and monitoring.yml

- packages/e/eza/abi_used_symbols
- packages/e/eza/package.yml
- packages/e/eza/pspec_x86_64.xml
**Summary**
- Add icon for `cron.minutely` directory
**Test Plan**
Run `eza` in multiple directories.
**Checklist**
> eza: Update to 0.18.14

- packages/f/font-firago/package.yml
- packages/f/font-firago/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> font-firago: Add homepage

- packages/k/kubectl/package.yml
- packages/k/kubectl/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> kubectl: include homepage

- packages/m/marisa-trite/abi_used_symbols
- packages/m/marisa-trite/package.yml
- packages/m/marisa-trite/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked homepage was
**Checklist**
> marisa-trite: include homepage

- packages/f/font-weather-icons/package.yml
- packages/f/font-weather-icons/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> font-weather-icons: Add homepage

- packages/m/macchanger/abi_used_symbols
- packages/m/macchanger/package.yml
- packages/m/macchanger/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> macchanger: include homepage

- packages/m/mathjax2/package.yml
- packages/m/mathjax2/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> mathjax2: include homepage

- packages/m/mailnag/package.yml
- packages/m/mailnag/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> mailnag: include homepage

- packages/m/metacity/abi_libs
- packages/m/metacity/abi_symbols
- packages/m/metacity/abi_used_symbols
- packages/m/metacity/package.yml
- packages/m/metacity/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked package was installed.
**Checklist**
> metacity: include homepage

- packages/m/media-player-info/package.yml
- packages/m/media-player-info/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> media-player-info: include homepage

- packages/n/nushell/abi_used_symbols
- packages/n/nushell/monitoring.yml
- packages/n/nushell/package.yml
- packages/n/nushell/pspec_x86_64.xml
**Summary**
- [0.93.0](https://www.nushell.sh/blog/2024-04-30-nushell_0_93_0.html)
- [0.92.2](https://www.nushell.sh/blog/2024-04-10-nushell_0_92_2.html)
- [0.92.1](https://www.nushell.sh/blog/2024-04-04-nushell_0_92_1.html)
- [0.92.0](https://www.nushell.sh/blog/2024-04-02-nushell_0_92_0.html)
**Test Plan**
Start a new (heh) shell, change directories, list files, make this commit and pull request.
**Checklist**
> nushell: Update to 0.93.0

- packages/t/ttyplot/abi_used_libs
- packages/t/ttyplot/abi_used_symbols
- packages/t/ttyplot/package.yml
- packages/t/ttyplot/pspec_x86_64.xml
**Summary**
- bugfix release
**Test Plan**
- echo 1 2 3 | TERM=vt100 ttyplot
**Checklist**
> ttyplot: Update to 1.6.4

- packages/h/hunspell-uk/package.yml
- packages/h/hunspell-uk/pspec_x86_64.xml
**Summary**
- No changelog provided
**Test Plan**
- proofread some text
**Checklist**
> hunspell-uk: Update to 6.4.4

- packages/f/fossil/abi_used_symbols
- packages/f/fossil/monitoring.yml
- packages/f/fossil/package.yml
- packages/f/fossil/pspec_x86_64.xml
- packages/s/shards/monitoring.yml
- packages/s/shards/package.yml
- packages/s/shards/pspec_x86_64.xml
**Summary**
- Full changelog can be found [here](https://fossil-scm.org/home/doc/trunk/www/changes.wiki#v2_24)
- Add `homepage` key to `package.yml` (Part of https://github.com/getsolus/packages/issues/411)
**Test Plan**
- Rebuild `shards` against this package
**Checklist**
> fossil: Update to 2.24

- packages/m/microdns/package.yml
- packages/m/microdns/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> microdns: include homepage

- packages/p/pandoc-crossref/package.yml
- packages/p/pandoc-crossref/pspec_x86_64.xml
**Summary**
Added `homepage` key to `package.yml` (part of getsolus/packages#411)
**Test Plan**
Build, install, compile demo example
**Checklist**
> pandoc-crossref: Add homepage

- packages/s/starship/abi_used_symbols
- packages/s/starship/package.yml
- packages/s/starship/pspec_x86_64.xml
**Summary**
- container: show name if available
- gleam: Add Gleam module
- k8s: Add detect env vars option
- nats: Add NATS Context
- odin: Add Odin Lang module
- username: add aliases option
- bash: use `eval` instead of a procsub for the POSIX mode
- bun: change default icon
- scala: use scala-cli first to avoid timeout
**Test Plan**
Start a new session, navigate to directories that are git repositories.
**Checklist**
> starship: Update to 1.19.0

- packages/e/eglexternalplatform/package.yml
- packages/e/eglexternalplatform/pspec_x86_64.xml
**Summary**
Add `homepage` key to `package.yml` (part of getsolus/packages#411)
**Test Plan**
Built, Installed package.
**Checklist**
> eglexternalplatform: Add homepage

- packages/m/mkchromecast/package.yml
- packages/m/mkchromecast/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> mkchromecast: include homepage

- packages/m/mit-scheme/abi_used_symbols
- packages/m/mit-scheme/package.yml
- packages/m/mit-scheme/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> mit-scheme: include homepage

- packages/m/miniupnpc/abi_used_symbols
- packages/m/miniupnpc/package.yml
- packages/m/miniupnpc/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> miniupnpc: include homepage

- packages/m/minigbm/abi_used_symbols
- packages/m/minigbm/abi_used_symbols32
- packages/m/minigbm/package.yml
- packages/m/minigbm/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked package was added.
**Checklist**
> minigbm: include homepage

- packages/m/moka-icon-theme/package.yml
- packages/m/moka-icon-theme/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> moka-icon-theme: include homepage

- packages/t/tailscale/package.yml
- packages/t/tailscale/pspec_x86_64.xml
**Summary**
- [changelog](https://tailscale.com/changelog#2024-05-15-client)
**Test Plan**
**Checklist**
> tailscale: Update to 1.66.3

- packages/m/mokutil/abi_used_symbols
- packages/m/mokutil/package.yml
- packages/m/mokutil/pspec_x86_64.xml
**Summary**
- Revert the default listing to the verbose form
**Test Plan**
- Installed and checked commands worked.
**Checklist**
> mokutil: update to 0.7.2

- packages/n/noisetorch/MAINTAINERS.md
- packages/n/noisetorch/abi_used_symbols
- packages/n/noisetorch/files/io.github.noisetorch.noisetorch.metainfo.xml
- packages/n/noisetorch/monitoring.yml
- packages/n/noisetorch/package.yml
- packages/n/noisetorch/pspec_x86_64.xml
**Summary**
- Release notes: 
- [0.12.2](https://github.com/noisetorch/NoiseTorch/releases/tag/v0.12.2) 
- [0.12.1](https://github.com/noisetorch/NoiseTorch/releases/tag/v0.12.1)
**Test Plan**
Run the app and record audio
**Checklist**
> noisetorch: Update to v0.12.2

- packages/h/hunspell-es/monitoring.yml
- packages/h/hunspell-es/package.yml
- packages/h/hunspell-es/pspec_x86_64.xml
**Summary**
- Full changelog can be found [here](https://raw.githubusercontent.com/sbosio/rla-es/v2.8/Changelog.txt)
**Test Plan**
Tested by @nelsontkq 
**Checklist**
> hunspell-es: Update to v2.8

- packages/s/solaar/package.yml
- packages/s/solaar/pspec_x86_64.xml
**Summary**
Release notes can be found [here](https://github.com/pwr-Solaar/Solaar/blob/1.1.13/Release_Notes.md).
**Test Plan**
- restart solaar
- unpair mouse from unifying receiver
- pair mouse to unifying receiver
- change mouse settings for scroll wheel
- change mouse dpi setting
- change mouse button mapping
**Checklist**
> solaar: Update to 1.1.13

- packages/b/budgie-desktop-branding/package.yml
- packages/b/budgie-desktop-branding/pspec_x86_64.xml
- packages/m/mate-desktop-branding/package.yml
- packages/m/mate-desktop-branding/pspec_x86_64.xml
- packages/x/xfce4-desktop-branding/MAINTAINERS.md
- packages/x/xfce4-desktop-branding/package.yml
- packages/x/xfce4-desktop-branding/pspec_x86_64.xml
**Summary**
Add or update default mimeapps files for Budgie, MATE, and XFCE.
**Test Plan**
Ensure that the files are present after installing.
**Checklist**
> add or update mimeapps lists

- packages/s/scrcpy/abi_symbols
- packages/s/scrcpy/abi_used_symbols
- packages/s/scrcpy/monitoring.yml
- packages/s/scrcpy/package.yml
- packages/s/scrcpy/pspec_x86_64.xml
**Summary**
Release notes can be found [here](https://github.com/Genymobile/scrcpy/releases/tag/v2.4).
**Test Plan**
Connect to my phone, mirror the display. Tested shared clipboard.
**Checklist**
> scrcpy: Update to 2.4

- packages/p/paper-icon-theme/monitoring.yml
- packages/p/paper-icon-theme/package.yml
- packages/p/paper-icon-theme/pspec_x86_64.xml
**Summary**
- Added `monitoring.yml` file with Anitya ID key (only key found)
**Test Plan**
Built, installed, used paper-icon-theme
**Checklist**
> paper-icon-theme: Add homepage & monitoring.yml

- packages/u/upx/abi_used_symbols
- packages/u/upx/monitoring.yml
- packages/u/upx/package.yml
- packages/u/upx/pspec_x86_64.xml
**Summary**
Release notes can be found [here](https://github.com/upx/upx/blob/v4.2.4/NEWS).
**Test Plan**
Used upx to compress one of the system binaries with various compression methods and tested if compressed binary still works.
**Checklist**
> upx: Update to 4.2.4

- packages/m/mono/abi_used_symbols
- packages/m/mono/package.yml
- packages/m/mono/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> mono: include homepage

- packages/k/kitty/abi_used_symbols
- packages/k/kitty/package.yml
- packages/k/kitty/pspec_x86_64.xml
**Summary**
**Test Plan**
- run cli in TERM
**Checklist**
> kitty: Update to 0.35.0

- packages/m/msodbcsql/package.yml
- packages/m/msodbcsql/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> msodbcsql: include homepage

- packages/m/msgpack/package.yml
- packages/m/msgpack/pspec_x86_64.xml
**Summary**
- Improve CI environment
- Improve build system
**Test Plan**
- Installed and started neovim which has this as a dependency.
**Checklist**
> msgpack: update to 6.0.1

- packages/f/fuse-zip/abi_libs
- packages/f/fuse-zip/abi_symbols
- packages/f/fuse-zip/abi_used_libs
- packages/f/fuse-zip/abi_used_symbols
- packages/f/fuse-zip/package.yml
- packages/f/fuse-zip/pspec_x86_64.xml
**Summary**
- Full changelog can found [here](https://bitbucket.org/agalanin/fuse-zip/raw/9b01842a149d904209aefec93beb70b2193c40a0/changelog)
**Test Plan**
- Mount zip file to `/tmp`
**Checklist**
> fuse-zip: Update to 0.7.2

- packages/d/discover/package.yml
- packages/d/discover/pspec_x86_64.xml
- packages/g/gnome-software/package.yml
- packages/g/gnome-software/pspec_x86_64.xml
**Test Plan**
N/A
**Checklist**
> Mark gnome-software & plasma-discover as no longer experimental

- packages/m/multibootusb/package.yml
- packages/m/multibootusb/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> multibootusb: include homepage

- packages/m/moreutils/abi_used_symbols
- packages/m/moreutils/files/Makefile.patch
- packages/m/moreutils/package.yml
- packages/m/moreutils/pspec_x86_64.xml
**Summary**
- Makefile: Warn users of pkgx.dev about their poor life choices.
**Test Plan**
- Installed and ran some of the commands.
**Checklist**
> moreutils: update to 0.69

- packages/l/libcangjie/abi_symbols
- packages/l/libcangjie/abi_used_symbols
- packages/l/libcangjie/monitoring.yml
- packages/l/libcangjie/package.yml
- packages/l/libcangjie/pspec_x86_64.xml
- packages/py/pycangjie/abi_symbols
- packages/py/pycangjie/monitoring.yml
- packages/py/pycangjie/package.yml
- packages/py/pycangjie/pspec_x86_64.xml
**Summary**
- libcangjie: Housekeeping
- pycangjie: Rebuild against libcangjie
> libcangjie : Housekeeping

- packages/m/mygui/abi_used_symbols
- packages/m/mygui/package.yml
- packages/m/mygui/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> mygui: include homepage

- packages/o/opencc/abi_used_symbols
- packages/o/opencc/package.yml
- packages/o/opencc/pspec_x86_64.xml
**Summary**
- Include homepage to package.yml
**Test Plan**
**Checklist**
> opencc: include homepage

- packages/a/antidote/MAINTAINERS.md
- packages/a/antidote/monitoring.yml
- packages/a/antidote/package.yml
- packages/a/antidote/pspec_x86_64.xml
**Summary**
- Initial inclusion.
**Test Plan**
- Installed and loaded plugins.
**Checklist**
Resolves https://github.com/getsolus/packages/issues/1776
> antidote: initial inclusion at 1.9.6

- packages/q/qutebrowser/monitoring.yml
**Summary**
- Add monitoring file
**Test Plan**
- Checked file.
**Checklist**
> qutebrowser: include monitoring

- packages/y/yasm/abi_used_symbols
- packages/y/yasm/package.yml
- packages/y/yasm/pspec_x86_64.xml
**Summary**
- Using latest commit to make it build.
- Fixed licenses.
- Resolves https://github.com/getsolus/packages/issues/2569
**Test Plan**
**Checklist**
- Moved over to latest commit to make it build. Not official release.
> yasm: update to 1.3.0.99

- packages/i/ipcalc/monitoring.yml
**Summary**
- Add monitoring file
**Test Plan**
- Checked file.
**Checklist**
> ipcalc: include monitoring

- packages/o/oniguruma/package.yml
- packages/o/oniguruma/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> oniguruma: include homepage

- packages/o/opensp/abi_used_symbols
- packages/o/opensp/package.yml
- packages/o/opensp/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> opensp: include homepage

- packages/o/opus-tools/package.yml
- packages/o/opus-tools/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> opus-tools: include homepage

- packages/o/ostree/abi_used_symbols
- packages/o/ostree/package.yml
- packages/o/ostree/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> ostree: include homepage

- packages/o/opusfile/package.yml
- packages/o/opusfile/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> opusfile: include homepage

- packages/n/nuget/package.yml
- packages/n/nuget/pspec_x86_64.xml
**Summary**
This should fix the patch file bug
**Test Plan**
- pack a file
- install a package
> nuget: build fix

- packages/k/kraft/abi_used_symbols
- packages/k/kraft/package.yml
- packages/k/kraft/pspec_x86_64.xml
**Summary**
- Substancial code cleanups
- Fix saving of XRechnung files
- Add a image mask for reportlab
- Add checkbox to mark document types to get XRechnung support
- Add a feedback link to the system overview page
- Updated translations
**Test Plan**
Create a new database, create an invoice, add two invoice items, view invoice as PDF
**Checklist**
> kraft: Update to 1.2.1

- packages/a/antidote/package.yml
- packages/a/antidote/pspec_x86_64.xml
**Summary**
- antibody is being deprecated in favor of this package, antibody, so add a replaces entry.
Part of https://github.com/getsolus/packages/issues/1647
> antidote: Add replaces entry for antibody

- packages/s/schedtool/abi_libs
- packages/s/schedtool/abi_symbols
- packages/s/schedtool/abi_used_symbols
- packages/s/schedtool/package.yml
- packages/s/schedtool/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> schedtool: include homepage

- packages/s/scanmem/abi_used_symbols
- packages/s/scanmem/package.yml
- packages/s/scanmem/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> scanmem: include homepage

- packages/s/sbsigntools/package.yml
- packages/s/sbsigntools/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> sbsigntools: include homepage

- packages/s/sane-airscan/abi_used_libs
- packages/s/sane-airscan/abi_used_symbols
- packages/s/sane-airscan/package.yml
- packages/s/sane-airscan/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked it installed correctly.
**Checklist**
> sane-airscan: update to 0.99.29

- packages/s/screenfetch/package.yml
- packages/s/screenfetch/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> screenfetch: include homepage

- packages/n/ncdu/abi_used_libs
- packages/n/ncdu/abi_used_symbols
- packages/n/ncdu/package.yml
- packages/n/ncdu/pspec_x86_64.xml
**Summary**
- [changelog](https://dev.yorhel.nl/ncdu/changes2)
**Test Plan**
- ncdu --color dark
**Checklist**
> ncdu: Update to 2.4

- packages/s/sdl2-gfx/package.yml
- packages/s/sdl2-gfx/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> sdl2-gfx: include homepage

- packages/s/sdl1-mixer/abi_used_symbols
- packages/s/sdl1-mixer/abi_used_symbols32
- packages/s/sdl1-mixer/package.yml
- packages/s/sdl1-mixer/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
- Added missing dependencies to make it build.
> sdl1-mixer: include homepage

- packages/s/sdl1-image/abi_used_symbols
- packages/s/sdl1-image/abi_used_symbols32
- packages/s/sdl1-image/package.yml
- packages/s/sdl1-image/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> sdl1-image: include homepage

- packages/s/sdl1-net/package.yml
- packages/s/sdl1-net/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
- Added missing dependencies to make it build.
> sdl1-net: include homepage

- packages/s/sequeler/MAINTAINERS.md
- packages/s/sequeler/abi_used_symbols
- packages/s/sequeler/package.yml
- packages/s/sequeler/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
- Removed maintainer file of inactive maintainer.
> sequeler: include homepage

- packages/s/seexpr/abi_used_symbols
- packages/s/seexpr/package.yml
- packages/s/seexpr/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> seexpr: include homepage

- packages/s/sdl-ttf/abi_libs32
- packages/s/sdl-ttf/abi_symbols
- packages/s/sdl-ttf/abi_used_libs
- packages/s/sdl-ttf/abi_used_libs32
- packages/s/sdl-ttf/abi_used_symbols32
- packages/s/sdl-ttf/package.yml
- packages/s/sdl-ttf/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> sdl-ttf: include homepage

- packages/e/eza/package.yml
- packages/e/eza/pspec_x86_64.xml
**Summary**
- Add icon for Nushell extension
**Test Plan**
List files in a directory.
**Checklist**
> eza: Update to 0.18.17

- packages/s/slurp/package.yml
- packages/s/slurp/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> slurp: include homepage

- packages/s/smplayer-theme/package.yml
- packages/s/smplayer-theme/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> smplayer-theme: include homepage

- packages/a/anki/abi_used_symbols
- packages/a/anki/package.yml
- packages/a/anki/pspec_x86_64.xml
**Summary**
Release notes:
- [24.06](https://github.com/ankitects/anki/releases/tag/24.06)
- [24.06.1](https://github.com/ankitects/anki/releases/tag/24.06.1)
**Test Plan**
Played through a couple of Japanese cards with images and audio
**Checklist**
> anki: Update to 24.06.1

- packages/g/gaupol/monitoring.yml
- packages/g/gaupol/package.yml
- packages/g/gaupol/pspec_x86_64.xml
**Summary**
Changes:
- Fix translations missing for enums
- Fix Python 3.12 compatibility and drop support for Python < 3.4
- Add Chinese (China) translation
- Change the icon for the toggle video player toolbar item to an action icon (not mimetype) that has a symbolic version available
- Fix installation on Python >= 3.12 by using distutils from setuptools
- Fix invalid entry in AppData file
**Test Plan**
Edited some subtitles for "Die Hard"
**Checklist**
> gaupol: Update to 1.14.1 and add monitoring.yml

- packages/s/signon-plugin-oauth2/abi_used_symbols
- packages/s/signon-plugin-oauth2/package.yml
- packages/s/signon-plugin-oauth2/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> signon-plugin-oauth2: include homepage

- packages/f/flask-cors/monitoring.yml
- packages/f/flask-cors/package.yml
- packages/f/flask-cors/pspec_x86_64.xml
**Summary**
Changes:
- Update extension.py to clean request.path before logging it
**Security**
- CVE-2024-1681
**Test Plan**
Ran some examples from the project README
**Checklist**
> flask-cors: Update to 4.0.1 and add monitoring.yml

- packages/s/sndio/abi_symbols
- packages/s/sndio/abi_symbols32
- packages/s/sndio/abi_used_symbols
- packages/s/sndio/abi_used_symbols32
- packages/s/sndio/package.yml
- packages/s/sndio/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked mpd which is dependent on this.
**Checklist**
> sndio: update to 1.9.0

- packages/py/python-pyrate-limiter/package.yml
- packages/py/python-pyrate-limiter/pspec_x86_64.xml
**Summary**
Changes:
- Add support for creating/getting bucket asynchronously
**Test Plan**
Tested some examples from the project README
**Checklist**
> python-pyrate-limiter: Update to 3.6.1

- packages/s/smplayer/abi_used_symbols
- packages/s/smplayer/monitoring.yml
- packages/s/smplayer/package.yml
- packages/s/smplayer/pspec_x86_64.xml
**Summary**
- Bug fixes
Fixes https://github.com/getsolus/packages/issues/2937
**Test Plan**
Play an audio file, use the pause, play, stop buttons, and play a video file with audio.
**Checklist**
> smplayer: Update to 24.5.0

- packages/m/man-pages/package.yml
- packages/m/man-pages/pspec_x86_64.xml
**Summary**
Changes:
- New and rewritten pages
- Newly documented interfaces in existing pages
- New and changed links
- Stamp the versions on the pages at install time, instead of dist time
**Test Plan**
- Viewed some of the new and updated man pages
- Confirmed versions were correctly stamped
**Checklist**
> man-pages: Update to 6.8

- packages/s/solarus-quest-editor/abi_used_symbols
- packages/s/solarus-quest-editor/package.yml
- packages/s/solarus-quest-editor/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> solarus-quest-editor: include homepage

- packages/f/font-ibm-plex/package.yml
- packages/f/font-ibm-plex/pspec_x86_64.xml
**Summary**
- [changelog](https://github.com/IBM/plex/compare/v6.4.0...v6.4.1)
**Test Plan**
- render text
**Checklist**
> font-ibm-plex: Update to 6.4.1

- packages/py/python-orjson/package.yml
- packages/py/python-orjson/pspec_x86_64.xml
**Summary**
Changes:
**Test Plan**
Executed some examples from the project's README
**Checklist**
> python-orjson: Update to 3.10.4

- packages/a/ant-gtk-theme/package.yml
- packages/a/ant-gtk-theme/pspec_x86_64.xml
**Summary**
- Many fixes and support for newer desktop releases
**Test Plan**
Switch to the theme in Budgie and see that the theme looks okay.
**Checklist**
> ant-gtk-theme: Sync with git

- packages/o/openssl-11/package.yml
- packages/o/openssl-11/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked package was installed.
**Checklist**
> openssl-11: include homepage

- packages/s/sox/package.yml
- packages/s/sox/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> sox: include homepage

- packages/s/spice-protocol/package.yml
- packages/s/spice-protocol/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> spice-protocol: include homepage

- packages/s/speedtest-cli/package.yml
- packages/s/speedtest-cli/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> speedtest-cli: include homepage

- packages/s/steamtinkerlaunch/package.yml
- packages/s/steamtinkerlaunch/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> steamtinkerlaunch: include homepage

- packages/s/stb/package.yml
- packages/s/stb/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> stb: include homepage

- packages/w/wine/abi_symbols
- packages/w/wine/abi_symbols32
- packages/w/wine/abi_used_symbols
- packages/w/wine/abi_used_symbols32
- packages/w/wine/package.yml
- packages/w/wine/pspec_x86_64.xml
**Summary**
- C++ exception handling on ARM platforms
- More DPI Awareness support improvements
Full release notes available [here](https://gitlab.winehq.org/wine/wine/-/releases/wine-9.11)
**Test Plan**
- Ran `winefile`, `winemine`, `winecfg`, `wineconsole`
**Checklist**
> wine: Update to 9.11

- packages/s/swh-plugins/package.yml
- packages/s/swh-plugins/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> swh-plugins: include homepage

- packages/s/surfn-icon-theme/package.yml
**Summary**
**Test Plan**
**Checklist**
> surfn-icon-theme: include homepage

- .github/ISSUE_TEMPLATE/request-package-deprecation.yml
**Summary**
Fix broken link on deprecation request form
> Fix broken link on deprecation request form

- packages/s/syncthing-gtk/package.yml
- packages/s/syncthing-gtk/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> syncthing-gtk: include homepage

- packages/s/switcheroo-control/package.yml
- packages/s/switcheroo-control/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> switcheroo-control: include homepage

- packages/s/solus-hardware-config/package.yml
- packages/s/solus-hardware-config/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> solus-hardware-config: include homepage

- packages/s/sonivox/package.yml
- packages/s/sonivox/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> sonivox: include homepage

- packages/s/solus-artwork/package.yml
- packages/s/solus-artwork/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> solus-artwork: include homepage

- packages/t/t4k-common/abi_symbols
- packages/t/t4k-common/abi_used_symbols
- packages/t/t4k-common/package.yml
- packages/t/t4k-common/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> t4k-common: include homepage

- packages/s/systemd-bootchart/abi_used_symbols
- packages/s/systemd-bootchart/package.yml
- packages/s/systemd-bootchart/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> systemd-bootchart: include homepage

- packages/py/python3-cairo/abi_used_symbols
- packages/py/python3-cairo/monitoring.yml
- packages/py/python3-cairo/package.yml
- packages/py/python3-cairo/pspec_x86_64.xml
**Summary**
- Full changelog can be found [here](https://pycairo.readthedocs.io/en/latest/changelog.html)
**Test Plan**
TBD
**Checklist**
> python3-cairo: Update to 1.26.0

- packages/py/python3/package.yml
- packages/py/python3/pspec_x86_64.xml
**Summary**
**Test Plan**
Verified homepage loads relevant informations
**Checklist**
> python3: Add homepage

- packages/t/tailscale/package.yml
- packages/t/tailscale/pspec_x86_64.xml
**Summary**
- [changelog](https://tailscale.com/changelog#2024-06-14-client)
**Test Plan**
**Checklist**
> tailscale: Update to 1.68.1

- packages/f/font-iosevka-ttf/package.yml
- packages/f/font-iosevka-ttf/pspec_x86_64.xml
**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v30.2.0/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**
> font-iosevka-ttf: Update to 30.2.0

- packages/py/python3-pyudev/monitoring.yml
- packages/py/python3-pyudev/package.yml
- packages/py/python3-pyudev/pspec_x86_64.xml
**Summary**
- Full changelog can be found [here](https://github.com/pyudev/pyudev/blob/v0.24.3/CHANGES.rst)
**Test Plan**
TBD
**Checklist**
> python3-pyudev: Update to 0.24.3

- packages/t/tcpdump/abi_used_symbols
- packages/t/tcpdump/package.yml
- packages/t/tcpdump/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> tcpdump: include homepage

- packages/t/tcp_wrappers/package.yml
- packages/t/tcp_wrappers/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
- [X} Package was built and tested against unstable
> tcp_wrappers: include homepage

- packages/t/teeworlds/abi_used_symbols
- packages/t/teeworlds/package.yml
- packages/t/teeworlds/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> teeworlds: include homepage

- packages/t/tdrop/package.yml
- packages/t/tdrop/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> tdrop: include homepage

- packages/k/kitty/package.yml
- packages/k/kitty/pspec_x86_64.xml
**Summary**
- A new option, window_logo_scale to specify how window logos are scaled
- A new option, cursor_shape_unfocused to specify the shape of cursor
- Remote control: Fix empty password not working
- Fix flickering on Wayland window resize on NVIDIA drivers
- [full changelog](https://sw.kovidgoyal.net/kitty/changelog/#detailed-list-of-changes)
**Test Plan**
- run CLI
**Checklist**
> kitty: Update to 0.35.2

- packages/f/font-iosevka-ttf/package.yml
- packages/f/font-iosevka-ttf/pspec_x86_64.xml
**Summary**
- [changelog](https://github.com/be5invis/Iosevka/blob/v30.3.0/CHANGELOG.md)
**Test Plan**
- render text
**Checklist**
> font-iosevka-ttf: Update to 30.3.0

- packages/t/tomlc99/package.yml
- packages/t/tomlc99/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> tomlc99: include homepage

- packages/t/tmate/abi_symbols
- packages/t/tmate/abi_used_symbols
- packages/t/tmate/package.yml
- packages/t/tmate/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> tmate: include homepage

- packages/t/tinyxml/abi_used_symbols
- packages/t/tinyxml/package.yml
- packages/t/tinyxml/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> tinyxml: include homepage

- packages/t/tini/abi_used_symbols
- packages/t/tini/package.yml
- packages/t/tini/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> tini: include homepage

- packages/t/tinc/abi_used_symbols
- packages/t/tinc/package.yml
- packages/t/tinc/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> tinc: include homepage

- packages/t/tilp/package.yml
- packages/t/tilp/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> tilp: include homepage

- packages/t/tidy-html5/package.yml
- packages/t/tidy-html5/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> tidy-html5: include homepage

- packages/t/translate-shell/package.yml
- packages/t/translate-shell/pspec_x86_64.xml
**Summary**
- Bing Translator: fixed engine support
- Apertium Translator: (partly) fixed engine support
- REPL: supported setting sl and tl by :set
**Test Plan**
- Installed and did some translations.
**Checklist**
> translate-shell: update to 0.9.7.1

- packages/t/tap-plugins/abi_used_symbols
- packages/t/tap-plugins/package.yml
- packages/t/tap-plugins/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
- Switched to new source as this was removed from GitHub.
> tap-plugins: include homepage

- packages/py/python-orjson/package.yml
- packages/py/python-orjson/pspec_x86_64.xml
**Summary**
Changes:
**Test Plan**
Executed some example from the project's README
**Checklist**
> python-orjson: Update to 3.10.5

- packages/s/slick-greeter/abi_used_symbols
- packages/s/slick-greeter/monitoring.yml
- packages/s/slick-greeter/package.yml
- packages/s/slick-greeter/pspec_x86_64.xml
**Summary**
- Add cursor scaling for HiDPI displays
**Test Plan**
Restart the computer and log in successfully.
**Checklist**
> slick-greeter: Update to 2.0.5

- packages/c/cinnamon-translations/package.yml
- packages/c/cinnamon-translations/pspec_x86_64.xml
- packages/l/libcinnamon-desktop/abi_used_symbols
- packages/l/libcinnamon-desktop/package.yml
- packages/l/libcinnamon-desktop/pspec_x86_64.xml
- packages/n/nemo-extensions/abi_used_symbols
- packages/n/nemo-extensions/package.yml
- packages/n/nemo-extensions/pspec_x86_64.xml
- packages/n/nemo/abi_used_libs
- packages/n/nemo/abi_used_symbols
- packages/n/nemo/package.yml
- packages/n/nemo/pspec_x86_64.xml
- packages/p/pastebinit/package.yml
- packages/p/pastebinit/pspec_x86_64.xml
- packages/x/xapp/abi_used_symbols
- packages/x/xapp/package.yml
- packages/x/xapp/pspec_x86_64.xml
**Summary**
- **xapp: Update to 2.8.4**
- **libcinnamon-desktop: Update to 6.2.0**
- **cinnamon-translations: Update to 6.2.1**
- **nemo: Update to 6.2.1**
- **pastebinit: Update to 1.7.0**
- **nemo-extensions: Update to 6.2.0**
**Test Plan**
Launch Nemo and navigate to different folders.
**Checklist**
> xapp and nemo update

- packages/x/xaut/package.yml
- packages/x/xaut/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> xaut: include homepage

- packages/x/xbitmaps/package.yml
- packages/x/xbitmaps/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> xbitmaps: include homepage

- packages/x/xclip/abi_used_symbols
- packages/x/xclip/package.yml
- packages/x/xclip/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> xclip: include homepage

- packages/t/tv-lite/files/com.tv_lite.tv_lite.metainfo.xml
- packages/t/tv-lite/monitoring.yml
- packages/t/tv-lite/package.yml
- packages/t/tv-lite/pspec_x86_64.xml
**Summary**
- Added metainfo xml
- Added monitoring file
**Test Plan**
- Checked files were added.
**Checklist**
> tv-lite: housekeeping

- packages/x/xdg-utils/package.yml
- packages/x/xdg-utils/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> xdg-utils: include homepage

- packages/x/xdotool/abi_used_symbols
- packages/x/xdotool/package.yml
- packages/x/xdotool/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
- Fixed license
> xdotool: include homepage

- packages/x/xiccd/abi_used_symbols
- packages/x/xiccd/package.yml
- packages/x/xiccd/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> xiccd: include homepage

- packages/x/xl2tpd/abi_used_symbols
- packages/x/xl2tpd/package.yml
- packages/x/xl2tpd/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> xl2tpd: include homepage

- packages/x/xmltoman/package.yml
- packages/x/xmltoman/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> xmltoman: include homepage

- packages/x/xrdp-budgie-integration/package.yml
- packages/x/xrdp-budgie-integration/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> xrdp-budgie-integration: include homepage

- packages/x/xrdp-gnome-integration/package.yml
- packages/x/xrdp-gnome-integration/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> xrdp-gnome-integration: include homepage

- packages/x/xrdp-mate-integration/package.yml
- packages/x/xrdp-mate-integration/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> xrdp-mate-integration: include homepage

- packages/x/xrdp-plasma-integration/package.yml
- packages/x/xrdp-plasma-integration/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> xrdp-plasma-integration: include homepage

- packages/x/xsettingsd/abi_used_symbols
- packages/x/xsettingsd/package.yml
- packages/x/xsettingsd/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
- The project has moved to Codeberg, changed the source.
> xsettingsd: include homepage

- packages/x/xvidcore/package.yml
- packages/x/xvidcore/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> xvidcore: include homepage

- packages/x/xfwm4/abi_used_symbols
- packages/x/xfwm4/package.yml
- packages/x/xfwm4/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
- Maintainers file is missing name and surname of maintainer.
> xfwm4: include homepage

- packages/l/lite-xl/package.yml
- packages/l/lite-xl/pspec_x86_64.xml
**Summary**
- General bug fixes
- [changelog](https://github.com/lite-xl/lite-xl/blob/v2.1.5/changelog.md) 
**Test Plan**
- open a file with lite-xl 
**Checklist**
Resolves https://github.com/getsolus/packages/issues/3136
> lite-xl: Update to 2.1.5

- packages/b/barrier/abi_used_symbols
- packages/b/barrier/files/1886.patch
- packages/b/barrier/files/com.github.debauchee.barrier.appdata.xml
- packages/b/barrier/monitoring.yml
- packages/b/barrier/package.yml
- packages/b/barrier/pspec_x86_64.xml
**Summary**
- Add appstream metadata
- Add monitoring file
**Test Plan**
- Checked files were added.
**Checklist**
- Added new patch to make it build
- Metadata file taken from flathub
> barrier: housekeeping

- packages/l/libgeocode-glib2/abi_used_symbols
- packages/l/libgeocode-glib2/package.yml
- packages/l/libgeocode-glib2/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libgeocode-glib2: add homepage

- packages/l/libgepub/abi_used_symbols
- packages/l/libgepub/package.yml
- packages/l/libgepub/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked that homepage was added. Built package successfully.
**Checklist**
> libgepub: add homepage

- packages/l/libimobiledevice/package.yml
- packages/l/libimobiledevice/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libimobiledevice: add homepage

- packages/b/blueman/files/io.github.blueman_project.blueman.metainfo.xml
- packages/b/blueman/package.yml
- packages/b/blueman/pspec_x86_64.xml
**Summary**
- Add app stream metainfo
**Test Plan**
- Verified metainfo with appstream-builder --packages-dir=. --include-failed -v
**Checklist**
> blueman: add appstream metainfo

- packages/l/libmanette/abi_used_symbols
- packages/l/libmanette/package.yml
- packages/l/libmanette/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libmanette: add homepage

- packages/l/libmatroska/package.yml
- packages/l/libmatroska/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libmatroska: add homepage

- packages/l/libmcrypt/package.yml
- packages/l/libmcrypt/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libmcrypt: add homepage

- packages/l/libinput-gestures/package.yml
- packages/l/libinput-gestures/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libinput-gestures: add homepage

- packages/l/liblastfm/abi_used_symbols
- packages/l/liblastfm/package.yml
- packages/l/liblastfm/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> liblastfm: add homepage

- packages/l/libhangul/package.yml
- packages/l/libhangul/pspec_x86_64.xml
**Summary**
- Added `gettext-devel` to fix failing build getsolus/packages#3175
**Test Plan**
- Checked if homepage was added. Built package successfuly.
**Checklist**
> libhangul: fix failing build

- packages/l/libiptcdata/abi_used_symbols
- packages/l/libiptcdata/monitoring.yml
- packages/l/libiptcdata/package.yml
- packages/l/libiptcdata/pspec_x86_64.xml
**Summary**
Resolves https://github.com/getsolus/packages/issues/3178
**Test Plan**
Used the `iptc` command to view and modify IPTC metadata in .jpg files
**Checklist**
> libiptcdata: Add homepage, monitoring.yml; and fix license

- packages/l/libmpack/package.yml
- packages/l/libmpack/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libmpack: add homepage

- packages/l/libmspack/package.yml
- packages/l/libmspack/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libmspack: add homepage

- packages/l/libnettle6/abi_used_symbols
- packages/l/libnettle6/abi_used_symbols32
- packages/l/libnettle6/package.yml
- packages/l/libnettle6/pspec_x86_64.xml
**Summary**
**Test Plan**
- checked if homepage was added. Built package successfully.
**Checklist**
> libnettle6: add homepage

- packages/l/libnfs/abi_used_symbols
- packages/l/libnfs/package.yml
- packages/l/libnfs/pspec_x86_64.xml
**Summary**
**Test Plan**
- checked if homepage was added. Built package successfully.
**Checklist**
> libnfs: add homepage

- packages/l/libmypaint/abi_used_symbols
- packages/l/libmypaint/package.yml
- packages/l/libmypaint/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libmypaint: add homepage

- packages/l/libftdi1/abi_libs
- packages/l/libftdi1/abi_symbols
- packages/l/libftdi1/package.yml
- packages/l/libftdi1/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked homepage was added. Built package successfully.
**Checklist**
> libftdi1: add homepage

- packages/b/brewtarget/files/io.github.brewtarget.brewtarget.metainfo.xml
- packages/b/brewtarget/monitoring.yml
- packages/b/brewtarget/package.yml
- packages/b/brewtarget/pspec_x86_64.xml
**Summary**
- Add metadata file
- Add monitoring file
**Test Plan**
- Verified metainfo with appstream-builder --packages-dir=. --include-failed -v
**Checklist**
> brewtarget: housekeeping

- packages/l/libnitrokey/package.yml
- packages/l/libnitrokey/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked homepage was added. Built package successfully.
**Checklist**
> libnitrokey: add homepage

- packages/b/bandwhich/abi_used_symbols
- packages/b/bandwhich/package.yml
- packages/b/bandwhich/pspec_x86_64.xml
**Summary**
- Use cargo macros
**Test Plan**
- Made sure it build with the new macros.
**Checklist**
> bandwhich: use cargo macros

- packages/b/btop/files/io.github.aristocratos.btop.metainfo.xml
- packages/b/btop/package.yml
- packages/b/btop/pspec_x86_64.xml
**Summary**
- Add appstream metadata
**Test Plan**
- Verified that the appstream metadata was correct.
**Checklist**
> btop: include appsteam metadata

- common/Scripts/appstream_ignored_packages.txt
**Summary**
Add more packages to `appstream_ignored_packages.txt`
> Add more packages to appstream_ignored_packages.txt

- packages/c/cargo-audit/abi_used_symbols
- packages/c/cargo-audit/package.yml
- packages/c/cargo-audit/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cargo-audit: use new cargo macros

- packages/b/bottom/abi_used_symbols
- packages/b/bottom/package.yml
- packages/b/bottom/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> bottom: use new cargo macros

- packages/l/libopusenc/abi_symbols
- packages/l/libopusenc/abi_used_symbols
- packages/l/libopusenc/package.yml
- packages/l/libopusenc/pspec_x86_64.xml
**Summary**
- Fixed failing build by replacing `%configure` with `%configure_no_runstatedir`
**Test Plan**
**Checklist**
> libopusenc: add homepage, fix build

- packages/l/libopenglrecorder/abi_used_symbols
- packages/l/libopenglrecorder/package.yml
- packages/l/libopenglrecorder/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked if homepage was added. Built package successfully. 
**Checklist**
> libopenglrecorder: add homepage

- packages/py/python-websocket-client/package.yml
- packages/py/python-websocket-client/pspec_x86_64.xml
**Summary**
**Test Plan**
Verified homepage now exists.   Installed new package, created and ran a test python program to validate basic functionality.
**Checklist**
> python-websocket-client:  add homepage

- packages/c/cargo-c/package.yml
- packages/c/cargo-c/pspec_x86_64.xml
**Summary**
- Use new macros
**Test Plan**
**Checklist**
> cargo-c: use new macros

- packages/a/amdgpu_top/package.yml
- packages/a/amdgpu_top/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> amdgpu_top: use new cargo macros

- packages/c/czkawka/abi_used_libs
- packages/c/czkawka/abi_used_symbols
- packages/c/czkawka/package.yml
- packages/c/czkawka/pspec_x86_64.xml
**Summary**
- Use new cargo macro
**Test Plan**
**Checklist**
> czkawka: use new cargo macro

- packages/b/brscan4/files/brscan4.metainfo.xml
- packages/b/brscan4/package.yml
- packages/b/brscan4/pspec_x86_64.xml
**Summary**
- Resolved getsolus/packages#3083
**Test Plan**
Verify metainfo with appstream-builder --packages-dir=. --include-failed -v
**Checklist**
> brscan4: Add appstream metainfo

- packages/t/thunar-volman/package.yml
- packages/t/thunar-volman/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
- Maintainers file is missing name and surname of maintainer.
> thunar-volman: include homepage

- packages/c/cargo-auditable/abi_used_symbols
- packages/c/cargo-auditable/package.yml
- packages/c/cargo-auditable/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cargo-auditable: use new cargo macros

- packages/t/tailscale/package.yml
- packages/t/tailscale/pspec_x86_64.xml
**Summary**
- [changelog](https://tailscale.com/changelog#2024-07-02-client)
**Test Plan**
**Checklist**
> tailscale: Update to 1.68.2

- packages/l/libnih/abi_used_symbols
- packages/l/libnih/package.yml
- packages/l/libnih/pspec_x86_64.xml
**Summary**
- Fixed license to correct format
**Test Plan**
**Checklist**
> libnih: add homepage, fix lincese, fix build

- packages/l/libmikmod2/abi_used_symbols32
- packages/l/libmikmod2/package.yml
- packages/l/libmikmod2/pspec_x86_64.xml
**Summary**
- Replaced mirror source with direct one
**Test Plan**
- Checked if homepage was added. Package built successfully.
**Checklist**
> libmikmod2: add homepage, fix build, change source mirror

- packages/s/scikit-learn/abi_used_symbols
- packages/s/scikit-learn/package.yml
- packages/s/scikit-learn/pspec_x86_64.xml
**Summary**
Add homepage reference URL to package.yml
**Test Plan**
Verified homepage reference in package.yml
Built and installed package, installed pytest and tested per scikit-learn.org instructions
Performed basic pytests.  Not 100% pass rate, but results were the same before & after the new package build. 
**Checklist**
> scikit-learn: Add homepage

- packages/l/libpagemaker/package.yml
- packages/l/libpagemaker/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked if homepage was added.
**Checklist**
> libpagemaker: add homepage

- packages/l/libmms/package.yml
- packages/l/libmms/pspec_x86_64.xml
**Summary**
- Replaced mirror with direct source
- Fixed license format
**Test Plan**
- Downloaded from new source
**Checklist**
> libmms: add homepage, fix license, change source

- packages/p/perl-xmlparser/package.yml
- packages/p/perl-xmlparser/pspec_x86_64.xml
**Summary**
[Changelog](https://metacpan.org/release/TODDR/XML-Parser-2.47/source/Changes)
**Test Plan**
Test the synopsis code https://metacpan.org/pod/XML::Parser#SYNOPSIS
**Checklist**
> perl-xmlparser: Update to 2.47

- packages/l/libmikmod/package.yml
- packages/l/libmikmod/pspec_x86_64.xml
**Summary**
- Replaced mirror with direct source
**Test Plan**
- Checked if homepage was added. 
- Downloaded from new source. 
- Built package successfully.
**Checklist**
> libmikmod: add homepage, change source, fix build

- packages/s/syncthing/package.yml
- packages/s/syncthing/pspec_x86_64.xml
**Summary**
Bugfixes & minor enhancements
**Test Plan**
- Restart Syncthing-GTK and verify it can connect to the syncthing backend, all folders sync
**Checklist**
> syncthing: update to 1.27.9

- packages/f/font-firacode-nerd/files/nerd-fonts.metainfo.xml
- packages/f/font-firacode-nerd/package.yml
- packages/f/font-firacode-nerd/pspec_x86_64.xml
**Summary**
Fix metainfo name component
> font-firacode-nerd: Fix metainfo name component

- packages/f/font-ibm-plex/files/ibmplex.metainfo.xml
- packages/f/font-ibm-plex/package.yml
- packages/f/font-ibm-plex/pspec_x86_64.xml
**Summary**
Fix metainfo name component
> font-ibm-plex: Fix metainfo name component

- packages/f/font-sarasa-gothic/files/sarasa-gothic.metainfo.xml
- packages/f/font-sarasa-gothic/package.yml
- packages/f/font-sarasa-gothic/pspec_x86_64.xml
**Summary**
Fix metainfo name component
> font-sarasa-gothic: Fix metainfo name component

- packages/n/noto-sans-ttf/files/noto-sans-ttf.metainfo.xml
- packages/n/noto-sans-ttf/files/noto-serif-ttf.metainfo.xml
- packages/n/noto-sans-ttf/package.yml
- packages/n/noto-sans-ttf/pspec_x86_64.xml
**Summary**
Fix metainfo name component
> noto-sans-ttf: Fix metainfo name component

- packages/c/calf/abi_used_symbols
- packages/c/calf/files/org.calf_studio_gear.calf.metainfo.xml
- packages/c/calf/package.yml
- packages/c/calf/pspec_x86_64.xml
**Summary**
- Add appstream metadata.
**Test Plan**
- Checked files were added.
**Checklist**
> calf: add appstream metadata

- packages/c/cbindgen/package.yml
- packages/c/cbindgen/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> cbindgen: use new cargo macros

- packages/g/git-absorb/abi_used_symbols
- packages/g/git-absorb/package.yml
- packages/g/git-absorb/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> git-absorb: use new cargo macros

- packages/py/python-orjson/package.yml
- packages/py/python-orjson/pspec_x86_64.xml
**Summary**
Changes:
**Test Plan**
Ran through some examples from the project's README
**Checklist**
> python-orjson: Update to 3.10.6

- packages/l/libotr/files/libotr-4.1.1-include-socket.h.patch
- packages/l/libotr/monitoring.yml
- packages/l/libotr/package.yml
- packages/l/libotr/pspec_x86_64.xml
**Summary**
- Include monitoring file
- Fixes https://github.com/getsolus/packages/issues/3253
**Test Plan**
**Checklist**
> libotr: housekeeping

- packages/f/fan2go/MAINTAINERS.md
> fan2go: Remove MAINTAINERS.MD

- packages/h/hyperfine/abi_used_symbols
- packages/h/hyperfine/package.yml
- packages/h/hyperfine/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> hyperfine: use new cargo macros

- packages/l/libreoffice/package.yml
- packages/l/libreoffice/pspec_x86_64.xml
**Summary**
Full changelog [here](https://wiki.documentfoundation.org/ReleaseNotes/24.2)
**Test Plan**
Open a few documents
**Checklist**
> libreoffice: Update to 24.2.5.2

- packages/f/font-iosevka-ttf/package.yml
- packages/f/font-iosevka-ttf/pspec_x86_64.xml
**Summary**
- Fix side bearings of U+02CC under Quasi-Proportional.
- Improve glyph shape for U+02ED.
- [changelog](https://raw.githubusercontent.com/be5invis/Iosevka/v30.3.2/CHANGELOG.md)
**Test Plan**
**Checklist**
> font-iosevka-ttf: Update to 30.3.2

- packages/r/ripgrep/abi_used_symbols
- packages/r/ripgrep/package.yml
- packages/r/ripgrep/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> ripgrep: use new cargo macros

- packages/n/navi/abi_used_symbols
- packages/n/navi/package.yml
- packages/n/navi/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> navi: use new cargo macros

- packages/m/mandown/abi_used_symbols
- packages/m/mandown/package.yml
- packages/m/mandown/pspec_x86_64.xml
**Summary**
**Test Plan**
- Created a man page.
**Checklist**
> mandown: update to 0.1.4

- packages/s/sd/abi_used_symbols
- packages/s/sd/package.yml
- packages/s/sd/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> sd: use new cargo macros

- packages/c/cendric/abi_used_symbols
- packages/c/cendric/files/ch.cendric.cendric.metainfo.xml
- packages/c/cendric/package.yml
- packages/c/cendric/pspec_x86_64.xml
**Summary**
- Add appstream metadata
**Test Plan**
- Verified the file was correct.
**Checklist**
> cendric: add appstream metadata

- packages/f/fortune-mod/MAINTAINERS.md
- packages/f/fortune-mod/monitoring.yml
- packages/f/fortune-mod/package.yml
- packages/f/fortune-mod/pspec_x86_64.xml
**Summary**
- Add the the-x-files-taglines collection.
- Add the -D USE_PCRE=1 option to use the PCRE2 library for regexes.
- Remove duplicates.
**Test Plan**
- Read some fortunes.
**Checklist**
> fortune-mod: update to 3.22.0

- packages/n/nasm/abi_used_symbols
- packages/n/nasm/monitoring.yml
- packages/n/nasm/package.yml
- packages/n/nasm/pspec_x86_64.xml
**Summary**
- Full changelog [here](https://nasm.us/doc/nasmdocc.html)
- Add `monitoring.yml`
**Security Fixes:**
- CVE-2022-46456
**Test Plan**
N/A
**Checklist**
> nasm: Update to 2.16.03

- packages/c/ckb/files/io.github.ckb_next.ckb.metainfo.xml
- packages/c/ckb/package.yml
- packages/c/ckb/pspec_x86_64.xml
**Summary**
**Test Plan**
-  Verified the metainfo.
**Checklist**
> ckb: add appstream metainfo

- packages/l/libmad/monitoring.yml
- packages/l/libmad/package.yml
- packages/l/libmad/pspec_x86_64.xml
**Summary**
**Test Plan**
- Checked if homepage was added.
- Built package successfully.
**Checklist**
> libmad: add homepage, fix build, monitoring

- packages/l/libpcre3/monitoring.yml
- packages/l/libpcre3/package.yml
- packages/l/libpcre3/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libpcre3: homepage, monitoring

- packages/l/libva-intel-driver/package.yml
- packages/l/libva-intel-driver/pspec_x86_64.xml
**Summary**
add homepage key to package.yml
**Test Plan**
- ensure package is successfully built
**Checklist**
> libva-intel-driver: add homepage

- packages/l/libpcre/abi_used_symbols
- packages/l/libpcre/abi_used_symbols32
- packages/l/libpcre/monitoring.yml
- packages/l/libpcre/package.yml
- packages/l/libpcre/pspec_x86_64.xml
**Summary**
- Changed the source mirror to direct source
**Test Plan**
**Checklist**
> libpcre: homepage, source mirror, monitoring

- packages/l/libpillowfight/monitoring.yml
- packages/l/libpillowfight/package.yml
- packages/l/libpillowfight/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libpillowfight: homepage, monitoring

- common/Scripts/appstream_ignored_packages.txt
**Summary**
add new programs to ignore list for appstream metadata
**Test Plan**
- Checked the file were modified.
**Checklist**
> add new programs to ignore list for appstream metadata

- packages/c/codelite/abi_used_symbols
- packages/c/codelite/files/org.codelite.codelite.metainfo.xml
- packages/c/codelite/monitoring.yml
- packages/c/codelite/package.yml
- packages/c/codelite/pspec_x86_64.xml
**Summary**
- Housekeeping
**Test Plan**
- Verified that the appstream metadata was correct.
**Checklist**
> codelite: housekeeping

- packages/g/github-cli/package.yml
- packages/g/github-cli/pspec_x86_64.xml
**Summary**
- [2.53.0](https://github.com/cli/cli/releases/tag/v2.53.0)
- [2.52.0](https://github.com/cli/cli/releases/tag/v2.52.0)
**Test Plan**
**Checklist**
> github-cli: Update to 2.53.0

- packages/g/gajim/package.yml
- packages/g/gajim/pspec_x86_64.xml
- packages/py/python-emoji/package.yml
- packages/py/python-emoji/pspec_x86_64.xml
- packages/py/python-nbxmpp/package.yml
- packages/py/python-nbxmpp/pspec_x86_64.xml
**Summary**
New
* Menu: Add main menu button
Improvements
* ChatFunctionPage: Show MUC address when displaying error
* SecurityLabels: Allow correction of labels
* Use different icon for context menu on contact list page
* Unify wording for 'Toggle Menu Bar'
* ConversationView: Use better method for scrolling to row
Change
* Raise nbxmpp version
Bug Fixes
* Reactions: Show timestamp in correct timezone
* Search: Don’t search messages of disabled accounts
* DebugConsole: Fix filtering stanzas when combining accounts and types
* VoiceMessageRecorderButton: Honor visibility setting on startup
* SecurityLabels: Fix merging messages with same security label
* ChatActionProcessor: Make handling selected action more robust
* Settings: Store account jid in dedicated setting
* Migration: Don’t …
> gajim: update to 1.9.1

- packages/w/waybar/abi_used_symbols
- packages/w/waybar/package.yml
- packages/w/waybar/pspec_x86_64.xml
**Summary**
Full release note: [0.10.4](https://github.com/Alexays/Waybar/releases/tag/0.10.4)
**Test Plan**
It was updated, and it loads the previous configuration with zero issues
**Checklist**
> waybar: update to 0.10.4

- packages/p/pdfsam/package.yml
- packages/p/pdfsam/pspec_x86_64.xml
**Summary**
add homepage to package.yml
**Test Plan**
Build package successfully.  Install new package.
Successfully extract pages from a PDF.  Successfully merged multiple PDFs into a single pdf.
**Checklist**
> pdfsam: add homepage

- packages/l/libpth/monitoring.yml
- packages/l/libpth/package.yml
- packages/l/libpth/pspec_x86_64.xml
**Summary**
- Fixed license to correct format and type
**Test Plan**
- Checked which license is specified in COPYING inside tarball
- Checked for CPE
**Checklist**
> libpth: homepage, license, build

- packages/l/libplist/abi_used_symbols
- packages/l/libplist/monitoring.yml
- packages/l/libplist/package.yml
- packages/l/libplist/pspec_x86_64.xml
**Summary**
**Test Plan**
**Checklist**
> libplist: homepage, monitoring

- packages/g/gtk-engines/abi_used_symbols
- packages/g/gtk-engines/package.yml
- packages/g/gtk-engines/pspec_x86_64.xml
**Summary**
- add homepage
- change configure macro
**Test Plan**
Ensure homepage tag is present in pspec
**Checklist**
> gtk-engines: add homepage

- packages/f/font-iosevka-ttf/package.yml
- packages/f/font-iosevka-ttf/pspec_x86_64.xml
**Summary**
- [changelog](https://raw.githubusercontent.com/be5invis/Iosevka/v30.3.3/CHANGELOG.md)
**Test Plan**
**Checklist**
> font-iosevka-ttf: Update to 30.3.3

- packages/t/tailscale/package.yml
- packages/t/tailscale/pspec_x86_64.xml
**Summary**
- [changelog](https://tailscale.com/changelog/#2024-07-17-client)
**Test Plan**
**Checklist**
> tailscale: Update to 1.70.0

- packages/l/libffi/package.yml
- packages/l/libffi/pspec_x86_64.xml
**Summary**
Adds homepage url to libffi
**Test Plan**
**Checklist**
> libffi: add homepage
